Implement ISDDNET server message to decouple version expectation from gametype
ddnet/ddnet pull request #1320
Opened 2018-10-02 19:22 UTC by timakro

This adds a new network message sent from the server to the client when a client connects. It tells the client that the server is a DDNet server and it is used in addition to the gametype to determine whether the server supports DDNet features. This can be used by server modifications e.g. Unique Race which support DDNet features but want to use a different gametype string.

2018-10-02 19:39 UTC, Learath2 commented
I was thinking something more along the lines of 005 in IRC (ISUPPORT) so we could have an extensible and bi-directional way of indicating support for features.

2018-10-02 19:41 UTC, timakro commented
Sounds good but can we Unique guys have this now? You can always replace it later.

2018-10-02 19:50 UTC, Learath2 approved these changes
Looks good to me codewise

2018-10-02 20:01 UTC, heinrich5991 commented
I think this should be a game message so it ends up in the client's demos.

2018-10-02 20:07 UTC, heinrich5991 commented
In fact, this should probably be sent after each map change, so that the game type can change dynamically.

2018-10-03 15:36 UTC, timakro commented
@heinrich5991 Explain to me, why would the gametype change with the map? I hope I changed it like you imagined.

2018-10-03 17:58 UTC, heinrich5991 commented
It's (/was) not uncommon to have different game types on the same server. While zoom is allowed for e.g. race, it should not be allowed for things like iCTF.

2018-10-03 18:49 UTC, heinrich5991 requested changes
Thanks for your PR. :)

I requested a couple of changes related to the possibility of changing the game type during a map change and some style issues.

2018-10-03 18:49 UTC, heinrich5991 commented on src/engine/client/client.cpp
> +			m_ServerVersion = Unpacker.GetInt();
Missing error handling.

2018-10-03 18:49 UTC, heinrich5991 commented on src/engine/server/server.cpp
> +				SendIsDDNet(ClientID);
Maybe put this into the `SendConnectionReady` function, before the `NETMSG_CON_READY` message. Then the client gets this at exactly the right time (and you don't miss a couple of `SendMap` calls.

2018-10-03 18:49 UTC, heinrich5991 commented on src/engine/client/client.cpp
> +	m_ServerVersion = VERSION_VANILLA;
I think this should be moved to the `CHANGE_MAP` message, so that it gets reset after every map change.

2018-10-03 18:49 UTC, heinrich5991 commented on src/engine/serverbrowser.h
> +	int m_ServerVersion;
This doesn't really belong into the server info struct. Maybe make a function on `IClient` that returns this version. :)

2018-10-03 22:05 UTC, timakro commented on src/engine/serverbrowser.h
> +	int m_ServerVersion;
That would mean writing an additional IsRace, IsDDRace, IsDDNet and Is64Player function and replacing it everywhere it is used. I considered other ways but came to the conclusion that this is the best solution.

2018-10-03 22:32 UTC, timakro commented on src/engine/serverbrowser.h
> +	int m_ServerVersion;
For my reasoning: While tedious you could double up all those functions (you need more than just IsDDNet because they call each other) with the original functions taking a server info object and the new functions accessing the current server info object and checking server version. But this is very similar functionality and results in more code (the functions calling each other e.g. IsDDRace using IsDDNet is really the problem here). I'd also argue that the server version fits quite well into the server info object. It's not connected to the server info network mechanism but it is meta information about the server and it is useful in the same context (as in this use case).

2018-10-03 22:33 UTC, heinrich5991 commented on src/engine/serverbrowser.h
> +	int m_ServerVersion;
Mh. This is certainly the solution with the least changes.

I don't particularly like it, because it reuses a struct for completely unrelated things… Perhaps one could create a new `CServerCapabilities` struct or so, containing the game type and this version number privately, returned from `IServer`, with member functions for `IsRace`, etc.? Just floating ideas around here…

Do you see why I don't like adding `m_ServerVersion` to `CServerInfo`?

2018-10-03 22:50 UTC, timakro commented on src/engine/serverbrowser.h
> +	int m_ServerVersion;
I see why you don't like it but I'm not changing it. This tends towards Learath2's idea of some kind of support indication system and honestly I don't want to invest that amount of work. Maybe it makes my current solution more acceptable to you: The struct also contains other variables that are not part of the actual server info but are used by the serverbrowser e.g. `m_QuickSearchHit`.

2018-10-04 13:38 UTC, Learath2 commented on src/engine/serverbrowser.h
> +	int m_ServerVersion;
I think I'm fine with this one as it's not really a long term change. Nor is it something we'd have to commit to. It's not like we are wasting precious space for new protocol messages anymore.

2018-10-04 13:46 UTC, heinrich5991 commented on src/engine/serverbrowser.h
> +	int m_ServerVersion;
"Temporary change" haha. :P That has always worked.

The problem I see is that someone has to clean up this mess which was just extended. I feel like I cleaned some stuff up already in some parts of the code, and so it's not completely out of question that I'll also clean up this part. I don't think we should make code less clean, because it will just waste our time in the future.

2018-10-04 13:56 UTC, heinrich5991 commented on src/engine/serverbrowser.h
> +	int m_ServerVersion;
(But hey, if you wanna merge it, do it.)

2019-01-14 11:14 UTC, def- commented
What's the status of this change?

2019-04-20 16:23 UTC, fokkonaut commented
Merge?

2019-04-22 07:57 UTC, Learath2 commented
I think this also belongs in the proposed gameinfo netobj

2019-04-22 10:05 UTC, fokkonaut commented
Yes

2019-05-15 07:22 UTC, timakro commented
Closing in favor of 9c3dafac9d96ee39ed90c2978adc0c5b31f54cdb.

2019-05-15 07:22 UTC, closed without merging