Add DDRace Score NETMSG
ddnet/ddnet pull request #1387
Opened 2018-11-24 13:56 UTC by fokkonaut

2019-01-05 17:07 UTC, fokkonaut commented
the server admin can edit sv_ddrace_score in his autoexec file. if its 1, it allows the client to use ddrace scoreboard, if its 0 it disallows it. this would work nicely with IsDDNet by timakro, to have a server with a custom gametype, ddrace features, but also the normal score (not ddrace score with times).
it can also be used to run mutliple gametypes on a single server without having weird time scores (need more editing serverside ofc).

with this addition we could also merge IsBlockWorlds and IsDDNet, then exec just have to add this message to tell the client that it has to use the normal score and not ddrace score.

here is an example of how we would use this feature:
https://github.com/DDNetPP/DDNetPP/pull/188

2019-01-05 17:22 UTC, heinrich5991 requested changes
Thank you for your updated pull request!

I think we should rename the feature a little, "DDRace score" doesn't quite capture what it does. The config variable seems a bit superfluous; it should be good enough if people can mod it (for blockworlds, DDRacePP, etc.).

If you need help with updating this pull request, ping me on Discord. :)

2019-01-06 23:08 UTC, fokkonaut commented on src/game/client/components/scoreboard.cpp
> +		if(m_IsGameTypeRace && g_Config.m_ClDDRaceScoreBoard && ((m_pClient->m_AllowDDRaceScore[0] && !g_Config.m_ClDummy) || (m_pClient->m_AllowDDRaceScore[1] && g_Config.m_ClDummy)))
i dont understand this one? there need to be 2 Independent ones, one for the dummy, one for the main tee. Just like this.

2019-01-06 23:09 UTC, fokkonaut commented on src/game/client/components/scoreboard.cpp
> +		if(m_IsGameTypeRace && g_Config.m_ClDDRaceScoreBoard && ((m_pClient->m_AllowDDRaceScore[0] && !g_Config.m_ClDummy) || (m_pClient->m_AllowDDRaceScore[1] && g_Config.m_ClDummy)))
i think i got it, thanks :)

2019-01-06 23:10 UTC, fokkonaut commented on src/engine/shared/protocol_ex_msgs.h
> +UUID(NETMSG_DDRACE_SCORE, "ddrace-score@ddnet.tw")
is `TIME_SCORE` ok?

2019-01-06 23:15 UTC, heinrich5991 commented on src/engine/shared/protocol_ex_msgs.h
> +UUID(NETMSG_DDRACE_SCORE, "ddrace-score@ddnet.tw")
Yes. :)

2019-01-11 22:20 UTC, heinrich5991 approved these changes

2019-01-11 22:21 UTC, heinrich5991 commented
Looks good to me. Sorry for the long waiting times.

bors r+

2019-01-11 22:33 UTC, fokkonaut commented
i added another commit because now blockworlds can add this netmsg and disallow time score using that.

2019-01-14 06:06 UTC, fokkonaut commented
can someone remove the last commit and merge it then, so from the state where heinrich wanted to merge it?

2019-01-14 07:01 UTC, def- commented
Done.

That's why you should use branches when doing a PR ;)

2019-01-14 07:09 UTC, def- commented
Done.

That's why you should use branches when doing a PR ;)

2019-01-14 07:09 UTC, closed without merging

2019-01-14 11:02 UTC, fokkonaut commented
thanks :)