Add autoban depending on client version
ddnet/ddnet pull request #1443
Opened 2019-02-04 19:49 UTC by ChillerDragon

``sv_bot_version_numbers`` takes a list of ddnet based bots version numbers (seperated by comma).
Set no punishment, kicks or bans up to 1024 minutes with ``sv_bot_punishment``.

2019-02-04 20:06 UTC, Learath2 requested changes
Couple small things

2019-02-04 20:06 UTC, Learath2 commented on src/game/server/gamecontext.cpp
> +bool CGameContext::isBotVersion(int Version)
Teeworlds uses Pascal Case for function and class names

2019-02-04 20:06 UTC, Learath2 commented on src/game/server/gamecontext.cpp
> +	char *p = strtok(aVersions, ";");;
Someone should probably implement a `str_tokenize` in system.c that's actually thread safe. But I guess this works for the time being.

2019-02-04 20:06 UTC, Learath2 commented on src/game/server/gamecontext.cpp
> +					str_format(aBuf, sizeof(aBuf), "kick %d bot client", ClientID);
I'd use `IServer::Kick` for this one instead of going through `IConsole`

2019-02-04 20:06 UTC, Learath2 commented on src/game/server/gamecontext.cpp
> +					str_format(aBuf, sizeof(aBuf), "ban %d %d %s", ClientID, g_Config.m_SvBotPunishment, "bot client");
Ditto above, add a `IServer::Ban` for this one.

2019-02-04 20:15 UTC, ChillerDragon commented on src/game/server/gamecontext.cpp
> +bool CGameContext::isBotVersion(int Version)
hehe y I did too much non tw coding latley ._.

2019-02-04 20:17 UTC, ChillerDragon commented
as @12pm said
> @ChillerDragon btw better make the list comma separated so you keep 1 style?

I personally think that commas look better and cleaner but @def- implemented something similar with commas so to be consitent it might make sens to only use commas or semicolons.

2019-02-04 21:43 UTC, Learath2 commented on src/game/server/gamecontext.cpp
> +					str_format(aBuf, sizeof(aBuf), "ban %d %d %s", ClientID, g_Config.m_SvBotPunishment, "bot client");
@ChillerDragon add this one as well and I'll merge :)

2019-02-04 21:45 UTC, Learath2 commented
Also agree with @12pm either change @def-'s to a semicolon, or change yours into a comma. The second would be easier.

2019-02-05 01:59 UTC, 12pm commented
I wouldn't use "bot" in the naming. Especially the kick messages shouldn't say "bot client", rather something along the lines of "unsupported client". It may be our current use case, but who knows, maybe we want to kick non-bot clients in the future too (for whatever reason). Then it would be better to have something more neutral :)

2019-02-05 07:11 UTC, ChillerDragon commented
@12pm i like configs but I think it is Overkill and not ddnet style here. So maybe if we use it we can change it when the time comes?

2019-02-05 09:13 UTC, heinrich5991 requested changes
I'm still skeptical of the change at all, but here are my comments if you do want to add it. :)

2019-02-05 09:13 UTC, heinrich5991 commented on src/engine/server.h
> +	virtual void Ban(int ClientID, int seconds, const char *pReason) = 0;
Naming style.

2019-02-05 09:13 UTC, heinrich5991 commented on src/engine/server/server.h
> +	void Ban(int ClientID, int seconds, const char *pReason);
Naming style.

2019-02-05 09:13 UTC, heinrich5991 commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_STR(SvBotVersionNumbers, sv_bot_version_numbers, 128, "", CFGFLAG_SERVER, "Comma seperated list of known bot clients to be punished by (sv_bot_punishment)")
separated

`sv_bot_versions` works as well and is shorter.

2019-02-05 09:13 UTC, heinrich5991 commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(SvBotPunishment, sv_bot_punishment, 0, 0, 1024, CFGFLAG_SERVER, "0=kick otherwise ban in minutes")
What's the point in banning? You can always join the next server of DDNet with the next bot client to check.

It'll be quickly enumerated anyway.

2019-02-05 09:13 UTC, heinrich5991 commented on src/game/server/gamecontext.cpp
> +	char *p = strtok(aVersions, ",");;
Can't use this function, not thread-safe. Double semicolon.

2019-02-05 09:13 UTC, heinrich5991 commented on src/game/server/gamecontext.cpp
> +	}
Perhaps this "in-comma-separated list" function could be factored out (I found it twice in the code base) and tested.

2019-02-05 10:47 UTC, Learath2 commented
@ChillerDragon I can factor out the tokenisation and in-comma-separated list if you don't want to or you can just give me highlight on discord if you get stuck with it.

2019-02-05 13:33 UTC, 12pm commented
> @12pm i like configs but I think it is Overkill and not ddnet style here. So maybe if we use it we can change it when the time comes?

Changing a couple names to neutral ones doesn't sound overkill to me. Better do it while you're at it so you don't have the hassle later.

2019-02-06 12:01 UTC, ChillerDragon commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_STR(SvBotVersionNumbers, sv_bot_version_numbers, 128, "", CFGFLAG_SERVER, "Comma seperated list of known bot clients to be punished by (sv_bot_punishment)")
Was my first idea but i thought mentioning that they can only be numbers could be helpfull. Since they are actually converted to a integer. But sure less typing and short stuff is always good I will change it.

2019-02-06 13:51 UTC, ChillerDragon commented
I removed the autoban feature but i kept the IServer::Ban function because I think it should be there anyways.

2019-02-07 00:19 UTC, 12pm approved these changes

2019-02-08 21:01 UTC, 12pm commented
You could make `sv_client_suggestion_bot` also take the bot versions from `sv_bot_versions`

2019-02-10 09:45 UTC, ChillerDragon commented
@12pm yes I thought about it. But maybe some bots are more suitable for a message and others for a kick. And maybe the kicking feature gets deactivated and you still want the message I don’t know.

But maybe add something like the bot punishment variable agian. And instead of choosing between kick and ban you could choose between kick and message. This could be used for depreciated ddnet clients with or clients with security vulnerabilities as well.

2019-02-11 17:56 UTC, Learath2 approved these changes

2019-02-12 10:34 UTC, fokkonaut commented
you shouldnt even allow those clients to join, otherwise they spam the chat.

2019-02-13 08:53 UTC, ChillerDragon commented
Thanks @Learath2 good point @fokkonaut.
Any other opinions on this? For me it sounds tricky becuase I don't know if the client sends his version number when he is already connected. But maybe we can look at the reconnecting spam detection agian if it isn't implemented already. This could at least detect the spam and hide the messages.

2019-02-13 10:34 UTC, heinrich5991 commented
I think this is a "good enough" approach so far.

2019-02-13 11:04 UTC, merged

2019-02-13 11:11 UTC, heinrich5991 reviewed
`str_in_list` contains a bug and a couple of other issues.

2019-02-13 14:00 UTC, Learath2 commented on src/base/system.c
> +int str_in_list(const char *list, const char *delim, const char *needle)
So only support comma seperated lists?