Rewrite of prediction code, with additional prediction (updated)
ddnet/ddnet pull request #1620
Opened 2019-04-11 01:19 UTC by trml

This is a reworked attempt at a rewrite of the prediction code (#464), to allow for more client side prediction. It doesn't fix the duplication of server code, but the client code should otherwise be cleaner. This includes separating prediction code out of gamecore/gameclient, and a refactor of the rendering of predicted characters.

There is also prediction for some new things, and some other changes:
- prediction of laser, shotgun, ninja, fng hammer, pickups and ddrace tiles (freeze/unfreeze tiles with cl_predict_freeze)
- laser and bullets are rendered when you fire them and bullets don't go through walls (when both cl_antiping_grenade and cl_antiping_weapons are enabled)
- antiping for flags
- prediction of dummy input
- an additional smoothing option that attempts to make antiping less jumpy (cl_antiping_smooth)

2019-04-11 01:24 UTC, fokkonaut commented
Could you add prediction for laser doors? That would be the only one missing for me :)

2019-04-11 03:27 UTC, trml commented
@fokkonaut It would require some more changes, but I was thinking about perhaps looking into it later.

2019-04-11 18:01 UTC, def- commented
Sounds pretty great, but quite a huge change, so difficult to tell if anything might break. If you rebase on current master gcc will out a warning:

    src/game/client/components/players.cpp:688:6: warning: this condition has identical branches [-Wduplicated-branches]

Maybe I should provide a nightly build for people to try this out?

2019-04-11 23:11 UTC, trml commented
I thought about that too, and having some more testing would be a good idea.

2019-04-12 06:36 UTC, def- commented
https://forum.ddnet.tw/viewtopic.php?f=3&t=6803

2019-04-12 12:16 UTC, fokkonaut commented
sure about cl_predict_freeze being enabled by default?

2019-04-12 12:27 UTC, fokkonaut commented
can you make dummy copy moves prediction? since its always exactly the same movement it could be predicted

2019-04-12 16:42 UTC, def- requested changes
Such a huge change.

2019-04-12 16:42 UTC, def- commented on src/base/vmath.h
> +	T &operator[](const int index) { return index ? y : x; }
that seems slightly hacky. -1, 2, 3 etc all count as 1. but ok.

2019-04-12 16:42 UTC, def- commented on src/engine/serverbrowser.h
> +bool IsBlockWorlds(const CServerInfo *pInfo);
is this related to your change?

2019-04-12 16:42 UTC, def- commented on src/engine/shared/serverbrowser.cpp
> +	    || IsBlockWorlds(pInfo))
I believe we removed this intentionally, why are you bringing it back?

2019-04-12 16:42 UTC, def- commented on src/game/client/components/items.cpp
> +										ReconstructSmokeTrail((const CNetObj_Projectile *)pData, Item.m_ID, pProj->m_DestroyTick, pProj->m_LifeSpan);
if if if if if if ifi fi fiif i fififiif
Please make it a big
```
if(x &&
  y &&
  z)
```

2019-04-12 16:42 UTC, def- commented on src/game/client/components/items.cpp
> +						continue;
likewise

2019-04-12 16:42 UTC, def- commented on src/game/client/gameclient.h
> +	CGameWorld m_GameWorld;
why are these public?

2019-04-12 16:42 UTC, def- commented on src/game/client/prediction/entities/projectile.h
> +//private:
no private?

2019-04-12 16:42 UTC, def- commented on src/game/client/prediction/entities/projectile.h
> +//private:
maybe you need to friend something, but please keep variables private. Also please put the entire public block together at the top

2019-04-12 21:45 UTC, trml commented on src/engine/shared/serverbrowser.cpp
> +	    || IsBlockWorlds(pInfo))
BW doesn't use tiles that are compatible with DDNet (for example their freeze tiles aren't used for freeze), and I added this so that prediction of ddrace tiles could be disabled on their servers. But perhaps adding this back isn't the right solution (it would be better if they fixed the tiles), so I could remove this.

2019-04-12 22:12 UTC, trml commented on src/base/vmath.h
> +	T &operator[](const int index) { return index ? y : x; }
Agree that it is hacky, but I couldn't immediately think of a non-hacky way to do it (that would also be safe, such as not using pointer arithmetic), since vec2 isn't implemented as arrays (and I didn't want to change the implementation). Could try to find a better way to do it. This operator also probably isn't required by most parts of the code, but some of the code in this pr would be slightly longer/more convoluted without it.

2019-04-12 23:46 UTC, trml commented
@fokkonaut not completely sure if it freeze pred should be enabled by default (guess it depends on how many who prefers it?), and I made it a separate setting in case someone preferred not to have it.

Dummy copy move should already work as well as prediction of dummy hammerfly, since the prediction reads the dummy input directly. However, the dummy is still unpredicted in solo parts (and this pr will currently not make a difference), since the client doesn't predict others when you are in solo.

2019-04-13 00:05 UTC, fokkonaut commented
copy moves doesnt work, hammerfly does.

2019-04-13 09:38 UTC, def- commented
Did you change anything with the mouse sensitivity btw?

2019-04-13 09:39 UTC, def- commented on src/engine/shared/serverbrowser.cpp
> +	    || IsBlockWorlds(pInfo))
ok

2019-04-13 22:02 UTC, trml commented
Nothing related to the mouse has been changed, and here are no changes in controls.cpp/input.cpp. The only other thing I think of are the changes in client.cpp. Also just realized I made a small change there related to how dummy input works, that would have been better to do in a different pr.

2019-04-13 23:51 UTC, trml commented on src/game/client/gameclient.h
> +	CGameWorld m_GameWorld;
The others could be made private (fixed it), but m_GameWorld (and similar) is used to access the predicted entities in CItems.

2019-04-14 19:59 UTC, def- approved these changes

2019-04-14 19:59 UTC, def- commented
I'm ok with merging this and then fixing stuff as we go since it seems to be a definitive improvement on our current state. Any other opinions?

2019-04-14 19:59 UTC, def- commented
I'm ok with merging this and then fixing stuff as we go since it seems to be a definitive improvement on our current state. Any other opinions?

2019-04-15 12:00 UTC, Learath2 commented
I think at least a couple more people should give this a try before we merge this in. People are pretty sensitive to these kinds of changes.

2019-04-15 12:34 UTC, PathosEthosLogos commented
@trml can you explain a bit on how `cl_antiping_smooth 1` works?

Amazing stuff by the way. I'm really looking forward to flag antiping. It was really needed in Pan American communities.

>prediction of laser, shotgun, ninja, fng hammer, pickups
This is possibly problematic for vanilla, correct? In vanilla, after picking up a weapon, the weapon disappears, whereas in DDRace, the weapon does not disappear. Is this possible to have it as an option instead?

Also, can you also predict the audio for the weapons so that they are synced as well?

2019-04-15 16:05 UTC, def- commented
https://github.com/ddnet/ddnet/issues/1630 is caused by this, please fix. To reproduce use a ruler move your mouse and measure how far it has to be moved to go from the top of the screen to the bottom.

2019-04-15 21:02 UTC, 12pm commented
can you improve super behaviour somehow? it's even worse than before now

2019-04-15 21:42 UTC, trml commented
@def- Couldn't reproduce it when I tried it now (although I don't have a very accurate mouse to test on at the moment, can try it again in a week). How noticable is the difference?

2019-04-15 21:43 UTC, def- commented
The mouse is about 20% slower on my system.

2019-04-19 21:13 UTC, trml commented
@12pm Super is tricky since the client currently doesn't know about it, so things like freeze is currently wrongly predicted with super. This could be solved with #1649 / #1650.

2019-04-20 16:26 UTC, fokkonaut commented
With the new DDNetCharacter NetObj its possible to predict this aswell.

2019-04-21 14:32 UTC, trml commented
@def- Does it happen with static camera? And with the latest rebase? With static camera the mosue position is taken more or less directly from SDL, so that would reduce the possible number of causes.

In an attempt to test it more accurately I lowered the mousesens to 5 but didn't see a difference (does that still reproduce it for you?).

2019-04-21 18:28 UTC, def- commented
Weird, now it is the same. Maybe I did something wrong before.

I think we should merge this in and keep improving it as we go.

2019-04-21 22:46 UTC, fokkonaut commented
👍🏼

2019-04-21 22:47 UTC, fokkonaut commented
Why did you put that m_Super check to everything? It is checked inside of Freeze() already

2019-04-22 07:45 UTC, def- commented
Sounds like another issue might be caused by this: https://github.com/ddnet/ddnet/issues/1657

2019-04-22 12:13 UTC, fokkonaut commented
@trml can you like not predict other players if you dont interact with them (by hook, walking against them, weapons)? That should help against the jumpyness of the other players

2019-04-22 17:45 UTC, trml commented
Perhaps I should split the dummy related things into a different pr? It isn't directly related to the rest.

2019-04-22 18:32 UTC, def- commented
Would be great if it's not too much work.

2019-04-22 23:25 UTC, trml commented
Ok, don't think it should.

2019-04-23 00:49 UTC, trml commented
@fokkonaut Determining who you interact with could be difficult in some cases. Do you mean by looking at past (recent) interactions?

2019-04-23 01:21 UTC, fokkonaut commented
I mean current interactions. If you just walk through the map or play gores then dont predict other players, then they dont jiggle. as soon as you touch, hammer, grenade, shotgun, hook or whatever them (->interact) then predict them

2019-04-23 17:01 UTC, def- commented
bors r+

2019-04-23 17:52 UTC, merged