Cl_text_entities_size
ddnet/ddnet pull request #1632
Opened 2019-04-13 01:57 UTC by BannZay

Allows to users to change size of overlay text entities

2019-04-13 06:55 UTC, Jupeyy commented
Could you please undo all changes in CMapImages.cpp.

It was on purpose designed to fit the text overlay into 1 tile, to drastically increase performance for all kind of overlay that uses text, when you use OpenGL 3.3

The text is already aligned to fit the tile

Also notice the FPS difference!!

OpenGL 3.3

![screenshot_2019-04-13_08-52-41](https://user-images.githubusercontent.com/6654924/56075884-d1223380-5dc9-11e9-97fd-2f71f01d3355.png)

OpenGL 2

![screenshot_2019-04-13_08-52-57](https://user-images.githubusercontent.com/6654924/56075886-d41d2400-5dc9-11e9-8770-748781c52d1d.png)

2019-04-13 10:40 UTC, fokkonaut commented
I am against this change

2019-04-13 11:09 UTC, BannZay commented
Just tested output for both 2.0 and 3.3 OpenGL before and after my commit. Still cant get your point, @Jupeyy  
Whats wrong?
There IS differences but they are pretty minor
OpenGL 3.3:
Before commit:
![3 3_before](https://user-images.githubusercontent.com/17499770/56078830-19a31680-5df5-11e9-92e6-69a691368ef7.png)
After:
![3 3_after](https://user-images.githubusercontent.com/17499770/56078831-19a31680-5df5-11e9-8b50-63b40a509d3b.png)

OpenGL 2.0
Before:
![2 0_before](https://user-images.githubusercontent.com/17499770/56078853-4a834b80-5df5-11e9-9ad2-e1968cf1abe6.png)
After:
![2 0_after](https://user-images.githubusercontent.com/17499770/56078852-49eab500-5df5-11e9-8df6-eb3b9a05cc5e.png)

> The text is already aligned to fit the tile
What if someone has a 27 inches monitor where text looks ugly being so big as tile?
There is cl_text_entities_size coming in

2019-04-13 11:12 UTC, Jupeyy commented
because your merge conflict redone the old behaivour, not because your code is working

2019-04-13 11:22 UTC, BannZay commented
> because your merge conflict redone the old behaivour, not because your code is working

Damn, failed to merge. I will fix soon

2019-04-13 11:27 UTC, fokkonaut commented
> What if someone has a 27 inches monitor where text looks ugly being so big as tile?
> There is cl_text_entities_size coming in

if someone has a screen that big, he would use zoom- multiple times (i use it once and i have a 22 inch monitor) so the tiles are smaller again.

2019-04-13 11:34 UTC, BannZay commented
I just want to have a solution for my problem, and zooming out didnt helped me. 
And there I am.
Anyway, whats bad in possibility to configure text size, especially if user wants this.

2019-04-13 12:24 UTC, fokkonaut commented
Because its automatically set to fit the box of the tile

2019-04-13 13:28 UTC, BannZay commented
> Because its automatically set to fit the box of the tile

No changes at all with default value for OpenGL 3.3. Check out screenshots

2019-04-15 18:48 UTC, Learath2 requested changes
Looks good except for a couple style issues.

Also maybe we should make this setting between 0 and 100, 0 and 64 isn't really intuitive, but again, not really important.

2019-04-15 18:48 UTC, Learath2 commented on src/game/client/render_map.cpp
> +	float size = g_Config.m_ClTextEntitiesSize / 64.f;
```suggestion
	float Size = g_Config.m_ClTextEntitiesSize / 64.f;
```
Style

2019-04-15 18:48 UTC, Learath2 commented on src/game/client/render_map.cpp
> +				UI()->TextRender()->Text(0, mx*Scale - 3.f, my*Scale, size * Scale, aBuf, -1);
```suggestion
				UI()->TextRender()->Text(0, mx*Scale - 3.f, my*Scale, Size * Scale, aBuf, -1);
```
^^

2019-04-15 18:48 UTC, Learath2 commented on src/game/client/render_map.cpp
> +	float size = g_Config.m_ClTextEntitiesSize / 64.f;
```suggestion
	float Size = g_Config.m_ClTextEntitiesSize / 64.f;
```
Style

2019-04-15 18:48 UTC, Learath2 commented on src/game/client/render_map.cpp
> +	float size = g_Config.m_ClTextEntitiesSize / 64.f;
```suggestion
	float Size = g_Config.m_ClTextEntitiesSize / 64.f;
```
Style

2019-04-15 18:48 UTC, Learath2 commented on src/game/client/render_map.cpp
> +	float size = g_Config.m_ClTextEntitiesSize * Scale / 64.f;
```suggestion
	float Size = g_Config.m_ClTextEntitiesSize * Scale / 64.f;
```
Style

2019-04-15 18:48 UTC, Learath2 commented on src/game/client/components/mapimages.cpp
> +	if (m_TextureSize == Size)
```suggestion
	if(m_TextureSize == Size)
```
Style

2019-04-15 18:48 UTC, Learath2 commented on src/game/client/gameclient.cpp
> +void CGameClient::ConchainClTextEntitiesSize(IConsole::IResult *pResult, void *pUserData, IConsole::FCommandCallback pfnCallback, void *pCallbackUserData)
Clean this up, should take about 3 lines, 5 if you are being strict with style.

2019-04-15 18:48 UTC, Learath2 commented on src/game/client/gameclient.cpp
> +	if (pResult->NumArguments())
```suggestion
	if(pResult->NumArguments())
```
Style

2019-04-15 18:48 UTC, Learath2 commented on src/game/client/components/mapimages.cpp
> +	if (Graphics()) // check if component was initialized
```suggestion
	if(Graphics()) // check if component was initialized
```
Style

I think you should/could also check `m_OverlayBottomTexture == -1`

2019-04-15 18:48 UTC, Learath2 commented on src/game/client/components/mapimages.cpp
> +int CMapImages::TextureSize()
This could be in the header file

2019-04-15 18:48 UTC, Learath2 commented on src/game/client/components/mapimages.h
> +	int TextureSize();
I'm not really sure if it's a good idea to name these as the same, but not really important.

2019-04-15 21:05 UTC, 12pm commented
probably better to have the config in %?

2019-04-17 19:02 UTC, BannZay commented on src/game/client/gameclient.cpp
> +void CGameClient::ConchainClTextEntitiesSize(IConsole::IResult *pResult, void *pUserData, IConsole::FCommandCallback pfnCallback, void *pCallbackUserData)
Just followed code around style it will looks unnatural if it will be done

2019-04-17 19:07 UTC, BannZay commented
Fixed code styles issues. Completely agree setting should be as percent so made it as percent also

2019-04-17 20:24 UTC, BannZay commented on src/game/client/components/mapimages.cpp
> +int CMapImages::TextureSize()
So getter will be in header and setter not ? If it is okay I can do it.

2019-04-18 12:04 UTC, Learath2 commented on src/game/client/gameclient.cpp
> +void CGameClient::ConchainClTextEntitiesSize(IConsole::IResult *pResult, void *pUserData, IConsole::FCommandCallback pfnCallback, void *pCallbackUserData)
I meant the entire function, it's all messy, has an unneeded block there, a commented out if statement.

2019-04-18 12:06 UTC, Learath2 commented on src/game/client/components/mapimages.cpp
> +int CMapImages::TextureSize()
I'd call the setter `SetTextureSize` and move the getter to the header

2019-04-18 18:12 UTC, BannZay commented on src/game/client/gameclient.cpp
> +void CGameClient::ConchainClTextEntitiesSize(IConsole::IResult *pResult, void *pUserData, IConsole::FCommandCallback pfnCallback, void *pCallbackUserData)
I see, my bad, sorry. Didnt realized that I changed code before reading this comment. Anyway, it should looks good now

2019-04-18 18:20 UTC, BannZay commented on src/game/client/components/mapimages.cpp
> +int CMapImages::TextureSize()
I am worried about that many commits already here. I will do it when something else is need to be changed

2019-04-20 16:28 UTC, fokkonaut commented
So the default value is 100 and it cant get bigger than it is right now, correct? If yes the rest looks done.

2019-04-20 18:27 UTC, BannZay commented
@fokkonaut, yes. 100 - is default and maximum value for this setting. With 100 it will looks the same as now

2019-04-20 19:00 UTC, fokkonaut commented
Okay, good. This looks done

2019-04-22 10:34 UTC, VxMiMxV commented
Just wanted to say that i'd love to have this.
Also:
![Screen 1698](https://user-images.githubusercontent.com/47721445/56496680-abe4a200-64fa-11e9-99d0-5b2104853201.png)
I hope the single digit numbers will be centered like this (4 is unedited)
And yes, some numbers stick out like this 4 for me personally.

2019-04-22 11:20 UTC, BannZay commented
@VxMiMxV, I believe you`ve posted screenshot with modified tileset (btw, I do use similar). With original one the number will overlap with text "FROM" so there is some questions like "should we lift it up to prevent overlapping?". It is responsibility for another setting like "overlay_text_centered or better overlay_text_x/overlay_text_y" tho.

This one setting is first stem of such custumization.

 I would love to continue working and discussing it with support of people who could make such decisions. Because doing big change may open such many questions so this PR will never succeed

2019-04-23 14:31 UTC, def- commented
@Jupeyy Is this ok from your side now?

2019-04-23 15:03 UTC, Jupeyy commented
Mh not 100% happy tbh.
The speedups text is now always 50%(at 100% setting) of the tile, which is pretty huge, the value before was 20
so 20 / 64 around 31% of the tile

also the y offset for the bottom overlay isn't calculated properly if you use smaller value. it has to stick to the bottom of the tile not to the mid of the tile.

And last, what @Learath2 said, please name the getter and setter properly, else the code gets just more messy to read

2019-04-23 17:09 UTC, BannZay commented
> speedups text is now always 50%

I just dropped all the magic instead of figuring out what the hell is going on here. Once I realized it is fine I just left it unless I dont have any requirements how this should work.

P.s.: it will be nice if some one could rewrite whole functionality from the scratch and this PR will be turned to POC

2019-04-23 17:40 UTC, Jupeyy commented
its totally fine and useful commit, pls don't give up:

imagine the whole mapimages thing like this. all the game tile attributes have a range of 0-255(like speed, or tele outcome)
and teeworlds map layers are also 256 possiblities, that made it easy to overlap tiles with the text.
the magic is just that it pre renders all the text into textures, so at runtime it doesnt need CPU nor GPU workload.

It must fit 1 tile, because, then it can be querried just like a game tile would.

Here are images, that probably explain what happens

![image](https://user-images.githubusercontent.com/6654924/56603041-1f6fd780-65ff-11e9-9f38-f9e314a51db6.png)

![image](https://user-images.githubusercontent.com/6654924/56603066-30b8e400-65ff-11e9-9792-4261f7179247.png)

![image](https://user-images.githubusercontent.com/6654924/56603093-3c0c0f80-65ff-11e9-9da1-568b700fba89.png)


You do everything right, i just thought would be neat to actually fit stuff correctly, a tile on these textures is 64 pixel, so if you use a font size of 20, you could just do 64 - 20, that would make the text appear on the bottom of the tile.

Also nothing is wrong with many commits as you said somewhere. it's totally fine :)

2019-04-23 21:18 UTC, BannZay commented
I will fix everything asked above. Just one question - it will be fine if text vertically aligned to the center of it 32 pixel area?

2019-04-23 21:46 UTC, Jupeyy commented
well alignment is something that could be improved for sure(also horizontal, bcs small letters are on the left not centered anymore), but i guess its ok for now, since the standard value atleast looks good then.

But if you want to work on this sure, go ahead ;D

2019-05-02 20:59 UTC, BannZay commented
**Before:**
![before](https://user-images.githubusercontent.com/17499770/57106499-31a3f100-6d36-11e9-9b0d-4dbc4b14e7c7.png)
**Now:**
![now](https://user-images.githubusercontent.com/17499770/57106497-31a3f100-6d36-11e9-8eb2-9314a1fabb14.png)

2019-05-03 14:38 UTC, Jupeyy commented
i just let the mantainers decide, if they are ok, its ok

2019-05-03 18:25 UTC, Learath2 requested changes
A lot of style nits, other then that, if we agree this is the best way to size them then it LGTM afterwards.

2019-05-03 18:25 UTC, Learath2 commented on src/engine/client/text.cpp
> +		{
Could you please cleanup the trailing spaces?

2019-05-03 18:25 UTC, Learath2 commented on src/engine/client/text.cpp
> +		CFont* pFont = m_pDefaultFont;
```suggestion
		CFont *pFont = m_pDefaultFont;
```
We put the * with the label.

2019-05-03 18:25 UTC, Learath2 commented on src/engine/client/text.cpp
> +			if (NextCharacter)
```suggestion
			if(NextCharacter)
```

No space after control keywords

2019-05-03 18:25 UTC, Learath2 commented on src/engine/client/text.cpp
> +				if (FT_Load_Char(pFont->m_FtFace, NextCharacter, FTFlags))
```suggestion
				if(FT_Load_Char(pFont->m_FtFace, NextCharacter, FTFlags))
```
^^

2019-05-03 18:25 UTC, Learath2 commented on src/engine/textrender.h
> +	virtual void UploadEntityLayerText(int TextureID, const char* pText, int Length, float x, float y, int FontHeight) = 0;
```suggestion
	virtual void UploadEntityLayerText(int TextureID, const char *pText, int Length, float x, float y, int FontHeight) = 0;
```
^^

2019-05-03 18:25 UTC, Learath2 commented on src/game/client/components/mapimages.cpp
> +	if (m_TextureScale == Scale)
```suggestion
	if(m_TextureScale == Scale)
```
^^

2019-05-03 18:25 UTC, Learath2 commented on src/game/client/components/mapimages.cpp
> +	void* pMem = calloc(1024 * 1024, 1);
```suggestion
	void *pMem = calloc(1024 * 1024, 1);
```
^^

2019-05-03 18:25 UTC, Learath2 commented on src/game/client/components/mapimages.cpp
> +	for (int i = 0; i < 256; ++i)
```suggestion
	for(int i = 0; i < 256; ++i)
```
^^

2019-05-03 18:25 UTC, Learath2 commented on src/game/client/components/mapimages.cpp
> +	char buff[4];
```suggestion
	char aBuf[4];
```
Naming

2019-05-03 18:25 UTC, Learath2 commented on src/game/client/components/mapimages.cpp
> +		str_format(buff, 4, "%d", i);
```suggestion
		int Len = str_format(aBuf, 4, "%d", i);
```
^^ VV

2019-05-03 18:25 UTC, Learath2 commented on src/game/client/components/mapimages.cpp
> +		int len = str_length(buff);
```suggestion

```
`str_format` already returns the length of the string written.

2019-05-03 18:25 UTC, Learath2 commented on src/game/client/components/mapimages.cpp
> +	str_format(buff, 4, "%d", 255);
```suggestion
	int Len = str_format(aBuf, 4, "%d", 255);
```
^^VV

2019-05-03 18:25 UTC, Learath2 commented on src/game/client/components/mapimages.cpp
> +	int len = str_length(buff);
```suggestion

```
VV

2019-05-03 18:25 UTC, Learath2 commented on src/game/client/components/mapimages.cpp
> +}
```suggestion
}

```
You should configure your editor to make sure it adds a newline at EOF.

2019-05-03 18:25 UTC, Learath2 commented on src/game/client/render_map.cpp
> +	float size = g_Config.m_ClTextEntitiesSize/100.f;
```suggestion
	float Size = g_Config.m_ClTextEntitiesSize/100.f;
```
Naming

2019-05-03 18:25 UTC, Learath2 commented on src/game/client/components/mapimages.cpp
> +		TextRender()->UploadEntityLayerText(TextureID, buff, len, x, y + YOffset, FontSize);
```suggestion
		TextRender()->UploadEntityLayerText(TextureID, aBuf, Len, x, y + YOffset, FontSize);
```
^^

2019-05-03 18:25 UTC, Learath2 commented on src/game/client/render_map.cpp
> +	float toCenterOffset = (1-size)/2.f;
```suggestion
	float ToCenterOffset = (1-size)/2.f;
```
^^

2019-05-03 18:25 UTC, Learath2 commented on src/game/client/render_map.cpp
> +				UI()->TextRender()->Text(0, mx*Scale - 3.f, (my+toCenterOffset)*Scale, size*Scale, aBuf, -1);
```suggestion
				UI()->TextRender()->Text(0, mx*Scale - 3.f, (my+ToCenterOffset)*Scale, Size*Scale, aBuf, -1);
```
^^

2019-05-03 18:25 UTC, Learath2 commented on src/game/client/render_map.cpp
> +	float size = g_Config.m_ClTextEntitiesSize / 100.f;
Naming as above, also for lines below, too many to mark :P

2019-05-05 16:33 UTC, Learath2 requested changes
There are still more of these, You really should configure your editor.

Also please capitalize `toCenterOffset` properly for all instances.

2019-05-05 16:33 UTC, Learath2 commented on src/engine/client/text.cpp
> +		const char* pCurrent = (char*)pText;
```suggestion
		const char  pCurrent = (char *)pText;
```

2019-05-05 16:33 UTC, Learath2 commented on src/engine/client/text.cpp
> +		const char* pEnd = pCurrent + Length;
```suggestion
		const char *pEnd = pCurrent + Length;
```

2019-05-05 16:33 UTC, Learath2 commented on src/engine/client/text.cpp
> +		CFont* pFont = m_pDefaultFont;
```suggestion
		CFont *pFont = m_pDefaultFont;
```

2019-05-05 16:33 UTC, Learath2 commented on src/engine/client/text.cpp
> +		FT_Bitmap* pBitmap;
```suggestion
		FT_Bitmap *pBitmap;
```

2019-05-05 16:33 UTC, Learath2 commented on src/engine/client/text.cpp
> +
Can't suggest this one but trailing spaces

2019-05-05 16:33 UTC, Learath2 commented on src/engine/client/text.cpp
> +	virtual int AdjustFontSize(const char* pText, int TextLength, int MaxSize = -1)
```suggestion
	virtual int AdjustFontSize(const char *pText, int TextLength, int MaxSize = -1)
```

2019-05-05 16:33 UTC, Learath2 commented on src/engine/client/text.cpp
> +	virtual int CalculateTextWidth(const char* pText, int TextLength, int FontWidth, int FontHeight)
```suggestion
	virtual int CalculateTextWidth(const char *pText, int TextLength, int FontWidth, int FontHeight)
```

2019-05-05 16:33 UTC, Learath2 commented on src/engine/client/text.cpp
> +		const char* pCurrent = (char*)pText;
```suggestion
		const char *pCurrent = (char *)pText;
```

2019-05-05 16:33 UTC, Learath2 commented on src/engine/client/text.cpp
> +		const char* pEnd = pCurrent + TextLength;
```suggestion
		const char *pEnd = pCurrent + TextLength;
```

2019-05-05 16:33 UTC, Learath2 commented on src/engine/client/text.cpp
> +			const char* pTmp = pCurrent;
```suggestion
			const char *pTmp = pCurrent;
```

2019-05-05 16:33 UTC, Learath2 commented on src/engine/textrender.h
> +	virtual int AdjustFontSize(const char* pText, int TextLength, int MaxSize = -1) = 0;
```suggestion
	virtual int AdjustFontSize(const char *pText, int TextLength, int MaxSize = -1) = 0;
```

2019-05-05 16:33 UTC, Learath2 commented on src/game/client/gameclient.cpp
> +		CGameClient* GameClient = (CGameClient*)pUserData;
```suggestion
		CGameClient *pGameClient = (CGameClient*)pUserData;
```

2019-05-05 16:33 UTC, Learath2 commented on src/game/client/gameclient.cpp
> +		GameClient->m_pMapimages->SetTextureScale(g_Config.m_ClTextEntitiesSize);
```suggestion
		pGameClient->m_pMapimages->SetTextureScale(g_Config.m_ClTextEntitiesSize);
```

2019-05-05 16:33 UTC, Learath2 commented on src/game/client/gameclient.cpp
> +
```suggestion

```

2019-05-05 16:33 UTC, Learath2 commented on src/game/client/gameclient.h
> +	static void ConchainClTextEntitiesSize(IConsole::IResult * pResult, void * pUserData, IConsole::FCommandCallback pfnCallback, void * pCallbackUserData);
```suggestion
	static void ConchainClTextEntitiesSize(IConsole::IResult *pResult, void *pUserData, IConsole::FCommandCallback pfnCallback, void *pCallbackUserData);
```

2019-05-05 19:41 UTC, BannZay commented
> You really should configure your editor

I want it to but can not find anything about how to do it. Furtermore, I could not even find DDNet code style convention. For example toCenterOffset is local variable and even in Teeworlds code convention nothing about local variables.

Maybe there is nothing special for you who work with DDNet long enough, but for me, who dont even code in C++ it is challenge. It just not worth it. I have to analyze some amount of code to configure whole code style to contribute a little thing.

I use Visual Studio 2019. There is [thing](https://devblogs.microsoft.com/dotnet/code-style-configuration-in-the-vs2017-rc-update/) what probably can solve it. So newcomers can easily use it

2019-05-05 19:44 UTC, BannZay commented
Everything I said before is not excuse, just wanted to let you know about problem I face working on this. And everything you reported I will fix

2019-05-06 10:29 UTC, def- commented
@Learath2 can we squash and merge?

2019-05-06 12:19 UTC, merged