Remove all checking for the gametype in the game
ddnet/ddnet pull request #1772
Opened 2019-06-03 19:56 UTC by heinrich5991

OK, maybe not actually remove because it is kept for fallback when the
new method isn't available.

The whole gametype parsing business had the same downsides as user agent
parsing on the web, hence I removed it while keeping behavior the same.

This allows servers to explicitly opt in or out of certain bug
workarounds and other client behavior. This increases the complexity of
different configurations that are available in the client (which is a
bad thing).

2019-06-03 21:20 UTC, Learath2 commented on datasrc/network.py
> +GameInfoFlags = ["TIMESCORE", "GAMETYPE_RACE", "GAMETYPE_FASTCAP", "GAMETYPE_FNG", "GAMETYPE_DDRACE", "GAMETYPE_DDNET", "GAMETYPE_BLOCK_WORLDS", "GAMETYPE_VANILLA", "GAMETYPE_PLUS", "FLAG_STARTS_RACE
multilinepls

2019-06-04 22:46 UTC, fokkonaut commented on datasrc/network.py
> +	NetObjectEx("GameInfoEx", "gameinfo@netobj.ddnet.tw", [
DDNetGameInfo was a good name, it matches the DDNetPlayer and DDNetCharacter.

2019-06-04 22:46 UTC, heinrich5991 commented on src/game/server/gamecontroller.cpp
> +		| GAMEINFOFLAG_ENTITIES_RACE;
This was meant as "it's useful to display the entities as DDNet, DDRace, or Race, use the most sophisticated one you have".

2019-06-04 22:57 UTC, heinrich5991 commented on datasrc/network.py
> +	NetObjectEx("GameInfoEx", "gameinfo@netobj.ddnet.tw", [
I don't want this solely for DDNet though, but rather also for Race game types, etc.

2019-06-04 23:02 UTC, heinrich5991 commented
Still need to fix that the smaller gameinfo object is simply dropped by the network code.

2019-06-12 09:39 UTC, def- commented
@heinrich5991 Ran into a conflict. Should I rebase and submit?

2019-06-13 21:13 UTC, Learath2 requested changes
Most of these are things that I want to ask rather then actual problems.

2019-06-13 21:13 UTC, Learath2 commented on src/game/client/components/mapimages.h
> +	const char *m_pEntitiesGameType;
How safe is this? You are assigning a pointer to a string literal to they have static storage duration like in C?

2019-06-13 21:13 UTC, Learath2 commented on src/game/client/gameclient.cpp
> +	else if(InfoExSize >= 8)
This condition is useless as the one above gets executed `\forall InfoExSize >= 4`

2019-06-13 21:13 UTC, Learath2 commented on src/game/client/gameclient.cpp
> +	bool Race = IsRace(pFallbackServerInfo);
Small nit, these are all string comparisons that if we have `Version => 1` will go to waste.

2019-06-13 21:13 UTC, Learath2 commented on src/game/client/gameclient.cpp
> +static CGameInfo GetGameInfo(const CNetObj_GameInfoEx *pInfoEx, int InfoExSize, CServerInfo *pFallbackServerInfo)
What is the Fallback really for? Maybe you should have two `GetGameInfo`s, one `static CGameInfo GetGameInfo(const CNetObj_GameInfoEx *pInfoEx, int InfoExSize);` and one `static CGameInfo GetGameInfo(CServerInfo *pFallbackServerInfo);`

Also why is the size of the info object needed?

2019-06-13 21:13 UTC, Learath2 commented on src/game/client/gameclient.h
> +		const CNetObj_GameInfoEx *m_pGameInfoEx;
This isn't needed anymore.

2019-06-13 22:30 UTC, heinrich5991 commented on src/engine/client/client.cpp
> +			m_ServerSentCapabilities = true;
Renamed.

2019-06-13 22:30 UTC, heinrich5991 commented on src/game/client/components/mapimages.h
> +	const char *m_pEntitiesGameType;
Yes, this is safe because we only assign static string literals.

2019-06-13 22:40 UTC, Learath2 approved these changes
LGTM

2019-06-13 22:43 UTC, Learath2 commented
bors r+

2019-06-13 22:56 UTC, merged