Add afk marks
ddnet/ddnet pull request #1821
Opened 2019-07-13 11:00 UTC by ardadem

This is final state  (and most minimalist to not create mess) of my previous pull request. I didn't reopen it because it's contains changed unnecessary commits.

If someone will become afk, mark will be spawn next to tee's name.
![2019-07-13-13:59:20-screenshot](https://user-images.githubusercontent.com/13207692/61170739-8c4b9b80-a576-11e9-9d87-4c4b2f93941b.png)

2019-07-13 11:12 UTC, bojidar-bg commented
Would this tag dummies as AFK on dummy maps? I think the AFK mark might be distracting for the player.

2019-07-13 11:14 UTC, ardadem commented
It's optional, u can set cl_afk_mark to 0.

2019-07-13 12:20 UTC, fokkonaut commented
I liked the colored names version more.

2019-07-13 12:25 UTC, ardadem commented
Well we have `cl_afk_mark_color` option too, you can use more highlighted color. Or we can set different mark for this.

2019-07-13 16:05 UTC, fokkonaut commented
I think this should be a flag, not a NetBool.

2019-07-13 16:43 UTC, Learath2 commented
Yeah a flag would be more appropriate.

On Sat, Jul 13, 2019, 19:05 fokkonaut <notifications@github.com> wrote:

> I think this should be a flag, not a NetBool.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ddnet/ddnet/pull/1821?email_source=notifications&email_token=AADXYBG4PO6HAMNENKTBB43P7H4L7A5CNFSM4IC25M22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ3UOFI#issuecomment-511133461>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AADXYBHSQ53224SIB3A3MFLP7H4L7ANCNFSM4IC25M2Q>
> .
>

2019-07-13 19:45 UTC, heinrich5991 commented
This only seems to work if you have enabled nameplates, not if you only show them near the cursor or not at all.

2019-07-13 19:57 UTC, ardadem commented
Yes, it's works only if you have enabled nameplates.

2019-07-19 16:50 UTC, Learath2 requested changes
A couple small nits, after that it looks ready to merge for me.

2019-07-19 16:50 UTC, Learath2 commented on datasrc/network.py
> +                NetBool("m_Afk"),
Move this inside `m_Flags`

2019-07-19 16:50 UTC, Learath2 commented on src/game/client/components/nameplates.cpp
> +			const char *afkMark = "!";
```suggestion
			const char *AfkMark = "!";
```
We don't do camelCase

2019-07-19 16:50 UTC, Learath2 commented on src/game/client/components/nameplates.cpp
> +		ColorRGBA rgbAfkM = color_cast<ColorRGBA>(ColorHSLA(g_Config.m_ClAfkMarkColor));
```suggestion
		ColorRGBA RgbAfkM = color_cast<ColorRGBA>(ColorHSLA(g_Config.m_ClAfkMarkColor));
```
Proper casing and maybe a better name for it.

2019-07-26 08:55 UTC, ardadem commented
What about now?

2019-07-26 08:58 UTC, def- commented
bors r+
Thanks!

2019-07-26 09:09 UTC, ardadem commented
@def- This pull request doesn't include paused ones. You removed eye blink function but now we can't see who is paused or playing.

2019-07-26 09:11 UTC, merged

2019-07-26 09:43 UTC, Learath2 commented
Also create a new flags array for the extended flags, as like this you are
wasting flagspace in DDNetPlayer.

bors r-

On Fri, Jul 26, 2019, 12:09 Arda Demir <notifications@github.com> wrote:

> @def- <https://github.com/def-> This pull request doesn't include paused
> ones. You removed eye blink function but now we can't see who is paused or
> playing.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ddnet/ddnet/pull/1821?email_source=notifications&email_token=AADXYBA4TW6W25ZONHOGM6DQBK5N7A5CNFSM4IC25M22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD237RYQ#issuecomment-515373282>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AADXYBAP6S4SWRAH73RXYELQBK5N7ANCNFSM4IC25M2Q>
> .
>

2019-07-26 11:44 UTC, 12pm commented
> @def- This pull request doesn't include paused ones. You removed eye blink function but now we can't see who is paused or playing.

Why doesn’t it include paused tees? It’s effectively the same as being afk (you’re unable to react)

2019-07-26 12:05 UTC, ardadem commented
It would be messy otherwise

2019-07-26 12:14 UTC, 12pm commented
But what's the purpose of this feature then if it doesn't fix the "bug" of being able to set afk eyes yourself?