BlockWorlds Entities
ddnet/ddnet pull request #2195
Opened 2020-05-19 14:51 UTC by MikiGamer

2020-05-19 15:00 UTC, heinrich5991 requested changes
Thanks for your first pull request. :)

It still needs some changes to maintain backward compatibility. Ping me on Discord (heinrich5991#9827) if you need help with the comments I left.

2020-05-19 15:00 UTC, heinrich5991 commented on datasrc/network.py
> +	"ENTITIES_VANILLA", "ENTITIES_BW", "DONT_MASK_ENTITIES",
This needs to go at the end.

2020-05-19 15:00 UTC, heinrich5991 commented on src/game/client/components/mapimages.cpp
> +		pEntities = "blockworlds";
Can you move this up over FNG?

2020-05-19 15:00 UTC, heinrich5991 commented on src/game/client/gameclient.cpp
> +		Info.m_EntitiesBW = Flags&GAMEINFOFLAG_ENTITIES_BW;
You need to create a new version for this, and put it into an `if` block:
```
if(Version >= 4)
{
	Info.m_EntitiesBW = Flags&GAMEINFOFLAG_ENTITIES_BW;
}
```

The server also needs to be updated to send version 4.

2020-05-20 13:23 UTC, heinrich5991 commented
Oh, sorry, missed the update.

You still need to update the version number the server sends in its `CNetObj_GameInfoEx`.

2020-05-20 20:36 UTC, heinrich5991 approved these changes
Thanks a lot. :)

bors r+

2020-05-20 20:43 UTC, merged

2020-05-20 21:59 UTC, fokkonaut commented
Why did you merge this? The entities_clear are not good for ingame playing, and BW has multiple layers (you can add unlimited front layer like layers). This should be reverted

2020-05-21 00:05 UTC, fokkonaut commented
@heinrich5991

2020-05-21 17:46 UTC, heinrich5991 commented
> Why did you merge this?

In case this was not a rhetorical question: Because having entities seemed like a better option than not having them.

2020-05-21 19:41 UTC, fokkonaut commented
But they are not working properly because as I said BW has multiple front layers