Implement /enablerescue for teams
ddnet/ddnet pull request #2204
Opened 2020-05-22 22:01 UTC by def-

As discussed on Discord today, can be enabled inside of teams on the fly
during each run on any server. Finishes don't count. I haven't tested
save/load yet, would do that live on the server if this can be merged.

2020-05-22 22:15 UTC, Learath2 commented
Maybe give this a more generic name so we can have other practice features too if we ever get any consensus on it?

2020-05-22 22:16 UTC, d3fault commented
lgtm but I would just implicitly enable "rescue mode" (aka non-ranking-mode) on the first use of /r. not a huge deal but requires less effort (maybe more likely to be used 'accidentally' this way? however *either* way a bind could be pressed 'accidentally', ruining your precious r1)

I would also change the wording a bit:
>you can't finish the map with rescue turned on.

becomes:
>you can't earn a rank with rescue turned on.

or:
>you can't earn a rank after you've used /r.

And maybe give a message when crossing the finish line: "Good job. Now do it without cheating!"

2020-05-22 22:36 UTC, fokkonaut commented
isnt /rescue used for the actual rescue like /r? i think enablerescue is pretty good

2020-05-22 22:58 UTC, d3fault commented
I can't tell from skimming the code if this is already the case, but when the last player leaves the team "enable rescue" mode should then be turned off. Similar to how a /lock'd team becomes unlocked when the last player leaves (and the code to do this could probably go right next to that /unlocking code).

2020-05-23 07:43 UTC, def- commented
> I can't tell from skimming the code if this is already the case, but when the last player leaves the team "enable rescue" mode should then be turned off.

Yes, done and tested that it works.

> isnt /rescue used for the actual rescue like /r?

Yes

> lgtm but I would just implicitly enable "rescue mode" (aka non-ranking-mode) on the first use of /r

I'm strongly against this since some players will have a bind for /r and if they accidentally press it their team can't finish anymore. It should be a more conscious decision.

> Maybe give this a more generic name so we can have other practice features too if we ever get any consensus on it?

Changed /enablerescue to /enablecheats.

2020-05-23 16:01 UTC, fokkonaut commented
Why is m_WishesPractice a char and m_Practice in teams an int?

2020-05-23 16:04 UTC, def- commented
Fixed faster than you commented already. Copy-paste error

2020-05-23 16:09 UTC, fokkonaut commented
int m_Practice is still not a bool

2020-05-23 16:37 UTC, def- commented
That's intentional since we store it as a 0/1 anyway. See all other values in save.h

2020-05-23 16:49 UTC, Learath2 requested changes
I think the logic looks sane, just some style fixes and we can merge.

2020-05-23 16:49 UTC, Learath2 commented on src/game/server/ddracechat.cpp
> +void CGameContext::ConPractice(IConsole::IResult *pResult, void *pUserData)
`CGameControllerDDRace *pController = (CGameControllerDDRace *)pSelf->m_pController`
would clean this up a little

2020-05-23 16:49 UTC, Learath2 commented on src/game/server/ddracechat.cpp
> +		return;
Maybe a console print here aswell? `Team is already in practice mode`

2020-05-23 16:49 UTC, Learath2 commented on src/game/server/ddracechat.cpp
> +	str_format(aBuf, sizeof(aBuf), "'%s' (%d/%d required votes) voted to %s /practice mode in your team, which means you can use /r, but you can't earn a rank.", pSelf->Server()->ClientName(pResult->m_C
`...for your team...`, maybe also move the vote status to the end.

2020-05-23 16:49 UTC, Learath2 commented on src/game/server/ddracechat.cpp
>  			else if (((CGameControllerDDRace*) pSelf->m_pController)->m_Teams.SetCharacterTeam(
```suggestion
			else if (pController->m_Teams.SetCharacterTeam(
```

2020-05-23 16:49 UTC, Learath2 commented on src/game/server/ddracechat.cpp
> +				if (((CGameControllerDDRace*) pSelf->m_pController)->m_Teams.IsPractice(Team))
```suggestion
				if (pController->m_Teams.IsPractice(Team))
```

2020-05-23 16:49 UTC, Learath2 commented on src/game/server/ddracechat.cpp
> +	int Team = ((CGameControllerDDRace*) pSelf->m_pController)->m_Teams.m_Core.Team(pResult->m_ClientID);
```suggestion
	int Team = pController->m_Teams.m_Core.Team(pResult->m_ClientID);
```

2020-05-23 16:49 UTC, Learath2 commented on src/game/server/ddracechat.cpp
> +	if (!g_Config.m_SvRescue && !((CGameControllerDDRace*) pSelf->m_pController)->m_Teams.IsPractice(Team)) {
```suggestion
	if (!g_Config.m_SvRescue && !pController->m_Teams.IsPractice(Team)) {
```

2020-05-23 16:49 UTC, Learath2 commented on src/game/server/entities/character.cpp
> +	if(g_Config.m_SvRescue || (Team() > TEAM_FLOCK && Team() < TEAM_SUPER)) {
Could we maybe check if this team specifically is in practice mode? It shouldn't make much of a difference but I think it'd be clearer.

2020-05-23 16:49 UTC, Learath2 commented on src/game/server/save.cpp
> +	if (m_Practice) {
Either omit the braces or move the opening brace to a new line.

2020-05-23 16:49 UTC, Learath2 commented on src/game/server/ddracechat.cpp
> +	if (!CheckClientID(pResult->m_ClientID))
```suggestion
	if(!CheckClientID(pResult->m_ClientID))
```
There are a couple more instances of this but I'll point it out once.

2020-05-23 17:04 UTC, def- commented on src/game/server/ddracechat.cpp
> +void CGameContext::ConPractice(IConsole::IResult *pResult, void *pUserData)
Done

2020-05-23 17:05 UTC, def- commented on src/game/server/ddracechat.cpp
> +		return;
Done

2020-05-23 17:06 UTC, def- commented on src/game/server/ddracechat.cpp
> +	str_format(aBuf, sizeof(aBuf), "'%s' (%d/%d required votes) voted to %s /practice mode in your team, which means you can use /r, but you can't earn a rank.", pSelf->Server()->ClientName(pResult->m_C
Done

2020-05-23 17:07 UTC, def- commented on src/game/server/ddracechat.cpp
>  			else if (((CGameControllerDDRace*) pSelf->m_pController)->m_Teams.SetCharacterTeam(
Done

2020-05-23 17:08 UTC, def- commented on src/game/server/ddracechat.cpp
> +	int Team = ((CGameControllerDDRace*) pSelf->m_pController)->m_Teams.m_Core.Team(pResult->m_ClientID);
Done

2020-05-23 17:09 UTC, def- commented on src/game/server/ddracechat.cpp
> +				if (((CGameControllerDDRace*) pSelf->m_pController)->m_Teams.IsPractice(Team))
Done

2020-05-23 17:09 UTC, def- commented on src/game/server/ddracechat.cpp
> +	if (!g_Config.m_SvRescue && !((CGameControllerDDRace*) pSelf->m_pController)->m_Teams.IsPractice(Team)) {
Done

2020-05-23 17:10 UTC, def- commented on src/game/server/entities/character.cpp
> +	if(g_Config.m_SvRescue || (Team() > TEAM_FLOCK && Team() < TEAM_SUPER)) {
Nope, that has the problem that you might want to enable rescue mode after you failed (the main use case) and then there is no rescue spot saved.

2020-05-23 17:10 UTC, def- commented on src/game/server/save.cpp
> +	if (m_Practice) {
Done

2020-05-23 17:11 UTC, Learath2 commented on src/game/server/entities/character.cpp
> +	if(g_Config.m_SvRescue || (Team() > TEAM_FLOCK && Team() < TEAM_SUPER)) {
Ah but now that I think about it, this would prevent looking for rescuepoints before practice is turned on

2020-05-23 17:13 UTC, def- commented on src/game/server/ddracechat.cpp
> +	if (!CheckClientID(pResult->m_ClientID))
Done

2020-05-23 17:20 UTC, Learath2 approved these changes

2020-05-23 18:20 UTC, d3fault commented on src/game/server/teams.cpp
> +					"Your team would've finished in: %d minute(s) %5.2f second(s). Since you had cheats enabled your rank doesn't count. Try again without cheats.",
> Since you had cheats enabled

should be:
> Since you had practice mode enabled

2020-05-23 18:45 UTC, def- commented on src/game/server/teams.cpp
> +					"Your team would've finished in: %d minute(s) %5.2f second(s). Since you had cheats enabled your rank doesn't count. Try again without cheats.",
Done

2020-05-27 15:05 UTC, def- commented
Time to merge @heinrich5991 @Learath2 ?

2020-05-27 15:40 UTC, heinrich5991 commented
Fingers crossed.

bors r+

2020-05-27 15:48 UTC, merged