support multiple modifiers for binds
ddnet/ddnet pull request #2675
Opened 2020-08-30 00:06 UTC by plsplsplslol

2020-08-30 08:29 UTC, edg-l commented
You are ignoring so many naming conventions...

2020-08-30 08:38 UTC, edg-l requested changes
I don't think I like this or i find it useful, also you introduce repeated code.

2020-08-30 08:38 UTC, edg-l commented on src/game/client/components/binds.cpp
> +		char aModifier[256] = { 0 };
```cpp
char aModifier[256];
aModifier[0] = '\0';
```
Fits more our style.

2020-08-30 08:38 UTC, edg-l commented on src/game/client/components/binds.cpp
> +				const char *ModifierName = GetModifierName(i);
Pointers use the prefix `p`, therefore the name should be `pModifierName`

2020-08-30 08:38 UTC, edg-l commented on src/game/client/components/binds.cpp
> +		for(int Mod = 0; Mod < (1 << MODIFIER_COUNT); Mod++)
You use `(1 << MODIFIER_COUNT)` quite a lot, maybe create a constant and name it properly.

2020-08-30 08:38 UTC, edg-l commented on src/game/client/components/binds.cpp
> +			if (Modifier & (1 << i)) {
Brace style, change it to allman style

```
if()
{ // <- Notice the opening brace has its own line
}
```

2020-08-30 08:38 UTC, edg-l commented on src/game/client/components/binds.cpp
> +		for (int i = 1; i < MODIFIER_COUNT; i++) {
Brace style

2020-08-30 08:38 UTC, edg-l commented on src/game/client/components/binds.cpp
> +						const char *ModifierName = GetModifierName(k);
Wrong variable name.

2020-08-30 08:38 UTC, edg-l commented on src/game/client/components/binds.cpp
> +					if (i & (1 << k)) {
Brace style

2020-08-30 08:38 UTC, edg-l commented on src/game/client/components/binds.cpp
> +				for (int k = 1; k < MODIFIER_COUNT; k++) {
Brace style

2020-08-30 08:38 UTC, edg-l commented on src/game/client/components/binds.cpp
> +			char aModifier[256] = { 0 };
Style like I said previously.

2020-08-30 08:38 UTC, edg-l commented on src/game/client/components/binds.cpp
> +			for (int k = 1; k < MODIFIER_COUNT; k++) {
Brace style

2020-08-30 08:38 UTC, edg-l commented on src/game/client/components/binds.cpp
> +				if (i & (1 << k)) {
Brace style

2020-08-30 08:38 UTC, edg-l commented on src/game/client/components/binds.cpp
> +					const char *ModifierName = GetModifierName(k);
Variable name

2020-08-30 09:08 UTC, Learath2 commented
One problem with this is that it's now creating a rather large sparse array to store the binds in. I took a look at a couple other projects which seem to either use a hashmap or just put them all in a dense array. We could look into the performance implications of those.

2020-08-30 22:19 UTC, BannZay commented
@Learath2 out of interest, it is possible to make hashmap work here? If we taking hash from key and its mod then I see no way to efficiently discover shift+b binding when user presses alt+shift+b.

P.s. I would prefer to not invoke shift+b on alt+shift+b press at the first point but this is current game behavior.

2020-08-31 14:56 UTC, Learath2 commented
> P.s. I would prefer to not invoke shift+b on alt+shift+b press at the first point but this is current game behavior.

It's not since the game doesn't even have multi modifier binds.

The check for the bind would be done when they hit the b, so it'd only ever trigger one.

2020-08-31 15:07 UTC, BannZay commented
yes, user press alt+shift+b
if there is a binding 'shift+b' it will be triggered

2020-08-31 18:06 UTC, plsplsplslol commented
@Learath2 should I continue fixing this or have someone else make this with a hashmap or dense array?

2020-09-04 10:52 UTC, Learath2 commented
This takes the memory usage for binds from 16k to 64k for a feature that will be seldom used. I think I like the feature but you should look into how you can get the memory usage down without a large performance hit.

2020-09-04 11:01 UTC, Learath2 commented
You can keep fixing this. I guess 64k is acceptable

2020-09-15 08:37 UTC, def- commented
bors r+
Thanks!

2020-09-15 08:45 UTC, merged