Adapt 0.7 start menu
ddnet/ddnet pull request #2730
Opened 2020-09-04 05:56 UTC by def-

![screenshot-20200904@075411](https://user-images.githubusercontent.com/2335377/92204521-f3679600-ee83-11ea-99f0-56339d39bb53.png)
Supports hotkeys to enter them, escape to go back. Start menu can be disabled in settings.
Still missing:
- News picture
- More DDNet-looking Play picture
- Maybe implement the server button

2020-09-04 10:02 UTC, def- commented
code-wise ready for review. Maybe someone else wants to implement the server button. It should pipe out stdout, probably using select on Posix and some equivalent on Windows and display it inline.

2020-09-04 23:46 UTC, BannZay commented
I would add learn button to new main menu and remove from the "old" menu setting/demos/editor/news/learn tabs making them stand alone pages with return to main menu button. 

The return button just awesome and allows you to navigate extremely fast. Exit from editor by return key is the best thing ever <3

Can we maybe just execute "start DDNet-Server.exe" if none will implement it "right" way. Will improve later. I like the Server button here because this might force user to learn stuff about ddnet server

2020-09-04 23:53 UTC, BannZay commented
Nice Deen, this is very as is already. I love it

2020-09-05 22:44 UTC, def- commented
> I would add learn button to new main menu and remove from the "old" menu setting/demos/editor/news/learn tabs making them stand alone pages with return to main menu button.

Done

> Can we maybe just execute "start DDNet-Server.exe" if none will implement it "right" way. Will improve later. I like the Server button here because this might force user to learn stuff about ddnet server

Done, but F7 doesn't work properly on Windows and I don't see a standard way of opening a terminal window in Linux.

2020-09-06 00:11 UTC, BannZay commented on src/game/client/components/menus_start.cpp
> +			m_ServerProcess.Process = shell_execute(Storage()->GetBinaryPath(PLAT_SERVER_EXEC, aBuf, sizeof(aBuf)));
yea, it wont work on windows if working directory is not where DDNet-Server.exe located as storage contains wrong data IMO

I failed to understand the code of FindDatadir which assumes that binary dir are always in the same directory where data directory located. 

At least CMAKE builds following structure for windows:
build\Debug\DDnet.exe 
build\data\mapres

I see no reason why we just wont get the full directory path to executive assembly for m_aBinarydir? (GetModuleFileNameA for windows)

2020-09-06 00:11 UTC, BannZay commented on src/game/client/components/menus.cpp
> +		if(DoButton_MenuTab(&s_StartButton, Localize("Back"), false, &Button, CUI::CORNER_T))
"Menu" instead of "Back" looks better to me

2020-09-06 06:23 UTC, edg-l commented
This is also a chance to add a discord button, since now there is space for it i think.

2020-09-06 09:12 UTC, def- commented on src/game/client/components/menus.cpp
> +		if(DoButton_MenuTab(&s_StartButton, Localize("Back"), false, &Button, CUI::CORNER_T))
Done.

2020-09-06 09:13 UTC, def- commented
> This is also a chance to add a discord button, since now there is space for it i think.

I don't think that belongs in the client.

2020-09-06 11:53 UTC, Ekidoxx commented
Three buttons in bottom left corner - for website, wiki and discord could be nice addition actually.

2020-09-06 12:22 UTC, BannZay commented
Should not we move learn and news to bottom left as well? They does not have icons & logically not really part of actual gameplay

2020-09-06 12:25 UTC, BannZay commented on src/base/system.c
> +	info.lpVerb = "open";
@def- Does not work without cbsize (this is required param)

2020-09-06 23:01 UTC, heinrich5991 commented on src/game/client/components/menus.cpp
> +			IOHANDLE File = Storage()->OpenFile(Storage()->GetBinaryPath("autoexec_server.log", aBuf, sizeof(aBuf)), IOFLAG_READ, IStorage::TYPE_ALL);
Does this work on Windows? It usually has problems with two processes accessing the same file.

2020-09-06 23:03 UTC, heinrich5991 commented
How does the econ console work? I can't find it in the code.

Looks nice. Should we get this in soon or wait a little more?

2020-09-07 04:42 UTC, def- commented on src/game/client/components/menus.cpp
> +			IOHANDLE File = Storage()->OpenFile(Storage()->GetBinaryPath("autoexec_server.log", aBuf, sizeof(aBuf)), IOFLAG_READ, IStorage::TYPE_ALL);
I will get rid of this. I noticed that Windows didn't work, probably some io_seek magic would fix it, but econ console seems more stable.

2020-09-07 04:42 UTC, def- commented
> How does the econ console work? I can't find it in the code.

It doesn't work yet. I still have to implement the EconClient.

2020-09-07 09:27 UTC, heinrich5991 commented
I'm fine with waiting a little.

2020-09-07 10:07 UTC, def- commented
![screenshot-20200907@120453](https://user-images.githubusercontent.com/2335377/92376334-b6f59d80-f102-11ea-835b-9e1e72b79d02.png)

2020-09-07 10:24 UTC, def- commented on src/base/system.c
> +	info.lpVerb = "open";
Done.

2020-09-07 10:42 UTC, def- commented on src/game/client/components/menus_start.cpp
> +			m_ServerProcess.Process = shell_execute(Storage()->GetBinaryPath(PLAT_SERVER_EXEC, aBuf, sizeof(aBuf)));
But we never release builds like that, right? The autoupdater also depends on this location of DDNet-Server.exe, so I think we can keep it as is. The alternative would be to offer something like FindDatadir but FindDDNetServer that searches in some paths, starting with pArgv0. For Mac OSX the path is probably also wrong, not sure how to find it there. @Learath2 any idea, should we just hardcode it?

2020-09-07 11:28 UTC, BannZay commented on src/game/client/components/menus_start.cpp
> +			m_ServerProcess.Process = shell_execute(Storage()->GetBinaryPath(PLAT_SERVER_EXEC, aBuf, sizeof(aBuf)));
I find it good just to store our exe's in `binary` dir. We should probably explain this idea to CMAKE

2020-09-07 11:31 UTC, def- commented on src/game/client/components/menus_start.cpp
> +			m_ServerProcess.Process = shell_execute(Storage()->GetBinaryPath(PLAT_SERVER_EXEC, aBuf, sizeof(aBuf)));
btw, my build doesn't create Debug directory, maybe cause I build in-directory with `cmake .`

2020-09-07 11:32 UTC, BannZay commented on src/game/client/components/menus_start.cpp
> +			m_ServerProcess.Process = shell_execute(Storage()->GetBinaryPath(PLAT_SERVER_EXEC, aBuf, sizeof(aBuf)));
But still, maybe it is better to query an executable location and mark its folder as binary folder. Is binary files should be a part of storage.cfg ?

2020-09-07 13:48 UTC, def- commented
@heinrich5991 @Learath2 any suggestion how to find DDNet-Server.exe on OSX distribution and Windows cmake build?

Other than that should be done, I removed the econ for now since I got annoyed by it.

2020-09-07 13:57 UTC, BannZay commented
> any suggestion how to find DDNet-Server.exe

GetModuleFileNameA can be used for windows. As client and server builds into the same directory

2020-09-07 14:00 UTC, def- commented
That does *not* work for Mac OSX. If we use GetModuleFileNameA we could also just use argv[0] which is available on more platforms, couldn't we?

2020-09-07 18:48 UTC, def- commented
![screenshot-20200907@204748](https://user-images.githubusercontent.com/2335377/92412247-78d09c00-f14b-11ea-86b4-deb2fbb9779c.png)

2020-09-07 19:17 UTC, BannZay commented
if you click on News or demos and then on Settings tab then you will be navigated to Play menu
I guess we should remove settings and Editor from tabs bar

2020-09-07 20:52 UTC, def- commented
I actually like to still have the small buttons there for settings and quit. How Teeworlds solved it with remembering the previous page when you go back from settings might be a bit cleaner, but I'm ok with our current solution.

2020-09-08 19:30 UTC, Ekidoxx commented
Little bug with the tabs

1. Click on `Demos`
![image](https://user-images.githubusercontent.com/14035306/92519040-9ff59f00-f219-11ea-91b3-d513f3a2f486.png)

2. From there go to `settings`
![image](https://user-images.githubusercontent.com/14035306/92519075-ac79f780-f219-11ea-95fd-dfbc14364989.png)

3. \*Puff\* `Demos` tab changed to `Internet`, `LAN`, `Favourites`, `DDNet` & `KoG` tabs
Or otherwise said, you're moved from `Demos` to `Play`
![image](https://user-images.githubusercontent.com/14035306/92519115-bc91d700-f219-11ea-9886-cb2603075df2.png)


Discovered thanks to @BannZay

2020-09-08 22:26 UTC, def- commented
I don't actually mind that behaviour much. Not sure if it's worth the effort to change it. In the end after changing settings people mostly go to play :D

2020-09-08 23:43 UTC, BannZay commented
This menus is so fresh for DDNet.

I would make this menu the only thing you can use to reach places without using bindings.

I can continue the work on tabs after this pr merge if you dont mind.

2020-09-09 15:00 UTC, def- commented
@BannZay Sure, would be great if you can improve it a bit. I'm a bit tired of UI changes, so from my point of view this should go in.

2020-09-09 17:41 UTC, Ekidoxx commented
What do you guys think about our own, DDNet-related images taken directly out of the game & client?

![image](https://user-images.githubusercontent.com/14035306/92634195-371f2d00-f2d4-11ea-84c2-b5a87553790b.png)

2020-09-09 17:59 UTC, BannZay commented
Idk, its cool to have own and they are descent, but teeworlds ones way cooler tho

2020-09-09 18:36 UTC, kingston-svg commented
It's cool, I like it.

2020-09-09 20:11 UTC, HiRavie commented
I suggest an entire new layout to set us apart from 0.7, I sketched this one up. It can surely still be improved, but let me know what you think before I put more time into this. 

![layout](https://user-images.githubusercontent.com/65019210/92647569-5de75e80-f2e8-11ea-8aee-d0a97729fe16.png)

2020-09-10 16:29 UTC, heinrich5991 requested changes
Bugs found while testing:
- The loading bar goes all the way to the right before starting at 0 and going to 100%.
- Run server hangs the client.
- Quit asks whether I really want to quit (as opposed to usually where it only asks it when you're ingame for more than 20 min).

2020-09-10 17:57 UTC, def- commented
> The loading bar goes all the way to the right before starting at 0 and going to 100%.

What loading bar?

> Run server hangs the client.

Any idea how to reproduce? Works for me.

> Quit asks whether I really want to quit (as opposed to usually where it only asks it when you're ingame for more than 20 min).

Fixed.

2020-09-10 19:55 UTC, heinrich5991 commented
I get
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
DDNet: xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

When running with strace, I don't get the hang, but still get these messages…

The loading bar I'm referring to is the initial loading bar of the DDNet client.

2020-09-10 20:40 UTC, def- commented
> The loading bar I'm referring to is the initial loading bar of the DDNet client.

That bar is one frame for me so impossible to debug.

2020-09-10 20:47 UTC, Learath2 commented
Slow it down arbitrarily, or maybe record it?

On Thu, Sep 10, 2020, 23:40 Dennis Felsing <notifications@github.com> wrote:

> The loading bar I'm referring to is the initial loading bar of the DDNet
> client.
>
> That bar is one frame for me so impossible to debug.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ddnet/ddnet/pull/2730#issuecomment-690714691>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADXYBGK2QCHADZIWCLP2ELSFE2UPANCNFSM4QXJW4SQ>
> .
>

2020-09-10 20:48 UTC, def- commented
I figured it out already, easy enough to fix.

But no idea about the other problem with running DDNet-Server yet

2020-09-10 22:50 UTC, heinrich5991 commented on src/base/system.c
>  		execv(file, argv);
Found it, happens on file not found for the server.

This seems to happen due to incorrect error checking. When execv returns, process creation failed and the current process must be killed.

`fork()` should probably also get some error checking.

2020-09-11 07:47 UTC, def- commented on src/base/system.c
>  		execv(file, argv);
Thanks, done.

2020-09-11 13:24 UTC, heinrich5991 approved these changes
Thanks, looks good now.

bors r+

2020-09-11 13:32 UTC, merged

2020-09-12 06:23 UTC, def- commented
@HiRavie maybe you can work with @BannZay if you two still want to improve the layout.