Create ALLOW_X_SKINS game info flag
ddnet/ddnet pull request #2917
Opened 2020-09-24 09:42 UTC by def-

To allow server to set any x_ prefixed skin and client won't filter it
out. As requested by Pure_luck for his mod to show players as tanks,
walls, etc. Won't be enabled on DDNet-Servers, thus such skins can be
added where a server modification wants to fine-control what skins are
allowed and can enforce such skins.

2020-09-24 09:49 UTC, fokkonaut commented
Well, can a client use such skin on their own then without it getting forced by the server?

2020-09-24 09:58 UTC, pure-luck-999 commented on src/game/server/gamecontroller.cpp
> +	pGameInfoEx->m_Flags2 = 0;
Server owners should replace 0 with ALLOW_X_SKINS here, right?

2020-09-24 09:59 UTC, fokkonaut commented on src/game/server/gamecontroller.cpp
> +	pGameInfoEx->m_Flags2 = 0;
Yes.

2020-09-24 10:03 UTC, def- commented
> Well, can a client use such skin on their own then without it getting forced by the server?

Depends on how the server implements the filtering. But client can try setting it, depends on server if it gets respected. Won't have to be implemented in this project but in mods that want to use allow_x_skins.

2020-09-24 11:39 UTC, heinrich5991 commented
I'd like to review this one later.

2020-09-25 00:14 UTC, heinrich5991 requested changes
Needs a size check (otherwise we could read memory not intended for us), rest seems to be correct.

2020-09-25 00:14 UTC, heinrich5991 commented on src/game/client/gameclient.cpp
> +	if(Version >= 5)
Needs a size check as well. If it fails, just set version to 4 I guess.

2020-09-25 00:14 UTC, heinrich5991 commented on src/game/client/gameclient.cpp
> +	Info.m_AllowXSkins = AllowXSkins;
This is a bit implicit.

AllowXSkins is intended to be false unless the server sends an version >= 5 info with the flag enabled.

Can you set `Info.m_AllowXSkins` to false here, and later set it to `Flags2 & GAMEINFOFLAG2_ALLOW_X_SKINS` in a `if(Version >= 5)` branch after `if(Version >= 4)`?

2020-09-25 00:14 UTC, heinrich5991 commented on src/game/client/gameclient.cpp
> +		City = Flags2 & GAMEINFOFLAG2_GAMETYPE_CITY;
This line should be in the a `if(Version >= 5)`. Alternatively: `Version >= 5 && (Flags2 & GAMEINFOFLAG2_GAMETYPE_CITY`.

2020-09-25 06:12 UTC, def- commented on src/game/client/gameclient.cpp
> +	if(Version >= 5)
Done

2020-09-25 06:13 UTC, def- commented on src/game/client/gameclient.cpp
> +	Info.m_AllowXSkins = AllowXSkins;
Done

2020-09-25 06:15 UTC, def- commented on src/game/client/gameclient.cpp
> +		City = Flags2 & GAMEINFOFLAG2_GAMETYPE_CITY;
But Flags2 is only assigned if Version >= 5, so not sure what good the check does.(except being more explicit)

2020-09-25 19:39 UTC, heinrich5991 commented on src/game/client/gameclient.cpp
> +		Version = 4;
This stops version 1-3 from working. Need to cap it at 4 instead. Maybe: `Version = min(pInfoEx->m_Version, 4);`

2020-09-25 20:25 UTC, def- commented on src/game/client/gameclient.cpp
> +		Version = 4;
Done

2020-09-25 21:22 UTC, heinrich5991 approved these changes

2020-09-25 21:22 UTC, heinrich5991 commented
bors r+

Thanks! :)

2020-09-25 21:29 UTC, merged