No negative right shift in snaphsot.h (fixes #3049)
ddnet/ddnet pull request #3051
Opened 2020-10-10 09:55 UTC by def-

2020-10-10 12:46 UTC, Jupeyy commented
dunno if u want me to rebase on this pr, but
```
			int v = d[y * Pitch + x * 4];
			if(OrgWeight == 0)
				v = 0;
			else if(v <= OrgWeight)
				v = (int)(((v / (float)OrgWeight) * NewWeight));
			else if(InvOrgWeight == 0)
				v = NewWeight;
			else
				v = (int)(((v - OrgWeight) / (float)InvOrgWeight) * InvNewWeight + NewWeight);
			d[y * Pitch + x * 4] = v;
			d[y * Pitch + x * 4 + 1] = v;
			d[y * Pitch + x * 4 + 2] = v;```

should do the job

2020-10-10 13:42 UTC, def- commented
> dunno if u want me to rebase on this pr, but this should do the job

Thanks, done.

2020-10-11 00:22 UTC, heinrich5991 requested changes
Rest looks good, thanks.

2020-10-11 00:22 UTC, heinrich5991 commented on src/base/math.h
> +	return v / 1024;
This does something different for negative integers, `-1 / 1024 == 0`, `-1 >> 10 == -1`.

2020-10-11 00:22 UTC, heinrich5991 commented on src/engine/shared/snapshot.h
> +	int Type() { return m_TypeAndID >= 0 ? m_TypeAndID >> 16 : -1; }
This changes behavior, did you verify that we don't rely on the old one?

2020-10-11 08:38 UTC, def- commented on src/base/math.h
> +	return v / 1024;
Done.

2020-10-11 09:16 UTC, def- commented on src/engine/shared/snapshot.h
> +	int Type() { return m_TypeAndID >= 0 ? m_TypeAndID >> 16 : -1; }
I'm not sure how to best fix this. Suggestions?

2020-10-11 09:43 UTC, Jupeyy commented on src/engine/shared/snapshot.h
> +	int Type() { return m_TypeAndID >= 0 ? m_TypeAndID >> 16 : -1; }
I can't see code where its relying on negative numbers except the -1, can you?

2020-10-11 13:12 UTC, heinrich5991 commented on src/base/math.h
> +	return v / 1024;
Okay, can we talk about the reason why you avoid right-shifting integers? Right-shifting negative integers is implementation-defined behavior until C++20 which is defined to do arithmetic right-shift in all major compilers.

https://github.com/ddnet/ddnet/issues/3049#issuecomment-706564322

The issue is not fixed by the branch, `>> 10` rounds towards -infinity, `/ 1024` rounds towards 0.

2020-10-11 13:15 UTC, Jupeyy commented on src/base/math.h
> +	return v / 1024;
but we are not at c++20 and msvc2017 failed

2020-10-11 13:20 UTC, heinrich5991 commented on src/base/math.h
> +	return v / 1024;
Can you look at the assembly maybe?

Godbolt shows that right shifts are compiled to arithmetic right shifts by MSVC 2017:

https://godbolt.org/z/En8r5n

2020-10-11 13:35 UTC, Jupeyy commented on src/base/math.h
> +	return v / 1024;
yes, the assembly looks right, i'll try and see why the pointer is invalid then

2020-10-11 13:40 UTC, Jupeyy commented on src/engine/shared/snapshot.h
> +	int Type() { return m_TypeAndID >= 0 ? m_TypeAndID >> 16 : -1; }
![image](https://user-images.githubusercontent.com/6654924/95680205-19492e80-0bd8-11eb-8dbc-928e2d1e8c35.png)

2020-10-11 13:46 UTC, Jupeyy commented on src/engine/shared/snapshot.h
> +	int Type() { return m_TypeAndID >= 0 ? m_TypeAndID >> 16 : -1; }
Maybe bcs of the other snapshot problems, but my knowledge doesnt go deep here, its your turn now xd

2020-10-11 13:48 UTC, heinrich5991 commented on src/engine/shared/snapshot.h
> +	int Type() { return m_TypeAndID >= 0 ? m_TypeAndID >> 16 : -1; }
> ![image](https://user-images.githubusercontent.com/6654924/95680205-19492e80-0bd8-11eb-8dbc-928e2d1e8c35.png)

Not sure if that's what you're claiming, but
```
>>> "{:032b}".format(2147418112)
'01111111111111110000000000000000'
```
so 2147418112 is not the bit pattern of a negative number, and for positive numbers, right shift is strictly defined by the C standard.

2020-10-11 13:50 UTC, Jupeyy commented on src/engine/shared/snapshot.h
> +	int Type() { return m_TypeAndID >= 0 ? m_TypeAndID >> 16 : -1; }
yes, my claim is, that appearently the same snapshot has different values between linux and windows
So its probs caused by some of the other snapshot code

2020-10-11 13:51 UTC, Jupeyy commented on src/engine/shared/snapshot.h
> +	int Type() { return m_TypeAndID >= 0 ? m_TypeAndID >> 16 : -1; }
sry, maybe it was confusing that i replied to the other comment first, just wanted to switch here bcs this is the actual problem :D

2020-10-11 14:37 UTC, def- commented
I removed the shift commits.

2020-10-11 14:45 UTC, heinrich5991 approved these changes
As said, looks good. Thanks for the fixes. :)

bors r+

2020-10-11 14:53 UTC, merged