Add clang-tidy to CI and enable clang-analyzer checks (superseded #3075)
ddnet/ddnet pull request #3076
Opened 2020-10-12 11:38 UTC by def-

> 470 warnings treated as errors

The actual work will be fixing those or at least
NOLINT(clang-analyzer-optin.cplusplus.VirtualCall) them so we can enable
this.

2020-10-12 17:22 UTC, def- commented
I think this found some actual issues that can cause crashes as well as undefined behaviour. Good to have gone through. A few false positives though since the static analysis is not that smart.

2020-10-12 18:27 UTC, Jupeyy commented on src/game/client/components/mapimages.cpp
> +			if(ColorChannelCount > 0)
lets just set colorchannel to 4, LoadPNG only returns RGB and RGBA(we can just set format to RGB in LoadPNG for default case or make LoadPNG otherwise safer)

2020-10-12 18:36 UTC, Jupeyy commented on src/game/client/components/mapimages.cpp
> +			if(ColorChannelCount > 0)
oh you even made it safer later :D

2020-10-12 20:14 UTC, def- commented on src/game/client/components/mapimages.cpp
> +			if(ColorChannelCount > 0)
so all good?

2020-10-12 20:25 UTC, Jupeyy commented on src/game/client/components/mapimages.cpp
> +			if(ColorChannelCount > 0)
so this check is false positive, if we just initialize ColorChannelCount to 3 or 4

2020-10-12 20:30 UTC, def- commented on src/game/client/components/mapimages.cpp
> +			if(ColorChannelCount > 0)
ok, done.

2020-10-13 22:16 UTC, heinrich5991 requested changes
Rest looks good.

2020-10-13 22:16 UTC, heinrich5991 commented on src/game/server/gamecontext.cpp
> +	if(TotalLength > 0)
This (and the corresponding change in config_store.cpp) seem to introduce logic bugs. When the config has length 0, the map still needs to be updated.

What clang-tidy fix does this satisfy?

I guess you could just allocate more if it's a check like "malloc must not be called with size 0".

2020-10-14 12:54 UTC, def- commented on src/game/server/gamecontext.cpp
> +	if(TotalLength > 0)
Right.

2020-10-14 13:01 UTC, heinrich5991 commented on src/game/server/gamecontext.cpp
> +	char *pSettings = (char *)malloc(maximum(1, TotalLength));
Given that style-check failed anyway, you could try to reduce the diff to a minimum in this file and config_store.cpp by moving the `CDataFileWriter Writer;` and following line to the initial position.

2020-10-14 13:46 UTC, def- commented on src/game/server/gamecontext.cpp
> +	char *pSettings = (char *)malloc(maximum(1, TotalLength));
Done.

2020-10-14 14:07 UTC, heinrich5991 commented
bors r+

Thanks. Let's see whether coding becomes impossible once I also get the name-checking in. :P

2020-10-14 14:07 UTC, heinrich5991 approved these changes

2020-10-14 14:15 UTC, merged