Settings Tabs Animations
ddnet/ddnet pull request #3193
Opened 2020-10-26 01:16 UTC by Banana090

Yet another "Crazy Visual Update" everyone will doubt about. Made additional argument for DoButton_MenuTab to make button animate by upscaling it on hover/active state. That's all for now. It's first step in adding some light animations to UI. Making this PR so you can start your favorite discussions about new visuals and so on.

No screenshots, cuz that's animated changes. Look for video on Discord:
[Discord Message Link](https://discordapp.com/channels/252358080522747904/295908390956433410/770091824752099328)
[Download Video](https://cdn.discordapp.com/attachments/295908390956433410/770091820683624458/2020-10-26_04-08-51.mp4)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [?] Tested in combination with possibly related configuration options
- [?] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [?] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2020-10-26 01:23 UTC, l-ouis commented
looks nice but text grows too big and doesn't look centered either.

is the upscale linear / smooth / ? btw

2020-10-26 01:26 UTC, Banana090 commented
@l-ouis it's linear, but smooth xD. Text is aligned by Do_Label code and considering size changes, so it should be centered, but yes, it grows. I can disable this behavior, we'll see

2020-10-26 02:08 UTC, TsFreddie commented on src/game/client/components/menus.cpp
>  	UI()->DoLabel(&Temp, pText, Temp.h * ms_FontmodHeight, 0, -1, AlignVertically);
If you want to scale text. "DoLabel" needs to be changed so you scale the rendered texture instead of trying to render glyphs with new fontsize. It is possible you are spamming multiple redundant glyphs onto the atlas texture under some resolution. Plus pixel alignment in textrender might render the animation shaky in lower resolution.

2020-10-26 03:09 UTC, Banana090 commented
I've updated links to video, because I made some changes, look at this now please:
[Discord Message](https://discordapp.com/channels/252358080522747904/295908390956433410/770121606219169822)
[Download Video](https://cdn.discordapp.com/attachments/295908390956433410/770121602355822642/2020-10-26_06-07-44.mp4)

2020-10-26 08:27 UTC, def- commented
Only having watched the video, I surprisingly like the look, even though I'm generally against animations.

2020-10-26 10:41 UTC, heinrich5991 commented
I'd be fine with it.

2020-10-26 13:32 UTC, Jupeyy requested changes
Don't really like that the browser tabs are round now too.
A step backwards imo

2020-10-26 13:32 UTC, Jupeyy commented on src/game/client/components/menus.cpp
> +		Time = time();
we have time_get_microseconds

2020-10-26 13:32 UTC, Jupeyy commented on src/game/client/components/menus.cpp
> +		if(pAnimator->m_Time + 1000000.f < Time)
No need to use floats, they just create inconsitency

2020-10-26 13:32 UTC, Jupeyy commented on src/game/client/ui.h
> +	float m_Time;
Here again

2020-10-26 14:32 UTC, Banana090 commented on src/game/client/components/menus.cpp
> +		if(pAnimator->m_Time + 1000000.f < Time)
think more please

2020-10-26 14:34 UTC, def- commented on src/game/client/components/menus.cpp
> +		if(pAnimator->m_Time + 1000000.f < Time)
> think more please

Try to be nicer in your communication. Also explain why you actually use a float here instead of your snarky comment. I agree with Jupeyy.

2020-10-26 14:35 UTC, Banana090 commented on src/game/client/components/menus.cpp
> +		Time = time();
no thx, for what reason? Remove 1 extra zero from division? For me it's much clearer to divide by million, not 100.000

2020-10-26 15:46 UTC, Jupeyy commented on src/game/client/ui.h
> +	long long m_Time;
why not just int64, just include system.h or whatever its required

2020-10-26 16:05 UTC, edg-l commented
You don't take into account other languages use longer words, they will be now more out of place than before.

The tabs being round is ugly.

2020-10-26 18:45 UTC, Banana090 commented
@edg-l the text size does not change at all...

2020-10-27 11:53 UTC, edg-l commented
Your animation indeed makes the text bigger.

2020-10-28 14:31 UTC, Banana090 commented
What are we waiting for with this PR? What should I do now for it to be merged? Turned out my next PRs rely on this one

2020-10-28 14:36 UTC, Jupeyy commented
1. You didnt resolve the requested changes
2. We also have other prs and problems, we cannot add 1 trillion features without testing them
3. You have a conflict that must be resolved

2020-10-30 22:46 UTC, Banana090 commented on src/game/client/components/menus.cpp
>  	UI()->DoLabel(&Temp, pText, Temp.h * ms_FontmodHeight, 0, -1, AlignVertically);
Not changing text size anymore

2020-10-30 22:52 UTC, Banana090 commented
Resolved conflict, changed `long long` to `int64`, included system.h
fixed ultra-rare bug with type overflow so if you open menu just in time (happened every 36 minutes for once) all animations would play once simultaneously.

2020-10-31 21:26 UTC, Jupeyy reviewed
You could try and see if your IDE or text editor has a clang-format extension or plugin or whatever, so you don't always run into these style issues

2020-10-31 21:26 UTC, Jupeyy commented on src/game/client/components/menus.cpp
> +	for(SUIAnimator &animator : m_aAnimatorsSettingsTab)
Capital A

2020-10-31 21:26 UTC, Jupeyy commented on src/game/client/components/menus.cpp
> +	for(SUIAnimator &animator : m_aAnimatorsBigPage)
Capital A

2020-10-31 21:26 UTC, Jupeyy commented on src/game/client/components/menus.cpp
> +	for(SUIAnimator &animator : m_aAnimatorsSmallPage)
Capital A,

Also, you are only initializing a few values of these variables, and don't explicitly have a constructor for `SUIAnimator`

2020-11-02 20:35 UTC, heinrich5991 commented
@Banana090 Are you still interested in updating this?

2020-11-06 15:49 UTC, closed without merging