Update translations for 15.2 release
ddnet/ddnet pull request #3248
Opened 2020-11-05 08:05 UTC by def-

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2020-11-05 08:12 UTC, b3z requested changes
nickname is one word.

2020-11-05 08:12 UTC, b3z commented on data/languages/brazilian_portuguese.txt
> +Your nick name '%s' is already used (%d points). Do you still want to use it?
nickname is one word.

2020-11-05 08:12 UTC, b3z commented on data/languages/bulgarian.txt
> +Your nick name '%s' is already used (%d points). Do you still want to use it?
again, nickname is one word. Same like above.

2020-11-05 08:12 UTC, b3z commented on data/languages/catalan.txt
> +Your nick name '%s' is already used (%d points). Do you still want to use it?
nickname

2020-11-05 08:12 UTC, b3z commented on data/languages/belarusian.txt
>  Please enter your nick name below.
nickname, okay you get it. its 49 results. won't comment all.

2020-11-05 08:16 UTC, b3z commented on data/languages/brazilian_portuguese.txt
> +Your nick name '%s' is already used (%d points). Do you still want to use it?
48 more cases

2020-11-05 08:32 UTC, def- commented on data/languages/brazilian_portuguese.txt
> +Your nick name '%s' is already used (%d points). Do you still want to use it?
Done.

2020-11-05 08:35 UTC, b3z approved these changes
👍

2020-11-06 23:30 UTC, Jupeyy commented
bors r+

2020-11-06 23:38 UTC, merged