Move PNG loading in SkinDL to fetch thread (fixes #3398)
ddnet/ddnet pull request #3402
Opened 2020-12-12 11:40 UTC by def-

Sorry for the trouble, seems to work.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2020-12-12 12:38 UTC, Jupeyy requested changes
Rest looks good i guess.
I still don't think you should apologize :D in the end there were enough reviewers about this feature(i even complained about exactly this issue (https://github.com/ddnet/ddnet/pull/2864), so its atleast partially my fault too being not constructive enough)

2020-12-12 12:38 UTC, Jupeyy commented on src/game/client/components/skins.cpp
> +		return 0;
The other LoadSkin returns -1 on error, guess this should too

2020-12-12 12:38 UTC, Jupeyy commented on src/game/client/components/skins.cpp
>  	if(!Graphics()->LoadPNG(&Info, pPath, DirType) || !Graphics()->CheckImageDivisibility(pPath, Info, g_pData->m_aSprites[SPRITE_TEE_BODY].m_pSet->m_Gridx, g_pData->m_aSprites[SPRITE_TEE_BODY].m_pSet->
i think the CheckImageDivisibility check should go somewhere else, bcs it can push to a member vector of the graphic object, which would be a critical data section

2020-12-12 13:44 UTC, def- commented on src/game/client/components/skins.cpp
> +		return 0;
Does it? I think LoadSkin always returned 0, no matter if it worked.

2020-12-12 13:48 UTC, def- commented on src/game/client/components/skins.cpp
>  	if(!Graphics()->LoadPNG(&Info, pPath, DirType) || !Graphics()->CheckImageDivisibility(pPath, Info, g_pData->m_aSprites[SPRITE_TEE_BODY].m_pSet->m_Gridx, g_pData->m_aSprites[SPRITE_TEE_BODY].m_pSet->
Done

2020-12-12 14:12 UTC, Jupeyy commented on src/game/client/components/skins.cpp
> +		return 0;
true confused it with Find :D

2020-12-12 14:16 UTC, Jupeyy commented on src/game/client/components/skins.cpp
> +		return 0;
Oh you changed it now, but i guess its better to change it back then :D

2020-12-12 16:39 UTC, def- commented on src/game/client/components/skins.cpp
> +		return 0;
I think it's better this way.

2020-12-12 16:46 UTC, Learath2 commented
Is LoadPNG threadsafe? I see a `png_init(0, 0)` there, could it be doing some global stuff?

2020-12-12 16:51 UTC, def- commented
No need to call it for every png we load actually, just needs to be run once at program startup, changed. The rest of pnglite doesn't seem to write to any globals, so should be threadsafe.

2020-12-12 23:00 UTC, Jupeyy commented on src/game/client/components/skins.cpp
> +		return 0;
Generally yes, but it will stop loading skins if one of them is broken for example as far as I can see about the skin directory scan implementation

2020-12-12 23:09 UTC, def- commented on src/game/client/components/skins.cpp
> +		return 0;
Fair enough, fixed

2020-12-15 15:00 UTC, def- commented
I have the feeling this should be released quickly.

2020-12-15 15:09 UTC, Jupeyy commented
bors r+

2020-12-15 15:18 UTC, merged