Small (mainly backported) refactor
ddnet/ddnet pull request #3502
Opened 2021-01-11 23:49 UTC by Kaffeine

Port some cleanup and refactoring from the upstream and add some custom refactoring.

Changes overview:
- Backported angle() and direction() functions (upstream commit https://github.com/ddnet/ddnet/commit/7735557aa5c6fb81daa724cce3caa109d1c76c11)
- Backported vector math cleanup (remove some pointless templates, refactor other functions; upstream commit https://github.com/ddnet/ddnet/commit/bdaabc10bcb04e28cf650bb489b87fe8a0e03dee)
- `ddracechat.h` (used by both client and server) moved to a shared dir next to `ddracecommands.h`
- Extracted `CGameController::DoActivityCheck()`
- Some other small cleanups.

I checked that the client and server work (didn't do deep testing though).

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2021-01-13 09:27 UTC, def- commented
On a quick look this seems fine to me. Other opinions?

2021-01-13 16:21 UTC, heinrich5991 commented on src/base/vmath.h
> +
This change has the potential to affect gameplay, but I'm fine with trying it out and seeing if anyone notices anything.

2021-01-13 16:22 UTC, heinrich5991 commented on src/base/vmath.h
> +	vector3_base(float nx, float ny, float nz)
This looks wrong.

2021-01-13 16:31 UTC, Kaffeine commented on src/base/vmath.h
> +
Yeah, I was noticed that too. Some docs say that the second arg should not be zero and can trigger "domain error". But the upstream did it so here we are.

2021-01-13 16:39 UTC, heinrich5991 requested changes
Rest looks good. I went commit-by-commit and marked some places where I was unsatisfied with the solution.

1) Make sure not to modify game physics code.
2) Code that is commented out should be deleted.
3) We name all parameters in DDNet code.

2021-01-13 16:39 UTC, heinrich5991 commented on src/base/vmath.h
> +	operator const T *() { return &x; }
I think we deliberately removed this conversion. We saw nothing good coming from it, but it has the possibility of programming errors.

2021-01-13 16:39 UTC, heinrich5991 commented on src/game/client/gameclient.cpp
> +		vec2 ClosestPoint = closest_point_on_line(HookPos, NewPos, Position);
What happens if `HookPos == NewPos`? The old code caught that. Same with the other instances of `closest_point_on_line`. I don't think this change to `closest_point_on_line` is sensible.

2021-01-13 16:39 UTC, heinrich5991 commented on src/game/server/gamecontroller.h
> +		Function: on_CCharacter_death
Function name is wrong. Same below.

2021-01-13 16:39 UTC, heinrich5991 commented on src/game/server/gamecontroller.h
> +	//virtual bool OnEntity(int Index, vec2 Pos);
Code that is commented out can be removed.

2021-01-13 16:39 UTC, heinrich5991 commented on src/game/server/gamecontroller.h
> +	// void OnPlayerInfoChange(class CPlayer *pPlayer);
Code that is commented out should be removed.

2021-01-13 16:39 UTC, heinrich5991 commented on src/game/server/gamecontroller.cpp
> +void IGameController::HandleCharacterTiles(CCharacter *, int)
This is unusual for DDNet code, please name the parameters even if you don't use them.

2021-01-13 16:39 UTC, heinrich5991 commented on src/game/server/gamecontroller.cpp
> +int64 IGameController::GetMaskForPlayerWorldEvent(int, int ExceptID)
Please name all parameters.

2021-01-13 16:41 UTC, Kaffeine commented on src/base/vmath.h
> +	vector3_base(float nx, float ny, float nz)
You're absolutely right! During the conflict solving I had to redo some T->float replacement for `length`, `angle`, and other methods.

Thank you for saving me from a regression. You have a sharp look. :+1: 

I fixed this locally but I'll wait for further comments to address them all at once.

2021-01-13 16:43 UTC, Kaffeine commented on src/game/server/gamecontroller.cpp
> +void IGameController::HandleCharacterTiles(CCharacter *, int)
We'll get "unused variables" warnings in that case. In other frameworks there are some UNUSED() macros; I can introduce such one and use it here. Or I can leave warnings.

2021-01-13 16:44 UTC, heinrich5991 commented on src/base/vmath.h
> +
https://en.cppreference.com/w/c/numeric/math/atan2

It says that there's only a problem if x and y are both zero. cppreference.com is fairly authorative on C/C++ standard.

2021-01-13 16:45 UTC, heinrich5991 commented on src/base/vmath.h
> +
I was more talking about the fact that you replaced our manual angle calculation with the more correct atan2f. This can change how stuff is rounded, however, so it has the potential to affect real physics.

2021-01-13 16:45 UTC, Kaffeine commented on src/game/server/gamecontroller.h
> +	// void OnPlayerInfoChange(class CPlayer *pPlayer);
I left it here because we have commented code that calls this: https://github.com/ddnet/ddnet/blob/master/src/game/server/player.cpp#L656

I'll remove this here and I cleanup CPlayer code if you want.

2021-01-13 16:46 UTC, heinrich5991 commented on src/game/server/gamecontroller.cpp
> +void IGameController::HandleCharacterTiles(CCharacter *, int)
Do we get unused variables warnings? I thought we didn't have such a warning enabled.

2021-01-13 16:48 UTC, Kaffeine commented on src/base/vmath.h
> +	operator const T *() { return &x; }
You're right we removed this from ddnet/master: f83d528f5d7b1ef9fe2709fa04ca44c16f589cc9. I'll remove it too.

2021-01-13 17:01 UTC, Kaffeine commented on src/game/server/gamecontroller.h
> +		Function: on_CCharacter_death
The commit backported as-is. I'll fix it nonetheless.

2021-01-13 17:04 UTC, def- commented on src/game/server/gamecontroller.cpp
> +void IGameController::HandleCharacterTiles(CCharacter *, int)
If you get the warning then write the name in a comment with`/* name */`

2021-01-13 17:33 UTC, Kaffeine commented
v2:
- Removed vector2_base operator const T *() (intentionally removed by commit f83d528f5d7b1ef9fe2709fa04ca44c16f589cc9)
- Fixed accidentical vector3_base constructor arguments (were `float`).
- Name all method arguments (in IGameController::HandleCharacterTiles(), IGameController::GetMaskForPlayerWorldEvent())
- Removed some added commented-out code
- Fixed method names in the backported comments in gamecontroller.h
- vmath.h: `angle()` (ex. `GetAngle()`) kept as-is (not as the upstream version)
- vmath.h: closest_point_on_line() kept as-is (not as the upstream version)

2021-01-13 17:33 UTC, Kaffeine commented on src/game/server/gamecontroller.cpp
> +int64 IGameController::GetMaskForPlayerWorldEvent(int, int ExceptID)
Done

2021-01-13 17:34 UTC, Kaffeine commented on src/game/client/gameclient.cpp
> +		vec2 ClosestPoint = closest_point_on_line(HookPos, NewPos, Position);
I restored the previous `closest_point_on_line()` implementation.

2021-01-13 17:35 UTC, Kaffeine commented on src/base/vmath.h
> +
>This change has the potential to affect gameplay

I restored the previous GetAngle() implementation. The main goal here is to have the same API (e.g. function name and the header file).

2021-01-13 18:05 UTC, Kaffeine commented
Oh. Check-style failed on `datasrc/network.py`. I have no idea what could be wrong. My diff to the yesterday "v1" version https://github.com/ddnet/ddnet/commit/fbb690ec7fd164b992a556ee5abd23e0fbf00316:

```
$ git diff fbb690e..9bc562e --stat
 src/base/vmath.h                         | 59 +++++++++++++++++++++++++++++++++++++----------------------
 src/game/client/components/items.cpp     |  5 +++--
 src/game/client/gameclient.cpp           | 15 +++++++++------
 src/game/client/prediction/gameworld.cpp | 30 ++++++++++++++++++------------
 src/game/gamecore.cpp                    | 17 ++++++++++-------
 src/game/server/gamecontroller.cpp       |  4 ++--
 src/game/server/gamecontroller.h         | 21 +++------------------
 src/game/server/gameworld.cpp            | 32 +++++++++++++++++++-------------
 8 files changed, 101 insertions(+), 82 deletions(-)
```

(mostly `closest_point_on_line` and the comments)

2021-01-13 18:06 UTC, heinrich5991 commented
See #3507, not your fault.

2021-01-16 00:24 UTC, Kaffeine commented
The PR is ready for (re)review and maybe merge.

2021-01-17 13:55 UTC, Learath2 commented
I like all of these. I have one question: What is the motivation behind `GameController::HandleCharacterTiles`? 

Structurally the more sane approach to this would be the collision code calling into the entities when they touch a tile, which would be a rather large rework. Until that is there really much value of moving this around?

2021-01-17 14:30 UTC, Kaffeine commented
> What is the motivation behind `GameController::HandleCharacterTiles`?

The main motivation is to get rid of `&((CGameControllerDDRace *)GameServer()->m_pController)->` references from the codebase and make it possible to base another mod on top of DDNet without commenting-out a lot of racing-related code here, there, and somewhere else.

I have a (legacy) mod codebase on the upstream 0.6 version and I tried to reengineer it on top of upstream 0.7. Now I'm backporting the 0.7 stuff to DDNet to make the port easier, but the task is still harder (than the base on the upstream) because of the racing code spread through the codebase in both expected and very unexpected places.

I'm OK with (/would not care about) the extra tiles such as accelerators, doors, and all other stuff that extends the base game physics.

>Structurally the more sane approach to this would be the collision code calling into the entities when they touch a tile, which would be a rather large rework.

I also tried to add two methods:
```
virtual void OnCharacterTouchEntity(class CCharacter *pChr, int TileIndex);
virtual void OnCharacterCloseToEntity(class CCharacter *pChr, int TileIndex);
```
This results in much better code, like:
```diff
-if(((m_TileIndex == TILE_FINISH) 
-    || (m_TileFIndex == TILE_FINISH) 
-    || FTile1 == TILE_FINISH 
-    || FTile2 == TILE_FINISH 
-    || FTile3 == TILE_FINISH 
-    || FTile4 == TILE_FINISH 
-    || Tile1 == TILE_FINISH 
-    || Tile2 == TILE_FINISH 
-    || Tile3 == TILE_FINISH 
-    || Tile4 == TILE_FINISH) && PlayerDDRaceState == DDRACE_STARTED)
+if((TileIndex == TILE_FINISH) && PlayerDDRaceState == DDRACE_STARTED)
```
but then I realized that such code can introduce regressions/bugs on maps that rely on the order of the checks.
I can restore the code but the reorder can be dangerous.

2021-01-17 14:56 UTC, Kaffeine commented
> Structurally the more sane approach to this would be the collision code calling into the entities when they touch a tile, which would be a rather large rework

@Learath2: This is how it can look like:
https://github.com/InfectionDust/ddnet/compare/ddnet-refactor-base...InfectionDust:ddnet-refactor-handle-tiles

No much rework and I like it very much; it was my first approach. But I should repeat: it can trigger bugs because of reordering. E.g.:

```
int FTileIndex = TILE_START;
int TileIndex = TILE_FINISH;
```
The old code would process `TILE_START` and then `TILE_FINISH`. The new code will process `TileIndex` (and thus `TILE_FINISH`) before `FTileIndex` (`TILE_START`).

2021-01-17 19:38 UTC, Learath2 commented
I see what you mean. We should merge as-is for now, a more comprehensive rework or reordering requires more testing and thinking :)

2021-01-17 20:18 UTC, Kaffeine commented
> I see what you mean. We should merge as-is for now, a more comprehensive rework or reordering requires more testing and thinking :)

I think that a map should not rely on the order of the checks. It makes little sense to place controversial or order-dependent tiles at the same index. The order should be treated as undefined, like [C++ undefined behavior](https://en.cppreference.com/w/cpp/language/ub). But probably we still should care about those who rely on our "UB" or at least we should think twice.

> We should merge as-is for now

Probably :).

> How about the checklist, at a first glance it looks like it only moved things around but it'd be nice to know that you've tested atleast the basics, starting/finishing a race, etc.

I will do some testing tomorrow — I just wanted some ACK before spending my time on the checks (if I would get some negative acknowledgment it'll be better for me to not spend another 30-40 minutes on the server setup (I don't have such a host setup for ten years)).

2021-01-17 20:20 UTC, Kaffeine commented
@heinrich5991, are you OK with the code now (see [v2 details](https://github.com/ddnet/ddnet/pull/3502#issuecomment-759622381)), so it makes sense to test it?

2021-01-17 20:24 UTC, Learath2 commented
> I think that a map should not rely on the order of the checks. It makes little sense to place controversial or order-dependent tiles at the same index. The order should be treated as undefined, like [C++ undefined behavior](https://en.cppreference.com/w/cpp/language/ub). But probably we still should care about those who rely on our "UB" or at least we should think twice.

In an ideal world, yes but ddnet has a loong history and the mappers have mostly been unchecked for most of it. So any and all physics checks need quite a bit of scrutiny to make sure we don't break ranks or maps.

Order is veeery unlikely to break anything, but it'd still make me less certain about merging this

2021-01-17 21:57 UTC, heinrich5991 approved these changes
>@heinrich5991, are you OK with the code now (see v2 details), so it makes sense to test it?

@Kaffeine I'm okay with these changes now. :) It makes sense to test it now.

2021-01-19 19:40 UTC, Kaffeine commented
I tested the changes and found a terrible bug due to one missing line. I didn't call the `IGameController::OnCharacterSpawn(pChr);` in `CGameControllerDDRace::OnCharacterSpawn(CCharacter *pChr)` thus the Character had no HP and no ammo (the char had full armor nonetheless).

I fixed the commit and think that now PR is ready to land.

2021-01-21 10:56 UTC, Learath2 approved these changes
LGTM, thanks for some much needed cleanup

bors r+

2021-01-21 11:05 UTC, merged

2022-05-04 12:25 UTC, C0D3D3V commented
Is there a real reason for `GameController::GetMaskForPlayerWorldEvent()`
Or are you ok with it if I remove it again and replace it with `m_pCharacter->TeamMask()`
for all of these:
https://github.com/ddnet/ddnet/commit/c28bd693d3b8782a3b8ef824aae0e6c70ecb5bb7

2022-05-04 13:39 UTC, Kaffeine commented
The idea is to decouple the classes. Why would you want to couple them again?
The less classes know about each other (to some reasonable degree of course), the easier it is to change them.

Personally I don't see `teeworlds` as a good upstream for the mods, I would prefer to cleanup `ddnet` codebase and use it as the upstream instead. I would prefer to have DDNet gameplay related features concentrated in a few classes, rather then spread through the entire codebase.

What's wrong with `GameController::GetMaskForPlayerWorldEvent()`? It is up to the game controller to decide if the game mode has teams with separated events. Some game controllers need to mask the events, some do not. How it is the base `CPlayer` business?

2022-05-04 13:46 UTC, C0D3D3V commented
It is the same method just a longer name... The dependency to the character is from nature already there. But I do not have something against it, if you thing any mod can do something good with that.

2022-05-04 13:52 UTC, C0D3D3V commented
The method only felt into my eye, as I cleaned up the use of Team()->TeamMask(...)
here https://github.com/ddnet/ddnet/pull/5063/commits/e73f125093a0d691c3c2dff8030eb8b0c67aa4c3 and https://github.com/ddnet/ddnet/pull/5063/commits/e73f125093a0d691c3c2dff8030eb8b0c67aa4c3

thats all. If this helps other mods to write independent code then I think it's good.

2022-05-04 15:57 UTC, Kaffeine commented
I see, the `TeamMask()` is now directly available in `CCharacter`, so at least we won't have to put back `#include <game/server/teams.h>`.
Okay, I think this also works for me.
I tried to make it easier to entirely remove `CGameTeams`. With your change the modders can cut it off in the single place in `CCharacter`, so this is good enough. And also hm, now I do *not* think that `CGameTeams` is that huge and bad. Previously I though that it is necessary to remove it if it is not used (in the modified gameplay).
---
Side note: personally I think that GameController is not enough to do a significant modification. Ideally I see us having basic gameplay in CPlayer / CCharacter / CGameController (which is actually `IGameController`), and then we can encapsulate the mod gameplay into C<Mod>Player / C<Mod>Character / C<Mod>GameController using methods override.

I actually do this in a mod I currently maintain. I added `virtual CPlayer *IGameController::CreatePlayer(int ClientID)` and `CInfClassGameController::CreatePlayer() override`  returns `CInfClassPlayer` instance. In its turn,  `CInfClassPlayer` overrides `void CPlayer:;TryRespawn()` and constructs `CInfClassCharacter` instead.

The basic game logic works as is, all gametype-specific modifications are done via virtual methods overload. The mod classes know about the mod game controller, so there is no ugly cast (like `&((CGameControllerDDRace *)GameServer()->m_pController)->` partially removed in this PR).