Get rid of the MySQL C++ connector as a dependency and disable C++ exceptions
ddnet/ddnet pull request #3568
Opened 2021-01-31 17:03 UTC by heinrich5991

We now use the C API directly. This has the advantage of using one
obscure dependency less, as the C++ connector also used the C API.

Also remove exceptions from database code.

The equivalent code with return codes is a human-assisted mechanical
translation of the old code, no attempts to improve correctness were
made.

This allows us to enable the -fno-exceptions flag.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2021-01-31 17:03 UTC, heinrich5991 commented
CC @Zwelf @Learath2

2021-02-20 22:25 UTC, heinrich5991 commented
Will rebase onto master if someone is willing to review this. @Learath2? :)

2021-02-20 23:55 UTC, Learath2 commented
I'm a little scared of this. I'll review it but no way I'm merging it unless you are available for a couple hours when we deploy it to fix bugs that may arise

2021-02-23 20:20 UTC, Learath2 commented on src/engine/server/databases/connection_pool.cpp
>  #include <stdexcept>
Since we now compile without exceptions I can't imagine this being too useful

2021-02-23 20:21 UTC, Learath2 commented on src/engine/server/databases/mysql.cpp
> +	dbg_assert(g_MysqlState.compare_exchange_strong(Initialized, MYSQLSTATE_SHUTTINGDOWN), "double MySQL free or free without initialization");
This is not safe as discussed

2021-02-23 20:21 UTC, Learath2 requested changes
Other than the asserts I'm fine with merging this, I can't spot any other issues by eye

2021-02-24 16:27 UTC, Learath2 requested changes
Kinda still concerned

2021-02-24 16:27 UTC, Learath2 commented on .github/workflows/build.yaml
> +        sudo apt-get install libboost-dev libmariadbclient-dev libwebsockets-dev -y
I think we don't need boost either now

2021-02-24 16:27 UTC, Learath2 commented on src/engine/server/databases/sqlite.cpp
> +	dbg_assert(!m_InUse.exchange(true), "Tried connecting while the connection is in use");
Don't think this assert is safe either

2021-02-24 16:34 UTC, Learath2 approved these changes
Okay, I can't spot anything else. Fingers very crossed

bors r+

2021-02-24 16:43 UTC, heinrich5991 commented
bors r=Learath2

2021-02-24 16:53 UTC, merged