Ddnet refactor
ddnet/ddnet pull request #3605
Opened 2021-02-08 21:44 UTC by Kaffeine

- Backport 'Make spectators stay specs on map changed'
- Adopt upstream refactoring: Mark several functions as 'const'
- CGameContext::SendVoteStatus: Hide the trick for 64 clients
- GameController: Add OnPlayerConnect() like in the upstream
- Move DDRace-specific player initialization code to the Controller. Dependencies:
  - CGameControllerDDRace: Add Score() getter
  - Get rid of gamemode.h with confusing/conflicting definitions (re-defined `GAME_NAME`)
- Replace remaining int64_t by int64 for the sake of consistency

I checked the changes in-game (I ran a server and tested with two players)

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2021-02-08 22:32 UTC, heinrich5991 requested changes
Looked through the changes, they look good. Only one note and one commit I don't like.

2021-02-08 22:32 UTC, heinrich5991 commented on src/game/server/gamemodes/DDRace.cpp
> +	m_pGameType = g_Config.m_SvTestingCommands ? TEST_TYPE_NAME : GAME_TYPE_NAME;
You could inline the strings directly I guess.

2021-02-08 22:32 UTC, heinrich5991 commented on src/engine/server/server.cpp
> +			if((pPacket->m_Flags & NET_CHUNKFLAG_VITAL) != 0 && (m_aClients[ClientID].m_State == CClient::STATE_CONNECTING || m_aClients[ClientID].m_State == CClient::STATE_CONNECTING_AS_SPEC))
I don't like making the engine aware of spectator vs non-spectator: https://github.com/teeworlds/teeworlds/pull/2066. Can we skip this commit?

2021-02-08 23:08 UTC, Kaffeine commented on src/engine/server/server.cpp
> +			if((pPacket->m_Flags & NET_CHUNKFLAG_VITAL) != 0 && (m_aClients[ClientID].m_State == CClient::STATE_CONNECTING || m_aClients[ClientID].m_State == CClient::STATE_CONNECTING_AS_SPEC))
I saw your PR. The ability to keep spectators is crucial for the mod I'm maintaining now. I guessed that as you didn't merge your code here, then it's better to have the upstream version than nothing. I also can keep this patch in the mod branch though having no `CGameContext::IsClientSpectator` () is unfortunate. Maybe we can merge your PR to DDNet? Or would you prefer if I cherry-pick and add it to this PR?

2021-02-08 23:11 UTC, Kaffeine commented on src/game/server/gamemodes/DDRace.cpp
> +	m_pGameType = g_Config.m_SvTestingCommands ? TEST_TYPE_NAME : GAME_TYPE_NAME;
It depends. We have this few lines below:
```cpp
GameServer()->SendChatTarget(ClientID, "DDraceNetwork Mod. Version: " GAME_VERSION);
```
I'm wondering why we don't use any of `GAME_TYPE_NAME` (="DDraceNetwork") or `GAME_NAME` (="DDNet") definition here.

2021-02-20 16:39 UTC, heinrich5991 commented on src/engine/server/server.cpp
> +			if((pPacket->m_Flags & NET_CHUNKFLAG_VITAL) != 0 && (m_aClients[ClientID].m_State == CClient::STATE_CONNECTING || m_aClients[ClientID].m_State == CClient::STATE_CONNECTING_AS_SPEC))
I'd prefer not introducing state in the engine for the game. With my patch applied, it'd work for me.

2021-02-23 16:37 UTC, Kaffeine commented
- "Move DDRace-specific player initialization code to the Controller" rebased after c79bb91b16c19f27d24c908eaa9e08f9cfed1378
- Added more cleanups related to int64 (get rid of unneeded typedefs for MSVC)
- Changes from https://github.com/teeworlds/teeworlds/pull/2066 adopted into commit "Make spectators stay specs on map changed"

2021-02-23 18:15 UTC, heinrich5991 approved these changes

2021-02-23 18:16 UTC, heinrich5991 commented
Thanks for your efforts. :)

bors r+

2021-02-23 18:32 UTC, merged