Further fixes for Haiku
ddnet/ddnet pull request #3783
Opened 2021-04-18 12:21 UTC by panos

- Haiku is Unix-like, but it still doesn't use libnotify.
- Haiku comes with its own sets of definitions for certain long variables. There's still a problem revolving around the variables, but I removed a duplicate, conflicting definition on the Haiku platform.
- Changed some definition-related logic in detect.h, because the gcc compiler in Haiku (version 8.3.0) complained about duplicate definitions. I chose to use 'unknown' rather than an empty string.

I think that I'm very close.

2021-04-18 13:38 UTC, def- commented
The Windows linking error looks related, please fix

2021-04-18 14:09 UTC, panos commented
Don't mess with prefixes and suffixes!

2021-04-18 14:12 UTC, panos commented
The game builds just fine on 32-bit, but it doesn't compile on 64-bit just yet due to a variable-related bug in Haiku that was actually detected thanks to this game. I brought this up in the IRC.

Moreover, just like Teeworlds, the game launches with a black screen.

2021-04-18 14:27 UTC, panos commented
Had to change the size of:

https://github.com/panos/ddnet/blob/01393ed9bb19bf3a620f1a4975a14d3fd35820ed/src/game/client/components/chat.h#L103
https://github.com/panos/ddnet/blob/01393ed9bb19bf3a620f1a4975a14d3fd35820ed/src/game/client/components/chat.cpp#L105

Since this is an array, I'm very skeptical as to whether using a 64-bit long variable type is the right decision.

There's also https://github.com/haikuports/haikuports/issues/5838, which unfortunately also applies to ddnet.

2021-04-18 18:14 UTC, panos commented
[`detect.h`](https://github.com/ddnet/ddnet/pull/3783/files#diff-86d59021cb4561b3911602552aed980edc3ddf8b4846d5e59f09b3e863fff8e5) seems to be breaking the Windows build, not sure why as of this moment.

2021-04-18 22:48 UTC, def- requested changes

2021-04-18 22:48 UTC, def- commented on src/base/detect.h
> +#define CONF_PLATFORM_STRING "unknown"
This seems wrong. Why did you remove the #define?

2021-04-19 02:30 UTC, panos commented on src/base/detect.h
> +#define CONF_PLATFORM_STRING "unknown"
I wasn't sure why that existed (now I think I am, despite not being sure what the function is, in all honesty), but gcc 8.3.0 complained about a duplicate definition and I did that as an experiment.

The compiler *on Haiku* stopped complaining, but that doesn't seem to be the case with the Windows CI...

2021-05-17 06:53 UTC, panos commented
FYI: This isn't stale yet, I'll have more time to work on this in a few months since this is a huge headache.

2021-05-31 06:34 UTC, panos commented on src/base/detect.h
> +#define CONF_PLATFORM_STRING "unknown"
Hey, do you mind telling me what the `#define` is useful for in the first place?

I'm not sure I get it.

2021-05-31 06:35 UTC, panos commented on src/base/detect.h
> +#define CONF_PLATFORM_STRING "unknown"
I could just create a complicated if... else statement that would use my changes in Haiku and the `#define` part elsewhere, or something, but that would likely a) not work, b) it would look awful.

2021-05-31 07:18 UTC, def- commented on src/base/detect.h
> +#define CONF_PLATFORM_STRING "unknown"
It's used to identify the client. Just don't set CONF_PLATFORM_STRING "haiku" at all (remove line 90), then you don't have to change the definition of CONF_PLATFORM_STRING.

2021-06-08 15:58 UTC, panos commented
Have not tested this change (or all of my changes, since I haven't gotten a build for Haiku to fully run and function), just checking whether it will successfully build. Please do not merge yet.

2021-08-14 13:16 UTC, Jupeyy commented
We cleaned the int64 stuff up, if you still want to try to fix the remaining stuff, go ahead

2021-08-23 14:55 UTC, panos commented
> We cleaned the int64 stuff up, if you still want to try to fix the remaining stuff, go ahead

Immensely helpful. I'll rebase on top of your changes and check if this works whenever I can.

2021-09-13 11:05 UTC, heinrich5991 commented
Status: Needs to be rebased, but @panos indicated interest.

2021-09-13 12:47 UTC, panos commented
Tried rebasing, not sure if it went well as I used the GitHub client because I'm not currently using my ordinary development environment.

2021-09-13 13:03 UTC, panos commented
Trying again after using a suitable environment. Some outstanding issues, such as "what do I do with Windows?", will probably still stand. The change has not been adequately tested.

2021-09-13 13:04 UTC, panos commented
Okay, give me just a bit because I think that I'm doing this in a bit of a panicked "I completely forgot about this project and need to get done with it ASAP" manner, which is why this is so low-quality.

2021-09-13 13:08 UTC, panos commented
I actually tried compiling this on a Linux environment before pushing (successfully), Haiku testing is something to be done.

2021-09-13 13:14 UTC, panos commented
Compiles successfully on a default Haiku installation!!!

Currently, only a black screen shows up, but I presume it's because Mesa is running a bit behind right now. Should be fine in the long run, but I need to test this further. Apart from the style fixes, I'm waiting to see if the Windows build is going to break.

2021-09-13 13:30 UTC, panos commented
Okay, should be good to go for the most part. Haven't managed to reach that part where I take pride in a screenshot yet, but this batch of changes is ready to be reviewed.

2021-09-13 15:12 UTC, heinrich5991 reviewed
Code still needs to be formatted with clang-format.

2021-09-13 15:12 UTC, heinrich5991 commented on src/base/detect.h
> +#define CONF_PLATFORM_STRING "unknown"
The changes in line 182 to 188 should probably be reverted.

2021-09-13 17:36 UTC, panos commented on src/base/detect.h
> +#define CONF_PLATFORM_STRING "unknown"
Breaks like earlier. Is removing `CONF_PLATFORM_STRING "haiku"` ***really*** a good idea? Not sure if this is going to cause trouble later down the line.

![2021-09-13_19-33](https://user-images.githubusercontent.com/30193966/133130233-50c2aa1a-6008-4110-8918-227423c26d75.png)

2021-09-13 17:47 UTC, Jupeyy commented on src/base/detect.h
> +#define CONF_PLATFORM_STRING "unknown"
its bcs you have a typo

`#define CONF_PLATFORM_STRING "haiku"`
should be
`#define PLATFORM_STRING "haiku"`

2021-09-13 18:00 UTC, panos commented on src/base/detect.h
> +#define CONF_PLATFORM_STRING "unknown"
;_;

thanks for the catch, I'll try again!

2021-09-13 19:14 UTC, def- commented
bors r+

2021-09-13 19:18 UTC, panos commented
> bors r+

thanks, left clang-format running in the background but forgot about it, I'll have to test this on Haiku again though because I have some concerns

2021-09-13 19:21 UTC, panos commented
I have no idea why, but this is what happens now. It didn't happen previously.

![2021-09-13_21-21](https://user-images.githubusercontent.com/30193966/133143830-f5ef9e54-0b78-4261-b475-3ff16c753c56.png)

2021-09-13 19:36 UTC, merged

2021-09-13 19:38 UTC, Jupeyy commented
> I have no idea why, but this is what happens now. It didn't happen previously.

try to use master branch with a clean build dir, i don't see why it shouldn't work