Add hammer_hit_fire_delay tune
ddnet/ddnet pull request #3792
Opened 2021-04-25 09:30 UTC by def-

as requested by J$ON for new map with Genex

the current hammer_fire_delay is only used when no other tee has been
hit. In order not to change any existing behaviour I have added a new
tune for the case of hitting, instead of making the existing one control
both.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2021-04-25 15:28 UTC, heinrich5991 commented
What is that map about? Will that tune be reused in maps?

I'm skeptical about adding code for just one map.

2021-04-25 16:40 UTC, twJSON commented
> What is that map about? Will that tune be reused in maps?
> 
> I'm skeptical about adding code for just one map.

Hey heinrich, the tune command is needed to force the hitfly technique which is used for the whole map. otherwise people could just use speedfly instead, to cheat the parts. delaying the hammer is the only possible way to force that technique. we are planning on continueing the map series, since i think it will be a hit on ddnet, because there is no map yet using/forcing that method. in future maps, parts could be mapped to use this technique in even single parts and gives a new flait to the maps

2021-04-25 16:48 UTC, def- commented
The alternative would be to use the same hammer_fire_delay tune for both values, but with a factor inbetween for the hit case. I think this wouldn't work for the map though.

2021-04-30 15:54 UTC, def- commented
@Learath2 @heinrich5991 ping. @twJSON still wants to use this for upcoming tournament map.

2021-04-30 16:08 UTC, Learath2 commented
I see this as more of a shortcoming of how this was initially coded. The after hit delay should have been a factor of the non-hit one or this tuning should have existed from the start.

I'm okay with merging this

2021-04-30 16:32 UTC, def- commented
> I'm against adding features for single maps.

Then we would have no new map features at all, would we? I added most DDNet map features in cooperation with a mapper making a single map for it.

2021-04-30 17:13 UTC, heinrich5991 commented
> Then we would have no new map features at all, would we? I added most DDNet map features in cooperation with a mapper making a single map for it.

Can you give an example? AFAIK jetpack gun, doors, draggers, blockers were not implemented for a single map.

I'd base that decision on gameplay, not on "a mapper asked me to do a feature".

2021-04-30 17:19 UTC, Learath2 commented
> > Then we would have no new map features at all, would we? I added most DDNet map features in cooperation with a mapper making a single map for it.
> 
> Can you give an example? AFAIK jetpack gun, doors, draggers, blockers were not implemented for a single map.
> 
> I'd base that decision on gameplay, not on "a mapper asked me to do a feature".

Telegun was one like this iirc

2021-04-30 17:22 UTC, def- commented
Well, if you want to go by what change makes sense, then currently there is no way to control the delay of hammer hit when hitting tee, so independent of the map there should be a way, since there is one for every other weapon.

2021-05-01 14:28 UTC, heinrich5991 requested changes
Given that we want this, two comments. One makes the code more complicated, one gives the illusion of accuracy.

2021-05-01 14:28 UTC, heinrich5991 commented on src/game/server/gamecontext.cpp
> +			Last = 44;
Judging from the code on the client side, I see no reason not to send the whole tune params. It just ignores extra data.

2021-05-01 14:28 UTC, heinrich5991 commented on src/game/tuning.h
> +MACRO_TUNING_PARAM(HammerHitFireDelay, hammer_hit_fire_delay, 333, "Delay of hammering (when hitting another tee)")
Can we make it to 320 to represent the fire delay more accurately? Only increments of 20ms work (due to the 50 Hz ticks).

2021-05-01 14:43 UTC, heinrich5991 approved these changes

2021-05-01 14:43 UTC, heinrich5991 commented
Thanks.

bors r+

2021-05-01 14:53 UTC, merged