Display colors for strong / weak hook states
ddnet/ddnet pull request #3960
Opened 2021-07-20 19:19 UTC by BloodWod

Off by default, cl_nameplates_strongweak 1 to enable;
Also shown in debug mode (ctrl-shift-d);
You can change the colors in the HUD.
## Checklist

- ![hkUp2p8chGA](https://user-images.githubusercontent.com/33897884/126379859-1dc29c09-57fb-4d4b-9810-a4f0b09599a0.jpg)
![WCZx_ZR8fQ0](https://user-images.githubusercontent.com/33897884/126379863-3f25295a-ca36-4184-a0ed-1946b40ed967.jpg)

- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2021-07-20 19:35 UTC, heinrich5991 commented
Hello @BloodWod, thanks for your first pull request. I think the coloring is a good idea.

You add three config options for this feature. We already have 11 confiig options regarding nameplates, I don't really want to increase this number. Config options make it harder to modify the code, because more combinations have to be tested. Especially around nameplates, 11 options is basically impossible to test exhaustively. Would it be possible to drop these config options?

2021-07-20 19:37 UTC, BloodWod commented
> Hello @BloodWod, thanks for your first pull request. I think the coloring is a good idea.
> 
> You add three config options for this feature. We already have 11 confiig options regarding nameplates, I don't really want to increase this number. Config options make it harder to modify the code, because more combinations have to be tested. Especially around nameplates, 11 options is basically impossible to test exhaustively. Would it be possible to drop these config options?

I think they should just be renamed, I can do it

2021-07-20 19:47 UTC, BloodWod commented
Is this option suitable?
cl_strongweak_state (Show strong and weak players)
cl_strong_state_color(Strong player color)
cl_weak_state_color(Weak player color)

2021-07-22 15:31 UTC, BloodWod-513 commented
if the color choice is not so important, then it seems to me that a bind for on/off mode would look good

2021-08-10 23:00 UTC, BloodWod-513 commented
I think it's worth introducing a binding for this on/off function. I also asked the players, they think it's useful, and when I got used to it, I couldn't play without it. Also, as an option, you can change the numbers to some other option, possibly graphical...
What do you think about this?

2021-08-11 08:41 UTC, Jupeyy reviewed
I'd say we could test this out, looks like a QOL improvement

2021-08-11 08:41 UTC, Jupeyy commented on src/game/client/prediction/entities/character.h
> +	bool m_Weak;
Could you initialize this value in the constructor or in `ResetPrediction`

2021-08-11 08:41 UTC, Jupeyy commented on src/game/client/components/nameplates.cpp
> +			if(pPlayerInfo->m_Local || !m_pClient->m_GameWorld.m_WorldConfig.m_IsDDRace)
Any reason to disallow it for non ddrace?
Guess it doesn't hurt anybody, even if the server fixed strong/weak

2021-08-11 11:02 UTC, BloodWod-513 commented on src/game/client/components/nameplates.cpp
> +			if(pPlayerInfo->m_Local || !m_pClient->m_GameWorld.m_WorldConfig.m_IsDDRace)
Hi, thank you for your feedback. At first I didn't do this check, but then I got to such servers as KoG, fng and others, and in theory we can't predict how this system will be changed there, as a result, m_StrongWeakID = 0 was for everyone and all were red, I decided that for now it's better to put a check on the mod and leave the white color

2021-08-11 11:31 UTC, BloodWod-513 commented
I think it looks better now. I will also insist on making the cl_show_weakness bind xd

2021-08-11 13:45 UTC, Jupeyy commented on src/game/client/components/nameplates.cpp
> +			if(pPlayerInfo->m_Local || !m_pClient->m_GameWorld.m_WorldConfig.m_IsDDRace)
Mh yeah i see your problem, you'd need to check if the server sent extended data of the client, if you feel comfortable enough you could try that, or init m_StrongWeakID to -1 or smth more useful

2021-08-12 10:30 UTC, BloodWod-513 commented on src/game/client/components/nameplates.cpp
> +			if(pPlayerInfo->m_Local || !m_pClient->m_GameWorld.m_WorldConfig.m_IsDDRace)
In general, now when you go to the server where the hook system is changed (everyone is given a strength hook, I saw 0 servers where everyone is given a weak hook) if everyone has strongweakid = 0, then everyone will be highlighted in green, which means the truth.

2021-08-12 11:24 UTC, BloodWod-513 commented
![image](https://user-images.githubusercontent.com/33897884/129188976-ff22e310-0f58-4d56-ae3c-b896c87c404a.png)
![image](https://user-images.githubusercontent.com/33897884/129188986-0125c767-817e-418b-82db-079585193488.png)

2021-08-12 11:27 UTC, Jupeyy commented on src/game/client/components/nameplates.cpp
> +			if(pPlayerInfo->m_Local || !m_pClient->m_GameWorld.m_WorldConfig.m_IsDDRace)
but on vanilla this won't work, or does it?

2021-08-12 15:33 UTC, BloodWod-513 commented on src/game/client/components/nameplates.cpp
> +			if(pPlayerInfo->m_Local || !m_pClient->m_GameWorld.m_WorldConfig.m_IsDDRace)
As I understand it, the DetectStrongHook method is used on vanilla, and it is checked only when using hook. Need off this feature colors on vanilla servers, because if the server does not send extended data, but then everything will be displayed correctly on servers such as fng or KoG

2021-08-12 15:33 UTC, BloodWod-513 commented on src/game/client/components/nameplates.cpp
> +			if(pPlayerInfo->m_Local || !m_pClient->m_GameWorld.m_WorldConfig.m_IsDDRace)
I don't know how right I am

2021-08-12 17:39 UTC, BloodWod-513 commented on src/game/client/components/nameplates.cpp
> +			if(pPlayerInfo->m_Local || !m_pClient->m_GameWorld.m_WorldConfig.m_IsDDRace)
Then it turns out that if extended data is not sent, then we remove the display of colors?

2021-08-12 17:44 UTC, Jupeyy commented on src/game/client/components/nameplates.cpp
> +			if(pPlayerInfo->m_Local || !m_pClient->m_GameWorld.m_WorldConfig.m_IsDDRace)
Yes, i think that makes most sense,
strong weak is mostly important for ddrace
for strong only servers we could still invent another capability and add it to the client prediction

2021-08-12 18:17 UTC, BloodWod-513 commented on src/game/client/components/nameplates.cpp
> +			if(pPlayerInfo->m_Local || !m_pClient->m_GameWorld.m_WorldConfig.m_IsDDRace)
Okay I heard you

2021-08-12 18:24 UTC, BloodWod-513 commented on src/game/client/components/nameplates.cpp
> +			if(pPlayerInfo->m_Local || !m_pClient->m_GameWorld.m_WorldConfig.m_IsDDRace)
Now the display of numbers and colors works only on servers where there is extended data

2021-08-13 22:59 UTC, BloodWod-513 commented
![image](https://user-images.githubusercontent.com/33897884/129425571-3fe1e579-5f4f-48f8-a720-6c35b120eaaf.png)

2021-08-14 12:53 UTC, edg-l commented
Can you rename strongweak.png to strong_weak.png to follow the naming convention of other files?

2021-08-14 12:58 UTC, Jupeyy commented on src/game/client/components/nameplates.cpp
>  		if(pCharacter)
Would be nice to check m_HasExtendedData for the target character too, prevent edge cases

2021-08-14 13:39 UTC, gerdoe-jr commented on src/game/client/components/nameplates.cpp
>  		if(pCharacter)
Can you give an example of edge case?

2021-08-14 13:42 UTC, Jupeyy commented on src/game/client/components/nameplates.cpp
>  		if(pCharacter)
> Can you give an example of edge case?

As far as i can see the server can send extended data per character

2021-08-14 13:59 UTC, BloodWod-513 commented on src/game/client/components/nameplates.cpp
>  		if(pCharacter)
I don't understand a little, because this condition works for every player

2021-08-14 14:07 UTC, Jupeyy commented on src/game/client/components/nameplates.cpp
>  		if(pCharacter)
I dunno, i see `m_Snap.m_aCharacters[Item.m_ID].m_HasExtendedData = true;` in the code, so looks like its per character.
The StrongWeakID also doesnt respect it(not your fault)

2021-08-14 14:19 UTC, BloodWod-513 commented on src/game/client/components/nameplates.cpp
>  		if(pCharacter)
On vanilla, fng and kog it's false. Or I don't quite understand the problem due to the language barrier

2021-08-14 14:24 UTC, Jupeyy commented on src/game/client/components/nameplates.cpp
>  		if(pCharacter)
yeah nvm i'm just very picky rn, just wait for other reviews

2021-08-16 13:42 UTC, Learath2 requested changes
Overall good idea but I don't like the extra variable, less sources of truth the better.

2021-08-16 13:42 UTC, Learath2 commented on src/game/client/prediction/entities/character.h
> +	bool m_Weak;
I don't like this redundant variable

2021-08-16 13:42 UTC, Learath2 commented on src/game/client/components/nameplates.cpp
> +	if((g_Config.m_Debug || g_Config.m_ClNameplatesStrong) && m_pClient->m_Snap.m_aCharacters[pPlayerInfo->m_ClientID].m_HasExtendedData)
You need to check that both the local player and the target player has extended data

2021-08-16 13:42 UTC, Learath2 commented on src/game/client/components/nameplates.cpp
> +				if(pCharacter->m_Weak)
Just get the strongweakid of the local character and compare that to the strongweakid of `pCharacter` here.

2021-08-17 15:33 UTC, BloodWod-513 commented on src/game/client/components/nameplates.cpp
> +	if((g_Config.m_Debug || g_Config.m_ClNameplatesStrong) && m_pClient->m_Snap.m_aCharacters[pPlayerInfo->m_ClientID].m_HasExtendedData)
Okay, I'm checking like this or need to check m_HasExtendedData when there is pPlayerInfo->m_Local
if(m_pClient->m_Snap.m_aCharacters[pPlayerInfo->m_ClientID].m_HasExtendedData && m_pClient->m_Snap.m_aCharacters[m_pClient->m_Snap.m_LocalClientID].m_HasExtendedData)

But I don't understand what is the point if this is done for every player, including the local one?

2021-08-23 11:33 UTC, Learath2 commented on src/game/client/gameclient.cpp
> +	if(pLocalChar && !m_Snap.m_SpecInfo.m_Active && Client()->State() != IClient::STATE_DEMOPLAYBACK && (m_Tuning[g_Config.m_ClDummy].m_PlayerCollision || m_Tuning[g_Config.m_ClDummy].m_PlayerHooking))
Hm, what happened here?

2021-08-23 21:18 UTC, BloodWod-513 commented on src/game/client/gameclient.cpp
> +	if(pLocalChar && !m_Snap.m_SpecInfo.m_Active && Client()->State() != IClient::STATE_DEMOPLAYBACK && (m_Tuning[g_Config.m_ClDummy].m_PlayerCollision || m_Tuning[g_Config.m_ClDummy].m_PlayerHooking))
This only worked with antiping enabled, I removed the antiping check and left the other conditions

2021-08-23 22:15 UTC, Jupeyy commented
LGTM now, should we get this in?

2021-08-24 12:19 UTC, Jupeyy commented
bors r+

2021-08-24 12:31 UTC, merged

2021-11-16 04:56 UTC, KRN-8 commented
I LOVE this !
but it doesnt work in any kind of Spectate view (spectate/pause/spec) ;-(