Team authorkill
ddnet/ddnet pull request #4005
Opened 2021-08-09 15:25 UTC by BloodWod-513

Allows only the team leader to press "kill".
TODO: You can add the on/off of the team leader in the future, and also the transfer of the leader by nickname.
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2021-08-09 15:37 UTC, BloodWod-513 commented
> What about... Timeout protection and kick from team. If guy will timeout or just kicked out of team. Did u test it? :D

If a person is not a leader, he can leave the team through a disconnect, and everyone will be alive. Need to create a timeout handler so that when the leader enters the timeout, another player becomes the leader

2021-08-09 15:44 UTC, Anime-pdf commented
> > What about... Timeout protection and kick from team. If guy will timeout or just kicked out of team. Did u test it? :D
> 
> If a person is not a leader, he can leave the team through a disconnect, and everyone will be alive. Need to create a timeout handler so that when the leader enters the timeout, another player becomes the leader

Use current one kekw
https://github.com/ddnet/ddnet/blob/94cfb332ae05e66e904e92cbb8ff7d35764e3eba/src/game/server/player.cpp#L222

2021-08-09 17:28 UTC, BloodWod-513 commented
> > > What about... Timeout protection and kick from team. If guy will timeout or just kicked out of team. Did u test it? :D
> > 
> > 
> > If a person is not a leader, he can leave the team through a disconnect, and everyone will be alive. Need to create a timeout handler so that when the leader enters the timeout, another player becomes the leader
> 
> Use current one kekw
> https://github.com/ddnet/ddnet/blob/94cfb332ae05e66e904e92cbb8ff7d35764e3eba/src/game/server/player.cpp#L222

That's about what I was talking about, thank you

2021-08-09 17:43 UTC, BloodWod-513 commented
test kick
![image](https://user-images.githubusercontent.com/33897884/128750052-0e6e59db-9bae-435b-b199-d29a8710f362.png)

2021-08-09 18:32 UTC, BloodWod-513 commented
timeout test
![image](https://user-images.githubusercontent.com/33897884/128756089-f462a65c-b890-4385-a3b5-aa19a3265cfd.png)

2021-08-14 13:11 UTC, Learath2 commented
Eh, this is a lot of work done without any prior discussion. Is this a desired change? The last attempt at this was by greyfox like 10 years ago and we removed it because it was just confusing.

2021-08-14 13:23 UTC, edg-l requested changes
i still dont know if this is useful at all, since most ppl that play in teams trust eachother

2021-08-14 13:23 UTC, edg-l commented on src/game/server/ddracechat.cpp
> +	if(Team > 0 && Team < MAX_CLIENTS)
i think it's better to check for the opposite and do an early return, we avoid unnecessary indents this way

2021-08-14 13:23 UTC, edg-l commented on src/game/server/ddracechat.cpp
> +		str_format(aBuf, sizeof aBuf, "'%s' transfer the leader to '%s'.", pSelf->Server()->ClientName(pResult->m_ClientID), pSelf->Server()->ClientName(Target));
The wording is a bit bad, maybe try:

`'%s' has transfered the team leader position to '%s'.`

2021-08-14 13:23 UTC, edg-l commented on src/game/server/ddracechat.cpp
> +			pSelf->SendChatTarget(pResult->m_ClientID, "You can't transfer the leader on to yourself.");
Better: `You are already the team leader.`

2021-08-14 13:23 UTC, edg-l commented on src/game/server/ddracechat.cpp
> +			pSelf->SendChatTarget(pResult->m_ClientID, "You can't become a leader without being found in a team.");
`You have to be in a team before becoming the team leader.`

2021-08-14 13:23 UTC, edg-l commented on src/game/server/ddracechat.cpp
> +			pSelf->SendChatTarget(pResult->m_ClientID, "You can't transfer a leader because you're not a leader.");
`You can't do this because you are not the team leader.`

2021-08-14 13:23 UTC, edg-l commented on src/game/server/ddracechat.cpp
> +		pSelf->SendChatTarget(pResult->m_ClientID, "You can't transfer a leader without being found in a team.");
`You have to be in a team before becoming the team leader.`

Also this looks like repeated code, maybe you can refactor it to a function.

2021-08-14 13:23 UTC, edg-l commented on src/game/server/gamecontext.cpp
> +					SendChatTarget(ClientID, "You can't kill the team because you're not the leader. If you want kill unlock team");
`You can't kill the team because you're not the leader. If you want to kill unlock the team`

2021-08-14 13:23 UTC, edg-l commented on src/game/server/teams.cpp
> +		if(Server()->GetNetErrorString(i)[0] && Team != 0)
Maybe add a comment here explaining that you are checking for players that are timed out or have disconnected and then transfering the leadership to make it clear what you are doing

2021-08-14 13:23 UTC, edg-l commented on src/game/server/teams.cpp
> +				str_format(aBuf, sizeof(aBuf), "Team leader '%s' has left/timeout this team, now the team leader is '%s'.",
`The team leader '%s' has left or got timeouted, the new team leader is '%s'.`

2021-08-14 17:04 UTC, BloodWod-513 commented
> i still dont know if this is useful at all, since most ppl that play in teams trust eachother

Well, a couple of people suggested this idea to me, and I decided that it doesn't look bad

2021-09-13 11:41 UTC, heinrich5991 commented
I think for adding a feature like this, an issue should be created first. As-is, I don't think this feature is useful enough to add it to the code.

2021-09-13 11:41 UTC, closed without merging