log git revision hash to stdout/console
ddnet/ddnet pull request #4089
Opened 2021-08-16 14:37 UTC by edg-l

Fixes #3963

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2021-08-16 16:16 UTC, Learath2 requested changes

2021-08-16 16:16 UTC, Learath2 commented on src/game/server/gamecontext.cpp
> +	Console()->Print(IConsole::OUTPUT_LEVEL_STANDARD, "git-revision", GIT_SHORTREV_HASH);
```suggestion
	if(GIT_SHORTREV_HASH)
		Console()->Print(IConsole::OUTPUT_LEVEL_STANDARD, "git-revision", GIT_SHORTREV_HASH);
```

2021-08-16 16:29 UTC, edg-l commented on src/game/server/gamecontext.cpp
> +	Console()->Print(IConsole::OUTPUT_LEVEL_STANDARD, "git-revision", GIT_SHORTREV_HASH);
i thought about it after making the commit, i guess it can really not exist

2021-08-20 15:12 UTC, def- commented
bors r+

2021-08-20 15:27 UTC, merged