Kill unfinishable teams if they don't enter /practice within a minute
ddnet/ddnet pull request #4148
Opened 2021-09-10 16:26 UTC by heinrich5991

This is to avoid players playing in unfinishable teams for a long time
if they don't understand the system messages.

Fixes #4088.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2021-09-11 10:01 UTC, Learath2 requested changes

2021-09-11 10:01 UTC, Learath2 commented on src/game/server/teams.cpp
> +		m_TeamSentStartWarning[m_Core.Team(ClientID)] = false;
Duplicate line

2021-09-11 18:23 UTC, heinrich5991 commented on src/game/server/ddracechat.cpp
> +	SendChatTarget(Team, aBuf);
Done.

2021-09-11 18:24 UTC, heinrich5991 commented on src/game/server/teams.cpp
> +		m_TeamSentStartWarning[m_Core.Team(ClientID)] = false;
Oh, that's actually a bug, a different line needs to go there. Nice find.

2021-09-13 11:03 UTC, Learath2 commented
LGTM

bors r+

2021-09-13 11:13 UTC, merged

2021-09-14 07:34 UTC, murpii commented
@heinrich5991 The warning message is abit to long:

![image](https://user-images.githubusercontent.com/60477660/133215069-1e980b97-6355-4f54-8c35-3cb0873b46b6.png)

2021-09-14 22:56 UTC, heinrich5991 commented
Ah, this is in the console. Should I try and put it into two lines?

2021-09-15 07:22 UTC, murpii commented
> Ah, this is in the console. Should I try and put it into two lines?

That would be great. It's also cut off in the regular chat.