Add option to highlight self in kill messages
ddnet/ddnet pull request #4188
Opened 2021-10-02 21:38 UTC by Azorlogh

Motivation: #4186

List of changes:
- Add options clKillMessageHighlightSelf, clKillMessageNormalColor, clKillMessageHighlightColor
- Rework HUD panel in settings

![hud_0](https://user-images.githubusercontent.com/17968319/135732345-b8152c74-f754-4722-9b60-46a1ba7cc9c8.png)

![hud_1](https://user-images.githubusercontent.com/17968319/135732346-814a918b-1828-4860-a3c7-372869b79575.png)

![in_game](https://user-images.githubusercontent.com/17968319/135732347-6e9cf148-29b8-4fc4-8dba-647e049f961a.png)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [x] Written a unit test if it works standalone, system.c especially (not standalone)
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2021-10-04 18:19 UTC, Jupeyy commented
Is `m_pLocalInfo` safe to use like this?
When I search it, every component NULL checks it

2021-10-05 12:16 UTC, Azorlogh commented
Indeed you're right. I switched to using m_LocalClientID instead which worse case scenario will be -1.

2021-10-05 15:29 UTC, heinrich5991 requested changes
Looks mostly good, thanks for the work.

In general, we try to minimize configuration options, but those for text colors are okay.

2021-10-05 15:29 UTC, heinrich5991 commented on src/game/variables.h
> +MACRO_CONFIG_INT(ClKillMessageHighlightSelf, cl_killmessage_highlightself, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Highlight self in kill messages")
It seems like this option is superfluous, you can set the kill message self highlight color to the normal one if you don't want them highlighted.

2021-10-05 16:54 UTC, Azorlogh commented on src/game/variables.h
> +MACRO_CONFIG_INT(ClKillMessageHighlightSelf, cl_killmessage_highlightself, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Highlight self in kill messages")
That's right, I removed it, thanks.

2021-10-05 16:55 UTC, Azorlogh commented on src/game/client/components/killmessages.cpp
> +		unsigned color = g_Config.m_ClKillMessageNormalColor;
Fixed

2021-10-06 15:25 UTC, heinrich5991 commented
bors r+

Thanks. :)

2021-10-06 15:37 UTC, merged