Add GetInt64
ddnet/ddnet pull request #4334
Opened 2021-11-07 15:49 UTC by ChillerDragon

Comes in handy for my downstream

2021-11-07 15:54 UTC, def- requested changes

2021-11-07 15:54 UTC, def- commented on src/engine/server/databases/mysql.cpp
> +	int Value;
int64_t

2021-11-07 16:06 UTC, def- reviewed
lgtm. Did you test if this actually works with large numbers?

2021-11-07 16:37 UTC, ChillerDragon commented
nope untested

Am So., 7. Nov. 2021 um 17:06 Uhr schrieb Dennis Felsing <
***@***.***>:

> ***@***.**** commented on this pull request.
>
> lgtm. Did you test if this actually works with large numbers?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ddnet/ddnet/pull/4334#pullrequestreview-799557793>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE3G33FCS7W46REUFZNFBMTUK2PZLANCNFSM5HQ6OD5A>
> .
>

2021-11-07 21:57 UTC, heinrich5991 commented
Please test this.

2021-11-08 16:23 UTC, ChillerDragon commented
Okay i tested with sqlite3 and successfully loaded the value ``222147483647`` into a ``int64_t``

``std::numeric_limits<int>::max()`` gave me ``2147483647``

2021-11-08 16:33 UTC, def- commented
bors r+

2021-11-08 16:44 UTC, merged