Add IStorage::FormatTmpPath static method
ddnet/ddnet pull request #4484
Opened 2021-12-20 14:01 UTC by def-

Not sure I prefer it, but now it's done. Any opinions?

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2021-12-20 14:10 UTC, heinrich5991 requested changes
Looks fine to me.

The update of `ddnet-libs` seems to be accidental.

2021-12-20 14:10 UTC, heinrich5991 commented on src/test/test.h
> +	char m_aFilename[IO_MAX_PATH_LENGTH];
Leaving it at 64 forgoes the include of base/system.h, I'd prefer that. It's no user-given paths anyway.

2021-12-20 14:19 UTC, def- commented
> The update of ddnet-libs seems to be accidental.

Yes, happens all the time to me since I have to use other ddnet-libs locally.

2021-12-20 14:24 UTC, heinrich5991 commented on src/test/test.h
> +#include <base/system.h>
Include still there.

2021-12-20 15:37 UTC, heinrich5991 approved these changes
bors r+

Thanks.

2021-12-21 10:28 UTC, heinrich5991 commented
bors retry

2021-12-21 10:40 UTC, merged