Add Vulkan backend
ddnet/ddnet pull request #4687
Opened 2022-02-10 16:20 UTC by Jupeyy

This adds a Vulkan 1.0 backend and new features to the graphic settings to select the GPU(if multiple Vulkan GPUs are supported, and a new list for renderers (see screenshot below))

Mutleasy benchmark (CPU bound):
Vulkan multithreaded, single threaded vs OpenGL
(lower graphs are histograms, code by @Chairn )

Y = Frametimes in microseconds
lower graphs = amount of frametimes that happened (histogram)
(since the renderer speed differs, you should look at it more like a spread of values rather than the actual values)
![Figure_1](https://user-images.githubusercontent.com/6654924/153448356-941222a3-8bd3-424d-8685-a43389a4f691.png)

Vulkan is especially good in these scenarios, beating OpenGL 3.3 almost 3x with my setup (~600-700 FPS vs. ~1700-1800FPS)

Remaining TODO list:
- [x] compile shaders in cmake ( e.g. `https://gist.github.com/evilactually/a0d191701cb48f157b05be7f74d79396` )
- [ ] needs windows vulkan libraries
- [x] add build instructions (packages)
- [x] get away from coherent memory even for staging buffers (flushing memory just seems to be faster)
- [ ] a lot of testing :P

![screenshot_2022-02-10_17-13-46](https://user-images.githubusercontent.com/6654924/153449066-38d8741b-60c1-4c0c-ba50-57cc07aa2f9d.png)

![screenshot_2022-02-10_17-13-50](https://user-images.githubusercontent.com/6654924/153449075-91ef3b7b-7238-4cad-9a4c-aeb2d784238b.png)

If there are bugs and it's crashing inside the driver the best you can do is to start the client with `dbg_gfx 4` which will (if supported) add Khronos standard validation layers + verbose debugging information + validation layer extensions, e.g. a synchronization validation layer and validation errors reported by the GPU driver directly.
(setting for dbg_gfx (0: none, 1: minimal, 2: affects performance, 3: verbose, 4: all))

edits:
fixes #3547 (probably fixes it, fixed some data races)

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2022-02-10 16:39 UTC, Kaffeine commented
Oh my god! This is great :+1: 

It would be interesting to see the particles performance. (I'll add a messages with (OpenGL :eyes: ) profiling data)

2022-02-10 16:39 UTC, heinrich5991 commented
What's the y axis in the first diagram? (probably the same as the x axis in the second row?)

2022-02-10 16:40 UTC, Jupeyy commented
> What's the y axis in the first diagram? (probably the same as the x axis in the second row?)

I'll add the description directly above the picture

2022-02-10 16:46 UTC, Jupeyy commented
> It would be interesting to see the particles performance. (I'll add a messages with (OpenGL eyes ) profiling data)

I already tested it, its a bit better than OGL 3.3 since better control over the memory managment, but the diff between OGL3.3 and older renderers is still bigger(since those don't batch their render calls)

2022-02-10 16:51 UTC, Jupeyy commented
Full scoreboard:

Vulkan:
![screenshot_2022-02-10_17-49-28](https://user-images.githubusercontent.com/6654924/153455943-4bd0acae-1e2e-4dec-89c7-f35a31958d1f.png)

OGL 3.3
![screenshot_2022-02-10_17-49-44](https://user-images.githubusercontent.com/6654924/153455949-77bc1cd2-e5a7-4c2a-87a7-34c3b218cb1f.png)

GL 1.x (GL 1.x always was especially good in streamed data)
![screenshot_2022-02-10_17-50-30](https://user-images.githubusercontent.com/6654924/153456072-9109a435-6634-4018-b36a-fda2cb4c6a04.png)

2022-02-10 17:03 UTC, def- commented
From looking at the screenshots: "Graphic cards" -> "Graphics cards"

2022-02-10 17:14 UTC, heinrich5991 commented
I can do the CMake part if you want.

2022-02-10 17:30 UTC, Jupeyy commented
> I can do the CMake part if you want.

Any help is welcome :D

2022-02-10 18:36 UTC, Chairn commented on CMakeLists.txt
> +set(AUTO_VULKAN_BACKEND OFF)
why off by default for windows?

2022-02-10 18:40 UTC, Jupeyy commented on CMakeLists.txt
> +set(AUTO_VULKAN_BACKEND OFF)
currently only builds on mingw

2022-02-10 19:56 UTC, Kaffeine requested changes

2022-02-10 19:56 UTC, Kaffeine commented on cmake/FindVulkan.cmake
> +    set(VULKAN_LIBRARIES ${PC_VULKAN_LIBRARIES})
```suggestion
    set(VULKAN_INCLUDE_DIRS "${PC_VULKAN_INCLUDE_DIRS}")
    set(VULKAN_LIBRARIES "${PC_VULKAN_LIBRARIES}")
```

`PC_VULKAN_INCLUDE_DIRS` is an empty path on some system (it is the case of my KDE Neon (based on Ubuntu 20.04).

`set(VULKAN_INCLUDE_DIRS ${PC_VULKAN_INCLUDE_DIRS})` with the last one being empty results in `VULKAN_INCLUDE_DIRS` being set to `VULKAN_INCLUDE_DIRS-NOTFOUND` which breaks all the following (CMake) code.

Add quotes to fix it.

![image](https://user-images.githubusercontent.com/374839/153486067-4f946e26-22e2-46a9-9b8f-2bf4f19758ef.png)

2022-02-10 19:56 UTC, Kaffeine commented on cmake/FindVulkan.cmake
> +    FIND_PATH(
```suggestion
    find_path(
```

2022-02-10 20:27 UTC, Jupeyy commented on cmake/FindVulkan.cmake
> +    set(VULKAN_LIBRARIES ${PC_VULKAN_LIBRARIES})
ty

2022-02-20 12:55 UTC, Jupeyy commented
I removed some overhead in the video recorder, it should now be significantly faster

2022-02-20 12:58 UTC, def- commented
Nice!

2022-02-21 17:01 UTC, Jupeyy commented
now i made video rendering multi threaded. Its insanly fast now :D

2022-02-22 14:10 UTC, Jupeyy commented
Mh glslang-tools were just added in debian buster, so let's use that for our official builds and also drop ubuntu 18 for the CI.

For windows, we either include glslangValidator in our ddnet-libs or we cannot build the vulkan backend in the CI for Windows, because downloading and installing the Vulkan SDK for every run would probs be overkill

2022-02-23 12:34 UTC, Kaffeine commented on src/engine/shared/video.h
> +#include <atomic>
This include is not used in this header.

2022-02-23 13:14 UTC, Learath2 commented
> For windows, we either include glslangValidator in our ddnet-libs or we cannot build the vulkan backend in the CI for Windows, because downloading and installing the Vulkan SDK for every run would probs be overkill

I think there was some between the runs caching capability in github actions. I'll take a look

2022-03-19 14:24 UTC, Jupeyy commented
Looks like it built correctly for windows now. The CI works with vulkan

2022-03-20 12:18 UTC, def- requested changes
Tested with Intel on Linux.

When I use vulkan the debug text is blurry:
![screenshot-20220320@131437](https://user-images.githubusercontent.com/2335377/159161627-d9113fb4-50d7-437d-ac43-3aa8f2514117.png)

Also the first line in menus is missing:
![screenshot-20220320@131510](https://user-images.githubusercontent.com/2335377/159161649-3d6bc27f-c7d5-4e8f-956f-79d4749e8749.png)

Window resizes don't work:
![screenshot-20220320@131606](https://user-images.githubusercontent.com/2335377/159161673-9b8f195c-5923-4f08-bea8-0ac0413be76e.png)

I guess those issues are all related to some scaling problem.

```
[2022-03-20 13:18:03][sdl]: SDL version 2.0.20 (compiled = 2.0.20)
[2022-03-20 13:18:03][gfx]: Created Vulkan 1.0 context.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[2022-03-20 13:18:03][gfx]: GPU vendor: INTEL
[2022-03-20 13:18:03][gfx]: GPU renderer: Intel(R) HD Graphics 530 (SKL GT2)
[2022-03-20 13:18:03][gfx]: GPU version: Vulkan 1.2.195
```

2022-03-20 12:18 UTC, def- commented on README.md
> +    sudo pacman -S --needed base-devel cmake curl freetype2 git glew gmock libnotify opusfile python sdl2 sqlite wavpack x264 ffmpeg vulkan-devel glslang spirv-tools
vulkan-devel has multiple members in Arch, do we need all?:
```
:: There are 7 members in group vulkan-devel:
:: Repository extra
   1) spirv-tools  2) vulkan-extra-layers  3) vulkan-extra-tools  4) vulkan-headers  5) vulkan-html-docs
   6) vulkan-tools  7) vulkan-validation-layers

Enter a selection (default=all):
```

2022-03-20 12:18 UTC, def- commented on src/game/client/components/menus_settings.cpp
> +						str_format(aTmpBackendName, sizeof(aTmpBackendName), "%s", Localize("auto"));
When it's auto, could we show what is being used then?

2022-03-20 12:18 UTC, def- commented on src/game/client/components/menus_settings.cpp
> +					  s_GfxBackendChanged &&
I'm not getting the "needs restart" message when I switch renderers on Linux.

2022-03-20 12:20 UTC, def- commented
```
[2022-03-20 13:18:03][graphics]: converted image editor/checker.png to RGBA, consider making its file format using RGBA
[2022-03-20 13:18:03][graphics]: converted image editor/background.png to RGBA, consider making its file format using RGBA
```
s/using //
Can you convert those images?

2022-03-20 12:59 UTC, Jupeyy commented
> I guess those issues are all related to some scaling problem.

Is this with xmonad? Can you try lavapipe, or a different WM?
Cannot reproduce this at all

2022-03-20 13:01 UTC, Jupeyy commented
> > I guess those issues are all related to some scaling problem.
> 
> Is this with xmonad? Can you try lavapipe, or a different WM? Cannot reproduce this at all

Ah wait, is your resolution ratio worse than 5:4?

2022-03-20 13:03 UTC, Jupeyy commented on README.md
> +    sudo pacman -S --needed base-devel cmake curl freetype2 git glew gmock libnotify opusfile python sdl2 sqlite wavpack x264 ffmpeg vulkan-devel glslang spirv-tools
It doesn't hurt to install all. I dont have arch, so cant test
Strictly speaking spirv, glslang and vulkan-headers aswell as vulkan loader are needed to compile and run. Basically the debian packages

2022-03-20 13:04 UTC, Jupeyy commented on src/game/client/components/menus_settings.cpp
> +						str_format(aTmpBackendName, sizeof(aTmpBackendName), "%s", Localize("auto"));
auto should only be our default, else it says custom. I can hardcode it

2022-03-20 13:05 UTC, def- commented
Yes, xmonad. Yes, worse than 5:4, but no matter how I resize it the resize events don't seem to come in. Works fine in OpenGL.

2022-03-20 13:06 UTC, Jupeyy commented
> Yes, xmonad. Yes, worse than 5:4, but no matter how I resize it the resize events don't seem to come in. Works fine in OpenGL.

Well i only listen on SDL2 events and additionally if the vulkan surface reports a change.
If non of these are sent then i'd say its a xmonad bug?

2022-03-20 13:06 UTC, def- commented
Ah, actually only when worse than 5:4, my bad.

2022-03-20 13:08 UTC, def- commented on src/game/client/components/menus_settings.cpp
> +						str_format(aTmpBackendName, sizeof(aTmpBackendName), "%s", Localize("auto"));
![screenshot-20220320@140624](https://user-images.githubusercontent.com/2335377/159163776-4d739b27-9c28-49be-9e79-570e2991d42b.png)
For me it just shows "auto"

2022-03-20 13:09 UTC, Jupeyy commented
> Ah, actually only when worse than 5:4, my bad. With OpenGL I get a little grey bar at the top, with Vulkan it's scaled and the UI breaks

Ok let me see if i can fix it

2022-03-20 14:11 UTC, Jupeyy commented
> UI breaks as described Grey bar example:

should now have a black bar

2022-03-20 14:12 UTC, Jupeyy commented on src/game/client/components/menus_settings.cpp
> +					  s_GfxBackendChanged &&
true forgot to implement it, hope it works correctly now

2022-03-20 14:13 UTC, Jupeyy commented on src/game/client/components/menus_settings.cpp
> +						str_format(aTmpBackendName, sizeof(aTmpBackendName), "%s", Localize("auto"));
What i mean is, it will always say auto (OpenGL 3.0.0) then, since the fallback makes the changed backend say "custom". I changed it now

2022-03-20 14:16 UTC, Jupeyy commented on README.md
> +    sudo pacman -S --needed base-devel cmake curl freetype2 git glew gmock libnotify opusfile python sdl2 sqlite wavpack x264 ffmpeg vulkan-devel glslang spirv-tools
So what should I add? is vulkan-devel a meta package or what

Is this the real package needed?
https://www.archlinux.de/packages/extra/x86_64/vulkan-icd-loader

I kinda find the naming for this arch package really bad.. When i install a vulkan-devel package i assume i can just start developing vulkan

2022-03-20 14:30 UTC, Jupeyy commented on src/game/client/components/menus_settings.cpp
> +						str_format(aTmpBackendName, sizeof(aTmpBackendName), "%s", Localize("auto"));
just removed the auto and added a "default" hint instead

![image](https://user-images.githubusercontent.com/6654924/159167338-d5e28364-28b1-4f54-919b-a6c05e3a4f65.png)

2022-03-20 16:40 UTC, Jupeyy commented on README.md
> +    sudo pacman -S --needed base-devel cmake curl freetype2 git glew gmock libnotify opusfile python sdl2 sqlite wavpack x264 ffmpeg vulkan-devel glslang spirv-tools
I just added them explicitly now:
`vulkan-icd-loader vulkan-headers glslang spirv-tools`
Hope thats better

2022-03-20 17:43 UTC, def- commented on README.md
> +    sudo pacman -S --needed base-devel cmake curl freetype2 git glew gmock libnotify opusfile python sdl2 sqlite wavpack x264 ffmpeg vulkan-devel glslang spirv-tools
Thanks.

2022-03-20 17:43 UTC, def- commented
Thanks, black bar works. For consistency, can you put it at the top instead of bottom? Same as for OpenGL.

2022-03-20 17:46 UTC, Jupeyy commented
> Thanks, black bar works. For consistency, can you put it at the top instead of bottom? Same as for OpenGL.

I prefer to not touch it, vulkan uses a different coordinate system :D

![v](https://www.saschawillems.de/images/2019-03-29-vulkan-flipping-the-viewport/viewports_gl_vk.png)

2022-03-20 22:04 UTC, def- approved these changes

2022-03-20 23:47 UTC, def- commented
Sometimes the grey/black bar flickers when ingame. Not sure if that's easy to fix, if not ok to keep it.

2022-03-20 23:49 UTC, def- commented
bors r+
I want to see this beta tested in an RC. Will create one tomorrow.
Huge thanks @Jupeyy for this crazy effort to support Vulkan!

2022-03-21 05:43 UTC, Jupeyy commented
bors retry

2022-03-21 06:38 UTC, Jupeyy commented
> Sometimes the grey/black bar flickers when ingame. Not sure if that's easy to fix, if not ok to keep it.

ok since bors strikes currently, let me fix it here

2022-03-21 08:50 UTC, def- commented
On macOS now I can't start client anymore:
```
[2022-03-21 09:49:55][client]: starting...
[2022-03-21 09:49:55][sdl]: SDL version 2.0.20 (compiled = 2.0.20)
[2022-03-21 09:49:55][gfx]: Created OpenGL 3.0 context.
[2022-03-21 09:49:55][gfx]: unable to create graphic context: Failed creating OpenGL context at version requested
[2022-03-21 09:49:55][sdl]: SDL version 2.0.20 (compiled = 2.0.20)
[2022-03-21 09:49:55][gfx]: Created OpenGL 2.1 context.
[2022-03-21 09:49:55][opengl]: Vendor string: Apple
[2022-03-21 09:49:55][opengl]: Version string: 2.1 Metal - 76.3
[2022-03-21 09:49:55][sdl]: SDL version 2.0.20 (compiled = 2.0.20)
[2022-03-21 09:49:55][gfx]: Created OpenGL 1.5 context.
```
Then it just hangs. Current master branch works.

2022-03-21 08:52 UTC, Jupeyy commented
> On macOS now I can't start client anymore (even with clean ddnet_settings.cfg):
> 
> ```
> [2022-03-21 09:49:55][client]: starting...
> [2022-03-21 09:49:55][sdl]: SDL version 2.0.20 (compiled = 2.0.20)
> [2022-03-21 09:49:55][gfx]: Created OpenGL 3.0 context.
> [2022-03-21 09:49:55][gfx]: unable to create graphic context: Failed creating OpenGL context at version requested
> [2022-03-21 09:49:55][sdl]: SDL version 2.0.20 (compiled = 2.0.20)
> [2022-03-21 09:49:55][gfx]: Created OpenGL 2.1 context.
> [2022-03-21 09:49:55][opengl]: Vendor string: Apple
> [2022-03-21 09:49:55][opengl]: Version string: 2.1 Metal - 76.3
> [2022-03-21 09:49:55][sdl]: SDL version 2.0.20 (compiled = 2.0.20)
> [2022-03-21 09:49:55][gfx]: Created OpenGL 1.5 context.
> ```
> 
> Then it just hangs. Current master branch works.

can you show where it hangs

2022-03-21 08:56 UTC, def- commented
```
[2022-03-21 09:55:42][sdl]: SDL version 2.0.20 (compiled = 2.0.20)
[2022-03-21 09:55:42][gfx]: Created OpenGL 1.5 context.
Process 22527 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x0000000197698290 libsystem_kernel.dylib`__psynch_cvwait + 8
libsystem_kernel.dylib`__psynch_cvwait:
->  0x197698290 <+8>:  b.lo   0x1976982b0               ; <+40>
    0x197698294 <+12>: pacibsp
    0x197698298 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x19769829c <+20>: mov    x29, sp
Target 0: (DDNet) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x0000000197698290 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001976d283c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x0000000197621230 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x0000000100071f68 DDNet`CGraphicsBackend_Threaded::WaitForIdle(this=0x0000000106010200) at backend_sdl.cpp:144:20 [opt]
    frame #4: 0x0000000100073d58 DDNet`CGraphicsBackend_SDL_GL::Init(this=0x0000000106010200, pName=<unavailable>, pScreen=<unavailable>, pWidth=<unavailable>, pHeight=<unavailable>, pRefreshRate=<unavailable>, FsaaSamples=<unavailable>, Flags=<unavailable>, pDesktopWidth=0x00000001001d0d6c, pDesktopHeight=0x00000001001d0d70, pCurrentWidth=0x0000000120008010, pCurrentHeight=0x0000000120008014, pStorage=0x0000000104810000) at backend_sdl.cpp:1112:2 [opt]
    frame #5: 0x0000000100094da8 DDNet`CGraphics_Threaded::IssueInit(this=0x0000000120008000) at graphics_threaded.cpp:2247:22 [opt]
    frame #6: 0x00000001000953f0 DDNet`CGraphics_Threaded::InitWindow(this=0x0000000120008000) at graphics_threaded.cpp:2386:15 [opt]
    frame #7: 0x0000000100095698 DDNet`CGraphics_Threaded::Init(this=0x0000000120008000) at graphics_threaded.cpp:2443:5 [opt]
    frame #8: 0x000000010007fcf4 DDNet`CClient::Run(this=0x0000000110008000) at client.cpp:2872:35 [opt]
    frame #9: 0x000000010008692c DDNet`::TWMain(argc=<unavailable>, argv=<unavailable>) at client.cpp:4458:11 [opt]
    frame #10: 0x0000000100361088 dyld`start + 516
```

2022-03-21 09:12 UTC, def- commented
```
[2022-03-21 10:11:57][gfx]: Created OpenGL 1.5 context.
Process 24133 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x0000000197698290 libsystem_kernel.dylib`__psynch_cvwait + 8
libsystem_kernel.dylib`__psynch_cvwait:
->  0x197698290 <+8>:  b.lo   0x1976982b0               ; <+40>
    0x197698294 <+12>: pacibsp
    0x197698298 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x19769829c <+20>: mov    x29, sp
Target 0: (DDNet) stopped.
(lldb) bt all
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x0000000197698290 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001976d283c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x0000000197621230 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x00000001000d1fac DDNet`CGraphicsBackend_Threaded::WaitForIdle(this=0x0000000106018a00) at backend_sdl.cpp:144:20
    frame #4: 0x00000001000d4b40 DDNet`CGraphicsBackend_SDL_GL::Init(this=0x0000000106018a00, pName="DDNet Client", pScreen=0x00000001003b8530, pWidth=0x00000001003b8534, pHeight=0x00000001003b8538, pRefreshRate=0x00000001003b853c, FsaaSamples=0, Flags=20, pDesktopWidth=0x00000001003b8540, pDesktopHeight=0x00000001003b8544, pCurrentWidth=0x00000001103e8010, pCurrentHeight=0x00000001103e8014, pStorage=0x0000000106008200) at backend_sdl.cpp:1112:2
    frame #5: 0x0000000100117fe0 DDNet`CGraphics_Threaded::IssueInit(this=0x00000001103e8000) at graphics_threaded.cpp:2247:22
    frame #6: 0x00000001001187e8 DDNet`CGraphics_Threaded::InitWindow(this=0x00000001103e8000) at graphics_threaded.cpp:2386:15
    frame #7: 0x0000000100118a80 DDNet`CGraphics_Threaded::Init(this=0x00000001103e8000) at graphics_threaded.cpp:2443:5
    frame #8: 0x00000001000eca08 DDNet`CClient::Run(this=0x0000000108020000) at client.cpp:2872:35
    frame #9: 0x00000001000f572c DDNet`::TWMain(argc=1, argv=0x000000016fdff180) at client.cpp:4458:11
    frame #10: 0x00000001001b2904 DDNet`main(argc=1, argv=0x000000016fdff180) at client.m:22:10
    frame #11: 0x0000000100895088 dyld`start + 516
  thread #2
    frame #0: 0x00000001976c3584 libsystem_kernel.dylib`sem_wait + 8
    frame #1: 0x0000000100074bcc DDNet`::sphore_wait(sem=0x0000600001704890) at system.cpp:1067:36
    frame #2: 0x0000000100073aa4 DDNet`aio_thread(user=0x0000600001704880) at system.cpp:625:4
    frame #3: 0x0000000100074904 DDNet`thread_run(user=0x0000600000008190) at system.cpp:866:2
    frame #4: 0x00000001976d226c libsystem_pthread.dylib`_pthread_start + 148
  thread #3
    frame #0: 0x00000001976c3584 libsystem_kernel.dylib`sem_wait + 8
    frame #1: 0x0000000100074bcc DDNet`::sphore_wait(sem=0x00000001086f0128) at system.cpp:1067:36
    frame #2: 0x000000010004d030 DDNet`CJobPool::WorkerThread(pUser=0x00000001086f0010) at jobs.cpp:56:3
    frame #3: 0x0000000100074904 DDNet`thread_run(user=0x000060000000c000) at system.cpp:866:2
    frame #4: 0x00000001976d226c libsystem_pthread.dylib`_pthread_start + 148
  thread #4
    frame #0: 0x00000001976c3584 libsystem_kernel.dylib`sem_wait + 8
    frame #1: 0x0000000100074bcc DDNet`::sphore_wait(sem=0x00000001086f0128) at system.cpp:1067:36
    frame #2: 0x000000010004d030 DDNet`CJobPool::WorkerThread(pUser=0x00000001086f0010) at jobs.cpp:56:3
    frame #3: 0x0000000100074904 DDNet`thread_run(user=0x000060000000c010) at system.cpp:866:2
    frame #4: 0x00000001976d226c libsystem_pthread.dylib`_pthread_start + 148
  thread #5
    frame #0: 0x00000001976cd078 libsystem_pthread.dylib`start_wqthread
  thread #6
    frame #0: 0x000000019769674c libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #7
    frame #0: 0x000000019769674c libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #8, name = 'OGL Profiler'
    frame #0: 0x00000001976948d0 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x0000000197694d40 libsystem_kernel.dylib`mach_msg + 76
    frame #2: 0x00000001f8b8988c OpenGL`glcDebugListener + 408
    frame #3: 0x00000001976d226c libsystem_pthread.dylib`_pthread_start + 148
  thread #9
    frame #0: 0x000000019769674c libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #10
    frame #0: 0x00000001976cd078 libsystem_pthread.dylib`start_wqthread
  thread #11
    frame #0: 0x000000019769674c libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #12
    frame #0: 0x000000019769674c libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #13
    frame #0: 0x00000001976cd078 libsystem_pthread.dylib`start_wqthread
  thread #14
    frame #0: 0x000000019769674c libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #15
    frame #0: 0x000000019769674c libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #16
    frame #0: 0x0000000000000000
  thread #17
    frame #0: 0x0000000197698290 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001976d283c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x0000000197621230 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x00000001000d1630 DDNet`CGraphicsBackend_Threaded::ThreadFunc(pUser=0x0000000106018a00) at backend_sdl.cpp:74:27
    frame #4: 0x0000000100074904 DDNet`thread_run(user=0x00006000000097a0) at system.cpp:866:2
    frame #5: 0x00000001976d226c libsystem_pthread.dylib`_pthread_start + 148
```

2022-03-21 09:30 UTC, Jupeyy commented
@def- can you try again?

2022-03-21 11:09 UTC, Jupeyy commented
I've to say this is a really weird bug, and doesn't really make sense to me.
In my understanding its not possible that both threads ever wait on the cond_variable

Can you run ASAN and TSAN?

2022-03-21 13:17 UTC, def- commented
Works now.

2022-03-21 13:38 UTC, def- commented
bors r+

2022-03-21 14:25 UTC, Jupeyy commented
ah my bad, didnt know bors has its own list :D

2022-03-21 14:28 UTC, def- commented
Me neither, just grepped for 18.04 :D

2022-03-21 14:45 UTC, merged