[WIP] Deobfuscate players OnRender function
ddnet/ddnet pull request #4775
Opened 2022-03-02 22:43 UTC by C0D3D3V

Does anyone else feel that the code here: https://github.com/ddnet/ddnet/blob/ff085a4545cbe58fb7e613fca7b7cb2071e31629/src/game/client/components/players.cpp#L660-L709 is somewhat obfuscated? I do not think that the compactness of the code at this point increases the readability :D

I just already opened the pull request to get the opinion if it is ok that I refactor it. I still want to change a  little thing tomorrow...

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2022-03-02 23:30 UTC, Chairn commented
The p loop sure looks weird as well as some of the condition tested on p (why < 3??).

Since we're talking about readability, i find it really weird to test "variable == loop_index" instead of "loop_index == variable" :D

2022-03-02 23:32 UTC, C0D3D3V commented
xD yes it is very strange loop, but unrolled it is exactly my version

2022-03-03 10:21 UTC, C0D3D3V commented
@Chairn This is now ready for review

2022-03-04 08:36 UTC, edg-l commented
> The p loop sure looks weird as well as some of the condition tested on p (why < 3??).

because the first if checks `p % 3 == 0` which is also valid for `p = 0` (`0 % 3 == 0`)

2022-03-04 08:44 UTC, edg-l requested changes

2022-03-04 08:44 UTC, edg-l commented on src/game/client/components/players.cpp
> +inline bool CPlayers::IsPlayerInfoAvailable(int ClientID)
I think you can make this method const too

```suggestion
inline bool CPlayers::IsPlayerInfoAvailable(int ClientID) const
```

2022-03-04 08:44 UTC, edg-l commented on src/game/client/components/players.cpp
> +	int localClientID = m_pClient->m_Snap.m_LocalClientID;
Incorrect naming, please see <https://github.com/ddnet/ddnet/issues/2945>

Should start with an uppercase: LocalClientID

2022-03-04 08:44 UTC, edg-l commented on src/game/client/components/players.cpp
> +	RenderHook(&m_pClient->m_aClients[localClientID].m_RenderPrev, &m_pClient->m_aClients[localClientID].m_RenderPrev, &m_aRenderInfo[localClientID], localClientID);
You use `m_pClient->m_aClients[localClientID]` several times, you should put it in a variable of it's own.

2022-03-04 15:54 UTC, Chairn commented
> @Chairn This is now ready for review

Oh, im not official dev here ;) But it definitely looks better and more comprehensible now :+1:. I guess it's also a little bit faster

2022-03-04 16:44 UTC, Robyt3 commented on src/game/client/components/players.cpp
> +	CGameClient::CClientData LocalClientData = m_pClient->m_aClients[LocalClientID];
The `LocalClientID` will be `-1` in server demos, so you need to check here before accessing the array.
This should be a pointer `const CGameClient::CClientData *pLocalClientData` instead of copying the client data. That way you can also set it to a null pointer when there is no local client.

2022-03-04 17:12 UTC, C0D3D3V commented on src/game/client/components/players.cpp
> +	CGameClient::CClientData LocalClientData = m_pClient->m_aClients[LocalClientID];
I didn't know we had server demos, how are they created? Can you do that simply via the console?

Also I noticed that I forgot to check if the local client is active at all.

2022-03-04 17:16 UTC, Robyt3 commented on src/game/client/components/players.cpp
> +	CGameClient::CClientData LocalClientData = m_pClient->m_aClients[LocalClientID];
Yeah, you can use `record` and `stoprecord` in the rcon. Though some parts of the server don't handle server demos currently so the server may crash when recording a server demo. I'll open an issue later.

2022-03-04 17:26 UTC, C0D3D3V commented on src/game/client/components/players.cpp
> +	CGameClient::CClientData LocalClientData = m_pClient->m_aClients[LocalClientID];
would you not access m_pClient->m_aClients[LocalClientID] at all if LocalClientID is -1? how would you do that?
or do you think the way I have it now is also okay?

2022-03-04 17:36 UTC, Robyt3 commented on src/game/client/components/players.cpp
> +	CGameClient::CClientData LocalClientData = m_pClient->m_aClients[LocalClientID];
I would do

```
int LocalClientID = m_pClient->m_Snap.m_LocalClientID;
const CGameClient::CClientData *pLocalClientData = LocalClientID == -1 ? nullptr : &m_pClient->m_aClients[LocalClientID];
```

but yours should be fine, as long as the pointer is not being used when `LocalClientID` is `-1`.

2022-03-04 17:41 UTC, C0D3D3V commented on src/game/client/components/players.cpp
> +	CGameClient::CClientData LocalClientData = m_pClient->m_aClients[LocalClientID];
How would you like it if I simply put the definition of LocalClientData into the two new conditions? So before the two lines 681 and 705.

2022-03-04 17:47 UTC, Robyt3 commented on src/game/client/components/players.cpp
> +	CGameClient::CClientData LocalClientData = m_pClient->m_aClients[LocalClientID];
That would also work, yeah.

2022-03-04 19:04 UTC, C0D3D3V commented
Ready for final review 🙈

2022-03-07 08:14 UTC, edg-l approved these changes

2022-03-07 11:09 UTC, merged