make the vanilla teams independent from the ddrace teams
ddnet/ddnet pull request #4802
Opened 2022-03-11 12:40 UTC by C0D3D3V

Because my changes have some effects on the display and thus people who like it as it was could bother, I have described my changes in detail here.

Until now it was the case that players who are in /spec (while sv_pausable is activated) or the own active player who is in /pause or /spec are in the Spectators team.

With this change this is no longer the case. I took the opportunity to make a few adjustments in the display logic. 

On the server side nothing had to be adjusted, because there was already a separation of the normal and the ddnet teams. 

1. Regarding the specators component:

I intentionally did not adjust the conditions in the OnRender function (lines 224, 306, 325 and 338) so that you can manually select players who are in /spec to watch as well.
I find this helpful, because it has often annoyed me not to be able to quickly find players who are in /spec on the map.

This also allows the selection of players that are in spec in demos. The only problem is that in demos the information about sepc players is missing (The same as in Game, only in Game the information is provided as soon as you spectate). However, until now this was also the case for players who are not in their own team. I find it handy to also have Spec players selectable, so that when they become active, the camera follows them directly.

In addition, you can spectate yourself in demos as well as in the game.
In demos this was already possible, as long as the own player in the demo is not currently in pause, at that moment you could only follow the recorded spectating camera. 

However, I have kept that in SpectateNext, SpectatePrevious and SpectateClosest the own player is not included. However, it is also possible to jump here in spectating to players in /spec.  

2.  Regarding the scoreboard component:

Now only real spectators are displayed under the scoreboard in the spectators team. No longer players who are in /spec or the own player who is currently paused.
So I did not adjust line 125, 341, 354, 367.

Line 724 would not need to be adjusted anyway since it only affects vanilla team games. If the function GetClanName is used for DDnet, this has the effect that paused players are also included.

I have adjusted the active condition of the scoreboard so that it is not automatically displayed when the player is spectating (that's the way it used to be).

Since now the own player is shown in the scoreboard even if he is paused, I have removed the marking of the own player when following another player (line 416).

3.  Regarding the menus_ingame component:
I left the behavior as it was, since we are talking about dangerous commands here (join spectator team and commit suicide) I think it is quite good that these are hidden when the player is paused.

To maintain this behavior, when creating the kill button, we must also check if we are not in pause or spec.
Actually we could check here m_pClient->m_Snap.m_SpecInfo.m_Active just like I did in the scoreboard, but since the code was already created I kept it.

4.  Regarding the IsOtherTeam function in gameclient:
This function is used to determine if the transparency m_ClShowOthersAlpha should be applied to players and nameplates of other teams and if entities of other teams should be predicted.

So I left the behavior as it was, i.e. if you pause via /pause or /spec the transparency is not applied, because then False is returned.

5. Regarding the HUD component:
I have not adjusted any condition here (line 310, 319 and 323). So far the behavior was that when the player went on pause (/pause /spec), in the small time display at the bottom right the top2 players were displayed and otherwise the best and the own player.
Now it is so that the own player is also displayed when he is paused, but not when he is a real spectator.
I personally find it strange why the display should change just because you pause. 

6. Regarding the chat component:

If the dummy paused is in the same team as the player and then a team message arrives, it will no longer be double logged.
Until now, when a player is in the same team in /spec and sends a message, his name was displayed in the Spectators team color and not in the team color. Since I have not adjusted the condition in line 803, the player names are also displayed in the team color for such messages.

7. Regarding the items component:

Here it is determined whether the local player is in the game and depending on that other GameTicks are used and ReconstructSmokeTrail is not canceled. 
Here I could not work in so exactly, no idea what consequences this has that I have not adjusted the conditions in line 47 and 560.  
I noticed at least when testing no difference, maybe someone who knows about it can explain to me what that has for effects.

About all changes I made we can discuss I am ready to undo them or restore the behavior as it was before.  But please justify with arguments.

Independently:
I added a -1 check for the m_LocalClientID to the Strong Week indicators in the Nameplates. So that with server demos the array is not accessed outside of the array range. For demos there are currently no predicted characters and therefore no strong week indicators, so it doesn't change anything.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change  
I can provide screenshots to compare before after, but it's best to test it yourself.

- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2022-03-12 11:35 UTC, def- commented on src/engine/shared/protocol.h
> +	VERSION_DDNET_INDEPENDENT_SPECTATORS_TEAM = 15092,
16000, there will be no 15.9.2

2022-03-12 11:36 UTC, def- requested changes

2022-03-12 11:36 UTC, def- commented on src/game/version.h
> +#define CLIENT_VERSIONNR 15092
Hm, now I see why you set it to 15.9.2 above, easier for testing. Should still keep this at 15091, otherwise this will cause confusion for moderators when nightly players suddenly have a different version :D

2022-03-12 15:27 UTC, heinrich5991 commented
Thanks for this incredibly thoughtful description, @C0D3D3V!

I think I agree with most of your reasoning. :)

> However, I have kept that in SpectateNext, SpectatePrevious and SpectateClosest the own player is not included. However, it is also possible to jump here in spectating to players in /spec.

This is not voicing a requirement, just a thought: I guess SpectateClosest excludes yourself because you might want to spectate the closest other player. What's the reason for excluding yourself in SpectateNext/SpectatePrevious? Because you usually wouldn't want to spectate yourself at all?

2022-03-12 15:47 UTC, C0D3D3V commented
Yes exactly, that was my thought process. SpectateNext/SpectatePrevious is usually used to spectate others and not to spectate yourself that was at least my opinion (was not otherwise possible until now). I had also considered to allow this especially in demos (that you appear there in the sequence also).

But I would still like to allow a manual selection of the own player. The use case would be if you are paused, but want the camera to follow your player and not stay where you paused. Could also be used to let the spectating camera jump to your own player without leaving pause, for whatever reason you should do that :D Actually this is just equivalent to not pausing and being AFK :D, there is actually hardly any meaningful use. 

This is an extra rand use case and probably makes more sense in demos than in normal gameplay. 
I can understand if we want to remove this rather, it was strange for me to allow this extra for demos but not ingame, so I just allowed it for both.  

In demos the sense would be that it follows the player but not the spectating camera, was previously also allowed, but you could only make the choice as long as the player was not paused. 

What do you think about this, should the player be allowed to spectate himself ingame or should we limit this to demos only?

2022-03-12 20:28 UTC, heinrich5991 commented
I think allowing to spectate yourself makes sense. I'd tend to including yourself in the SpectateNext/SpectatePrev cycle, if you don't have a strong opinion on that.

2022-03-14 12:26 UTC, C0D3D3V commented on src/engine/shared/protocol.h
> +	VERSION_DDNET_INDEPENDENT_SPECTATORS_TEAM = 15092,
done

2022-03-14 12:26 UTC, C0D3D3V commented on src/game/version.h
> +#define CLIENT_VERSIONNR 15092
I changed it back to 15091, testing is now no longer possible

2022-03-14 12:29 UTC, C0D3D3V commented
@heinrich5991  inclouded yourself in SpectateNext/SpectatePrev. And also in SpectateClosest, but so that you first jump to another close player, then if you are the next close player you jump back to yourself.

2022-03-14 13:01 UTC, def- approved these changes

2022-03-14 13:06 UTC, def- commented
bors r+
Let's see in the next release candidate how players like this.

2022-03-14 13:24 UTC, merged