Improvement of the automatic completion of player names in chat
ddnet/ddnet pull request #4826
Opened 2022-03-14 21:15 UTC by C0D3D3V

This is still work in progress for now and should fix #659 or just improve the order of player names if you use automatic completion. 

In principle it works already. I only get segmentation faults when pressing multiple times tab. 
I'm not as top as I used to be in C++ memory management, maybe someone who is good at it could take a look and tell me what I did wrong or how to do it best.

This is the error output:

```
/home/daniel/Desktop/other_repos/ddnet/src/game/client/prediction/gameworld.cpp:147:23: runtime error: downcast of address 0x6190000b5480 which does not point to an object of type 'CCharacter'
0x6190000b5480: note: object is of type 'CEntity'
 00 00 00 00  30 43 53 57 55 55 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  c0 ad b3 e2
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'CEntity'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/daniel/Desktop/other_repos/ddnet/src/game/client/prediction/gameworld.cpp:147:23 in 
/home/daniel/Desktop/other_repos/ddnet/src/game/client/prediction/gameworld.cpp:148:19: runtime error: member call on address 0x6190000b5480 which does not point to an object of type 'CCharacter'
0x6190000b5480: note: object is of type 'CEntity'
 00 00 00 00  30 43 53 57 55 55 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  c0 ad b3 e2
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'CEntity'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/daniel/Desktop/other_repos/ddnet/src/game/client/prediction/gameworld.cpp:148:19 in 
[2022-03-14 22:04:56][client]: got pong from current server, latency=53ms
[2022-03-14 22:04:57][datafile]: loading. filename='maps/0'
[2022-03-14 22:04:57][datafile]: could not open 'maps/0'
[2022-03-14 22:04:58][chat]: *** You will now see all tees on this server, no matter the distance
=================================================================
==1379813==ERROR: AddressSanitizer: heap-use-after-free on address 0x6270000b4f28 at pc 0x5555565528db bp 0x7fffffff3550 sp 0x7fffffff3548
READ of size 4 at 0x6270000b4f28 thread T0
    #0 0x5555565528da in CChat::OnInput(IInput::CEvent) /home/daniel/Desktop/other_repos/ddnet/src/game/client/components/chat.cpp:461:104
    #1 0x555556b5e305 in CGameClient::OnUpdate() /home/daniel/Desktop/other_repos/ddnet/src/game/client/gameclient.cpp:364:34
    #2 0x5555561e1c6a in CClient::Update() /home/daniel/Desktop/other_repos/ddnet/src/engine/client/client.cpp:2757:17
    #3 0x5555561efe18 in CClient::Run() /home/daniel/Desktop/other_repos/ddnet/src/engine/client/client.cpp:3092:4
    #4 0x555556246c68 in main /home/daniel/Desktop/other_repos/ddnet/src/engine/client/client.cpp:4427:11
    #5 0x7ffff516d30f in __libc_start_call_main libc-start.c
    #6 0x7ffff516d3c0 in __libc_start_main@GLIBC_2.2.5 (/usr/lib/libc.so.6+0x2d3c0)
    #7 0x555555edf424 in _start (/home/daniel/Desktop/other_repos/ddnet/build/DDNet+0x98b424)

0x6270000b4f28 is located 9768 bytes inside of 12776-byte region [0x6270000b2900,0x6270000b5ae8)
freed by thread T0 here:
    #0 0x555555f89de9 in __interceptor_free (/home/daniel/Desktop/other_repos/ddnet/build/DDNet+0xa35de9)
    #1 0x5555571fdbb9 in CSnapshotStorage::PurgeUntil(int) /home/daniel/Desktop/other_repos/ddnet/src/engine/shared/snapshot.cpp:456:3
    #2 0x5555561bfa55 in CClient::ProcessServerPacket(CNetChunk*, int, bool) /home/daniel/Desktop/other_repos/ddnet/src/engine/client/client.cpp:2036:30
    #3 0x5555561cd4aa in CClient::PumpNetwork() /home/daniel/Desktop/other_repos/ddnet/src/engine/client/client.cpp:2391:4
    #4 0x5555561dee60 in CClient::Update() /home/daniel/Desktop/other_repos/ddnet/src/engine/client/client.cpp:2699:2
    #5 0x5555561efe18 in CClient::Run() /home/daniel/Desktop/other_repos/ddnet/src/engine/client/client.cpp:3092:4
    #6 0x555556246c68 in main /home/daniel/Desktop/other_repos/ddnet/src/engine/client/client.cpp:4427:11
    #7 0x7ffff516d30f in __libc_start_call_main libc-start.c

previously allocated by thread T0 here:
    #0 0x555555f8a0a9 in malloc (/home/daniel/Desktop/other_repos/ddnet/build/DDNet+0xa360a9)
    #1 0x5555571fde0d in CSnapshotStorage::Add(int, long, int, void*, int) /home/daniel/Desktop/other_repos/ddnet/src/engine/shared/snapshot.cpp:481:32
    #2 0x5555561bfc36 in CClient::ProcessServerPacket(CNetChunk*, int, bool) /home/daniel/Desktop/other_repos/ddnet/src/engine/client/client.cpp:2039:30
    #3 0x5555561cd4aa in CClient::PumpNetwork() /home/daniel/Desktop/other_repos/ddnet/src/engine/client/client.cpp:2391:4
    #4 0x5555561dee60 in CClient::Update() /home/daniel/Desktop/other_repos/ddnet/src/engine/client/client.cpp:2699:2
    #5 0x5555561efe18 in CClient::Run() /home/daniel/Desktop/other_repos/ddnet/src/engine/client/client.cpp:3092:4
    #6 0x555556246c68 in main /home/daniel/Desktop/other_repos/ddnet/src/engine/client/client.cpp:4427:11
    #7 0x7ffff516d30f in __libc_start_call_main libc-start.c

SUMMARY: AddressSanitizer: heap-use-after-free /home/daniel/Desktop/other_repos/ddnet/src/game/client/components/chat.cpp:461:104 in CChat::OnInput(IInput::CEvent)
Shadow bytes around the buggy address:
  0x0c4e8000e990: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c4e8000e9a0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c4e8000e9b0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c4e8000e9c0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c4e8000e9d0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x0c4e8000e9e0: fd fd fd fd fd[fd]fd fd fd fd fd fd fd fd fd fd
  0x0c4e8000e9f0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c4e8000ea00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c4e8000ea10: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c4e8000ea20: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c4e8000ea30: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1379813==ABORTING

```

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2022-03-14 22:36 UTC, def- commented
> I only get segmentation faults when pressing multiple times tab.

Just a minor issue, let's ship it anyway :D 

I think the `vptr for 'CEntity'` issues are unrelated.

Asan shows the cause of the crash. You access a snapshot which has been purged (deleted) already. I'm wondering how `pCompletionString = m_pClient->m_aClients[m_aPlayerCompletionList[m_CompletionChosen].PlayerInfo->m_ClientID].m_aName;` accesses a snapshot though. Can you try printing out `m_CompletionChosen`? Maybe it's totally out of range.

2022-03-14 23:40 UTC, C0D3D3V commented
Thank you @def- 
Now it should work :) My tests were successful at least.

It is ready for a review.

2022-03-15 00:00 UTC, def- requested changes

2022-03-15 00:00 UTC, def- commented on src/game/client/components/chat.cpp
> +						m_PlayerCompletionListLength++;
I don't think this will work. You access m_aPlayerCompletionList by index i, so there will be gaps inbetween if some players left the server. Then m_PlayerCompletionListLength will be too small. Maybe just use m_aPlayerCompetionList[m_PlayerCompletionListLength]

2022-03-15 00:02 UTC, C0D3D3V commented on src/game/client/components/chat.cpp
> +						m_PlayerCompletionListLength++;
It works because the list is sorted after that

2022-03-15 00:08 UTC, C0D3D3V commented
I will adjust this tomorrow so that only up to m_PlayerCompletionListLength is sorted. And the rest of the array finds no attention. So only at index m_PlayerCompletionListLength is inserted.

2022-03-15 18:56 UTC, C0D3D3V commented
I have another idea to improve the order. One could influence the order by using upper and lower case letters.
So, if the name you are looking for starts with a capital letter, you could search with a capital letter to get the name you are looking for suggested faster.

E.g.: Players on the server: "Daniel" and "david", if you now search for "da", then "Daniel" would be suggested first, it would be better if "david" is suggested first and then "Daniel". And if you search for "Da" it would be the other way around. Or what do you think about this?

2022-03-15 20:26 UTC, C0D3D3V commented
mh i think my last suggestion with upper and lower case prioritization would only confuse more.

2022-03-16 14:31 UTC, C0D3D3V commented
I renamed RateablePlayer to CRateablePlayer to comply with the bussines rules

2022-03-16 15:17 UTC, def- approved these changes

2022-03-16 16:03 UTC, merged