predicted weapons now uses non predicted player positions if player p…
ddnet/ddnet pull request #4833
Opened 2022-03-17 17:01 UTC by JSaurusRex

Motivation:
current weapon prediction can make it look as if you hit stuff whilst the laser doesn't actually hit anybody on screen
![image](https://user-images.githubusercontent.com/50572621/158853963-36b0be13-6965-4e0b-998f-dfb8e91e3249.png)

This should fix that issue by using the non predicted world;

## Checklist

- [X] Tested the change ingame
- [X] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [X] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2022-03-17 17:12 UTC, def- requested changes
Thanks for the first contribution. I have some minor requests and a question.

@trml want to take a look too?

2022-03-17 17:12 UTC, def- commented on src/game/client/prediction/entities/laser.cpp
> +	//gets non predicted world if player positions is disabled
space after //

2022-03-17 21:48 UTC, JSaurusRex commented on src/game/client/prediction/entities/laser.cpp
> +			world = world->m_pParent;
To not have the predictions have a permanent effect a child world which is a copy of the normal world is created for the predictions to be done in. We iterate all the way up to get the non predicted game world. I don't know how deep it normally would be but I do know that the most upper one is the normal non predicted world received from the server.

2022-03-17 23:20 UTC, trml commented
This would also change the prediction itself, since it would only predict a hit if you aimed at the unpredicted position of other players when firing, as opposed to now where you have to lead the shot and hit their predicted position. This would look better in some cases (instagib, fng), but it would lead to more physics mispredictions when using shotgun on a dummy or frozen player in ddrace, so I'm not sure if changing the physics prediction is the best solution here.

If it would somehow be possible to keep physics prediction like it is, but render the laser in a different/better way (maybe by keeping two versions of the laser), I think that would be better.

Using predicted characters for the prediction is also how the hook is handled, btw, with antiping off (and is also how vanilla does it). But there the problem gets concealed because the hook immediately starts following the target, instead of ending up at a fixed location like the laser.

2022-03-18 13:05 UTC, JSaurusRex commented
Using m_WorldConfig.m_IsDDRace we can check if the game mode is a DDRace based gamemode and thus if we should enable it or not. This is probably alright for 99% of cases, but for the weird 1% of cases where it's off but the prediction should still be there it might be better to purely change it visually. That being said, as far as i could tell i couldn't find the 1%, ddnet, ddrock, fng2+ and normal ictf servers all reported correctly.

2022-03-18 18:46 UTC, trml commented
Yes, that sounds like it could be a better option, and the 1% would be ok since the server modders change fix it anyway. For mods without ddrace shotgun the prediction would only be visual anyway, and in pvp there is no guarantee that either way of prediction gives a better result (and the current way of predicting moving players is far from perfect), so it sounds like it would be worth to try it.

(I also dont have a strong opinion on one or the other since I dont play much fng/ictf with high ping or with player prediction of)

2022-03-18 18:55 UTC, trml commented on src/game/client/prediction/entities/laser.cpp
> +			world = world->m_pParent;
There is at most one parent (and in that case the child is the predicted world), so an "if(world ...)" should be enough here.

The purpose is keep track of entities in the case where they disappear during the prediction (e.g. a grenade that explodes when hitting a wall), and to retain some information about them afterwards (e.g. at which tick the projectile exploded). Each individual entity (in the predicted world) also has a parent entity (in the snapshot gameworld), to achieve this.

2022-03-18 23:23 UTC, C0D3D3V commented
Am I misunderstanding the comment: "
gets non predicted world if player positions is disabled"

  if not what has "player position" to do with g_Config.m_ClAntiPingPlayers?

2022-03-19 08:50 UTC, Robyt3 commented on src/game/client/prediction/entities/laser.cpp
> +	CGameWorld *p_world = GameWorld();
`p_world` -> `pWorld`

2022-03-20 17:15 UTC, trml commented on src/game/client/prediction/entities/laser.cpp
> +		while(pWorld->m_pParent != nullptr)
Minor things: The comment could perhaps be "player antiping" instead of "player positions", and the `while` can be replaced by an `if` (and can go into the condition above), since there is maximum 1 parent.

2022-04-02 11:19 UTC, def- commented
@JSaurusRex could you fix the requested things?

2022-04-21 13:18 UTC, JSaurusRex commented
Sorry for the delay, I forgot I hadn't yet closed this pr. I made the requested changes

2022-04-21 13:32 UTC, def- commented
bors r+
Thanks

2022-04-21 14:09 UTC, C0D3D3V commented
this somehow seems to me to be more of a symptom treatment. I've been testing this for a few games now and I don't really see much of an advantage, well I wouldn't play with high ping anyway but that's another matter.
I don't even understand why you have `cl_antiping` on but `cl_antiping_players` off. Well, but what I wanted to say is this:

The problem actually comes from the fact that we predict the player positions in vanilla mods of all players regardless of whether `cl_antiping_players` is on or off. And in ddnet mods only on own team see:

https://github.com/C0D3D3V/ddnet/blob/8c6a7ef38a89d123cf4b9c5e495e2c25971efe92/src/game/client/gameclient.cpp#L2448

wouldn't it be smarter to simply adjust the cause of this condition?

2022-04-21 14:24 UTC, trml commented
Prediction of other players is also required for predicting your own player (and the vanilla client also does this the same way). Otherwise your own player would look glitchy when you hook someone / bump into someone, as these things affect your own character slightly. For other teams (and when in solo) it is less of an issue since there is no interaction to those players.

2022-04-21 14:32 UTC, JSaurusRex commented
This is definitely not a completely issue free pr, there are cases where anti ping is wrong (aspecially with high ping) and you should have missed but the shot seems to land on air. However even the current way works its questionable which one you want. If you should clearly miss on your screen but you end seeing the shot stop mid air as it appears to have hit something and then seeing the effects of said hit (as it actually hit), this can look weird. However the opposite where your shot seems to miss but then actually did hit something is also weird. So not a perfect solution kinda just shifts the problem around.

2022-04-21 15:12 UTC, trml commented
@C0D3D3V The underlying physics prediction happens in `CGameClient::OnPredict()` and uses all players, or all players in the same team, while `UpdatePositions`/`UpdateRenderedCharacters` selects how each player is shown (predicted or unpredicted) depending on the settings. It also is possible to not predict your own player, by disabling all prediction with cl_predict 0.

2022-04-21 15:18 UTC, C0D3D3V commented
@trml  It predicts only the own player if `AntiPingPlayers()` returns false, or am I wrong?

By the way, I tried to reproduce the behavior of the miscalculated laser by running two clients side by side and recording them. I took a close look at the recording and it didn't happen once. How often does the miscalculation of the laser occur and at what ping? Can you reproduce this and possibly make a video @JSaurusRex?

In principle, I find the workaround ok, most players will probably not use it, because it only comes into play when you have antiping on but antiping_players off. 

but i would like it better if we would add an option to turn off the prediction of the own player separately, why ever you wanted that.

2022-04-28 12:03 UTC, heinrich5991 commented
> I don't even understand why you have cl_antiping on but cl_antiping_players off.

What's the use case for this scenario? Could we maybe remove `cl_antiping_players`?

2022-04-28 14:52 UTC, def- commented
Yes, I'd be in favor of only having Antiping on/off, no other switches.

2022-05-25 09:39 UTC, JSaurusRex commented
Gonna close this pull request, after further consideration i don't think it would help players more than it would hinder. Also planning on further pull requests to have better prediction for ictf, this wouldn't help with that either.
Sorry for any waisted time, next pull requests should go smoother

2022-05-25 09:39 UTC, closed without merging

2022-06-01 23:52 UTC, heinrich5991 commented
> Sorry for any waisted time, next pull requests should go smoother

No worries. Thanks for your continued interest. :)