Add option to change default eyes when joining server
ddnet/ddnet pull request #4997
Opened 2022-04-18 06:15 UTC by sjrc6

Risky Feat suggested this idea to me, I also thought it was good so I implemented it. 

If you press one of the eyes in the settings it will change which eyes you get when you join a server.

It saves a separate variable for dummy/player.

It will also change your eyes anytime you press one of them, but only if you are playing as the same Tee whose eyes you are trying to change. If someone could figure out the best way to make it change the opposite Tees eyes as well that would be nice but I don't think it's necessary. 

It also changes the "Your Skin:" Tee eyes on the left if you have one selected. 

I had to change the cl_run_on_join code a bit, I tested and I don't think it should ever break anything but it might be good for someone to double check. 

![image](https://user-images.githubusercontent.com/22122579/163762410-ec7aa67d-6417-433d-8707-e21cda2bcd5f.png)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2022-04-18 08:02 UTC, def- commented
![screenshot-20220418@100129](https://user-images.githubusercontent.com/2335377/163777087-4c34793f-ffb9-42f6-9a5f-5ed57d6880f9.png)
Everything has to fix with 5:4, for UI changes I suggest testing with 5:4 resolution always.

2022-04-18 17:22 UTC, def- commented on src/engine/client/client.cpp
> +								case EMOTE_NORMAL:
Let's just send nothing for the default case? Otherwise this feature destroys the server-side halloween feature of giving players angry eyes by default.

2022-04-18 17:27 UTC, sjrc6 commented on src/engine/client/client.cpp
> +								case EMOTE_NORMAL:
Yes that's fair I didn't think about that

2022-04-18 17:37 UTC, sjrc6 commented
I fixed it, also removed a lot of code because it's in a loop now.

If you think it's excessive to render all 6 options as a fancy button we could also just make it a single text button that cycles when you press it. But I like how it doubles as a way to view all the eyes for the skin you select. 

![image](https://user-images.githubusercontent.com/22122579/163845707-5212aa95-41aa-4d0d-93d7-34a7b4e011a4.png)

![image](https://user-images.githubusercontent.com/22122579/163846284-71fc6bb9-ab1b-40a7-8a38-cb8e53986c79.png)

2022-04-18 17:39 UTC, def- commented
I think it's ok. Other opinions?

2022-04-18 19:28 UTC, srdante commented
I think the padding around those icons is not being considered. The 4:3 is currently tight with elements on top and bottom, and the 16:9 is not respecting the right padding. Example of 16:9:

![image](https://user-images.githubusercontent.com/35383529/163864006-3fb0e307-79ff-4a07-bf25-a034fe6ffb21.png)

2022-04-18 20:17 UTC, sjrc6 commented
It respects the right side padding now 

![image](https://user-images.githubusercontent.com/22122579/163870993-4a00a002-fb4a-4372-aad7-e43d9845c157.png)
![image](https://user-images.githubusercontent.com/22122579/163871026-3845e192-547d-498c-a8cd-5752dadc8ea6.png)
![image](https://user-images.githubusercontent.com/22122579/163871121-efae2563-d2fd-4dfb-a138-187b6f8f4471.png)

2022-04-23 01:26 UTC, murpii commented
> I think it's ok. Other opinions?

I mean.. isn't this already possible with cl_run_on_join ? 

> it will also change your eyes anytime you press one of them

The emote wheel has all eyes aswell

2022-04-23 07:18 UTC, heinrich5991 commented on src/game/variables.h
> +MACRO_CONFIG_INT(ClPlayerDefaultEyes, player_defualt_eyes, 0, 0, 5, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player eyes when joining server")
```suggestion
MACRO_CONFIG_INT(ClPlayerDefaultEyes, player_default_eyes, 0, 0, 5, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player eyes when joining server")
```
Typo.

2022-04-23 07:19 UTC, heinrich5991 reviewed
LGTM otherwise.

2022-04-23 07:19 UTC, heinrich5991 commented on src/game/variables.h
> +MACRO_CONFIG_INT(ClPlayerDefaultEyes, player_defualt_eyes, 0, 0, 5, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player eyes when joining server")
I'd also list the possible choices here.

2022-04-25 14:14 UTC, C0D3D3V commented
I had another idea. You could do this as a popup. You could make the "Your Skin" look like a button, with tooltip "click to select the eyes your tee has by default when joining a server". And then when you click on it a popup opens with the 6 choices.

2022-04-26 22:24 UTC, sjrc6 commented
I think it's good enough now. I fixed the typo, added some more vertical padding when rendering below, and added a tooltip. 

I had to change the render order to prevent the tooltip from rendering under the tees but that actually ended up being less code than before so that's fine. 

Tool tips changed since I started this pr so to get it to merge the branch doesn't compile by itself, I tested it locally and it works fine though. probably there is some obscure git technique to fix this idk

2022-04-26 22:28 UTC, def- commented
> Tool tips changed since I started this pr so to get it to merge the branch doesn't compile by itself, I tested it locally and it works fine though. probably there is some obscure git technique to fix this idk

Not so obscure, but basic git functionality: merge or rebase depending on your taste. I can do that.

2022-04-26 22:33 UTC, sjrc6 commented
> The tooltip activation feels weird to me. Sometimes it doesn't activate, sometimes I move my mouse a bit and it deactivates again, sometimes not. I'm not seeing this behavior with other tooltips.

Is it because the tooltip doesn't activate between the buttons?

2022-04-26 22:35 UTC, sjrc6 commented
rebase worked thanks, I was overthinking it

2022-04-26 22:35 UTC, def- commented
No, it happens even when moving the cursor a bit on the same button

2022-04-26 22:36 UTC, sjrc6 commented
hmm let me see

2022-04-26 22:39 UTC, def- commented
Checked again and it only happens after I resized window. I think the tooltips don't handle that properly, I'll open a new issue for this, unrelated to this change.

2022-04-26 22:39 UTC, sjrc6 commented
it seems like changing resolution after starting the game breaks tooltips?

2022-04-26 22:41 UTC, def- commented
Yep, opened bug: https://github.com/ddnet/ddnet/issues/5026

2022-04-26 23:04 UTC, def- requested changes

2022-04-26 23:04 UTC, def- commented on src/engine/client/client.cpp
> +								str_format(aBuf, sizeof(aBuf), "%s;%s", aBuf, aBufEmote);
Minor comment: For the EMOTE_NORMAL case would be nice not to insert `;`. Maybe just an `if(aBufEmote[0])` around this.

2022-04-26 23:04 UTC, def- commented on src/engine/client/client.cpp
> +								char aBufEmote[128];
`aBufEmote[0] = '\0'`
Otherwise any old memory can still be in here with EMOTE_NORMAL.

2022-04-27 00:50 UTC, sjrc6 commented
@def- I think I addressed those changes

2022-04-27 07:42 UTC, def- approved these changes

2022-04-27 08:00 UTC, merged