Add a CMake option to enable IPO
ddnet/ddnet pull request #5076
Opened 2022-05-07 13:24 UTC by Kaffeine

The main motivation is to reduce the size of binaries for release build (following #5074).
The feature is not enabled by default because it increases the build time and the effect should be valued case-by-case.

#### Linux
Linux build time changed from 2:01 to 2:56 (with GNU gold) or 3:20 (default ld).

| Executable | Before  | After |
| ------------- | ---------|---- |
| config_retrieve | 886K | 43K |
| config_store | 890K | 51K |
| DDNet | 4.1M | 4.1M |
| DDNet-Server | 1.6M | 1.6M |
| dilate | 898K | 35K |
| map_convert_07 | 902K | 59K |
| map_diff | 890K | 47K  |
| map_extract | 898K | 47K  |

#### macOS
macOS build time remained to be around 2:30.

The size of `.dmg` image without IPO is `47.6Mb`, the size with IPO enabled is `46.4Mb`. I didn't check the internals.

#### Windows
Windows build time changed from 3:10 to 5:05

The binaries became even _bigger_ with IPO enabled. Nonsense, maybe IPO is messed up with some other project-specific compiler settings. I didn't investigate.

### Conclusion
It makes sense to (manually) enable IPO for macOS and Linux builds for production builds (probably update https://github.com/ddnet/ddnet-scripts/blob/master/release/build.sh for that).

2022-05-07 13:49 UTC, Jupeyy commented
Do we really need to change code for this?

Just use `cmake .. -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON`

We don't really support very old compilers anyway

2022-05-07 13:59 UTC, Kaffeine commented
> Do we really need to change code for this?
> Just use `cmake .. -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON`

I tried that at first. Globally enabled IPO fails on GTEST (warning about CMP0069 treated as error).

> Also why gold linker? xd isn't mold the currently fastest linker?

I've listed the numbers in PR. GA build for Linux without IPO: 2:01 minutes, with IPO: 3:20 (default ld), with IPO *and* GNU gold: 2:56.

2022-05-08 12:56 UTC, Jupeyy commented
> I tried that at first. Globally enabled IPO fails on GTEST (warning about CMP0069 treated as error).

Ok cannot reproduce this works without any problems for me, but maybe it happens if you download GTEST over the DOWNLOAD_GTEST option.

since we had a pr with LTO before #4614 
@def- @heinrich5991 
What do you think about LTO for production use, in this case the argument is about smaller files. A few MBytes. Worth it or not? Is the download size the important factor? E.g. how much difference is there in the zip file.
Do you think we should add extra code for it, instead of just relying on CMake?

I guess it won't really hurt. Can MinGW already do LTO? :D

2022-05-08 13:11 UTC, Kaffeine commented
> > I tried that at first. Globally enabled IPO fails on GTEST (warning about CMP0069 treated as error).
> 
> Ok cannot reproduce this works without any problems for me, but maybe it happens if you download GTEST over the DOWNLOAD_GTEST option.
> 
This is the (failed) build with https://github.com/infclass/infclass-client/actions/runs/2285963161 `CMAKE_INTERPROCEDURAL_OPTIMIZATION=ON`

> Do you think we should add extra code for it, instead of just relying on CMake?

... extra *CMake* code, instead of just relying on CMake *global property*.

2022-05-08 13:25 UTC, Jupeyy commented
> This is the (failed) build with https://github.com/infclass/infclass-client/actions/runs/2285963161 `CMAKE_INTERPROCEDURAL_OPTIMIZATION=ON`

Mh ok, sounds to me like GTest should not be affected by whatever compile flag we pass to DDNet's build system tho.
Would be the cleaner fix imo

2022-05-08 17:38 UTC, Kaffeine commented
If you don't want to save a few MB on macOS and Linux then I'm fine with closing this until better times. Not a big deal :smiley: 
(In that case I'll add https://github.com/ddnet/ddnet/pull/5076/commits/f595318b830653ca13f462e6949fbf80eb7b6860 to some other PR)

2022-05-08 17:40 UTC, Jupeyy commented
Im in favor of adding LTO to the Release. Just prefer to keep stuff as simple as possible.

So thanks for firing up this discussion and also share what benefit it gives

2022-05-08 21:37 UTC, def- commented
Yes, LTO for Release builds sounds fine to me, it had no noticable performance change, but saving a few MB in executable size is fine.

2022-05-08 21:44 UTC, Kaffeine commented
For Release builds (done everytime by GitHub Action) or for the production builds (via https://github.com/ddnet/ddnet-scripts/blob/master/release/build.sh)?

I mean: should I add a commit which enables LTO in macOS/Linux CI? Maybe I can also try to use mold for CI, if you're interesting.

2022-05-08 21:51 UTC, def- commented
mold is a bit more complicated to set up right now, probably linking time doesn't matter that much.

2022-05-13 11:50 UTC, Learath2 commented
Definitely for using this in Release configuration. I'm curious what went wrong with Windows, so let's create a tracking issue after we merge this so we can look into it.

2022-05-13 16:00 UTC, Kaffeine commented
Hm, I thought that https://github.com/ddnet/ddnet/pull/5076/commits/c281414ecdaa75387dc7726383c95f79470025d3 won't change anything, but in fact CMake version for 20.04 changes from 3.16.3 to 3.23.1.

Okay, I dropped that commit so we can test the build with CMake 3.16.

2022-05-15 11:13 UTC, def- requested changes

2022-05-15 11:13 UTC, def- commented on .github/workflows/build.yaml
> +        ${{ matrix.cmake-path }}cmake ${{ matrix.cmake-args }} ${{ matrix.cmake-release-args }} -DCMAKE_BUILD_TYPE=Debug -Werror=dev -DDOWNLOAD_GTEST=ON -DDEV=ON -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBU
This seems wrong. Why enable -DIPO=ON in Debug builds? There is a release build below.

2022-05-15 11:13 UTC, def- commented on CMakeLists.txt
> +option(IPO "Enable interprocedural optimizations" OFF)
Maybe we should default IPO to ON in Release builds.

2022-05-15 11:17 UTC, Kaffeine commented on .github/workflows/build.yaml
> +        ${{ matrix.cmake-path }}cmake ${{ matrix.cmake-args }} ${{ matrix.cmake-release-args }} -DCMAKE_BUILD_TYPE=Debug -Werror=dev -DDOWNLOAD_GTEST=ON -DDEV=ON -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBU
Oh.

2022-05-15 11:17 UTC, Kaffeine commented on CMakeLists.txt
> +option(IPO "Enable interprocedural optimizations" OFF)
Ok :+1:

2022-05-15 11:19 UTC, Kaffeine commented on CMakeLists.txt
> +option(IPO "Enable interprocedural optimizations" OFF)
Only for Linux and macOS?

2022-05-15 11:22 UTC, def- commented on CMakeLists.txt
> +option(IPO "Enable interprocedural optimizations" OFF)
How did you build on Windows? Is it with Visual Studio? If so, let's turn it off by default on Visual Studio with a comment explaining why.

2022-05-15 11:31 UTC, Kaffeine commented on CMakeLists.txt
> +option(IPO "Enable interprocedural optimizations" OFF)
Locally I have only Linux. I use CI to build for any other platform.

> If so, let's turn it off by default on Visual Studio

Hm, maybe IPO will be beneficial for mingw builds indeed but we don't have it in CI.

> with a comment explaining why

Okay.

2022-05-15 11:40 UTC, def- requested changes

2022-05-15 11:40 UTC, def- commented on CMakeLists.txt
> +  set(AUTO_IPO OFF)
`if(MSVC)`
CI uses MSVC, I will attempt it with MinGW when the change is ready.

2022-05-15 11:41 UTC, def- commented on CMakeLists.txt
> +set(AUTO_IPO ON)
Wait, only set it to ON in Release builds, not in Debug.

2022-05-15 11:43 UTC, Kaffeine commented on CMakeLists.txt
> +set(AUTO_IPO ON)
Yeah, I've noticed the missing condition right after push.

2022-05-15 11:48 UTC, def- commented
bors r+
Thanks

2022-05-15 11:48 UTC, def- approved these changes

2022-05-15 12:23 UTC, merged