Update Brazilian Portuguese translation
ddnet/ddnet pull request #5304
Opened 2022-06-01 23:55 UTC by dan1xk

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2022-06-02 03:00 UTC, srdante commented
@dan1xk Traduziu tudo errado pqp

2022-06-02 03:01 UTC, srdante commented
@dan1xk Pelo amor de deus cara refaz isso

2022-06-02 04:32 UTC, dan1xk commented
@srdante ta certo

2022-06-02 09:33 UTC, def- commented
@srdante Don't be so tough on him. Can the translations be fixed?

2022-06-02 14:21 UTC, srdante commented
@def- Of course it can be fixed, can you assign me as a reviewer of this pull request so I can add the review comments in the parts that need to be changed?

2022-06-02 14:46 UTC, def- commented
I don't think I can do that. You can just edit the file and make a new PR. But I would have preferred if dan1xk could have fixed them.

2022-06-02 17:13 UTC, srdante commented
@def- Ok, no problem. I just wanted to use the comment on code tool. I'll see if I can use the tool without being a reviewer.

2022-06-02 17:13 UTC, srdante requested changes
@dan1xk Cara, você tem que entender que a tradução de frases em algum sistema não pode ser feito da forma que você fez. Não é tão simples assim quanto parece. 

As frases originais elas estão em alguma parte específica do jogo e você não consegue saber exatamente onde sem uma investigação mais a fundo. Levando isso em consideração, você não pode começar a fazer alterações no sentido das frases, para tentar deixar elas de uma forma mais cordial ou re-adaptadas, pois você não sabe exatamente onde elas estão sendo aplicadas. 

Em algumas frases as traduções estão realmente incorretas... porem outras você alterou a semântica e o sentido dela, de uma forma que dentro do jogo, pode ficar incorreto ou mal encaixado.

Então deixei alguns comentários nas frases que você traduziu, para dar uma visão de como elas podem ser corrigidas.

2022-06-02 17:14 UTC, srdante commented
@def- It worked :). Didn't know I could leave a review just being a contributor.

2022-06-14 17:57 UTC, def- commented
@dan1xk can you add the changes @srdante suggested?

2022-06-14 22:06 UTC, dan1xk commented on data/languages/brazilian_portuguese.txt
> +== Trocar para editar as definições do seu dummy
"Trocar para editar as definições do seu dummy"

Frase correta:
> Alterne para editar as **configurações** do seu dummy

2022-06-14 22:06 UTC, dan1xk commented on data/languages/brazilian_portuguese.txt
> +== Escolha o padrão de olhos ao entrar em um servidor
"Escolha o padrão de olhos ao entrar em um servidor"

Frase Correta:
> Escolha **os olhos padrões** ao entrar em um servidor

2022-06-14 22:06 UTC, dan1xk commented on data/languages/brazilian_portuguese.txt
> +== Permite renderizar mapas com mais detalhes
"Permite renderizar mapas com mais detalhes"

Frase Correta:
> Permite **que os mapas renderizem** com mais detalhes

2022-06-14 22:06 UTC, dan1xk commented on data/languages/brazilian_portuguese.txt
> +== Equipe
As frases mantém um padrão, de fato seria correto seguir esse padrão, já o parametro foi realmente um erro esquecer de introduzi-lo

"Equipe"

Palavra correta:
> Time %d

2022-06-14 22:07 UTC, dan1xk commented on data/languages/brazilian_portuguese.txt
> +== Ajustar a opacidade das entidades pertencentes a outras equipes, tais como tees e placas de identificação
"Ajustar a opacidade das entidades pertencentes a outras equipes, tais como tees e placas de identificação"

Frase correta:
> Ajustar a opacidade das entidades pertencentes a **outros times**, tais como tees e placas de identificação

2022-06-14 22:07 UTC, dan1xk commented on data/languages/brazilian_portuguese.txt
> +== Os Quads são utilizados para decoração de fundo
"Os Quads são utilizados para decoração de fundo"

Frase correta:
> Quads são utilizados para decoração de fundo

2022-06-14 22:07 UTC, dan1xk commented on data/languages/brazilian_portuguese.txt
> +== Ao cruzar a linha de partida, mostre um tee fantasma que replica os movimentos do seu melhor tempo
"Ao cruzar a linha de partida, um tee fantasma que replica os movimentos do seu melhor tempo"

Frase correta:
> Ao cruzar a linha de partida, **mostra** um tee fantasma **replicando** os movimentos do seu melhor tempo

2022-06-16 08:27 UTC, def- commented
Closed in favor of https://github.com/ddnet/ddnet/pull/5437

2022-06-16 08:27 UTC, closed without merging