Update french.txt
ddnet/ddnet pull request #5643
Opened 2022-07-19 18:41 UTC by Sehyn

Added translation for some untranslated strings.

Fixed a translation mistake -> "Reconnecte dans %s is Reconnexion dans %s"

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2022-07-19 18:48 UTC, dannyhpy requested changes

2022-07-19 18:48 UTC, dannyhpy commented on data/languages/french.txt
> +# Sucre       2022-07-19 20:36:00
```diff
- # Sucre       2022-07-19 20:36:00
+ #	Sucre			2022-07-19 20:36:00
```

2022-07-19 18:48 UTC, dannyhpy commented on data/languages/french.txt
> +== Appparance
```diff
- == Appparance
+ == Apparence
```

2022-07-19 18:48 UTC, dannyhpy commented on data/languages/french.txt
> +== Montrer la collision du grapin
```diff
- == Montrer la collision du grapin
+ == Ligne de collision du grapin
```

2022-07-19 18:48 UTC, dannyhpy commented on data/languages/french.txt
> +== Montrer l'UI DDrace
DDRace*

2022-07-19 18:48 UTC, Chairn commented on data/languages/french.txt
> +== Appparance
Apparence

2022-07-19 19:42 UTC, Sehyn commented on data/languages/french.txt
> +== Montrer la collision du grapin
I'm not sure about that one cause, in another line it actually talk about hook line.

2022-07-19 19:43 UTC, Sehyn commented on data/languages/french.txt
> +== Montrer l'UI DDrace
Absolutely my mistake.

2022-07-19 19:43 UTC, Sehyn commented on data/languages/french.txt
> +== Montrer l'indicateur de saut
To be confirmed if it's pluriel or not.

2022-07-19 20:33 UTC, def- commented
@Sehyn can you make the fixes and update this PR?

2022-07-19 21:03 UTC, NouaaTW commented
Looks good to me

2022-07-19 21:34 UTC, dannyhpy requested changes

2022-07-19 21:34 UTC, dannyhpy commented on data/languages/french.txt
> +== Monter la vie, bouclier et munitions
```diff
+ == Montrer la vie, le bouclier et les munitions
```

2022-07-19 21:35 UTC, dannyhpy commented on data/languages/french.txt
> +== HUD DDrace
Il y a une raison particulière à l'écrire "DDrace" au lieu de "DDRace" comme dans la chaîne de caractères initiale ?

2022-07-19 22:33 UTC, Sehyn commented on data/languages/french.txt
> +== HUD DDrace
Petit problème de caps lock, a modifier du coup.

Si jamais la question de pourquoi HUD DDRace avant et pas DDRace HUD, on dit  l'interface DE quelque chose et non quelque chose de l'interface ou quelque chose interface

2022-07-20 10:03 UTC, dannyhpy approved these changes

2022-07-20 11:07 UTC, blueskyGH commented on data/languages/french.txt
> +== Montrer la collision du grapin
@Sehyn in this case its just talking about the line itself, not about showing it 😄

2022-07-26 18:08 UTC, def- commented
bors r+
Thanks

2022-07-26 18:27 UTC, merged