Fix motd render in server info
ddnet/ddnet pull request #5704
Opened 2022-08-05 22:56 UTC by MikiGamer

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

Screenshots:

Before:
![ss1](https://user-images.githubusercontent.com/35080830/183221232-bfd834c1-5d32-45eb-851f-bf0a31135d57.png)

After:
![ss2](https://user-images.githubusercontent.com/35080830/183221246-9e5a5cfd-ef59-497d-bc12-5361ac014bc2.png)
![ss3](https://user-images.githubusercontent.com/35080830/183221250-c2c8e9d7-374c-484a-ac6c-7a8c0f3b7b8f.png)

2022-08-05 23:06 UTC, def- requested changes

2022-08-05 23:06 UTC, def- commented on src/game/client/components/menus_ingame.cpp
> +		if (Motd[c] == *"\n") {
`if (Motd[c] == '\n') {`

2022-08-05 23:06 UTC, def- commented
See also the compiler warning:
```
/home/runner/work/ddnet/ddnet/src/game/client/components/menus_ingame.cpp:481:19: error: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
  481 |  for(int c = 0; c < strlen(Motd); c++)
      |                 ~~^~~~~~~~~~~~~~
```

2022-08-05 23:07 UTC, def- commented on src/game/client/components/menus_ingame.cpp
> +	for(int c = 0; c < strlen(Motd); c++)
instead of strlen we use the functions from system.cpp, in this case str_length.

2022-08-05 23:08 UTC, def- commented on src/game/client/components/menus_ingame.cpp
> +int CMenus::GetMotdLength(char* Motd) {
pMotd instead of Motd by our naming convention

2022-08-05 23:09 UTC, def- commented on src/game/client/components/menus_ingame.cpp
> +	UiDoListboxStart(&s_MotdContainer, &Motd, 18.0f, Localize("MOTD"), "", NumItems, 1, -1, s_ScrollValue);
Could we show no list box when it fits on screen?

2022-08-05 23:09 UTC, def- commented on src/game/client/components/menus_ingame.cpp
> +	int NumItems = GetMotdLength(m_pClient->m_Motd.m_aServerMotd);
I think the names NumItems and GetMotdLength are a bit confusing, those are numbers of lines, right?

2022-08-05 23:10 UTC, def- commented on src/game/client/components/menus_ingame.cpp
> +	for(int c = 0; c < strlen(Motd); c++)
running a strlen for each iteration of a loop is a bad idea in general, it is recalculated by iterating over the entire string.

2022-08-05 23:10 UTC, MikiGamer commented
```
src/game/client/components/menus_ingame.cpp:470:93: error: code should be clang-formatted [-Wclang-format-violations]
        TextRender()->Text(0, Motd.x + x, Motd.y + y, 16, m_pClient->m_Motd.m_aServerMotd, Motd.w);
```
What about this format error?

2022-08-05 23:10 UTC, def- commented on src/game/client/components/menus_ingame.cpp
> +	int length = 1;
Length, not length by our naming convention

2022-08-05 23:10 UTC, def- commented on src/game/client/components/menus_ingame.cpp
> +	if(strlen(Motd) < 1)
Is this special casing useful?

2022-08-05 23:13 UTC, def- commented
Nice change, just needs some minor fixes. Does it show the scroll bar 

> ```
> src/game/client/components/menus_ingame.cpp:470:93: error: code should be clang-formatted [-Wclang-format-violations]
>         TextRender()->Text(0, Motd.x + x, Motd.y + y, 16, m_pClient->m_Motd.m_aServerMotd, Motd.w);
> ```
> 
> What about this format error?

You can ignore it or try running clang-format. No need to put in effort to fix it manually.

2022-08-05 23:16 UTC, MikiGamer commented on src/game/client/components/menus_ingame.cpp
> +	int NumItems = GetMotdLength(m_pClient->m_Motd.m_aServerMotd);
Yes, its number of lines. We count them here to provide height to scrolling bar. Because we don't know how many lines a server can provide.

2022-08-05 23:17 UTC, MikiGamer commented on src/game/client/components/menus_ingame.cpp
> +	for(int c = 0; c < strlen(Motd); c++)
So the resolve can be to count it when client receives motd from server?

2022-08-05 23:18 UTC, MikiGamer commented on src/game/client/components/menus_ingame.cpp
> +	UiDoListboxStart(&s_MotdContainer, &Motd, 18.0f, Localize("MOTD"), "", NumItems, 1, -1, s_ScrollValue);
It actually doesn't show until its needed.

2022-08-05 23:19 UTC, MikiGamer commented on src/game/client/components/menus_ingame.cpp
> +	UiDoListboxStart(&s_MotdContainer, &Motd, 18.0f, Localize("MOTD"), "", NumItems, 1, -1, s_ScrollValue);
![screenshot_2022-08-06_01-19-11](https://user-images.githubusercontent.com/35080830/183222770-59e837ed-dac1-46bb-8a2b-82f941b50774.png)

2022-08-05 23:48 UTC, def- commented on src/game/client/components/menus_ingame.cpp
> +	for(int c = 0; c < strlen(Motd); c++)
That's an independent issue. Even when you do the count at a different location, you should store the result of `str_length(Motd)` in a variable and then refer to that in the for loop. Don't call str_length(Motd) for each iteration of the loop.

2022-08-06 00:14 UTC, def- commented on src/game/client/components/menus_ingame.cpp
> +	UiDoListboxStart(&s_MotdContainer, &Motd, 18.0f, Localize("MOTD"), "", m_pClient->m_Motd.m_aMotdLinesNumber, 1, -1, s_ScrollValue);
LinesNumber -> NumLines

2022-08-06 00:14 UTC, def- commented on src/game/client/components/motd.cpp
> +	if(str_length(pMotd) < 1)
I still think this special casing is not necessary.

2022-08-06 00:15 UTC, def- commented on src/game/client/components/motd.cpp
> +	for(int c = 0; c < str_length(pMotd); c++)
str_length(pMotd) -> pMotd[c] != '\0'

2022-08-06 00:16 UTC, def- commented on src/game/client/components/motd.cpp
> +	if(str_length(pMotd) < 1)
pMotd[0] == '\0'
Then you don't have to iterate over the entire string.

2022-08-06 00:16 UTC, def- commented on src/game/client/components/motd.cpp
> +int CMotd::Getlinescount(char *pMotd)
count -> Count

2022-08-06 17:56 UTC, MikiGamer commented
Do we need some padding here or its okay?
![image](https://user-images.githubusercontent.com/35080830/183260435-97c40a69-7ee4-47cf-b53b-d9a731ce8d3b.png)

2022-08-06 21:39 UTC, Chairn commented
Can you squash the commit please?

2022-08-07 16:08 UTC, def- commented on src/game/client/components/motd.h
> +	int GetlinesCount(char *pMotd);
lines -> Lines :D

2022-08-07 16:09 UTC, def- requested changes
lines -> Lines :D
See https://en.wikipedia.org/wiki/Camel_case

2022-08-19 21:20 UTC, def- commented
@MikiGamer sorry, this has been fixed in https://github.com/ddnet/ddnet/pull/5751 as well

2022-08-20 15:18 UTC, closed without merging