Laser menu tweaks; Changed Freeze laser color
ddnet/ddnet pull request #5843
Opened 2022-09-16 22:30 UTC by VoxelDoesCode

fixes #5841 

![image](https://user-images.githubusercontent.com/95713843/190824834-a48913ec-360a-40a8-8b48-d278f5916493.png)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2022-09-16 22:31 UTC, def- approved these changes

2022-09-17 00:10 UTC, heinrich5991 commented
Looks good to me. clang-formatted.

2022-09-17 00:11 UTC, VoxelDoesCode commented
I still want to add a Reset all button at the bottom, if that's fine.

2022-09-17 00:18 UTC, heinrich5991 commented
Sorry, should've asked first. Reverted to the original state.

2022-09-17 09:29 UTC, def- requested changes

2022-09-17 09:29 UTC, def- commented on src/game/client/components/menus_settings.cpp
> +		if(DoButton_Menu(&s_AllToDefaultResetID, Localize("Reset all"), 0, &Button))
Use "Reset to defaults", then we don't need a new translation.

2022-09-17 22:16 UTC, def- commented
bors r+

2022-09-17 22:36 UTC, merged