Just enough 0.7 client support to join a server
ddnet/ddnet pull request #5949
Opened 2022-10-16 08:55 UTC by ChillerDragon

While keeping 0.6 fully working and untouched
This adds the option to connect via 0.7

This is the first working version there is still work todo There are a few known bugs and missing featues to name a few:

- Switching versions crashes the client
- Maps with envelopes crash the client
- Many snap items are not properly translates like gameinfo for example
- No support for all the 0.7 features like
  + 0.7 skins
  + ready
  + dead players
  + colored broadcast

https://user-images.githubusercontent.com/20344300/196026956-0f676f43-b595-49ac-8a2d-c52410e6ce89.mp4

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2022-10-16 08:57 UTC, ChillerDragon commented
The 0.7 support is far from finished but I would appreciate getting this merged into master to reduce maintenance effort caused by git conflicts. All the incomplete code should be opt in by specifying 0.7 when connecting via the ``connect`` command.

2022-10-16 09:14 UTC, Robyt3 commented on src/base/math.h
> +	return (((rand() & 0xffff) << 16) | (rand() & 0xffff)) & 0x7FFFFFFF;
This causes undefined behavior. See https://github.com/teeworlds/teeworlds/pull/3143/commits/cb9ac4d8331b1616efc342e8700db61bc47947c7.

2022-10-16 09:17 UTC, ChillerDragon commented on src/base/math.h
> +	return (((rand() & 0xffff) << 16) | (rand() & 0xffff)) & 0x7FFFFFFF;
:heavy_check_mark:

2022-10-16 15:43 UTC, heinrich5991 requested changes
I'd like to review this pull request before it gets merged.

2022-10-16 15:48 UTC, ChillerDragon commented
> I'd like to review this pull request before it gets merged.

Yes thanks. That would help a lot before I continue with this code :slightly_smiling_face:

2022-10-19 23:01 UTC, heinrich5991 requested changes
I'd prefer if we didn't introduce sixup parameters everywhere. Instead, the connect string should be extended to allow for 0.7 connecting, e.g. with `tw-0.7+udp://127.0.0.1`, like used in the serverbrowser.

(Additionally, we could probably add a flag to the NETADDR struct so we can pass it through that as well. @Learath2, what would you think about that?)

Stuff that's only important for version 7 should get a 7 into the name.

2022-10-19 23:01 UTC, heinrich5991 commented on src/engine/shared/network.cpp
> +void CNetBase::SendControlMsgWithToken(NETSOCKET Socket, NETADDR *pAddr, TOKEN Token, int Ack, int ControlMsg, TOKEN MyToken, bool Extended)
This should be called `SendControlMsgWithToken7`, I guess?

2022-10-20 15:30 UTC, Robyt3 commented on src/base/math.h
> +	return ((rand() & 0x7fff) << 16) | (rand() & 0xffff);
The function is only used once to create a random `TOKEN`, which is an `unsigned int`. So this function should be renamed to `random_unsigned` and then it would be fine to use the original implementation, though you'd probably have to use unsigned literals consistenly or the bitwise operations will implicitly cast the intermediate results to int again, which would cause undefined behavior when a bit is shifted into the sign bit of an int.

```cpp
((((unsigned)rand()) & 0xffffu) << 16u) | (((unsigned)rand()) & 0xffffu);
```

But it would probably be even better to use `secure_random_fill` to generate a token instead of using `rand`:

```cpp
TOKEN CNetConnection::GenerateToken7(const NETADDR *pPeerAddr)
{
    TOKEN Token;
    secure_random_fill(&Token, sizeof(Token));
    return Token;
}
```

2022-10-21 10:35 UTC, ChillerDragon commented on src/base/math.h
> +	return ((rand() & 0x7fff) << 16) | (rand() & 0xffff);
Went with this thanks @Robyt3 

```C++
TOKEN CNetConnection::GenerateToken7(const NETADDR *pPeerAddr)
{
    TOKEN Token;
    secure_random_fill(&Token, sizeof(Token));
    return Token;
}
```

2022-10-21 10:37 UTC, ChillerDragon commented
Did a litle force pushing to improve the funcname7 naming convention and rand code. Still open refactor todos.

2022-10-21 10:42 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +	}
It is Connect vs Connect7 I refactored it to a more concise version hope that helps

```C++
	if(m_Sixup = Sixup)
		m_aNetClient[CONN_MAIN].Connect7(aConnectAddrs, NumConnectAddrs);
	else
		m_aNetClient[CONN_MAIN].Connect(aConnectAddrs, NumConnectAddrs);
```

2022-10-21 10:44 UTC, ChillerDragon commented on src/engine/shared/network.h
> +class CNetClient : public CNetBase
```
/home/chiller/Desktop/git/ddnet/src/engine/shared/network_client.cpp: In member function ‘bool CNetClient::Open(NETADDR)’:
/home/chiller/Desktop/git/ddnet/src/engine/shared/network_client.cpp:22:27: error: cannot convert ‘CNetClient*’ to ‘CNetBase*’
   22 |         m_Connection.Init(this, m_Socket, false);
      |                           ^~~~
      |                           |
      |                           CNetClient*
```

2022-10-21 10:46 UTC, ChillerDragon commented on src/tools/twping.cpp
> +	while(g_NetOp.Recv(&Packet, nullptr, false))
Indeed good catch! Thanks fixed.

```C++
SECURITY_TOKEN ResponseToken;
while(g_NetOp.Recv(&Packet, &ResponseToken, false))
```

2022-10-21 10:53 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +	}
Is that blocking? I would add them back anyways during development and clean this up when its finished. Those should not be printed when using the client in 0.6 mode.

I can ofc prio that refactor if the current state is a no go for you.

2022-10-21 11:32 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +	}
Managed to refactor it to this but still needs cleanup at some point

```C++
	// TODO: chiller clean this up
	if(Sixup && !pMsg->m_NoTranslate)
	{
		if(pMsg->m_System)
		{
			if(MsgId >= OFFSET_UUID) // TODO: this still by learath2 do we need dis?
				;
			else if(MsgId == NETMSG_INFO)
				;
			else if(MsgId == NETMSG_READY)
				MsgId += 4;
			else if(MsgId == NETMSG_RCON_CMD)
				MsgId = 21; // 17 -> NETMSG_RCON_CMD
			else if(MsgId == NETMSG_ENTERGAME)
				MsgId = 19; // 15 -> 19
			else if(MsgId == NETMSG_INPUT)
				MsgId = 20; // 16 -> 20
			else
			{
				dbg_msg("net", "DROP send sys %d", MsgId);
				return true;
			}
		}
		else
		{
			if(MsgId >= 0 && MsgId < OFFSET_UUID)
			{
				// CGameClient::SendSTartInfo7 build a 0.7 message do not translate that
				if(MsgId != protocol7::NETMSGTYPE_CL_STARTINFO)
					MsgId = Msg_SixToSeven(MsgId);
			}

			if(MsgId < 0)
				return true;
		}
	}
```

2022-10-21 12:43 UTC, heinrich5991 commented on src/engine/shared/network.h
> +class CNetClient : public CNetBase
Just move `unsigned char m_aRequestTokenBuf[NET_TOKENREQUEST_DATASIZE];` out of the class, I'd say, and into a local variable in the function. Then you don't need the new inheritance.

2022-10-22 09:57 UTC, ChillerDragon commented
I just noticed that the server side bridge broke. Connecting to ddnet servers with a 0.7 client should be added to the CI.

2022-11-23 04:11 UTC, VoxelDoesCode commented on src/engine/client/client.cpp
> +	}
This looks like a job for a switch function.

2023-01-21 08:34 UTC, ChillerDragon commented
Okay I finally fixed all the token flipping. Now the client and the server send and expect the correct tokens.

2023-02-04 09:08 UTC, ChillerDragon commented
> I'd prefer if we didn't introduce sixup parameters everywhere. Instead, the connect string should be extended to allow for 0.7 connecting, e.g. with `tw-0.7+udp://127.0.0.1`, like used in the serverbrowser.
> 
> (Additionally, we could probably add a flag to the NETADDR struct so we can pass it through that as well. @Learath2, what would you think about that?)

Is that blocking this pullrequest?

2023-02-10 12:03 UTC, ChillerDragon commented
Another feature rich force push. I started to properly translate game messages and snap items. Before it just read 0.7 stuff as 0.6 which somewhat worked due to so many things overlapping.

As suggested by heinrich I am going over the whole snapshot after it is received and build a translated snapshot. So the rest of the code still thinks it is on a 0.6 server. The snapshot translation happens in a new file

https://github.com/ChillerDragon/ddnet/blob/cf84818a183ecee99f6f8bc497b99dafdc1335a6/src/engine/shared/snapshot_translate.cpp

in the ``CSnapshot::TranslateSevenToSix`` method. It makes use of a newly added ``CTranslationContext`` class which keeps track of information that was sent as game message and has to be included in the snap. 

https://github.com/ChillerDragon/ddnet/blob/cf84818a183ecee99f6f8bc497b99dafdc1335a6/src/engine/shared/translation_context.h

So for example when the client receives the game message [msg_game_info](https://chillerdragon.github.io/teeworlds-protocol/07/game_messages.html#NETMSGTYPE_SV_GAMEINFO) it stores the fields in the translation context. And then will be added to the snapshot as [obj_game_info](https://chillerdragon.github.io/teeworlds-protocol/06/snap_items.html#obj_game_info). This is a bit hacky but ensures that the codebase can stay 0.6 even though 0.7 moved things out of the snap into game messages.

The client looks at the m_pAltSnap for all the snapshot data so I replaced that by the following wrapper.
```c++
CSnapshot *AltSnap()
{
	return m_pTransSnap ? m_pTransSnap : m_pAltSnap;
}
```
So if it is in sixup mode and got a translated snap it will prefer this one over the m_pAltSnap. The m_pAltSnap then is the raw untouched 0.7 snapshot.

Its a early draft with a lot of messy comments and todos. But the conceptual layout of translating the snap after receive and a translation context is planned to stay so feedback on that would be nice.

2023-02-10 12:07 UTC, fokkonaut commented on src/engine/client/client.cpp
> +			if(MsgId >= OFFSET_UUID) // TODO: this still by learath2 do we need dis?
yes, you need this.

2023-02-10 12:33 UTC, Jupeyy commented
This patch might sound nice. But it should be made clear that this yet another maintenance nightmare for almost no gain. The client is bloated with backends that nobody uses, with network code workaround for all versions. Even the server side translation is not the best. I just hope that before merging this, it must be clear that someone has to maintain this and that for the 5 users that might use it and complain about bugs.

2023-02-10 17:21 UTC, ChillerDragon commented
> I just hope that before merging this, it must be clear that someone has to maintain this and that for the 5 users that might use it and complain about bugs.

If this ever reaches a functional state I would be one of the 5 users and thus motivated to fix the bugs I encounter.

2023-02-13 16:55 UTC, ChillerDragon commented
https://user-images.githubusercontent.com/20344300/218519849-aedba112-0c81-46db-a650-ee6fe29ec364.mp4

Snap translation went pretty well. A few bugs are probably still there. And the damage indicators are janky (wrong angles). But other than that it seems pretty playable. Note that I hardcode translated the skin greensward and use default for all others so thats also a open todo. But the biggest blocker for now is that connecting to a server with a 0.7 map crashes the client. But Roby is on that luckily.

So I overreached the goal for this pr by far. I would love to see this merged as soon as possible the reduce maintenance efforts for me caused by merge conflicts. This is not ready to be played yet and integrated in the ui. That would be a next step but in a seperate  pull request.

2023-02-13 18:34 UTC, Kaffeine commented on src/engine/shared/snapshot_translate.cpp
> +				return -3;
I'd suggest to `return - pItem7->Type();` for the negative ret codes in this file.

2023-02-15 10:50 UTC, ChillerDragon commented on src/engine/shared/snapshot_translate.cpp
> +				return -3;
Yea sounds smart but I rather keep it simple. Also helps with searching in the code if you can look for magic numbers.

2023-02-15 12:34 UTC, edg-l commented
> Jeff Atwood: “the best code is no code at all. Every new line of code you willingly bring into the world is code that has to be debugged, code that has to be read and understood, code that has to be supported. Every time you write new code, you should do so reluctantly, under duress, because you completely exhausted all your other options.”

> Robert Galanakis: “The fastest code is the code which does not run. The code easiest to maintain is the code that was never written.”

2023-03-10 12:54 UTC, heinrich5991 commented
@ChillerDragon wants to know whether to continue working on this.

@Jupeyy says this following:
> This patch might sound nice. But it should be made clear that this yet another maintenance nightmare for almost no gain. The client is bloated with backends that nobody uses, with network code workaround for all versions. Even the server side translation is not the best. I just hope that before merging this, it must be clear that someone has to maintain this and that for the 5 users that might use it and complain about bugs.

I agree that this will increase maintenance cost, although I think only by a little. Of course, having a lot of features, all with a tiny maintenance cost, adds up. As you say, someone has to maintain that part. In order to not become a maintenance issue for other people, it'd be nice if the code was separated enough so that it could easily be ripped out again.

@edg-l posted some quotes that imply that he's against adding this.

Personally, I find the idea cool that the DDNet client would be able to join 0.7 servers, maybe just from a technical perspective. It seems there are very few players on 0.7-only servers, at least right now.


<details>
<summary>List of 0.7 only servers (117 servers, 3 players)</summary>
<table>
<tr><td>B|City</td><td>B|City Server Hosted by : [MLP] Rafael</td></tr>
<tr><td>CRAZY-DM</td><td>CRAZY Server Hosted by : [MLP] Rafael</td></tr>
<tr><td>CTF</td><td>! ! ! ePlay TV Fun-Server CTF ! ! !</td></tr>
<tr><td>CTF</td><td>! !! [Asso-ResPawn.fr] !! ! --FR-- CTF</td></tr>
<tr><td>CTF</td><td>! Public EUROPE Vanilla CTF5</td></tr>
<tr><td>CTF</td><td>! yet another lizard</td></tr>
<tr><td>CTF</td><td>Acumerse LAN</td></tr>
<tr><td>CTF</td><td>American CTF server</td></tr>
<tr><td>CTF</td><td>Bone Sawing Bio Weapons Lab</td></tr>
<tr><td>CTF</td><td>CTF : Refuge for lost souls</td></tr>
<tr><td>CTF</td><td>Caesar-Lynx</td></tr>
<tr><td>CTF</td><td>City Dev Labs TW-server 2022</td></tr>
<tr><td>CTF</td><td>EPFL - GNU Generation - https://gnugeneration.epfl.ch/</td></tr>
<tr><td>CTF</td><td>Fuck putin</td></tr>
<tr><td>CTF</td><td>KarboLabs game server</td></tr>
<tr><td>CTF</td><td>Marti Mon</td></tr>
<tr><td>CTF</td><td>Maxilan Capture The Flag</td></tr>
<tr><td>CTF</td><td>NetoMX's server on LA</td></tr>
<tr><td>CTF</td><td>SR Teeworlds Server</td></tr>
<tr><td>CTF</td><td>Teeworlds.Net - CTF 1</td></tr>
<tr><td>CTF</td><td>Turn Teeworlds CTF Server</td></tr>
<tr><td>CTF</td><td>Turn Teeworlds CTF5 only Server</td></tr>
<tr><td>CTF</td><td>Twocows Teeworlds Server</td></tr>
<tr><td>CTF</td><td>Tyria Server CTF/DM</td></tr>
<tr><td>CTF</td><td>Ural TeeWorlds Server</td></tr>
<tr><td>CTF</td><td>What Clan's shooting range</td></tr>
<tr><td>CTF</td><td>[8G] Teeworlds Dedicated France</td></tr>
<tr><td>CTF</td><td>[CPLAN] Teeworlds</td></tr>
<tr><td>CTF</td><td>creepy-hd teeworlds</td></tr>
<tr><td>CTF</td><td>hLAN</td></tr>
<tr><td>CTF</td><td>inQontroL Vanilla 2on2 CTF1 Clanserver - www.inQontrol.de</td></tr>
<tr><td>CTF</td><td>inQontroL Vanilla 3on3 CTF3 Clanserver - www.inQontrol.de</td></tr>
<tr><td>CTF</td><td>inQontroL Vanilla CTF5 Public Server - www.inQontrol.de</td></tr>
<tr><td>CTF</td><td>inQontroL Vanilla CTF5 Public Server - www.inQontrol.de</td></tr>
<tr><td>CTF</td><td>inQontroL Vanilla XonX CTF2 Clanserver - www.inQontrol.de</td></tr>
<tr><td>Catch16</td><td>Catch16 Instagib Server Hosted by : [MLP] Rafael</td></tr>
<tr><td>DM</td><td>! ! ! ePlay TV Fun-Server ! ! !</td></tr>
<tr><td>DM</td><td>! !! [Asso-ResPawn.fr] !! ! --FR-- DM</td></tr>
<tr><td>DM</td><td>! Public EUROPE Vanilla DM</td></tr>
<tr><td>DM</td><td>..:: sysmo.pro™ ::.. Vanilla</td></tr>
<tr><td>DM</td><td>American DM server</td></tr>
<tr><td>DM</td><td>AzGame</td></tr>
<tr><td>DM</td><td>Bob's Teeworlds Server</td></tr>
<tr><td>DM</td><td>DM : Refuge for lost souls</td></tr>
<tr><td>DM</td><td>Darlington Deathmatch Server</td></tr>
<tr><td>DM</td><td>DieCommunity.eu Server</td></tr>
<tr><td>DM</td><td>Einherjer Europe [linuxiuvat.de]</td></tr>
<tr><td>DM</td><td>GPlays-EU: Teeworlds Test Server</td></tr>
<tr><td>DM</td><td>Game Player Club - Texas</td></tr>
<tr><td>DM</td><td>Game Player Club - Toronto</td></tr>
<tr><td>DM</td><td>GamingOnLinux DeathMatch</td></tr>
<tr><td>DM</td><td>Habertech-Teeworlds-Server</td></tr>
<tr><td>DM</td><td>Headhunterz</td></tr>
<tr><td>DM</td><td>Le Village Gaulois</td></tr>
<tr><td>DM</td><td>Maxilan Death Match</td></tr>
<tr><td>DM</td><td>Mr_Console</td></tr>
<tr><td>DM</td><td>ORDIX</td></tr>
<tr><td>DM</td><td>Ploobis Domain Teeworlds Server</td></tr>
<tr><td>DM</td><td>ProggerX's server</td></tr>
<tr><td>DM</td><td>Prutsers United Game Server</td></tr>
<tr><td>DM</td><td>Solaire Clanserver</td></tr>
<tr><td>DM</td><td>Teeworlds.Net - Duel 1</td></tr>
<tr><td>DM</td><td>Teeworlds.Net - FFA 1</td></tr>
<tr><td>DM</td><td>The-Solaris-Agency_01</td></tr>
<tr><td>DM</td><td>TheAnister's server</td></tr>
<tr><td>DM</td><td>Turn Teeworlds Deathmatch Server</td></tr>
<tr><td>DM</td><td>Vinculogamer</td></tr>
<tr><td>DM</td><td>[DM] jakku server</td></tr>
<tr><td>DM</td><td>coolfriends</td></tr>
<tr><td>DM</td><td>firecraft.studio</td></tr>
<tr><td>DM</td><td>inQontroL Vanilla 1on1 DM1 Clanserver - www.inQontrol.de</td></tr>
<tr><td>DM</td><td>inQontroL Vanilla DMX Clanserver - www.inQontrol.de</td></tr>
<tr><td>DM</td><td>silicium</td></tr>
<tr><td>DM</td><td>syzygia</td></tr>
<tr><td>DM</td><td>this_is_a_server</td></tr>
<tr><td>DM</td><td>unnamed server</td></tr>
<tr><td>DM</td><td>unnamed server</td></tr>
<tr><td>DM</td><td>unnamed server</td></tr>
<tr><td>DM</td><td>unnamed server</td></tr>
<tr><td>DM</td><td>your_server_name</td></tr>
<tr><td>DM</td><td>ÆON Clanserver #1</td></tr>
<tr><td>DM</td><td>ÆON Clanserver #2</td></tr>
<tr><td>Fire</td><td>Fire Server Hosted by : [MLP] Rafael</td></tr>
<tr><td>LMS</td><td>! ! ! ePlay TV - LTS-Server ! ! !</td></tr>
<tr><td>LMS</td><td>Dönerstag [dave-cc]</td></tr>
<tr><td>LMS</td><td>Maxilan LMS</td></tr>
<tr><td>LTS</td><td>! Public EUROPE Vanilla LTS</td></tr>
<tr><td>LTS</td><td>Maxilan LTS</td></tr>
<tr><td>MOD</td><td>Metalbanana [DM with tunings]</td></tr>
<tr><td>PlayLife</td><td>PlayLife [Early Access] | <= Jobs, Minigames, Ranking, Level & m</td></tr>
<tr><td>Race</td><td>[ Flyrate ] Race Server</td></tr>
<tr><td>Race</td><td>[ Flyrate ] run_guy_25 server</td></tr>
<tr><td>TDM</td><td>! ! ! ePlay TV Fun-Server TDM ! ! !</td></tr>
<tr><td>TDM</td><td>Discord-Linux.com</td></tr>
<tr><td>TDM</td><td>LinuxGSM</td></tr>
<tr><td>TDM</td><td>Maxilan Team Death Match</td></tr>
<tr><td>TDM</td><td>Memory16's Server</td></tr>
<tr><td>TDM</td><td>Teeworlds.Net - TDM 1</td></tr>
<tr><td>fng2</td><td>[中国整活服][香港]Kelvin老姐姐的献祭服[FNG]</td></tr>
<tr><td>fng2</td><td>ΛLIVΣ FNG2 Boom Server</td></tr>
<tr><td>fng2</td><td>ΛLIVΣ FNG2 Server</td></tr>
<tr><td>fng2</td><td>ΛLIVΣ FNG2 Server</td></tr>
<tr><td>fng2</td><td>ΛLIVΣ FNG2 Solo Server</td></tr>
<tr><td>gCTF+</td><td>Simply gCTF Server #1</td></tr>
<tr><td>gCTF+</td><td>Simply gCTF Server #2</td></tr>
<tr><td>iCTF*</td><td>inQontroL Instagib ICTF Clanserver - www.inQontrol.de</td></tr>
<tr><td>iCTF*</td><td>inQontroL Instagib ICTF Clanserver - www.inQontrol.de</td></tr>
<tr><td>iCTF*</td><td>inQontroL Instagib ICTF Clanserver - www.inQontrol.de</td></tr>
<tr><td>iCTF*</td><td>inQontroL Instagib ICTF Clanserver - www.inQontrol.de</td></tr>
<tr><td>iDM*</td><td>inQontroL Instagib 1on1 IDM Server - www.inQontrol.de</td></tr>
<tr><td>zCatch</td><td>Just zCatch Grenade</td></tr>
<tr><td>zCatch</td><td>Simply zCatch Grenade</td></tr>
<tr><td>zCatch</td><td>Simply zCatch Grenade Beginner Server</td></tr>
<tr><td>zCatch</td><td>Simply zCatch Laser</td></tr>
<tr><td>zCatch</td><td>[TCN] ZCatch Server</td></tr>
</table>
</details>

Currently I'm in favor of @ChillerDragon continuing to work on this. Let's maybe wait a week or so for everyone to give their opinion on this.

2023-07-15 08:55 UTC, ChillerDragon commented on src/engine/shared/network.h
> +class CNetClient : public CNetBase
done :)

2023-07-24 20:07 UTC, heinrich5991 commented
Status: Don't have the energy to deal with this PR right now.

2023-07-29 12:00 UTC, ChillerDragon commented
Thanks to @Robyt3 the client can now load 0.7 maps!!!

It loads the 0.7 version of generic_unhookable, grass_dooads and grass_main if needed.

```patch
diff --git a/src/game/client/components/mapimages.cpp b/src/game/client/components/mapimages.cpp
index ffcf38768..a48d5fc74 100644
--- a/src/game/client/components/mapimages.cpp
+++ b/src/game/client/components/mapimages.cpp
@@ -111,7 +111,8 @@ void CMapImages::OnMapLoadImpl(class CLayers *pLayers, IMap *pMap)
                {
                        char aPath[IO_MAX_PATH_LENGTH];
                        char *pName = (char *)pMap->GetData(pImg->m_ImageName);
-                       str_format(aPath, sizeof(aPath), "mapres/%s.png", pName);
+                       bool Translated = Client()->IsSixup() && (!str_comp(pName, "grass_doodads") || !str_comp(pName, "grass_main") || !str_comp(pName, "generic_unhookable"));
+                       str_format(aPath, sizeof(aPath), "mapres/%s%s.png", pName, Translated ? "_0.7" : "");
                        m_aTextures[i] = Graphics()->LoadTexture(aPath, IStorage::TYPE_ALL, CImageInfo::FORMAT_AUTO, LoadFlag);
                        pMap->UnloadData(pImg->m_ImageName);
                }
```

Here a screenshot of a vanilla 0.7 teeworlds server with the official 0.7 dm1 map.

![screenshot_2023-07-29_13-59-33](https://github.com/ddnet/ddnet/assets/20344300/d83fbf94-6de6-4825-8e3a-01815c1c04ee)

2023-08-05 08:52 UTC, heinrich5991 commented
> Any objections to adding the version column? Too visually polluting? Too little space? Too technical?

Yes, I think it offers little value to the user for the space it uses.

2023-08-05 13:16 UTC, ChillerDragon commented
> > Any objections to adding the version column? Too visually polluting? Too little space? Too technical?
> 
> Yes, I think it offers little value to the user for the space it uses.

So what do you suggest instead? Just list 0.7 servers without indicating their version anywhere?

2023-08-05 14:08 UTC, ChillerDragon commented
@heinrich5991 I added NETTYPE_TW7 into the the NETADDR type field as you suggested.

<details>

```diff
diff --git a/src/base/system.cpp b/src/base/system.cpp
index a5ceb3d5a..6870abefc 100644
--- a/src/base/system.cpp
+++ b/src/base/system.cpp
@@ -1027,7 +1027,7 @@ int64_t time_freq()
 static void netaddr_to_sockaddr_in(const NETADDR *src, struct sockaddr_in *dest)
 {
 	mem_zero(dest, sizeof(struct sockaddr_in));
-	if(src->type != NETTYPE_IPV4 && src->type != NETTYPE_WEBSOCKET_IPV4)
+	if(!(src->type & NETTYPE_IPV4) && !(src->type & NETTYPE_WEBSOCKET_IPV4))
 	{
 		dbg_msg("system", "couldn't convert NETADDR of type %d to ipv4", src->type);
 		return;
@@ -1041,9 +1041,9 @@ static void netaddr_to_sockaddr_in(const NETADDR *src, struct sockaddr_in *dest)
 static void netaddr_to_sockaddr_in6(const NETADDR *src, struct sockaddr_in6 *dest)
 {
 	mem_zero(dest, sizeof(struct sockaddr_in6));
-	if(src->type != NETTYPE_IPV6)
+	if(!(src->type & NETTYPE_IPV6))
 	{
-		dbg_msg("system", "couldn't not convert NETADDR of type %d to ipv6", src->type);
+		dbg_msg("system", "couldn't convert NETADDR of type %d to ipv6", src->type);
 		return;
 	}
 
@@ -1169,16 +1169,16 @@ void net_addr_str_v6(const unsigned short ip[8], int port, char *buffer, int buf
 	}
 }
 
-void net_addr_str(const NETADDR *addr, char *string, int max_length, int add_port)
+int net_addr_str(const NETADDR *addr, char *string, int max_length, int add_port)
 {
-	if(addr->type == NETTYPE_IPV4 || addr->type == NETTYPE_WEBSOCKET_IPV4)
+	if(addr->type & NETTYPE_IPV4 || addr->type & NETTYPE_WEBSOCKET_IPV4)
 	{
 		if(add_port != 0)
 			str_format(string, max_length, "%d.%d.%d.%d:%d", addr->ip[0], addr->ip[1], addr->ip[2], addr->ip[3], addr->port);
 		else
 			str_format(string, max_length, "%d.%d.%d.%d", addr->ip[0], addr->ip[1], addr->ip[2], addr->ip[3]);
 	}
-	else if(addr->type == NETTYPE_IPV6)
+	else if(addr->type & NETTYPE_IPV6)
 	{
 		int port = -1;
 		unsigned short ip[8];
@@ -1194,7 +1194,27 @@ void net_addr_str(const NETADDR *addr, char *string, int max_length, int add_por
 		net_addr_str_v6(ip, port, string, max_length);
 	}
 	else
+	{
 		str_format(string, max_length, "unknown type %d", addr->type);
+		return 1;
+	}
+	return 0;
+}
+
+void net_addr_url_str(const NETADDR *addr, char *string, int max_length, int add_port)
+{
+	char ipaddr[512];
+	if(net_addr_str(addr, ipaddr, sizeof(ipaddr), add_port))
+	{
+		str_copy(string, ipaddr, max_length);
+		return;
+	}
+	str_format(
+		string,
+		max_length,
+		"tw-%s+udp://%s",
+		addr->type & NETTYPE_TW7 ? "0.7" : "0.6",
+		ipaddr);
 }
 
 static int priv_net_extract(const char *hostname, char *host, int max_host, int *port)
@@ -1351,14 +1371,18 @@ int net_addr_from_url(NETADDR *addr, const char *string, char *host_buf, size_t
 	int start = 0;
 	int end;
 	int failure;
+	bool sixup = false;
+	mem_zero(addr, sizeof(*addr));
 	const char *str = str_startswith(string, "tw-0.6+udp://");
 	if(!str)
+	{
 		str = str_startswith(string, "tw-0.7+udp://");
+		addr->type |= NETTYPE_TW7;
+		sixup = true;
+	}
 	if(!str)
 		return 1;
 
-	mem_zero(addr, sizeof(*addr));
-
 	length = str_length(str);
 	end = length;
 	for(int i = 0; i < length; i++)
@@ -1385,6 +1409,9 @@ int net_addr_from_url(NETADDR *addr, const char *string, char *host_buf, size_t
 	if((failure = net_addr_from_str(addr, host)))
 		return failure;
 
+	if(sixup)
+		addr->type |= NETTYPE_TW7;
+
 	return failure;
 }
 
diff --git a/src/base/system.h b/src/base/system.h
index 40b399b41..7e36e2f01 100644
--- a/src/base/system.h
+++ b/src/base/system.h
@@ -845,6 +845,7 @@ enum
 	NETTYPE_IPV4 = 1,
 	NETTYPE_IPV6 = 2,
 	NETTYPE_WEBSOCKET_IPV4 = 8,
+	NETTYPE_TW7 = 16,
 
 	NETTYPE_ALL = NETTYPE_IPV4 | NETTYPE_IPV6 | NETTYPE_WEBSOCKET_IPV4,
 	NETTYPE_MASK = NETTYPE_ALL | NETTYPE_LINK_BROADCAST,
@@ -933,9 +934,28 @@ int net_addr_comp_noport(const NETADDR *a, const NETADDR *b);
  * @param max_length Maximum size of the string.
  * @param add_port add port to string or not
  *
+ * @return 0 on success,
+ *
+ * @remark The string will always be zero terminated
+ */
+int net_addr_str(const NETADDR *addr, char *string, int max_length, int add_port);
+
+/**
+ * Turns a network address into a url string.
+ * Examples:
+ *   tw-0.6+udp://127.0.0.1:8303
+ *   tw-0.7+udp://127.0.0.1
+ *
+ * @ingroup Network-General
+ *
+ * @param addr Address to turn into a string.
+ * @param string Buffer to fill with the url string.
+ * @param max_length Maximum size of the url string.
+ * @param add_port add port to url string or not
+ *
  * @remark The string will always be zero terminated
  */
-void net_addr_str(const NETADDR *addr, char *string, int max_length, int add_port);
+void net_addr_url_str(const NETADDR *addr, char *string, int max_length, int add_port);
 
 /**
  * Turns url string into a network address struct.
diff --git a/src/engine/client/client.cpp b/src/engine/client/client.cpp
index 6186b892d..f388642fe 100644
--- a/src/engine/client/client.cpp
+++ b/src/engine/client/client.cpp
@@ -844,6 +844,7 @@ void CClient::Connect(const char *pAddress, bool Sixup, const char *pPassword)
 		NETADDR NextAddr;
 		char aHost[128];
 		int url = net_addr_from_url(&NextAddr, aBuffer, aHost, sizeof(aHost));
+		bool sixup = NextAddr.type & NETTYPE_TW7;
 		if(url > 0)
 			str_copy(aHost, aBuffer);
 
@@ -862,6 +863,8 @@ void CClient::Connect(const char *pAddress, bool Sixup, const char *pPassword)
 			NextAddr.port = 8303;
 		}
 		char aNextAddr[NETADDR_MAXSTRSIZE];
+		if(sixup)
+			NextAddr.type |= NETTYPE_TW7;
 		net_addr_str(&NextAddr, aNextAddr, sizeof(aNextAddr), true);
 		log_debug("client", "resolved connect address '%s' to %s", aBuffer, aNextAddr);
 		aConnectAddrs[NumConnectAddrs] = NextAddr;
@@ -892,8 +895,10 @@ void CClient::Connect(const char *pAddress, bool Sixup, const char *pPassword)
 	m_UseTempRconCommands = 0;
 	m_pConsole->DeregisterTempAll();
 
-	if((m_Sixup = Sixup))
+	if((m_Sixup = aConnectAddrs[0].type & NETTYPE_TW7))
+	{
 		m_aNetClient[CONN_MAIN].Connect7(aConnectAddrs, NumConnectAddrs);
+	}
 	else
 		m_aNetClient[CONN_MAIN].Connect(aConnectAddrs, NumConnectAddrs);
 
diff --git a/src/engine/client/serverbrowser.cpp b/src/engine/client/serverbrowser.cpp
index 0657fac10..0439382f9 100644
--- a/src/engine/client/serverbrowser.cpp
+++ b/src/engine/client/serverbrowser.cpp
@@ -552,7 +552,7 @@ void ServerBrowserFormatAddresses(char *pBuffer, int BufferSize, NETADDR *pAddrs
 		{
 			return;
 		}
-		net_addr_str(&pAddrs[i], pBuffer, BufferSize, true);
+		net_addr_url_str(&pAddrs[i], pBuffer, BufferSize, true);
 		int Length = str_length(pBuffer);
 		pBuffer += Length;
 		BufferSize -= Length;
diff --git a/src/engine/shared/network_client.cpp b/src/engine/shared/network_client.cpp
index 6aa7e5fb4..f693174b7 100644
--- a/src/engine/shared/network_client.cpp
+++ b/src/engine/shared/network_client.cpp
@@ -91,6 +91,8 @@ int CNetClient::Recv(CNetChunk *pChunk, SECURITY_TOKEN *pResponseToken, bool Six
 		{
 			continue;
 		}
+		if(Sixup)
+			Addr.type |= NETTYPE_TW7;
 
 		SECURITY_TOKEN Token;
 		*pResponseToken = NET_SECURITY_TOKEN_UNKNOWN;
diff --git a/src/test/netaddr.cpp b/src/test/netaddr.cpp
index ccbf09648..ecc6450b5 100644
--- a/src/test/netaddr.cpp
+++ b/src/test/netaddr.cpp
@@ -2,18 +2,32 @@
 
 #include <base/system.h>
 
-TEST(NetAddr, FromUrlString)
+TEST(NetAddr, FromUrlStringInvalid)
 {
 	NETADDR Addr;
-	char aBuf1[NETADDR_MAXSTRSIZE];
-	char aBuf2[NETADDR_MAXSTRSIZE];
 
 	EXPECT_EQ(net_addr_from_url(&Addr, "tw-0.6+udp://127.0", nullptr, 0), -1); // invalid ip
 	EXPECT_EQ(net_addr_from_url(&Addr, "tw-0.6+udp://ddnet.org", nullptr, 0), -1); // invalid ip
 	EXPECT_EQ(net_addr_from_url(&Addr, "127.0.0.1", nullptr, 0), 1); // not a URL
 	EXPECT_EQ(net_addr_from_url(&Addr, "tw-0.9+udp://127.0.0.1", nullptr, 0), 1); // invalid tw protocol
-	EXPECT_EQ(net_addr_from_url(&Addr, "tw-0.7+udp://127.0.0.1", nullptr, 0), 1); // unsupported tw protocol
 	EXPECT_EQ(net_addr_from_url(&Addr, "tw-0.6+tcp://127.0.0.1", nullptr, 0), 1); // in [...]

2023-08-07 13:57 UTC, heinrich5991 commented
> In the browser it connects using 0.7 if the servers http master version field starts with "0.7"

The master server already communicates which servers support the 0.7 protocol, I think it'd be good to use this instead. I'd argue that we should connect via the 0.6 protocol if the server supports that, otherwise use the 0.7 protocol if the server supports that but not the 0.6 protocol.

2023-08-09 09:29 UTC, ChillerDragon commented
> > In the browser it connects using 0.7 if the servers http master version field starts with "0.7"
> 
> The master server already communicates which servers support the 0.7 protocol, I think it'd be good to use this instead. I'd argue that we should connect via the 0.6 protocol if the server supports that, otherwise use the 0.7 protocol if the server supports that but not the 0.6 protocol.
> 
> ```json
>     {
>       "addresses": [
>         "tw-0.6+udp://5.78.73.17:8306",
>         "tw-0.7+udp://5.78.73.17:8306"
>       ],
>       "location": "as",
>       "info": {
>         "max_clients": 63,
>         "max_players": 63,
>         "passworded": false,
>         "game_type": "DDraceNetwork",
>         "name": "DDNet USA2 - Brutal",
>         "map": {
>           "name": "Grandma",
>           "sha256": "ed9532928b57ce9c8a0e3fbdf7424f201fbe090a762e5744781040fe20278ec5",
>           "size": 314327
>         },
>         "version": "0.6.4, 17.1.1",
>         "client_score_kind": "time",
>         "clients": []
>       }
>     }
> ```
> 
> The addresses field tells you that the server supports the 0.6 and the 0.7 protocol:
> 
> ```json
>       "addresses": [
>         "tw-0.6+udp://5.78.73.17:8306",
>         "tw-0.7+udp://5.78.73.17:8306"
>       ]
> ```

Currently all servers supporting both 0.6 and 0.7 do not start with 0.7 in the version field. This gives the server owner a choice to pick a preferred version. And would as of right now only connect to in 0.7 mode to vanilla 0.7.5 servers. But if its a hard no from your side I can also refactor the code. Iirc it needs some tweaking because the addresses are not stored as urls so the version info is lost. So that would have to change. And it needs a iteration over the addresses before connect to check which versions are available. All in all sounds doable.

2023-08-09 14:12 UTC, heinrich5991 commented
> This gives the server owner a choice to pick a preferred version.

Can we come up with a scenario where this makes sense?

2023-08-11 11:28 UTC, ChillerDragon commented
@heinrich5991 it is now connecting via 0.6 as soon as one of the addresses is 0.7
And I also removed the version column from the browser again.

<details>

```diff
diff --git a/src/engine/client/client.cpp b/src/engine/client/client.cpp
index b307e0c81..6701cc043 100644
--- a/src/engine/client/client.cpp
+++ b/src/engine/client/client.cpp
@@ -838,6 +838,7 @@ void CClient::Connect(const char *pAddress, const char *pPassword)
        mem_zero(aConnectAddrs, sizeof(aConnectAddrs));
        const char *pNextAddr = pAddress;
        char aBuffer[128];
+       bool OnlySixup = true;
        while((pNextAddr = str_next_token(pNextAddr, ",", aBuffer, sizeof(aBuffer))))
        {
                NETADDR NextAddr;
@@ -864,6 +865,8 @@ void CClient::Connect(const char *pAddress, const char *pPassword)
                char aNextAddr[NETADDR_MAXSTRSIZE];
                if(Sixup)
                        NextAddr.type |= NETTYPE_TW7;
+               else
+                       OnlySixup = false;
                net_addr_str(&NextAddr, aNextAddr, sizeof(aNextAddr), true);
                log_debug("client", "resolved connect address '%s' to %s", aBuffer, aNextAddr);
                aConnectAddrs[NumConnectAddrs] = NextAddr;
@@ -894,7 +897,7 @@ void CClient::Connect(const char *pAddress, const char *pPassword)
        m_UseTempRconCommands = 0;
        m_pConsole->DeregisterTempAll();
 
-       if((m_Sixup = aConnectAddrs[0].type & NETTYPE_TW7))
+       if((m_Sixup = OnlySixup))
        {
                m_aNetClient[CONN_MAIN].Connect7(aConnectAddrs, NumConnectAddrs);
        }
diff --git a/src/game/client/components/menus_browser.cpp b/src/game/client/components/menus_browser.cpp
index 8eabbcc83..e97efa2b6 100644
--- a/src/game/client/components/menus_browser.cpp
+++ b/src/game/client/components/menus_browser.cpp
@@ -101,7 +101,7 @@ void CMenus::RenderServerbrowserServerList(CUIRect View)
                {COL_PLAYERS, IServerBrowser::SORT_NUMPLAYERS, "Players", 1, 85.0f, {0}, {0}},
                {-1, -1, " ", 1, 10.0f, {0}, {0}},
                {COL_PING, IServerBrowser::SORT_PING, "Ping", 1, 40.0f, {0}, {0}},
-               {COL_VERSION, IServerBrowser::SORT_VERSION, "Version", 1, 40.0f, {0}, {0}},
+               // {COL_VERSION, IServerBrowser::SORT_VERSION, "Version", 1, 40.0f, {0}, {0}},
        };
 
        int NumCols = std::size(s_aCols);
```

</details>

2023-08-22 13:47 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +			if(MsgId >= OFFSET_UUID) // TODO: this still by learath2 do we need dis?
thanks

2023-08-27 10:11 UTC, ChillerDragon commented
@heinrich5991 formally requesting another review. Ready to merge.

2023-08-27 11:32 UTC, Kaffeine commented on src/base/system.cpp
> +int net_addr_str(const NETADDR *addr, char *string, int max_length, int add_port)
`bool`?

2023-08-27 11:37 UTC, ChillerDragon commented on src/base/system.cpp
> +int net_addr_str(const NETADDR *addr, char *string, int max_length, int add_port)
I guess until #6436 is closed one can use what he wants

2023-08-27 11:41 UTC, Kaffeine commented on src/base/system.cpp
> +int net_addr_str(const NETADDR *addr, char *string, int max_length, int add_port)
Oh, here it is. Fair enough.
I was looking for that issue and its status but found only other works toward bool ([1](https://github.com/ddnet/ddnet/pull/6343/files), [2](https://github.com/ddnet/ddnet/pull/6429/files), you know...)

2023-08-31 08:57 UTC, ChillerDragon commented
I put the skin configs in a player7_ namespace so the body config for 0.7 is ``player7_skin_body`` and the one for 0.6 still is ``player_skin_body``. I do not like that very much. But also do not know what would be better. They should be separated for sure otherwise switching between 0.6 and 0.7 resets the skin of the other version or you start sending wrong versioned skins.

2023-09-30 12:58 UTC, ChillerDragon commented
Could I get some update on this pr? When I asked for a fast merge to reduce git conflict work I did not expect it to merged the next day. But it has almost been a year.

When allocating one hour to work on this every few weeks I easily spend half of it only on rebasing.

The current state is not bug free or perfect. But I incorporated all feedback and 0.7 servers are actually playable.

2023-09-30 13:16 UTC, def- commented
Fine by me to submit.

2023-09-30 13:34 UTC, ChillerDragon commented
The biggest user facing work in progress area is the 0.7 skin menu. Which has empty parts.
The basic section is empty. So is the unused personal section. And markings are not being rendered in the skin menu or in game.
But the visible things in the skin menu work. Except the randomize skin button which is a bit bugged so I deactivated that one for now.

![screenshot_2023-09-30_15-24-48](https://github.com/ddnet/ddnet/assets/20344300/f4648b24-85ef-469f-a9b5-d87e903c6aa1)
![screenshot_2023-09-30_15-32-13](https://github.com/ddnet/ddnet/assets/20344300/bd353c7d-3bfc-4f4e-aa2a-b9641df7933d)
![screenshot_2023-09-30_15-31-53](https://github.com/ddnet/ddnet/assets/20344300/a5eef14a-c7a8-40c3-915d-0ce028ab09ec)

2023-10-01 11:45 UTC, ChillerDragon commented
Added support for dummy skins. Listed all skins in the basic section. Fixed the randomize button.
I would consider the skin menu ready to use.
Missing nice to haves would be:
- [ ] skin save button
- [ ] search

![screenshot_2023-10-01_13-43-08](https://github.com/ddnet/ddnet/assets/20344300/e592d7af-630f-4e3e-b79a-f548f839c755)
![screenshot_2023-10-01_13-43-31](https://github.com/ddnet/ddnet/assets/20344300/d4699ece-c5fb-4a1b-aefa-4a58c5e709b6)
![screenshot_2023-10-01_13-43-42](https://github.com/ddnet/ddnet/assets/20344300/a2505976-c8db-4d7e-9a60-9b3b82111159)

2023-10-03 09:25 UTC, ChillerDragon commented
Fixed dummy and squashed all together in one commit.

2023-10-05 08:49 UTC, ChillerDragon commented
Fixed another conflict :)

Anything I can do to progress the merge? @def- @heinrich5991

2023-10-05 10:40 UTC, def- commented
I'll merge this tomorrow if @heinrich5991 doesn't complain.

2023-10-05 11:21 UTC, Robyt3 requested changes
At the moment, there are too many open TODOs and too much dead (commented) code being added for my taste. This currently adds around 45 TODOs.

Is it possible to extract the changes to system to a separate PR?

2023-10-05 11:21 UTC, Robyt3 commented on src/engine/client/serverbrowser.cpp
> +
Seems unnecessary to me. Why do you want to sort by version?

2023-10-05 11:21 UTC, Robyt3 commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(ClMenuAlpha, cl_menu_alpha, 25, 0, 75, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Transparency of the menu background")
It's unused and I don't think it belongs in this PR.

2023-10-05 11:21 UTC, Robyt3 commented on src/engine/shared/network.cpp
> +	static unsigned char s_aRequestTokenBuf[NET_TOKENREQUEST_DATASIZE];
Why is this static? Should be avoided if possible.

2023-10-05 11:21 UTC, Robyt3 commented on src/game/client/components/menus.cpp
> +	m_SkinNameInput.SetBuffer(m_aSaveSkinName, sizeof(m_aSaveSkinName), protocol7::MAX_SKIN_LENGTH);
Should use `CLineInputBuffered`. Remove these lines.

2023-10-05 11:21 UTC, Robyt3 commented on src/game/client/components/menus.h
> +	CLineInput m_SkinNameInput;
Replace with `CLineInputBuffered<protocol7::MAX_SKIN_ARRAY_SIZE, protocol7::MAX_SKIN_LENGTH> m_SkinNameInput;`

2023-10-05 11:21 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +void CMenus::RenderHSLPicker(CUIRect MainView)
I don't like how this adds yet another color picker implementation to our code.

2023-10-05 11:21 UTC, Robyt3 commented on src/game/client/render.cpp
> +
Should be refactored to reduce the duplicate code.

2023-10-05 11:21 UTC, Robyt3 commented on src/game/client/render.cpp
> +
Same, duplicate code. Also looks like a bug, you are checking the number of sprites in the normal data and not in the data7.

2023-10-05 11:21 UTC, Robyt3 commented on src/engine/client/client.cpp
> +	str_copy(pSelf->m_aCmdConnect, pResult->GetString(0));
Remove, `HandleConnectLink` already does this.

2023-10-05 15:37 UTC, ChillerDragon commented
Thanks a lot for looking into it @Robyt3
Good findings as always! I will implement fixes next time I get to working on this.

Some of the things you mentioned will take me quite some time to fix. Do you have any suggestions on how to do a partial merge or reduce git conflicts during that time?

> Is it possible to extract the changes to system to a separate PR?

You mean changes to system.cpp and system.h? Yea I would love that. As long as it actually gets merged and does not end up as two stale prs that depend on each other. Heinrich gave me the impression on [this](https://github.com/ddnet/ddnet/pull/6876) pr that this 0.7 stuff should not be added while it is unused.

2023-10-05 17:20 UTC, Robyt3 commented on src/engine/client/client.cpp
> +	if((m_Sixup = OnlySixup))
Avoid assignment inside if-condition.

2023-10-05 17:25 UTC, Robyt3 commented on src/game/client/components/scoreboard.cpp
> +			TextRender()->TextEx(&Cursor, "\xE2\x9C\x93", str_length("\xE2\x9C\x93"));
`TextRender()->TextEx(&Cursor, "⚙");`

2023-10-05 17:43 UTC, Robyt3 commented
> Do you have any suggestions on how to do a partial merge or reduce git conflicts during that time?

Not really, unfortunately. Many of your changes are already in separate files so at least those will not conflict. It didn't look like there were notable unrelated changes that could be moved to a separate PR either, which would otherwise have helped. 

> You mean changes to system.cpp and system.h? Yea I would love that. As long as it actually gets merged and does not end up as two stale prs that depend on each other. Heinrich gave me the impression on this pr that this 0.7 stuff should not be added while it is unused.

I see.

2023-10-05 19:24 UTC, Kaffeine commented on src/engine/shared/network_client.cpp
> +#include <engine/shared/config.h>
Seems unused

2023-10-06 10:17 UTC, ChillerDragon commented on src/engine/shared/network_client.cpp
> +#include <engine/shared/config.h>
Indeed is! Thanks fixed :)

2023-10-06 10:18 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +	str_copy(pSelf->m_aCmdConnect, pResult->GetString(0));
Oh yea good catch! That is not supposed to be there anyways. Thats a super old hack/test I needed to make the ``./DDNet "connect localhost 0.7"`` work.

Fixed

2023-10-06 10:35 UTC, ChillerDragon commented on src/engine/shared/network.cpp
> +	static unsigned char s_aRequestTokenBuf[NET_TOKENREQUEST_DATASIZE];
It is passed as a pointer to a function call.
```
CNetBase::SendControlMsg(Socket, pAddr, 0, ControlMsg, s_aRequestTokenBuf, Extended ? sizeof(s_aRequestTokenBuf) : 4, Token, true);
```

The way I understood C++ this is not good if it is just a local variable.
It used to be a member variable but that added an inheritance heinrich did not like.

What do you suggest to do? Remove the static? Is that safe?

2023-10-06 10:37 UTC, ChillerDragon commented on src/engine/shared/network.cpp
> +	static unsigned char s_aRequestTokenBuf[NET_TOKENREQUEST_DATASIZE];
Or is the lifetime of the variable until the call to ``SendControlMsg`` finished? Which then directly does a mem copy. So it should be safe? Still seems kinda spooky to me.

2023-10-06 11:28 UTC, heinrich5991 commented on src/engine/shared/network.cpp
> +	static unsigned char s_aRequestTokenBuf[NET_TOKENREQUEST_DATASIZE];
Local variables live until the end of the function. This is fine as a local variable here.

2023-10-06 12:11 UTC, ChillerDragon commented on src/engine/shared/network.cpp
> +	static unsigned char s_aRequestTokenBuf[NET_TOKENREQUEST_DATASIZE];
Okay cool thanks. Is that a good style coding pattern? Seems like it lays the foundation for memory bugs being added when the called function is then refactored.

2023-10-06 12:19 UTC, heinrich5991 commented on src/engine/shared/network.cpp
> +	static unsigned char s_aRequestTokenBuf[NET_TOKENREQUEST_DATASIZE];
> Seems like it lays the foundation for memory bugs being added when the called function is then refactored.

That would be a wrong refactoring even with the static variable. It'll change on the next call, so calling this function twice would result in the same pointer being passed to `SendControlMsg`.

It'd rather be bad code style to have a static variable here.

2023-10-06 12:36 UTC, ChillerDragon commented on src/engine/client/serverbrowser.cpp
> +
Yes it is now unnecessary. For a short time there was a version column in the browser which this was used for. But I removed it and forgot to clean it up. I now also reverted the other places related to this which I did not clean up yet

```diff
diff --git a/src/engine/client/serverbrowser.cpp b/src/engine/client/serverbrowser.cpp
index 42eecb7d0..e62ae1bc7 100644
--- a/src/engine/client/serverbrowser.cpp
+++ b/src/engine/client/serverbrowser.cpp
@@ -229,6 +229,13 @@ bool CServerBrowser::SortComparePing(int Index1, int Index2) const
        return pIndex1->m_Info.m_Latency < pIndex2->m_Info.m_Latency;
 }
 
+bool CServerBrowser::SortCompareVersion(int Index1, int Index2) const
+{
+       CServerEntry *pIndex1 = m_ppServerlist[Index1];
+       CServerEntry *pIndex2 = m_ppServerlist[Index2];
+       return str_comp(pIndex1->m_Info.m_aVersion, pIndex2->m_Info.m_aVersion) < 0;
+}
+
 bool CServerBrowser::SortCompareGametype(int Index1, int Index2) const
 {
        CServerEntry *pIndex1 = m_ppServerlist[Index1];
@@ -455,6 +462,8 @@ void CServerBrowser::Sort()
                std::stable_sort(m_pSortedServerlist, m_pSortedServerlist + m_NumSortedServers, CSortWrap(this, &CServerBrowser::SortCompareName));
        else if(g_Config.m_BrSort == IServerBrowser::SORT_PING)
                std::stable_sort(m_pSortedServerlist, m_pSortedServerlist + m_NumSortedServers, CSortWrap(this, &CServerBrowser::SortComparePing));
+       else if(g_Config.m_BrSort == IServerBrowser::SORT_VERSION)
+               std::stable_sort(m_pSortedServerlist, m_pSortedServerlist + m_NumSortedServers, CSortWrap(this, &CServerBrowser::SortCompareVersion));
        else if(g_Config.m_BrSort == IServerBrowser::SORT_MAP)
                std::stable_sort(m_pSortedServerlist, m_pSortedServerlist + m_NumSortedServers, CSortWrap(this, &CServerBrowser::SortCompareMap));
        else if(g_Config.m_BrSort == IServerBrowser::SORT_NUMPLAYERS)
diff --git a/src/engine/client/serverbrowser.h b/src/engine/client/serverbrowser.h
index 63cf2db29..170769a3c 100644
--- a/src/engine/client/serverbrowser.h
+++ b/src/engine/client/serverbrowser.h
@@ -142,6 +142,7 @@ private:
        bool SortCompareName(int Index1, int Index2) const;
        bool SortCompareMap(int Index1, int Index2) const;
        bool SortComparePing(int Index1, int Index2) const;
+       bool SortCompareVersion(int Index1, int Index2) const;
        bool SortCompareGametype(int Index1, int Index2) const;
        bool SortCompareNumPlayers(int Index1, int Index2) const;
        bool SortCompareNumClients(int Index1, int Index2) const;
```

[![browserversions](https://user-images.githubusercontent.com/20344300/258421940-d4100cbb-5511-4132-8000-81299c6e7b22.png)](https://github.com/ddnet/ddnet/pull/5949#issuecomment-1665569102)

2023-10-06 13:14 UTC, Kaffeine commented on src/engine/shared/network.cpp
> +	static unsigned char s_aRequestTokenBuf[NET_TOKENREQUEST_DATASIZE];
> Or is the lifetime of the variable until the call to `SendControlMsg` finished? Which then directly does a mem copy. So it should be safe? Still seems kinda spooky to me.

The code (without `static`) is totally fine. It would be "spooky" (ASAN should catch it) if you'd *return* a pointer to a local variable. Making a function call with a local variable is 100% legit.

2023-10-06 13:28 UTC, ChillerDragon commented on src/game/client/render.cpp
> +
Fixed the bug. Is the duplication here really bad? I mean it is looking up in another array. So no idea how this would be deduplicated. Templates?

2023-10-06 13:51 UTC, Kaffeine commented on src/game/client/render.cpp
> +
I it would be a lot of work but I think it is doable to extract all structs from client_data headers and use `client_data7` version for `client_data`.

As I see it:
1. In data (6) change `CDataSound::m_Id` type to `CSampleHandle`
2. In data (6) add `int m_Flag = 0;` to `CDataImage`.
3. Maybe extract the structs to some `client_data_types.h`
4. Drop the structs from `client_data7`, `#include "client_data_types.h"`.
5. Keep `extern CDataContainer *g_pData;` and following code in both `client_data.h` and `client_data7.h`.

This can (and thus should) be done in a separated PR.

Finally: use the same CRenderTools::SelectSprite() in both selection wrappers:

```cpp
void CRenderTools::SelectSprite(int Id, int Flags, int sx, int sy)
{
	if(Id < 0 || Id >= g_pData->m_NumSprites)
		return;
	SelectSprite(&g_pData->m_aSprites[Id], Flags, sx, sy);
}

void CRenderTools::SelectSprite7(int Id, int Flags, int sx, int sy)
{
	if(Id < 0 || Id >= client_data7::g_pData->m_NumSprites)
		return;
	SelectSprite(&client_data7::g_pData->m_aSprites[Id], Flags, sx, sy);
}
```

2023-10-06 14:01 UTC, Kaffeine commented on src/game/client/render.cpp
> +
Hm, "Change CDataSound::m_Id type to `CSampleHandle`" seems to be a self-contained subtask and maybe someone will do it as a part of game refactoring. Such PR would be typical for @Robyt3 :smile: but maybe I can do it if you (ddnet devs) want.

Easier way: do the opposite and change `client_data7::CDataSound::m_Id` type to `int` for now.

2023-10-06 14:33 UTC, Kaffeine commented on src/game/client/render.cpp
> +
Here you are: https://github.com/ddnet/ddnet/pull/7309 (the easiest approach to unblock this PR)

2023-10-08 09:53 UTC, ChillerDragon commented on src/game/client/components/menus_settings.cpp
> +void CMenus::RenderHSLPicker(CUIRect MainView)
Fixed. I reused the ddnet color picker now.

2023-10-08 09:54 UTC, ChillerDragon commented
As requested by robsti I removed the teeworlds color picker and used the ddnet color picker instead.

![screenshot_2023-10-08_11-52-18](https://github.com/ddnet/ddnet/assets/20344300/24288297-e434-49bd-b11b-965c1907b11c)
![screenshot_2023-10-08_11-52-33](https://github.com/ddnet/ddnet/assets/20344300/578d4a0b-1c66-41e4-9fd4-37706e7fb533)

2023-10-20 13:21 UTC, ChillerDragon commented on src/game/client/render.cpp
> +
Solved that thanks to @Kaffeine

2023-10-20 14:49 UTC, ChillerDragon commented on src/game/client/render.cpp
> +
As I said fixed the bug. @Robyt3 is the duplication really an issue or can we mark this as solved?

```c++
void CRenderTools::SelectSprite(int Id, int Flags, int sx, int sy)
{
	if(Id < 0 || Id >= g_pData->m_NumSprites)
		return;
	SelectSprite(&g_pData->m_aSprites[Id], Flags, sx, sy);
}

void CRenderTools::SelectSprite7(int Id, int Flags, int sx, int sy)
{
	if(Id < 0 || Id >= client_data7::g_pData->m_NumSprites)
		return;
	SelectSprite(&client_data7::g_pData->m_aSprites[Id], Flags, sx, sy);
}
```

This is how it looks like now. Seems similar but it is accessing different g_pData's so that seems fine to me.

2023-10-21 10:07 UTC, Robyt3 commented on src/game/client/render.cpp
> +
Would probably be possible to reduce the duplicate code with templates, but I'm not sure it would improve readability, so I think this is okay for now.

2023-11-11 15:26 UTC, ChillerDragon commented
Update on this. I am still actively working on it. My current mission is getting rid of all commented out code and all TODO comments as robsti requested.

I just played on a CTF server for a few hours with this client and it was very smooth. Did not do that in years it was lots of fun.

2023-11-18 20:33 UTC, Kaffeine commented on src/base/system.cpp
> +int net_addr_str(const NETADDR *addr, char *string, int max_length, int add_port)
@ChillerDragon now you have to (use bool and return `true` for success).

2023-11-18 21:52 UTC, heinrich5991 commented
@ChillerDragon What's the current status on this?

2023-11-19 01:22 UTC, ChillerDragon commented
> @ChillerDragon What's the current status on this?

Same status as last week. And looks like it will stay like that for a few weeks. It is already working and playable. I update the original pr description at the top very actively. All newly found or solved bugs are listed there. Since robsti requested to get rid of all the TODOs and commented out code before it gets merged I have a lot to do. I will make some noise when I am ready for another round of reviews.

2023-11-19 01:30 UTC, ChillerDragon commented on src/base/system.cpp
> +int net_addr_str(const NETADDR *addr, char *string, int max_length, int add_port)
done

2023-11-19 09:51 UTC, Robyt3 requested changes

2023-11-19 09:51 UTC, Robyt3 commented on src/game/client/components/broadcast.cpp
> +	m_ClientBroadcastTime7 = 0;
Maybe you could add the client broadcast in a separate PR already as a general purpose client feature, then we can discuss that on its own. Skip the suffix `7` on the related names. And add `client_broadcast` (or just `broadcast`) as client-side command to show a client broadcast.

2023-11-19 09:51 UTC, Robyt3 commented on src/game/client/components/broadcast.cpp
> +	if(m_BroadcastRenderOffset < 0.0f)
Use a separate variable for client and server broadcast render offsets or you'll get issues when both are rendered at the same time with different offsets.

2023-11-19 09:51 UTC, Robyt3 commented on src/game/client/components/broadcast.cpp
> +	m_ClientBroadcastTime7 = Client()->LocalTime() + 10.0f;
Reset the client broadcast render offset to `-1.0f` here.

2023-12-24 14:34 UTC, Kaffeine commented
@ChillerDragon I fixed some 0.7 skins related issues at https://github.com/ChillerDragon/ddnet/pull/3.
My goal is enable 0.7 skins for 0.6 extended protocol. The [prototype](https://github.com/infclass/infclass-client/commit/1be36fbfe00b0cc8535a099f8ec077ab99fa752e) works somehow :)

2023-12-26 13:09 UTC, Kaffeine commented on src/game/client/render.h
>  	void RenderTee6(const CAnimState *pAnim, const CTeeRenderInfo *pInfo, int Emote, vec2 Dir, vec2 Pos, float Alpha = 1.0f);
Makes no sense to keep RenderTee6 without `const`.

2023-12-26 13:15 UTC, ChillerDragon commented on src/game/client/render.h
>  	void RenderTee6(const CAnimState *pAnim, const CTeeRenderInfo *pInfo, int Emote, vec2 Dir, vec2 Pos, float Alpha = 1.0f);
Clang told me so. What do you suggest I should do?

2023-12-26 13:16 UTC, ChillerDragon commented on src/game/client/components/controls.cpp
> +#include <engine/shared/protocolglue.h>
Good catch no idea how that happend

2023-12-26 13:16 UTC, Kaffeine commented on src/game/client/render.h
>  	void RenderTee6(const CAnimState *pAnim, const CTeeRenderInfo *pInfo, int Emote, vec2 Dir, vec2 Pos, float Alpha = 1.0f);
I think we'd better to have `const` both or none.

2023-12-26 13:20 UTC, ChillerDragon commented on src/game/client/render.h
>  	void RenderTee6(const CAnimState *pAnim, const CTeeRenderInfo *pInfo, int Emote, vec2 Dir, vec2 Pos, float Alpha = 1.0f);
I agree. But currently this is the only option that compiles. I just cba to mess with such esoterics right now I want to do some actual progress. If you wanna fix this go ahead :p

2023-12-26 13:22 UTC, Kaffeine commented on src/game/client/render.h
>  	void RenderTee6(const CAnimState *pAnim, const CTeeRenderInfo *pInfo, int Emote, vec2 Dir, vec2 Pos, float Alpha = 1.0f);
@ChillerDragon oh, I see. The `const` is forced by https://github.com/ddnet/ddnet/pull/7653.
I'll check the differences (what prevents RenderTee6 from being `const`) and comment or suggest a fix. I don't see why there is that difference, maybe we're doing something wrong.

2023-12-26 13:29 UTC, ChillerDragon commented on src/game/client/render.h
>  	void RenderTee6(const CAnimState *pAnim, const CTeeRenderInfo *pInfo, int Emote, vec2 Dir, vec2 Pos, float Alpha = 1.0f);
>  maybe we're doing something wrong.

I am sure :D

resolving this convo feel free to reopen c:

2024-03-11 07:46 UTC, ChillerDragon commented
Oopsie I accidentally force pushed all my commits away so github closed the pr. Nothing to see here.

2024-03-17 03:56 UTC, ChillerDragon commented
I added enums.h which just contains NUM_DUMMIES that a bit weird. But otherwise I struggle to use NUM_DUMMIES in the translation context class which is a member of the client class. Is that a problem? Is there a better way?

2024-03-19 10:34 UTC, furo321 reviewed
Seems to work pretty well, but I'm a bit concerned about the new `Tee 0.7` menu. Most people don't know what 0.7 is and would then get confused because they don't see the skin they just customized, in game. Also the menu itself doesn't fit in the with the "current UI style", and just looks out of place (in my opinion).

2024-03-19 10:34 UTC, furo321 commented on src/engine/shared/translation_context.h
> +	int m_LocalClientId[NUM_DUMMIES];
`m_aLocalClientId`

2024-03-19 10:34 UTC, furo321 commented on src/game/client/gameclient.h
> +		int m_SkinPartIds[NUM_SKINPARTS];
`m_aSkinPartIds`

2024-03-19 10:40 UTC, ChillerDragon commented
> I'm a bit concerned about the new Tee 0.7 menu. Most people don't know what 0.7 is and would then get confused because they don't see the skin they just customized, in game. Also the menu itself doesn't fit in the with the "current UI style", and just looks out of place (in my opinion).

We could show it only in menus in game if the current connection is 0.7 and then hide the 0.6 one. That should reduce confusion and also hide the ugly parts if unused :D

But yea it should not break the ddnet style I am just not that good with the ui code. I would love to merge it now as is and then hide it from the end user until it is polished. So remove the whole 0.7 support with a compile macro or commented code.

2024-03-19 22:35 UTC, Kaffeine commented
> `@Robyt3` this getting quite annoying to maintain. Since I am dragging along 3 commits every force push is a rebase. That now conflicts quite often also because of #8019
> Every time I work on this I have to slide in my patches into the first commit of this branch without updating the others.

@ChillerDragon, as I've said, [do whatever you want, e.g. squash everything into the only 0.7 support commit](https://github.com/ChillerDragon/ddnet/pull/3#issuecomment-1868574554). I had no idea that you'll have to tackle this for so long.

I think I'm mostly positive to have this merged. I had no time for the past two months but if  we'll have this merged and I have some time then I'll submit the prototype for "0.7 skins for 0.6/ddnet protocol". It is just a few lines of code allowing a server to set 0.7 skins to players.

2024-03-19 23:32 UTC, heinrich5991 commented
> We could show it only in menus in game if the current connection is 0.7 and then hide the 0.6 one.

I like this idea!

2024-03-20 17:30 UTC, Robyt3 requested changes
I'll try to review the remainder on the weekend. Haven't looked at the skins component and menu yet, but I agree we don't need to fix every TODO before we can merge this.

2024-03-20 17:30 UTC, Robyt3 commented on src/game/client/components/menus.h
> +
Order includes according to some logic, i.e. group them by folder, same as the other includes in this file. Also, the include of `render.h` is duplicate.

2024-03-20 17:30 UTC, Robyt3 commented on src/game/client/components/menus.cpp
> +	m_RefreshSkinSelector = true;
For new code, prefer adding variable initialization directly with the declaration instead of separately in the construtor (unless necessary like for function calls). This makes it more readable IMO.

2024-03-20 17:30 UTC, Robyt3 commented on src/engine/shared/translation_context.h
> +	const protocol7::CNetObj_PlayerInfoRace *m_paPlayerInfosRace[MAX_CLIENTS];
`m_apPlayerInfosRace`, it's an array of pointers

2024-03-20 17:30 UTC, Robyt3 commented on src/engine/shared/translation_context.h
> +		char m_aSkinName[64];
`MAX_SKIN_LENGTH` (which is 24) (you even added this constant)

2024-03-20 17:30 UTC, Robyt3 commented on src/engine/shared/translation_context.h
> +	struct CServerSettings
`class`

2024-03-20 17:30 UTC, Robyt3 commented on src/engine/shared/translation_context.h
> +	struct CClientData
`class`

2024-03-20 17:30 UTC, Robyt3 commented on src/engine/shared/translation_context.h
> +			str_copy(m_aSkinName, "default", sizeof(m_aSkinName));
Are we ever supposed to see those default values? If not, initialize everything to empty string instead.

Also, now that I see it, do a regex search on the new code for all `str_copy\((.*), .*?sizeof\(\1\)` or something like that and remove the `sizeof` argument, i.e. use the templated function instead.

2024-03-20 17:30 UTC, Robyt3 commented on src/engine/shared/demo.h
> +	bool m_Sixup;
Either add a setter and make the member private or remove the getter. Or don't add a setter if it's not necessary, I haven't looked at all code yet. The getter should be a const function, if kept.

2024-03-20 17:30 UTC, Robyt3 commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(ClPlayer7UseCustomColorBody, player7_use_custom_color_body, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggles usage of custom colors for body")
Other color variables should also have `CFGFLAG_INSENSITIVE` I think, same as the 0.6 variables.

2024-03-20 17:30 UTC, Robyt3 commented on src/engine/serverbrowser.h
> +	const char *ShortVersion() const { return str_startswith(m_aVersion, "0.7") ? "0.7" : "0.6"; }
Might also be unused because of the version column that we don't want.

2024-03-20 17:30 UTC, Robyt3 commented on src/engine/client/client.h
> +	bool IsSixup() override { return m_Sixup; };
`const` function and remove the trailing `;`

2024-03-20 17:30 UTC, Robyt3 commented on src/engine/client/client.cpp
> +		Msg.AddString(Config()->m_Password, 128);
Is 0.7 server password length limited to 128? Arguments should probably be removed so the strings are sent entirely (see 0.6 code below).

2024-03-20 17:30 UTC, Robyt3 commented on src/engine/client/client.cpp
> +		Msg7.AddString(pPassword, 32);
Is 0.7 rcon password length limited to 32? Arguments should probably be removed so the strings are sent entirely (see 0.6 code below).

2024-03-20 17:30 UTC, Robyt3 commented on src/engine/shared/snapshot.cpp
> +void CSnapshot::InvalidateItem(int Index)
This should probably better not exist, we don't handle the items with invalid index anywhere. Seems like it's only used once, where it would be better to discard the invalid netobj instead mangling and then propagating it.

2024-03-20 17:30 UTC, Robyt3 commented on src/engine/shared/protocolglue.h
> +#endif
Newline

2024-03-20 17:30 UTC, Robyt3 commented on src/engine/shared/protocol7.h
> +#include <base/system.h>
You only need to include `types.h` for `UTF8_BYTE_LENGTH`.

2024-03-23 03:10 UTC, ChillerDragon commented on src/game/client/components/menus_settings.cpp
> +		static std::vector<const char *> s_vpGpuIdNames;
Someone broke the style guide that was added in #8019 so the automated merge conflict solver fixed it. As soon as this gets fixed on master this diff is gone in my pr. Someone should fix the master branch and add it to the CI

https://github.com/ddnet/ddnet/pull/8019#issuecomment-1997599140

2024-03-23 03:18 UTC, ChillerDragon commented
Finally added a search to the skins menu :rocket: 

![image](https://github.com/ddnet/ddnet/assets/20344300/dc793ffa-75a3-451d-9547-256e0d5acadd)


... yes I am aware it is long o.O

2024-03-23 03:22 UTC, ChillerDragon commented on src/engine/client/sixup/translate_game.cpp
> +			str_format(aBuf, sizeof(aBuf), "'%s' has left the game (%s)", m_aClients[pMsg7->m_ClientId].m_aName, pMsg7->m_pReason);
You mean that in 0.7 normally "has left the game" is localized and this pr does not do it yet? Yes that is correct. I rather spend my time on actual bugs. #wontfix unless someone says its blocking the merge.

2024-03-23 03:24 UTC, ChillerDragon commented on src/engine/serverbrowser.h
> +		SORT_VERSION,
Indeed that is a left over of the iteration I did that showed versions in the master. Heinrich did not like it and i forgot to clean it up. Good catch thanks.

2024-03-23 03:29 UTC, ChillerDragon commented on src/engine/shared/translation_context.h
> +	int m_LocalClientId[NUM_DUMMIES];
Fixed thanks.

2024-03-23 03:32 UTC, ChillerDragon commented on src/game/client/gameclient.h
> +		int m_SkinPartIds[NUM_SKINPARTS];
In fact it was unused. I removed it. Fyi @Kaffeine you added that. Not sure what your plan was here. Did you forget to use it for something?

2024-03-23 03:37 UTC, ChillerDragon commented on src/game/client/render.h
> +
Good catch. Done.

```diff
diff --git a/src/game/client/render.h b/src/game/client/render.h
index 080df6d65..06ae41326 100644
--- a/src/game/client/render.h
+++ b/src/game/client/render.h
@@ -48,6 +48,11 @@ public:
                m_GotAirJump = true;
                m_TeeRenderFlags = 0;
                m_FeetFlipped = false;
+
+               // 0.7
+               for(auto &Texture : m_aTextures)
+                       Texture = IGraphics::CTextureHandle();
+               m_BotTexture = IGraphics::CTextureHandle();
        }
 
        CSkin::SSkinTextures m_OriginalRenderSkin;
```

2024-03-23 03:39 UTC, ChillerDragon commented on src/game/client/render.cpp
> +				float cs = 1.0f; // color scale
:white_check_mark: 

Also added some line breaks. Because it became so long.

2024-03-23 03:39 UTC, ChillerDragon commented on src/game/client/render.cpp
> +					SelectSprite7(client_data7::SPRITE_TEE_BOT_BACKGROUND, 0, 0, 0);
@heinrich5991 does not like default values.

2024-03-23 03:42 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +		Msg.AddString(Config()->m_Password, 128);
The 128 is from here

https://github.com/teeworlds/teeworlds/blob/a1911c8f7d8458fb4076ef8e7651e8ef5e91ab3e/src/engine/client/client.cpp#L345

2024-03-23 03:42 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +		Msg7.AddString(pPassword, 32);
The 32 is from here

https://github.com/teeworlds/teeworlds/blob/a1911c8f7d8458fb4076ef8e7651e8ef5e91ab3e/src/engine/client/client.cpp#L369

2024-03-23 03:51 UTC, ChillerDragon commented on src/engine/shared/snapshot.cpp
> +void CSnapshot::InvalidateItem(int Index)
I am not sure if I fully understand what you mean. It also has been a few months since I added that.

But if I remember correctly I added it to stay close to the teeworlds code.

What do you mean by "discard" and "propagating"? You mean drop the item on receive and never include it into the snap? Or validate later wherever the snap item is consumed?

> we don't handle the items with invalid index anywhere.

I did test it. I modified the server to send for example direction out of bounds and the client would drop that snap item correctly.

https://github.com/ddnet/ddnet/blob/96889c8d41d45a2ebec1350074d696aead59eb86/datasrc/seven/network.py#L152


The current system works and I tested it. It is close to upstream. It uses the validations generated by python correctly. That all sounds good to me. I do not understand your concerns with the current approach could you elaborate in more detail please :)

2024-03-23 03:52 UTC, ChillerDragon commented on src/engine/shared/protocolglue.h
> +#endif
I assume you wanted this

```diff
diff --git a/src/engine/shared/protocolglue.h b/src/engine/shared/protocolglue.h
index 9205be92b..8fa2f13dd 100644
--- a/src/engine/shared/protocolglue.h
+++ b/src/engine/shared/protocolglue.h
@@ -6,4 +6,4 @@ int PlayerFlags_SixToSeven(int Flags);
 void PickupType_SevenToSix(int Type7, int &Type6, int &SubType6);
 int PickupType_SixToSeven(int Type6, int SubType6);
 
-#endif
\ No newline at end of file
+#endif
```

2024-03-23 03:52 UTC, ChillerDragon commented on src/engine/shared/protocolglue.h
> +#endif
Should probably be added to ./scripts/fix_style.py

2024-03-23 04:13 UTC, ChillerDragon commented
> > We could show it only in menus in game if the current connection is 0.7 and then hide the 0.6 one.
> 
> I like this idea!

Done.

```diff
diff --git a/src/game/client/components/menus.h b/src/game/client/components/menus.h
index bcfadaea9..b64e0a526 100644
--- a/src/game/client/components/menus.h
+++ b/src/game/client/components/menus.h
@@ -671,7 +671,6 @@ public:
                SETTINGS_GENERAL,
                SETTINGS_PLAYER,
                SETTINGS_TEE,
-               SETTINGS_TEE7,
                SETTINGS_APPEARANCE,
                SETTINGS_CONTROLS,
                SETTINGS_GRAPHICS,
diff --git a/src/game/client/components/menus_settings.cpp b/src/game/client/components/menus_settings.cpp
index 827ae1b6e..d0e365acf 100644
--- a/src/game/client/components/menus_settings.cpp
+++ b/src/game/client/components/menus_settings.cpp
@@ -2036,8 +2036,7 @@ void CMenus::RenderSettings(CUIRect MainView)
                Localize("Language"),
                Localize("General"),
                Localize("Player"),
-               "Tee",
-               "Tee 0.7",
+               Client()->IsSixup() ? "Tee 0.7" : "Tee",
                Localize("Appearance"),
                Localize("Controls"),
                Localize("Graphics"),
@@ -2075,12 +2074,10 @@ void CMenus::RenderSettings(CUIRect MainView)
        else if(g_Config.m_UiSettingsPage == SETTINGS_TEE)
        {
                m_pBackground->ChangePosition(CMenuBackground::POS_SETTINGS_TEE);
-               RenderSettingsTee(MainView);
-       }
-       else if(g_Config.m_UiSettingsPage == SETTINGS_TEE7)
-       {
-               m_pBackground->ChangePosition(CMenuBackground::POS_SETTINGS_TEE);
-               RenderSettingsTee7(MainView);
+               if(Client()->IsSixup())
+                       RenderSettingsTee7(MainView);
+               else
+                       RenderSettingsTee(MainView);
        }
        else if(g_Config.m_UiSettingsPage == SETTINGS_APPEARANCE)
        {
```

![image](https://github.com/ddnet/ddnet/assets/20344300/f8a864fe-4999-4b8d-b473-67da931b31a8)

![image](https://github.com/ddnet/ddnet/assets/20344300/13db9e71-b408-499a-9bd1-320e53c68a12)

Ignore the bugged colors kaffeine fixed that in the next commit.

![image](https://github.com/ddnet/ddnet/assets/20344300/ce6bf288-f774-4e9d-96db-1a8c604b77c2)

2024-03-23 06:25 UTC, ChillerDragon commented on src/game/client/render.cpp
> +		for(int f = 0; f < 2; f++)
Yea Filling sounds about right. Fixed.

2024-03-23 06:29 UTC, ChillerDragon commented on src/game/client/gameclient.cpp
> +void CGameClient::SendReadyChange7()
I disagree. The ready change is a 0.7 only feature. The only 0.6 thing that is handled there is the error message that it does not work in 0.6. If the ready change is added to ddnet then the function can be renamed.

2024-03-23 06:33 UTC, ChillerDragon commented on src/game/client/gameclient.cpp
> +
Oh yea nice one. Fixed.

The stuff above I would consider out of scope for this pr. It can be fixed on the master branch. I am not carrying that git conflict surface around.

2024-03-23 06:37 UTC, ChillerDragon commented on src/game/client/gameclient.cpp
> +		if(!Client()->IsSixup())
This is a 0.6 error message. The 0.7 equivalent uses the 0.7 obj handler and is printed on translation.

https://github.com/ChillerDragon/ddnet/blob/23131d3f9a687191110e09b1e405e709ef4cacf5/src/engine/client/sixup/translate_game.cpp#L133

2024-03-23 06:42 UTC, ChillerDragon commented on src/game/client/gameclient.cpp
> +	}
Done.

2024-03-23 06:59 UTC, ChillerDragon commented on src/base/system.cpp
> +	if(!str && (str = str_startswith(string, "tw-0.7+udp://")))
I am ready to fight you on this one. Either we add ``grep -rE 'if\([^(]*\([^)"]+ = .*\)' src/`` to the github CI and make it an official unbreakable rule. And we also remove all those occurrences:

```
$ grep -rE 'if\([^(]*\([^)"]+ = .*\)' src/
src/game/client/components/console.cpp: if((m_RemoteConsole.m_UsernameReq = UsernameReq))
src/game/client/components/menu_background.cpp: if((pSuffix = str_endswith(aFullName, "_day")))
src/game/client/components/menu_background.cpp: else if((pSuffix = str_endswith(aFullName, "_night")))
src/game/client/components/statboard.cpp:                       if((p = str_find(pMsg->m_pMessage, pLookFor)))
src/game/client/prediction/gameworld.cpp:               if((pChar = (CCharacter *)GetEntity(ObjId, ENTTYPE_CHARACTER)))
src/game/server/gamecontroller.cpp:                     if((pChr = pPlayer2->GetCharacter()) && pChr->m_DDRaceState == DDRACE_STARTED)
src/game/server/gamecontroller.cpp:             else if((pChr = pPlayer->GetCharacter()) && pChr->m_DDRaceState == DDRACE_STARTED)
src/base/system.cpp:    if(!str && (str = str_startswith(string, "tw-0.7+udp://")))
src/engine/client/updater.cpp:                          if((pTemp = json_object_get(pCurrent, "download"))->type == json_array)
src/engine/client/updater.cpp:                          if((pTemp = json_object_get(pCurrent, "remove"))->type == json_array)
src/engine/server/server.cpp:   if(m_aClients[ClientId].m_Sixup && (Msg = MsgFromSixup(Msg, Sys)) < 0)
src/engine/server/server.cpp:                           if(m_AuthManager.CheckKey((KeySlot = m_AuthManager.DefaultKey(AUTHED_ADMIN)), pPw))
src/engine/server/server.cpp:                           else if(m_AuthManager.CheckKey((KeySlot = m_AuthManager.DefaultKey(AUTHED_MOD)), pPw))
src/engine/server/server.cpp:                           else if(m_AuthManager.CheckKey((KeySlot = m_AuthManager.DefaultKey(AUTHED_HELPER)), pPw))
```

Or we say that assignments in if statements should be avoided but there are exceptions when the code becomes easier to read and cleaner. And then I would argue that this is a perfect case where assignments in if statements should be used.

It aligns so nice with the other assignment.

![image](https://github.com/ddnet/ddnet/assets/20344300/5661a536-009e-43e8-b111-076fbac28a0f)


The alternative would be doing two str_startswith calls which is a waste of performance. And also more complex to read.

![image](https://github.com/ddnet/ddnet/assets/20344300/0fc75323-7cbb-4bd2-8da6-85ea510544de)

The other alternative has one more if branch and is harder to read for me. It breaks the alignment of 0.6 and 0.7. It is less obvious that ``if(str)`` means 0.7.

![image](https://github.com/ddnet/ddnet/assets/20344300/ab2b14bf-633e-4dcc-a061-8f3f90f17989)

2024-03-23 07:18 UTC, ChillerDragon commented on src/base/system.cpp
> +	if(!str && (str = str_startswith(string, "tw-0.7+udp://")))
I opened an issue to discuss assignments in if statements.

https://github.com/ddnet/ddnet/issues/8142

2024-03-23 07:26 UTC, ChillerDragon commented on src/base/types.h
> +	NETTYPE_TW7 = 16,
Adding TW7 to base was requested by @heinrich5991 [here](https://github.com/ddnet/ddnet/pull/5949#pullrequestreview-1148360008).

I do not know what NETTYPE_MASK is. It is a unused variable. But I added it now :shrug: 

```diff
diff --git a/src/base/types.h b/src/base/types.h
index 2c0d41477..b05067342 100644
--- a/src/base/types.h
+++ b/src/base/types.h
@@ -48,7 +48,7 @@ enum
        NETTYPE_TW7 = 16,
 
        NETTYPE_ALL = NETTYPE_IPV4 | NETTYPE_IPV6 | NETTYPE_WEBSOCKET_IPV4,
-       NETTYPE_MASK = NETTYPE_ALL | NETTYPE_LINK_BROADCAST,
+       NETTYPE_MASK = NETTYPE_ALL | NETTYPE_LINK_BROADCAST | NETTYPE_TW7,
 };
 
 /**
```

2024-03-23 07:27 UTC, ChillerDragon commented on src/base/types.h
> +	NETTYPE_TW7 = 16,
Not sure what comment would fit there. Any chance you guys could formulate that? @heinrich5991 @Robyt3

2024-03-23 07:32 UTC, ChillerDragon commented on src/game/client/components/menus.h
> +
This was probably a hack by me to avoid doing the alphabet in my head or running ./scripts/fix_style.sh :sweat_smile: 

I merged them with the other group now. That will make rebasing master more annoying but I hoping for a merge soon :crossed_fingers:

2024-03-23 07:37 UTC, ChillerDragon commented on src/game/client/components/menus.cpp
> +	m_RefreshSkinSelector = true;
Also less lines of code changed. Less git conflict surface. Love it. :white_check_mark:

2024-03-23 07:41 UTC, ChillerDragon commented on src/engine/shared/translation_context.h
> +	struct CServerSettings
Did we ban structs?

2024-03-23 08:43 UTC, ChillerDragon commented on src/engine/shared/translation_context.h
> +			str_copy(m_aSkinName, "default", sizeof(m_aSkinName));
I assume that "name" and "clan" were placeholders during development. The skin name "default" is actually used by the protocol but that should be set somewhere else I guess so I set all 3 to an empty string.

Found a few matches with ``git --no-pager show | grep  'str_copy.*sizeof'``

2024-03-23 09:11 UTC, ChillerDragon commented
Okay I have looked at all feedbacks unless I oversaw something. The only thing that is still pending from my side is https://github.com/ChillerDragon/ddnet/issues/5 which I did not find the time for yet.

@Robyt3 all other conversations I expect you to either respond with a comment or by clicking resolve on the conversation.

Parts of the diff with all the fixes can be seen here

<details>

```diff
diff --git a/src/base/types.h b/src/base/types.h
index 2c0d41477..b05067342 100644
--- a/src/base/types.h
+++ b/src/base/types.h
@@ -48,7 +48,7 @@ enum
 	NETTYPE_TW7 = 16,
 
 	NETTYPE_ALL = NETTYPE_IPV4 | NETTYPE_IPV6 | NETTYPE_WEBSOCKET_IPV4,
-	NETTYPE_MASK = NETTYPE_ALL | NETTYPE_LINK_BROADCAST,
+	NETTYPE_MASK = NETTYPE_ALL | NETTYPE_LINK_BROADCAST | NETTYPE_TW7,
 };
 
 /**
diff --git a/src/engine/client.h b/src/engine/client.h
index d9f6e124c..59913975f 100644
--- a/src/engine/client.h
+++ b/src/engine/client.h
@@ -262,7 +262,7 @@ public:
 	int64_t ReconnectTime() const { return m_ReconnectTime; }
 	void SetReconnectTime(int64_t ReconnectTime) { m_ReconnectTime = ReconnectTime; }
 
-	virtual bool IsSixup() = 0;
+	virtual bool IsSixup() const = 0;
 
 	virtual int GetCurrentRaceTime() = 0;
 
diff --git a/src/engine/client/client.cpp b/src/engine/client/client.cpp
index a5c41e05d..5f56895d6 100644
--- a/src/engine/client/client.cpp
+++ b/src/engine/client/client.cpp
@@ -3761,7 +3761,7 @@ const char *CClient::DemoPlayer_Play(const char *pFilename, int StorageType)
 		return m_DemoPlayer.ErrorMessage();
 
 	m_Sixup = str_startswith(m_DemoPlayer.Info()->m_Header.m_aNetversion, "0.7");
-	m_DemoPlayer.m_Sixup = m_Sixup;
+	m_DemoPlayer.SetSixup(m_Sixup);
 
 	// load map
 	const CMapInfo *pMapInfo = m_DemoPlayer.GetMapInfo();
diff --git a/src/engine/client/client.h b/src/engine/client/client.h
index 459335130..c98eb274a 100644
--- a/src/engine/client/client.h
+++ b/src/engine/client/client.h
@@ -360,7 +360,7 @@ public:
 	void FinishDDNetInfo();
 	void LoadDDNetInfo();
 
-	bool IsSixup() override { return m_Sixup; };
+	bool IsSixup() const override { return m_Sixup; }
 
 	const NETADDR &ServerAddress() const override { return *m_aNetClient[CONN_MAIN].ServerAddress(); }
 	int ConnectNetTypes() const override;
diff --git a/src/engine/client/sixup/translate_game.cpp b/src/engine/client/sixup/translate_game.cpp
index f7e004f4a..337cf77fe 100644
--- a/src/engine/client/sixup/translate_game.cpp
+++ b/src/engine/client/sixup/translate_game.cpp
@@ -435,8 +435,8 @@ void *CGameClient::TranslateGameMsg(int *pMsgId, CUnpacker *pUnpacker, int Conn)
 		CTranslationContext::CClientData &Client = m_pClient->m_TranslationContext.m_aClients[pMsg7->m_ClientId];
 		Client.m_Active = true;
 		Client.m_Team = pMsg7->m_Team;
-		str_copy(Client.m_aName, pMsg7->m_pName, sizeof(Client.m_aName));
-		str_copy(Client.m_aClan, pMsg7->m_pClan, sizeof(Client.m_aClan));
+		str_copy(Client.m_aName, pMsg7->m_pName);
+		str_copy(Client.m_aClan, pMsg7->m_pClan);
 		Client.m_Country = pMsg7->m_Country;
 		CClientData *pClient = &m_aClients[pMsg7->m_ClientId];
 		for(int p = 0; p < NUM_SKINPARTS; p++)
diff --git a/src/engine/client/sixup/translate_system.cpp b/src/engine/client/sixup/translate_system.cpp
index b5018bfbe..869c0da5f 100644
--- a/src/engine/client/sixup/translate_system.cpp
+++ b/src/engine/client/sixup/translate_system.cpp
@@ -31,12 +31,12 @@ int CClient::TranslateSysMsg(int *pMsgId, bool System, CUnpacker *pUnpacker, CPa
 		// this is a 0.7 only message and not handled in 0.6 code
 		*pMsgId = -1;
 		net_addr_str(&pPacket->m_Address, m_CurrentServerInfo.m_aAddress, sizeof(m_CurrentServerInfo.m_aAddress), true);
-		str_copy(m_CurrentServerInfo.m_aVersion, pUnpacker->GetString(CUnpacker::SANITIZE_CC | CUnpacker::SKIP_START_WHITESPACES), sizeof(m_CurrentServerInfo.m_aVersion));
-		str_copy(m_CurrentServerInfo.m_aName, pUnpacker->GetString(CUnpacker::SANITIZE_CC | CUnpacker::SKIP_START_WHITESPACES), sizeof(m_CurrentServerInfo.m_aName));
+		str_copy(m_CurrentServerInfo.m_aVersion, pUnpacker->GetString(CUnpacker::SANITIZE_CC | CUnpacker::SKIP_START_WHITESPACES));
+		str_copy(m_CurrentServerInfo.m_aName, pUnpacker->GetString(CUnpacker::SANITIZE_CC | CUnpacker::SKIP_START_WHITESPACES));
 		str_clean_whitespaces(m_CurrentServerInfo.m_aName);
 		pUnpacker->GetString(CUnpacker::SANITIZE_CC | CUnpacker::SKIP_START_WHITESPACES); // Hostname
-		str_copy(m_CurrentServerInfo.m_aMap, pUnpacker->GetString(CUnpacker::SANITIZE_CC | CUnpacker::SKIP_START_WHITESPACES), sizeof(m_CurrentServerInfo.m_aMap));
-		str_copy(m_CurrentServerInfo.m_aGameType, pUnpacker->GetString(CUnpacker::SANITIZE_CC | CUnpacker::SKIP_START_WHITESPACES), sizeof(m_CurrentServerInfo.m_aGameType));
+		str_copy(m_CurrentServerInfo.m_aMap, pUnpacker->GetString(CUnpacker::SANITIZE_CC | CUnpacker::SKIP_START_WHITESPACES));
+		str_copy(m_CurrentServerInfo.m_aGameType, pUnpacker->GetString(CUnpacker::SANITIZE_CC | CUnpacker::SKIP_START_WHITESPACES));
 		int Flags = pUnpacker->GetInt();
 		if(Flags & SERVER_FLAG_PASSWORD)
 			m_CurrentServerInfo.m_Flags |= SERVER_FLAG_PASSWORD;
diff --git a/src/engine/serverbrowser.h b/src/engine/serverbrowser.h
index a0fa77993..1cb4a0899 100644
--- a/src/engine/serverbrowser.h
+++ b/src/engine/serverbrowser.h
@@ -122,7 +122,6 @@ public:
 	static int EstimateLatency(int Loc1, int Loc2);
 	static bool ParseLocation(int *pResult, const char *pString);
 	void InfoToString(char *pBuffer, int BufferSize) const;
-	const char *ShortVersion() const { return str_startswith(m_aVersion, "0.7") ? "0.7" : "0.6"; }
 };
 
 class CCommunityCountryServer
diff --git a/src/engine/shared/config_variables.h b/src/engine/shared/config_variables.h
index ac494e5e8..41a87e228 100644
--- a/src/engine/shared/config_variables.h
+++ b/src/engine/shared/config_variables.h
@@ -141,19 +141,19 @@ MACRO_CONFIG_COL(ClPlayer7ColorMarking, player7_color_marking, 0xFF0000FF, CFGFL
 MACRO_CONFIG_COL(ClPlayer7ColorDecoration, player7_color_decoration, 0x1B6F74, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLLIGHT | CFGFLAG_INSENSITIVE, "Player decoration color")
 MACRO_CONFIG_COL(ClPlayer7ColorHands, player7_color_hands, 0x1B759E, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLLIGHT | CFGFLAG_INSENSITIVE, "Player hands color")
 MACRO_CONFIG_COL(ClPlayer7ColorEyes, player7_color_eyes, 0x0000FF, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLLIGHT | CFGFLAG_INSENSITIVE, "Player eyes color")
-MACRO_CONFIG_INT(ClPlayer7UseCustomColorBody, player7_use_custom_color_body, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggles usage of custom colors for body")
-MACRO_CONFIG_INT(ClPlayer7UseCustomColorMarking, player7_use_custom_color_marking, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggles usage of custom colors for marking")
-MACRO_CONFIG_INT(ClPlayer7UseCustomColorDecoration, player7_use_custom_color_decoration, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggles usage of custom colors for decoration")
-MACRO_CONFIG_INT(ClPlayer7UseCustomColorHands, player7_use_custom_color_hands, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggles usage of custom colors for hands")
-MACRO_CONFIG_INT(ClPlayer7UseCustomColorFeet, player7_use_custom_color_feet, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggles usage of custom colors for feet")
-MACRO_CONFIG_INT(ClPlayer7UseCustomColorEyes, player7_use_custom_color_eyes, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggles usage of custom colors for eyes")
-MACRO_CONFIG_STR(ClPlayer7Skin, player7_skin, protocol7::MAX_SKIN_ARRAY_SIZE, "default", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player skin")
-MACRO_CONFIG_STR(ClPlayer7SkinBody, player7_skin_body, protocol7::MAX_SKIN_ARRAY_SIZE, "standard", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player skin body")
-MACRO_CONFIG_STR(ClPlayer7SkinMarking, player7_skin_marking, protocol7::MAX_SKIN_ARRAY_SIZE, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player skin marking")
-MACRO_CONFIG_STR(ClPlayer7SkinDecoration, player7_skin_decoration, protocol7::MAX_SKIN_ARRAY_SIZE, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player skin decoration")
-MAC [...]

2024-03-23 09:50 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +		if(!Client()->IsSixup())
I see. Could you add that as a comment in the code so it's clear for the next reader?

2024-03-23 09:54 UTC, Robyt3 commented on src/base/types.h
> +	NETTYPE_TW7 = 16,
Suggestion:

```cpp
/**
 * 0.7 address. This is a flag in NETADDR to avoid introducing a parameter to every networking function
 * to differenciate between 0.6 and 0.7 connections.
 */
```

2024-03-23 09:57 UTC, Robyt3 commented on src/engine/client/client.cpp
> +		Msg.AddString(Config()->m_Password, 128);
The password length on the 0.7 server side seems to be limited to 32 though. I think the limit on the client-side is unnecessary.

2024-03-23 09:59 UTC, Robyt3 commented on src/engine/client/client.cpp
> +		Msg7.AddString(pPassword, 32);
I think always sending the entire string makes more sense instead of truncating it. Could be removed for future proofing (i.e. if 0.7 would ever support longer passwords).

2024-03-23 10:02 UTC, Robyt3 commented on src/engine/shared/snapshot.cpp
> +void CSnapshot::InvalidateItem(int Index)
> What do you mean by "discard" and "propagating"? You mean drop the item on receive and never include it into the snap? Or validate later wherever the snap item is consumed?

If possible, I want the 0.7 snapshots validation to mirror the 0.6 validation (see also https://github.com/ddnet/ddnet/pull/5918#issuecomment-1272346678), which means discarding the invalid items as soon as possible.

2024-03-23 10:19 UTC, Robyt3 commented on src/game/client/render.cpp
> +					SelectSprite7(client_data7::SPRITE_TEE_BOT_BACKGROUND, 0, 0, 0);
We'll leave this to another discussion. I don't like default values in all cases either, but in some cases (especially the UI functions) they make the code easier to read and write IMO. Although in many cases I switched to parameter objects (and with C++20 I would use designated initializers) because they allow only specifying the required arguments.

2024-03-23 10:43 UTC, Robyt3 requested changes
Thanks for your work @ChillerDragon, sorry if I sometimes nitpick a lot.

Some more small comments related to skins and the skin menu below, I think that's enough to get this into a mergeable state. Bringing the 0.7 skin menu more in line with our UI can be a future issue. For example, using tabs to switch between player/dummy settings, and removing some of the dark backgrounds.

2024-03-23 10:43 UTC, Robyt3 commented on src/game/client/components/skins7.h
> +// todo: fix duplicate skins (different paths)
Is this TODO from upstream? I think our storage should fix the issue of duplicate files in different storage locations.

2024-03-23 10:43 UTC, Robyt3 commented on src/game/client/components/menus_settings7.cpp
> +		// CListboxItem Item = UiDoListboxNextItem(&s_paSkinList[i], OldSelected == i);
Remove dead code

2024-03-23 10:43 UTC, Robyt3 commented on src/game/client/components/menus_settings7.cpp
> +			// Ui()->DoLabelSelected(&Label, s->m_aName, Item.m_Selected, 10.0f, TEXTALIGN_CENTER);
Use `DoLabel`, I don't think we need/want the `DoLabelSelected` that inverts the color for selected items.

2024-03-23 10:43 UTC, Robyt3 commented on src/game/client/components/menus_settings7.cpp
> +		mem_copy(Config()->m_ClPlayer7Skin, m_pSelectedSkin->m_aName, sizeof(Config()->m_ClPlayer7Skin));
Use `str_copy` so we don't end up with truncated UTF-8 (also below)

2024-03-23 10:43 UTC, Robyt3 commented on src/game/client/components/menus_settings7.cpp
> +			// Ui()->DoLabelSelected(&Label, s->m_aName, Item.m_Selected, 10.0f, TEXTALIGN_CENTER);
`DoLabel`

2024-03-23 10:43 UTC, Robyt3 commented on src/game/client/components/menus_settings7.cpp
> +	s_ListBox.DoHeader(&MainView, Localize("Skins")); // TODO: Ui()->GetListHeaderHeight()
Remove `// TODO: Ui()->GetListHeaderHeight()`, I don't think we need it.

2024-03-23 10:43 UTC, Robyt3 commented on src/game/client/components/menus_settings7.cpp
> +	static std::vector<const CSkins7::CSkin *> s_paSkinList;
`s_vpSkinList`

2024-03-23 10:43 UTC, Robyt3 commented on src/game/client/components/menus_settings7.cpp
> +	Ui()->DoLabel(&Label, Localize("Tee"), ButtonHeight * CUi::ms_FontmodHeight * 0.8f, TEXTALIGN_CENTER);
Use `TEXTALIGN_MC` instead of `TEXTALIGN_CENTER` (also below), so the text is centered vertically also.

2024-03-23 10:57 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +
See #8144.

2024-03-23 11:08 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +		static std::vector<const char *> s_vpGpuIdNames;
See #8145.

2024-03-24 05:54 UTC, ChillerDragon commented on src/game/client/gameclient.cpp
> +
The rebase to master caused m_SkinInfo.Reset() to be duplicated without git conflicts. I was kinda expecting that so I fixed it. But I am not aware of all commits on master I hope that this was the only logic bug that causes no build or git conflict errors. It has been years of rebasing this pr. Those things are also not obvious even if you check the entire diff of the pr. Nasty.

![image](https://github.com/ddnet/ddnet/assets/20344300/e2221e6d-a544-44e7-b229-702b1bbcc53d)

2024-03-24 05:56 UTC, ChillerDragon commented on src/game/client/gameclient.cpp
> +		if(!Client()->IsSixup())
```diff
diff --git a/src/game/client/gameclient.cpp b/src/game/client/gameclient.cpp
index c105708f0..e355375e8 100644
--- a/src/game/client/gameclient.cpp
+++ b/src/game/client/gameclient.cpp
@@ -849,6 +849,8 @@ void CGameClient::OnMessage(int MsgId, CUnpacker *pUnpacker, int Conn, bool Dumm
 
        if(!pRawMsg)
        {
+               // the 0.7 version of this error message is printed on translation
+               // in sixup/translate_game.cpp
                if(!Client()->IsSixup())
                {
                        char aBuf[256];
```

2024-03-24 05:58 UTC, ChillerDragon commented on src/base/types.h
> +	NETTYPE_TW7 = 16,
Thanks :heart:  copy pasted it straight above it.

```diff
diff --git a/src/base/types.h b/src/base/types.h
index b05067342..13abeb0e8 100644
--- a/src/base/types.h
+++ b/src/base/types.h
@@ -45,6 +45,10 @@ enum
        NETTYPE_IPV4 = 1,
        NETTYPE_IPV6 = 2,
        NETTYPE_WEBSOCKET_IPV4 = 8,
+       /**
+        * 0.7 address. This is a flag in NETADDR to avoid introducing a parameter to every networking function
+        * to differenciate between 0.6 and 0.7 connections.
+        */
        NETTYPE_TW7 = 16,
 
        NETTYPE_ALL = NETTYPE_IPV4 | NETTYPE_IPV6 | NETTYPE_WEBSOCKET_IPV4,
```

2024-03-24 05:59 UTC, ChillerDragon commented on src/game/client/components/menus_settings.cpp
> +		static std::vector<const char *> s_vpGpuIdNames;
Gone thanks.

2024-03-24 06:00 UTC, ChillerDragon commented
> Thanks for your work @ChillerDragon, sorry if I sometimes nitpick a lot.

Don't be sorry its good stuff (mostly hehe). And it is a big pr so that makes sense. The problem here is not the amount of nitpicks per code but the amount of code. Thats why I would have loved a partial merge.

2024-03-24 06:03 UTC, ChillerDragon commented on src/game/client/components/menus_settings7.cpp
> +	s_ListBox.DoHeader(&MainView, Localize("Skins")); // TODO: Ui()->GetListHeaderHeight()
We don't but I read this todo currently as: Don't make it ugly :D 
The scrolled tees currently fade off too early on the top. This should be fixed.

2024-03-24 06:06 UTC, ChillerDragon commented on src/game/client/components/skins7.h
> +// todo: fix duplicate skins (different paths)
Yep that is from upstream. And yep that is fixed. Removed the comment.

2024-03-24 06:17 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +		Msg7.AddString(pPassword, 32);
I like future proof but it might break login binds. Not too sure on that one. The password is compared with the config variable that also has a max size of 32 https://github.com/teeworlds/teeworlds/blob/a1911c8f7d8458fb4076ef8e7651e8ef5e91ab3e/src/engine/shared/config_variables.h#L94

Currently users can have a 512 long password set in both the client bind config and in the server side autoexec. It will be truncated to 32 on both ends and then match. If we extend the client side it might be annoying for users to debug why their authentication does not work. Using the same bind that worked for them in the vanilla client.

Its tricky but I don't like the trade off given the chances of how likely official teeworlds servers will have a 0.7.x not 0.8.x release with longer password support. Given the current upstream situation.

2024-03-24 06:19 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +		Msg.AddString(Config()->m_Password, 128);
Agree. Changed.

2024-03-24 06:25 UTC, ChillerDragon commented on src/game/client/components/menus_settings7.cpp
> +		mem_copy(Config()->m_ClPlayer7Skin, m_pSelectedSkin->m_aName, sizeof(Config()->m_ClPlayer7Skin));
I do not fully understand the consequences. Teeworlds 0.7 introduced a constant for that to cut it off.
```
mem_copy(CSkins7::ms_apSkinVariables[(int)m_Dummy][p], m_pSelectedSkin->m_apParts[p]->m_aName, protocol7::MAX_SKIN_ARRAY_SIZE);
```

This might display different skins in the ddnet client than in the teeworlds client. Should we favor correctness over compatibility here? I would prefer to not fix it in ddnet until it is fixed in teeworlds. To implement the protocol in the same way.

2024-03-24 06:28 UTC, ChillerDragon commented on src/game/client/components/menus_settings7.cpp
> +	Ui()->DoLabel(&Label, Localize("Tee"), ButtonHeight * CUi::ms_FontmodHeight * 0.8f, TEXTALIGN_CENTER);
Looks better indeed.

```diff
diff --git a/src/game/client/components/menus_settings7.cpp b/src/game/client/components/menus_settings7.cpp
index d695c1c34..d549255c4 100644
--- a/src/game/client/components/menus_settings7.cpp
+++ b/src/game/client/components/menus_settings7.cpp
@@ -80,7 +80,7 @@ void CMenus::RenderSettingsTee7(CUIRect MainView)
        Right.Draw(vec4(0.0f, 0.0f, 0.0f, 0.25f), 15, 5.0F);
 
        Left.HSplitTop(ButtonHeight, &Label, &Left);
-       Ui()->DoLabel(&Label, Localize("Tee"), ButtonHeight * CUi::ms_FontmodHeight * 0.8f, TEXTALIGN_CENTER);
+       Ui()->DoLabel(&Label, Localize("Tee"), ButtonHeight * CUi::ms_FontmodHeight * 0.8f, TEXTALIGN_MC);
 
        // Preview
        {
@@ -209,7 +209,7 @@ void CMenus::RenderSettingsTee7(CUIRect MainView)
        }
 
        Right.HSplitTop(ButtonHeight, &Label, &Right);
-       Ui()->DoLabel(&Label, Localize("Settings"), ButtonHeight * CUi::ms_FontmodHeight * 0.8f, TEXTALIGN_CENTER);
+       Ui()->DoLabel(&Label, Localize("Settings"), ButtonHeight * CUi::ms_FontmodHeight * 0.8f, TEXTALIGN_MC);
 
        // Settings
        {
```

2024-03-24 06:30 UTC, ChillerDragon commented on src/game/client/components/menus_settings7.cpp
> +	static std::vector<const CSkins7::CSkin *> s_paSkinList;
I ran ``perl -i -p -e's/\bs_paSkinList\b/s_vpSkinList/g' $(find . -name *.cpp -o -name '*.h')``

Hope nothing broke :crossed_fingers: 

```diff
diff --git a/src/game/client/components/menus_settings7.cpp b/src/game/client/components/menus_settings7.cpp
index d549255c4..196cb4af6 100644
--- a/src/game/client/components/menus_settings7.cpp
+++ b/src/game/client/components/menus_settings7.cpp
@@ -365,12 +365,12 @@ void CMenus::RenderSettingsTeeCustom7(CUIRect MainView)
 void CMenus::RenderSkinSelection7(CUIRect MainView)
 {
 	static float s_LastSelectionTime = -10.0f;
-	static std::vector<const CSkins7::CSkin *> s_paSkinList;
+	static std::vector<const CSkins7::CSkin *> s_vpSkinList;
 	static CListBox s_ListBox;
 	static int s_SkinCount = 0;
 	if(m_SkinListNeedsUpdate || m_pClient->m_Skins7.Num() != s_SkinCount)
 	{
-		s_paSkinList.clear();
+		s_vpSkinList.clear();
 		s_SkinCount = m_pClient->m_Skins7.Num();
 		for(int i = 0; i < s_SkinCount; ++i)
 		{
@@ -382,7 +382,7 @@ void CMenus::RenderSkinSelection7(CUIRect MainView)
 			// no special skins
 			if((s->m_Flags & CSkins7::SKINFLAG_SPECIAL) == 0)
 			{
-				s_paSkinList.emplace_back(s);
+				s_vpSkinList.emplace_back(s);
 			}
 		}
 		m_SkinListNeedsUpdate = false;
@@ -391,11 +391,11 @@ void CMenus::RenderSkinSelection7(CUIRect MainView)
 	m_pSelectedSkin = 0;
 	int OldSelected = -1;
 	s_ListBox.DoHeader(&MainView, Localize("Skins")); // TODO: Ui()->GetListHeaderHeight()
-	s_ListBox.DoStart(60.0f, s_paSkinList.size(), 10, 1, OldSelected);
+	s_ListBox.DoStart(60.0f, s_vpSkinList.size(), 10, 1, OldSelected);
 
-	for(int i = 0; i < (int)s_paSkinList.size(); ++i)
+	for(int i = 0; i < (int)s_vpSkinList.size(); ++i)
 	{
-		const CSkins7::CSkin *s = s_paSkinList[i];
+		const CSkins7::CSkin *s = s_vpSkinList[i];
 		if(s == 0)
 			continue;
 		if(!str_comp(s->m_aName, Config()->m_ClPlayer7Skin))
@@ -404,7 +404,7 @@ void CMenus::RenderSkinSelection7(CUIRect MainView)
 			OldSelected = i;
 		}
 
-		CListboxItem Item = s_ListBox.DoNextItem(&s_paSkinList[i], OldSelected == i);
+		CListboxItem Item = s_ListBox.DoNextItem(&s_vpSkinList[i], OldSelected == i);
 		if(Item.m_Visible)
 		{
 			CTeeRenderInfo Info;
@@ -445,7 +445,7 @@ void CMenus::RenderSkinSelection7(CUIRect MainView)
 	if(NewSelected != -1 && NewSelected != OldSelected)
 	{
 		s_LastSelectionTime = Client()->LocalTime();
-		m_pSelectedSkin = s_paSkinList[NewSelected];
+		m_pSelectedSkin = s_vpSkinList[NewSelected];
 		mem_copy(Config()->m_ClPlayer7Skin, m_pSelectedSkin->m_aName, sizeof(Config()->m_ClPlayer7Skin));
 		for(int p = 0; p < NUM_SKINPARTS; p++)
 		{
```

2024-03-24 09:56 UTC, Robyt3 commented on src/game/client/components/menus_settings7.cpp
> +	s_ListBox.DoHeader(&MainView, Localize("Skins")); // TODO: Ui()->GetListHeaderHeight()
We could probably remove the entire header for consistency with the 0.6 skin menu.

2024-03-24 10:09 UTC, Robyt3 commented on src/game/client/components/menus_settings7.cpp
> +		mem_copy(Config()->m_ClPlayer7Skin, m_pSelectedSkin->m_aName, sizeof(Config()->m_ClPlayer7Skin));
> I do not fully understand the consequences. Teeworlds 0.7 introduced a constant for that to cut it off.
> This might display different skins in the ddnet client than in the teeworlds client.

I mean you should still use the same size constant, but use `str_copy` instead of `mem_copy`. This means the bytes are only copied until the first null-character and truncated UTF-8 is fixed. This should work identically for all valid UTF-8 string with maximum length 96+1 bytes.

> Should we favor correctness over compatibility here?

I want to prevent UTF-8 from ever appearing in the client because it will cause crashes on Windows. I don't think it's a question of compatibility, because I find it unlikely that even Teeworlds would depend on bytes after the null-character being copied or on broken UTF-8 in skin names.

2024-03-25 11:31 UTC, ChillerDragon commented on src/game/client/components/menus_settings7.cpp
> +	s_ListBox.DoHeader(&MainView, Localize("Skins")); // TODO: Ui()->GetListHeaderHeight()
Yep that was the plan

2024-03-25 11:38 UTC, ChillerDragon commented on src/game/client/components/menus_settings7.cpp
> +		mem_copy(Config()->m_ClPlayer7Skin, m_pSelectedSkin->m_aName, sizeof(Config()->m_ClPlayer7Skin));
Ah sounds good. Fixed.

```diff
diff --git a/src/game/client/components/menus_settings7.cpp b/src/game/client/components/menus_settings7.cpp
index 196cb4af6..269a2f83e 100644
--- a/src/game/client/components/menus_settings7.cpp
+++ b/src/game/client/components/menus_settings7.cpp
@@ -446,10 +446,10 @@ void CMenus::RenderSkinSelection7(CUIRect MainView)
        {
                s_LastSelectionTime = Client()->LocalTime();
                m_pSelectedSkin = s_vpSkinList[NewSelected];
-               mem_copy(Config()->m_ClPlayer7Skin, m_pSelectedSkin->m_aName, sizeof(Config()->m_ClPlayer7Skin));
+               str_copy(Config()->m_ClPlayer7Skin, m_pSelectedSkin->m_aName);
                for(int p = 0; p < NUM_SKINPARTS; p++)
                {
-                       mem_copy(CSkins7::ms_apSkinVariables[(int)m_Dummy][p], m_pSelectedSkin->m_apParts[p]->m_aName, protocol7::MAX_SKIN_ARRAY_SIZE);
+                       str_copy(CSkins7::ms_apSkinVariables[(int)m_Dummy][p], m_pSelectedSkin->m_apParts[p]->m_aName, protocol7::MAX_SKIN_ARRAY_SIZE);
                        *CSkins7::ms_apUCCVariables[(int)m_Dummy][p] = m_pSelectedSkin->m_aUseCustomColors[p];
                        *CSkins7::ms_apColorVariables[(int)m_Dummy][p] = m_pSelectedSkin->m_aPartColors[p];
                }
@@ -547,7 +547,7 @@ void CMenus::RenderSkinPartSelection7(CUIRect MainView)
        if(NewSelected != -1 && NewSelected != OldSelected)
        {
                const CSkins7::CSkinPart *s = s_paList[m_TeePartSelected][NewSelected];
-               mem_copy(CSkins7::ms_apSkinVariables[(int)m_Dummy][m_TeePartSelected], s->m_aName, protocol7::MAX_SKIN_ARRAY_SIZE);
+               str_copy(CSkins7::ms_apSkinVariables[(int)m_Dummy][m_TeePartSelected], s->m_aName, protocol7::MAX_SKIN_ARRAY_SIZE);
                Config()->m_ClPlayer7Skin[0] = 0;
                m_SkinModified = true;
        }
```

2024-03-26 18:54 UTC, Robyt3 requested changes

2024-03-26 18:54 UTC, Robyt3 commented on src/engine/client/client.cpp
> +	m_Sixup = false;
This should be in `DisconnectWithReason`. The `Disconnect` function is only called on user interactions, not for example when you get disconnected by the server or demo playback fails, so this doesn't clear the variable in all cases. Seems like if you play a 0.7 demo and playback fails, the client would now be stuck in sixup mode until you connect to another server, so you'll see the wrong tee settings.

2024-03-26 18:54 UTC, Robyt3 commented on src/engine/client/client.cpp
> +		else if(IsSixup() && Conn != CONN_MAIN && (pPacket->m_Flags & NET_CHUNKFLAG_VITAL) != 0 && Msg == NETMSG_MAP_CHANGE)
Use `Conn == CONN_DUMMY`, this should probably not include `CONN_CONTACT`.

2024-03-26 18:54 UTC, Robyt3 commented on src/engine/client/sixup/translate_game.cpp
Not sure about the location of this file. It defines functions in `CGameClient` and includes `src/game`, so I think it shouldn't be in `src/engine`.

2024-03-28 01:13 UTC, ChillerDragon commented on src/engine/client/sixup/translate_game.cpp
If I remember correctly it depends on the translation context which is tied into the snap. I think it was tricky to compile without changing where what is linked. But no hard feelings on the file location. Tell me where it should be I can give it another try.

2024-03-28 10:53 UTC, ChillerDragon commented on src/engine/shared/snapshot.cpp
> +void CSnapshot::InvalidateItem(int Index)
The snapshot translation currently passes all 0.7 snap items twice. On the first pass it marks them as invalid. The only alternative I see is having the invalidation twice at the beginning of both loops. The invalid items never reach the 0.6 code. Only valid items will be added to the translated snap. I do not like having the validity check twice. Especially because I do not understand what is bad about invalidation. It seems to work right now. It seems to work for teeworlds two. Is it because it is different than ddnet does it? We can rename InvalidateItem to InvalidateItem7 would that help?

So far it seems to me like this requested change might break working and tested code, costs time to implement and causes more complex code in the end while having no benefit.

2024-03-28 11:12 UTC, ChillerDragon commented on src/game/client/render.h
> +	ColorRGBA m_BotColor;
What do you want me to do? I assumed @heinrich5991 wanted something like this based on his feedback [here](https://github.com/ddnet/ddnet/pull/5660#issuecomment-1194054474). If not validity, based on what should be decided which skin to use?

2024-03-28 11:18 UTC, jxsl13 commented
:rocket:

2024-03-28 17:28 UTC, Robyt3 requested changes

2024-03-28 17:28 UTC, Robyt3 commented on src/engine/client/sixup/translate_game.cpp
I'd move `translate_game.cpp` to `src/game/client/sixup_translate_game.cpp`
and move `translate_system.cpp` to `src/engine/client/sixup_translate_system.cpp`, so I'd remove the folder and add `sixup` somewhere in the file names. Could be in the beginning, middle or end though, I don't have any strong preference.

2024-03-28 17:28 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +	if(MsgId == NETMSGTYPE_SV_TUNEPARAMS || (Client()->IsSixup() && MsgId == protocol7::NETMSGTYPE_SV_TUNEPARAMS))
I think this should be `(!Client()->IsSixup() && MsgId == NETMSGTYPE_SV_TUNEPARAMS) || (Client()->IsSixup() && MsgId == protocol7::NETMSGTYPE_SV_TUNEPARAMS)` for correctness. Would otherwise handle whatever internal ID 0.6 `NETMSGTYPE_SV_TUNEPARAMS` is also as a sixup message. Maybe doesn't matter in practice because both IDs are the same though.

2024-03-28 17:28 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +				aColor = color_cast<ColorRGBA>(ColorHSLA(aTeamColors[m_Team]));
`aColor` -> `Color`

2024-03-28 17:28 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +				aColor = color_cast<ColorRGBA>(ColorHSLA(12829350));
`aColor` -> `Color`

2024-03-28 17:28 UTC, Robyt3 commented on src/engine/shared/snapshot.cpp
> +void CSnapshot::InvalidateItem(int Index)
Seems fine for now if it works and is only used for 0.7 snap items.

2024-03-28 17:31 UTC, Robyt3 commented on src/game/client/render.h
> +	ColorRGBA m_BotColor;
I see. Then we'll try to go with one `CTeeRenderInfo` class and two functions `Valid` and `Valid7`. I think also the 0.7 member variables should either have a common prefix or be inside a nested class, to make it clearer which variant of the render info is being used.

2024-03-28 23:46 UTC, ChillerDragon commented on src/game/client/gameclient.cpp
> +	if(MsgId == NETMSGTYPE_SV_TUNEPARAMS || (Client()->IsSixup() && MsgId == protocol7::NETMSGTYPE_SV_TUNEPARAMS))
Both have id 6 do you still want me to waste clock cycles on readability?

https://chillerdragon.github.io/teeworlds-protocol/06/game_messages.html#NETMSGTYPE_SV_TUNEPARAMS
https://chillerdragon.github.io/teeworlds-protocol/07/game_messages.html#NETMSGTYPE_SV_TUNEPARAMS

For me your suggestion reads more complicated.

2024-03-29 00:14 UTC, ChillerDragon commented on src/game/client/render.h
> +	ColorRGBA m_BotColor;
Done. Used a nested class.

2024-03-29 01:32 UTC, ChillerDragon commented on src/engine/client/sixup/translate_game.cpp
Compilation seemed fine. I think my thought process back then was that the system part for sure belonged into the engine and the game part belonged to the system part. So to keep it all in one place I decided on engine instead of game. Also conceptually translating the protocol is not gameplay related. I just had to do some game hacks because not every message could be translated without side effects.

I will move it to game if you are still fully sure that the files should go exactly there and never move again. And if you say it is blocking the merge. Otherwise I would like to avoid manually applying all changes kaffeine made into the moved file during rebase.

As of right now it seems like a lot of effort to move files from a to b with the final result not being better than the original.

2024-03-29 02:44 UTC, ChillerDragon commented
@heinrich5991 is demos not working yet a problem for you? With robsti saying not EVERY todo has to be solved the last big blocker I am aware of got lifted. I am under the impression the merge is close or am I missing something fundamental? I am aware that jopsti and ryo do not like the change. I talked with jopsti in dms he did not seem too upset. I am willing to maintain this.

2024-03-29 14:11 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +	if(MsgId == NETMSGTYPE_SV_TUNEPARAMS || (Client()->IsSixup() && MsgId == protocol7::NETMSGTYPE_SV_TUNEPARAMS))
Then I would suggest only comparing `MsgId == NETMSGTYPE_SV_TUNEPARAMS` and adding a `static_assert` that ensures that both IDs must be identical at compile-time.

2024-03-29 14:31 UTC, Robyt3 commented on src/engine/client/sixup/translate_game.cpp
It makes sense to split the translation between engine/system and game like you already did, but the game file should be in the game folder, because it defines functions directly in the `CGameClient` class and should therefore only have to be compiled when you compile the gameclient.

> I will move it to game if you are still fully sure that the files should go exactly there and never move again. And if you say it is blocking the merge. Otherwise I would like to avoid manually applying all changes kaffeine made into the moved file during rebase.

Yes, please move the files like described in https://github.com/ddnet/ddnet/pull/5949#discussion_r1543330149. Their location. I think it would be fine if you squash the commits, as @Kaffeine said before in https://github.com/ChillerDragon/ddnet/pull/3#issuecomment-1868574554.

2024-03-29 17:16 UTC, Robyt3 commented
> is demos not working yet a problem for you?

What more specifically works and doesn't work?

2024-03-29 23:24 UTC, ChillerDragon commented
> > is demos not working yet a problem for you?
> 
> What more specifically works and doesn't work?

I spent 0 time on it. Just enough for it to compile. Everything is bugged. There are also 0.7 demo specific network items I did not cover yet.

2024-03-29 23:33 UTC, ChillerDragon commented on src/engine/client/sixup/translate_game.cpp
I do not want @Kaffeine to become the co author on the commit I have been working on for 2 years. It took me quite some time and effort to get this to work as it is right now. I do not feel comfortable sharing that commit.

2024-03-29 23:36 UTC, Kaffeine commented on src/engine/client/sixup/translate_game.cpp
No problem at all. I assumed you don't squash because you think a kind of opposite. Just do the squash then😀

2024-03-29 23:39 UTC, ChillerDragon commented on src/game/client/gameclient.cpp
> +	if(MsgId == NETMSGTYPE_SV_TUNEPARAMS || (Client()->IsSixup() && MsgId == protocol7::NETMSGTYPE_SV_TUNEPARAMS))
```
/home/chiller/Desktop/git/ddnet/src/game/client/gameclient.cpp: In member function ‘virtual void CGameClient::OnMessage(int, CUnpacker*, int, bool)’:                                                              
/home/chiller/Desktop/git/ddnet/src/game/client/gameclient.cpp:819:48: warning: comparison between ‘enum<unnamed>’ and ‘enum protocol7::<unnamed>’ [-Wenum-compare]                                                
  819 |         static_assert(NETMSGTYPE_SV_TUNEPARAMS == protocol7::NETMSGTYPE_SV_TUNEPARAMS, "0.6 and 0.7 tune message id do not match");                                                                        
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                      
At global scope:                                                                                                                                                                                                   
cc1plus: note: unrecognized command-line option ‘-Wno-nullability-completeness’ may have been intended to silence earlier diagnostics  
```

2024-03-29 23:41 UTC, ChillerDragon commented on src/engine/client/sixup/translate_game.cpp
I also do not want to swallow your changes and claim they are mine. I would like to keep the commit authors. Everything else feels wrong.

2024-03-30 01:39 UTC, ChillerDragon commented
I now took a close look at team colors. Until now the red and blue teams were still from the first poc state were I was satisfied with being able to distinguish enemy and friend. But markings were not rendered the same way as in 0.7. And the team colors did not match 0.6 or 0.7. It was red and blue but a brand new shade.

I now decided to go with a 0.6 look for team colors and markings. This only affects team play modes. The dm based modes still look exactly like 0.7.

In 0.7 the red and blue team colors were changed to something more saturated. In ddnet 0.7 connections it is now using the 0.6 version of the red and blue for the body. In 0.7 markings can have different colors and transparencies. When team play is on teeworlds 0.7 uses some magic color method to compute a matching shade of the custom marking for the given team color. I decided against that and went full 0.6 markings in team mode. So if there is a visible marking (transparency 10% or higher) it will have the 0.6 marking color without any shading support.

```diff
diff --git a/src/game/client/gameclient.cpp b/src/game/client/gameclient.cpp
index c091465a4..cb9f80587 100644
--- a/src/game/client/gameclient.cpp
+++ b/src/game/client/gameclient.cpp
@@ -2243,8 +2243,23 @@ void CGameClient::CClientData::UpdateRenderInfo(bool IsTeamPlay)
                {
                        m_RenderInfo.m_ColorBody = color_cast<ColorRGBA>(ColorHSLA(aTeamColors[m_Team]));
                        m_RenderInfo.m_ColorFeet = color_cast<ColorRGBA>(ColorHSLA(aTeamColors[m_Team]));
-                       for(auto &Color : m_RenderInfo.m_Sixup.m_aColors)
-                               Color = color_cast<ColorRGBA>(ColorHSLA(aTeamColors[m_Team]));
+
+                       // 0.7
+                       {
+                               const ColorRGBA aTeamColorsSixup[2] = {
+                                       ColorRGBA(0.753f, 0.318f, 0.318f, 1.0f),
+                                       ColorRGBA(0.318f, 0.471f, 0.753f, 1.0f)
+                               };
+                               const ColorRGBA aMarkingColorsSixup[2] = {
+                                       ColorRGBA(0.824f, 0.345f, 0.345f, 1.0f),
+                                       ColorRGBA(0.345f, 0.514f, 0.824f, 1.0f)
+                               };
+                               float MarkingAlpha = m_RenderInfo.m_Sixup.m_aColors[protocol7::SKINPART_MARKING].a;
+                               for(auto &Color : m_RenderInfo.m_Sixup.m_aColors)
+                                       Color = aTeamColorsSixup[m_Team];
+                               if(MarkingAlpha > 0.1f)
+                                       m_RenderInfo.m_Sixup.m_aColors[protocol7::SKINPART_MARKING] = aMarkingColorsSixup[m_Team];
+                       }
                }
                else
                {
```

I first wanted to support the transparency from 0.7 to allow users to see lighter shades of the markings. But it turned out that changing the alpha of ColorRGBA affects the color and turns it darker. That looks really wrong and ugly. And since the team colors are also 0.6 styled already might as well enforce full 0.6 marking colors. So ctf should feel the same on 0.6 and 0.7 servers.

Alpha being bugged. So I did not use it:
![colors](https://github.com/ddnet/ddnet/assets/20344300/cff9cc23-8694-47d0-935f-2d38cb1dbcf4)

This is how the 0.7 connection renders a ugly blue marking:
![image](https://github.com/ddnet/ddnet/assets/20344300/40016af1-ea6e-4c07-a746-6c38088ce732)

This is the marking that the tee actually has:
![image](https://github.com/ddnet/ddnet/assets/20344300/efc39ca1-31dc-4e0d-b6e4-4c799aa5e5d1)

This is how the 0.6 version in a 0.6 connection looks like:
![image](https://github.com/ddnet/ddnet/assets/20344300/75daf13c-23d9-4133-bb46-eb228697edcf)

This is how the 0.7 skin in a 0.7 connection looks like if the marking alpha is below 10% (its not rendered):
![image](https://github.com/ddnet/ddnet/assets/20344300/41eb6925-e3a7-441a-9a86-bed7c43b5ee7)

2024-03-30 01:53 UTC, ChillerDragon commented on src/engine/client/sixup/translate_game.cpp
Done. Moved them. Now they are in separate folders and thus more spread in the code base. This is something lerato might not like.

2024-03-30 02:04 UTC, ChillerDragon commented
This pr became so bloated it is tricky to keep track of all the reviews. I think I solved all of them. And still wait for feedback [here](https://github.com/ddnet/ddnet/pull/5949#discussion_r1544954580).

@Robyt3 if you plan to do another run with a bunch of reviews that should not get lost maybe you could open issues [here](https://github.com/ChillerDragon/ddnet/issues) instead so we have a nicer overview.

I turned the pr into a draft because I do not want it to be merged as is. My initial plan was to merge it partially just to reduce the git maintenance and hide the 0.7 support from the end users. But now it got so stable that it could be shipped to the end users directly. I would like to do one proper test by playing a bit before it is being shipped to users.

**tl;dr status:** ready for review, not ready to merge

2024-03-30 09:28 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +	if(MsgId == NETMSGTYPE_SV_TUNEPARAMS || (Client()->IsSixup() && MsgId == protocol7::NETMSGTYPE_SV_TUNEPARAMS))
Cast both to `int`

2024-04-03 00:35 UTC, ChillerDragon commented
Okay I am starting to work on demo support now. I got the snap fixed but game/system and demo specific messages are still missing. Chat looks all borked, skins are wrong. But you can already follow the gameplay.

I decided to write the translated data to disk. So the sixup connections produce 0.6 demos and the ddnet client can still not play back demos created by 0.7 clients. That is a bit sad but its the most backwards compatible, least intrusive and more simple approach it seems.

2024-04-03 08:08 UTC, ChillerDragon commented
Okay the ddnet can now play back demos recorded by 0.7 teeworlds clients. The next goal is to write correct 0.7 demos when playing in sixup connections.

2024-04-11 02:19 UTC, ChillerDragon commented
While working on demos I realized I had to pull more and more game client code into the snapshot translation layer. So I decided to move the entire snapshot translation method out of the engine/snapshot into the gameclient. This way there is no dependency on the game layer in the engine.

<details>

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6e39671cb..f6724ee68 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -2415,6 +2415,7 @@ if(CLIENT)
     render.h
     render_map.cpp
     sixup_translate_game.cpp
+    sixup_translate_snapshot.cpp
     skin.h
     ui.cpp
     ui.h
diff --git a/src/engine/client.h b/src/engine/client.h
index 62657ffb2..db6f3228a 100644
--- a/src/engine/client.h
+++ b/src/engine/client.h
@@ -359,6 +359,7 @@ public:
 
 	virtual void ApplySkin7InfoFromSnapObj(const protocol7::CNetObj_De_ClientInfo *pObj, int ClientId) = 0;
 	virtual int OnDemoRecSnap7(class CSnapshot *pFrom, class CSnapshot *pTo) = 0;
+	virtual int TranslateSnap(class CSnapshot *pSnapSix, class CSnapshot *pSnapSeven, int Conn, bool Dummy) = 0;
 };
 
 void SnapshotRemoveExtraProjectileInfo(class CSnapshot *pSnap);
diff --git a/src/engine/client/client.cpp b/src/engine/client/client.cpp
index 222efeff4..669fd14e3 100644
--- a/src/engine/client/client.cpp
+++ b/src/engine/client/client.cpp
@@ -53,6 +53,7 @@
 
 #include "client.h"
 #include "demoedit.h"
+#include "engine/client.h"
 #include "friends.h"
 #include "notifications.h"
 #include "serverbrowser.h"
@@ -1970,16 +1971,7 @@ void CClient::ProcessServerPacket(CNetChunk *pPacket, int Conn, bool Dummy)
 						unsigned char aTmpTransSnapBuffer[CSnapshot::MAX_SIZE];
 						CSnapshot *pTmpTransSnapBuffer = (CSnapshot *)aTmpTransSnapBuffer;
 						mem_copy(pTmpTransSnapBuffer, pTmpBuffer3, CSnapshot::MAX_SIZE);
-						AltSnapSize = pTmpTransSnapBuffer->TranslateSevenToSix(
-							pAltSnapBuffer,
-							m_TranslationContext,
-							LocalTime(),
-							CClient::GameTick(g_Config.m_ClDummy),
-							Conn,
-							Dummy,
-							GameClient()->GetNetObjHandler7(),
-							GameClient()->GetNetObjHandler(),
-							GameClient());
+						AltSnapSize = GameClient()->TranslateSnap(pTmpTransSnapBuffer, pAltSnapBuffer, Conn, Dummy);
 					}
 					else
 					{
@@ -2519,7 +2511,7 @@ void CClient::OnDemoPlayerSnapshot(void *pData, int Size)
 	if(IsSixup())
 	{
 		pTmpTranslateBuffer = (CSnapshot *)aTmpTranslateBuffer;
-		TranslatedSize = ((CSnapshot *)pData)->TranslateSevenToSix(pTmpTranslateBuffer, m_TranslationContext, LocalTime(), GameTick(g_Config.m_ClDummy), CONN_MAIN, false, GameClient()->GetNetObjHandler7(), GameClient()->GetNetObjHandler(), GameClient());
+		TranslatedSize = GameClient()->TranslateSnap((CSnapshot *)pData, pTmpTranslateBuffer, CONN_MAIN, false);
 		if(TranslatedSize < 0)
 		{
 			dbg_msg("sixup", "failed to translate snapshot. error=%d", TranslatedSize);
diff --git a/src/engine/shared/sixup_translate_snapshot.cpp b/src/engine/shared/sixup_translate_snapshot.cpp
index 419e0c4ab..b2af53205 100644
--- a/src/engine/shared/sixup_translate_snapshot.cpp
+++ b/src/engine/shared/sixup_translate_snapshot.cpp
@@ -1,515 +1,6 @@
-#include <base/math.h>
 #include <base/system.h>
-#include <engine/client.h>
-#include <engine/shared/protocol.h>
-#include <engine/shared/protocolglue.h>
-#include <engine/shared/translation_context.h>
-#include <game/client/gameclient.h>
-#include <game/gamecore.h>
-#include <game/generated/protocol.h>
-#include <game/generated/protocol7.h>
-#include <game/generated/protocolglue.h>
 
 #include "snapshot.h"
-#include "uuid_manager.h"
-
-int CSnapshot::TranslateSevenToSix(
-	CSnapshot *pSixSnapDest,
-	CTranslationContext &TranslationContext,
-	float LocalTime,
-	int GameTick,
-	int Conn,
-	bool Dummy,
-	protocol7::CNetObjHandler *pNetObjHandler,
-	CNetObjHandler *pNetObjHandler6,
-	IGameClient *pGameClient)
-{
-	CSnapshotBuilder Builder;
-	Builder.Init();
-
-	for(auto &PlayerInfosRace : TranslationContext.m_apPlayerInfosRace)
-		PlayerInfosRace = nullptr;
-
-	int SpectatorId = -3;
-
-	for(int i = 0; i < m_NumItems; i++)
-	{
-		const CSnapshotItem *pItem7 = (CSnapshotItem *)GetItem(i);
-		const int Size = GetItemSize(i);
-		const int ItemType = GetItemType(i);
-
-		// ddnet ex snap items
-		if((ItemType > __NETOBJTYPE_UUID_HELPER && ItemType < OFFSET_NETMSGTYPE_UUID) || pItem7->Type() == NETOBJTYPE_EX)
-		{
-			CUnpacker Unpacker;
-			Unpacker.Reset(pItem7->Data(), Size);
-
-			void *pRawObj = pNetObjHandler6->SecureUnpackObj(ItemType, &Unpacker);
-			if(!pRawObj)
-			{
-				if(ItemType != UUID_UNKNOWN)
-					dbg_msg("sixup", "dropped weird ddnet ex object '%s' (%d), failed on '%s'", pNetObjHandler6->GetObjName(ItemType), ItemType, pNetObjHandler6->FailedObjOn());
-				continue;
-			}
-			const int ItemSize = pNetObjHandler6->GetUnpackedObjSize(ItemType);
-
-			void *pObj = Builder.NewItem(pItem7->Type(), pItem7->Id(), ItemSize);
-			if(!pObj)
-				return -17;
-
-			mem_copy(pObj, pRawObj, ItemSize);
-			continue;
-		}
-
-		if(pNetObjHandler->ValidateObj(pItem7->Type(), pItem7->Data(), Size) != 0)
-		{
-			if(pItem7->Type() > 0 && pItem7->Type() < OFFSET_UUID_TYPE)
-			{
-				dbg_msg(
-					"sixup",
-					"invalidated index=%d type=%d (%s) size=%d id=%d",
-					i,
-					pItem7->Type(),
-					pNetObjHandler->GetObjName(pItem7->Type()),
-					Size,
-					pItem7->Id());
-			}
-			InvalidateItem(i);
-		}
-
-		if(pItem7->Type() == protocol7::NETOBJTYPE_PLAYERINFORACE)
-		{
-			const protocol7::CNetObj_PlayerInfoRace *pInfo = (const protocol7::CNetObj_PlayerInfoRace *)pItem7->Data();
-			int ClientId = pItem7->Id();
-			if(ClientId < MAX_CLIENTS && TranslationContext.m_aClients[ClientId].m_Active)
-			{
-				TranslationContext.m_apPlayerInfosRace[ClientId] = pInfo;
-			}
-		}
-		else if(pItem7->Type() == protocol7::NETOBJTYPE_SPECTATORINFO)
-		{
-			const protocol7::CNetObj_SpectatorInfo *pSpec7 = (const protocol7::CNetObj_SpectatorInfo *)pItem7->Data();
-			SpectatorId = pSpec7->m_SpectatorId;
-			if(pSpec7->m_SpecMode == protocol7::SPEC_FREEVIEW)
-				SpectatorId = SPEC_FREEVIEW;
-		}
-	}
-
-	// hack to put game info in the snap
-	// even though in 0.7 we get it as a game message
-	// this message has to be on the top
-	// the client looks at the items in order and needs the gameinfo at the top
-	// otherwise it will not render skins with team colors
-	if(TranslationContext.m_ShouldSendGameInfo)
-	{
-		void *pObj = Builder.NewItem(NETOBJTYPE_GAMEINFO, 0, sizeof(CNetObj_GameInfo));
-		if(!pObj)
-			return -1;
-
-		int GameStateFlagsSix = 0;
-		if(TranslationContext.m_GameStateFlags7 & protocol7::GAMESTATEFLAG_GAMEOVER)
-			GameStateFlagsSix |= GAMESTATEFLAG_GAMEOVER;
-		if(TranslationContext.m_GameStateFlags7 & protocol7::GAMESTATEFLAG_SUDDENDEATH)
-			GameStateFlagsSix |= GAMESTATEFLAG_SUDDENDEATH;
-		if(TranslationContext.m_GameStateFlags7 & protocol7::GAMESTATEFLAG_PAUSED)
-			GameStateFlagsSix |= GAMESTATEFLAG_PAUSED;
-
-		/*
-			This is a 0.7 only flag that we just ignore for now
-
-			GAMESTATEFLAG_ROUNDOVER
-		*/
-
-		CNetObj_GameInfo Info6 = {};
-		Info6.m_GameFlags = TranslationContext.m_GameFlags;
-		Info6.m_GameStateFlags = GameStateFlagsSix;
-		Info6.m_RoundStartTick = TranslationContext.m_GameStartTick7;
-		Info6.m_WarmupTimer = 0; // removed in 0.7
-		if(TranslationContext.m_GameStateFlags7 & protocol7::GAMESTATEFLAG_WARMUP)
-			Info6.m_WarmupTimer = TranslationContext.m_GameStateEndTick7 - GameTick;
-		if(TranslationContext.m_GameStateFlags7 & protocol7::GAMESTATEFLAG_STARTCOUNTDOWN)
-			Info6.m_WarmupTimer = TranslationContext.m_GameStateEndTick7 - GameTick;
-
-		// hack to port 0.7 race timer to ddnet warmup gametimer hack
-		int TimerClientId = clamp(TranslationContext.m_aLocalClientId[Conn], 0, (int)MAX_CLIENTS);
-		if(SpectatorId >= 0)
-			TimerClientId = SpectatorId;
-		const protocol7::CNetObj_PlayerInfoRace *pRaceInfo = TranslationContext.m_apPlayerInfosRace[TimerClientId];
-		if(pRaceInfo)
-		{
-			Info6.m_WarmupTimer = -pRaceInfo->m_RaceStartTick;
-			Info6 [...]

2024-04-24 08:46 UTC, ChillerDragon commented
Okay demo support is finished. Demos can be recorded and played back just fine. Tested with dummy too.

2024-04-24 08:48 UTC, jxsl13 commented
sick.

2024-04-25 02:55 UTC, ChillerDragon commented
# out of draft

## done

- Implemented all features I wanted to implement.
- Implemented all feedback comments on this pr.
- Fixed all bugs I found while testing.
- Tested by playing on vanilla servers and ddnet servers.
- Tested using asan and ubsan.
- Tested demos and dummy.

## not planned

Missing 0.7 features are:
- colored broadcast
- race (best time, checkpoints, ..)
- chat commands
- chat translation
- rcon map list entries

Those features are not gameplay relevant and somewhat optional features that were added in 0.7.
They are not really used in vanilla gameplay. So their complexity is just making this way too big pull request bigger.

I might add support for them in a follow up pullrequest.

2024-04-27 16:15 UTC, heinrich5991 commented on src/engine/client/client.cpp
> +		Msg7.AddString(pPassword, 32);
Truncating passwords has a bad history. We shouldn't pretend that we accept the longer password and truncate it to a "good size" so that the "authentication works". Let it blow up in the user's face so that they understand that their password was truncated behind their backs. Otherwise you'll have them think their long password actually works.

2024-04-28 01:30 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +		Msg7.AddString(pPassword, 32);
Okay I removed the limit. I still don't like it but fine.

2024-04-28 03:40 UTC, ChillerDragon commented
I responded to all review comments last month already. What is currently blocking the merge? Is any maintainer still planning to do another review? Or are you waiting for me to do something?

2024-05-02 10:32 UTC, ChillerDragon commented
Fixed new git conflict with master branch. Ready for review.

2024-05-02 19:13 UTC, Robyt3 requested changes
Final round of comments from my side.

2024-05-02 19:13 UTC, Robyt3 commented on src/game/client/components/skins7.h
> +		vec3 m_BloodColor;
`ColorRGBA`

2024-05-02 19:13 UTC, Robyt3 commented on src/game/client/components/skins7.h
> +	std::vector<CSkin> m_aSkins;
`m_avSkinParts`, `m_vSkins`

2024-05-02 19:13 UTC, Robyt3 commented on src/game/client/components/skins7.cpp
> +	free(Info.m_pData);
Use `LoadTextureRawMove` and remove the `free`

2024-05-02 19:13 UTC, Robyt3 commented on src/game/client/components/skins7.cpp
> +			free(Info.m_pData);
Use `LoadTextureRawMove` and remove the `free`

2024-05-02 19:13 UTC, Robyt3 commented on src/game/client/components/skins7.cpp
> +			free(Info.m_pData);
Use `LoadTextureRawMove` and remove the `free`

2024-05-02 19:16 UTC, Robyt3 commented on src/game/client/components/skins7.cpp
> +	free(Info.m_pData);
Also, when calling `LoadTextureRaw` and `LoadTextureRawMove`, pass the filename as the third argument for better error/warning messages.

2024-05-02 23:19 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +		}
Yes it was sent twice and no it is not needed. Good catch thanks.

2024-05-03 00:22 UTC, ChillerDragon commented on src/game/client/components/skins7.cpp
> +	free(Info.m_pData);
What about

```C++
	Part.m_OrgTexture = pSelf->Graphics()->LoadTextureRaw(Info, 0);
```

2024-05-03 08:36 UTC, Robyt3 commented on src/game/client/components/skins7.cpp
> +	free(Info.m_pData);
Also pass the filename/path as the third argument, but keep using `LoadTextureRaw`.

You can use `LoadTextureRawMove` only when you would otherwise manually free the texture afterwards, as the backend will free the texture for you if you use this function (and it will avoid copying the data internally). The original and greyscale textures use the same data, so if you used `LoadTextureRawMove` for both, then the first call would free the data already.

2024-05-04 02:04 UTC, ChillerDragon commented on src/game/client/components/chat.h
> +			int m_aSkinPartColors[protocol7::NUM_SKINPARTS];
Could I just remove those variables and not support skin refresh for 0.7 in this pr? This seems like a big task for little gain. I would also have to add a new button to the UI code. Update all other components to support skin refreshing. There are no skin download urls for 0.7 yet anyways. This only affects someone editing the skin file on the disk and then clicking the refresh button. Also if I were to introduce OnRefreshSkins7 it would add way more git conflict surface to his pr which makes it even harder to keep rebasing.

This creates a bunch of code changes that could introduce new bugs and have to be reviewed again. Imo skin refresh is a feature out of scope for this too big pr and not needed for feature complete CTF gameplay.

I can implement this feature as soon as this pr is merged into master.

2024-05-04 08:27 UTC, ChillerDragon commented
I found a new bug. Cutting demos does not work.

2024-05-05 10:10 UTC, Robyt3 requested changes

2024-05-05 10:10 UTC, Robyt3 commented on src/engine/client/client.cpp
> +		m_aapSnapshots[0][SnapshotType]->m_TransSnapSize = 0;
This variable is unused.

2024-05-05 10:13 UTC, Robyt3 commented on src/game/client/components/chat.h
> +			int m_aSkinPartColors[protocol7::NUM_SKINPARTS];
Yeah, seems fine for now if refreshing 0.7 skins is not enabled right now.

2024-05-05 10:39 UTC, ChillerDragon commented on src/engine/client/client.h
> +	int TranslateSysMsg(int *pMsgId, bool System, CUnpacker *pUnpacker, CPacker &Packer, CNetChunk *pPacket, bool &IsExMsg);
Which one? Reference or pointers? If we prefer references we could mention that in https://github.com/ddnet/ddnet/pull/8288

2024-05-05 11:48 UTC, Robyt3 commented on src/engine/client/client.h
> +	int TranslateSysMsg(int *pMsgId, bool System, CUnpacker *pUnpacker, CPacker &Packer, CNetChunk *pPacket, bool &IsExMsg);
Whether to prefer pointers or references overall is still an open discussion (#3088).

For "local" consistency with the other functions in `IClient` I would prefer pointers here since we mostly seem to use pointers here at the moment.

2024-05-06 01:04 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +							}
I agree with the problem and would like to do even more but that would be out of scope for this pr.
The `CClient` should not send chat messages the chat.cpp component should do that.
Also the method name `Say` in chat.cpp should be changed to `SendChat` (see https://github.com/teeworlds/teeworlds/pull/3239).

Instead of hand crafting a chat messages in the snapshot unpack code the gameclient should have a way to detect if enough snapshots were received to send the timeout code.

This magic comment and all the hacky code below it should be replaced by a component hook.

https://github.com/ddnet/ddnet/blob/5586961b4cb674b3bd3f2ea9fcc312e4400b87be/src/engine/client/client.cpp#L1845

It should do something like `GameClient()->OnConnected()` there. Which then calls `OnConnected()` in all components. So we can move the timeout code and all the other things directly into chat.cpp

---

I did add your SendPackMsg and used the much nicer `protocol7::CNetMsg_Cl_Say`. The other things should be a separate pr imo.

```diff
diff --git a/src/engine/client.h b/src/engine/client.h
index 1f025a51f..130a70222 100644
--- a/src/engine/client.h
+++ b/src/engine/client.h
@@ -247,6 +247,15 @@ public:
                return SendMsgActive(&Packer, Flags);
        }
 
+       template<class T>
+       int SendPackMsg(int Conn, T *pMsg, int Flags, bool NoTranslate = false)
+       {
+               CMsgPacker Packer(T::ms_MsgId, false, NoTranslate);
+               if(pMsg->Pack(&Packer))
+                       return -1;
+               return SendMsg(Conn, &Packer, Flags);
+       }
+
        //
        virtual const char *PlayerName() const = 0;
        virtual const char *DummyName() const = 0;
diff --git a/src/engine/client/client.cpp b/src/engine/client/client.cpp
index 2b09ba761..2a34ca807 100644
--- a/src/engine/client/client.cpp
+++ b/src/engine/client/client.cpp
@@ -2106,11 +2106,11 @@ void CClient::ProcessServerPacket(CNetChunk *pPacket, int Conn, bool Dummy)
                                                        }
                                                        if(IsSixup())
                                                        {
-                                                               CMsgPacker MsgSay(NETMSGTYPE_CL_SAY);
-                                                               MsgSay.AddInt(protocol7::CHAT_ALL); // mode
-                                                               MsgSay.AddInt(-1); // target
-                                                               MsgSay.AddString(aBufMsg, sizeof(aBufMsg)); // msg
-                                                               SendMsg(Conn, &MsgSay, MSGFLAG_VITAL);
+                                                               protocol7::CNetMsg_Cl_Say Msg7;
+                                                               Msg7.m_Mode = protocol7::CHAT_ALL;
+                                                               Msg7.m_Target = -1;
+                                                               Msg7.m_pMessage = aBufMsg;
+                                                               SendPackMsg(Conn, &Msg7, MSGFLAG_VITAL, true);
                                                        }
                                                        else
                                                        {
```

2024-05-06 03:11 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +							}
I gave the new component hook a try and could not come up with anything clean.
I don't like the `CClient::SendSayChat` too much either. The current code on the master is ugly but I don't know a nice fix for it. I still think it is not the responsibility of the 0.7 pr to cleanup existing issues of the master branch.

The DbgStress thing is in gameclient.cpp so that could just use `m_Chat.SendChat()` instead of manually building the message. I sent a separate pr for that https://github.com/ddnet/ddnet/pull/8316

2024-05-06 11:46 UTC, Robyt3 approved these changes
LGTM!

2024-05-23 00:17 UTC, ChillerDragon commented
Solved new conflicts with master branch. Ready for review.

2024-06-01 11:11 UTC, ChillerDragon commented
Seems like the merge broke connecting to 0.7 servers...

2024-06-02 04:19 UTC, ChillerDragon commented
Fixed :white_check_mark:. It was caused by the new token endianness.

2024-07-05 01:09 UTC, ChillerDragon commented
Solved big time conflicts with https://github.com/ddnet/ddnet/pull/8545

2024-07-05 01:19 UTC, ChillerDragon commented
Fixed winter maps see https://github.com/ChillerDragon/ddnet/issues/8 and https://github.com/ddnet/ddnet/pull/8546

2024-07-21 13:57 UTC, ChillerDragon commented
@SoulyVEVO reported some [bugs](https://github.com/ChillerDragon/ddnet/issues/10). I am planning to fix those as soon as I get to it. Nothing criticial. Just small polishes.

2024-07-21 21:13 UTC, fokkonaut commented
@ChillerDragon You probably have to add seperate infos for main/dummy, like here in F-Client: https://github.com/fokkonaut/F-Client/commit/628ea8abe03e910e2f4a6b6f4cb106cdad584431
Since 0.7 removed a lot of things from the snap, we have to handle things more seperately on the clientside now as it's not as variable as it used to be with the snaps of 0.6.

2024-07-23 11:01 UTC, Kaffeine commented
@ChillerDragon, it seems that RenderHand7 is still missing (sorry I can't help with it).  We'd need to somehow port 0.7 RenderHand (https://github.com/teeworlds/teeworlds/commit/ecea6edcf70f34a6a8afb7f1652a14f457f3bc46) to [DDNet refactoring](https://github.com/ddnet/ddnet/commit/a59d7401b51ac78d9f29a184c20225c83044b5e2#diff-619bc2285dfceebaa74c335ad9df122d2cc19e665de4536801ccf63c4ab80714R57).

Currently 'alpha' transparency does not work well with 0.6 skins (we need to apply alpha to rendered tee, instead of layering semi-transparent tee parts). 
![image](https://github.com/user-attachments/assets/00195bc5-4371-4f51-b534-5c39799382c5)
 and I thought that with multipart 0.7 skins it would be even worse but no, it is not worse. 
![image](https://github.com/user-attachments/assets/22d53626-60fa-450a-887d-ca8a59639c6f)

2024-07-23 12:59 UTC, Kaffeine commented
> @Kaffeine yes I am currently working on RenderHand7 (see [ChillerDragon#16](https://github.com/ChillerDragon/ddnet/issues/16))
> 
That's cool, thank you (no irony). I've also mentioned this issue in https://github.com/ChillerDragon/ddnet/pull/3.

2024-07-23 22:50 UTC, ChillerDragon commented
@Kaffeine I mean yes your suggestion seems more correct. It just never bothered me in game in 0.6. Looks good enough to me. But yea idk how to do that and it's for sure not belonging in this pr. If you think it's a bug that should be fixed you can open a new issue.

2024-07-24 04:53 UTC, ChillerDragon commented
@def- can we get some progress here? This pr is done since a while. A few 0.7 features are intentionally not in scope and could be added later. A few players already tried it and reported bugs that were fixed. There are some minor things that I am still polishing the progress can be seen [here](https://github.com/ChillerDragon/ddnet/issues?q=is%3Aissue+is%3Aopen+ChillerDragon%3Apr_07_client+). Even without these small details implemented it is ready to be merged and totally playable.

@Robyt3 [approved the pr over 2 months ago](https://github.com/ddnet/ddnet/pull/5949#pullrequestreview-2040603358). That review is getting more and more outdated the longer I keep polishing small things and merge into the master branch.

heinrich is probably not going to review this again any time soon but he had 2 years time to veto anything and already approved the general concept.

2024-08-10 12:51 UTC, def- approved these changes
As noted on Discord, I personally don't think it makes sense to support the 20 players that TW 0.7 has with all this effort. But since the effort is done, merging.

2024-08-10 13:26 UTC, merged