Add buttons+increased length on demo viewbar
ddnet/ddnet pull request #6060
Opened 2022-11-19 22:52 UTC by l-ouis

Aimed to add some more controls on the demo view bar:

Added tick step buttons and jump to next/prev marker buttons
Increased width of demo controls panel so it wasn't as cluttered
changed export cut icon to a common export icon instead of the camcorder icon
Centered the time multiplier

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2022-11-19 22:53 UTC, l-ouis commented
first code pr, i'm pretty sure i wrote a bunch of spaghetti 😅😅😅

2022-11-19 23:58 UTC, def- requested changes
Doesn't look bad

2022-11-19 23:58 UTC, def- commented on src/game/client/components/menus_demo.cpp
> +	CUIRect SeekBar, ButtonBar, NameBar, SpeedBar{};
The `{}` doesn't hurt, it zero-initializes the object, just costs a bit. Can be left out.

2022-11-19 23:58 UTC, def- commented on src/game/client/components/menus_demo.cpp
> +	ButtonBar.VSplitLeft(Margins + 10.0f, 0, &ButtonBar);
The +10.0f is just a magic number to make it look nicer?

2022-11-19 23:58 UTC, def- commented on src/game/client/components/menus_demo.cpp
> +				DemoPlayer()->SeekPercent(static_cast<float>(pInfo->m_aTimelineMarkers[i] - pInfo->m_FirstTick) / static_cast<float>(TotalTicks));
I think the second cast is not required

2022-11-20 03:54 UTC, l-ouis commented on src/game/client/components/menus_demo.cpp
> +	ButtonBar.VSplitLeft(Margins + 10.0f, 0, &ButtonBar);
Yes, to slightly separate the play/stop with the two tick controls

2022-11-20 04:01 UTC, l-ouis commented on src/game/client/components/menus_demo.cpp
> +	CUIRect SeekBar, ButtonBar, NameBar, SpeedBar{};
Deleted

2022-11-20 04:01 UTC, l-ouis commented on src/game/client/components/menus_demo.cpp
> +				DemoPlayer()->SeekPercent(static_cast<float>(pInfo->m_aTimelineMarkers[i] - pInfo->m_FirstTick) / static_cast<float>(TotalTicks));
Removed second casts, and changed the cast to use `(float)` instead of `static_cast<float>`

2022-11-20 09:40 UTC, Robyt3 commented
Skipping forward multiple times in a row doesn't work. You need a larger threshold to consider multiple ticks to belong to the same marker. You can take some inspiration from upstream:

https://github.com/teeworlds/teeworlds/blob/26d24ec061d44e6084b2d77a9b8a0a48e354eba6/src/game/client/components/menus_demo.cpp#L199-L246

Would also be nice if you could skip to the beginning or end if there is no previous or next marker respectively.

2022-11-20 15:03 UTC, l-ouis commented
> Skipping forward multiple times in a row doesn't work. You need a larger threshold to consider multiple ticks to belong to the same marker. You can take some inspiration from upstream:
Do I need a very long demo to reproduce? I noticed I needed a small threshold, `if((pInfo->m_aTimelineMarkers[i] - pInfo->m_FirstTick) - 2 > CurrentTick)`, (2 ticks in that case). If it doesn't work for longer demos or more spread-apart markers then I will fix it (And I'll add a constant + comment as well)

> Would also be nice if you could skip to the beginning or end if there is no previous or next marker respectively.
will add

2022-11-20 15:09 UTC, Robyt3 commented
I tried it with a demo that's about a minute long. On upstream I used a threshold of 10 ticks in both directions.

2022-11-23 04:00 UTC, VoxelDoesCode commented
I've done some tests, so I'll put some notes here:

Can you align the actual markers with the playhead when you skip to them? It turns out that the actual marker points are behind where they should be. Under `// draw slice markers`, the marker is offset by 10 pixels to align with the playhead, seen in `IGraphics::CQuadItem QuadItem(10.0f + SeekBar.x [...]`. The markers don't have that extra 10.0f.
![image](https://user-images.githubusercontent.com/95713843/203466314-b2082f3d-c89d-4634-99d1-6078bba90258.png)

Also if you manage to add a demomarker right when you start your demo, you can skip back to it, and then skip to the beginning (which is a really short distance). But when you skip forward, it skips that other marker completely and goes to the one after that. Unsure if this is worth it to fix, but it's something to note anyways.

2022-12-04 05:44 UTC, l-ouis commented
> Also if you manage to add a demomarker right when you start your demo, you can skip back to it, and then skip to the beginning (which is a really short distance). But when you skip forward, it skips that other marker completely and goes to the one after that.

In this case I believe the marker will be so close to the beginning that it shouldn't have a noticeable effect, but correct me if I'm wrong

2022-12-04 11:09 UTC, def- commented
bors r+
Thanks louis!

2022-12-04 11:28 UTC, merged