Add /unsolo and /undeep practice commands
ddnet/ddnet pull request #6617
Opened 2023-05-18 19:58 UTC by hus3h

Related: https://github.com/ddnet/ddnet/issues/6318#issuecomment-1498626132 and #2391

Unsolo is often needed especially in maps with death tiles and solo part spawns, undeep can also be useful for some parts.

Some notes:

- didn't use `CFGFLAG_SERVER` for the commands as it resulted in a conflict with the registered `unsolo` and `undeep` super team console commands, not entirely sure if that's okay
- `/help unsolo` and `/help undeep` will print the help text of the super team commands, not the new chat commands. The texts are currently the same, but it's still a sign of possible conflicts
- prevented `/unsolo` on solo servers by checking for `SV_TEAM_FORBIDDEN` and `SV_TEAM_FORCED_SOLO`, let me know if that's not enough (Tutorial map?)
- no server message is sent on `/unsolo` (as opposed to going through unsolo tiles), didn't seem like it's needed here even if it feels different at first

 If the conflicts are problematic enough, the easiest fix might be using new unique commands instead of `unsolo` and `undeep`, I couldn't think of something that would fit as well though.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-05-18 20:05 UTC, def- requested changes
Generally looks fine

2023-05-18 20:05 UTC, def- commented on src/game/ddracechat.h
> +CHAT_COMMAND("unsolo", "", CFGFLAG_CHAT, ConPracticeUnSolo, this, "Puts you out of solo part")
```suggestion
CHAT_COMMAND("unsolo", "", CFGFLAG_CHAT | CFGFLAG_SERVER, ConPracticeUnSolo, this, "Puts you out of solo part")
```

2023-05-18 20:05 UTC, def- commented on src/game/ddracechat.h
> +CHAT_COMMAND("undeep", "", CFGFLAG_CHAT, ConPracticeUnDeep, this, "Puts you out of deep freeze")
```suggestion
CHAT_COMMAND("undeep", "", CFGFLAG_CHAT | CFGFLAG_SERVER, ConPracticeUnDeep, this, "Puts you out of deep freeze")
```

2023-05-18 20:05 UTC, def- commented on src/game/server/gamecontext.h
> +	static void ConPracticeUnSolo(IConsole::IResult *pResult, void *pUserData);
```suggestion
	static void ConPracticeUnsolo(IConsole::IResult *pResult, void *pUserData);
```

2023-05-18 20:05 UTC, def- commented on src/game/server/gamecontext.h
> +	static void ConPracticeUnDeep(IConsole::IResult *pResult, void *pUserData);
```suggestion
	static void ConPracticeUndeep(IConsole::IResult *pResult, void *pUserData);
```

2023-05-18 20:05 UTC, def- commented on src/game/server/ddracechat.cpp
> +void CGameContext::ConPracticeUnSolo(IConsole::IResult *pResult, void *pUserData)
```suggestion
void CGameContext::ConPracticeUnsolo(IConsole::IResult *pResult, void *pUserData)
```

2023-05-18 20:05 UTC, def- commented on src/game/server/ddracechat.cpp
> +void CGameContext::ConPracticeUnDeep(IConsole::IResult *pResult, void *pUserData)
```suggestion
void CGameContext::ConPracticeUndeep(IConsole::IResult *pResult, void *pUserData)
```
I consider "undeep" and "unsolo" to be one verb, so no capitalization inbetween

2023-05-18 20:17 UTC, hus3h commented on src/game/server/ddracechat.cpp
> +void CGameContext::ConPracticeUnDeep(IConsole::IResult *pResult, void *pUserData)
I agree it's better but I mainly copied the style from the other commands:

```c++
void CGameContext::ConUnSolo(IConsole::IResult *pResult, void *pUserData)
```
```c++
void CGameContext::ConUnDeep(IConsole::IResult *pResult, void *pUserData)
```

Should I rename the new commands to `Unsolo` and `Undeep` anyway?

2023-05-18 20:27 UTC, hus3h commented on src/game/ddracechat.h
> +CHAT_COMMAND("unsolo", "", CFGFLAG_CHAT, ConPracticeUnSolo, this, "Puts you out of solo part")
Sadly adding this flag results in a conflict with `unsolo` and `undeep` commands of super team and then they are called instead, although they don't work:

`Access for command unsolo denied.` in the terminal output.

More details in the original comment, might have to use different words if the commands must be unique (across chat and console).

2023-05-18 20:51 UTC, Robyt3 commented on src/game/server/ddracechat.cpp
> +void CGameContext::ConPracticeUnDeep(IConsole::IResult *pResult, void *pUserData)
If you want, you can also rename the functions in the existing code (preferably in a separate commit or PR).

2023-05-18 22:40 UTC, def- commented on src/game/ddracechat.h
> +CHAT_COMMAND("unsolo", "", CFGFLAG_CHAT, ConPracticeUnSolo, this, "Puts you out of solo part")
Oh right, there are rcon commands for that already, forgot.

2023-05-19 10:35 UTC, hus3h commented on src/game/server/ddracechat.cpp
> +void CGameContext::ConPracticeUnDeep(IConsole::IResult *pResult, void *pUserData)
@Robyt3 If you mean for the whole project, there are 60 results in 12 files for `Un[A-Z]`, which made me a little bit hesitant as I don't know how big of a change that refactoring would be (for custom modes and forks, developers used to the old syntax, branches in progress) considering it'd include changes to core functions like character `UnFreeze` for example. Also not sure whether terms like `UnFreezeHammer` would also be considered one verb and become `Unfreezehammer` (and whether that's a better style in this case).

2023-05-19 12:01 UTC, def- commented
bors r+
Alright, let's do the Un[A-Z] later

2023-05-19 12:51 UTC, merged