Improve demo (video) renderer UX
ddnet/ddnet pull request #6820
Opened 2023-07-08 01:27 UTC by Kaffeine

In this MR I want to address three issues with video recorder:
1. A bug: if I start a rendering with 0.25x speed and click on 'Increase the speed' during the rendering, I expect to get the next speed (0.5x) but as the speed index is not set (kept default `4`), the speed is boosted to 1.25x.
2. Usecase: I want to adjust the camera (change position, decrease zoom, etc) for the demos and I don't want to use extra video editor to cut the first frames with the unwanted camera settings from the demo. I came to a simple solution: start the rendering pre-paused to do the needed adjustments before anything added to the video.
3. NotABug: All recorded video files have double `.demo.mp4` extension which is ugly.

Probably I have to change something to fit DDNet codebase. E.g. I don't know if `Localize("(paused)")` is acceptable here.

## Before
![image](https://github.com/ddnet/ddnet/assets/374839/7273dd5b-e3d1-4f73-87bd-e09493d106a0)

## After
![image](https://github.com/ddnet/ddnet/assets/374839/7d62028d-04bc-45af-babf-5a2e8cb243dc)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-07-08 07:31 UTC, def- requested changes

2023-07-08 07:31 UTC, def- commented on src/game/client/components/menus.cpp
> +			const char *pPaused = g_Config.m_ClVideoPauseOnStart ? Localize("(paused)") : "";
What good is the paused button?

2023-07-08 08:20 UTC, Robyt3 requested changes

2023-07-08 08:20 UTC, Robyt3 commented on src/game/client/components/menus_demo.cpp
> +			}
```cpp
char aNameWithoutExt[IO_MAX_PATH_LENGTH];
fs_split_file_extension(m_vDemos[m_DemolistSelectedIndex].m_aFilename, aNameWithoutExt, sizeof(aNameWithoutExt));
m_DemoRenderInput.Set(aNameWithoutExt);
```

`m_aFilename` should always have the `.demo` file extension, so no check for existing extension should be necessary.

2023-07-08 08:20 UTC, Robyt3 commented on src/game/editor/io.cpp
> +		for(CLayer *pLayer : pGroup->m_vpLayers)
Why not `const` anymore?

2023-07-08 12:23 UTC, Kaffeine commented on src/game/editor/io.cpp
> +		for(CLayer *pLayer : pGroup->m_vpLayers)
No const because it is "fake" const which immediately casted away:
https://github.com/ddnet/ddnet/blob/4260d51dd9b1e31e278061d8c87422ca1115fc6d/src/game/editor/io.cpp#L195-L200

```cpp
for(const auto &pLayer : pGroup->m_vpLayers)
{
    if(pLayer->m_Type == LAYERTYPE_TILES)
    {
        CLayerTiles *pLayerTiles = (CLayerTiles *)pLayer;
        pLayerTiles->PrepareForSave();
        // ..
    }
    else if(pLayer->m_Type == LAYERTYPE_QUADS)
    {
        CLayerQuads *pLayerQuads = (CLayerQuads *)pLayer;
```

We can't make those layers const because we call modifying methods (e.g. `PrepareForSave()`)

2023-07-08 12:38 UTC, Kaffeine commented on src/game/client/components/menus.cpp
> +			const char *pPaused = g_Config.m_ClVideoPauseOnStart ? Localize("(paused)") : "";
Camera settings seems to be read from the demo file. For server-side demos the camera position is (0,0), for player side demos the camera is right where it was for the player. Oh, now I see, from a race PoV there is nothing interesting around the player, it is just their move.

But in some other multiplayer mods the actions of other players are very important. The player is doing their own task and use the camera for that, but from the replay point of view it can be much better to move the camera and get more or different players in frame. 

Pause is needed to adjust the camera before the first video frame rendered to the file. Otherwise a user need an external software just to cut the first seconds with camera positioning/zooming.

2023-07-08 12:43 UTC, Kaffeine commented on src/game/client/components/menus_demo.cpp
> +			}
Thanks, this is much better!

2023-07-08 12:45 UTC, Kaffeine commented on src/game/client/components/menus_demo.cpp
> +			}
[Fixed](https://github.com/ddnet/ddnet/compare/062dbc9e3ac9f5b74e1b3a46361829396b4e9ed6..5ba2a21528d4c76614268b255fb73d72a1ef6916) (a link to the diff between v1 and v2 in this MR)

2023-07-08 14:31 UTC, Robyt3 approved these changes

2023-07-08 15:04 UTC, def- approved these changes
bors r+

2023-07-08 15:22 UTC, merged

2023-08-19 06:41 UTC, Jupeyy commented
Any reason why `cl_video_pause_on_start` defaults to 1.. I find this a bad default to have to click "start rendering" twice before rendering again. Also this option should be in the HUD.
Can you provide a fix please @Kaffeine

2023-08-19 10:25 UTC, Kaffeine commented
Sure.