Selectable quadpoints
ddnet/ddnet pull request #6844
Opened 2023-07-13 17:39 UTC by Marmare314

Selecting multiple quadpoints is currently a lot of work because the hitbox is small and you have to select them one at a time. This PR allows using the box-selection on all quadpoints to make it easier. To make this possible (and consistent with other controls) a few other changes had to be made. In particular:
- Shift + click now selects another quad basepoint. Before it allowed moving them, which is now ctrl + click.
- Rotation is now bound to R.
- Copying quads now works through ctrl + c / ctrl + v.

I havent tested it very much yet. Because of this and since there has not been any discussion on this, I am submitting this as a draft.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-07-15 08:26 UTC, Robyt3 commented
I like it. Feels much easier to use then shift-clicking the points, where it's easy to miss.

2023-07-15 08:26 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +		m_pTooltip = "Left mouse button to move. Hold ctrl to move pivot. Hold alt to ignore grid. Hold shift and right click to delete.";
Should also mention new hotkey `R`.

2023-07-15 12:07 UTC, Marmare314 commented on src/game/editor/editor.cpp
> +		m_pTooltip = "Left mouse button to move. Hold ctrl to move pivot. Hold alt to ignore grid. Hold shift and right click to delete.";
Should `ctrl + c` and `ctrl + v` then also be mentioned? The status bar is quite full with this tooltip already.

2023-07-16 08:15 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +		m_pTooltip = "Left mouse button to move. Hold ctrl to move pivot. Hold alt to ignore grid. Hold shift and right click to delete.";
If it still fits, yeah. Otherwise we can leave it out and hope that those are common enough hotkeys so users will realise that they exist.

2023-07-16 09:01 UTC, Robyt3 requested changes
When you press R without having a quad pivot selected it just locks your mouse until you press a mouse button.

Can you also add the slow-moving mode to rotation? So when in rotate mode (after pressing R) you can hold shift at any point to rotate more slowly (for example multiply the speed by `0.05f` like in other places).

Just for understanding: Selecting multiple quad pivot points from the same quad layer was not supported before either, right? Would be cool to support this in the future, but you don't need to add it to this PR.

You can select multiple quad layers at the same time with shift+click which then allows you to select multiple quads/points from multiple layers. That feature still appears to be as buggy as before though, so I'm fine with this PR not making it any more or less buggy.

2023-07-16 09:22 UTC, Marmare314 commented
> Just for understanding: Selecting multiple quad pivot points from the same quad layer was not supported before either, right? Would be cool to support this in the future, but you don't need to add it to this PR.

I'm not sure why but `std::vector<int> m_vSelectedQuads;` was already a vector. I don't know how it was possible to select multiple quads, but thats why I allowed this. I can remove it again, but that would be more changes then just allowing multiple selection.

2023-07-16 09:45 UTC, Marmare314 commented on src/game/editor/editor.cpp
> +		m_pTooltip = "Left mouse button to move. Hold ctrl to move pivot. Hold alt to ignore grid. Hold shift and right click to delete.";
We could also add a copy entry to the context menu. Then it would at least still be possible to copy them without knowing the shortcut.

2023-07-16 10:25 UTC, Robyt3 commented
> I'm not sure why but std::vector<int> m_vSelectedQuads; was already a vector. I don't know how it was possible to select multiple quads, but thats why I allowed this. I can remove it again, but that would be more changes then just allowing multiple selection.

Ah, so selecting multiple quads should already work with this PR? It didn't work correctly for me when I tried it.

2023-07-16 12:08 UTC, Marmare314 commented
> Ah, so selecting multiple quads should already work with this PR? It didn't work correctly for me when I tried it.

I fixed it. At least for one layer it should now work.

2023-07-16 18:36 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +		m_pTooltip = "Left mouse button to move. Hold ctrl to move pivot. Hold alt to ignore grid. Hold shift and right click to delete.";
Yeah, that could work. The tooltip for the copy button could then explain both Ctrl+C and Ctrl+V hotkeys.

2023-07-17 18:02 UTC, Marmare314 commented on src/game/editor/editor.cpp
> +		m_pTooltip = "Left mouse button to move. Hold ctrl to move pivot. Hold alt to ignore grid. Hold shift and right click to delete.";
Or maybe this could fit in the default hovering tooltip for quad layers if it is reworded. I think that would be the best place for it. If a copy button is added there should also be a paste button, which would require a new contextmenu, which I am not sure I like.

2023-07-18 14:28 UTC, Marmare314 commented on src/game/editor/editor.cpp
> +		m_pTooltip = "Left mouse button to move. Hold ctrl to move pivot. Hold alt to ignore grid. Hold shift and right click to delete.";
I separated the tooltip for quad and tile layers and now it fits there easily.

2023-07-19 09:06 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +				m_pTooltip = "Hold shift to select multiple quads. Use ctrl + c and ctrl + v to copy and paste quads.";
Should probably include the hotkey R because you can use it in this context.

2023-07-19 09:09 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +				if(Input()->ModifierIsPressed())
Should be `ShiftIsPressed` because we use shift everywhere else for slow movement.

2023-07-19 09:16 UTC, Robyt3 commented
Looks good now. I you want, you can also squash the commits after addressing the two remaining comments above.

2023-07-19 09:48 UTC, Marmare314 commented on src/game/editor/editor.cpp
> +				if(Input()->ModifierIsPressed())
The envelope editor uses shift to select which direction a point is moved and ctrl for slow movement. The only other places with slow movement that I can think of are value selectors, which use shift. Im not sure which is better, but it should be consistent.

2023-07-19 09:49 UTC, Marmare314 commented on src/game/editor/editor.cpp
> +				m_pTooltip = "Hold shift to select multiple quads. Use ctrl + c and ctrl + v to copy and paste quads.";
It can then probably also be removed from the other tooltip.

2023-07-19 11:22 UTC, Marmare314 commented
Alright, should be done now.

2023-07-19 11:54 UTC, Robyt3 approved these changes
Thanks.

2023-07-19 12:17 UTC, merged