Multiple selection in envelope editor
ddnet/ddnet pull request #6872
Opened 2023-07-16 11:19 UTC by Marmare314

This PR allows multiple selection in the envelope editor and (because I am bad at separating features) adds a context menu to envelope points.

![env_context](https://github.com/ddnet/ddnet/assets/49279081/07dc5ab8-81ff-4db7-8cc6-ea513abec391)

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-07-16 11:41 UTC, Robyt3 commented
Seems like a good idea.

Though I'd prefer if #5737 gets merged first because this will conflict a lot.

2023-07-24 20:23 UTC, heinrich5991 commented
Status: Draft, needs rebase.

2023-07-26 08:09 UTC, Marmare314 commented
This also changes the behaviour of (shift +) right-click. Now it only resets the selected tangent point instead of all of the tangent points connected to the envelope point.
Also I allowed moving values outside the view again as I think its too restrictive with multiple selection. This could be replaced with edge-scrolling at some point.

2023-07-27 20:33 UTC, Robyt3 requested changes
Some spacing should be added after the labels in the value/time popup and the popup could also be a bit larger.

The popup could maybe also have a title like `Point #4` or `Point #5 Out-Tangent`.

The values in the editboxes of the bezier tangent popups are not updated when clicking the reset button.

I find having to right click for contexts menu sometimes makes me accidentally add a point when missing. Maybe new points should be added with double-click instead to prevent this.

I don't really like how the selected envelope points look: 
![img](https://github.com/ddnet/ddnet/assets/23437060/72fb94cf-692f-4d67-9c9e-0b1788eb6fe8)

I'd prefer if the highlight color was always covering the original envelope point. Normally the hot (hovered) UI elements have a slightly brighter highlight color than the active (clicked/selected) elements.

2023-07-27 20:33 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +	if(pEditor->DoButton_Editor(&s_DeleteButtonID, pButtonText, 0, &Row, IGraphics::CORNER_ALL, pTooltip))
You are passing a corner constant as buttons flags (which are currently mostly unused), pass `0` instead.

2023-07-27 20:33 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +float ClampDelta(float val, float delta, float min, float max)
Variable names with upper case initial.

Make the function `static`.

2023-07-27 20:33 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +	for(int c = 0; c < 4; c++)
Use `CEnvPoint::MAX_CHANNELS` instead of `4` here

2023-07-27 21:13 UTC, Marmare314 commented
> I find having to right click for contexts menu sometimes makes me accidentally add a point when missing. Maybe new points should be added with double-click instead to prevent this.

This would become less likely with #6867. However then you can't add points near other points. But double-click also seems more intuitive for me.

> I don't really like how the selected envelope points look

I don't either, but I tried to keep the same style as quadpoints, I only made the border white because of the background.
(Also maybe the border is a bit bigger which should be changed)

> I'd prefer if the highlight color was always covering the original envelope point. Normally the hot (hovered) UI elements have a slightly brighter highlight color than the active (clicked/selected) elements.

I'm not really sure what you want the points to look like. In #6867 there was originally also a redesign of quadpoints. Maybe you mean something along those lines?

2023-07-27 21:45 UTC, Robyt3 commented
> I'm not really sure what you want the points to look like. In https://github.com/ddnet/ddnet/pull/6867 there was originally also a redesign of quadpoints. Maybe you mean something along those lines?

Yeah, I like that redesign. I think circles also fit better for points.

2023-07-28 04:57 UTC, Marmare314 commented
So maybe we could just leave the selection design as it is for this PR and I will create a PR redesigning all points after this.

> The popup could maybe also have a title like `Point #4` or `Point #5 Out-Tangent`.

I'm not sure I like that since it adds no useful information, so I did not add it yet.

> Some spacing should be added after the labels in the value/time popup and the popup could also be a bit larger.

It now fits values up to `-100000.000` which I think should be enough.

2023-07-28 09:47 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +							m_pTooltip = "Envelope point. Left mouse to drag. Hold ctrl to be more precise. Hold shift to alter time point as well. Right click + shift to delete.";
`Right click + shift` --> `Shift + Right click`

Remove `point as well` because shift makes you only alter the time and not time and value at the same time.

Add `ms_pUiGotContext = pID;` after this line. This will add `Right click for context menu.` after the tooltip automatically and change the mouse cursor color when a context menu is available.

2023-07-28 09:48 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +								m_pTooltip = "Bezier out-tangent. Left mouse to drag. Hold ctrl to be more precise. Shift + Right click to reset.";
Also add `ms_pUiGotContext = pID;`

2023-07-28 09:48 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +								m_pTooltip = "Bezier in-tangent. Left mouse to drag. Hold ctrl to be more precise. Shift + Right click to reset.";
Also add `ms_pUiGotContext = pID;`

2023-07-28 09:51 UTC, Robyt3 commented
Looks good otherwise, you can also squash the commits.

2023-07-28 10:43 UTC, Marmare314 commented
I also changed the envelope tooltip to mention double-clicking to create new points instead of right-clicking.

2023-07-28 11:10 UTC, Robyt3 approved these changes
Thanks.

2023-07-28 11:37 UTC, merged