Support master server address format in client
ddnet/ddnet pull request #6876
Opened 2023-07-16 12:17 UTC by ChillerDragon

Support master server address format in client
    
This still works

```    
$ ./DDNet "connect 127.0.0.1"
```
    
But now also this works

```
$ ./DDNet "connect tw-0.6+udp://ger10.ddnet.org:8303"
2023-07-16 14:07:50 I engine: running on unix-linux-amd64
2023-07-16 14:07:50 I client: starting...
2023-07-16 14:07:50 I client: version 17.1.1 on linux amd64
2023-07-16 14:07:50 I client: git revision hash: 7f100e262032b50d
2023-07-16 14:07:50 I client: connecting to 'tw-0.6+udp://ger10.ddnet.org:8303'
2023-07-16 14:07:50 I host_lookup: host='ger10.ddnet.org' port=8303 3
2023-07-16 14:07:51 I client: connected, sending info
```

This string still needs a catchy name. I called it "rich" format but that doesn't seem too optimal.
Also not too sure if the ``tw_protocol`` field in ``struct NETADDR`` should really be a string.

```C++
typedef struct NETADDR
{
	unsigned int type;
	unsigned char ip[16];
	unsigned short port;
	char tw_protocol[4];

	bool operator==(const NETADDR &other) const;
	bool operator!=(const NETADDR &other) const { return !(*this == other); }
} NETADDR;
```

It could also be a ``char`` and hold the digit ``6`` or ``7``. That would work fine if the rich format is only ever used to differentiate between teeworlds 0.7 and 0.6 maybe even 0.8 and 0.9. But it would not support ``tw-ddnet2+udp://127.0.0.1``

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [x] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-07-16 12:25 UTC, def- approved these changes
Good idea

2023-07-16 12:25 UTC, heinrich5991 commented
Generally in favor, would have planned implementing something like this myself.

Just thinking out loud, not a suggestion: Perhaps this could go into the flags field? Does it clash with anything there?

> This string still needs a catchy name. I called it "rich" format but that doesn't seem too optimal.

It's a [URL](https://en.wikipedia.org/wiki/URL). ;)

Given that it's a URL, it should probably support the URL format. This is probably not entirely trivial though. We should probably talk about that before you implement it.

2023-07-16 12:30 UTC, Chairn commented on src/base/system.h
> +int net_addr_from_rich_str(NETADDR *addr, const char *string);
maybe return some enum instead of numbers, that would make code more readable

2023-07-16 12:33 UTC, ChillerDragon commented on src/base/system.h
> +int net_addr_from_rich_str(NETADDR *addr, const char *string);
thats not very system.h style is it?

2023-07-16 13:04 UTC, ChillerDragon commented
> Given that it's a URL, it should probably support the URL format. This is probably not entirely trivial though. We should probably talk about that before you implement it.

Are you saying I should not use the name url unless its implementing the whole url spec. Or are you saying you are against a merge unless it is conforming to the whole url spec? If you really say that the ddnet connection string should support the full url format I would be curious why. Is it to be forward compatible to properly ignore for example query parameters if we decide to use those? Rolling a self made implementation sounds like work and even possible security flaws. One could use a rust crate that parses urls since we have the infrastructure for adding rust crates already. But in my opinion both solutions are adding useless complexity while my simple 10 lines of code do properly parse the formats that we need.

2023-07-16 13:08 UTC, heinrich5991 commented
> Is it to be forward compatible to properly ignore for example query parameters if we decide to use those?

Yes, basically that. Actually, I think we already have an implementation that does that, we need to. We're consuming the data from the HTTPS masterserver. ^^ You could probably just move this function around.

2023-07-16 17:05 UTC, ChillerDragon commented
Oki yoinked your code into system.cpp

2023-07-22 10:58 UTC, ChillerDragon commented
Switched out ``char tw_protocol[6];`` with just ``char tw_protocol;`` to bloat less bytes into ram.

Using this enum instead of the string values ``"0.6"`` and ``"0.7"``

```c++
enum {
	PROTOCOL_TW6 = 6,
	PROTOCOL_TW7 = 7,
};
```

2023-07-23 10:12 UTC, ChillerDragon commented
Anything blocking the merge?

2023-07-23 20:16 UTC, def- approved these changes

2023-07-23 20:20 UTC, heinrich5991 commented
Sorry, I'm also currently reviewing and I have comments. :(

2023-07-23 20:32 UTC, heinrich5991 requested changes
Looks good generally, I left some comments on what needs changing.

2023-07-23 20:32 UTC, heinrich5991 commented on src/base/system.cpp
> +	str += 6;
I do not see code quality improvements over the old function. Could you take the old code? It didn't involve manual index shuffling.

`str_startswith(…, "tw-0.6+udp://")` is also easier to read, and easier to grep for. It doesn't stand in the way of adding 0.7 support either, one can simply add a `str_startswith(…, "tw-0.7+udp")` in that case.

2023-07-23 20:32 UTC, heinrich5991 commented on src/base/system.cpp
> +	int tw_protocol;
Inconsistent style for the variable names, should probably all be lowercase.

2023-07-23 20:32 UTC, heinrich5991 commented on src/base/system.h
> +
Should be removed until we support more protocols.

2023-07-23 20:32 UTC, heinrich5991 commented on src/base/system.h
> +	char tw_protocol;
Should probably go into the type instead, but should be removed until we need more than one type.

2023-07-23 20:32 UTC, heinrich5991 commented on src/base/system.h
> + * The url format is tw-{teeworlds_protocol}+{internet_protocol}://{ipaddr}[:{port}]
```suggestion
 * The url format is tw-0.6+udp://{ipaddr}[:{port}]
```

2023-07-23 20:32 UTC, heinrich5991 commented on src/engine/client/client.cpp
> +			str_copy(aHost, aBuffer + 13);
This is a random offset, this shouldn't be here.

2023-07-23 20:32 UTC, heinrich5991 commented on src/engine/client/client.cpp
> +		char tw_protocol;
Can be removed for now.

2023-07-23 20:32 UTC, heinrich5991 commented on src/engine/client/serverbrowser_http.cpp
> +	return net_addr_from_url(pOut, pUrl) != 0;
Can you add a comment to `net_addr_from_url` implementation that one should consider that the function is also used for masterserver communication and should be changed with care?

2023-07-27 08:10 UTC, ChillerDragon commented
Status: waiting for heinrich :trollface:

2023-07-27 08:31 UTC, heinrich5991 reviewed
Some more nits.

2023-07-27 08:31 UTC, heinrich5991 commented on src/test/netaddr.cpp
> +	EXPECT_EQ(net_addr_from_url(&Addr, "127.0.0.1", nullptr, 0), -2); // not rich format
```suggestion
	EXPECT_EQ(net_addr_from_url(&Addr, "127.0.0.1", nullptr, 0), -2); // not a URL
```

2023-07-27 08:31 UTC, heinrich5991 commented on src/base/system.h
> + * This format is used by the ddnet master server.
```suggestion
 * This format is used for parsing the master server, be careful before changing it.
```

2023-07-27 08:31 UTC, heinrich5991 commented on src/base/system.h
> + * @param pHost	buffer to write the host to (including the port if given)
Please note that `host` is allowed to be `nullptr` and say what `host_size` you should set in this case.

2023-07-27 08:31 UTC, heinrich5991 commented on src/base/system.cpp
> +	char aHost[128];
```suggestion
	char host[128];
```

2023-07-27 08:31 UTC, heinrich5991 commented on src/base/system.h
> + * @return 0 on success
Since you rely on `-1` as a return value, it should be documented. Perhaps switch to `1` if the address can't be parsed and `<0` if there's another error. This way, you can also return an error if the address can't be parsed, but no host buffer has been passed in.

2023-07-27 10:59 UTC, ChillerDragon commented
done :)

2023-08-04 10:32 UTC, ChillerDragon commented
Improved return code documentation as suggested by mr 5991 on irc.

2023-08-05 08:49 UTC, heinrich5991 approved these changes
Thanks!

2023-08-05 09:14 UTC, merged