Add grid to envelope editor
ddnet/ddnet pull request #6923
Opened 2023-07-26 13:14 UTC by Marmare314

![zoom_grid](https://github.com/ddnet/ddnet/assets/49279081/e197be7f-0eb5-4386-a8c0-947e3d8a4513)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-07-26 14:44 UTC, Robyt3 requested changes
Very nice feature.

Visually, there should be a bit more padding between the grid and the axis labels. Or maybe it's possible to draw a background behind the axis labels and draw them directy centered above the grid lines.

2023-07-26 14:44 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +			enum ETimeUnit
Can this be refactored using `std::literals::chrono_literals`?

2023-07-26 14:49 UTC, Robyt3 commented
Axis labels can be too close together when zoomed out very far (see screenshot and test map in #6926).

2023-07-26 17:14 UTC, Marmare314 commented
> Or maybe it's possible to draw a background behind the axis labels and draw them directy centered above the grid lines.

If this would mean taking away space from the editor itself I am against it.

> Visually, there should be a bit more padding between the grid and the axis labels.

Do you mean both the left and bottom labels? On the left I definitely agree. The bottom labels look ok to me, but I can increase the spacing anyway.

> Axis labels can be too close together when zoomed out very far

I will fix the other issue but within the zoom constraints it should work fine.

2023-07-26 17:48 UTC, Robyt3 commented
> Do you mean both the left and bottom labels? On the left I definitely agree. The bottom labels look ok to me, but I can increase the spacing anyway.

Yeah, left side needs more spacing. Bottom is okay but maybe it would also look better with one more pixel spacing.

2023-07-26 21:58 UTC, Marmare314 commented on src/game/editor/editor.cpp
> +			enum ETimeUnit
The problem is that I need to know what the original unit was. So yes it is possible but makes the `TimeStep` class more complicated (it would need a templated constructor + some constexpr if checks). Maybe I am just missing what you are suggesting though.

2023-07-26 22:53 UTC, Marmare314 commented on src/game/editor/editor.cpp
> +			enum ETimeUnit
I updated the code. It was still a lot better than the old implementation.

2023-07-27 20:39 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +class TimeStep
`CTimeStep`

2023-07-27 20:40 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +	void format(char *pBuffer, int BufferSize)
`Format`

`size_t` for `BufferSize`

2023-07-27 20:40 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +	TimeStep operator-(const TimeStep &other)
`Other`

2023-07-27 20:41 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +	float as_seconds() const
`AsSeconds`

2023-07-27 20:44 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +			float UnitPerLineOptionsY[] = {0.005f, 0.01f, 0.025f, 0.05f, 0.1f, 0.25f, 0.5f, 1.0f, 2.0f, 4.0f, 8.0f, 16.0f, 32.0f, 2 * 32.0f, 5 * 32.0f, 10 * 32.0f, 20 * 32.0f, 50 * 32.0f, 100 * 32.0f};
`static const float s_aUnitPerLineOptionsY[] = ...`

2023-07-27 20:45 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +			TimeStep UnitPerLineOptionsX[] = {5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1s, 2s, 5s, 10s, 15s, 30s, 1min};
`static const CTimeStep UnitPerLineOptionsX[] = ...`

(I'm not entirely sure if it will compile like that or if you need to make the `CTimeStep` constructor `constexpr` if that's possible.)

2023-07-28 09:55 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +			static const float UnitPerLineOptionsY[] = {0.005f, 0.01f, 0.025f, 0.05f, 0.1f, 0.25f, 0.5f, 1.0f, 2.0f, 4.0f, 8.0f, 16.0f, 32.0f, 2 * 32.0f, 5 * 32.0f, 10 * 32.0f, 20 * 32.0f, 50 * 32.0f, 100 * 3
`s_aUnitPerLineOptionsY`

2023-07-28 09:55 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +			static const CTimeStep UnitPerLineOptionsX[] = {5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1s, 2s, 5s, 10s, 15s, 30s, 1min};
`s_aUnitPerLineOptionsX`

2023-07-28 10:23 UTC, Marmare314 commented on src/game/editor/editor.cpp
> +			static const float UnitPerLineOptionsY[] = {0.005f, 0.01f, 0.025f, 0.05f, 0.1f, 0.25f, 0.5f, 1.0f, 2.0f, 4.0f, 8.0f, 16.0f, 32.0f, 2 * 32.0f, 5 * 32.0f, 10 * 32.0f, 20 * 32.0f, 50 * 32.0f, 100 * 3
Not sure I will ever get used to the naming conventions

2023-07-28 14:11 UTC, Robyt3 commented
Unfortunately it conflicts now. Can you rebase on master again?

2023-07-28 14:25 UTC, Marmare314 commented
Done.

2023-07-28 14:35 UTC, Robyt3 approved these changes
Thanks.

2023-07-28 15:05 UTC, merged