Add pixelart tool to editor
ddnet/ddnet pull request #7002
Opened 2023-08-12 10:30 UTC by Marmare314

Generate tilelayers and color maps from an image. This could be useful for all sorts of things from importing shapes like circles to creating maps like pokemon gen 1. For each 255 colors one color map and layer is generated and the tiles are set accordingly.

![screenshot_2023-08-12_12-25-34](https://github.com/ddnet/ddnet/assets/49279081/e86f4618-0141-4d44-b461-dd1efdb5c92e)
![screenshot_2023-08-12_12-11-44](https://github.com/ddnet/ddnet/assets/49279081/c7dc7374-abd3-4658-a7cf-5770836f8d61)

Maybe some warnings should be added if the image is big or there are many colors.

## Checklist

- [ ] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-08-12 11:49 UTC, Marmare314 commented
Maybe this could be named 'Tileart' instead to make it clearer what it does.

2023-08-12 12:27 UTC, Robyt3 commented on src/game/editor/pixelart.cpp
> +	std::vector<CColorRGBAInt> UniqueColors;
`vUniqueColors`

2023-08-12 12:27 UTC, Robyt3 commented on src/game/editor/pixelart.cpp
> +	std::vector<std::array<CColorRGBAInt, NumTiles>> ColorGroups;
`vColorGroups`

2023-08-12 12:27 UTC, Robyt3 commented on src/game/editor/pixelart.cpp
> +		pEditor->ShowFileDialogError("Only RGB and RGBA PNG images are supported");
`.` at the end of the error message

2023-08-12 16:18 UTC, Robyt3 commented
Declare the local functions in `pixelart.cpp` as `static` to ensure that they have internal linkage only.

2023-08-16 17:57 UTC, Robyt3 requested changes

2023-08-16 20:52 UTC, Marmare314 commented on src/game/editor/tileart.cpp
> +struct CColorRGBAInt
Yes thats definitely possible, I looked for that type but didn't find it. The access operator is not used anymore, I forgot to remove it. I will check if there is any easy way for `std::set` to use `ivec4::length` or something similar. Then the other operator could also be avoided.

2023-08-16 21:10 UTC, Marmare314 commented on src/game/editor/tileart.cpp
> +struct CColorRGBAInt
Nevermind, the ordering needs to be antisymmetric. But I simplified the comparison operator a bit.

2023-08-17 18:10 UTC, Robyt3 commented on src/game/editor/tileart.cpp
> +		str_format(aImageName, sizeof(aImageName), "%s %zu", m_aTileartFilename, i + 1);
Replace `"%s %zu"` with `"%s %" PRIzu` to fix this warning when using MinGW:

```
  180 |                 str_format(aImageName, sizeof(aImageName), "%s %zu", m_aTileartFilename, i + 1);
      |                                                                 ^
src/game/editor/tileart.cpp:180:60: warning: too many arguments for format [-Wformat-extra-args]
  180 |                 str_format(aImageName, sizeof(aImageName), "%s %zu", m_aTileartFilename, i + 1);
      |                                                            ^~~~~~~~
```

2023-08-17 18:16 UTC, Robyt3 commented
The client crashes when trying to create a pixelart for an image of non-square dimensions (for example with both 1021x1021 and 78x53):

```
DDNet.exe caused an Access Violation at location 00007FF6F1195C9F in module DDNet.exe Reading from location 000001893E0FF058.

AddrPC           Params
00007FF6F1195C9F 00000005739BC510 00000189326903E8 0000000500000000  DDNet.exe!GetPixelColor+0x92  [src/game/editor/tileart.cpp @ 24]
    22: 
    23: ivec4 Color;
>   24: Color.r = pData[PixelStartIndex + 0];
    25: Color.g = pData[PixelStartIndex + 1];
    26: Color.b = pData[PixelStartIndex + 2];
00007FF6F1196638 00000005739BC5E0 0000000000000000 0000000000000000  DDNet.exe!SetTilelayerIndices+0x5d  [src/game/editor/tileart.cpp @ 165]
   163: {
   164: for(int y = 0; y < pLayer->m_Height; y++)
>  165: pLayer->m_pTiles[x + y * pLayer->m_Width].m_Index = GetColorIndex(aColorGroup, GetPixelColor(Image, x, y));
   166: }
   167: }
00007FF6F1196831 000001893268FF70 000001893268E460 0000000000000000  DDNet.exe!CEditor::AddTileart+0x13f  [src/game/editor/tileart.cpp @ 182]
   180: str_format(aImageName, sizeof(aImageName), "%s %" PRIzu, m_aTileartFilename, i + 1);
   181: std::shared_ptr<CLayerTiles> pLayer = AddLayerWithImage(this, pGroup, vColorImages[i], aImageName);
>  182: SetTilelayerIndices(pLayer, vaColorGroups[i], m_TileartImageInfo);
   183: }
   184: SortImages();
00007FF6F1196A1C 00000005739BC960 B1E3BCFB42DC0000 00000005739BC960  DDNet.exe!CEditor::TileartCheckColors+0x11e  [src/game/editor/tileart.cpp @ 209]
   207: }
   208: else
>  209: AddTileart();
   210: }
   211: 
00007FF6F118FFAE 00000005739BCA10 00007FF640800000 00000005739BCA01  DDNet.exe!CEditor::PopupEvent+0x6b8  [src/game/editor/popups.cpp @ 1864]
  1862: else if(pEditor->m_PopupEventType == POPEVENT_PIXELART_BIG_IMAGE)
  1863: {
> 1864: pEditor->TileartCheckColors();
  1865: }
  1866: else if(pEditor->m_PopupEventType == POPEVENT_PIXELART_MANY_COLORS)
00007FF6F10E8DF6 000001893268E460 00007FF6F157C41C 00000005739BCB10  DDNet.exe!CUI::RenderPopupMenus+0x232  [src/game/client/ui.cpp @ 1336]
  1334: PopupRect.Margin(SPopupMenu::POPUP_MARGIN, &PopupRect);
  1335: 
> 1336: EPopupMenuFunctionResult Result = PopupMenu.m_pfnFunc(PopupMenu.m_pContext, PopupRect, Active);
  1337: if(Result != POPUP_KEEP_OPEN || (Active && ConsumeHotkey(HOTKEY_ESCAPE)))
  1338: ClosePopupMenu(PopupMenu.m_pID, Result == POPUP_CLOSE_CURRENT_AND_DESCENDANTS);
00007FF6F1128868 000001893268E4D0 00007FF6441FB8E3 0000000543AD0E39  DDNet.exe!CEditor::Render+0x1278  [src/game/editor/editor.cpp @ 7627]
  7625: MapView()->UpdateZoom();
  7626: 
> 7627: UI()->RenderPopupMenus();
  7628: FreeDynamicPopupMenus();
  7629: 
00007FF6F112BA8E 000001893268E460 0000000543622AE7 000000053F800000  DDNet.exe!CEditor::OnRender+0x1cc  [src/game/editor/editor.cpp @ 8269]
  8267: UI()->Update(m_MouseX, m_MouseY, m_MouseDeltaX, m_MouseDeltaY, m_MouseWorldX, m_MouseWorldY);
  8268: 
> 8269: Render();
  8270: 
  8271: m_MouseDeltaX = 0.0f;
00007FF6F0F15435 00000005739BF158 00000005739BF158 00000005739BF083  DDNet.exe!CClient::Run+0x12cf  [src/engine/client/client.cpp @ 3293]
  3291: else
  3292: {
> 3293: m_pEditor->OnRender();
  3294: DebugRender();
  3295: }
00007FF6F0F1E782 0000000000000001 0000000000000006 00007FF6F15CE458  DDNet.exe!main+0x1164  [src/engine/client/client.cpp @ 4820]
  4818: // run the client
  4819: dbg_msg("client", "starting...");
> 4820: pClient->Run();
  4821: 
  4822: const bool Restarting = pClient->State() == CClient::STATE_RESTARTING;
```

2023-08-17 20:21 UTC, Marmare314 commented
Somehow it did not crash for me even in debug mode. But I think it should be fixed now (I used the dimensions of the color images instead of the reference image).

2023-08-17 20:36 UTC, Marmare314 commented
I just noticed that the only excluded image format is `CImageInfo::FORMAT_SINGLE_COMPONENT` which I think are just gray-scale images. Support for those should also probably be added for completeness since its only a small change.

2023-08-17 23:38 UTC, heinrich5991 commented
Here's a blog post for doing the same thing in fewer layers btw: https://patiga.eu/blog/ddnet-pixelart.

2023-08-27 10:22 UTC, Marmare314 commented
> Here's a blog post for doing the same thing in fewer layers btw: https://patiga.eu/blog/ddnet-pixelart.

Unfortunately it does not really work for RGBA images and it only takes less layers for images with more than 3 * 255 colors. Would be cool to add this for RGB images (or even images with only 0 and 255 as alpha values) with many colors, but I'm not up for that right now.

2023-08-27 18:42 UTC, Robyt3 approved these changes
LGTM!

2023-08-27 19:02 UTC, merged