Add `CProofMode` and `CMapGrid` component
ddnet/ddnet pull request #7017
Opened 2023-08-14 15:03 UTC by Marmare314

Also extract more code into `CMapView` and extend the `CEditorComponent` interface.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-08-20 10:39 UTC, Robyt3 requested changes

2023-08-20 10:39 UTC, Robyt3 commented on src/game/editor/map_grid.cpp
> +		float h = UI()->Screen()->h;
Would be more readable to use only `const CUIRect *pScreen = UI()->Screen()` instead of `w` and `h`.

2023-08-20 10:39 UTC, Robyt3 commented on src/game/editor/map_view.cpp
> +				IGraphics::CLineItem Array[4] = {
`aArray`

2023-08-20 10:39 UTC, Robyt3 commented on src/game/editor/map_view.cpp
> +				Graphics()->LinesDraw(Array, 4);
`std::size(aArray)` instead of `4`

2023-08-20 10:39 UTC, Robyt3 commented on src/game/editor/map_view.cpp
> +	std::shared_ptr<CLayerTiles> pT = std::static_pointer_cast<CLayerTiles>(Editor()->GetSelectedLayerType(0, LAYERTYPE_TILES));
`pT` to `pSelectedTilesLayer`

2023-08-20 10:39 UTC, Robyt3 commented on src/game/editor/proof_mode.cpp
> +				Graphics()->LinesDraw(Array, 2);
`aArray` and `std::size`

2023-08-20 10:39 UTC, Robyt3 commented on src/game/editor/proof_mode.cpp
> +				Graphics()->LinesDraw(Array, 4);
`aArray` and `std::size`

2023-08-20 10:39 UTC, Robyt3 commented on src/game/editor/proof_mode.cpp
> +				Graphics()->LinesDraw(Array, 2);
`aArray` and `std::size`

2023-08-20 10:39 UTC, Robyt3 commented on src/game/editor/proof_mode.cpp
> +				Graphics()->LinesDraw(Array, 4);
`aArray` and `std::size`

2023-08-20 10:39 UTC, Robyt3 commented on src/game/editor/proof_mode.cpp
> +				std::set<int> indices;
`Indices`

2023-08-20 10:39 UTC, Robyt3 commented on src/game/editor/proof_mode.h
> +public:
As much as possible should be `private`. Add getters and setters to expose just what's necessary.

2023-08-20 10:39 UTC, Robyt3 commented on src/game/editor/component.cpp
>  void CEditorComponent::OnInput() {}
Should eventually accept an argument `const IInput::CEvent &Event` and return `true` if the event was consumed or `false` if other systems are still allowed to use it.

2023-08-20 10:39 UTC, Robyt3 commented on src/game/editor/map_view.h
> +	CMapGrid m_MapGrid;
Maybe it's better if we immediately encapsulate all members of the new components, e.g. `CProofMode *ProofMode() { ... }`.

The other `CMapView` members should also be `private` if possible, but you can also do that in another PR.

2023-08-20 11:47 UTC, Marmare314 commented on src/game/editor/map_grid.cpp
> +		float h = UI()->Screen()->h;
Since I only copied this code it might be better to make all these refactorings a seperate PR.

2023-08-20 13:07 UTC, Robyt3 commented on src/game/editor/map_grid.cpp
> +		float h = UI()->Screen()->h;
Yeah, makes sense.

2023-08-20 17:09 UTC, Marmare314 commented on src/game/editor/component.cpp
>  void CEditorComponent::OnInput() {}
I hope I'm not missing anything but I think this could already be done and won't lead to many issues in the refactoring. Then there would also be a mechanism to call the `OnInput` functions, like for `CComponent`. In `CComponent` there is just one big list in `CClient` for all components, but I think it would be nicer if each `CEditorComponent` could have subcomponents. It would probably be nice to have some `RegisterComponent` function as part of `CEditorInterface` to register subcomponents. These could be stored in a vector, but I'm not sure if that might be too inefficient (I was planning on making even envelope points  and operations like panning `CEditorComponent`s). So maybe there should be a subclass of `CEditorComponent`which adds this functionality.

2023-08-25 09:22 UTC, Marmare314 commented on src/game/editor/proof_mode.h
> +public:
Making them private requires moving the proof position selection code to be moved into the class which is still a big refactoring. But I added getters/setters so that they can be made private once that refactoring is done.

2023-08-25 10:32 UTC, Marmare314 commented on src/game/editor/component.cpp
>  void CEditorComponent::OnInput() {}
I added the subcomponent vector to all components for now, if it turns out that this is too much overhead this can still easily be done later.

2023-08-25 10:33 UTC, Marmare314 commented
I think I should have addressed everything now.

2023-08-26 08:54 UTC, Robyt3 approved these changes
Looks good, thanks!

2023-08-26 09:14 UTC, merged

2023-08-26 10:01 UTC, ChillerDragon commented
The api is non obvious for me. It is called ``GetWorldOffset`` to get the worldoffset but just ``WorldZoom`` to get the worldzoom

2023-08-26 14:58 UTC, Marmare314 commented
> The api is non obvious for me. It is called `GetWorldOffset()` to get the worldoffset but just `WorldZoom()` to get the worldzoom

You're right, I will fix this in one of the follow-up PRs.