Update ukrainian.txt
ddnet/ddnet pull request #7035
Opened 2023-08-16 14:58 UTC by StormAxs

Updated ukranian for 17.2

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-08-16 15:07 UTC, Robyt3 commented on data/languages/ukrainian.txt
> +== Неможливо видалити папку '%s'. Впевніться що папка пуста
`.` at the end

2023-08-16 15:07 UTC, Robyt3 commented on data/languages/ukrainian.txt
> +== Дефо-файл з таким іменем вже існує
Remove space at the end.

2023-08-16 16:44 UTC, Possseidon requested changes

2023-08-16 16:44 UTC, Possseidon commented on data/languages/ukrainian.txt
> +== Закриваєму гру. Будь-ласка зачекайте<3
Sneaky little heart `<3` lol

2023-08-16 16:44 UTC, Possseidon commented on data/languages/ukrainian.txt
> +== Дефо-файл з таким іменем вже існує
I'm not Ukrainian, but google translate/deepl spit out "defo"/"dafoe"/"defoe" instead of "demo" when translated back to english. Typo?

Edit: Yeah, very likely typo, further down there's another instance of "demo" that is translated correctly; the first `ф` should be `м`.

2023-08-20 10:17 UTC, Robyt3 commented
Superseded by #7043.

2023-08-20 10:17 UTC, closed without merging