Add warning for unsaved editor changes when dragging a map file into the game
ddnet/ddnet pull request #7076
Opened 2023-08-26 16:33 UTC by dobrykafe

Closes #7011 

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-08-26 18:36 UTC, def- requested changes

2023-08-26 18:36 UTC, def- commented on src/engine/client/client.cpp
> -				dbg_msg("editor", "editing passed map file '%s' failed", m_aCmdEditMap);
Why was this removed?

2023-08-26 20:12 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +			}
This duplicate code should be avoided. `if(pEditor->m_PopupEventType == POPEVENT_LOADDROP)` should be inside the `if` for the button.

2023-08-28 13:49 UTC, def- approved these changes

2023-08-28 14:34 UTC, merged

2023-08-28 15:44 UTC, Marmare314 commented on src/game/editor/io.cpp
> +	return m_Map.HandleMapDrop(pFileName, IStorage::TYPE_ALL_OR_ABSOLUTE);
Is there any reason that the popup is not handled directly here? For me it would make more sense to handle popups in `CEditor` instead of `CEditorMap`.