Fix some `CLocConstString`s being localized twice
ddnet/ddnet pull request #7103
Opened 2023-08-29 19:57 UTC by Robyt3

Column and key names are stored as `CLocConstString`s, which automatically return the localized string with the operator `const char *()`. Calling `Localize` manually for these is unnecessary.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-08-29 20:35 UTC, def- approved these changes

2023-08-29 20:36 UTC, def- requested changes

2023-08-29 20:36 UTC, def- commented on src/game/client/components/menus_browser.cpp
> +		if(DoButton_GridHeader(s_aCols[i].m_Caption, s_aCols[i].m_Caption, Checked, &s_aCols[i].m_Rect))
Actually, if the static variable is containing localized text, how does that work when you change the language? I think we should call Localize here instead of in static variables.

2023-08-30 15:15 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +		if(DoButton_GridHeader(s_aCols[i].m_Caption, s_aCols[i].m_Caption, Checked, &s_aCols[i].m_Rect))
Each `CLocConstString` remembers the localization version and if it's different than the previous one then the localized string is reloaded, so it should be fine.

At least that's what I was going to write, but it seems that `CLocConstString` actually has an uninitialized member variable `m_ContextHash` so strings with context would not be handled correctly. I suppose we can also get rid of it, as this class violates the principle of least astonishment.

2023-08-30 15:53 UTC, closed without merging

2023-08-30 16:00 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +		if(DoButton_GridHeader(s_aCols[i].m_Caption, s_aCols[i].m_Caption, Checked, &s_aCols[i].m_Rect))
See #7109