Add restart button for when game needs to restart to apply settings
ddnet/ddnet pull request #7105
Opened 2023-08-29 21:11 UTC by dobrykafe

In addition to the warning message a button will be shown allowing for easy restart.

![restart-button-1](https://github.com/ddnet/ddnet/assets/121701317/4926e63d-4758-4d89-a7bf-2503a69c27a3)
![restart-button-2](https://github.com/ddnet/ddnet/assets/121701317/aecabf72-ae59-4fde-b9a4-dc3eb3fa74f5)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-08-29 21:45 UTC, def- commented
I'm slightly afraid that some people might not understand that "Restart" implies that they lose the progress of their ongoing game.

2023-09-06 16:10 UTC, Robyt3 commented on src/game/client/components/menus.cpp
>  			pExtraText = Localize("Are you sure that you want to quit?");
Or maybe only change the title, since the message `"There's an unsaved map in the editor, you might want to save it before you quit the game."` says "quit" anyway.

2023-09-23 09:01 UTC, Robyt3 requested changes

2023-09-23 09:01 UTC, Robyt3 commented on src/game/client/components/menus.cpp
> +					str_format(aBuf, sizeof(aBuf), "%s\n%s", Localize("There's an unsaved map in the editor, you might want to save it before you quit the game."), Localize("Quit anyway?"));
Maybe we could only use one string `"There's an unsaved map in the editor, you might want to save it."` instead of having two very long almost identical strings.

Other opinions?

2023-11-18 22:27 UTC, heinrich5991 commented
Status: Unaddressed review comments.

2023-12-28 21:26 UTC, dobrykafe commented
Sorry for the long delay on this!

2023-12-28 22:24 UTC, def- approved these changes
Thanks

2023-12-28 22:41 UTC, merged