Remove core reset in Init (fix #7170)
ddnet/ddnet pull request #7171
Opened 2023-09-12 12:16 UTC by 0xfaulty

Fix for [#7170](https://github.com/ddnet/ddnet/issues/7170)
Reset is not needed in core init, as it already reset before each init except reckoning.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-09-12 12:19 UTC, Kaffeine commented
(Reference: [teeworlds:src/game/gamecore.cpp](https://github.com/teeworlds/teeworlds/blob/a1911c8f7d8458fb4076ef8e7651e8ef5e91ab3e/src/game/gamecore.cpp#L69))

2023-09-12 18:27 UTC, Kaffeine commented
Note: the prediction must match that of the client side. E.g. if we added or add anything to the server which changes physics, then the previous client versions (without according changes) won't receive reckoning core and can get out of sync.

It turned out that in my mod I can't "fix" reckoning core because I have a call to [`CCharacter::ResetInput()`](https://github.com/ddnet/ddnet/blob/1bc250ba084b1d4e218213fa209d0d33ce2b8f2b/src/game/server/entities/character.cpp#L705) which affects the reckoning core and puts clients out of sync.

DDNet does not call this method (at all), so probably it is safe to apply the changes.

2023-09-20 07:37 UTC, edg-l commented
What are the implications of this regarding physics? Do we break any maps with this.

2023-09-20 08:42 UTC, 0xfaulty commented
> What are the implications of this regarding physics? Do we break any maps with this?

It doesn't affect physics, it only affects how often the server sends snapshots to the client.

2023-09-20 08:54 UTC, 0xfaulty commented
I mean, as I pointed out above, the Reset() method is already called wherever it is needed on core creation, but in the case of reckoning which is initialised each TickDeferred, this call is not needed, as it reset it's internal state and the difference in comparison

2023-09-23 15:28 UTC, Learath2 commented
The reset was introduced in 6680ec388cb8b71f9fa73223d3af9d37148bd26a and iirc fixed the mentioned issue. I'll have to dig around a bit to see why this reset causes issues

2023-09-23 18:42 UTC, Learath2 requested changes
After investigation, I agree that the reset is what broke the reckoning, but I'd like to argue that it's the `Init` call that doesn't belong in `CCharacter::TickDeferred`.

Initialize `m_ReckoningCore` properly in `CCharacter::Spawn`, consider using just `nullptr` as the `CGameWorld` (it should be sane, everything is guarded), update it's tuning inside `CCharacter::HandleTuneLayer`.

The `nullptr` world would change: 
- Hooktele prediction for reckoning (was already broken, doesn't use the PRNG)
- Grabbed hook prediction for reckoning (was already broken, the temp world doesn't have any other players to predict against)

2023-09-24 19:58 UTC, 0xfaulty commented
Closed, as fixed by #7247

2023-09-24 19:58 UTC, closed without merging