Add a popup for when video render is done
ddnet/ddnet pull request #7172
Opened 2023-09-12 15:23 UTC by furo321

![image](https://github.com/ddnet/ddnet/assets/141338449/900aeac3-d2dd-4b0f-959c-0b3712ec4f45)

This should hopefully make it less confusing about where the videos are saved once it's done rendering.

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-09-12 15:35 UTC, Robyt3 requested changes

2023-09-12 15:35 UTC, Robyt3 commented on src/game/client/components/menus.cpp
> +			TextBox.VSplitRight(60.0f, &TextBox, 0);
Use `nullptr` instead of `0`

2023-09-12 15:35 UTC, Robyt3 commented on src/game/client/components/menus.cpp
> +			UI()->DoLabel(&TextBox, aBuf, 18.0f, TEXTALIGN_LEFT);
Use `TEXTALIGN_TL` or `TEXTALIGN_ML`.

Alignment also needs to be tested with very long file names.

2023-09-12 15:35 UTC, Robyt3 commented on src/game/client/components/menus_demo.cpp
> +	if(m_DemoRenderInput.GetLength() > 0)
Use `!IsEmpty()` instead

2023-09-12 15:45 UTC, Jupeyy commented
It makes it less confusing to know where the videos are stored.

But once you know it, it makes it more annoying to use the render function

2023-09-12 16:01 UTC, furo321 commented
That's true, but I don't think it's that big of an issue. Also even if you already know the path, you can now just tap a button to go there instead of navigating through a maze of folders.

2023-09-12 17:40 UTC, Robyt3 commented
Maybe only put a button to open the videos folder in the demo browser?

![screenshot](https://github.com/ddnet/ddnet/assets/23437060/b27dcb30-25e2-4ca6-b5b3-6cfab22ade69)

2023-09-12 18:17 UTC, furo321 commented
There isn't a lot of space to put it, so I halved the size of the demos button. I personally think it looks pretty cramped, what do you think?
![image](https://github.com/ddnet/ddnet/assets/141338449/cea020a6-ad26-4289-b711-961e3a5ddf46)

2023-09-12 18:45 UTC, Robyt3 commented
To be honest, the demo browser UI should probably be reworked in any case. Some or all buttons could use icons instead of text to save space.

2023-09-12 20:29 UTC, Teero888 commented
> But once you know it, it makes it more annoying to use the render function (esp. if u render smaller clips and not a huge demo)

I think a little checkbox like "do not show again" would be an idea.

2023-09-30 09:37 UTC, def- approved these changes

2023-09-30 09:58 UTC, merged

2023-10-08 17:54 UTC, Jupeyy commented
> Maybe only put a button to open the videos folder in the demo browser?
> 
> ![screenshot](https://user-images.githubusercontent.com/23437060/267415251-b27dcb30-25e2-4ca6-b5b3-6cfab22ade69.png)

Wasn't the plan rather to do this, instead of this extra click?

2023-10-08 18:16 UTC, Robyt3 commented
I didn't find a great spot for a "Videos directory" button in #7311. Maybe the "Demos directory" button could be slightly smaller and moved to the left.

2023-10-08 18:18 UTC, Jupeyy commented
Yeah my point is more: If ppl find the render button. they also find the movie button ^^ (maybe even directly next to the render button)

Then we don't need this _ugly_ extra popup.

Except you say it's very user friendly