CMake: Revert versioning (move it back to version.h)
ddnet/ddnet pull request #7186
Opened 2023-09-16 00:02 UTC by Kaffeine

With current packaging scripts there is no much options other than that.

Sorry, this is barely tested. I'll update the status later if I can.
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-09-16 00:33 UTC, def- requested changes
Fails for me:
```
CMake Error at CMakeLists.txt:2052 (add_library):
  Cannot find source file:

    /ddnet-source/src/game/version.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:2052 (add_library):
  No SOURCES given to target: game-shared
```

2023-09-16 09:49 UTC, Kaffeine commented
> Fails for me on Linux builds:
> 
> ```
> CMake Error at CMakeLists.txt:2052 (add_library):
>   Cannot find source file:
> 
>     /ddnet-source/src/game/version.h
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
>   .hpp .hxx .in .txx
> 
> 
> CMake Error at CMakeLists.txt:2052 (add_library):
>   No SOURCES given to target: game-shared
> ```

CI build successfully. Maybe you build in the source directory? I pushed a change for that:
```diff
-# Remove outdated version.h which could be generated in some prev version
-file(REMOVE ${CMAKE_CURRENT_BINARY_DIR}/src/game/version.h)
+if(NOT "${CMAKE_CURRENT_BINARY_DIR}" STREQUAL "${CMAKE_CURRENT_SOURCE_DIR}")
+  # Remove version.h generated by previous build code
+  file(REMOVE ${CMAKE_CURRENT_BINARY_DIR}/src/game/version.h)
+endif()
```

2023-09-16 22:03 UTC, def- commented
bors r+
Thanks, that seems to work.

2023-09-17 14:51 UTC, def- approved these changes

2023-09-17 15:18 UTC, merged