Enhance editor toolbar sounds
ddnet/ddnet pull request #7208
Opened 2023-09-18 09:00 UTC by dobrykafe

Adds a seekbar that makes it easier to preview longer audio files.
Not really sure how to make it look.

![toolbar-sounds](https://github.com/ddnet/ddnet/assets/121701317/7bab48a3-c1a5-432f-9aa1-1d1288325636)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-09-18 14:39 UTC, Robyt3 commented on src/engine/client/sound.cpp
> +				Voice.m_Tick = pSample->m_NumFrames * Time;
You can break/return after setting the tick, there shouldn't be multiple voices with the same sample.

2023-09-18 14:42 UTC, Robyt3 commented on src/engine/client/sound.cpp
> +				Voice.m_Tick = pSample->m_NumFrames * Time;
Actually, a sample can be played multiple times in different voices. In that case, isn't this function setting the position in all voices using this sample? I think this should be changed so the position is changed only for individual voices. You get a voice handle when calling `Play`.

2023-09-18 14:49 UTC, Robyt3 commented on src/engine/client/sound.cpp
> +void CSound::Pause(int SampleID)
Allowing the pause per voice would be cleaner, like `StopVoice`. Although `StopVoice` doesn't seem to work correctly for `FLAG_LOOP` right now.

Pausing individual voices also wouldn't work in the current state, because `m_PausedAt` seems to be stored only once for each sample.

2023-09-18 14:51 UTC, Robyt3 commented on src/game/editor/editor.cpp
>  void CEditor::DoToolbarSounds(CUIRect ToolBar)
You could move the audio preview UI also into a separate function and use that also for the audio preview in the file dialog.

2023-09-18 14:57 UTC, Robyt3 requested changes
Looks good. Adding the same functionality for the file dialog should be relatively easy.

You can probably ignore my comments about the sound engine, since we don't seem to make use of the voice-based playback for anything except playback of ingame map sounds anyway.

2023-09-18 15:01 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +			ToolBarBottom.VSplitLeft(200.0f, &SeekBar, &ToolBarBottom);
I think a small `HMargin` on `SeekBar` would look better, also so the font size inside the seekbar isn't so large.

2023-09-18 15:03 UTC, Robyt3 commented on src/engine/client/sound.cpp
> +		}
Missing return statement here

2023-09-30 09:25 UTC, def- commented
@dobrykafe Still interested in fixing this up? Needs a rebase too.

2023-10-06 08:59 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +				float s_PrevAmount = 0.0f;
This has to be a static variable or skipping with shift will always reset the time to 0. Not sure if you also need two separate static variables for both calls of this function.

2023-10-06 09:03 UTC, Robyt3 commented on src/engine/client/sound.cpp
>  	return (m_aSamples[SampleID].m_NumFrames / m_aSamples[SampleID].m_Rate);
This calculation currently uses `int`, so the time is only returned in roughly whole seconds.

`(float)m_aSamples[SampleID].m_Rate`

2023-10-06 09:04 UTC, Robyt3 commented on src/engine/client/sound.cpp
> +				return (Voice.m_Tick / pSample->m_Rate);
`(float)pSample->m_Rate`

2023-10-06 09:04 UTC, Robyt3 commented on src/engine/client/sound.cpp
> +	return (pSample->m_PausedAt / pSample->m_Rate);
`(float)pSample->m_Rate`

2023-10-06 21:37 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +				float s_PrevAmount = 0.0f;
Would be easier. It doesn't work very well for demo skipping either.

2023-10-08 09:06 UTC, Robyt3 approved these changes
Thanks.

2023-10-08 09:28 UTC, merged