Add ability to swap without a name when team only has 2 players.
ddnet/ddnet pull request #7227
Opened 2023-09-21 17:42 UTC by furo321

Closes #3737 
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-09-21 20:56 UTC, def- requested changes

2023-09-21 20:56 UTC, def- commented on src/game/server/ddracechat.cpp
> +		int TeamSize = 0;
I'd say the variable is wrongly named since it currently excludes the player itself. So it doesn't represent the size of the team, but is 1 less than that.

2023-09-21 20:56 UTC, def- commented on src/game/server/ddracechat.cpp
> +		int TeamSize = 0;
```suggestion
		int TeamSize = 1;
```

2023-09-21 20:56 UTC, def- commented on src/game/server/ddracechat.cpp
> +		if(TeamSize > 1)
```suggestion
		if(TeamSize != 2)
```

2023-09-22 14:33 UTC, Robyt3 approved these changes

2023-09-22 14:55 UTC, merged