Detect if server started from client is no longer running
ddnet/ddnet pull request #7236
Opened 2023-09-22 16:40 UTC by furo321

Fixes 1. of #6403
> The menu button should be updated to reflect whether the server is still running. For example the server may have been shut down manually with shutdown or it may have failed to start entirely due to the map missing or another issue.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-09-22 17:00 UTC, Robyt3 requested changes

2023-09-22 18:19 UTC, furo321 commented
Thanks, fixed!

2023-09-22 19:14 UTC, Robyt3 commented on src/game/client/components/menus_start.cpp
> +		m_ServerProcess.m_Process = INVALID_PROCESS;
Nice, `KillServer` is even better. You don't need to set to `INVALID_PROCESS` then, because it's already done inside.

2023-09-22 19:25 UTC, furo321 commented on src/game/client/components/menus_start.cpp
> +		m_ServerProcess.m_Process = INVALID_PROCESS;
I was thinking so too, but it's only set if `kill_process` returns success. Which it won't do if the server isn't running anymore.

2023-09-22 19:31 UTC, Robyt3 commented on src/game/client/components/menus_start.cpp
> +		m_ServerProcess.m_Process = INVALID_PROCESS;
In that case the handle would also not be getting closed on Windows. I think `kill_process` should return success when the process is not running and also close the handle in that case.

2023-09-22 20:50 UTC, Robyt3 commented on src/base/system.cpp
> +	CloseHandle(process);
The handle shouldn't be closed if the process could not be terminated due to an error, since we still need the handle to try terminating the process again in that case.

2023-09-23 08:50 UTC, Robyt3 approved these changes
Thanks.

2023-09-23 09:11 UTC, merged

2023-09-25 14:44 UTC, heinrich5991 commented on src/base/system.cpp
> +		return true;
This is something that should generally not be done. Do the action instead of checking whether something exists first. This leads to TOCTOU vulnerabilities otherwise.

2023-09-25 14:47 UTC, heinrich5991 commented on src/game/client/components/menus_start.cpp
> +		KillServer();
If the process is not alive, kill it? That seems very suspect. A comment should be added, or maybe extract the parts you need from `KillServer`.

It's even in the render path. A syscall probably doesn't belong here. I don't know a better place to put it though. :/