firing/hooking takes aim when action happened not when tick
ddnet/ddnet pull request #7253
Opened 2023-09-25 10:50 UTC by JSaurusRex

When moving the mouse fast there can be a discrepancy between where I aimed and where my weapon or hook actually go's. This is because of the fact that the mouse can move after I've shot/hooked and the mouse position at the end of the tick gets send, not the one when shot/hooked.
This makes aiming these actions kind of random and tick dependent, if you did the action right before the tick ends its really accurate but if its all the way in the beginning the mouse can move up to 20 ms longer, that can be a big difference when moving fast.
Hopefully tying it to framerate will behave better, since most players play with higher framerates than 50.

That all being said, I have tested this but there isn't an extremely noticeable difference, some pro-players might want to test this out. That being said, I have printed the difference in values, the highest I saw was 100x 150y at 1920x1080. That probably is a pretty decent difference in aim, can be the difference between hitting a shot or hook and not.

Also sorry for shitty code I don't know the coding style that well and just wanted to quickly implement it, I don't mind changing the implementation.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-09-25 11:34 UTC, def- requested changes
I think this is by design, it might also make some previous tricks impossible, so I'm strongly opposed.

2023-09-25 12:06 UTC, JSaurusRex commented
It 100% should be an option that can be disabled / enabled. However I think it will also make a lot of tricks easier, I cant think of any tricks it would make harder. "I think this is by design", what do you mean by this? With my PR it still is 50hz nor does it do anything out of order.

2023-09-25 14:03 UTC, def- commented
I think these intentionally act immediately and no on the next tick. You are changing the physics of the game, so this would break any rank.

We don't want further options. That would increase complexity.

2023-09-25 14:19 UTC, JSaurusRex commented
At larger speeds this would pr would actually end up hurting the accuracy compared to what the player really wanted to do, I can implement a if statement to switch between using this and not depending whichever is greater but at that point it really has gotten more drawbacks than might be worth.
Still worth it for some modes (gores and fng for example, low movement speed but need fast mouse movements), but definitely not an 1 fix fixes all solution. I'll think about what to change next (probably opt in setting)

2023-09-25 14:22 UTC, JSaurusRex commented
> I think these intentionally act immediately and no on the next tick. You are changing the physics of the game, so this would break any rank.
> 
> We don't want further options. That would increase complexity.

no worries this doesn't act immediately, it simply replaces the position of the mouse that gets send with the position of when shot, so it doesn't change physics at all (which also is impossible from the client side alone)

2023-10-03 20:24 UTC, trml commented
From what I understand this pr attempts solves a problem that goes something like this:
You press fire when you are aiming at mousepos X, but there is still some time left (up to 20 ms) until the client will send the next input. Once the next tick is reached, the client sends mousepos Y instead of X, because the mouse moved a little in between.

The goal of this pr is to send mousepos X instead, which removes the randomness of which mouse position that is sent (since now it is random from the users point of view), and also on average reduces input lag by 10 milliseconds.

To me this sounds like a good idea (I'm not sure if a config is needed? reducing input lag is always a good thing?)

2023-10-03 20:51 UTC, JSaurusRex commented
> From what I understand this pr attempts solves a problem that goes something like this: You press fire when you are aiming at mousepos X, but there is still some time left (up to 20 ms) until the client will send the next input. Once the next tick is reached, the client sends mousepos Y instead of X, because the mouse moved a little in between.
> 
> The goal of this pr is to send mousepos X instead, which removes the randomness of which mouse position that is sent (since now it is random from the users point of view), and also on average reduces input lag by 10 milliseconds.
> 
> To me this sounds like a good idea (I'm not sure if a config is needed? reducing input lag is always a good thing?)

yes this exactly what it does, it doesn't really reduce input lag since its still just as delayed when you or the server see it but it kinda acts similarly in functionality. Only thing is that it can be less accurate when moving fast, imagine you're moving fast and tracking an tile with your mouse to hook, you hook but because the character moves up to 20ms further you miss. This is why it should be decided by the user and it depends per gamemode and personal preference if the player prefers it, if you track your hooks / shots it will decrease accuracy but if you flick it will increase. Some logic could be implemented but I think having it as an option (by default off) is the way to go. Some future PR can implement more complex logic if they wanted to.

2023-10-03 21:42 UTC, trml commented
> if you track your hooks / shots it will decrease accuracy but if you flick it will increase

I didn't think about tracking your shots, but yes, in that case having it enabled could create some inconsistencies (some logic could perhaps be added to handle the moving player case, but not for the moving target case).

2023-10-07 21:38 UTC, def- requested changes
I'm still afraid of this change, but since it's off by default let's give it a try

2023-10-07 21:38 UTC, def- commented on src/game/client/components/binds.cpp
> +	char *key = 0;
pKey

2023-10-07 21:38 UTC, def- commented on src/game/client/components/binds.cpp
> +#include <cstring>
We don't use cstring directly, only system.h

2023-10-07 21:38 UTC, def- commented on src/game/client/components/binds.cpp
> +		if(strcmp("+fire", key) == 0 || strcmp("+hook", key) == 0)
str_comp from system.h

2023-10-07 21:38 UTC, def- commented on src/game/client/components/binds.h
> +	bool mouseOnAction;
MouseOnAction

2023-10-08 11:37 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +		m_Controls.m_aMousePosOnAction[g_Config.m_ClDummy] = m_Controls.m_aMousePos[g_Config.m_ClDummy]; //idk what g_Config.m_ClDummy is
Remove the comment. It means whether dummy is currently active or not.

2023-10-08 11:38 UTC, Robyt3 commented on src/game/client/components/binds.cpp
> +	char *key = 0;
And `const char *` instead of `char *`

2023-10-08 11:40 UTC, Robyt3 commented on src/game/client/components/binds.h
> +	bool mouseOnAction;
`m_MouseOnAction`

2023-10-08 11:57 UTC, Robyt3 commented on src/game/client/components/binds.cpp
> +	char *key = 0;
`nullptr` instead of `0`

2023-10-08 12:12 UTC, JSaurusRex commented on src/game/client/gameclient.cpp
> +		m_Controls.m_aMousePosOnAction[g_Config.m_ClDummy] = m_Controls.m_aMousePos[g_Config.m_ClDummy]; //idk what g_Config.m_ClDummy is
forgot I added that xD, will do

2023-10-08 21:29 UTC, def- approved these changes

2023-10-08 21:52 UTC, merged