Quality of life ; rcon tele small changes
ddnet/ddnet pull request #7264
Opened 2023-09-28 17:07 UTC by Steinchen99

rcon tele didn't previously unfreeze nor reset speed

now it should

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-09-28 22:08 UTC, def- requested changes

2023-09-28 22:08 UTC, def- commented on CMakeLists.txt
> +  assets/entities/none/entities.png
These changes look unrelated to your commit message. I believe they were previously discussed and decided against.

2023-09-29 12:34 UTC, def- approved these changes

2023-09-29 12:55 UTC, heinrich5991 commented
Removed the intermediary commits that added images, these bloat the git repository forever.

2023-09-29 13:44 UTC, merged