store editor tooltip in optional string
ddnet/ddnet pull request #7287
Opened 2023-10-02 23:16 UTC by Marmare314

Currently when you want to use `str_format` for the tooltip you have to create a buffer for it. But when setting the tooltip from other classes this becomes a bit problematic, because the buffer still has to be part of `CEditor` to avoid nullptr exceptions.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-10-03 08:16 UTC, def- requested changes
I'm not sure I understand. The TW/DDNet style solution for this would be `char m_aTooltip[256];`

2023-10-03 08:39 UTC, Marmare314 commented
I guess so, I just find c-strings a pain to work with. So I thought that since this is not performance critical code the editor could use more strings instead.
Also `optional<string>` captures the idea behind the variable better than `char[256]` which is potentially empty. In this case it doesnt reallly make a difference, but still.

2023-10-03 12:02 UTC, Robyt3 commented
I'd prefer `char m_aTooltip[256];` and `SetTooltip(const char *pTooltip)`, where an empty tooltip is just an empty string.

2023-10-04 21:41 UTC, def- approved these changes

2023-10-05 10:22 UTC, merged