Add ability to scroll in console. Remove pages.
ddnet/ddnet pull request #7340
Opened 2023-10-13 18:13 UTC by furo321

This PR removes the idea of "pages" from the console and instead replaces it with "lines". This makes it now possible to navigate the consoles content by using the scroll wheel. It's still possible to use `PageUp` and `PageDown`, which would go down/up the amount of entries rendered.

Other bugs fixed
- The console now properly keeps the scroll position when new entries are added.
- Active page getting reset sometimes when opening/closing console (closes #6902)

One thing I wanted to fix, but couldn't was that the console should always try to render as many entries as possible. Currently if you scroll to the top it will only display the last entry, when instead it should show that entry + as many previous entries that would fit below it.

https://github.com/ddnet/ddnet/assets/141338449/d8e737cf-6689-42ed-b037-56343037df42

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-10-13 18:35 UTC, Robyt3 requested changes
Definitely a nice improvement to usability.

I envisioned scrolling in the console to work with clipping like in listboxes, but it looked like that could get dirty because we can't use a listbox directly in the console, because of the different mouse handling.

2023-10-13 18:35 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +		m_LocalConsole.PrintLine(pLine, str_length(pLine), ColorRGBA{TextRender()->DefaultTextColor()});
`ColorRGBA{TextRender()->DefaultTextColor()}` -> `TextRender()->DefaultTextColor()`

2023-10-13 18:35 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +		m_RemoteConsole.PrintLine(pLine, str_length(pLine), ColorRGBA{TextRender()->DefaultTextColor()});
same

2023-10-13 18:35 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +			TextRender()->Text(10.0f, FontSize / 2.f, FontSize, "Following", -1.0f);
Move the condition inside the argument to reduce the duplicate code

2023-10-13 18:35 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +			TextRender()->Text(10.0f, FontSize / 2.f, FontSize, "Following", -1.0f);
Last argument `-1.0f` is not necessary (identical to default)

2023-10-13 18:35 UTC, Robyt3 commented on src/game/client/components/console.cpp
> -		str_format(aBuf, sizeof(aBuf), Localize("-Page %d-"), pConsole->m_BacklogCurPage + 1);
I'd prefer if there was still an indication of the scroll position. You could store the height or number of lines of each rendered console entry to calculate the current scroll offset and the maximum height.

2023-10-13 18:35 UTC, Robyt3 commented on src/game/client/components/console.cpp
> -		str_format(aBuf, sizeof(aBuf), Localize("-Page %d-"), pConsole->m_BacklogCurPage + 1);
That way you could probably also solve this issue:

> One thing I wanted to fix, but couldn't was that the console should always try to render as many entries as possible. Currently if you scroll to the top it will only display the last entry, when instead it should show that entry + as many previous entries that would fit below it.

By ensuring that you don't scroll further when the oldest entry reaches the top of the screen.

2023-10-13 19:51 UTC, furo321 commented on src/game/client/components/console.cpp
> -		str_format(aBuf, sizeof(aBuf), Localize("-Page %d-"), pConsole->m_BacklogCurPage + 1);
I added back the scroll position, but I still couldn't figure out a good solution to the issue. I could only get something that worked only when using the scroll wheel, but then it would go outside if you went up more than one line (e.g. with `PageUP` or `Home`)

![image](https://github.com/ddnet/ddnet/assets/141338449/7cd904c5-22a2-494a-bb72-dbd64618f6c7)

2023-10-13 20:24 UTC, Robyt3 commented on src/game/client/components/console.cpp
> -		str_format(aBuf, sizeof(aBuf), Localize("-Page %d-"), pConsole->m_BacklogCurPage + 1);
Should be possible, I'd say you need to calculate the sum of the heights of the entry that would be skipped before actually performing the scroll. For example if you use `Home` then you'd need to calculate the sum of the entry heights starting at the oldest entry until the next sum would exceed the available console screen height.

2023-10-15 15:57 UTC, Robyt3 commented
The text moves a bit up and down when there are entries that span multiple lines. Doing page up and down in alternation will not keep the same entry selected when there are entries that span multiple lines. To get long console entries, use `echo mm...mm` with many `m`s.

2023-10-15 15:59 UTC, Robyt3 commented on src/game/client/components/console.cpp
> -		str_format(aBuf, sizeof(aBuf), Localize("-Page %d-"), pConsole->m_BacklogCurPage + 1);
Showing the current range of entries being displayed as well as the total number of entries would be better instead of only showing the index of the bottom entry.

2023-11-18 22:49 UTC, heinrich5991 commented
Status: Unaddressed review comments.

2023-12-04 21:58 UTC, closed without merging

2023-12-04 21:58 UTC, furo321 commented
Closing, I don't know how the solve the current issues with my PR. If anyone else wanna try, feel free to.