Add option to disable printing of regional rankings.
ddnet/ddnet pull request #7362
Opened 2023-10-22 23:06 UTC by furo321

This adds the ability to disable the printing of regional rankings in `/top5` and `/rank`. Most servers aren't split across multiple regions which leads to the `/top5` being effectively printed twice.

`sv_regional_rankings 1` (default)
![image](https://github.com/ddnet/ddnet/assets/141338449/c4a98a56-1911-4183-ba21-2b9335d883be)

`sv_regional_rankings 0`
![image](https://github.com/ddnet/ddnet/assets/141338449/2c7081a7-5195-4835-877a-9605ed9330de)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-10-23 05:27 UTC, def- requested changes

2023-10-23 05:27 UTC, def- commented on src/test/score.cpp
Could you add a test for sv_regional_rankings = false?

2023-10-27 15:49 UTC, Robyt3 approved these changes

2023-10-27 16:42 UTC, def- approved these changes

2023-10-27 17:06 UTC, merged