Add argument completion for `reset`, `toggle`, `access_level`
ddnet/ddnet pull request #7371
Opened 2023-10-25 18:12 UTC by furo321

Add auto completions for commands that take a command/config as their first argument.

https://github.com/ddnet/ddnet/assets/141338449/6b025409-724e-49db-a568-f8886f14ed53

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-10-25 22:58 UTC, def- approved these changes
Cool!

2023-10-26 15:56 UTC, Robyt3 requested changes

2023-10-26 15:56 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +		m_ArgumentCompletionFlagmask = CFGFLAG_SAVE;
I think this variable is unnecessary. It would be better to use `m_CompletionFlagmask` instead. I assume you are using `CFGFLAG_SAVE` instead of `CFGFLAG_CLIENT` because you only want to show config variables, but this will also exclude config variables that are not saved, e.g. `debug` could be used as an argument for `toggle` or `reset`. On the server-side, you are already showing all commands as possible arguments when using `reset`, including commands that cannot be reset.

We'd need a new `CFGFLAG_VARIABLE` if we want to mark the commands for config variables defined in `variables.h` and `config_variables.h` as such.

2023-10-27 16:17 UTC, furo321 commented on src/game/client/components/console.cpp
> +		m_ArgumentCompletionFlagmask = CFGFLAG_SAVE;
I mainly wanted to exclude commands commands beginning with `+` as they won't do anything if they're used as an argument.

2023-10-27 18:12 UTC, merged