Draft: Editor undo/redo v2
ddnet/ddnet pull request #7393
Opened 2023-10-30 12:48 UTC by archimede67

This is a complete rework of #5776 (started over a year ago). The main motivation is to make almost anything undoable in the editor.

There are 3 different histories:
- The map editor history, which holds all changes directly related to the map and layers
- The envelope editor history, which holds all changes related to envelopes and their points
- The server settings editor history, which holds all changes related to server settings commands

Each one of these histories has a maximum limit of actions they can hold. This limit can be configured through the `cl_editor_max_history` command, the default value is 50. Currently, I have set the maximum limit for that command to 500, but I might increase that in the future.

I have tried to optimize many actions that were saved as opposed as my previous attempt. For example, when drawing/changing tiles, the entire layer is not saved anymore, only the tile changes. This allows for a very memory efficient solution.

I have opened this pull request as a draft because right now everything should work, but I would like to refactor some part of the code and reduce duplicate code. I would also like if some of you readers could test the feature and give me suggestion/feedback on things that I should change, add or improve.

Regarding the actual features, I have added undo/redo buttons in the editor toolbar:
![image](https://github.com/ddnet/ddnet/assets/13364635/29bac44a-2a45-480c-89ba-35e66d25767f)

There is also two binds to undo/redo:
- `Ctrl+Z` is the bind to undo an action
- `Ctrl+Y` is the bind to redo. Some people might not be familiar with this bind, so I might add an additional `Ctrl+Shift+Z` bind

These binds are context dependant, meaning that if you have the envelope editor open and you press `Ctrl+Z`, it will undo any action inside that editor. If you don't have any extra editor opened, it will undo any action in the map editor history.

I have also added an history window (which works like an extra editor) which lists all the saved actions of the 3 histories. You can interact with this window by clicking one action, and it will undo all actions above the selected one. This allows you to quickly undo any changes past a specific point or go back to the initial map state. You can also clear the history from that window. Please note that when exeeding the maximum actions that can be saved (`cl_editor_max_history`), the oldest actions will be deleted from the history and there is no way to recover them. One thing I might add is a warning when you are about to exceed that limit to let you know that any actions past that will erase the old ones.
![image](https://github.com/ddnet/ddnet/assets/13364635/5b02af7f-da6a-4aab-b696-79b4e5e80bd0)

Finally, here is a small demonstration:

https://github.com/ddnet/ddnet/assets/13364635/63fd517d-5ef8-48a8-ae4b-77b8047e61c6

(Sorry for the crappy quality, I tried making it less than 10MB)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-10-30 13:35 UTC, def- commented
Incredible work!

2023-10-30 16:08 UTC, VoxelDoesCode commented
I don't like how the rotation buttons and the undo/redo buttons use the same font icon... I'd suggest an alternative, but I'm on my work shift.

2023-10-30 16:31 UTC, archimede67 commented
> I don't like how the rotation buttons and the undo/redo buttons use the same font icon... I'd suggest an alternative, but I'm on my work shift.

@VoxelDoesCode I used the icons you provided in #7393 ^^

2023-10-30 16:34 UTC, VoxelDoesCode commented
> @VoxelDoesCode I used the icons you provided in #5776 ^^ ([here](https://github.com/ddnet/ddnet/pull/5776#issuecomment-1322903304))

Oh right. Forgot about that. That was almost a year ago, though, and I do think I can provide less repetitive icons. Will contact later.

2023-10-30 18:54 UTC, Robyt3 requested changes
Amazing!

Haven't tested in detail yet, here are some code related comments already.

Already has merge conflicts though. When done all commits should be squashed so we don't have so many intermediate states in the history.

2023-10-30 18:54 UTC, Robyt3 commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(ClEditorMaxHistory, cl_editor_max_history, 50, 1, 500, CFGFLAG_SAVE | CFGFLAG_CLIENT, "Maximum number of undo actions in the editor history (not shared between editor, enveloppe edit
`enveloppe` -> `envelope`

2023-10-30 18:54 UTC, Robyt3 commented on src/game/client/ui.cpp
> +	static const void *s_Editing = nullptr;
`s_pEditing`

2023-10-30 18:54 UTC, Robyt3 commented on src/game/client/ui.cpp
> +	static const void *s_Editing = nullptr;
`s_pEditing`

2023-10-30 18:54 UTC, Robyt3 commented on src/game/client/ui.cpp
> +		dbg_msg("editor", "EDIT START UI VALUE");
Remove debug message

2023-10-30 18:54 UTC, Robyt3 commented on src/game/client/ui.cpp
> +		dbg_msg("editor", "EDIT END UI VALUE");
Remove debug message

2023-10-30 18:54 UTC, Robyt3 commented on src/game/client/ui.cpp
> +	if((ColorPickerRes = pUI->DoPickerLogic(&pColorPicker->m_ColorPickerId, &ColorsArea, &PickerX, &PickerY)) != EDITSTATE_NONE)
Avoid assignment inside `if`-condition

2023-10-30 18:54 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +	for(auto const &kp : m_SavedValues)
Rename `kp` to something more descriptive

2023-10-30 18:54 UTC, Robyt3 commented on src/game/editor/editor.h
> +	EditOneGo
Literals should be uppercase only, words separated by underscores.

2023-10-30 18:54 UTC, Robyt3 commented on src/game/editor/editor.h
> +	std::vector<int> m_TrackedProps;
`m_vTrackedProps`

2023-10-30 18:54 UTC, Robyt3 commented on src/game/editor/editor.h
> +	void Execute(std::shared_ptr<IEditorAction> const &pAction, const std::string &Display = "");
No need to pass `std::string` here, pass as `const char *`

2023-10-30 18:54 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +void CEditor::UndoLastAction()
Since we already started splitting the editor functionality, I think the code below should not all be in `editor.cpp`.

2023-10-30 18:54 UTC, Robyt3 commented on src/game/editor/tileart.cpp
> +	mem_copy(pEditor->m_aTileartFilename, pFilepath, sizeof(pEditor->m_aTileartFilename));
Use `str_copy` instead of `mem_copy`

2023-10-31 23:00 UTC, archimede67 commented on src/game/editor/editor.cpp
> +void CEditor::UndoLastAction()
I left `UndoLastAction` and `RedoLastAction` in `editor.cpp` but moved the rest of the code in different files

2023-10-31 23:01 UTC, archimede67 commented on src/game/client/ui.h
> +	enum EEditState
I made a shared enum class that is used in both `ui.cpp` and editor code

2023-10-31 23:03 UTC, archimede67 commented on src/game/client/ui.cpp
> +std::pair<int64_t, int> CUI::DoValueSelectorWithState(const void *pID, const CUIRect *pRect, const char *pLabel, int64_t Current, int64_t Min, int64_t Max, const SValueSelectorProperties &Props)
I made a custom shared struct `SUIEditResult<T>` which is used in both `ui.cpp` and editor code, which also uses the shared enum `EUIEditState`

2023-11-01 09:20 UTC, Robyt3 commented on src/game/editor/editor_action.h
> +#endif
Newline

2023-11-01 09:20 UTC, Robyt3 commented on src/game/editor/editor_history.cpp
> +}
Newline

2023-11-01 09:20 UTC, Robyt3 commented on src/game/editor/editor_history.cpp
> +	auto LastAction = m_vpUndoActions.back();
`LastAction` -> `pLastAction`

2023-11-01 09:20 UTC, Robyt3 commented on src/game/editor/editor_history.cpp
> +	auto LastAction = m_vpRedoActions.back();
`LastAction` -> `pLastAction`

2023-11-01 09:21 UTC, Robyt3 commented on src/game/editor/editor_history.h
> +#endif
Newline

2023-11-01 09:21 UTC, Robyt3 commented on src/game/editor/editor_history.h
> +	inline bool CanRedo() const { return m_vpRedoActions.size() > 0; }
Use `empty` instead of `size`

2023-11-01 09:22 UTC, Robyt3 commented on src/game/ui_edit_result.h
> +#endif
Newline, though I'm not sure this needs to be in a separate file.

2023-11-01 09:24 UTC, Robyt3 commented on src/game/editor/editor_trackers.cpp
> +	if((pIt = std::find(m_vTrackedProps.begin(), m_vTrackedProps.end(), Prop)) == m_vTrackedProps.end())
Avoid assignment in if-expression. Use `auto` for iterator and rename, `pIt` is not correct since it's not a pointer.

2023-11-01 09:34 UTC, Robyt3 commented on src/game/editor/editor_trackers.cpp
> +}
The name `GetColor` doesn't fit, since it doesn't simply return the color of the edit tracker and we don't use the `Get` prefix for getters anymore. Should be moved to `mapitems.h` and then renamed to `PackColor`. That would allow you to use this function also outside this class, where there was another use of this duplicate code.

2023-11-01 09:35 UTC, Robyt3 commented on src/game/editor/editor_trackers.h
> +		int m_Used;
Use `bool`?

2023-11-01 09:36 UTC, Robyt3 commented on src/game/editor/editor_trackers.h
> +#endif
Newline

2023-11-01 09:36 UTC, Robyt3 commented on src/game/editor/editor_trackers.cpp
> +}
Newline

2023-11-01 09:39 UTC, Robyt3 commented
Please rebase this on the current master branch to resolve the conflicts, so the CI runs, and so we can test if this works together with other recent editor changes.

2023-11-01 10:08 UTC, archimede67 commented on src/game/ui_edit_result.h
> +#endif
Yeah actually it does not need to be in a separate file, I moved them to `ui.h`

2023-11-01 16:32 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +	if((MouseLocked || s_TextMode) && !s_Editing)
This variable is only used once but `CheckMouseLock` is called again below. Either remove the variable or also use it below.

2023-11-01 16:35 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +			else if(!UI()->IsPopupOpen(&m_ColorPickerPopupContext))
The `if` condition is redundant, only use `else` here.

2023-11-01 16:36 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +				if(m_ColorPickerPopupContext.m_State == EUIEditState::EDITING)
This `if` can be moved up instead.

2023-11-01 16:39 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +	enum
Give the enum a name and use it instead of `int`

2023-11-01 16:40 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +	CEditorHistory *pCurrentHistory = nullptr;
You can remove the assignment of `nullptr` here. There are no code paths were it will be used, it's overriden on all code paths.

2023-11-01 16:41 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +			SLabelProperties Props;
Can be removed entirely

2023-11-01 16:50 UTC, Robyt3 commented on src/game/editor/editor_action.h
> +	virtual std::string Display() { return "Unknown"; }
Using `std::string` especially for formatting is not very idiomatic for our code base. It also looks like the strings are constructed while rendering every frame, which would be very inefficient.

I suggest changing this function to _non-virtual_ `const char *DisplayText() { return m_aDisplayText; }` and adding `char m_aDisplayText[256];` as a `protected` member to `IEditorAction`. As far as I can tell, the editor action are fully initialized with the constructor, so you only need to do one `str_format(m_aDisplayText, sizeof(m_aDisplayText), "...", ...);` call in every editor action contructor as well to define the display text for the action.

2023-11-01 16:54 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +	auto *pEditor = m_pEditor;
Seems redundant to me

2023-11-01 16:54 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +	auto *pEditor = m_pEditor;
Redundant

2023-11-01 16:54 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +	auto *pEditor = m_pEditor;
Redundant

2023-11-01 16:55 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +	static std::vector<std::string> s_PropNames{
This should be `static const char *s_apPropNames[]`, no need for `std::vector` here

2023-11-01 16:56 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +	static std::vector<std::string> s_PropNames{
No need for `std::vector` here

2023-11-01 16:58 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +		std::vector<int> ReverseIndexMap;
`vReverseIndexMap`

2023-11-01 16:58 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +		std::vector<std::shared_ptr<CEditorImage>> vRevertedImages;
`vpRevertedImages`

2023-11-01 16:58 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +		std::vector<int> ReverseIndexMap;
`vReverseIndexMap`

2023-11-01 16:58 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +		std::vector<std::shared_ptr<CEditorImage>> vRevertedImages;
`vpRevertedImages`

2023-11-01 16:59 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +	static std::vector<std::string> s_vNames{
No need for `std::*` here

2023-11-01 17:00 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +	static std::vector<std::string> s_vNames{
No need for `std::*` here

2023-11-01 17:00 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +	static std::vector<std::string> s_vNames = {
No need for `std::*` here

2023-11-01 17:01 UTC, Robyt3 commented on src/game/editor/editor_actions.h
> +	std::string m_MapName;
`char m_aMapName[IO_MAX_PATH_LENGTH];`

2023-11-01 17:01 UTC, Robyt3 commented on src/game/editor/editor_actions.h
> +	std::string m_TileArtFile;
`char m_aTileArtFile[IO_MAX_PATH_LENGTH];`

2023-11-01 17:01 UTC, Robyt3 commented on src/game/editor/editor_actions.h
> +#endif
Newline

2023-11-01 17:02 UTC, Robyt3 commented on src/game/editor/editor_trackers.cpp
> +					m_PreviousValuesPoint[QuadIndex][v][Prop] = Color;
Use `PackColor`

2023-11-01 17:03 UTC, Robyt3 commented on src/game/editor/mapitems/layer_quads.cpp
> +#include "../editor_actions.h"
`#include <game/editor/editor_actions.h>`

2023-11-01 17:04 UTC, Robyt3 commented on src/game/editor/mapitems/layer_sounds.cpp
> +#include "../editor_actions.h"
`#include <game/editor/editor_actions.h>`

2023-11-01 17:04 UTC, Robyt3 commented on src/game/editor/mapitems/layer_tele.cpp
> +}
Newline

2023-11-01 17:04 UTC, Robyt3 commented on src/game/editor/mapitems/layer_switch.cpp
> +}
Newline

2023-11-01 17:06 UTC, Robyt3 commented on src/game/editor/mapitems/layer_tiles.cpp
> +
Use `PackColor`

2023-11-01 17:07 UTC, Robyt3 commented on src/game/editor/mapitems/layer_tune.cpp
> +}
Newline

2023-11-01 17:07 UTC, Robyt3 commented on src/game/mapitems.cpp
> +}
Newline

2023-11-01 18:41 UTC, Kaffeine commented on src/game/editor/editor_history.h
> +	inline bool CanRedo() const { return !m_vpRedoActions.empty(); }
```suggestion
	bool CanUndo() const { return !m_vpUndoActions.empty(); }
	bool CanRedo() const { return !m_vpRedoActions.empty(); }
```

`Inline` keyword is unnecessary (as long as the method definitions provided *inline*)

2023-11-01 18:45 UTC, Kaffeine commented on src/game/editor/mapitems/layer_quads.cpp
> +	auto BeginProp = [&PropRes](int Value) mutable {
`mutable` makes this lambda eye-catching for no reason.

2023-11-01 18:51 UTC, Kaffeine commented on src/game/client/ui.h
> +struct SUIEditResult
`TUIEditResult`? @Robyt3 (or anyone else) please clarify (I'm not quite sure here but `SUIEditResult` sounds misleading).

2023-11-01 18:55 UTC, Kaffeine commented on src/game/editor/mapitems/layer_quads.cpp
> +		BeginProp(m_Image);
I think I'd prefer a RAII object (with `m_PreviousValue`) instead of the two lambdas and the static var.

2023-11-01 19:06 UTC, Kaffeine commented on src/game/editor/editor_action.h
> +	friend class CEditor;
What is the reason for the friendship? The class has only one protected member — the `m_pEditor` variable initialized via the constructor.

2023-11-01 19:07 UTC, Robyt3 commented on src/game/client/ui.h
> +struct SUIEditResult
The prefix `S` is correct since it's a `struct`, though the group upper case initial letters `SUIE` make it confusing to read. I mostly see the `T` prefix being used for `typedef`s in our code. A name like `SValueSelectorResult` would be better here, if objects of this struct are only used for `DoValueSelector`.

2023-11-01 19:11 UTC, Kaffeine commented on src/game/editor/mapitems/layer_tiles.h
> +	EditorTileStateChangeHistory<struct STileStateChange> m_TilesHistory;
```suggestion
	EditorTileStateChangeHistory<STileStateChange> m_TilesHistory;
```

2023-11-01 19:15 UTC, Kaffeine commented on src/game/client/ui.h
> +struct SUIEditResult
Oh, I thought T stands for the templates, and the "mislead" is that `SUIEditResult` sounds like a normally instanceable type (`SUIEditResult Result;`) while it is not.

2023-11-01 19:34 UTC, Kaffeine commented on src/game/editor/mapitems/layer_tiles.h
> +using EditorTileStateChangeHistory = std::map<int, std::map<int, T>>;
This is quite rough to read.

`std::vector<std::pair<int, EditorTileStateChangeHistory<STileStateChange>>> m_vTileChanges;` making it even worse: it is hard to say what's going on in [void CEditorBrushDrawAction::SetInfos()](https://github.com/ddnet/ddnet/pull/7393/files#diff-784539c38a2fb81a53b83b0a8f143c5abe3e7ad6be4b5b2f5e26ee9d77b7a046R65)

```cpp
for(auto const &Pair : m_vTileChanges)
{
    auto Changes = Pair.second;
    for(auto &Change : Changes)
    {
        m_TotalTilesDrawn += Change.second.size();
        // ..
```

A comment would help. It took me a while to see that this is `x, y, change` items.

2023-11-01 19:36 UTC, archimede67 commented on src/game/client/ui.h
> +struct SUIEditResult
`S` stands for `struct`, `UI` stands for well, UI and then the name, `EditResult`. Not sure how to mark that it is a templated type. This is used in multiple places, including `DoValueSelector` and `DoPropertiesWithState`

2023-11-01 19:38 UTC, archimede67 commented on src/game/editor/mapitems/layer_quads.cpp
> +		BeginProp(m_Image);
Yeah I don't like this either, I want to refactor it anyway

2023-11-01 19:42 UTC, Kaffeine commented on src/game/mapitems.h
> +int PackColor(CColor &Color);
The method is not inline and "as is" it requires LTCG/LTO from the compiler to see that CColor is actually not modified and the reference (aka the address of `Color`) is not needed.

Please pass CColor by value because it is better for read (won't make an impression of a big object passed for modification) and better for debug (even plain debug output 'll contain the value instead of a useless address). It is also faster for CPU, though this "optimization" is inessential.

2023-11-01 19:44 UTC, Kaffeine commented on src/game/editor/mapitems/layer_speedup.h
> +	inline void ClearHistory() override
```suggestion
	void ClearHistory() override
```

2023-11-01 19:50 UTC, Kaffeine commented on src/game/editor/editor_actions.h
> +	};
Consider
```cpp
enum class EType
{
    Delete,
    Add,
    MoveUp,
    MoveDown,
};
```
I don't see a justification for "hello C++98" in a new code. IMO typeless enumerations is one of the top things hurting readability of the legacy codebase.

2023-11-01 19:51 UTC, Kaffeine commented on src/game/editor/editor_actions.h
> +	enum
Please use enum class.

2023-11-01 19:51 UTC, Kaffeine commented on src/game/editor/editor_actions.h
> +	enum
enum class

2023-11-01 19:51 UTC, Kaffeine commented on src/game/editor/editor_actions.h
> +	enum
class

2023-11-01 19:53 UTC, archimede67 commented on src/game/editor/mapitems/layer_tiles.h
> +using EditorTileStateChangeHistory = std::map<int, std::map<int, T>>;
The idea is to store a list of changes for each layers that was selected (`m_vTileChanges`). There is like a small history which is basically a 2D map containing the changes (`EditorTileStateChangeHistory<T>`), and this is then paired with a layer index and stored in a `std::pair`. If you combine all of this, you get a rather long type indeed.

In the code snippet you took, here we iterate through each pair (`Pair`) of the vector, and then each entry of the small history (`Change`). Since this history is a 2D map, `Change.first` contains the `y` position (not `x`), and `Change.second` contains a 1D map for all changes on that `y` position (`.first` of this map is the `x` position, `.second` is the actual change item).

2023-11-01 20:00 UTC, Kaffeine commented on src/game/editor/editor_history.cpp
> +void CEditorHistory::RecordAction(std::shared_ptr<IEditorAction> const &pAction)
```suggestion
void CEditorHistory::RecordAction(const std::shared_ptr<IEditorAction> &pAction)
```

We [use](https://github.com/ddnet/ddnet/blob/03400f6ff384a9c8a64f3ebf26f1003858e362a1/src/game/server/gamecontext.h#L102) `const char *` instead of `char const *`, the same is [applicable](https://github.com/ddnet/ddnet/blob/03400f6ff384a9c8a64f3ebf26f1003858e362a1/src/engine/shared/json.h#L6) for structs/classes/whatever.

2023-11-01 20:07 UTC, Kaffeine commented on src/game/editor/mapitems/layer_tiles.h
> +using EditorTileStateChangeHistory = std::map<int, std::map<int, T>>;
Yeah, I see that but it took me five minutes (using GitHub interface) so I think it is worth it to add a comment for the `m_vTileChanges` member variable to save others time.

2023-11-01 20:12 UTC, Robyt3 commented on src/game/editor/editor_actions.h
> +	};
Enum classes seem good, but we'll have to have a discussion about whether we want to use `PascalCase` instead of `CONSTANT_CASE` for the enum literals.

2023-11-01 20:21 UTC, Robyt3 commented on src/game/client/ui.h
> +struct SUIEditResult
I don't think it's necessary or very useful to add a prefix to mark it as a templated type. Although it looks ugly, the correct case would be `SUiEditResult`, regardless of `UI` being an abbreviation. You could get rid of the `UI` in the name, making it just `SEditResult`.

2023-11-01 20:36 UTC, Kaffeine commented on src/game/editor/editor_actions.h
> +	};
Oh, indeed. I noticed new `enum class E<TypeName>` (a while ago) but I didn't remember that the constants are `UPPER_CASE`.

2023-11-11 15:14 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +	str_format(m_aDisplayText, sizeof(m_aDisplayText), "Edit layers group and order (x%d)", m_LayerIndices.size());
Either cast the argument to `int` to print it or use `PRIzu` to correctly print arguments of type `size_t` (see other uses in the code).

2023-11-15 20:58 UTC, Robyt3 requested changes

2023-11-15 20:58 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +		if(DoButton_FontIcon(&s_RedoButton, FONT_ICON_REDO, m_EnveloppeEditorHistory.CanRedo() ? 0 : -1, &Button, 0, "[Ctrl+Y] Redo last action", IGraphics::CORNER_R, 11.0f) == 1)
Do a replace all `Enveloppe` -> `Envelope` on the `src` folder, it appears in various places

2023-11-15 20:58 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +CEditorActionNewQuadOrSound::CEditorActionNewQuadOrSound(CEditor *pEditor, int GroupIndex, int LayerIndex, int x, int y) :
It would be better to split this into two actions, then it's easier to extend the code if more layer types are added in the future.

2023-11-15 20:58 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +	std::string Part = "layer";
`const char *pPart` instead of using `std::string`

2023-11-15 20:58 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +	std::string Part = "layer";
Also, the same code appears below again. I would add `virtual const char *TypeName() const = 0` to `CLayer`. Then every layer implementation overrides this function and returns the respective name and you only need to call `m_pLayer->TypeName()` here and below.

2023-11-15 21:25 UTC, furo321 commented
Why was the order of these buttons changed? I think it's best to not change it, so people don't accidentally click the wrong one by muscle memory.

Before,
![image](https://github.com/ddnet/ddnet/assets/141338449/97a69633-75f3-47bc-9f4a-f93d111270ef)

After,
![image](https://github.com/ddnet/ddnet/assets/141338449/d1ee0ffe-44d2-4d60-8c80-09418154c76b)

2023-11-18 23:01 UTC, heinrich5991 commented
Status: Looks active, maybe needs a review again. I'd hand this to @Robyt3 since he reviewed this before.

2023-11-25 11:07 UTC, Robyt3 requested changes
These buttons should be a bit larger so all text has the same size:

![1](https://github.com/ddnet/ddnet/assets/23437060/5c4d3a93-9ffe-48f0-ac9a-48b3468b6460)

2023-11-25 11:52 UTC, Robyt3 requested changes

2023-11-25 11:52 UTC, Robyt3 commented on src/game/mapitems.h
> +	struct SProp
I don't think these property enums should be in `src/game/mapitems.h`, they are only relevant for the editor so maybe you could add a new file in `src/game/editor/mapitems/`.

Also, use scoped enumerations everywhere instead of putting unnamed enums into a struct to give it a namespace:

```
enum class EQuadProp
{
	PROP_NONE = -1,
	...
};
```

The literals are then used like `EQuadProp::PROP_NONE`.

2023-11-25 11:52 UTC, Robyt3 commented on src/game/editor/mapitems/layer_speedup.h
> +	struct Data
`Data` -> `SData` in multiple places

2023-11-25 11:52 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +			dbg_msg("editor", "editing shape width: %d", NewVal);
Remove debug message

2023-11-25 11:52 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +		if(!(abs(CurrentTime - s_CurrentTime) < 0.0001f && abs(CurrentValue - s_CurrentValue) < 0.0001f))
Looks like it was already like this before, but it should be `absolute` instead of `abs`.

2023-11-25 15:53 UTC, archimede67 commented on src/game/mapitems.h
> +	struct SProp
Initially I wanted to keep the int values of those enums for simplicity. The prop trackers all inherit a base class, and that base class stores the prop as an int. It made things much more easier to handle, but there was no type safety so we could pass wrong props and also at some places I used magic number for specific props.

So I tried to use scoped enumerations everywhere like you suggested, and that adds a lot more complexity to the code. Indeed, I had to use templates to now specify the enum type we want for some of the methods and to all prop trackers as well. But in the end it works and provides type safety, the only inconvenience is that we need to specialize the templated function `DoPropertiesWithState` in `editor_props.cpp`, which is the reason why I moved this specific logic to that new file.

I hope its clear and good enough of a change

2023-12-04 20:29 UTC, Robyt3 requested changes
Looks good to me apart from #7544, which we need to solve or work around.

Please rebase on current master so codecov stops failing and commenting every line in the diff. Also squash the commits so we only have one commit adding the entire feature.

@Kaffeine What do you think from a modding perspective? Is this code flexible enough so that support for additional mapitems could be added without too much effort?

2023-12-04 20:30 UTC, Robyt3 commented on src/game/mapitems.h
> +	struct SProp
@heinrich5991 What do you think about the template instantiations at the end of `editor_props.cpp`? Are they acceptable like that or should we avoid them somehow?

2023-12-04 21:49 UTC, archimede67 commented
> Looks good to me apart from https://github.com/ddnet/ddnet/issues/7544, which we need to solve or work around.

@Robyt3 I have another PR (#7556) which could hopefully solve this issue by allowing rebinding commands such as editor commands (undo/redo and others), menus shortcuts, etc by making bind groups like you suggested.
Unfortunately, it is not quite ready yet as it requires more commands to be added (see #7559 nad #7560).

2023-12-09 17:38 UTC, def- approved these changes
@Robyt3 Let's submit this? I think https://github.com/ddnet/ddnet/issues/7544 is independent of this.

2023-12-09 18:17 UTC, Robyt3 approved these changes
Thanks a lot, @archimede67!

2023-12-09 18:34 UTC, merged