Fix client not quitting after graphics assertion, fix dead lock
ddnet/ddnet pull request #7416
Opened 2023-11-04 22:35 UTC by Robyt3

After the error message popup is shown for graphics assertions, the client window was destroyed but the process was not terminated properly. Now the graphics assertion error is handled like a normal assertion error, as those are also shown in an error message popup and correctly cause the client to break into the debugger or terminate.

The call to `WaitForIdle` is removed because this can cause deadlocks when `dbg_assert` is called from a code segment that owns the same lock that `WaitForIdle` uses. Waiting for the graphics to be idle before showing the error message popup does not seem to be necessary.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-11-04 22:55 UTC, def- requested changes

2023-11-04 22:55 UTC, def- commented on src/engine/client/backend_sdl.cpp
> +	dbg_assert(false, VerboseStr.c_str());
What good is a dbg_assert(false)?

2023-11-04 22:58 UTC, Robyt3 commented on src/engine/client/backend_sdl.cpp
> +	dbg_assert(false, VerboseStr.c_str());
It causes the dbg assert handler to be called, which shows a more detailed error message popup using the provided message:

https://github.com/ddnet/ddnet/blob/b60b14bf6115cf0042e81a342f6108cb07c1d810/src/engine/client/client.cpp#L4369-L4390

2023-11-04 23:01 UTC, Robyt3 commented on src/engine/client/backend_sdl.cpp
> +	dbg_assert(false, VerboseStr.c_str());
The call to `ShowMessageBox` already causes the window to be destroyed because showing popup messages doesn't work otherwise due to an SDL bug, so we should quit the client anyway because we can't continue without a window.

2023-11-04 23:14 UTC, def- approved these changes

2023-11-05 09:35 UTC, Robyt3 commented on src/engine/client/backend_sdl.cpp
> +	dbg_assert(false, VerboseStr.c_str());
That would fix the client not quitting on graphics assertions, but it doesn't fix that `dbg_assert` can cause dead locks depending on where the assert is triggered. Would also be better if we used `dbg_assert` here so the error message popup contains the addional information that's shown for normal assertions.

2023-11-05 09:35 UTC, Jupeyy commented on src/engine/client/graphics_threaded.cpp
> -	m_pBackend->WaitForIdle();
#6675

i am not sure about this tbh.

imagine it like this:
your GPU is rendering stuff and suddenly the whole heap just gets deleted xd (vulkan instance got destroyed)

We could ofc try to only destroy the surface, not the vk instance (https://github.com/ddnet/ddnet/blob/b60b14bf6115cf0042e81a342f6108cb07c1d810/src/engine/client/backend/vulkan/backend_vulkan.cpp#L5551-L5552)

but even for that i am not sure if we handle that well enough

2023-11-05 09:49 UTC, Jupeyy commented on src/engine/client/backend_sdl.cpp
> +	dbg_assert(false, VerboseStr.c_str());
well then remove the assert here?

the graphics calling itself by a hidden logic is simply always a problem.

i guess in the long run we should think about moving the displayed assert to a different place (a launcher or some restart logic or what so ever)

2023-11-05 09:51 UTC, Jupeyy commented on src/engine/client/backend_sdl.cpp
> +	dbg_assert(false, VerboseStr.c_str());
also a, i dunno if i'd call it clean but, way:
https://en.cppreference.com/w/cpp/thread/recursive_mutex

2023-11-05 09:59 UTC, Jupeyy commented on src/engine/client/backend_sdl.cpp
> +	dbg_assert(false, VerboseStr.c_str());
what if we simply replace this call with a std::exit or std::quick_exit?

2023-11-05 10:06 UTC, Robyt3 commented on src/engine/client/backend_sdl.cpp
> +	dbg_assert(false, VerboseStr.c_str());
True, this `dbg_assert` call could be moved to the engine client I guess, then the engine client can safely interact with the graphics. So the engine client would poll the graphics for fatal errors after rendering a frame and if an error it detected it can call `dbg_assert` without holding the graphics lock.

Then we just have to manually ensure in the future that `dbg_assert` is never used while holding a graphics lock.

2023-11-06 22:42 UTC, Robyt3 commented on src/engine/client/backend_sdl.cpp
> +	dbg_assert(false, VerboseStr.c_str());
I changed it so only the `dbg_assert` is delayed until the end of `RunBuffer` after the lock has been released, so it shouldn't cause a deadlock and the `WaitForIdle` call before showing the message box doesn't have to be removed.

2023-11-07 16:55 UTC, merged