Save unknown commands from `settings_ddnet.cfg`
ddnet/ddnet pull request #7427
Opened 2023-11-08 21:55 UTC by furo321

This fixes `Allow client to still save settings that it doesn't know about.` from #6660. Previously if you were to use a different client such as Tater-Client which shares the same config file as DDNet, the settings used from Tater-Client would be lost if you were to launch up DDNet again.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-11-08 23:10 UTC, def- approved these changes

2023-11-08 23:11 UTC, def- commented on src/engine/client/client.cpp
> +		if(!pConsole->ExecuteFile(CONFIG_FILE, IConsole::CLIENT_ID_SETTINGS_DDNET))
why is this a client id?

2023-11-08 23:23 UTC, heinrich5991 commented on src/engine/config.h
> +	std::vector<std::string> m_vUnknownCommands;
An interface should not have a member variable.

2023-11-09 16:34 UTC, furo321 commented on src/engine/client/client.cpp
> +		if(!pConsole->ExecuteFile(CONFIG_FILE, IConsole::CLIENT_ID_SETTINGS_DDNET))
I decided on reusing the `ClientID` argument because it was simpler than adding an extra argument that would save the unknown commands to all the functions that are called from `ExecuteFile`.

2023-11-09 16:36 UTC, furo321 commented on src/engine/config.h
> +	std::vector<std::string> m_vUnknownCommands;
Fixed, it's now moved to `CConfigManager`

2023-11-09 18:12 UTC, Robyt3 requested changes

2023-11-09 18:12 UTC, Robyt3 commented on src/engine/shared/config.h
> +	std::vector<std::string> m_vUnknownCommands;
Add the required includes `<vector>` and `<string>` directly to this file.

2023-11-09 18:12 UTC, Robyt3 commented on src/engine/config.h
> +#include <vector>
Remove unused include

2023-11-09 18:12 UTC, Robyt3 commented on src/engine/shared/console.cpp
> +					m_pConfigManager->m_vUnknownCommands.emplace_back(pStr);
Encapsulate this with a function, e.g. `IConfigManager::StoreUnknownCommand(const char *pCommand)`.

2023-11-09 18:12 UTC, Robyt3 commented on src/engine/shared/console.cpp
> +	m_pConfigManager = (CConfigManager *)Kernel()->RequestInterface<IConfigManager>();
Remove the down cast by encapsulating `m_vUnknownCommands` instead.

2023-11-09 18:12 UTC, Robyt3 commented on src/engine/shared/console.h
> +	CConfigManager *m_pConfigManager;
Use the interface by encapsulating `m_vUnknownCommands `

2023-11-09 18:12 UTC, Robyt3 commented on src/engine/shared/config.cpp
> +	for(auto const &Command : m_vUnknownCommands)
`const auto`

2023-11-09 18:17 UTC, heinrich5991 commented
Sorry for the late remark. We already have an "unknown command handler". I think it should be used instead of putting the code in the console.

2023-11-09 20:21 UTC, Kaffeine commented
Oh, I'm surpriced this is even acceptable.

A mod client can use its own config file, and I thought we want to keep the `.cfg` file clear.

2023-11-09 20:38 UTC, Jupeyy commented
> A mod client can use its own config file and I thought we want to keep the `.cfg` file clear.

if you ask me that makes sense anyway and should be done regardless. maybe we should even have a engine.cfg in ddnet.

That makes it easier to just tell ppl to delete their config file without loosing binds etc. and also makes it a bit clearer logical wise

2023-11-09 23:12 UTC, def- commented
It's also useful when switching between old and new DDNet client versions.

2023-11-11 17:59 UTC, Robyt3 commented on src/engine/shared/config.h
> +#include <vector>
It's better to also add the `<string>` include. Right now it only compiles because other files include `<string>` before this header is included.

2023-11-11 18:20 UTC, Robyt3 approved these changes
Thanks!

2023-11-11 18:51 UTC, merged

2023-11-11 19:00 UTC, ChillerDragon commented
amazing thanks @furo321