Appending in editor checks for duplicate images
ddnet/ddnet pull request #7451
Opened 2023-11-13 20:49 UTC by apelsin21

To fix issue  #7399 that appending maps in editor may duplicate images

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-11-14 17:21 UTC, Robyt3 requested changes
Anyone else got objections if we assume that images with the same name are duplicates or should we check for identical image data and rename the duplicate images if necessary? Same should apply to sounds.

2023-11-14 17:21 UTC, Robyt3 commented on src/game/editor/editor.cpp
>  	NewMap.m_vpImages.clear();
Also move this line up, after the `for` loop, so all the image related code is all together in one block.

(and remove second empty line)

2023-11-14 17:21 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +	static const auto &&s_replaceDuplicateImageIndex = [](int ToReplace, int ReplaceWith) {
`s_ReplaceIndex`

2023-11-14 17:21 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +			m_Map.m_vpImages.push_back(*NewMapIt);
Use `pNewImage`

2023-11-15 12:30 UTC, apelsin21 commented
Im thinking that this feature is only for convenience. Any maps that are submitted for official servers etc will be vetted in some way for images that are duplicates, so there's no reason to do a deeper comparison

Although ofc it would be nice to check sounds etc too

2023-11-18 23:05 UTC, heinrich5991 commented
> Anyone else got objections if we assume that images with the same name are duplicates or should we check for identical image data and rename the duplicate images if necessary?

Sounds ok to me.

2023-11-18 23:07 UTC, heinrich5991 commented
Rebased.

2023-11-18 23:11 UTC, def- approved these changes

2023-11-18 23:42 UTC, merged