Use Escape to cancel OP_SCALE envelope
ddnet/ddnet pull request #7456
Opened 2023-11-14 14:22 UTC by apelsin21

https://github.com/ddnet/ddnet/issues/7435

Now escape and right click should behave the same and fixes issue

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-11-14 17:11 UTC, Robyt3 requested changes
Adding a variable that's only set when the envelope editor is rendered seems brittle and will likely break in edge cases, like when you exit the editor with Ctrl+Shift+E or any other way where the envelope editor is not rendered anymore.

Try to use `UI()->ConsumeHotkey(CUI::HOTKEY_ESCAPE)`, which ensures that the escape hotkey is not handled multiple times. However, you need to ensure that the call to `ConsumeHotkey` for the escape hotkey that exits the editor comes last when rendering, so this use of the hotkey has the lowest priority. See how it's done in the menus:

https://github.com/ddnet/ddnet/blob/a329417dee5002bf4c31ef6b5e0fde5d4920e0d8/src/game/client/components/menus.cpp#L1784-L1790

2023-11-14 19:22 UTC, apelsin21 reviewed
i try

2023-11-14 20:03 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +
Move this down below the calls to `RenderPopupMenus` and `FreeDynamicPopupMenus`, then you should also be able to remove `&& !UI()->IsPopupOpen()` from the if-condition, since popup menus are then already handled before the quit button.

2023-11-14 22:22 UTC, Robyt3 approved these changes
Thanks.

2023-11-14 22:43 UTC, merged

2023-11-15 08:40 UTC, ChillerDragon commented
Thanks! ❤️