Add icon URL, remove `servers-key`/`ranks-key` from community JSON
ddnet/ddnet pull request #7459
Opened 2023-11-15 17:58 UTC by heinrich5991

Previously:

```json
{
  "ddnet": {
    "name": "DDraceNetwork",
    "servers-key": "servers",
    "ranks-key": "maps",
    "icon-sha256": "162313eeb954e34495ad03066fee1418ed3c963e76cc83dff993e1c7856c742b"
  }
}
```

Now:
```json
{
  "ddnet": {
    "name": "DDraceNetwork",
    "icon": {
      "sha256": "162313eeb954e34495ad03066fee1418ed3c963e76cc83dff993e1c7856c742b",
      "url": "https://info.ddnet.org/icons/ddnet.png"
    },
    "ranks": [
      …
    ],
    "servers": {
      …
    }
  }
}
```

Special case `ddnet` to look for the `servers`, `maps` in the top-level and `kog` to look for `servers-kog` in the top-level.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-11-15 18:02 UTC, heinrich5991 commented
Thoughts:

1) Should we maybe make communities an array instead of an object?
2) Should we maybe make a new info endpoint instead of adding backcompat for the ddnet/kog communities?
3) The downloaded file should probably be checked against the specified SHA256 and be ignored if it doesn't match.

2023-11-15 20:29 UTC, Robyt3 requested changes
> Should we maybe make communities an array instead of an object?

Yes, probably better. Seems like our parser preserves the order of the objects, but the standard specifies that json objects are unordered collections of name/value pairs. I wanted the order of communities to be defined by us, so we should use an array instead.

> Should we maybe make a new info endpoint instead of adding backcompat for the ddnet/kog communities?

Probably also a good idea if we eventually want to move the legacy non-DDNet servers like fng to their own communities but still preserve the old DDNet and KoG communities for old client versions.

> The downloaded file should probably be checked against the specified SHA256 and be ignored if it doesn't match.

Agreed.

2023-11-16 23:58 UTC, heinrich5991 commented on src/engine/client/serverbrowser.cpp
> +				net_addr_from_str(&NetAddr, Address.u.string.ptr);
Fixed (was broken before my PR :P).

2023-11-16 23:58 UTC, heinrich5991 commented on src/engine/client/serverbrowser.cpp
> +			if(str_comp(pCommunityId, "ddnet") == 0)
Done.

2023-11-16 23:58 UTC, heinrich5991 commented on src/engine/client/serverbrowser.cpp
> +			if(str_comp(pCommunityId, "ddnet") == 0)
Done.

2023-11-16 23:59 UTC, heinrich5991 commented on src/engine/client/serverbrowser.cpp
> +			if(str_comp(pCommunityId, "ddnet") == 0)
Done.

2023-11-17 00:01 UTC, heinrich5991 commented
> > Should we maybe make communities an array instead of an object?
> 
> Yes, probably better. Seems like our parser preserves the order of the objects, but the standard specifies that json objects are unordered collections of name/value pairs. I wanted the order of communities to be defined by us, so we should use an array instead.

Done.

> > Should we maybe make a new info endpoint instead of adding backcompat for the ddnet/kog communities?
> 
> Probably also a good idea if we eventually want to move the legacy non-DDNet servers like fng to their own communities but still preserve the old DDNet and KoG communities for old client versions.

Not done, I figured it might not be worth the complexity. It'll mean fng servers will move out of the DDNet tab for older clients, but I wouldn't call that too bad.

> > The downloaded file should probably be checked against the specified SHA256 and be ignored if it doesn't match.
> 
> Agreed.

I opened an issue: #7485.

2023-11-17 09:40 UTC, def- commented
Hm, not sure if we should introduce the possibility for server hosters to get IPs of all players. Or do we plan to keep all of them at info.ddnet.org?

2023-11-17 16:58 UTC, heinrich5991 commented
> Hm, not sure if we should introduce the possibility for server hosters to get IPs of all players. Or do we plan to keep all of them at info.ddnet.org?

Yes, info.ddnet.org.

2023-11-18 16:54 UTC, Robyt3 commented on src/engine/client/serverbrowser.cpp
> +	return false;
The return value is unused. I'd also prefer `true` being success for new code.

2023-11-18 17:01 UTC, Robyt3 commented on src/engine/client/serverbrowser.cpp
> +bool CServerBrowser::ParseCommunityFinishes(CCommunity *pCommunity, const json_value &Finishes)
`true` for success, or remove return value and only skip invalid entries.

2023-11-18 17:52 UTC, heinrich5991 commented on src/engine/client/serverbrowser.cpp
> +	return false;
Fixed, changed to `true` for success.

2023-11-18 17:52 UTC, heinrich5991 commented on src/engine/client/serverbrowser.cpp
> +bool CServerBrowser::ParseCommunityFinishes(CCommunity *pCommunity, const json_value &Finishes)
Fixed, changed to true for success.

2023-11-18 19:58 UTC, def- approved these changes

2023-11-18 19:59 UTC, def- commented
I guess we should update the server too for tomorrow's nightly.

2023-11-18 19:59 UTC, Robyt3 commented
@heinrich5991 Changes from the last comments seem to be missing.

2023-11-18 20:55 UTC, Robyt3 approved these changes
Thanks!

2023-11-18 21:24 UTC, merged