Use GetDDRaceTeam()
ddnet/ddnet pull request #7464
Opened 2023-11-15 20:28 UTC by ChillerDragon

2023-11-15 20:33 UTC, Robyt3 approved these changes

2023-11-15 20:42 UTC, Kaffeine commented
Well. This is all good and right but why you dropped the changes moving CGameTeams from the mod controller to the base controller class (`IGameController`)?

I'd repeat the key point from [my message](https://github.com/ddnet/ddnet/pull/7453#issuecomment-1810867298): it makes no sense to keep CGameTeams in the mod controller and have core classes depending on it.

2023-11-15 22:01 UTC, ChillerDragon commented
> Well. This is all good and right but why you dropped the changes moving CGameTeams from the mod controller to the base controller class (`IGameController`)?
> 
> I'd repeat the key point of [my message](https://github.com/ddnet/ddnet/pull/7453#issuecomment-1810867298): it makes no sense to keep CGameTeams in the mod controller and have core classes depending on it.

Because I want this merged and heinrich and robi somehow have a problem with moving it. So I opend a discussion issue https://github.com/ddnet/ddnet/issues/7465

2023-11-15 22:09 UTC, heinrich5991 commented
@ChillerDragon Sorry, I miscommunicated there. I think the other pull request together with what @Kaffeine said is fine.

2023-11-15 22:17 UTC, ChillerDragon commented
> @ChillerDragon Sorry, I miscommunicated there. I think the other pull request together with what @Kaffeine said is fine.

So moving teams would also get merged. Or is something else needed? No idea what "with what @Kaffeine said" is.

2023-11-15 22:23 UTC, heinrich5991 commented
Basically #7453 plus this.

2023-11-16 09:36 UTC, ChillerDragon commented
Okay added https://github.com/ddnet/ddnet/pull/7453 and also replaced `m_Teams` with `Teams()` so later this can be changed updated more easily. If for example we want this to be controlled by a custom controller. Or teams move once again or get renamed.

2023-11-16 17:10 UTC, Robyt3 requested changes
Some nits, but after some consideration I'm generally fine with moving the teams component to `IGameController`.

2023-11-16 17:10 UTC, Robyt3 commented on src/game/server/save.cpp
> +	CGameTeams *pTeams = &pController->m_Teams;
Use `Teams()` instead of `m_Teams`. I think that's cleaner and maybe we can remove the `friend class CSaveTeam` in the future (which is currently prevented by this and likely other accesses to private members).

2023-11-16 17:10 UTC, Robyt3 commented on src/game/server/save.cpp
> +	CGameTeams *pTeams = &pController->m_Teams;
`Teams()`

2023-11-16 17:20 UTC, Kaffeine commented on src/game/server/gamemodes/DDRace.cpp
>  }
Mhm, the 3rd option 'll keep the API as is, reducing the conflicts for the mods currently relying it 👀.
I [imported and used](https://github.com/infclass/teeworlds-infclassR/commit/952706f312ae7bc7c79179fbe00b63c2a03d92ef) that API for infclass.

2023-11-16 17:29 UTC, ChillerDragon commented
Done good catches @Robyt3 as always

2023-11-16 17:32 UTC, Kaffeine commented on src/game/server/gamemodes/DDRace.cpp
>  }
Yet, API-wise, it makes no sense to have both `GameServer()->GetDDRaceTeam()` and `GameController::GetPlayerTeam()` exposing the same player property.

I ignored/dropeed GameContext::GetDDRaceTeam because it is explicitly named as mod specific, and I don't need race teams in the mod.
On the other hand, it is also an issue with GameController because it exposes PlayerTeam different from the expected RED/BLUE/SPEC.

2023-11-16 17:39 UTC, Kaffeine commented on src/game/server/gamemodes/DDRace.cpp
>  }
@Robyt3, @heinrich5991, what would you say about "collision team" term replacing all three DDRaceTeam and PlayerTeam / GameTeam?

IMO it is the best option. I can do it in the next PR so we won't make @ChillerDragon working on that for another week. 😄 😇 

I want to open a merge request, renaming CGameTeam team getters to GetCollisionTeam(). BTW, do you want to also drop the `Get` prefix here? I can also rename the classes CTeamsCore to CTeamsCollisionCore.

Probably `CGameTeam` can/should stay as-is because it manages DDRace teams with swaps/locks/practice etc.

2023-11-16 17:52 UTC, Kaffeine commented
@Robyt3, @heinrich5991, what would you say about "collision team" term replacing all three DDRaceTeam and PlayerTeam / GameTeam? RED/BLUE/SPEC getters/setters/terms 'll be kept as-is.

IMO it is the best option. I can do it in the next PR so we won't make @ChillerDragon working on that for another week. 😄 😇

I want to open a merge request, renaming CGameTeam team getters to GetCollisionTeam(). BTW, do you want to also drop the Get prefix here? I can also rename CTeamsCore class to CTeamsCollisionCore (I'll double check if it makes sense; I have no IDE right now to say it for sure).

Probably CGameTeam can/should stay as-is because it manages DDRace teams with swaps/locks/practice etc.

2023-11-16 20:11 UTC, heinrich5991 commented
It's not really a team, from the perspective of the world, no? It's more like separate game worlds. Maybe simply `Instance(ID)`?

2023-11-18 11:23 UTC, ChillerDragon commented
rebased :rocket:

2023-11-18 11:32 UTC, Kaffeine commented on src/game/server/ddracecommands.cpp
> +	if((pController->Teams().m_Core.Team(Target) && pController->Teams().GetDDRaceState(pSelf->m_apPlayers[Target]) == DDRACE_STARTED) || (pChr && pController->Teams().IsPractice(pChr->Team())))
GetDDRaceTeam

2023-11-18 11:34 UTC, Kaffeine commented on src/game/server/gamecontext.cpp
> +			m_TeeHistorian.RecordPlayerTeam(i, pController->Teams().m_Core.Team(i));
GetDDRaceTeam

2023-11-18 12:53 UTC, ChillerDragon commented
squashed :rocket:

2023-11-18 13:00 UTC, Kaffeine commented
@heinrich5991

> It's more like separate game worlds. Maybe simply `Instance(ID)`?

What's about the super team? Also, do we consider 'solo parts' as extra worlds? The teams (`GetDDRaceTeam()`) are used outside of the GameWorld e.g. to determine the recipients of `say_team` messages.

There are `CCharacter::SameTeam()` and `CCharacter::CanCollide()` which can return all possible combinations depending on the conditions (the same team and different team members sometimes can collide and sometimes they can't).

A bit more of the context: In Infclass the players of *different* teams always *has collisions*, and the players of the *same* team has *no collisions* with each other by default. This behavior is wanted to ensure that teammates don't bother each other (and it is an extention of the "no friendly fire" idea). I also had to put the two (always colliding) groups (humans and the infected) to different teams to make other things (e.g. team chat) working properly.

I still doubt that infclass use-case fit into the CGameTeams concept but in fact it allows to have one customization point instead of many changes across the codebase.

Having that said, I don't like my own idea of the `GetDDRaceTeam()` -> `GetCollisionTeam()` renaming anymore, as it won't make the code more readable/understandable. Meh.

2023-11-18 13:02 UTC, ChillerDragon commented
@Kaffeine i think it would make sense to move that discussion to an issue -.-

2023-11-18 13:03 UTC, Kaffeine commented
The code looks good to me. :+1:

2023-11-18 13:04 UTC, Kaffeine commented
> @Kaffeine i think it would make sense to move that discussion to an issue -.-

I think I'll leave it as-is for now. I've no idea for a better name, and the current name fits this codebase more or less.

2023-11-18 13:41 UTC, heinrich5991 approved these changes
Thanks.

2023-11-18 13:55 UTC, ChillerDragon commented
> Thanks.

No thank you :heart:

2023-11-18 13:55 UTC, ChillerDragon commented
also thanks @Kaffeine and @Robyt3 for the findings :)

2023-11-18 13:57 UTC, merged