Use the first ShowDistance packet to calculate ZoomScale.
ddnet/ddnet pull request #7512
Opened 2023-11-20 15:03 UTC by furo321

Don't use `1400.0f` and `800.0f` as it varies depending on which screen resolution you have. It now uses the values of the first `ShowDistance` packet, which will be default zoom. As pointed out by @0xfaulty in #7511.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-11-20 16:04 UTC, heinrich5991 commented
Why does this need to capture an initial zoom state? Why is it not just the sent position? Maybe you can fix the sent position instead?

2023-11-20 16:17 UTC, furo321 commented
Wouldn't my change be better? As it stays compatible with older clients that support the ShowDistance netmsg?

2023-11-20 16:28 UTC, heinrich5991 commented
Adding more hacks on top of others when it's not necessary wouldn't be my preference, no.

2023-11-20 23:46 UTC, 0xfaulty commented
> Why does this need to capture an initial zoom state? Why is it not just the sent position? Maybe you can fix the sent position instead?

If we could send cursor position somewhere, it could simplify a lot of things for me, because this pr wil not work for dummy zoom for example, now in my case I should to check connected players, and if that is dummy (same ip address) copy this initial zoom settings to player settings..

2023-11-20 23:49 UTC, heinrich5991 commented
Ah, the problem is that the sent input isn't actually the cursor position wrt. the world, but with respect to some other coordinate system?

2023-11-20 23:51 UTC, 0xfaulty commented
Ye, cursor always sent without zoom shift

2023-11-21 04:13 UTC, heinrich5991 commented on src/game/client/components/controls.cpp
> +		m_aInputData[g_Config.m_ClDummy].m_TargetY = m_aInputData[g_Config.m_ClDummy].m_TargetY * m_pClient->m_Camera.m_Zoom;
This looks like it's changing the mouse pos of the dummy while zooming, while the dummy is inactive.

2023-11-21 11:49 UTC, 0xfaulty commented on src/game/ddracechat.h
> +CHAT_COMMAND("tc", "?r[player name]", CFGFLAG_CHAT | CFGFLAG_SERVER, ConTeleCursor, this, "Teleport yourself to player or to where you are spectating/or looking if no player name is given")
Seems need to update commands description

2023-11-21 13:54 UTC, heinrich5991 commented on src/game/client/components/controls.cpp
> +		m_aInputData[g_Config.m_ClDummy].m_TargetY = m_aInputData[g_Config.m_ClDummy].m_TargetY * m_pClient->m_Camera.m_Zoom;
Say your dummy's mouse pos is (100, 100), default zoom. You send (100, 100) for your dummy. Your main tee is active, you zoom out 2x. Now your dummy's mouse position gets sent as (200, 200) even though your dummy wasn't even active.

2023-11-23 07:15 UTC, furo321 commented on src/game/client/components/controls.cpp
> +		m_aInputData[g_Config.m_ClDummy].m_TargetY = m_aInputData[g_Config.m_ClDummy].m_TargetY * m_pClient->m_Camera.m_Zoom;
I'm sorry, but I don't think I understand what you mean. The MousePos or Target value changes when dummy is inactive.

https://github.com/ddnet/ddnet/assets/141338449/2a9e1fde-46d4-4e66-a26e-a1ac2fece701

2023-11-26 10:10 UTC, Robyt3 requested changes

2023-11-26 10:10 UTC, Robyt3 commented on src/game/client/components/controls.cpp
> +		m_aInputData[g_Config.m_ClDummy].m_TargetY = m_aInputData[g_Config.m_ClDummy].m_TargetY * m_pClient->m_Camera.m_Zoom;
Would be more readable to use `*=` here, I had to double-check that the same operand is used.

2023-11-26 10:10 UTC, Robyt3 commented on src/game/server/ddracecommands.cpp
> +			Pos = Pos + vec2(pChr->Core()->m_Input.m_TargetX, pChr->Core()->m_Input.m_TargetY);
Use `Pos += ...`

2023-11-26 10:10 UTC, Robyt3 commented on src/game/server/ddracechat.cpp
> +		Pos = Pos + vec2(pChr->Core()->m_Input.m_TargetX, pChr->Core()->m_Input.m_TargetY);
Use `Pos += ...`

2023-11-26 11:45 UTC, def- approved these changes

2023-11-30 19:41 UTC, Robyt3 approved these changes
Please rebase on master so the codecov check doesn't fail anymore.

2023-11-30 21:35 UTC, furo321 commented
Sure, rebased!

2023-12-01 16:52 UTC, merged