Add finish info messages from 0.7
ddnet/ddnet pull request #7515
Opened 2023-11-20 20:22 UTC by furo321

This adds showing finishes alongside kill messages (now renamed to info messages), like in 0.7 and a few older race clients.

![image](https://github.com/ddnet/ddnet/assets/141338449/0e3cf787-f8d2-45db-a8f3-d967291b771b)

![image](https://github.com/ddnet/ddnet/assets/141338449/e447e6d0-2f0d-4520-88c5-cf5ac3137ea2)

Also now with the new `Sv_RaceFinish` packet, we could also localize finish messages just like in 0.7 and move away from parsing finish messages.

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-11-20 20:25 UTC, ChillerDragon commented
Omg thanks! That was on my todo!

2023-11-20 20:28 UTC, heinrich5991 commented
It seems we already have a packet for transmitting race times. Could that be reused?

2023-11-20 20:28 UTC, ChillerDragon commented
Is it using the same arguments as the 0.7 message?

2023-11-20 20:50 UTC, ChillerDragon commented
Could we not make that a ddnet ex message, but a normal vanilla net message instead? And then use the message id from the protocol7:: namespace. This then would not require any translation code for client and server bridges anymore.

2023-11-20 20:56 UTC, Robyt3 commented
CC #5623

2023-11-20 21:14 UTC, heinrich5991 commented
> Could we not make that a ddnet ex message, but a normal vanilla net message instead?

No, we use UUIDs in order to guarantee not clashing. The 0.7 support can translate it to the relevant number if it wants to.

2023-11-20 23:54 UTC, ChillerDragon commented
> > Could we not make that a ddnet ex message, but a normal vanilla net message instead?
> 
> 
> 
> No, we use UUIDs in order to guarantee not clashing. The 0.7 support can translate it to the relevant number if it wants to.

Clashing with who?

2023-11-21 00:27 UTC, heinrich5991 commented
This message is primarily for DDNet clients. We're not going to implement the 0.7 protocol for DDNet client-server connections.

If Teeworlds adopts a similar way of adding messages that ensure that there are no clashes, we could implement their IDs, but not for numeric ones.

2023-11-21 00:41 UTC, ChillerDragon commented
> This message is primarily for DDNet clients. We're not going to implement the 0.7 protocol for DDNet client-server connections.

You rather implement a big if statement saying if sixup send this message if ddnet send that message? When you could just send the same message to both?

I am still wondering what clash you are talking about. For what purpose were the ids held free if they are not used when they actually can be shared with the upstream protocol?

2023-11-21 00:46 UTC, ChillerDragon commented
> If Teeworlds adopts a similar way of adding messages that ensure that there are no clashes, we could implement their IDs, but not for numeric ones.

Does not seem related to this discussion. What is this referring to? 0.8? Sounds good to implement that system if it ever gets added. My questions for why holding back numeric IDs still stands.

2023-11-21 00:55 UTC, heinrich5991 commented
I do not want to add numeric IDs. I like that we're doing stuff here that's good on a theoretical level. No need to introduce hacks here.

2023-11-21 00:57 UTC, ChillerDragon commented
> 0.7 code should be implemented in a way that it is easy to remove. We should not add dependencies to 0.7 code.

Unlike clashes this seems like a reasonable argument for not implementing my suggestion. I still think it is worth to implement game message ids 35-39 in ddnet natively and fully compatible with 0.7. If the dependency is such a problem for you then make it not a 0.7 dependency. Just 0.7 complaint. Not sure why you would like to remove 0.7 code but if you want to get rid of it you still can delete the protocol7:: namespace and keep the messages 35-39 under a different name as native ddnet. Or add them under a different name than 0.7 in the first place if that seems better to you. You can also generate them from the 0.6 python code as long as they can be sent to 0.7 clients.

Reimplementing the same protocol under a different name and with different ids so every message has to be prepared differently in the code for 0.6 and 0.7 connections seems wrong. And should not be justified by a dependency on 0.7 code (which can also be achieved independently)

2023-11-21 01:05 UTC, ChillerDragon commented
> I do not want to add numeric IDs. I like that we're doing stuff here that's good on a theoretical level. No need to introduce hacks here.

You are against using numeric IDs because they are a hack? Wasn't the ddnet message system invented to keep those numerical IDs free to not clash with the upstream? So ddnet then can implement the upstream protocol at those IDs?

Duplicating a protocol implementation does not sound good on a theoretical level to me.

Implementing the 0.7 protocol natively without clashing with 0.6 does not sound like a hack to me.

2023-11-21 01:15 UTC, ChillerDragon commented
> This message is primarily for DDNet clients. We're not going to implement the 0.7 protocol for DDNet client-server connections.

If you are saying 0.7 code should stay removable and ddnet should not move towards 0.7 that sounds like you are trying to hard fork ddnet. So that it stays in 0.6 and is no longer compatible with teeworlds.

I thought teeworlds compatibility was one of the goals of the project? Or did I mistake your ambition for backwards compatibility with teeworlds compatibility?

2023-11-21 01:25 UTC, ChillerDragon commented
> This message is primarily for DDNet clients. We're not going to implement the 0.7 protocol for DDNet client-server connections.

But this pull request is implementing exactly that. A 0.7 message for ddnet client-server connections. At least payload wise. So why not make it easier to work with and more compatible by also using the same message ID. What is your problem with implementing the 0.7 protocol for ddnet client-server connections?

2023-11-21 14:29 UTC, heinrich5991 reviewed
Looks mostly good to me.

2023-11-21 14:29 UTC, heinrich5991 commented on src/game/variables.h
> +MACRO_CONFIG_INT(ClShowFinishMessages, cl_showfinishmessages, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show kill messages")
I'd not add a separate setting for finish messages, one setting for hiding the whole thing in the top right should suffice. If we decide to add it anyway:
```suggestion
MACRO_CONFIG_INT(ClShowFinishMessages, cl_show_finish_messages, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show finish messages")
```

2023-11-21 14:29 UTC, heinrich5991 commented on src/game/client/components/infomessages.cpp
> +void CInfoMessages::CreateKillmessageNamesIfNotCreated(CInfoMsg *pInfoMsg)
```suggestion
void CInfoMessages::CreateNamesIfNotCreated(CInfoMsg *pInfoMsg)
```
This seems to be called for both finish and kill messages.

2023-11-21 14:31 UTC, heinrich5991 commented
> What is your problem with implementing the 0.7 protocol for ddnet client-server connections?

Because that's not the goal here. We don't try to stay/become as compatible as possible with the 0.7 protocol.

Acceptance of #5949 does not mean you get to pester every PR author for 0.7 support. In fact, please stop it. This is what was feared by the people being against #5949.

2023-11-21 15:20 UTC, ChillerDragon commented
> Because that's not the goal here. We don't try to stay/become as compatible as possible with the 0.7 protocol.

Why not? It is a simple change that that reduces code complexity in the current server bridge implementation.

Instead of this

```C++
		CNetMsg_Sv_RaceFinish RaceFinishMsg;
		RaceFinishMsg.m_ClientID = ClientID;
		RaceFinishMsg.m_Time = Time * 1000;
		RaceFinishMsg.m_Diff = 0;
		if(pData->m_BestTime)
		{
			RaceFinishMsg.m_Diff = Diff * 1000 * (Time < pData->m_BestTime ? -1 : 1);
		}
		RaceFinishMsg.m_RecordPersonal = (Time < pData->m_BestTime || !pData->m_BestTime);
		RaceFinishMsg.m_RecordServer = Time < GameServer()->m_pController->m_CurrentRecord;
		Server()->SendPackMsg(&RaceFinishMsg, MSGFLAG_VITAL | MSGFLAG_NORECORD, -1);
	}
	else
	{
		protocol7::CNetMsg_Sv_RaceFinish Msg;
		Msg.m_ClientID = ClientID;
		Msg.m_Time = Time * 1000;
		Msg.m_Diff = 0;
		if(pData->m_BestTime)
		{
			Msg.m_Diff = Diff * 1000 * (Time < pData->m_BestTime ? -1 : 1);
		}
		Msg.m_RecordPersonal = (Time < pData->m_BestTime || !pData->m_BestTime);
		Msg.m_RecordServer = Time < GameServer()->m_pController->m_CurrentRecord;
		Server()->SendPackMsg(&Msg, MSGFLAG_VITAL | MSGFLAG_NORECORD, -1);
	}
```

We could just have this

```C++

		protocol7::CNetMsg_Sv_RaceFinish Msg;
		Msg.m_ClientID = ClientID;
		Msg.m_Time = Time * 1000;
		Msg.m_Diff = 0;
		if(pData->m_BestTime)
		{
			Msg.m_Diff = Diff * 1000 * (Time < pData->m_BestTime ? -1 : 1);
		}
		Msg.m_RecordPersonal = (Time < pData->m_BestTime || !pData->m_BestTime);
		Msg.m_RecordServer = Time < GameServer()->m_pController->m_CurrentRecord;
		Server()->SendPackMsg(&Msg, MSGFLAG_VITAL | MSGFLAG_NORECORD, -1);
```

It makes ripping 0.7 code out even easier because it does not require its own if branch anymore.

2023-11-21 16:10 UTC, heinrich5991 commented
Feel free to continue the 0.7 message discussion in #5949, but not here.

2023-11-21 16:15 UTC, Robyt3 requested changes

2023-11-21 16:15 UTC, Robyt3 commented on src/game/client/components/infomessages.h
> +		int m_Type;
Add `enum EType` with `TYPE_KILL` and `TYPE_FINISH` literals inside `CInfoMsg` instead of using an `int`.

2023-11-21 16:15 UTC, Robyt3 commented on src/game/client/components/infomessages.h
> +		char m_TimeText[32];
`m_aTimeText`

2023-11-21 16:15 UTC, Robyt3 commented on src/game/client/components/infomessages.h
> +		char m_DiffText[32];
`m_aDiffText`

2023-11-21 16:15 UTC, Robyt3 commented on src/game/client/components/infomessages.h
> +		int m_RecordServer;
These variables can be `bool` instead of `int`. It also looks like only one of the variables is necessary right, as there is no different behavior for personal and server records.

2023-11-21 16:15 UTC, Robyt3 commented on src/game/client/components/infomessages.h
> +		int m_Time;
`m_Time` is currently unused.

2023-11-21 16:15 UTC, Robyt3 commented on src/base/system.cpp
> +		return str_format(buffer, buffer_size, "0:%02" PRId64 ".%02" PRId64, (centisecs % min) / sec, centisecs % sec);
If the format is kept, then the respective tests need to be fixed as well.

2023-11-21 16:42 UTC, VoxelDoesCode commented
This implies that we can have more options for info messages now. I wonder if in the future there would be more icons for what type of action you took (like leaving the server).

2023-11-21 16:46 UTC, furo321 commented on src/game/variables.h
> +MACRO_CONFIG_INT(ClShowFinishMessages, cl_showfinishmessages, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show kill messages")
I decided on keeping the config, but fixed the config name and description.

2023-11-21 17:28 UTC, Robyt3 commented on src/test/str.cpp
> +	EXPECT_STREQ(aBuf, "34.56");
Changing the expected value is not correct here, this test case seems to test the outwith when given an invalid time format. We should use an `enum` so it's impossible to pass an incorrect time format to the time functions and remove this test case.

2023-11-21 17:39 UTC, heinrich5991 commented on src/test/str.cpp
> +	EXPECT_STREQ(aBuf, "34.56");
`enum`s cannot guarantee that in C/C++.

2023-11-21 17:51 UTC, furo321 commented on src/test/str.cpp
> +	EXPECT_STREQ(aBuf, "34.56");
I changed it to `TIME_SECS_CENTISECS + 1`, so it's the same as previously.

2023-11-22 19:40 UTC, Robyt3 requested changes

2023-11-22 19:40 UTC, Robyt3 commented on src/game/client/components/infomessages.h
> +		float m_aDiffTextWidth;
No `a` prefix here

2023-11-24 18:13 UTC, Robyt3 approved these changes

2023-11-24 22:07 UTC, ChillerDragon commented
Yo @heinrich5991 

> The if branch you wrote shouldn't be added.

was referring to this right?

https://github.com/furo321/ddnet/blob/ff5db9b1061e53aa8a9cca7d441bbb276985d03a/src/game/server/teams.cpp#L774-L799

I feel like merging the pr decides the outcome of https://github.com/ddnet/ddnet/issues/7518 on whether we want to use the protocol7 ids or duplicate 0.7 messages as ddnet ex messages.

Sorry for pointing this out again but since @Robyt3 approved I wanted to mention this so everyone is aware.

2023-11-29 09:25 UTC, edg-l commented
> > This message is primarily for DDNet clients. We're not going to implement the 0.7 protocol for DDNet client-server connections.
> 
> If you are saying 0.7 code should stay removable and ddnet should not move towards 0.7 that sounds like you are trying to hard fork ddnet. So that it stays in 0.6 and is no longer compatible with teeworlds.
> 
> I thought teeworlds compatibility was one of the goals of the project? Or did I mistake your ambition for backwards compatibility with teeworlds compatibility?

Where is this goal stated? I like 0.7 should be easily removable, in fact, i do not want it there at all.

Teeworlds compatibility has been holding back this project for long, it's sad we need to do hacks here and there. A 0.7 compatible client should be out-of-tree and a fork done by someone else.

2023-12-01 16:11 UTC, heinrich5991 commented
> > The if branch you wrote shouldn't be added.
> 
> was referring to this right?

The 0.7 code should move to the 0.7 translation layer and not be done where it currently is.

2023-12-01 16:12 UTC, heinrich5991 commented
0.7 comments go to #7518.

2023-12-01 16:29 UTC, merged