Added possibility to edit chat size and width
ddnet/ddnet pull request #7540
Opened 2023-11-24 22:54 UTC by archimede67

Closes #7531. To make this work, I had to refactor the code that does chat preview. I also made sure to always have some minimal ratio between chat font size and chat width so that we don't have a 5 character wide chat possible. This should also work when `cl_chat_old` is set to `1`.

https://github.com/ddnet/ddnet/assets/13364635/310d75ba-c38d-4773-96eb-c02debb00616

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-11-25 07:51 UTC, def- commented
Does it still interact well with the scoreboard so there is no overlap?

2023-11-25 12:04 UTC, Robyt3 requested changes

2023-11-25 12:18 UTC, archimede67 commented
> Does it still interact well with the scoreboard so there is no overlap?

@def- Yes! I changed it a bit in the commit I just made so that the line width is relative to the font size, allowing for a larger line width for bigger font size, but still having it not overlapping with the scoreboard.


https://github.com/ddnet/ddnet/assets/13364635/1729a418-4be8-4577-bce0-81d6c944e10b

2023-11-25 22:19 UTC, def- approved these changes

2023-11-26 10:00 UTC, Robyt3 approved these changes

2023-11-26 11:59 UTC, merged