Support other tickrates than 50hz
ddnet/ddnet pull request #7555
Opened 2023-11-27 16:46 UTC by JSaurusRex

I want to make it clear that my intent is not for offical DDRace servers to change with this pr. Without recompiling with a different tickrate nothing in the gameplay will change. DDNet is the client most of the player base uses now, a lot of modern servers are now based off DDRace as well. For Gamemodes that I play like ictf, gctf and fng this change could help gameplay. Higher tickrates decreases ping since at 50hz networking only gets done every 20ms, at 100hz thats 10ms, meaning often 10ms lower delay. I want to add support to DDNet for this so that non DDRace servers can use this in the future. I tried to keep the code relatively simple, most of the changes are more so undoing hardcoded 50hz logic. The actual logic being added is very small and limited, most things already scale with tickrate.

This isn't a final version, more a proof of concept that works, I've made a version previously that had more fixes and such but was limited to 1 tickrate. I opened this pr hoping to discuss.

Pros of higher tickrates (lower are technically also supported):
- lower ping
- more precision with timing
- inputs missing a tick will have less of an effect since the next tick is sooner.

Cons:
- more processing and network bandwidth
- no support for older or non DDNet clients (they just get kicked, mixed servers are possible but way more messy and have more cons)

And once again, for the offical DDRace servers nothing changes, everything either scales as normal or is disabled at 50hz.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [~] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-11-27 16:58 UTC, Jupeyy commented on src/game/gamecore.cpp
> +					m_Vel *= pow(0.85f, 1/(SERVER_TICK_SPEED/50.0));
we should really make sure pow is accurate enough, else this can:tm: change physics

2023-11-27 17:24 UTC, Robyt3 commented on datasrc/network.py
> +	]),
Don't add new `NetMessage`s, it breaks all other netmessages at this index including modded messages. Add new `NetMessageEx` at the end.

2023-11-27 17:28 UTC, JSaurusRex commented on src/game/gamecore.cpp
> +					m_Vel *= pow(0.85f, 1/(SERVER_TICK_SPEED/50.0));
I agree, I definitely should double check it, but tee bounces haven't been done accurately, its one of the things I still have to fix.

2023-11-27 20:24 UTC, JSaurusRex commented on datasrc/network.py
> +	]),
aight thanks for telling me, I changed it.

2023-11-27 21:03 UTC, JSaurusRex commented
#7555 did remove a m_GameTickSpeed which I needed, so I brought it back.

2023-11-28 14:51 UTC, JSaurusRex commented
So there is 1 problem with higher tickrates which changes the game physics somewhat. The positions of players get rounded every tick, this can look funky and feel jittery / choppy. My old solution for this was to increase the position precision x4, so multiply 4 for netmsg and then divide by 4 to read it out. But this obviously also changes how the player moves somewhat and required some extra collision checks because without rounding you can get stuck in walls. You basically got rounded on the X whenever you hit a vertical wall and on the Y for a horizontal wall.
Is this approach acceptable?

2023-11-28 15:55 UTC, JSaurusRex commented on src/game/gamecore.cpp
> +					m_Vel *= pow(0.85f, 1/(SERVER_TICK_SPEED/50.0));
from my quick test, seems pow is accurate enough. To the point that == returns true

2023-12-02 15:58 UTC, JSaurusRex commented
since I haven't had a response yet and the mention was made in an edit I'm just gonna remention @heinrich5991 
Can you give some feedback on this proposal so far? Like if making the positions 4x more precise is acceptable. Or using a netmessageEx to send server tickrate to client.

2023-12-02 17:10 UTC, Jupeyy commented
I can tell you that breaking physics is sadly not really possible. this invalidates all current ranks.

DDNet can always think about hosting a second season with breaking physics, but for now i guess you could try to leave the physics as is

2023-12-02 17:27 UTC, Learath2 commented
This level of breaking physics will likely never be popular. As you increase tickrate, many of the timings people perfected over a decade become closer and closer to the realm of impossibility. As you increase quantization, a similar issue occurs. It would just take the consistency out of the game since no human can have timing that good over suboptimal connections.

This change might be a better fit for a pvp mod or vanilla where precise timing and movement are less important. This makes me think that maybe this repository isn't really the best place to have these changes in.

2023-12-02 17:36 UTC, Jupeyy commented
> This change might be a better fit for a pvp mod or vanilla where precise timing and movement are less important. This makes me think that maybe this repository isn't really the best place to have these changes in.

Even if i agree with this. this is true for a lot of stuff.
Since we don't really want to break our concepts of backward compatibility, and its resulting moddability, this is basically the only way to have high support across the community for such features

2023-12-02 18:05 UTC, JSaurusRex commented
> I can tell you that breaking physics is sadly not really possible. this invalidates all current ranks.
> 
> DDNet can always think about hosting a second season with breaking physics, but for now i guess you could try to leave the physics as is.
> 
> If you only want this precision boost for your new physics i guess it's ok. should probably be tested tho

Yeah its not possible to not break physics with other tickrates to some extend. This is why I didn't recommend this change for official DDRace servers. The physics are close enough for gamemodes that don't rely on that level of precision for tricks but rather reactionspeed.

The 4x precision for positions is only meant for higher tickrates, lower tickrates obviously also don't have this problem. However either way the physics change since 4x positional precision doesn't equal however many less quantizations. Preferably it would obviously be as close as possible to 50hz gameplay in some sense (obviously you can do inputs at different times, but ignoring that the physics should be close). I could also do normal positional precision at 50hz and then 4x at the rest so it more closely matches it. But that probably will look a bit weird since currently its interpolated vs simulated.

Also another showcase of why its good for something like fng or ictf is lets say an enemy player is running under you and you shoot straight down. Even if you got the timing correct it could be that the character was never at the exact spot you shot at (though they must go pretty fast for this to happen i think).

> basically the only way to have high support across the community for such features
Yep with ddnet client being the most popular client you basically need to add features you want into this one. That and if you wanted to make a new mode nowadays you also are probably best of forking ddnet/ddrace.

2023-12-02 18:24 UTC, Jupeyy commented
> The 4x precision for positions is only meant for higher tickrates
I see, but then there should be no problem i guess. that the physics won't be the same for higher tick rates is obviously always true, since it's mathematically impossible

2023-12-02 21:21 UTC, JSaurusRex commented
I don't know how to disable 0.7 registration since this doesn't support 0.7 obviously. But all other functionality that I tested seems to work. Atm I have some collision checks and round the X or Y position based if you're next to a wall, floor or ceiling. Otherwise you might clip into it which used to be a problem with the increased positional precision.
Demos however don't scale time correctly either... that's all issues I noticed.

2023-12-04 01:34 UTC, heinrich5991 commented
Sorry for the silence, wasn't really around.

I think this feature shouldn't be added since I don't see enough of value for the complexity it'll bring.

I certainly don't want DDNet servers to use this, having slightly different timings on DDNet maps sounds horrible.

For modding, I don't see enough of a use case. If an input misses a tick, it'll get applied in the next one. The worst that could happen is that your opponent will also send the kill input in that following tick, causing both of you to die. That seems okayish to me.

If other people still want to get that merged, it'll need to have support for demos and ghosts. This means we somehow have to embed the notion of tickrate into these file formats, which sounds not entirely trivial.

2023-12-04 19:28 UTC, Jupeyy commented
> For modding, I don't see enough of a use case. If an input misses a tick, it'll get applied in the next one. The worst that could happen is that your opponent will also send the kill input in that following tick, causing both of you to die. That seems okayish to me.

Well for PVP mods it would ofc make a huge difference. I don't want to start this discussion, but one can just accept that pros notice the difference right away (we tried 200 tick servers in the fng community already).

But yeah not trivial to add support to all components properly, agree with that

2023-12-07 15:18 UTC, JSaurusRex commented
nvm I changed how it works, the tuning values don't get changed in tuning.h but in gamecore.cpp
This means that you could technically have per player tickrate making mixed servers easier (not planned for this pr or maybe at all for ddrace). Demos now work properly because the tuning is the same. Custom tunings set in the map, tuning sections or server config now work properly as well without having to be converted (Not tested, I don't have good testing methods for this).

2023-12-07 16:20 UTC, JSaurusRex commented
With the recent commit you no longer have to recompile the server to get higher tickrates, using the sv_tickrate variable. If this is undesirable I can remove it.
Anyway everything to my knowledge works, this just gotta get tested a bunch then I'm gonna set it to a non-draft

2023-12-07 16:32 UTC, Jupeyy commented on src/game/version.h
> +#define GAME_RELEASE_VERSION "17.5"
i don't think we just change versions in PRs

2023-12-07 16:36 UTC, Jupeyy commented on src/game/gamecore.cpp
> +float CCharacterCore::ScaleValue(int Scaling, float value)
if you only use scaling as enum, make the type the enum not  `int`

2023-12-07 16:44 UTC, JSaurusRex commented
As per the recommendation of Jupeyy, I'll put the graphs I made a while back here
I used these to get the correct formula to scale acceleration.
![image](https://github.com/ddnet/ddnet/assets/50572621/95ce7f0e-fc95-4fc6-b9e5-cb46e5b61de3)

Python script used:

`# importing the required module 
import matplotlib.pyplot as plt 



def simulate(time, offset, arr1, arr2, arr3):

    accel : float = 5
    accel /= pow(time, 2)

    vel = 0
    pos = 0

    for i in range(int(20*time)):
        vel += accel
        pos += vel
        arr1.append(pos)
        arr3.append(vel)
        arr2.append(i/time - offset)




vel1 = []
pos1 = []
time1 = []
simulate(1.0, 0, pos1, time1, vel1)
vel2 = []
pos2 = []
time2 = []
simulate(2.0, 1, pos2, time2, vel2)


for i in range(len(vel2)):
    vel2[i] *= 2
  
# plotting the points  
plt.plot(time1, pos1, label="pos 1x")
plt.plot(time1, vel1, label="vel 1x")
plt.plot(time2, pos2, label="pos 2x")
plt.plot(time2, vel2, label="vel 2x")
  
# naming the x axis 
plt.xlabel('time') 
# naming the y axis 
plt.ylabel('pos') 

# giving a title to my graph 
plt.title('physics sim') 

plt.legend()
# function to show the plot 
plt.show() `

2023-12-11 14:29 UTC, JSaurusRex commented on src/game/version.h
> +#define GAME_RELEASE_VERSION "17.5"
kinda required to test, I can turn it back but that means you can't test it...

2023-12-16 15:49 UTC, Jupeyy requested changes
I haven't tested yet, just a small (and maybe incomplete) code review.

There are still many code areas where we could maybe make the diff smaller.
Right now we pass the tick rate quite often. generally I understand why you did that, but ofc this leads to many code paths where you have to be careful to not forget to change the tick rate (e.g. when assigning to the world tick rate).
_Not a strong opinion, but: maybe we could use a shared ptr to share the tick rate around components or smth similar_

The ghost, demo component is still a subject to talk about with everyone. In discord we also had the discussion if we could maybe disable ghost & demo for a first test.

2023-12-16 15:49 UTC, Jupeyy commented on datasrc/network.py
> +		NetIntRange("m_TickRate", 1, 1000),
range should not be lower than 50, this could just potentially lead to more bugs.

2023-12-16 15:49 UTC, Jupeyy commented on src/engine/client.h
> +	int m_GameTickSpeed;
please initialize this with `SERVER_TICK_SPEED`:
`int m_GameTickSpeed = SERVER_TICK_SPEED;`

else it's zero when the client starts

2023-12-16 15:49 UTC, Jupeyy commented on src/game/gamecore.cpp
> +float CCharacterCore::ScaleValue(TUNING_SCALE Scaling, float value)
can we completely remove this function maybe?

it seems to make the code less readable, we can add comments to where the physic was changed like this

2023-12-16 15:49 UTC, Jupeyy commented on src/game/gamecore.cpp
> +	vec2 tmpPos = NewPos;
i've no idea what this is but please move it to a new function, else it destroys the readability of the move function. and since it's only used for higher tick rates, the name of the function could make it clear.
generally describing the code a bit would be nice :D

2023-12-16 15:49 UTC, Jupeyy commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(SvTickRate, sv_tickrate, 50, 10, 400, CFGFLAG_SERVER, "Tickrate of server, default is 50. Higher means more bandwidth and processing.")
50 as minimum

2023-12-16 15:54 UTC, Jupeyy commented
![image](https://github.com/ddnet/ddnet/assets/6654924/b4bd8b3c-7ec0-46b0-a67c-09739aad1f19)

there seem to be animation bugs still. I'm not moving in the above picture

2023-12-16 15:58 UTC, Jupeyy commented
when i'm close to a wall, the physics are really weird:

https://github.com/ddnet/ddnet/assets/6654924/c8db16ec-84e5-4cdd-a199-439cbdb92f4f

2023-12-16 16:05 UTC, heinrich5991 commented
Can someone help me with the advantages again?
> lower ping

I assume you mean lower latency. Of what? Clicking the fire button and the other tee being dead in iCTF? Can you describe a situation where that matter?

Both tees send a laser fire, both having same ping to the server. One sends it 5 ms later. With 20 ms per tick, we now get a 75% chance that they kill each other. Is that what you want to lower?

> more precision with timing

What does that mean?

> inputs missing a tick will have less of an effect since the next tick is sooner.

Why is that interesting? Same scenario as the first question?

2023-12-16 16:08 UTC, Jupeyy commented
> I assume you mean lower latency. Of what? Clicking the fire button and the other tee being dead in iCTF? Can you describe a situation where that matter?
>
> Both tees send a laser fire, both having same ping to the server. One sends it 5 ms later. With 20 ms per tick, we now get a 75% chance that they kill each other. Is that what you want to lower?

if one shoots 10ms faster then the other, he has no advantage. so more ticks = faster reaction pays out

> > more precision with timing
>
> What does that mean?

Since more ticks are calculated, more sub positions are considered, so generally shooting is more accurate in the moment you saw it on your screen

2023-12-16 16:16 UTC, heinrich5991 commented
For these advantages, might it simply suffice to simulate more ticks on the server, not concerning the client with it? It means that status changes etc. and precision can be accurately modelled on the server, with no change of the client.

The only difference is in what the client receives, it'd still only receive a maximum of one snapshot every 20 ms. Not much happens in between though, since you can't suddenly accelerate in Teeworlds.

2023-12-16 16:20 UTC, Jupeyy commented
Sadly the physics are 100% different. maybe not a lot, but teeworlds physics are mathematically impossible to "just" increase.

So this would at least partially lead to inconsistent states

2023-12-16 16:29 UTC, heinrich5991 commented
> So this would at least partially lead to inconsistent states

Inconsistent states would be corrected every 20ms since the snap would override the positions predicted in the client.

2023-12-16 16:34 UTC, Jupeyy commented
> > So this would at least partially lead to inconsistent states
> 
> Inconsistent states would be corrected every 20ms since the snap would override the positions predicted in the client.

that is correct, but it would probably look horrible esp. on high refresh rate screens

2023-12-16 17:23 UTC, JSaurusRex commented
> The ghost, demo component is still a subject to talk about with everyone. In discord we also had the discussion if we could maybe disable ghost & demo for a first test.

How so? Ghosts and demos work now right?


> when i'm close to a wall, the physics are really weird:

I thought I fixed this issue, seems I forgotten a part of it. Will try and fix soon, pretty sure this is because of the rounding of the ints.

2023-12-16 17:25 UTC, heinrich5991 commented on src/engine/shared/demo.cpp
> +static const unsigned char gs_CurVersion = 7;
Version can't be increased anymore, need shenanigans like the sha256 version upgrade.

2023-12-16 17:26 UTC, JSaurusRex commented on src/game/gamecore.cpp
> +float CCharacterCore::ScaleValue(TUNING_SCALE Scaling, float value)
I think a better name would be better than removing it. The reason I did it like this is because very similar code had to be done in a whole lot of different places making it more difficult to change but also less readable vs 1 function which name describes what it does and the enum describes how it scales

2023-12-16 17:31 UTC, JSaurusRex commented on src/engine/shared/demo.cpp
> +static const unsigned char gs_CurVersion = 7;
Will do, but I am curious as to why?

2023-12-17 21:54 UTC, heinrich5991 commented on src/engine/shared/demo.cpp
> +	io_write(DemoFile, &tickrate, sizeof(int));
Would be nice to only write the tickrate if it's nonstandard, less compatibility problems with old clients or if we decide to revert this.

2023-12-17 21:54 UTC, heinrich5991 commented on src/engine/shared/demo.cpp
> +static const unsigned char gs_CurVersion = 7;
> Edit: guessing its because of 0.7 compatibility

Correct.

2023-12-19 01:51 UTC, JSaurusRex commented on src/engine/shared/demo.cpp
> +	io_write(DemoFile, &tickrate, sizeof(int));
ooh thats a good idea regardless if we revert it. a lot of players have multiple clients

2024-01-18 14:16 UTC, JSaurusRex commented
@heinrich5991 this one I think you wanna check out, I ended up for demos adding a new number for versions to avoid future conflicts upon which more variables can be added rather easily whilst still being kinda backwards compatible. The demo file would be read correctly afterwords because it contains a size variable so it knows where to skip to.

Ghosts at this moment still just have the version increased, maybe i should do something similar. Or does 0.7 not have ghosts?

2024-02-12 16:45 UTC, JSaurusRex commented
@heinrich5991 hey can you take a look at these demo changes i proposed?

2024-03-13 21:12 UTC, Robyt3 reviewed
The changes to demo and ghost handling look very hacky. I think the first change to either of those formats should be to introduce a UUID-based system like for maps and snapshots, instead of adding more hacks to the demo/ghost formats. This should be possible by adding one or more new demo/ghost chunk types for UUID items. That should be done in a separate PR independent of this feature.

2024-03-13 22:58 UTC, JSaurusRex commented
> The changes to demo and ghost handling look very hacky. I think the first change to either of those formats should be to introduce a UUID-based system like for maps and snapshots, instead of adding more hacks to the demo/ghost formats. This should be possible by adding one or more new demo/ghost chunk types for UUID items. That should be done in a separate PR independent of this feature.

i think i understand, and i had something similar in mind with my hacky solution. Only thing i would be careful for is backwards compatability, older clients can still somewhat detect demos and/or read them completely. Especially when non of the new features are used just like heinrich suggested.

If this feature will be on its own pr does that mean this pr can get merged like this (with demos and ghosts disabled) or will it have to wait for the other pr. Because im not sure i could implement something like that (literally had to search up what an uuid is).

2024-03-14 19:49 UTC, Robyt3 commented
TBH, I'm not sure if any of the maintainers are motivated to get this PR merged. I'd prefer not to merge this unless another maintainer wants it. Seems to risky for me for little gain for DDNet.

2024-09-19 10:42 UTC, JSaurusRex commented on datasrc/network.py
> +		NetIntRange("m_TickRate", 1, 1000),
I can see 25 being useful for some slower game modes that might want less resources being used

2024-09-21 12:40 UTC, JSaurusRex commented
I would like to make the argument as to why this PR should be accepted. Though not in this condition, its gone through so many changes it definitely picked up some changes that since have been partially reverted. However first I'd like to know the contributors opinions

My proposal is that non 50hz tickrates are considered experimental, subject to change. Potentially having some not yet found bugs. It still has its use cases even without Timed / Race gamemodes (Race, DDrace, Gores). DDNet is the standard client, by extension so is its server. With the reintroduction of gamemodes besides DDRace in DDNet it really makes sense to add functionally of this PR to DDNet itself even if DDRace doesn't benefit. (Some servers could use them if they're alright with the potential of physics changing in the future when bugs are found).

As is I do not have the ability to guarantee that the physics are perfect nor that every mechanic properly scales. Without proper tests this is simply too much and also outside my area of expertise (not a ddrace player). I cannot say that non 50hz is perfect, however 50hz is another thing. My code mostly comes back to 3 or so functions. Those functions all have if statements for 50hz to ensure that nothing gets changed. The PhysicsTickSpeedScaling function which returns a scaled version of what ever force you put into it returns the exact same value as put in when on 50hz. Collision is the same, only switching to another function when its above 50hz.

As of now the state of this PR is:
Demos work via Messages (no need for demos to have a format change, 50hz demos work without this pr as normal)
Ghost as far as I know don't use Messages so they still use the format change I implemented
The DDNet features I tested work but I didn't test them extensively (nor probably all)

I could write up a guide to properly make new stuff scale. However to not increase DDNet's complexity too much is why I suggested this to be experimental to begin with, keeping 50hz working the same is pretty easy. Ensuring tickspeeds higher are working is a luxery rather than necessity.

2025-08-06 17:50 UTC, edg-l commented
closing as its stale reopen another pr if you want to continue working on this

2025-08-06 17:50 UTC, closed without merging

2025-10-21 07:44 UTC, heinrich5991 commented
I don't want the added complexity of supporting tick rates other than 50 Hz in DDNet. You can experiment in other clients first.