Add a fading effect for buttons
ddnet/ddnet pull request #7557
Opened 2023-11-28 18:51 UTC by furo321

Adds a small fading effect when switching from the hover colour for buttons. Ported from 0.7.

https://github.com/ddnet/ddnet/assets/141338449/55d8d3a1-ca24-4be1-b4f3-0e4014195549

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-11-28 19:10 UTC, Robyt3 requested changes

2023-11-28 19:10 UTC, Robyt3 commented on src/game/client/components/menus.cpp
> +	Color = mix(Color, vec4(Color.r, Color.g, Color.b, Color.a * AlphaMultiplier), FadeVal);
This only seems to change the Alpha component, so you can apply the `mix` only to the alpha directly.

2023-11-28 19:10 UTC, Robyt3 commented on src/game/client/components/menus.cpp
> +	Color = mix(Color, vec4(Color.r, Color.g, Color.b, Color.a * AlphaMultiplier), FadeVal);
Only mix the alpha component

2023-11-28 19:10 UTC, Robyt3 commented on src/game/client/components/menus.cpp
>  int CMenus::DoButton_Menu(CButtonContainer *pButtonContainer, const char *pText, int Checked, const CUIRect *pRect, const char *pImageName, int Corners, float r, float FontFactor, vec4 ColorHot, vec4
Note for a future PR: We shouldn't use `vec4` for colors anymore, this should use `ColorRGBA`. That way we could eventually use a better color mixing procedure than simply averaging the components.

2023-11-28 22:05 UTC, def- commented
I intentionally didn't port this since I didn't like it much in 0.7.

2023-11-28 22:24 UTC, furo321 commented on src/game/client/components/menus.cpp
>  int CMenus::DoButton_Menu(CButtonContainer *pButtonContainer, const char *pText, int Checked, const CUIRect *pRect, const char *pImageName, int Corners, float r, float FontFactor, vec4 ColorHot, vec4
Fixed most of them, but had to keep a few due to `mix()` not being able to take it as an argument.

2023-11-29 01:51 UTC, VoxelDoesCode commented
This feels too distracting for DDNet, honestly.

2023-11-29 09:27 UTC, edg-l commented
I also don't like this.

While this is a small PR, there is a reason why we ask to make a issue first to discuss, so there is no wasted work.

2023-11-30 20:44 UTC, BurnyLlama commented
Nice UI change. Maybe make the animation a tad bit faster, at least when the mouse leaves. +1

2023-11-30 20:45 UTC, BurnyLlama commented
Also make a toggle for this in the settings, for accesability reasons.

2023-11-30 22:56 UTC, def- commented
Please no more toggles! How does the toggle even improve accessibility?

2023-11-30 23:12 UTC, VoxelDoesCode commented
its an excuse for people to turn off things they don't like

2023-12-04 01:59 UTC, heinrich5991 commented
Do programs usually do this? Games?

I think I'd personally prefer not to add this.

2023-12-04 21:48 UTC, closed without merging