Added search in console (ctrl+f)
ddnet/ddnet pull request #7577
Opened 2023-12-02 18:32 UTC by archimede67

Closes #5815. Highlights all occurrences in red.

https://github.com/ddnet/ddnet/assets/13364635/cf681e87-6afb-462c-9b2a-e4eec2afac4b

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-12-02 19:24 UTC, Chairn commented
I don't think you should hide not matching lines. highlighting and navigating the occurrences is better imo

2023-12-02 22:09 UTC, furo321 commented
I agree with Chairn, it should be possible to navigate the occurrences instead of filtering. I tried implementing something similar a few months ago.


https://github.com/ddnet/ddnet/assets/141338449/302a8725-0646-46e7-92cd-b403c37b2968

2023-12-03 10:27 UTC, Robyt3 commented
It should also search all pages and scroll to reveal matches instead of only searching the current page though. Would probably be better to finish #7340 first for that.

2023-12-10 16:34 UTC, archimede67 commented
I reworked the console search function, here's a small list of the functionalities:
- search through all lines and see all matches in one color
- navigate through matches and see selected match in another color
- works in local and remote console
- works with multiline entries
- automatically scroll to center the selected match


https://github.com/ddnet/ddnet/assets/13364635/72f8c45c-e290-4cca-8c19-5b9b8a581de8

2023-12-10 19:33 UTC, Robyt3 requested changes
Works good, I'll take a closer look at the code in the next few days.

Arrows keys up and down could also be used to navigate between matches. Enter key could also be used in the same way as tab key, which is how the search works e.g. in Sublime Text.

2023-12-13 19:02 UTC, Robyt3 requested changes

2023-12-13 20:14 UTC, archimede67 commented on src/engine/textrender.h
> +	virtual void TextColorSplit(const std::vector<SColorSplit> &vSplits) = 0;
I don't think I can store a vector in `CTextCursor` as it is being initialized with `mem_zero`, should I do it in another way without using `std::vector` or should we remove the initialization with `mem_zero` ?

2023-12-13 20:48 UTC, Robyt3 commented on src/engine/textrender.h
> +	virtual void TextColorSplit(const std::vector<SColorSplit> &vSplits) = 0;
Remove the `mem_zero`

2023-12-13 23:05 UTC, Robyt3 requested changes
Looks good otherwise. You can squash the commits when done and update the video in the PR description so we can use when showcasing the new version.

2023-12-13 23:05 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +			}
Combine both `if` conditions with `&&` so you can remove a duplicate `else` branch. You can also move up the `if` to make it an `else if` directly instead of nesting the `if` in the `else` branch with a block.

2023-12-13 23:18 UTC, archimede67 commented
@Robyt3 Are the colors OK? Maybe orange and red aren't contrasted enough, maybe I should change them?

2023-12-13 23:19 UTC, archimede67 commented on src/game/client/components/console.cpp
> +		if(SearchChanged)
I think that's a bug since it is not the case when you browse the files of the latest commit

2023-12-14 19:44 UTC, Robyt3 requested changes
> Maybe orange and red aren't contrasted enough, should I change them?

Using yellow `ColorRGBA(1.0f, 1.0f, 0.0f, 1.0f)` for `ms_SearchSelectedColor` contrasts a bit better I'd say.

The current text selection in the console (not the filter) should be cleared when scrolling to a search match.

I also noticed the console doesn't scroll to the first search match while you type the filter, if the first match is not currently visible. When you press enter it then goes to the second match instead. Maybe that's too complicated to handle though.

2023-12-14 19:49 UTC, archimede67 commented
> Using yellow ColorRGBA(1.0f, 1.0f, 0.0f, 1.0f) for ms_SearchSelectedColor contrasts a bit better I'd say.

What about system messages? If we use yellow for the selected match, then we wont really "see" it when the match is in a system message.

> The current text selection in the console (not the filter) should be cleared when scrolling to a search match.

Right, I'll do that.

> I also noticed the console doesn't scroll to the first search match while you type the filter, if the first match is not currently visible. When you press enter it then goes to the second match instead. Maybe that's too complicated to handle though.

Really? I have to test this, it should work though. Will try to see if I can fix it easily.

2023-12-14 19:58 UTC, archimede67 commented on src/game/client/components/console.cpp
> +		if(SearchChanged)
Ah I think that's my bad, I see it now

2023-12-14 20:33 UTC, archimede67 commented
Everything should work now, but I'm still a bit unsure about the color. I've changed `ms_SearchSelectedColor` to yellow which provides a better contrast and is actually visible in system messages.
I will update the video in the PR description to better reflect this updated version.
![image](https://github.com/ddnet/ddnet/assets/13364635/51ca3773-7e50-4b91-a634-3d57e3831758)

2023-12-14 21:11 UTC, Robyt3 approved these changes
Thanks!

2023-12-14 21:37 UTC, merged