Add ability to scroll in console. Remove pages.
ddnet/ddnet pull request #7593
Opened 2023-12-05 19:24 UTC by archimede67

Based on @furo321's work (#7340).
I attempted to fix the bugs in this PR, the big thing is that now we can scroll line by line no matter if the console entry is multiline or not. For that, I had to basically add the ability to use a `LineSpacing` parameter to render the text in order to keep things consistent for 1 line entries and multiline entries.
I've tested it on multiple different resolutions and it seems to work quite well.

https://github.com/ddnet/ddnet/assets/13364635/4a77901f-cf39-4722-9b76-1181fd7abfe8

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-12-05 20:22 UTC, heinrich5991 commented
Tested it, works nicely. Thanks @furo321 and thanks @archimede67 for finishing up @furo321's work.

2023-12-06 18:45 UTC, Robyt3 requested changes

2023-12-06 18:45 UTC, Robyt3 commented on src/game/client/components/console.h
> +	static constexpr float LINE_OFFSET = 1.0f;
It should also be called line spacing consistently and not line offset here.

2023-12-06 18:45 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +int CGameConsole::CInstance::GetLinesToScroll(int Direction)
This function can be declared `const`

2023-12-06 18:45 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +			}
Maybe you could avoid this mostly duplicate code if you use `GetLinesToScroll` and make `LinesToScroll` a parameter.

2023-12-06 18:45 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +				++m_BacklogCurLine;
Maybe you could avoid this mostly duplicate code if you use `GetLinesToScroll` and make `LinesToScroll` a parameter.

2023-12-06 18:45 UTC, Robyt3 commented on src/game/client/components/console.cpp
Text selection over multiple lines seems slightly broken now. The selection temporarily expands until the end of a line when going over the spacing. See video below.

https://github.com/ddnet/ddnet/assets/23437060/ce5db9fa-92f9-4e42-9f60-7dcb81b2ff65

2023-12-06 18:45 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +	auto Screen = *m_pGameConsole->UI()->Screen();
Inline unnecessary temporary variable

2023-12-06 18:45 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +void CGameConsole::CInstance::ComputeEntryLineCount(CBacklogEntry *pEntry)
Maybe rename to `UpdateEntryTextAttributes` or something like that

2023-12-06 18:45 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +		ComputeEntryLineCount(pEntry);
Don't call other functions that can print log messages here. `ComputeEntryLineCount` calls `TextEx` which can print log messages. As the comment above says, this will cause dead locks. Rendering the text here to calculate the attributes is also prone to break because the screen might not be mapped the same size as when the text is actually rendered.

2023-12-06 18:59 UTC, archimede67 commented on src/game/client/components/console.cpp
> +		float LineHeight = TextRender()->TextBoundingBox(FONT_SIZE, " ", -1, -1, LINE_OFFSET).m_H + LINE_OFFSET;
This is necessary for different resolutions, I guess the text size isn't always the provided font size. If I only use FontSize + LineSpacing, then the calculations are not correct and the text is rendered wrong:

https://github.com/ddnet/ddnet/assets/13364635/7f2dba38-ff19-46e2-83f9-f8bcb7c3adf3

As you can see, with multiline entries the text can be rendered on top of the input which is wrong.

2023-12-06 19:00 UTC, archimede67 commented on src/engine/textrender.h
> +	int m_StartLine;
Yeah, `m_StartLine` is to be able to start rendering after a specific line indeed. I tried using quad clipping but I forgot which issues I had with. I can try that again

2023-12-06 19:04 UTC, archimede67 commented on src/game/client/components/console.cpp
> +		ComputeEntryLineCount(pEntry);
Where should I put this computation then? I need it to be able to compute scroll offsets even when those entries are not rendered once.

2023-12-06 20:14 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +		ComputeEntryLineCount(pEntry);
If you really need the offsets and line counts to be up-to-date all the time then it seems you need the calculation here, but you shouldn't do it while owning the lock.

Put the contents of the `PumpBacklogPending` function into another scope (curly braces), so the `CLockScope` only applies to the original code and not to code you add. It should somewhat look like this:

```cpp
{
    // We must ensure that no log messages are printed while owning
	// m_BacklogPendingLock or this will result in a dead lock.
	const CLockScope LockScopePending(m_BacklogPendingLock);
    ...
}

// TODO: correctly map screen
for(CInstance::CBacklogEntry *pPendingEntry = m_BacklogPending.First(); pPendingEntry; pPendingEntry = m_BacklogPending.Next(pPendingEntry))
{
    // TODO: update entry's offset and line count if uninitialized
}
```

In `CGameConsole::CInstance::PrintLine` you should also properly initialize `pEntry->m_LineCount = -1` so you can later check if it hasn't been computed yet and to prevent potential use of uninitialized memory.

You probably should remove the variable `m_RecomputeYOffsets` as well and instead update the offsets and line counts immediately or they would be wrong temporarily when resizing the window while the console is not being rendered.

2023-12-07 11:55 UTC, archimede67 commented on src/game/client/components/console.cpp
> +int CGameConsole::CInstance::GetLinesToScroll(int Direction)
You mean `int CGameConsole::CInstance::GetLinesToScroll(int Direction) const` ? If so, it seems to give me errors with `m_Backlog`

2023-12-07 18:16 UTC, archimede67 commented on src/engine/textrender.h
> +	int m_StartLine;
Okay I got it working, I think it should work for any resolution

2023-12-07 18:17 UTC, archimede67 commented on src/game/client/components/console.cpp
> +		ComputeEntryLineCount(pEntry);
I followed your suggestions, I hope everything is right now

2023-12-07 18:55 UTC, furo321 commented on src/game/client/components/console.cpp
> +		TextRender()->Text(10.0f, FONT_SIZE / 2.f, FONT_SIZE, aBuf);
Should probably be localized, totally forgot about it in my original PR.

2023-12-09 09:59 UTC, Robyt3 requested changes
Looks and works very well now. Some more minor comments below.

Please squash all commits when done.

2023-12-09 09:59 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +		m_BacklogPending.Init();
It's not necessary to do this _after_ calling `UpdateEntryTextAttributes`. At this point the entries have already been copied into the real backlog, so you don't need to keep the pending backlog entries around to update the text attributes. You can move the call to `Init` up and only use the existing `LockScopePending` so you don't need to lock twice.

2023-12-09 09:59 UTC, Robyt3 commented on src/game/client/components/console.cpp
>  void CGameConsole::CInstance::ClearBacklogYOffsets()
`UpdateBacklogTextAttributes`

2023-12-09 09:59 UTC, Robyt3 commented on src/game/client/components/console.cpp
>  	// Pending backlog entries are not handled because they don't have a Y offset yet.
`a Y offset` -> `text attributes`

2023-12-09 09:59 UTC, Robyt3 commented on src/game/client/components/console.cpp
Works good now. We can also leave this minor issue to a future PR. It doesn't seem very noticeable during normal usage.

- Mouse between lines, results in a selection that should not be possible: ![screenshot_2023-12-09_10-44-26](https://github.com/ddnet/ddnet/assets/23437060/6df9a375-3c56-4718-a861-0d45098a00ff)

- Mouse moved some pixels down, selection is correct: ![screenshot_2023-12-09_10-44-33](https://github.com/ddnet/ddnet/assets/23437060/01cd49e1-98dd-4174-a5da-6eae97bed8fb)

2023-12-09 11:21 UTC, archimede67 commented on src/game/client/components/console.cpp
Yeah I noticed that too, and I agree to leave this to another PR

2023-12-09 18:26 UTC, Robyt3 approved these changes
Thanks!

2023-12-09 18:43 UTC, merged