Fix chat preview update
ddnet/ddnet pull request #7596
Opened 2023-12-06 11:53 UTC by archimede67

When I remade the chat preview for #7540, I forgot that you could change your name and that the chat preview would update accordingly. This PR fixes that issue, allowing the lines to be updated instead of initializing them only once.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-12-06 12:45 UTC, Sedonya commented
mega ultra super duper thx

2023-12-07 16:58 UTC, Robyt3 requested changes

2023-12-07 16:58 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +				pLine = &s_vLines[s_vLines.size() - 1];
Use `&s_vLines.back()` to get a pointer to the last element

2023-12-07 19:44 UTC, Robyt3 approved these changes

2023-12-07 20:04 UTC, merged