Add OnSnapPlayerScore() controller hook
ddnet/ddnet pull request #7598
Opened 2023-12-07 10:28 UTC by ChillerDragon

Allow game controllers to implement their own scoring snap. This comes in handy for forks that are not using race times as scores. And want to send their own values.

``sv_gametype ddnet`` still loads scores just fine.

``sv_gametype mod`` shows score 0 at all times.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-12-08 07:31 UTC, Kaffeine commented on src/game/server/gamemodes/DDRace.cpp
> +int CGameControllerDDRace::OnSnapPlayerScore(CPlayer *pPlayer, int SnappingClient)
Please change the name (maybe something like `GetPlayerScore()` or (looking at '[no Get prefix](https://github.com/ddnet/ddnet/pull/7136#discussion_r1324805630)' discussion) just `int PlayerScore(int ClientID) const` because `Snap`/`OnSnap` methods are typically `void` and use their own new SnapItems.
IOW it is weird to use a `On<something>` handler to get a value.

2023-12-08 08:27 UTC, Kaffeine commented
In general, we can use different approaches:
1. Delegate the score value to GameController
2. Add a setter/getter to CPlayer and set the `int m_Score` outside of the class (e.g. move all score-related logic to GameController) or (if we want to keep CPlayer::ProcessScoreResult in the player class) then
3. Use a subclass (I use this approach in [infclass](https://github.com/infclass/teeworlds-infclassR/commit/ede3e2e931aecc9857852255f4e9327bcde4c288)). API-wise we need to add a `virtual int GetScore() const` (or `optional<int> GetScore()`) to the CPlayer class, and (optionally) move DDNet-specifc scoring to CDDRacePlayer or CPlayerDDRace.
In the last case we can move this stuff from the base CPlayer:
```
	void ProcessScoreResult(CScorePlayerResult &Result);
	std::shared_ptr<CScorePlayerResult> m_ScoreQueryResult;
	std::shared_ptr<CScorePlayerResult> m_ScoreFinishResult;
```

I can quickly (but not early than the Sunday evening) submit a PR for the 3rd approach if DDNet devs agree on it.
The PR 'll have 4 commits:
1. `virtual IGameController::CreatePlayer()` introduction
2. CPlayer subclassing (a few `private`->`protected` replacements)
3. Long live CPlayerDDRace (without any customization at this point)
4. `virtual optional<int> GetScore() const` for CPlayer and the move of the three members to the DDRace player subclass

2023-12-10 16:56 UTC, Kaffeine commented
Note: I'm working on the 3rd approach so we could compare the exact impact on the codebase. It turned out that it is much harder to move m_Score{Query,Finish}Result members because CScore access them directly. I'm trying to unravel the tangle but it takes time and maybe I'll have to give up (and keep the members as is).

2023-12-12 22:34 UTC, ChillerDragon commented
I do like https://github.com/ddnet/ddnet/pull/7631 a lot! But still would like this pr get merged too. Imo it is cleaner if all that score logic is not happening in the snap directly but in a method. And it is also nice to only just overwrite this common part in a custom mod without having to overwrite and reimplement the entire snap.

2023-12-12 22:48 UTC, Kaffeine commented
> I do like #7631 a lot! But still would like this pr get merged too. Imo it is cleaner if all that score logic is not happening in the snap directly but in a method. And it is also nice to only just overwrite this common part in a custom mod without having to overwrite and reimplement the entire snap.

You'd have to reimplement the entire snap if you want to snap something different than time score because (in the current codebase and still in this MR) CPlayer::Snap is hardcoded to snap the score as time (not to say about the 0.7 protocol snapping BestTime and RaceData).

2023-12-13 13:52 UTC, ChillerDragon commented
After https://github.com/ddnet/ddnet/pull/7602 setting the timescore flag should be smoother. Since inheriting/overwriting the gamecontroller snap will be pretty chill.

2024-01-08 18:49 UTC, heinrich5991 requested changes
Blocked on #7777.

2024-10-02 03:44 UTC, closed without merging