Make it possible to use CPlayer subclass in a mod
ddnet/ddnet pull request #7631
Opened 2023-12-11 19:49 UTC by Kaffeine

This is an alternative approach to https://github.com/ddnet/ddnet/pull/7598

The issue with the linked approach is that it is not flexible enough (the snap is still tied to the race game type).

The approach suggested in this MR is tested in action — I base [infclass](https://github.com/infclass/teeworlds-infclassR/tree/staging/src/game/server) mod on CPlayer (and CCharacter) subclassing.

Later on we can move DDNet-specific stuff to some CPlayer subclass but right now it is hard to extract something because ddracechat commands access virtually all ddrace specific stuff in CPlayer, so it is blocked by missing commands registration support in GameController.

I marked `virtual` a few methods in CPlayer so a mod can override them (and I actually override those methods in infclass).

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-12-12 10:19 UTC, Kaffeine commented
macOS CI failed because of unused `CGameControllerMod *m_pGameController` in CPlayerMod. I added it to demonstrate that this way the mod code does not need any casts to get the mod controller instance.

What do you think about the naming? Personally I'd prefer `CModPlayer` and `CModGameController` (e.g. `CDDRacePlayer` instead of `CPlayerDDRace`; I use names `CInfClassPlayer` and `CInfClassGameController`, `CInfClassCharacter`, etc for infclass) but as the mod controller has `Mod` as suffix I followed that scheme for now.

2023-12-12 22:28 UTC, ChillerDragon commented on src/game/server/player.h
> +	std::optional<float> m_Score;
Why did you change this to float?

2023-12-12 22:30 UTC, ChillerDragon commented
Amazing thanks for working on this. Im sure some ddnet devs are super annoyed by all the downstream prs by now. But this change would make basing mods on ddnet way more fun!

2023-12-12 22:35 UTC, Kaffeine commented on src/game/server/player.h
> +	std::optional<float> m_Score;
I tried to do more refactor and (tried to) move the score to DDRace subclass. It turned out that CPlayer depends on CScore for more stuff than I'd expect and I changed the type to get rid of the dependency (I also moved other stuff to the subclass). Then I hit the problem of ddracechat accessing CPlayer for that moved stuff, and as CScore is not a part of GameController I could not use the CPlayer subclass there.

I dropped other commits but this change of the type seems to be a reasonable cleanup (we need the fractional score part to provide Race info for 0.7). See the commit: 
https://github.com/ddnet/ddnet/pull/7631/commits/2aa6017b38de96f44163c4f730cfcd4451096014

2023-12-20 23:38 UTC, Kaffeine commented
Okay, while still waiting for any response, I also added CCharacter subclassing.

I don't like to put everything inside one file and I'll move the things when we clarify the classes naming (current scheme would be `CCharacterDDNet`, `CPlayerDDNet` but personally I'd tend to `CDDNetCharacter` and `CDDNetPlayer`; also `CGameControllerDDRace is currently living in `DDRace.cpp`, breaking all schemes except "put ddrace classes into DDRace.cpp and put mod classes into mod.cpp", which I'm following right now.

2023-12-21 16:48 UTC, Robyt3 approved these changes
LGTM. I don't have a strong preference for the naming of the mod classes, as long as it's applied consistently.

2024-01-08 18:48 UTC, heinrich5991 requested changes
Blocked on #7777.

2025-01-18 23:09 UTC, closed without merging