Use curl-multi. Supersedes #5842
ddnet/ddnet pull request #7683
Opened 2023-12-18 21:51 UTC by Learath2

This rebases and partially rewrites #5842. Tested very roughly

I still am not the biggest fan but this is the best I can do without going far too deep into a jobs rewrite: 
- This iteration uses the approach in #5092 as we talked about on Discord so the `IJob` interface is lost.
- Another issue is that this isn't a real engine interface but just pretends to be one so I can easily get pointers to it around the code. This can be mitigated by either designing a proper interface for `IHttpRequest` or by passing `CHttp` around everywhere like in #5092
- Finally one might want to rework the concurrency aids from `std` with our own ones, I'm far too tired of messing around with this PR to care about that.

@heinrich5991 you specifically should take a lookt at `CHttpRequest::Wait()`, the way I implemented it is rather nasty. You might want to replace it with a condvar but then you also need a mutex and suddenly there is a lot to think about. This feature is currently only used in `CRegister`.

@Robyt3 you should probably take a look at my changes in `menus_browser.cpp`. Since we don't want to stall the curl thread I moved the loading of the icon to a thread of it's own.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-12-20 16:42 UTC, Robyt3 requested changes

2023-12-23 13:45 UTC, Learath2 commented on src/engine/shared/http.h
> +	}
It's a typo, it should be checking that it's running or queued. Willfix

2023-12-23 13:46 UTC, Learath2 commented on src/game/client/components/menus_browser.cpp
> +		if(pJob->Done())
This is why the `Done` function exists because even you forgot the ERROR state

2023-12-25 10:23 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +		if(pJob->Done())
This is the only case were using the new `Done` function would currently make sense though. This check here will likely go away with #7376 and the check in `RequestDDNetInfo` shouldn't include canceled jobs IMO.

2023-12-25 10:54 UTC, Learath2 commented on src/engine/client/client.cpp
> +	if(m_pDDNetInfoTask && !m_pDDNetInfoTask->Done())
I think keeping `Done` here is fine too. If we are shutting down, unless I made a mistake somewhere `CHttp::Run` should auto abort any new job anyway.

2024-01-14 14:06 UTC, Learath2 commented
@heinrich5991 I'm still not very happy with it but I don't think I can do any better than this. Let's review/merge it before it gets out of date again?

2024-01-14 22:40 UTC, def- approved these changes
Perfect timing to get this in, lots of time to get tested in nightly

2024-01-15 18:01 UTC, Robyt3 approved these changes

2024-01-15 21:54 UTC, heinrich5991 approved these changes
Amazing. 🎉

2024-01-15 22:11 UTC, merged