Editor: better map settings input (autocomplete, validation)
ddnet/ddnet pull request #7687
Opened 2023-12-20 22:56 UTC by archimede67

## Description

Closes #7124, #1406.
This PR overhauls the map settings input in the editor. Previously, we could add invalid commands, we could have multiple times the same command with different argument values, etc. An improvement was suggested in #7124, as well as better checks requested in #1406. This PR aims to solve both of these issues.

To make it work, all the map settings are compiled into a single file when compiling with a new python script `map_settings.py`. This script is used to generate the files `map_settings.h` and `map_settings.cpp`, which contain the static data for the available map settings.

There are two new files: `editor_server_settings.h` and `editor_server_settings.cpp` which contain the implementation and the rendering code for the server settings editor, this is a step forward of splitting editor code.

By default, only recognized map settings from ddnet are considered valid. However, there is a toggle next to the input line which allows or disallows unknown commands. I believe this can be useful when mapping for a modded server using ddnet client.

The input has colored arguments for valid ddnet command names:
- numeric values are in green (integer, float)
- string values are in cyan (string, rest of string)
- any error argument or invalid command is rendered in red

For validation purposes, I have added some parsing methods to `system.h` and `system.cpp` that have a success check.

Finally, I fixed argument types being wrong for tune commands, as they used `i` but they are floats, so they now use `f`. I also removed the command `toggle_tune` from the map settings by removing `CFGFLAG_GAME` as it does not make sense to have it as a map setting.

## Functionality

Here is a small list of the main functionalities:
- Autocompletion of server settings names
- Autocompletion of some string arguments such as tunes and mapbugs
- Validation of each argument
- Colored input
- Error display
- Argument name display
- Works with undo/redo
- Automatically updates corresponding line in the list when trying to add a similar command
- Toggle unknown commands support

## Status

It works, but I opened this PR as draft for two things:
- I would like to get your opinions on it, maybe things to change or improve
- [ ] I want to add validation of existing server settings when loading a map, and showing which settings are incorrect as well as an option to change or delete invalid settings from the map

## Some previews

Below are some screenshots of different settings and how it looks like.

- Valid setting, while the cursor is on the 2nd argument (`tuning`):
![arg_list_and_colors](https://github.com/ddnet/ddnet/assets/13364635/2655cc41-02a0-42f7-9216-c2a6b836c080)

- Invalid value for an argument:
![invalid_value](https://github.com/ddnet/ddnet/assets/13364635/f09449e4-07d0-4143-9df9-a1c932f3b6ce)

- Too many arguments for the setting:
![too_many_args](https://github.com/ddnet/ddnet/assets/13364635/ec0cc95c-5fdb-4ae8-a30f-6742e1953814)

- Unknown setting, with unknown settings disallowed:
![disallow_unknown_setting](https://github.com/ddnet/ddnet/assets/13364635/9c6c1a25-9a78-4d65-a17f-d9f75ef9c73c)

- Unknown setting, with unknown settings allowed:
![allow_unknown_setting](https://github.com/ddnet/ddnet/assets/13364635/e91687fc-5a08-406e-91cd-f3e6b34f3877)

- Available commands list:
![suggestions](https://github.com/ddnet/ddnet/assets/13364635/c2bb9fa7-6d0c-4e30-b89f-91d3d055364b)

- Out of range error:
![err_out_of_range](https://github.com/ddnet/ddnet/assets/13364635/d03c4bd8-9968-4b48-86b2-fdfa9f9544cc)

## Demo

https://github.com/ddnet/ddnet/assets/13364635/4aebdc0d-6d50-4a3e-a181-1d5299040811

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-12-20 23:09 UTC, def- commented
Woah, looks fancy!

2023-12-22 16:27 UTC, Robyt3 requested changes

2023-12-22 16:27 UTC, Robyt3 commented on src/game/server/gamecontext.cpp
> +	Console()->Register("tune_zone", "i[zone] s[tuning] f[value]", CFGFLAG_SERVER | CFGFLAG_GAME, ConTuneZone, this, "Tune in zone a variable to value");
> Finally, I fixed argument types being wrong for tune commands, as they used `i` but they are floats, so they now use `f`. I also removed the command `toggle_tune` from the map settings by removing `CFGFLAG_GAME` as it does not make sense to have it as a map setting.

These changes and those in `gameclient.cpp` seem independent from the feature itself, so they would be a good candidate for a separate PR.

2023-12-22 16:27 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +		if(m_SettingsCommandInput.IsEmpty() || Input()->ModifierIsPressed()) // Allow ctrl+click to fill the input even if empty
> `Ctrl+Click` on a setting in the list to load it into the input

What's the motivation for this? Feels very unintuitive if the editbox doesn't stay synchronized with the listbox selection.

2023-12-22 16:27 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +		{
The dropdown menu should be closed when you click on a listbox item or you can't see some items because the dropdown keeps opening.

2023-12-22 16:27 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +		str_format(aOutput, sizeof(aOutput), "%s", Match.m_pValue);
No need for `str_format` here, also in some other places below

2023-12-22 16:30 UTC, Robyt3 commented on src/engine/client/text.cpp
> +						if(Split.m_Length != -1 && PrevCharCount >= (Split.m_CharIndex + Split.m_Length - 1))
Hmm, seems like it could overflow then if we aren't careful about the order of operations.

2023-12-22 16:52 UTC, archimede67 commented on src/game/editor/editor_server_settings.cpp
> +		if(m_SettingsCommandInput.IsEmpty() || Input()->ModifierIsPressed()) // Allow ctrl+click to fill the input even if empty
The motivation is that you can edit a command and then click on a command in the list that you might want to replace. Previously this would replace the current command, now to replace you ctrl+click to avoid having to retype everything in case you wanted to replace a command.
If it really feels unintuitive then I can just restore the old behavior

2023-12-22 16:55 UTC, archimede67 commented on scripts/map_settings.py
I first tried to not use an extra python script but I realized like you said that we have map settings commands that are not available since they are not registered on the client. So I figured the best option would be to make a script to compile everything into one file, regardless of where they are registered.

I mainly made this script to future-proof the code in case more commands are added, to avoid having to hard-code them elsewhere.

Now I understand the issue with such a script, and if you think it is better to hard code them, then sure thing, I can do that.

2023-12-22 16:56 UTC, archimede67 commented on src/engine/client/text.cpp
> +						if(Split.m_Length != -1 && PrevCharCount >= (Split.m_CharIndex + Split.m_Length - 1))
I believe this can work yes, didn't think about it

2023-12-22 17:23 UTC, archimede67 commented on src/game/client/lineinput.cpp
> +STextBoundingBox CLineInput::Render(const CUIRect *pRect, float FontSize, int Align, bool Changed, float LineWidth, float LineSpacing, const std::vector<STextColorSplit> &vColorSplits)
How can I test this?

2023-12-22 18:02 UTC, archimede67 commented on src/engine/client/text.cpp
> +						if(Split.m_Length != -1 && PrevCharCount >= (Split.m_CharIndex + Split.m_Length - 1))
Oh, so do we keep `-1` ?

2023-12-22 21:41 UTC, archimede67 commented on src/game/client/lineinput.cpp
> +STextBoundingBox CLineInput::Render(const CUIRect *pRect, float FontSize, int Align, bool Changed, float LineWidth, float LineSpacing, const std::vector<STextColorSplit> &vColorSplits)
Should be fixed now!

2023-12-22 21:42 UTC, archimede67 commented on src/game/editor/editor_server_settings.cpp
> +	if(DoButton_FontIcon(&Context.m_AllowUnknownCommands, FONT_ICON_BAN, !Context.m_AllowUnknownCommands, &Button, 0, "Disallow/allow unknown commands", IGraphics::CORNER_R))
I used "question" icon, which looks good and fits better as you suggested

2023-12-22 22:52 UTC, archimede67 commented on scripts/map_settings.py
I think if I need to use `IConfigManager`, then I would need to move the structs `SConfigVariable`, `SIntConfigVarialbe`, etc from `engine/shared/config.cpp` to `engine/shared/config.h` so that I can access them from the editor code.

2023-12-25 10:49 UTC, Robyt3 requested changes

2023-12-25 10:49 UTC, Robyt3 commented on src/engine/shared/config.h
> +struct SConfigVariable
`config.h` shouldn't contain the implementation, so you don't need to include `system.h` here.

2023-12-25 10:53 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +		if(m_SettingsCommandInput.IsEmpty() || Input()->ModifierIsPressed()) // Allow ctrl+click to fill the input even if empty
Maybe swap both actions so clicking is the same as before and Ctrl+clicking just changes the selection. Then this wouldn't change how mappers use the feature.

2023-12-26 16:05 UTC, archimede67 commented
I have added a new dialog that is shown after loading a map containing invalid settings.
The dialog displays a list in which you can fix the invalid settings, by either deleting or editing them.
It also displays duplicate settings in which case you can choose between one of them.
The dialog asks you to fix all the issues before you can continue editing the map. If you press "escape" or press the "cancel" button, the the map will "unload".

Here is a short demo:

https://github.com/ddnet/ddnet/assets/13364635/58b27a42-e8c3-4100-ae09-1acfb842bd94

And here is an example after loading the map "Paralyzed":
![map_settings_error_example](https://github.com/ddnet/ddnet/assets/13364635/4603a7bd-042c-4c12-a04d-acc850e9adbb)

2023-12-28 10:43 UTC, Robyt3 requested changes

2023-12-28 10:43 UTC, Robyt3 commented on src/game/editor/editor_actions.cpp
> +		printf("Restoring %s\n", m_PreviousCommand.c_str());
Remove debug message

2023-12-28 10:43 UTC, Robyt3 commented on src/game/editor/editor_ui.h
> +#endif
Newline

2023-12-28 10:43 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +}
Newline

2023-12-28 10:43 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +		const bool ArgCountValid = m_vCurrentArgs.size() == m_pBackend->m_ParsedCommandArgs.at(m_pCurrentSetting).size();
Unnecessary variable

2023-12-28 10:43 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +			dbg_msg("editor", "Warning: length of server setting name exceeds limit.");
Seems like a programming error if this happens so you should `dbg_assert` instead of continuing and likely performing out of bounds writes with the `str_copy` below.

2023-12-28 10:43 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +	}
Position the buttons more like in the other popups, i.e. cancel on the left and confirm on the right, with spacing between them.

2023-12-28 10:43 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +						if(DoButton_Editor(&Duplicate.m_Context.m_Chosen, "Choose", IsInvalid && !Duplicate.m_Context.m_Fixed ? -1 : Duplicate.m_Context.m_Chosen, &ChooseBtn, 0, "Override with this command"))
Add a small `HMargin` to the choose buttons, same as the fix button.

2023-12-28 10:43 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +	Overlay.Draw(ColorRGBA(0, 0, 0, 0.33f), 0, 0);
`IGraphics::CORNER_NONE` and `0.0f`

2023-12-28 10:43 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +		List.HSplitTop(20.0f, nullptr, &List);
Is this space and the space at the bottom of the list necessary?

2023-12-28 10:43 UTC, Robyt3 commented on src/engine/textrender.h
> +MAYBE_UNUSED static const char *FONT_ICON_QUESTION = "\x3F";
No need for encoding here, this is simply `"?"` (the constant is still a good idea, to be clear)

2023-12-28 11:11 UTC, archimede67 commented on src/game/editor/editor_server_settings.cpp
> +		List.HSplitTop(20.0f, nullptr, &List);
Yeah, it is needed to display either the error for the very first line in the list (the error is displayed above the line, so if there is no space then it gets clipped and is basically invisible), or the possible values dropdown for the very last line in the list (if there is no space then the dropdown would be clipped and would be almost invisible as well).

2023-12-28 11:30 UTC, archimede67 commented on src/game/editor/editor_server_settings.cpp
> +	}
Like in the file browser dialog? Or can I just change the order with cancel being on the left instead, but keep the size of the buttons?
![image](https://github.com/ddnet/ddnet/assets/13364635/b027691e-3316-4442-802c-d586cb782048)

2023-12-28 16:56 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +	}
Like in this popup I'd say:

![button order layout](https://github.com/ddnet/ddnet/assets/23437060/83e99df6-9905-420d-b35c-d8961f60d8ba)

2023-12-28 17:53 UTC, archimede67 commented on src/game/editor/editor_server_settings.cpp
> +	}
This is how it looks like:
![image](https://github.com/ddnet/ddnet/assets/13364635/30550d69-c41e-418b-bfd1-7397b5ffdcfc)

I'm not sure about it, do you think it looks better?

2023-12-28 18:41 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +	}
Looks good to me.

2023-12-30 16:40 UTC, furo321 commented
Commands and settings can contain the `#` character to create comments. Here's an example of it being used on the map `Volleyball`

![image](https://github.com/ddnet/ddnet/assets/141338449/b103f6df-f3a0-4db0-8caa-5f360cbaba77)

Or here on `Kobra 4 Solo` with it being its own line.

![image](https://github.com/ddnet/ddnet/assets/141338449/a9be72e1-ab19-4b87-b2c1-ba8ca306fc3c)

I also don't think you should force the user to fix the map settings, as the map may use non-ddnet specific commands like `Q-move` on KoG

![image](https://github.com/ddnet/ddnet/assets/141338449/31e4ff05-2abf-431d-8545-4edb1bbb0611)

2023-12-30 20:36 UTC, archimede67 commented
> Commands and settings can contain the `#` character to create comments. Here's an example of it being used on the map `Volleyball`
Ohh I did not even know this was a thing! Thanks for pointing it out, should be an easy fix.

> I also don't think you should force the user to fix the map settings, as the map may use non-ddnet specific commands like Q-move on KoG
These settings can be fixed using the "Fix" button and checking the "allow unknown commands" button next to the command input. I chose to not allow unknown settings when loading a map to show potential misspelled commands, for example `sv_taems` instead of `sv_teams`. I could allow unknown settings which would mark those settings as completely valid, but then we would not know if there is a misspelled setting somewhere.

2023-12-30 22:11 UTC, archimede67 commented
Also I'm not sure if we should allow empty map settings or not? I see it used on map `Kobra 4` to separate groups of settings

2024-01-11 18:04 UTC, archimede67 commented
@Robyt3 Do you have any more comments on this? ^^

2024-01-11 20:59 UTC, Robyt3 requested changes
Should also be tested more with ASAN/UBSAN.

2024-01-11 20:59 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +		UI()->DoLabel(&Label, pStr, FontSize, TEXTALIGN_MIDDLE);
`TEXTALIGN_MIDDLE` --> `TEXTALIGN_ML`

2024-01-11 20:59 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +	static float s_Width = View.w;
This should be part of `SEditBoxDropdownContext`. Otherwise each call to the `RenderEditBoxDropdown` function uses the same `static` variable, so you couldn't have multiple dropdowns at once like this.

2024-01-11 20:59 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +void CEditor::RenderMapSettingsErrorDialog()
There has to be a way to accept all unknown map settings in this dialog. Otherwise the user has to click on "Fix" and press enter for ever map setting every time they load a map that contains non-vanilla settings.

2024-01-11 20:59 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +{
Client crashes with seemingly random backtrace sometimes when loading any map after attempting to load another map that unknown map settings and cancelling the dialog.

2024-01-11 21:12 UTC, archimede67 commented
> Should also be tested more with ASAN/UBSAN.

Is there a guide on how to run ASAN/UBSAN on Windows?

2024-01-11 22:33 UTC, Robyt3 commented
> Is there a guide on how to run ASAN/UBSAN on Windows?

[Visual Studio seems to supports ASAN](https://learn.microsoft.com/en-us/cpp/sanitizers/asan?view=msvc-170). Otherwise you are likely out of luck. I use an Ubuntu VM for that.

2024-01-13 15:53 UTC, archimede67 commented on src/game/editor/editor_server_settings.cpp
> +{
Are you able to reproduce this somehow? I've been trying what you said but couldn't get it to crash. What are the maps you tried ?

2024-01-13 16:05 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +{
I used this map [testing_server_settings.zip](https://github.com/ddnet/ddnet/files/13928681/testing_server_settings.zip) and other vanilla maps like dm1 and ctf5. The crash doesn't happen every time though. Eventually it happens when you keep loading maps without settings and maps where the server settings dialog is opened. For example I got the crash after loading two vanilla maps in a row after loading a map with unknown map settings.

2024-01-13 16:08 UTC, archimede67 commented on src/game/editor/editor_server_settings.cpp
> +{
I see, and do you have any trace/logs of these crashes when they happened? I will try to reproduce, thanks!

2024-01-13 16:46 UTC, archimede67 commented on src/game/editor/editor_server_settings.cpp
> +{
I tried your map and i got the crash instantly when loading it. I think the issue was something to do with trying to copy data to an argument while data length exceeded the max argument length which was 160. I changed the length to be 256 and inserted a dbg_assert just in case.

Could you try again if you are able to get a crash again?

2024-01-13 19:24 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +{
Seems to work with this map now, but it shouldn't crash with `dbg_assert` when you load maps with too long settings either. Maps can contain settings of arbitrary length. It seems fine to me to simply truncate the settings to 256 bytes, the same as it was already done previously.

2024-01-13 19:36 UTC, archimede67 commented on src/game/editor/editor_server_settings.cpp
> +{
Alright I changed it so there is no more `dbg_assert` and only copies a maximum if 256 bytes for each argument to be safe.

2024-01-13 19:37 UTC, archimede67 commented
I ran it with ASAN/UBSAN and didn't find anything related to my changes after the latest fixes. I tried loading maps with unknown settings, loading valid maps, loading empty map, fixing settings in the dialog, adding new settings on a fresh map, etc. Nothing was reported, so I think it should all be fine now.

2024-01-14 18:25 UTC, Robyt3 commented
Thanks, I'll review this again in a few days. We should wait for 18.0 to be released before merging this to avoid conflicts.

2024-01-18 20:46 UTC, Robyt3 requested changes

2024-01-18 20:46 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +		while((pIt = str_next_token(pIt, " ", aBuffer, 128)))
`128` -> `sizeof(aBuffer)`

2024-01-18 20:46 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +		str_copy(aSubString, m_aCommand, minimum((int)m_LastCursorOffset + 1, 128));
`128` -> `sizeof(aSubString)`

2024-01-18 20:46 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +	if(DoButton_Editor(&s_FixAllButton, "Fix all unknown settings", CanFixAllUnknown ? 0 : -1, &FixAllUnknownButton, 0, nullptr))
`Allow` instead of `Fix` fit better here. otherwise it make it seem like this attempts to fix/change the commands.

2024-01-18 20:46 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +							if(Valid) // Just to make sure
This check is redundant

2024-01-18 20:46 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +						if(DoButton_Editor(&s_Ok, "Done", Valid ? 0 : -1, &OkBtn, 0, "Confirm edition of this command") || (s_Input.IsActive() && Valid && UI()->ConsumeHotkey(CUI::HOTKEY_ENTER)))
`edition` -> `editing`

2024-01-18 20:46 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +						if(DoButton_Editor(&s_Ok, "Done", Valid ? 0 : -1, &OkBtn, 0, "Confirm edition of this command") || (s_Input.IsActive() && Valid && UI()->ConsumeHotkey(CUI::HOTKEY_ENTER)))
`edition` -> `editing`

2024-01-18 20:46 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +int CEditor::DoEditBoxDropdown(SEditBoxDropdownContext *pDropdown, CLineInput *pLineInput, const CUIRect *pEditBoxRect, int x, float MaxHeight, bool AutoWidth, const std::vector<T> &vData, const FDro
The `pLineInput` argument seems redundant, it should always be the lineinput of the dropdown context.

2024-01-18 20:46 UTC, Robyt3 commented on src/game/editor/editor_server_settings.cpp
> +int CEditor::RenderEditBoxDropdown(SEditBoxDropdownContext *pDropdown, CUIRect View, CLineInput *pLineInput, int x, float MaxHeight, bool AutoWidth, const std::vector<T> &vData, const FDropdownRender
`pLineInput` argument redundant

2024-01-19 17:12 UTC, archimede67 commented on src/game/editor/editor_server_settings.cpp
> +int CEditor::DoEditBoxDropdown(SEditBoxDropdownContext *pDropdown, CLineInput *pLineInput, const CUIRect *pEditBoxRect, int x, float MaxHeight, bool AutoWidth, const std::vector<T> &vData, const FDro
There is no lineinput in the dropdown context, the lineinput is in the backend context `CContext`.

2024-01-23 18:30 UTC, Robyt3 approved these changes
LGTM, please squash the commits.

2024-01-24 18:10 UTC, archimede67 commented
@Robyt3 Is this good for you? I'd like to keep the input and the dialog in separate commits

2024-01-24 18:17 UTC, Robyt3 approved these changes
Thanks!

2024-01-24 18:34 UTC, merged