A few fixes and improvements to server-side auto demos.
ddnet/ddnet pull request #7709
Opened 2023-12-25 15:15 UTC by furo321

1. Fix `sv_auto_demo_record 1` not starting recording of auto demo. Closes #7573
2. Don't use the same demo recorder for manual and auto demos.
3. Change path of server auto demos from `demos/auto` to `demos/auto/server`. Also match the filenames to be the same as the client auto demos. `autorecord_(date)` -> `(current map)_(date)`

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-12-25 15:31 UTC, Robyt3 requested changes

2023-12-25 15:31 UTC, Robyt3 commented on src/engine/server/server.cpp
> +	m_aDemoRecorder[MAX_CLIENTS + 1] = CDemoRecorder(&m_SnapshotDelta, false);
Would be easier to understand if you define separate constants in `server.h` like `RECORDER_MANUAL = MAX_CLIENTS`, `RECORDER_AUTO` and `NUM_RECORDERS`.

2023-12-25 15:31 UTC, Robyt3 commented on src/engine/server/server.cpp
> -	if(m_aDemoRecorder[MAX_CLIENTS].IsRecording())
Check if either of the demo recorders is recording before creating the demo snapshot.

2023-12-25 15:31 UTC, Robyt3 commented on src/engine/server/server.cpp
> +			SnapshotSize = m_SnapshotBuilder.Finish(pData);
The previous variables shouldn't be reused, that seems bug prone.

2023-12-25 16:32 UTC, furo321 commented
Thanks, fixed!

2023-12-25 16:54 UTC, Robyt3 approved these changes

2023-12-26 07:58 UTC, def- approved these changes

2023-12-26 08:16 UTC, merged