Editor: refactor dragbar, allow resize of layers panel
ddnet/ddnet pull request #7734
Opened 2023-12-27 21:44 UTC by archimede67

Refactor dragbar code to allow using it for purposes other than extra editor heights. Dragbar can be now used from one of four sides, which allows changing width or height of specific containers.

With this, I made the layers panel resizeable:

https://github.com/ddnet/ddnet/assets/13364635/991bf71f-1571-4917-b5f1-55fd2c861e3e

This refactor also allows us to do something like this (Proof Of Concept):

https://github.com/ddnet/ddnet/assets/13364635/ed400448-0c89-4823-aba8-75f014d153b4

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2023-12-27 23:12 UTC, def- requested changes
There should be a different mouse cursor for when you hover over a resizable area: ↔

2023-12-28 00:30 UTC, archimede67 commented
I tried my best creating a good looking resize cursor. Here is a short demo:

https://github.com/ddnet/ddnet/assets/13364635/fa66c4d7-d456-4f8d-9342-b57435faf180

2023-12-28 16:52 UTC, Robyt3 approved these changes
Looks good, needs a rebase to retry the CI.

2023-12-28 18:03 UTC, def- approved these changes

2023-12-28 18:20 UTC, merged