Fix crash on editor autosave, add system method `timestamp_from_str`
ddnet/ddnet pull request #7749
Opened 2023-12-31 13:40 UTC by archimede67

When working on editor related features and having a debugger attached, I often got an exception after a few minutes of having it open. I then found out that this happened consistantly when the editor tried to autosave a new map.

This is likely due to #7712 which changed how timestamps work. The issue is the computed timestamp in `CFileCollection` which is not a UNIX timestamp, so when using it with a method that takes a UNIX timestamp, it throws an error.

In this PR I fixed this issue by introducing a new system method `timestamp_from_str` to parse a time string into a valid UNIX timestamp that can then be used with the method `str_timestamp_ex` (that previously caused the exception). I have also added a few tests for that specific method.

One issue is that I had to use C++ specific methods such as `std::get_time` and `std::istringstream` because there is no easy C-like way to parse a string into a timestamp, but since the project is using C++, why not use its features.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [x] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-01-01 00:14 UTC, def- requested changes

2024-01-01 00:14 UTC, def- commented on src/base/system.cpp
> +	dbg_assert(!ss.fail(), "Time string could not be parsed with the given format");
I don't think we should crash when a timestamp can't be parsed. How about returning an error instead?

2024-01-01 03:18 UTC, archimede67 commented on src/base/system.cpp
> +	dbg_assert(!ss.fail(), "Time string could not be parsed with the given format");
Hmm, usually when a timestamp can't be parsed it means that either the string or the format is invalid, which means there was an error somewhere else. I'm not sure how to return such error but I could try to do that if you really think we should not crash there.

2024-01-01 10:25 UTC, Robyt3 requested changes

2024-01-01 10:25 UTC, Robyt3 commented on src/test/timestamp.cpp
> +}
Adding a [test fixure with `SetUp`](https://github.com/google/googletest/blob/main/docs/primer.md#test-fixtures-using-the-same-data-configuration-for-multiple-tests-same-data-multiple-tests) function would be more idiomatic usage of gtest.

2024-01-01 10:25 UTC, Robyt3 commented on src/base/system.h
> +*/
Please use doxygen style for new code (see e.g. `str_copy` documentation).

2024-01-01 10:25 UTC, Robyt3 commented on src/engine/shared/filecollection.h
> +	time_t GetTimestamp(const char *pFilename);
I think you could combine the functions to check for a valid filename at the same time as you extract it. Then you could get rid of the manual timestamp validation in `IsFilenameValid` and let `timestamp_from_str` return an error instead of crashing with an assertion error. Also add some tests where parsing fails then.

2024-01-02 20:11 UTC, Robyt3 requested changes

2024-01-02 20:11 UTC, Robyt3 commented on src/test/timestamp.cpp
> +	EXPECT_EQ(Result, true);
The gtest output in case of failures is more readable if you avoid unnecessary temporary variables like `pString` and `Result` and instead write the entire function call in the gtest macro.

Also prefer using `EXPECT_FALSE` and `EXPECT_TRUE` instead of `EXPECT_EQ` for `bool`s.

Also in the test case below.

For example `EXPECT_TRUE(timestamp_from_str("2023-12-31_12-58-55", FORMAT_NOSPACE, &Timestamp));`

2024-01-03 17:42 UTC, Robyt3 approved these changes

2024-01-04 11:17 UTC, def- approved these changes

2024-01-04 11:35 UTC, merged