Add support for custom score kinds in ddnet mods
ddnet/ddnet pull request #7770
Opened 2024-01-07 09:18 UTC by ChillerDragon

Running ``./DDNet-Server "sv_gametype mod"`` now shows -9999 in scoreboard and reports the "points" score kind to master server. This gives ddnet based mods a clear api for using point based scores. Mods with minigames or similiar might also want to report different score types to different players that is why the api also includes the ClientID.

https://github.com/ZillyInsta/ddnet-insta/pull/83

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-01-07 14:45 UTC, jxsl13 commented
most important PR. I need this.

2024-01-08 04:17 UTC, Kaffeine commented on src/game/server/gamecontroller.h
> +	virtual CServerInfo::EClientScoreKind ScoreKind(int ClientID) { return CServerInfo::CLIENT_SCORE_KIND_TIME; };
`const`

2024-01-08 04:17 UTC, Kaffeine commented on src/game/server/gamecontext.h
> +	const char *ScoreKind() override;
Please use different names for methods returning different types. It is confusing to have `const char *CGameContext::ScoreKind()` and `CServerInfo::EClientScoreKind IGameController::ScoreKind(int ClientID)`, even though they have different args.

```suggestion
	const char *ScoreKindStr() override;
```

2024-01-08 04:17 UTC, Kaffeine commented on src/engine/server.h
> +	virtual const char *ScoreKind() = 0;
`const`

2024-01-08 16:41 UTC, Robyt3 requested changes

2024-01-08 16:41 UTC, Robyt3 commented on src/game/server/gamecontext.cpp
> +		return "time";
Seems like a programming error, so do something like this instead:

```cpp
dbg_assert(false, "IGameController::ScoreKind returned invalid value");
dbg_break();
```
(`dbg_break` allows you to leave out the `return` statement)

2024-01-08 16:51 UTC, heinrich5991 requested changes
This should be handled like `OnUpdatePlayerServerInfo` instead. Less code.

2024-01-08 16:51 UTC, heinrich5991 commented on src/game/server/gamecontext.cpp
> +		return "unspecified";
Only `CLIENT_SCORE_KIND_TIME` and `CLIENT_SCORE_KIND_POINTS` should be supported here. The rest are programming errors.

Irrelevant, see top-level review.

2024-01-08 16:51 UTC, heinrich5991 commented on src/game/server/gamecontroller.h
> +	virtual CServerInfo::EClientScoreKind ScoreKind(int ClientID) const { return CServerInfo::CLIENT_SCORE_KIND_TIME; };
```suggestion
	virtual CServerInfo::EClientScoreKind ScoreKind() const { return CServerInfo::CLIENT_SCORE_KIND_TIME; };
```
Shouldn't support making it dependent on the snapping client, it's basically unsupported by the protocol. There can only be one score kind in the server info, and only one score kind for all of the scoreboard for each client, so it doesn't make sense to mix them.

Irrelevant, see top-level review.

2024-01-08 17:52 UTC, ChillerDragon commented on src/game/server/gamecontroller.h
> +	virtual CServerInfo::EClientScoreKind ScoreKind(int ClientID) const { return CServerInfo::CLIENT_SCORE_KIND_TIME; };
This is also called in the snap where it does actually work to show timescore in the scoreboard for one player and point score for another.

2024-01-08 17:53 UTC, ChillerDragon commented
> This should be handled like `OnUpdatePlayerServerInfo` instead. Less code.

How is it less code? And isnt that called for every player? Can it even access the score kind? Or should I change OnUpdatePlayerServerinfo to also change non player data?

2024-01-08 17:54 UTC, heinrich5991 commented on src/game/server/gamecontroller.h
> +	virtual CServerInfo::EClientScoreKind ScoreKind(int ClientID) const { return CServerInfo::CLIENT_SCORE_KIND_TIME; };
> > and only one score kind for all of the scoreboard for each client, so it doesn't make sense to mix them.
>
> This is also called in the snap where it does actually work to show timescore in the scoreboard for one player and point score for another.

Yes, but only one score kind for the whole scoreboard in one client.

2024-01-08 18:12 UTC, ChillerDragon commented on src/game/server/gamecontroller.h
> +	virtual CServerInfo::EClientScoreKind ScoreKind(int ClientID) const { return CServerInfo::CLIENT_SCORE_KIND_TIME; };
Yes. ``ClientID`` is the SnappingClient

2024-01-08 18:15 UTC, ChillerDragon commented on src/game/server/gamecontroller.h
> +	virtual CServerInfo::EClientScoreKind ScoreKind(int ClientID) const { return CServerInfo::CLIENT_SCORE_KIND_TIME; };
```C++
void IGameController::Snap(int SnappingClient)
{
	// [..]

	CNetObj_GameInfoEx *pGameInfoEx = Server()->SnapNewItem<CNetObj_GameInfoEx>(0);
	if(!pGameInfoEx)
		return;

	pGameInfoEx->m_Flags =
		GAMEINFOFLAG_GAMETYPE_RACE |
		GAMEINFOFLAG_GAMETYPE_DDRACE |
		GAMEINFOFLAG_GAMETYPE_DDNET |
		GAMEINFOFLAG_UNLIMITED_AMMO |
		GAMEINFOFLAG_RACE_RECORD_MESSAGE |
		GAMEINFOFLAG_ALLOW_EYE_WHEEL |
		GAMEINFOFLAG_ALLOW_HOOK_COLL |
		GAMEINFOFLAG_ALLOW_ZOOM |
		GAMEINFOFLAG_BUG_DDRACE_GHOST |
		GAMEINFOFLAG_BUG_DDRACE_INPUT |
		GAMEINFOFLAG_PREDICT_DDRACE |
		GAMEINFOFLAG_PREDICT_DDRACE_TILES |
		GAMEINFOFLAG_ENTITIES_DDNET |
		GAMEINFOFLAG_ENTITIES_DDRACE |
		GAMEINFOFLAG_ENTITIES_RACE |
		GAMEINFOFLAG_RACE;
	if(ScoreKind(SnappingClient) == CServerInfo::CLIENT_SCORE_KIND_TIME)
		pGameInfoEx->m_Flags |= GAMEINFOFLAG_TIMESCORE;
```

The way I understood it this is called once for every client. And ``SnappingClient`` is the recipient of that snap. So for all of them it might be a different score kind if the server has mini games where one half of the player base sees score kinds and the other sees race times.

2024-01-08 18:18 UTC, heinrich5991 commented on src/game/server/gamecontroller.h
> +	virtual CServerInfo::EClientScoreKind ScoreKind(int ClientID) const { return CServerInfo::CLIENT_SCORE_KIND_TIME; };
> Yes. `ClientID` is the SnappingClient

Yes.

I'm saying:
1) This should not be supported by the source code, because it can only show the complete scoreboard in a different view, for a particular client.
2) This is irrelevant, because I want to remove this method completely, replacing it by a method appending to the JSON in mod controller (passed through from the engine).
[3) If this method were to stay, `ClientID` would need to be renamed to `SnappingClientID` or similar.]

2024-01-08 18:21 UTC, ChillerDragon commented on src/game/server/gamecontroller.h
> +	virtual CServerInfo::EClientScoreKind ScoreKind(int ClientID) const { return CServerInfo::CLIENT_SCORE_KIND_TIME; };
2. This is not about the master server or json. This is about the snap.
3. done

2024-01-08 18:32 UTC, ChillerDragon commented on src/game/server/gamecontroller.h
> +	virtual CServerInfo::EClientScoreKind ScoreKind(int ClientID) const { return CServerInfo::CLIENT_SCORE_KIND_TIME; };
Okay I removed the argument -.-
Now modders who need a per client score kind have to overwrite and reimplement the whole snap method.

2024-01-08 18:48 UTC, heinrich5991 requested changes
Blocked on #7777.

2024-10-05 03:22 UTC, closed without merging