fix switch screen and blackscreen on opengl + window borderless
ddnet/ddnet pull request #7937
Opened 2024-02-05 17:56 UTC by Peakies

Improvement of #7873

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-02-06 00:29 UTC, ChillerDragon commented on src/rust-bridge/engine/shared/rust_version.cpp
> +void cxxbridge1$RustVersionPrint(const ::IConsole &console) noexcept
Wat dis do?

2024-02-06 09:48 UTC, kbbytes commented on src/rust-bridge/engine/shared/rust_version.cpp
> +void cxxbridge1$RustVersionPrint(const ::IConsole &console) noexcept
don't know just fixed my errors that appears after downgrade rust version and upgrade doesn't fix it don't know why :(

2024-02-06 09:54 UTC, Peakies commented on src/rust-bridge/engine/shared/rust_version.cpp
> +void cxxbridge1$RustVersionPrint(const ::IConsole &console) noexcept
don't know just fixed my errors that appears after downgrade rust version and upgrade doesn't fix it don't know why :(

2024-02-06 09:55 UTC, ChillerDragon commented on src/rust-bridge/engine/shared/rust_version.cpp
> +void cxxbridge1$RustVersionPrint(const ::IConsole &console) noexcept
If you do not know what it is and it is not related to your opengl changes I think it makes sense to exclude it from this pullrequest.

2024-02-06 17:02 UTC, Jupeyy reviewed
I can't test this change because I don't have any second screen right now.

Generally I trust you that this works, I remember SDL was really weird in these cases on Windows.

I'd still like to have some very basic comments to at least say "This changes to windowed mode, bcs Windows breaks everything" or whatever you like, just so it's clear that this is a workaround + the person that touches the code next knows on which operating system this was tested on ^^

2024-02-06 19:44 UTC, Robyt3 commented on src/engine/client.h
> +	virtual void SwitchWindowScreen(int Index, int WindowMode = -1) = 0;
The window mode doesn't need to be a parameter AFAICT. The function should store the current `gfx_fullscreen` and `gfx_borderless` settings internally and then restore those after switching the screen.

2024-02-06 19:51 UTC, Robyt3 commented on src/engine/client/client.cpp
> +		SetWindowParams(3, false);
I don't think this loop is necessary, you can get only the current video mode for one screen with the `GetCurrentVideoMode` function.

2024-02-06 19:54 UTC, Robyt3 commented on src/engine/client/client.cpp
> +			g_Config.m_GfxScreenWidth = s_aModes[i].m_WindowWidth;
Seems like `SetWindowScreen` calls `UpdateDisplayMode` which then sets the desktop screen width/height, so this loop sets the gfx screen width/height to desktop screen width/height and updates refresh rate and color depth.

2024-02-06 21:34 UTC, heinrich5991 commented
Thanks for your first pull request by the way!

2024-02-08 12:08 UTC, kbbytes reviewed
check it now

2024-02-08 18:01 UTC, Robyt3 requested changes
Thanks, this works for me on Windows 10 with all combinations of backends and window modes.

Some more comments below.

2024-02-09 19:17 UTC, Peakies commented on src/game/client/components/menus_settings.cpp
> -		}
`static int s_NumNodes = Graphics()->GetVideoModes(s_aModes, MAX_RESOLUTIONS, g_Config.m_GfxScreen);`
Doing same, don't need to assignment again after switch screen

2024-02-09 19:26 UTC, Peakies commented on src/engine/graphics.h
> +	virtual void GetCurrentVideoMode(CVideoMode &pModes, int Screen) = 0;
I think `CurMode` are better

2024-02-09 19:41 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> -		}
That's a static initialization, it will only happen the first time the line of code is reached. Seems like `s_ModesReload` is set to `true` by the the window prop change listener though, which causes the resolutions to be updated, so this code is indeed not necessary.

2024-02-09 19:42 UTC, Robyt3 approved these changes
Thanks!

2024-02-09 20:05 UTC, merged