Move tele vector init from gamecontroller to collision
ddnet/ddnet pull request #7947
Opened 2024-02-08 07:41 UTC by ChillerDragon

Woah there cowboy! I know how this looks like. Breaking physics? Adding crash bugs? Increasing client startup time??

While trying to implement shift+n to see the previous teleporter in the editor I noticed how broken my old code is.
This thing seems to skip some tele tiles it should find #6887. Also the code is looping through the entire map which is not performant enough for live tele tracing which is needed for #2415. Also the weird loop makes it super messy to step forward and backward which is needed for #7931.

Having an indexed map seems like something that belongs into collision anyway and not into the game controller.
This also gives the client access to it. It does not use it yet. So for now its useless memory and cpu usage on client boot. Which I do not like. I was thinking of lazy loading it. So it only starts to fill the std::map and the std::vector inside when this getter is called the first time ``std::map<int, std::vector<vec2>> &TeleIns() { return m_TeleIns; }`` this way the client would not have any cpu/memory impact on launch. And would only ever fill the heap if the user is using a feature that requires to lookup teleporters.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-02-08 10:45 UTC, Kaffeine commented on src/game/collision.h
> +	std::map<int, std::vector<vec2>> &TeleCheckOuts() { return m_TeleCheckOuts; }
IIUC there is no valid reason to modify the teleport from the outside of the Collision. Then it makes sense to change this to `const std::map<int, std::vector<vec2>> &TeleIns() const {` to prevent bugs/abuses.
However such change will require some more code adjustments. Looking at `ddracecommands.cpp`:
```
if(!pSelf->Collision()->TeleOuts()[TeleTo - 1].empty())
```
The code will insert `pSelf->Collision()->TeleOuts()[TeleTo - 1]` if it was not in place before. Such modifying access is error prone. I'd suggest to change the API to `const std::vector<vec2>&TeleIn(int Number) const` but we still need the maps for `CCharacter::SetTeleports`. Or we don't? It was weird to access GameController from the character but now with the Tele moved, it seems natural to access them (in Character code) via Collision() getter.

2024-02-08 12:21 UTC, ChillerDragon commented on src/game/collision.h
> +	std::map<int, std::vector<vec2>> &TeleCheckOuts() { return m_TeleCheckOuts; }
Yea the whole passing it to character seems weird anyways. Its not like different tees have different teles or do they?

2024-02-08 13:27 UTC, Kaffeine commented on src/game/collision.h
> +	std::map<int, std::vector<vec2>> &TeleCheckOuts() { return m_TeleCheckOuts; }
>Its not like different tees have different teles or do they?

We don't work with copies (so they potentially could be different), and all characters have pointers to the same `std::map` instances which are members of GameController.

2024-02-09 04:41 UTC, ChillerDragon commented
Any opinions on lazy loading?

2024-02-09 05:24 UTC, Kaffeine commented
> Any opinions on lazy loading?

Probably the extra complication won't worths it.
The code does not look like a bottleneck, I guess the tele setup takes less than 1ms. It is more productive to optimize only the stuff that worths the effort and complexity.

2024-02-09 07:57 UTC, ChillerDragon commented on src/game/collision.h
> +	std::map<int, std::vector<vec2>> &TeleCheckOuts() { return m_TeleCheckOuts; }
Not sure how to add the second const

```
/home/chiller/Desktop/git/ddnet/src/game/collision.h:120:85: error: passing ‘const std::map<int, std::vector<vector2_base<float> > >’ as ‘this’ argument discards qualifiers [-fpermissive]
  120 |         const std::vector<vec2> &TeleIns(int Number) const { return m_TeleIns[Number]; }
      |                                                                                     ^
```

2024-02-09 07:58 UTC, ChillerDragon commented on src/game/collision.h
> +	std::map<int, std::vector<vec2>> &TeleCheckOuts() { return m_TeleCheckOuts; }
Could use .at() but that might throw. Could use if .contains() and then .at() but thats c++20

2024-02-17 09:40 UTC, Robyt3 requested changes

2024-02-17 09:40 UTC, Robyt3 commented on src/game/collision.cpp
> +		int Height = m_pLayers->TeleLayer()->m_Height;
Use `TeleLayer()` consistently instead mixing usage of `TeleLayer()` and `m_pLayers->TeleLayer()`

2024-02-17 09:40 UTC, Robyt3 commented on src/game/gamecore.cpp
> -	m_pTeleOuts = pTeleOuts;
`m_pTeleOuts` is now unused (see failed run)

2024-02-17 10:56 UTC, Robyt3 commented on src/game/collision.cpp
> +		int Height = m_pLayers->TeleLayer()->m_Height;
Ah. Would have been less confusing if it was named `TeleTiles` instead. We assume that all entities layers have the same size in `CCollision::Init` above, so you can use `CCollision::m_Width` and `m_Height` directly and check if `CCollision::TeleLayer` is non-nullptr instead of delegating to `m_pLayers`.

2024-02-17 17:02 UTC, Robyt3 approved these changes

2024-03-13 21:20 UTC, Robyt3 commented
Please rebase, @ChillerDragon. I'll merge this soon if nobody complains.

2024-03-14 00:51 UTC, ChillerDragon commented
:heavy_check_mark:

2024-03-14 17:02 UTC, Robyt3 approved these changes
Thanks!

2024-03-14 17:19 UTC, merged