Do not recalculate if the mouse did not move
ddnet/ddnet pull request #7949
Opened 2024-02-08 08:22 UTC by ChillerDragon

I feel like this broke something. But before it was running a bunch of calculations based on the mouse position. And that every tick no matter if the mouse position changed or not. I added some dbg_msg() below. And it used to spam every tick and now is only spammed on mouse move. Does it work on touch screens and joysticks? Not sure I only tested 10 seconds on my laptop touch pad.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-02-08 09:14 UTC, Robyt3 requested changes
You are checking if the mouse relative movement this input frame is the same as previously. Should probably use `CursorType` instead, which is `IInput::CURSOR_NONE` when there is no relative movement.

2024-02-08 12:18 UTC, ChillerDragon commented
Okay I did what robsti said. Also as jopsti pointed out on discord my approach was totally wrong. The concerns of @Kaffeine sound scary. Could someone who feels comfortable with the undo feature verify nothing broke?

2024-02-08 18:06 UTC, Robyt3 reviewed
Kaffeine's concern applies to all situations where the content below the mouse is changed without the mouse position changing. For example when you pan the map view with WASD it now doesn't update the X and Y position in the top right corner correctly anymore.

2024-02-09 00:35 UTC, ChillerDragon commented
I see so the pr is no good then?

2024-02-09 16:28 UTC, Robyt3 commented
Doesn't seem like a performance bottleneck so not really worth it right now.

2024-02-09 16:28 UTC, closed without merging

2024-02-09 23:38 UTC, ChillerDragon commented
👌