Move select layer to editor component
ddnet/ddnet pull request #7954
Opened 2024-02-09 04:39 UTC by ChillerDragon

This pr is all about adding ``virtual void OnHoverTile(int Group, int Layer, const CTile &Tile, int x, int y){};`` to close #7943

It fixes no bugs (probably adds some). It also decreases performance and adds no functionality.
The advantage is that there is now some easy to use api for new editor components that want to make tiles clickable or hoverable.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-02-09 11:54 UTC, Kaffeine commented on src/game/editor/editor_object.h
> +#include <memory>
I don't see any use of this header here.

2024-02-09 11:54 UTC, Kaffeine commented on src/game/editor/layer_selector.cpp
> +	const std::shared_ptr<CLayer> pLayer = pGroup->m_vpLayers[Layer];
It seems that the variables are not used.

2024-02-09 11:57 UTC, Kaffeine commented on src/game/editor/layer_selector.cpp
> +	if(++m_Matches == m_SelectionOffset)
*Personally* I'd prefer to have non-modifying comparison. Would you mind to move `++m_Matches` out of the `if()` for the sake of readability? Feel free to disagree.

2024-02-09 12:47 UTC, ChillerDragon commented on src/game/editor/editor_object.h
> +#include <memory>
Nope not anymore you are right

2024-02-09 12:49 UTC, ChillerDragon commented on src/game/editor/layer_selector.cpp
> +	if(++m_Matches == m_SelectionOffset)
idc here u go

2024-02-12 17:26 UTC, Robyt3 requested changes

2024-02-12 17:26 UTC, Robyt3 commented on src/game/editor/layer_selector.cpp
> +	s_CtrlClick = true;
This seems to side-step normal UI click handling involving hot items entirely, so it causes issues like this action being activated at the same time as others, e.g. when popup menus are open or when the color picker is active.

I'd prefer if this and #7612 were fixed first or within this PR, so we can be sure that this API change works without having this input handling hack.

2024-02-13 02:50 UTC, ChillerDragon commented on src/game/editor/layer_selector.cpp
> +	s_CtrlClick = true;
> This seems to side-step normal UI click handling involving hot items entirely

Oh right I never noticed. This should be fixed. I wonder if the check if other ui items are active should already happen higher up. So that OnHoverTile() is never even fired if another menu item is active. But not sure if someone might ever need tile hovering in that scenario. What do you think?

> I'd prefer if this and https://github.com/ddnet/ddnet/issues/7612 were fixed first or within this PR

#7612 seems unrelated but sure I also would like to see it fixed I can give it a try in this pr.
I thought a fix causes new bugs and one refactor is enough per pr but fine with me either way.

> this input handling hack.

What are you referring to? The bypass of other active items or using the static variable. I used the static variable so the click is only registered once on hold.

2024-02-13 02:54 UTC, ChillerDragon commented on src/game/editor/layer_selector.cpp
> +	s_CtrlClick = true;
I did this now. To fix the ui bypass.

```diff
diff --git a/src/game/editor/layer_selector.cpp b/src/game/editor/layer_selector.cpp
index a2584bc28..f1b97498e 100644
--- a/src/game/editor/layer_selector.cpp
+++ b/src/game/editor/layer_selector.cpp
@@ -13,6 +13,8 @@ bool CLayerSelector::SelectByTile()
 {
        // ctrl+rightclick a map index to select the layer that has a tile there
        static bool s_CtrlClick = false;
+       if(!UI()->CheckActiveItem(nullptr))
+               return false;
        if(!UI()->MouseButton(1) || !Input()->ModifierIsPressed())
        {
                s_CtrlClick = false;
```

2024-02-13 04:37 UTC, ChillerDragon commented on src/game/editor/layer_selector.cpp
> +	s_CtrlClick = true;
I fixed https://github.com/ddnet/ddnet/issues/7612 :partying_face:

By passing the raw mouse position and using that in the calculation. It used to use the offset of the currently active group before and now it is using the offset of the group that is actually being checked.

```diff
diff --git a/src/game/editor/editor.cpp b/src/game/editor/editor.cpp
index 683dfa361..17cd21db4 100644
--- a/src/game/editor/editor.cpp
+++ b/src/game/editor/editor.cpp
@@ -8450,10 +8450,10 @@ void CEditor::HandleCursorMovement()
                m_MouseWorldNoParaY = aPoints[1] + WorldHeight * (s_MouseY / Graphics()->WindowHeight());
        }
 
-       OnMouseMove();
+       OnMouseMove(s_MouseX, s_MouseY);
 }
 
-void CEditor::OnMouseMove()
+void CEditor::OnMouseMove(float MouseX, float MouseY)
 {
        for(CEditorComponent &Component : m_vComponents)
                Component.BeforeHoverTile();
@@ -8478,8 +8478,8 @@ void CEditor::OnMouseMove()
                        pGroup->Mapping(aMapping);
                        int x = aMapping[0] + (aMapping[2] - aMapping[0]) / 2;
                        int y = aMapping[1] + (aMapping[3] - aMapping[1]) / 2;
-                       x += UI()->MouseWorldX() - (MapView()->GetWorldOffset().x * pGroup->m_ParallaxX / 100) - pGroup->m_OffsetX;
-                       y += UI()->MouseWorldY() - (MapView()->GetWorldOffset().y * pGroup->m_ParallaxY / 100) - pGroup->m_OffsetY;
+                       x += MouseX - (MapView()->GetWorldOffset().x * pGroup->m_ParallaxX / 100) - pGroup->m_OffsetX;
+                       y += MouseY - (MapView()->GetWorldOffset().y * pGroup->m_ParallaxY / 100) - pGroup->m_OffsetY;
                        x /= 32;
                        y /= 32;
 
diff --git a/src/game/editor/editor.h b/src/game/editor/editor.h
index 5031062b0..92de65b38 100644
--- a/src/game/editor/editor.h
+++ b/src/game/editor/editor.h
@@ -443,7 +443,7 @@ public:
        void ResetIngameMoved() override { m_IngameMoved = false; }
 
        void HandleCursorMovement();
-       void OnMouseMove();
+       void OnMouseMove(float MouseX, float MouseY);
        void DispatchInputEvents();
        void HandleAutosave();
        bool PerformAutosave();
```

2024-02-13 06:23 UTC, ChillerDragon commented
I do not think the api is ready to be used for what I intended it to be used for. It is a bit tedious to receive the position to draw to if one wants to highlight tiles.

2024-02-13 11:55 UTC, ChillerDragon commented
> I do not think the api is ready to be used for what I intended it to be used for. It is a bit tedious to receive the position to draw to if one wants to highlight tiles.

So I made it work with some vector that is being pushed into in OnHoverTile() that is then rendered in OnRender() like so.

```c++
	for(auto HoverTile : m_vHoverTiles)
	{
		const std::shared_ptr<CLayerGroup> pGroup = m_Map.m_vpGroups[HoverTile.m_Group];
		const std::shared_ptr<CLayer> pLayer = pGroup->m_vpLayers[HoverTile.m_Layer];
		auto pLayerTiles = std::static_pointer_cast<CLayerTiles>(pLayer);

		float wx = UI()->MouseWorldX();
		float wy = UI()->MouseWorldY();

		pGroup->MapScreen();

		CUIRect Rect;
		Rect.x = wx;
		Rect.y = wy;
		Rect.w = 0;
		Rect.h = 0;

		Graphics()->TextureClear();
		Graphics()->QuadsBegin();
		Graphics()->SetColor(0.0f, 1.0f, 0.0f, 0.5f);
		pLayerTiles->Snap(&Rect);
		IGraphics::CQuadItem QuadItem(Rect.x, Rect.y, Rect.w, Rect.h);
		Graphics()->QuadsDrawTL(&QuadItem, 1);
		Graphics()->QuadsEnd();

		UI()->MapScreen();
	}
```

That seems okayish for the features it is planned to be used for.

2024-02-13 11:57 UTC, ChillerDragon commented on src/game/editor/layer_selector.cpp
> +	s_CtrlClick = true;
Okay something broke. What I commited 7 hours ago is not working. I thought I had a tested working version. But either I tested wrong or did not commit the right thing. The current state is still off.

2024-02-14 06:02 UTC, ChillerDragon commented on src/game/editor/layer_selector.cpp
> +	s_CtrlClick = true;
Okay this took way too long but it is working now. Supporting offsets and parra.

```diff
diff --git a/src/game/editor/editor.cpp b/src/game/editor/editor.cpp
index 17cd21db4..40f1c18f1 100644
--- a/src/game/editor/editor.cpp
+++ b/src/game/editor/editor.cpp
@@ -8473,15 +8473,22 @@ void CEditor::OnMouseMove(float MouseX, float MouseY)
                                continue;
 
                        std::shared_ptr<CLayerTiles> pTiles = std::static_pointer_cast<CLayerTiles>(pLayer);
-
-                       float aMapping[4];
-                       pGroup->Mapping(aMapping);
-                       int x = aMapping[0] + (aMapping[2] - aMapping[0]) / 2;
-                       int y = aMapping[1] + (aMapping[3] - aMapping[1]) / 2;
-                       x += MouseX - (MapView()->GetWorldOffset().x * pGroup->m_ParallaxX / 100) - pGroup->m_OffsetX;
-                       y += MouseY - (MapView()->GetWorldOffset().y * pGroup->m_ParallaxY / 100) - pGroup->m_OffsetY;
-                       x /= 32;
-                       y /= 32;
+                       pGroup->MapScreen();
+                       float aPoints[4];
+                       pGroup->Mapping(aPoints);
+                       float WorldWidth = aPoints[2] - aPoints[0];
+                       float WorldHeight = aPoints[3] - aPoints[1];
+                       CUIRect Rect;
+                       Rect.x = aPoints[0] + WorldWidth * (MouseX / Graphics()->WindowWidth());
+                       Rect.y = aPoints[1] + WorldHeight * (MouseY / Graphics()->WindowHeight());
+                       Rect.w = 0;
+                       Rect.h = 0;
+                       RECTi r;
+                       pTiles->Convert(Rect, &r);
+                       pTiles->Clamp(&r);
+                       int x = r.x;
+                       int y = r.y;
+                       UI()->MapScreen();
 
                        if(x < 0 || x >= pTiles->m_Width)
                                continue;
```

2024-02-14 21:10 UTC, Robyt3 reviewed
I prefer #7976. Seems like an easier interface to use and conceptualize.

2024-02-15 00:27 UTC, ChillerDragon commented
> I prefer #7976. Seems like an easier interface to use and conceptualize.

Agree so lets close this c:

2024-02-15 00:27 UTC, closed without merging