Move select layer to editor component
ddnet/ddnet pull request #7976
Opened 2024-02-14 06:47 UTC by ChillerDragon

Alternative for https://github.com/ddnet/ddnet/pull/7954

I did not like the complexity of #7954 at all. It was 3 callbacks and one of them gets called for every tile. Working with that was not nice. So I decided to go with one vector that can just be red by everyone who needs it. I like it from a developer experience now. But I hate the performance. It is iterating over all tiles in all layers every tick and pushing the ones under the cursor in some vector. I still get similar cpu/ram usage stats than before on my laptop. But there has to be a more performant way of achieving the same thing. Maybe not using a vector and use a statically allocated fixed size array of size 64 instead. And just drop support for hovering more than 64 overlapping tiles. Or calling that code less often. Only when the underlying tiles actually changed (but that seems to be [tricky](https://github.com/ddnet/ddnet/pull/7949#pullrequestreview-1870921754)).

closed #7943
closed #7612

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-02-14 21:07 UTC, Robyt3 requested changes

2024-02-14 21:07 UTC, Robyt3 commented on src/game/editor/layer_selector.cpp
> +	s_CtrlClick = true;
I found a better solution. After #7978 you can do this:

```suggestion
	if(!Input()->ModifierIsPressed() || UI()->HotItem() != &m_MapEditorId || !UI()->MouseButtonClicked(1))
		return false;

	int MatchedGroup = -1;
	int MatchedLayer = -1;
	int Matches = 0;
	bool IsFound = false;
```

This should ensure the action is only enabled when the map editor view is the hot item.

2024-02-15 01:07 UTC, ChillerDragon commented on src/game/editor/editor.cpp
> +			UI()->MapScreen();
Yes works after the loop

2024-02-15 01:09 UTC, ChillerDragon commented on src/game/editor/editor.h
> +		const CTile &m_Tile;
Can the constructor argument stay a reference so it does not copy twice?

```
CHoverTile(int Group, int Layer, int x, int y, const CTile &Tile) :
                        m_Group(Group),
			m_Layer(Layer),
			m_X(x),
			m_Y(y),
			m_Tile(Tile)
```

2024-02-15 01:16 UTC, ChillerDragon commented on src/game/editor/layer_selector.cpp
> +	s_CtrlClick = true;
I do not understand why it works without the static variable at all. But I tested it and it works.

2024-02-15 02:36 UTC, ChillerDragon commented
```diff
diff --git a/src/game/editor/editor.cpp b/src/game/editor/editor.cpp
index a9e89e2dd..2e1dd75c0 100644
--- a/src/game/editor/editor.cpp
+++ b/src/game/editor/editor.cpp
@@ -8474,7 +8474,8 @@ void CEditor::HandleCursorMovement()
 
 void CEditor::OnMouseMove(float MouseX, float MouseY)
 {
-	m_vHoverTiles.clear();
+	int i = 0;
+	mem_zero((void *)m_aHoverTiles, sizeof(m_aHoverTiles));
 	for(size_t g = 0; g < m_Map.m_vpGroups.size(); g++)
 	{
 		const std::shared_ptr<CLayerGroup> pGroup = m_Map.m_vpGroups[g];
@@ -8513,8 +8514,15 @@ void CEditor::OnMouseMove(float MouseX, float MouseY)
 				continue;
 			CTile Tile = pTiles->GetTile(x, y);
 			if(Tile.m_Index)
-				m_vHoverTiles.emplace_back(CHoverTile(
-					g, l, x, y, Tile));
+			{
+				m_aHoverTiles[i].m_Group = g;
+				m_aHoverTiles[i].m_Layer = l;
+				m_aHoverTiles[i].m_X = x;
+				m_aHoverTiles[i].m_Y = y;
+				m_aHoverTiles[i].m_Tile = Tile;
+				m_aHoverTiles[i].m_Valid = true;
+				i++;
+			}
 		}
 	}
 	UI()->MapScreen();
diff --git a/src/game/editor/editor.h b/src/game/editor/editor.h
index 41be25f69..ac06d10f6 100644
--- a/src/game/editor/editor.h
+++ b/src/game/editor/editor.h
@@ -439,16 +439,21 @@ public:
 			m_Y(y),
 			m_Tile(Tile)
 		{
+			m_Valid = true;
+		}
+		CHoverTile() : m_Tile(CTile())
+		{
+			m_Valid = false;
 		}
 
+		bool m_Valid;
 		int m_Group;
 		int m_Layer;
 		int m_X;
 		int m_Y;
-		const CTile m_Tile;
+		CTile m_Tile;
 	};
-	std::vector<CHoverTile> m_vHoverTiles;
-	const std::vector<CHoverTile> &HoverTiles() const { return m_vHoverTiles; }
+	CHoverTile m_aHoverTiles[64];
 
 	void Init() override;
 	void OnUpdate() override;
diff --git a/src/game/editor/layer_selector.cpp b/src/game/editor/layer_selector.cpp
index 9b4d50c17..aedafedb4 100644
--- a/src/game/editor/layer_selector.cpp
+++ b/src/game/editor/layer_selector.cpp
@@ -21,8 +21,11 @@ bool CLayerSelector::SelectByTile()
 	int MatchedLayer = -1;
 	int Matches = 0;
 	bool IsFound = false;
-	for(auto HoverTile : Editor()->HoverTiles())
+	for(auto HoverTile : Editor()->m_aHoverTiles)
 	{
+		if(!HoverTile.m_Valid)
+			break;
+
 		if(MatchedGroup == -1)
 		{
 			MatchedGroup = HoverTile.m_Group;
```

So this one also works and it does not use a vector. It does no heap allocations. Any thoughts on performance @Robyt3?

2024-02-15 19:41 UTC, Robyt3 commented on src/game/editor/editor.h
> +		const CTile &m_Tile;
Passing a reference needs 8 bytes on 64 bit systems, whereas `CTile` is only 4 bytes large so it seems cheaper to pass it by value.

2024-02-17 04:06 UTC, ChillerDragon commented
Indeed ``m_vHoverTiles.capacity()`` never goes down. Not even when closing the editor. So I thought thats bad. Almost like a memory leak. And opening the editor could affect in game fps after that due to higher ram usage. But then I realized what numbers we are talking about here. The highest capacity I could trigger was 16 I tested two of my own maps that I know to be polluted with overlapping tiles. So thats ``16 x sizeof(CHoverTile)`` which is currently 4 ints and one CTile. I plan to extend it possibly with 2 more ints. But even then the increased ram usage should be totally fine. And calling shrink_to_fit() on editor close might not even be worth it.

That is amazing. Feels like with C++ you can write code so easy as if it was a scripting language and still get performance of C under the hood??

2024-02-17 09:34 UTC, Robyt3 approved these changes

2024-02-17 09:51 UTC, merged