Add validation for `StrToInts` and `IntsToStr`, move and rename
ddnet/ddnet pull request #8073
Opened 2024-03-07 21:44 UTC by Robyt3

Rename `StrToInts` function to `str_to_int32` and add strict validation. Because this function should only used with trusted internal strings, assertions are added to ensure that no invalid UTF-8 is being encoded as integers and that the string is not truncated. Some buffer sizes are adjusted accordingly, so truncation cannot happen.

Rename `IntsToStr` function to `int32_to_str` and add lenient validation. An additional argument specifying the size of the output buffer is added to assert that the size of the output buffer is sufficient. However, because this function is used to decode data sent by the server and read from maps and ghosts, invalid input data should never result in crashes or invalid UTF-8 strings. This function will replace invalid UTF-8 codepoints with `?` characters. The Unicode replacement character is not used, because it's 3 bytes long, so the string with added replacement characters may not fit into the buffer and this would also make the function more complicated, because it would require a temporary buffer. This provides reasonable support for loading old maps which might contain invalid UTF-8 in their layer, group or envelope names.

The functions are renamed and moved from `gamecore.h` to `system.h`. The motivation for this is that the tools would otherwise have to depend on game-shared, which previously only worked because the functions were inline. The inline definition is not wanted, because it requires adding a `system.h` include in `gamecore.h`.

Tests are added to ensure the function still behaves the same as before for valid inputs and correctly handles invalid inputs.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [X] Written a unit test (especially base/) or added coverage to integration test
- [X] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [X] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-03-07 22:26 UTC, def- commented
Why is this relevant for 18.1?

2024-03-07 22:35 UTC, Robyt3 commented
This would ensure that 18.1 clients don't crash on servers that did not receive #8057 yet, which would be relevant mostly for old mods. DDNet and KoG servers shouldn't be affected anymore.

2024-03-07 22:39 UTC, def- approved these changes

2024-03-08 12:11 UTC, Learath2 commented on src/base/system.cpp
> +	auto &&write_byte = [ints, &byte_index](int b) mutable {
This write byte by byte doesn't get optimized out by gcc or clang, this is not much of a concern for things like map layer names, but I wonder if we take any significant hit from it when snapping players which is O(n^2)

2024-03-08 12:19 UTC, Learath2 commented on src/base/system.cpp
> +	auto &&write_byte = [ints, &byte_index](int b) mutable {
Though I guess the byte by byte write is overshadowed by the fact that we now encode and decode each codepoint, so it's probably a non-issue.

2024-03-08 12:53 UTC, heinrich5991 requested changes
I'd prefer to be very strict with this very weird encoding.

2024-03-08 12:53 UTC, heinrich5991 commented on src/base/system.cpp
> +void str_to_int32(int *ints, size_t num_ints, const char *str)
I think the name doesn't do justice to the fact that these functions use a very weird encoding.

Perhaps `str_to_weird_tw_int32_encoding`? I think it's useful to say that this function shouldn't really be used.

2024-03-08 12:53 UTC, heinrich5991 commented on src/base/system.cpp
> +	// Clear all integers, which also ensures null-termination,
This is wrong, the null byte isn't encoded as 0, despite what the old code used to say, but rather as 128, I think.

2024-03-08 12:53 UTC, heinrich5991 commented on src/base/system.cpp
> +	auto &&write_byte = [ints, &byte_index](int b) mutable {
I'd echo what @Learath2 says. Preferably, this wouldn't decode UTF-8, but only fix the truncation at the end.

Could be done by doing a `str_utf8_rewind` on the source string and then a `str_utf8_forward` again and deleting everything in between if it goes to a different position.

2024-03-08 12:53 UTC, heinrich5991 commented on src/base/system.cpp
> +	}
Shouldn't mangle the data IMO, but return an error instead.

2024-03-08 15:37 UTC, heinrich5991 commented
> The functions are renamed and moved from `gamecore.h` to `system.h`. The motivation for this is that the tools would otherwise have to depend on game-shared, which previously only worked because the functions were inline. The inline definition is not wanted, because it requires adding a `system.h` include in `gamecore.h`.

Actually, could we maybe leave them in game/ and add game-shared code to tools? I find it a bit weird to have this tw-specific encoding that shouldn't really be used in our system abstraction layer.

2024-03-08 21:41 UTC, Robyt3 commented on src/base/system.cpp
> +	// Clear all integers, which also ensures null-termination,
The char '\0' was previously encoded as `0x80` (128) if appeared too early in the string, but the last byte that's encoded in the ints is always explicitly set to `0x00`. I simply adopted the wording from the old code, although it's probably not really accurate either:

```cpp
// null terminate
pInts[-1] &= 0xffffff00;
```

2024-03-08 21:41 UTC, Robyt3 commented on src/base/system.cpp
> +void str_to_int32(int *ints, size_t num_ints, const char *str)
> Actually, could we maybe leave them in game/ and add game-shared code to tools? I find it a bit weird to have this tw-specific encoding that shouldn't really be used in our system abstraction layer.

Seems fine if you prefer it this way.

2024-03-08 21:45 UTC, Robyt3 commented on src/base/system.cpp
> +	auto &&write_byte = [ints, &byte_index](int b) mutable {
I wouldn't even attempt to fix the truncation with this function. It's only called with trusted input, so I think we can simply assert that `str_length(str) <= num_ints * sizeof(int) - 1` at the beginning to prevent truncation.

2024-03-08 21:57 UTC, Robyt3 commented on src/base/system.cpp
> +	}
So the function should return a `bool` indicating success and we should

- discard `NETOBJTYPE_CLIENTINFO` with invalid members in the gameclient,
- load empty string for invalid layer, group and envelope names and show an error message in the editor, and
- load `default` skin name for invalid ghosts?

I wanted to avoid breaking maps, but I guess this wouldn't be too bad, as layer, group and envelope names are not relevant for ingame map rendering.

2024-03-09 09:47 UTC, Robyt3 commented on src/base/system.cpp
> +	auto &&write_byte = [ints, &byte_index](int b) mutable {
However, both of this wouldn't fix the case of out-of-bounds reads in the string data, because the string could have less bytes than `num_ints * sizeof(int) - 1` bytes.

For example `str_to_int32(&pClientInfo->m_Skin0, 6, "default")` should only read 8 bytes from the input string but it will read 24, beyond the size of the static string data.

Even if we write whole ints at a time we need to make sure we don't read outside the string buffer.

2024-03-10 11:52 UTC, Robyt3 commented on src/base/system.cpp
> +	auto &&write_byte = [ints, &byte_index](int b) mutable {
Mostly changed back to the old code with assertions to prevent truncation and without the GCC warning suppression.

2024-03-10 11:52 UTC, Robyt3 commented on src/base/system.cpp
> +void str_to_int32(int *ints, size_t num_ints, const char *str)
Done.

2024-03-10 11:54 UTC, Robyt3 commented on src/base/system.cpp
> +	}
Now `IntsToStr` only unpack the empty string and return `false` on invalid UTF-8. Discarding client info seems risky, I don't want to introduce regressions with this in 18.1, so I in the client I choose name `nameless tee` if the name contains invalid UTF-8 and otherwise keep the empty clan/skin.

2024-03-10 13:41 UTC, Learath2 approved these changes
Looks good to me

2024-03-10 14:15 UTC, merged

2024-03-10 14:22 UTC, Robyt3 commented
@def- Please replace 653c5d0 with 02f6042 in 18.1.