Editor: allow saving empty quads & sounds layers
ddnet/ddnet pull request #8102
Opened 2024-03-15 17:37 UTC by archimede67

In the editor, currently if you create new quads and sounds layers or have quads and sounds layers that are empty and then save the map, it will not save those empty layers. This then leads to missing layers and you can wonder where they went. I don't think this is needed (and it surprised me when I discovered this), as we can optimize the map if we need to to clear any empty layers afterwards but not while saving in the editor.

Now it will correctly save those layers as well.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-03-15 17:53 UTC, Robyt3 requested changes

2024-03-15 17:53 UTC, Robyt3 commented on src/game/editor/mapitems/map_io.cpp
>  					Item.m_Data = Writer.AddDataSwapped(pLayerQuads->m_vQuads.size() * sizeof(CQuad), pLayerQuads->m_vQuads.data());
`Item.m_Data` is not initialized when this branch is not taken, it should be set to `-1` so it's correctly initialized. However, it seems that this would break compatibility because old clients cannot handle the quad data being missing in maps saved with this PR. Same applies to the other layers. You need to save dummy data, it can't be empty because the datafile does not allow that.

2024-03-15 18:02 UTC, archimede67 commented on src/game/editor/mapitems/map_io.cpp
>  					Item.m_Data = Writer.AddDataSwapped(pLayerQuads->m_vQuads.size() * sizeof(CQuad), pLayerQuads->m_vQuads.data());
I think setting `m_Data` to `-1` is sufficient. The reason is that when old clients are trying to load a data index of `-1`, it will simply return `nullptr` and data the size will be `0`. Then, the `mem_copy` will copy `0` elements (because `m_NumQuads` (or `m_NumSources`) will be `0`) which I believe does not break anything. Therefore, I don't think there is a need to save dummy data.

2024-03-15 18:04 UTC, archimede67 commented on src/game/editor/mapitems/map_io.cpp
>  					Item.m_Data = Writer.AddDataSwapped(pLayerQuads->m_vQuads.size() * sizeof(CQuad), pLayerQuads->m_vQuads.data());
I just tested this fix, saved a map with it then opened it in 18.0.3 which worked without any problems

2024-03-15 19:23 UTC, Robyt3 commented on src/game/editor/mapitems/map_io.cpp
>  					Item.m_Data = Writer.AddDataSwapped(pLayerQuads->m_vQuads.size() * sizeof(CQuad), pLayerQuads->m_vQuads.data());
It might work with your compiler, but it's undefined behavior according to the standard.

> If either dest or src is an invalid or null pointer, the behavior is undefined, even if count is zero.

https://en.cppreference.com/w/cpp/string/byte/memcpy

2024-03-15 20:05 UTC, archimede67 commented on src/game/editor/mapitems/map_io.cpp
>  					Item.m_Data = Writer.AddDataSwapped(pLayerQuads->m_vQuads.size() * sizeof(CQuad), pLayerQuads->m_vQuads.data());
Can we add a check to `mem_cpy` to not do anything if `size` is `0`? And maybe extend that to other `mem_*` methods?

2024-03-15 20:21 UTC, archimede67 commented on src/game/editor/mapitems/map_io.cpp
>  					Item.m_Data = Writer.AddDataSwapped(pLayerQuads->m_vQuads.size() * sizeof(CQuad), pLayerQuads->m_vQuads.data());
Alright, so technically any valid pointer would do

2024-03-16 09:36 UTC, Robyt3 commented on src/game/editor/mapitems/map_io.cpp
>  					Item.m_Data = Writer.AddDataSwapped(pLayerQuads->m_vQuads.size() * sizeof(CQuad), pLayerQuads->m_vQuads.data());
I think it would make more sense if the dummy data would be a zeroed or a valid quad/soundsource instead of a random integer.

2024-03-16 11:11 UTC, archimede67 commented on src/game/editor/mapitems/map_io.cpp
>  					Item.m_Data = Writer.AddDataSwapped(pLayerQuads->m_vQuads.size() * sizeof(CQuad), pLayerQuads->m_vQuads.data());
The integer isn't "random", in this case it is the layer type. I did it like this so it would save as little data as possible (size of an int)

2024-03-16 12:22 UTC, Robyt3 commented on src/game/editor/mapitems/map_io.cpp
>  					Item.m_Data = Writer.AddDataSwapped(pLayerQuads->m_vQuads.size() * sizeof(CQuad), pLayerQuads->m_vQuads.data());
Probably not worth it to save a few bytes if this makes the code and map format more confusing.

I suppose "random value" was not precise, maybe "arbitrary value in this context" would have been better. Any dummy integer would've sufficed so `AddDataSwapped` and `GetData` technically work, but IMO picking anything except `0` in this situation seemed [random](https://xkcd.com/221/)/arbitrary to me. IMO adding a complete dummy quad/source is cleaner overall though.

2024-03-16 16:02 UTC, archimede67 commented on src/game/editor/mapitems/map_io.cpp
>  					Item.m_Data = Writer.AddDataSwapped(pLayerQuads->m_vQuads.size() * sizeof(CQuad), pLayerQuads->m_vQuads.data());
If you feel adding extra bytes to the map file by adding a complete dummy object is better, then sure I can do that instead.

2024-03-18 20:43 UTC, Robyt3 requested changes
Best to zero-initialize those dummy objects so they have at least some defined value in the map format. Otherwise the same map could be different each time you save it due to gargabe memory being saved.

2024-03-18 20:43 UTC, Robyt3 commented on src/game/editor/mapitems/map_io.cpp
> +					CQuad Dummy;
```suggestion
					CQuad Dummy{};
```

2024-03-18 20:43 UTC, Robyt3 commented on src/game/editor/mapitems/map_io.cpp
> +					CSoundSource Dummy;
```suggestion
					CSoundSource Dummy{};
```

2024-03-18 22:13 UTC, Robyt3 approved these changes

2024-03-18 22:31 UTC, merged