What about #8019
ddnet/ddnet pull request #8141
Opened 2024-03-23 04:25 UTC by ChillerDragon

This is not a pullrequest. This is an issue.

https://github.com/ddnet/ddnet/pull/8019 just introduced a strict style guide. And it has been already violated. This should either checked manually before new prs get merged. Or fixed on a regular basis. Or better added to ./scripts/fix_style.py

2024-03-23 08:41 UTC, def- requested changes

2024-03-23 08:41 UTC, def- commented on src/game/client/components/menus_settings.cpp
> +			Ui()->DoScrollbarOption(&g_Config.m_UiControllerSens, &g_Config.m_UiControllerSens, &Button, Localize("Ui controller sens."), 1, 500, &CUi::ms_LogarithmicScrollbarScale, CUi::SCROLLBAR_OPTION_NOCL
This is wrong, it's not an identifier

2024-03-23 08:41 UTC, def- commented on src/game/client/components/menus_settings.cpp
> +			Ui()->DoScrollbarOption(&g_Config.m_UiMousesens, &g_Config.m_UiMousesens, &Button, Localize("Ui mouse sens."), 1, 500, &CUi::ms_LogarithmicScrollbarScale, CUi::SCROLLBAR_OPTION_NOCLAMPVALUE);
wrong

2024-03-23 08:41 UTC, def- commented on src/game/client/components/menus_settings.cpp
> +	DoLine_ColorPicker(&s_UiColorResetId, 25.0f, 13.0f, 2.0f, &MainView, Localize("Ui Color"), &g_Config.m_UiColor, color_cast<ColorRGBA>(ColorHSLA(0xE4A046AFU, true)), false, nullptr, true);
wrong

2024-03-23 08:41 UTC, def- commented on src/game/client/ui.cpp
> +	dbg_assert(m_vUIRects.empty(), "Ui rects can only be initialized once, create another ui element instead.");
wrong

2024-03-23 08:43 UTC, archimede67 commented on src/game/client/lineinput.h
> +	Ui,
Wrong, this is an enum

2024-03-23 09:58 UTC, ChillerDragon commented
xd guys I am aware that it is wrong. But then the fix script needs to be improved and integrated into the CI. I just ran the command @heinrich5991 built.

This is not a pullrequest that should be merged. It just shows that running this has a diff which it shouldn't:

```
sed -i \
        -e 's/\([a-z]_\?\)ID/\1Id/g' \
        -e 's/\([^ ]\)\<UI\>/\1Ui/g' \
        -e 's/UI()/Ui()/g' \
        -e 's/\<CUI\>/CUi/g' \
        -e 's/\([\ta-z.(&]\|[,=|] \)ID\>/\1Id/g' \
        -e 's/\<ID\>\([^ ").]\)/Id\1/g' \
        -e 's/\<ID\([0-9]\)/Id\1/g' \
        -e 's/\<ID\>\( [<=>:+*/-]\)/Id\1/g' \
        -e 's/int ID/int Id/g' \
        -e 's/\([a-z]_\?\)GPU/\1Gpu/g' \
        -e 's/\([a-z]_\?\)IP/\1Ip/g' \
        -e 's/\([a-z]_\?\)CID/\1Cid/g' \
        -e 's/\([a-z]_\?\)MySQL/\1Mysql/g' \
        -e 's/MySql/Mysql/g' \
        -e 's/\([a-xz]_\?\)SQL/\1Sql/g' \
        -e 's/DPMode/DpMode/g' \
        -e 's/TTWGraphics/TTwGraphics/g' \
        \
        -e 's/Ipointer/IPointer/g' \
        -e 's/\.vendorId/.vendorID/g' \
        -e 's/\.windowId/.windowID/g' \
        -e 's/SDL_GetWindowFromId/SDL_GetWindowFromID/g' \
        -e 's/SDL_AudioDeviceId/SDL_AudioDeviceID/g' \
        -e 's/SDL_JoystickId/SDL_JoystickID/g' \
        -e 's/SDL_JoystickInstanceId/SDL_JoystickInstanceID/g' \
        -e 's/AVCodecId/AVCodecID/g' \
        src/**/*.cpp src/**/*.h {datasrc,scripts}/**/*.py
git checkout -- src/engine/external
```

Not all of them are false positives and #8019 is not very long ago. If we keep introducing style violations the huge reformatting commit was not really worth it. And if the fix script has false positives it can not be used by branches or forks to automatically resolve conflicts.

2024-03-23 10:07 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +				s_vpGpuIdNames[i] = GPUList.m_vGpus[i - 1].m_aName;
The script should also change `GPU` -> `Gpu` (except in strings).

2024-03-23 10:12 UTC, ChillerDragon commented
I wonder if it would be smarter to use something like tree sitter here instead of a naive script.

2024-03-23 10:15 UTC, Robyt3 commented
If you want to fix/check variable names in the CI for all our conventions then I don't think naive scripts will work.

1. Use C++ parser to get all variable declarations + locations
2. Filter based on location (ignore external etc.)
3. Filter based on variable name (ignore i and other allowed short variable names)

2024-03-26 01:45 UTC, ChillerDragon commented
I just wanted to show that heinrichs script causes a diff which is not nice. It is not solved yet but I don't want this weird non pr to become stale. So closing this.

2024-03-26 01:45 UTC, closed without merging