Add delta debug dump
ddnet/ddnet pull request #8236
Opened 2024-04-20 10:38 UTC by ChillerDragon

There is already a DebugDump() method for snapshots but there was none for deltas yet. I wrote this to debug an issue I was facing that only happend after the delta was unpacked so I wanted to see what was in the delta.

The method is unused and supposed to be patched in while debugging. For example like this

```diff
diff --git a/src/engine/client/client.cpp b/src/engine/client/client.cpp
index 79a19a65b..ce0be00b8 100644
--- a/src/engine/client/client.cpp
+++ b/src/engine/client/client.cpp
@@ -1757,6 +1757,9 @@ void CClient::ProcessServerPacket(CNetChunk *pPacket, int Conn, bool Dummy)
                                                DeltaSize = IntSize;
                                        }
 
+
+                                       m_SnapshotDelta.DebugDumpDelta(pDeltaData, DeltaSize);
+
                                        // unpack delta
                                        const int SnapSize = m_SnapshotDelta.UnpackDelta(pDeltaShot, pTmpBuffer3, pDeltaData, DeltaSize);
                                        if(SnapSize < 0)
```

```
2024-04-20 18:30:53 I delta_dump: +-----------------------------------------------                                                                                                                                                                                              
2024-04-20 18:30:53 I delta_dump: |  data_size=160                                                                                                                                                                                                                              
2024-04-20 18:30:53 I delta_dump: |    0            0  00000000 m_NumDeletedItems=0                                                                                                                                                           
2024-04-20 18:30:53 I delta_dump: |    1            2  00000002 m_NumUpdatedItems=2                                                                                                                                                           
2024-04-20 18:30:53 I delta_dump: |    2            0  00000000 _zero=0                                                                                                                                                                       
2024-04-20 18:30:53 I delta_dump: |  --------------------------------                                                                                                                                                                         
2024-04-20 18:30:53 I delta_dump: |    3            9  00000009 updated Type=9                                                                                                                                                                
2024-04-20 18:30:53 I delta_dump: |    4            0  00000000 updated Id=0                                                                                                                                                                  
2024-04-20 18:30:53 I delta_dump: |                             updated size=88 (known)                                                                                                                                                       
2024-04-20 18:30:53 I delta_dump: |    5           26  0000001a item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |    6            0  00000000 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |    7           32  00000020 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |    8            0  00000000 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |    9         -128  ffffff80 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |   10          402  00000192 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |   11            0  00000000 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |   12            0  00000000 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |   13            0  00000000 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |   14            0  00000000 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |   15            0  00000000 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |   16            0  00000000 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |   17           33  00000021 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |   18            0  00000000 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |   19            0  00000000 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |   20            1  00000001 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |   21            0  00000000 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |   22            0  00000000 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |   23            0  00000000 item data                                                                                                                                                                     
2024-04-20 18:30:53 I delta_dump: |   24            0  00000000 item data                                                                                                     [...]

2024-04-23 07:31 UTC, ChillerDragon commented on src/engine/shared/snapshot.cpp
> +		return -201;
done

2024-04-23 07:33 UTC, ChillerDragon commented
This could also be called when UnpackDelta fails to have useful information in the logs. But not sure.

2024-04-24 08:45 UTC, ChillerDragon commented
Okay yea fine with me. Then lets leave it unused.

2024-04-24 16:01 UTC, Robyt3 requested changes
Looks good, just some small nitpicks.

2024-04-24 16:01 UTC, Robyt3 commented on src/engine/shared/snapshot.cpp
> +		dbg_msg("delta_dump", "|  Invalid delta. Red past the end");
`Red` -> `Read`

2024-04-24 16:01 UTC, Robyt3 commented on src/engine/shared/snapshot.cpp
> +		dbg_msg("delta_dump", "|  Invalid delta. NumDeltedItems=%d is below zero.", pDelta->m_NumDeletedItems);
`NumDeltedItems` -> `NumDeletedItems`

For consistency with the other error message `below zero. `-> `negative`

2024-04-25 15:49 UTC, Robyt3 approved these changes

2024-04-25 16:23 UTC, merged