screen check for switch screen index
ddnet/ddnet pull request #8254
Opened 2024-04-23 12:06 UTC by Peakies

update for #7937 and fix for issue #8191

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-04-23 12:12 UTC, def- approved these changes

2024-04-23 15:30 UTC, Jupeyy commented
I am tagged as reviewer:

I find it weird to call such stuff every frame.
I don't know what `DisplayFusion` is, but does it not trigger any SDL event we can listen for?
If GetWindowScreen results in a SDL call, how can SDL know the window screen changed?
Does it cache it? Does it query it through a system call every frame now?

2024-04-23 16:59 UTC, Robyt3 reviewed
I agree with @Jupeyy, we should find out if the Windows Window Manager other programs like DisplayFusion send some kind of window event that we could listen to, instead of polling this every frame.

2024-04-24 19:20 UTC, Robyt3 requested changes

2024-04-24 19:20 UTC, Robyt3 commented on src/engine/client/backend_sdl.cpp
> +		SDL_AddEventWatch(&ScreenSwitchCallbackWrapper, this);
We already handle `SDL_WINDOWEVENT` in `input.cpp`. We shouldn't add a separate handler for it here.


Especially `SDL_AddEventWatch` should not be used because the callback is not thread-safe.

> WARNING: Be very careful of what you do in the event filter function, as it may run in a different thread!

https://wiki.libsdl.org/SDL2/SDL_AddEventWatch

2024-04-24 19:20 UTC, Robyt3 commented on src/engine/client/backend_sdl.cpp
> +				SetWindowParams(IsFullscreen, IsBorderless);
We should avoid this duplicate code. Possibly by merging `CClient::SetWindowParams` in `CGraphics_Threaded::SetWindowParams` and by moving `CClient::SwitchWindowScreen` to new `CGraphics_Threaded::SwitchWindowScreen`.

2024-04-26 09:46 UTC, kbbytes commented on src/engine/client/backend_sdl.cpp
> +		SDL_AddEventWatch(&ScreenSwitchCallbackWrapper, this);
I'm busy a little I'll check for it and find better and more clean code for switch screen

2024-04-26 18:07 UTC, Robyt3 reviewed
When moving the client window in Windowed mode to another screen using the mouse, then the resolution will be changed to fullscreen immediately. Moving a window to another screen should keep its original size in Windowed mode.

2024-04-27 09:10 UTC, Robyt3 requested changes
The screen change is sometimes not detected correctly when moving the window between screens in all fullscreen modes using default Windows+Shift+Left/Right hotkeys. This causes an incorrect resolution to be used when switching between screens and the wrong screen will be shown in the dropdown menu.

When moving the window between screens with the mouse, the window will now snap to the center of the screen when ending the movement on a different screen as before. Is it possible to avoid the snapping to center? Maybe avoiding setting the screen with the SDL function again if the current screen is the same would work.

Switching between screens using the Screen dropdown menu in the settings doesn't change the resolution to fullscreen anymore since the previous change. I suppose you need to handle manual changes of only the screen differently than changes where the window is moved which also changes the screen.

2024-04-27 09:10 UTC, Robyt3 commented on src/engine/client/backend_sdl.h
> +#include <SDL.h>
This include is unnecessary here in this header. Only add it exactly where required.

2024-04-27 09:10 UTC, Robyt3 commented on src/engine/client/input.h
> +#include <engine/client.h>
Unnecessary include here, only add it where required.

2024-04-27 09:10 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +		str_format(aBuf, sizeof(aBuf), " %dx%d @%dhz %d bit (%d:%d)", s_aModes[i].m_WindowWidth, s_aModes[i].m_WindowHeight, s_aModes[i].m_RefreshRate, Depth, s_aModes[i].m_WindowWidth / G, s_aModes[i].m_W
What's the difference between the canvas and window size and why was this changed?

2024-04-27 09:42 UTC, Peakies commented on src/game/client/components/menus_settings.cpp
> +		str_format(aBuf, sizeof(aBuf), " %dx%d @%dhz %d bit (%d:%d)", s_aModes[i].m_WindowWidth, s_aModes[i].m_WindowHeight, s_aModes[i].m_RefreshRate, Depth, s_aModes[i].m_WindowWidth / G, s_aModes[i].m_W
on fullscreen mode switching too fast sometime have m_CanvasWidth as zero and client crash cuz 0 can't devided and etc so I changed to m_WindowWidth and solved that problem

2024-04-28 10:47 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +		str_format(aBuf, sizeof(aBuf), " %dx%d @%dhz %d bit (%d:%d)", s_aModes[i].m_WindowWidth, s_aModes[i].m_WindowHeight, s_aModes[i].m_RefreshRate, Depth, s_aModes[i].m_WindowWidth / G, s_aModes[i].m_W
Does it happen without this PR? I couldn't reproduce it without this change, so it seems like a different bug with this PR that results in width and height being zero for a video mode.

2024-04-28 21:17 UTC, kbbytes commented on src/game/client/components/menus_settings.cpp
> +		str_format(aBuf, sizeof(aBuf), " %dx%d @%dhz %d bit (%d:%d)", s_aModes[i].m_WindowWidth, s_aModes[i].m_WindowHeight, s_aModes[i].m_RefreshRate, Depth, s_aModes[i].m_WindowWidth / G, s_aModes[i].m_W
It's happening on this PR after I add switch function on event listener for switches check

2024-04-29 14:28 UTC, Peakies commented
Sorry for messing up everything don't know why it's list all master commits but check below commit please 
[switch screen version 0.4](https://github.com/ddnet/ddnet/pull/8254/commits/cae792682a1241ff45e7a2cb4890b0273db71cd8)

2024-04-29 16:09 UTC, Jupeyy commented
git rebase upstream/master (where upstream is ddnet repo)

then they should be gone (normally)

2024-04-29 16:17 UTC, Jupeyy commented
And you are sure that 
git remote get-url upstream
leads to the official ddnet repo: https://github.com/ddnet/ddnet/ ?

Else dunno how u did that xD

2024-04-29 16:32 UTC, kbbytes commented
> git rebase upstream/master

git remote -v 
alt     git@github.com:ddnet/ddnet.git (fetch)
alt     git@github.com:ddnet/ddnet.git (push)
origin  git@github-second:Peakies/ddnet.git (fetch)
origin  git@github-second:Peakies/ddnet.git (push)

2024-04-29 16:32 UTC, kbbytes commented
> And you are sure that
> 
> ```
> git remote get-url upstream
> ```
> 
> leads to the official ddnet repo: https://github.com/ddnet/ddnet/ ?
> 
> Else dunno how u did that xD

git remote -v
alt [git@github.com](mailto:git@github.com):ddnet/ddnet.git (fetch)
alt [git@github.com](mailto:git@github.com):ddnet/ddnet.git (push)
origin git@github-second:Peakies/ddnet.git (fetch)
origin git@github-second:Peakies/ddnet.git (push)

2024-04-29 16:55 UTC, closed without merging

2024-04-29 17:22 UTC, Peakies commented on src/engine/client/input.cpp
> +				}
sometime it's goes to screen 0 but on graphic setting drop menu it's selected as screen 1 and sometime has been select as 0 but on screen 1 and this is best way that I could handle bugs and wrong monitor selection most of time it's happening on `fullscreen` or `fullscreen desktop`

for now I didn't find a better way to handle on all screen modes