Finnish language file update
ddnet/ddnet pull request #8269
Opened 2024-04-26 19:01 UTC by PotatoCreator

The Finnish translations were incomplete, causing some user interface elements to fall back on the English default. This pull request aims to provide a fully localized experience for Finnish users.

Please note that builds and other checks will be run for your change. Don't feel intimidated by failures in some of the checks. If you can't resolve them yourself, experienced developers can also help resolve them before merging your pull request.

## Checklist

- [x] Completed missing translations for Finnish language file

2024-04-26 19:04 UTC, Robyt3 requested changes

2024-04-26 19:04 UTC, Robyt3 commented on data/languages/finnish.txt
> +Epäonnistui alustuksen aikana. Yritä muuttaa gfx_backend arvoksi OpenGL tai Vulkan asetushakemistossa settings_ddnet.cfg ja yritä uudelleen.
The text in square brackets should not be translated, it only serves as additional context for the translator.

Add only the translated text on the line with the `==`. Also several times below.

2024-04-26 19:22 UTC, PotatoCreator commented
Hope I didn't miss any.

2024-04-26 19:30 UTC, furo321 commented
You seemed to have accidentally deleted some strings from the file.

<details>
  <summary>Here are the ones that are currently missing.</summary>

```
Loading demo file from storage
== 

No login required
== 

Player info change cooldown
== 

Converse
== 

Always show chat
== 

Show friend mark (♥) in name plates
== 

Show hook strength icon indicator
== 

Show hook strength number indicator
== 

Show own player's hook collision line
== 

Always show own player's hook collision line
== 

Always show other players' hook collision lines
== 
```
</details>

2024-04-27 15:47 UTC, def- approved these changes

2024-04-27 15:47 UTC, def- commented on data/languages/finnish.txt
> +
This line was accidentally added?

2024-04-27 16:21 UTC, PotatoCreator commented on data/languages/finnish.txt
> +
I guess, can you edit it?

2024-04-29 04:24 UTC, def- commented on data/languages/finnish.txt
> +
```suggestion

```

2024-04-29 04:24 UTC, def- approved these changes

2024-04-29 17:35 UTC, merged