Fix ddnet ex snap item registration (closed #8271)
ddnet/ddnet pull request #8272
Opened 2024-04-27 08:16 UTC by ChillerDragon

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-04-27 08:22 UTC, ChillerDragon commented
I don't like that the uuids are now registered at the end of the snap. That could probably fixed with some mem_copy or similar to insert snap items in the beginning instead of append to the end. But it seems to be working at the end too. Snap order does matter sometimes especially in this case.

2024-04-27 08:27 UTC, Robyt3 approved these changes

2024-04-27 08:30 UTC, ChillerDragon commented
@Robyt3 are you sure that adding an ddnet ex item to the snap before its registration item is working correctly? Because I am not.

2024-04-27 08:39 UTC, Robyt3 requested changes
Hmm, seems like this causes issues when the snapshot is full, because then the ex-items are dropped first.

To test, use `sv_map dm2; tune grenade_fire_delay 0; tune grenade_speed 0; tune grenade_lifetime 1000` and shoot grenades. Without this changes, the first items to disappear are sounds and explosions. With this changes, the projectiles disappear entirely when the snapshot is full.

2024-04-27 08:42 UTC, ChillerDragon commented
> Hmm, seems like this causes issues when the snapshot is full, because then the ex-items are dropped first.
> 
> To test, use `sv_map dm2; tune grenade_fire_delay 0; tune grenade_speed 0; tune grenade_lifetime 1000` and shoot grenades. Without this changes, the first items to disappear are sounds and explosions. With this changes, the projectiles disappear entirely when the snapshot is full.

Snapshot full is bad either way isn't it. But yes I would also like to have the registration in the beginning but for a different reason. I want to make sure that the uuid lookup does not fail because of some code that depends on snap item order.

I just don't see a clean way of inserting snap items in the beginning when the snapshot builder finished.

2024-04-27 09:28 UTC, ChillerDragon commented
Okay new idea. I am happy with that one now. So instead of putting all ddnet uuids at the beginning or the end of the snap I put the uuid right before the first item of that type that uses it. The code still has bugs and I have to go. So there is no code pushed yet.

2024-04-27 09:33 UTC, ChillerDragon commented
Okay nvm I made it work. But only had time for a quick test. In game looked good. The snap dump looked good too.

```
2024-04-27 17:31:54 I snapshot: data_size=520 num_items=17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
2024-04-27 17:31:54 I snapshot:         type=6 id=0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
2024-04-27 17:31:54 I snapshot:                   0            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   1            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   2            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   3            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   4            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   5            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   6            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   7            1        00000001                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:         type=0 id=32767                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
2024-04-27 17:31:54 I snapshot:                   0  -1824658838        933dea6a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   1   -629591830        da7930ea                                                                                                                                                                                       [...]

2024-04-29 14:26 UTC, heinrich5991 commented
It was intentional that extended item types never get dropped from the snap once they were added once. This is to make sure to not generate unnecessary diff traffic for extended item types as they're not expected to change. Can you restore that? It'd also get rid of the boolean array, since you could add all the extended item types in the beginning again.

2024-04-29 23:10 UTC, ChillerDragon commented
> It was intentional that extended item types never get dropped from the snap once they were added once. This is to make sure to not generate unnecessary diff traffic for extended item types as they're not expected to change. Can you restore that? It'd also get rid of the boolean array, since you could add all the extended item types in the beginning again.

When you say "extended item types" what are you reffering to? The items with type=0 and uuid as payload? Or the others?
In general I lack some proper wording for the two types of things. Is there anything official? How are those two called?
```
2024-04-27 17:31:54 I snapshot:         type=0 id=32766                                                                                                                                                                                                                                                                                                                                     
2024-04-27 17:31:54 I snapshot:                   0    583701389        22ca938d                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   1    327171627        13803e2b                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   2  -1636052395        9e7bd255                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   3  -1901674991        8ea6be11                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:         type=32766 id=0                                                                                                                                                                                                                                                                                                                                     
2024-04-27 17:31:54 I snapshot:                   0            1        00000001                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   1            0        00000000   
```
I would call the first one register and the second one ddnet ex. Because the first one registers the type 32766 to be the uuid 
22ca938d-1380-3e2b-9e7b-d2558ea6be11 which is known as [player@netobj.ddnet.tw](https://github.com/ddnet/ddnet/blob/03a0071d2885e13fbcfc5998fe73ebc71751973e/datasrc/network.py#L265-L268). And the second one is the actual ddnet ex object.

Isn't a higher diff the last problem when the snap is full? It dropped important gameplay information and then sends more bytes than it should. Nobody will be bothered by the latter if the former happend. Or do you mean that changing the order of the snap items creates a diff already in normal gameplay when new items get added and removed.

Yea I would be totally fine with adding the snap items in the beginning again. But I do not know how write the code for that.
I did not think the uuids in front of the items using it would be any problem. Now that I think about it I could do a mix. All old known ones are inserted at the top like they used to be. And the ones that are used for the first time in the snap get inserted before they are used.

2024-04-30 08:07 UTC, ChillerDragon commented
Okay I did that now @heinrich5991 

> Now that I think about it I could do a mix. All old known ones are inserted at the top like they used to be. And the ones that are used for the first time in the snap get inserted before they are used.

It is mostly like it was before. All loaded ddnet ex items are registered in the beginning. But all that are newly added for the first time are right in front of their corresponding snap item.

So the snapshot for the first connecting client on a fresh server start shows no errors when running with `debug 1` and has no uuids in the beginning yet because the server never loaded them.

```
2024-04-30 16:03:33 I snapshot: data_size=356 num_items=10                                                                                                                                                                                                                                                                                                                                  
2024-04-30 16:03:33 I snapshot:         type=6 id=0                                                                                                                                                                                                                                                                                                                                         
2024-04-30 16:03:33 I snapshot:                   0            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   1            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   2            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   3            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   4            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   5            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   6            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   7            1        00000001                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:         type=0 id=32767                                                                                                                                                                                                                                                                                                                                     
2024-04-30 16:03:33 I snapshot:                   0  -1824658838        933dea6a                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   1   -629591830        da7930ea                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   2  -1450210576        a98f8af0                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   3    914991429        3689a945                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:         type=32767 id=0                                                                                                                                                                                                                                                                                                                                     
2024-04-30 16:03:33 I snapshot:                   0    247983155        0ec7ec33                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   1            9        00000009                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   2           64        00000040                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:         type=11 id=0                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   0  -1008145940        c3e8e9ec                                                                                                     [...]

2024-04-30 08:53 UTC, heinrich5991 commented on src/engine/shared/snapshot.h
> +	bool m_aRegisteredExtendedItemTypes[MAX_EXTENDED_ITEM_TYPES];
This boolean array became unnecessary with the latest changes, no? You always know when you add an item type.

2024-04-30 08:53 UTC, heinrich5991 commented on src/engine/shared/snapshot.cpp
> -	}
Unnecessary diff.

2024-04-30 09:58 UTC, ChillerDragon commented on src/engine/shared/snapshot.h
> +	bool m_aRegisteredExtendedItemTypes[MAX_EXTENDED_ITEM_TYPES];
It adds all known ones from previous snaps in the beginning. And all new ones on demand.

To not add them twice if they are already known we have to keep track of the ones that were already added.

2024-04-30 10:07 UTC, heinrich5991 commented on src/engine/shared/snapshot.cpp
> +	AddExtendedItemType(m_NumExtendedItemTypes);
> It adds all known ones from previous snaps in the beginning. And all new ones on demand.
> 
> To not add them twice if they are already known we have to keep track of the ones that were already added.

There are exactly three call sites of `AddExtendedItemType`, one here, one where you mentioned and one above. In first two cases where it is called, it is statically known that item type hasn't been added to the snapshot yet. In the last case, it's statically known that the item type has been added already, making the call unnecessary. This means, as far as I understand it, that `m_aRegisteredExtendedItemTypes` is unnecessary.

2024-04-30 10:07 UTC, heinrich5991 commented on src/engine/shared/snapshot.cpp
> +	dbg_assert(0 <= Index && Index <= m_NumExtendedItemTypes, "index out of range");
```suggestion
	dbg_assert(0 <= Index && Index < m_NumExtendedItemTypes, "index out of range");
```

Please increment `m_NumExtendedItemTypes` first so that we can keep this out-of-bounds assert.

2024-05-01 01:27 UTC, ChillerDragon commented on src/engine/shared/snapshot.cpp
> +	AddExtendedItemType(m_NumExtendedItemTypes);
Ah I finally got it. Thanks to your comment on irc. Fixed :white_check_mark:.

2024-05-01 01:37 UTC, ChillerDragon commented
Okay after incorporating all feedback I did a full test again and it works as expected.
The layout of the snapshot still is exactly the same as described [here](https://github.com/ddnet/ddnet/pull/8272#issuecomment-2084661923).

Meaning all snaps that are bug free have the exact same format as on the master branch.
And the snaps with the edge case of new ddnet ex items being used for the first time by the server have the uuid items a bit later in the snap but only for exactly one snap. So no client running with debug on will show any errors anymore.

I tested with CSnapshot::DebugDump() on the client side.
I tested reconnecting.
I looked at the first and second snapshot carefully.
I tested with asan.
I tested recording and playing back demos.
I verified that new ddnet ex items that were added later than the first snap work correctly (spectator info)

![image](https://github.com/ddnet/ddnet/assets/20344300/93a8dc36-54fe-4402-a389-2529de18d9ea)

2024-05-01 09:56 UTC, heinrich5991 approved these changes
Perfect! Thanks.

2024-05-01 10:14 UTC, merged