Add support for colored broadcast (0.7 compatible)
ddnet/ddnet pull request #8283
Opened 2024-04-29 03:05 UTC by ChillerDragon

Example rcon command:
```
broadcast "aaaaaaa^123bbbbbbbbbbbb^321cccccccccccccccccc"
```

^123 and ^321 are the color codes that will not be included in the displayed text

![ddnet_teeworlds_broadcast_color_codes](https://github.com/ddnet/ddnet/assets/20344300/37ae9d99-a6f6-49b7-b555-93105d69bfb9)

See https://github.com/ddnet/ddnet/issues/4897

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-04-29 03:05 UTC, ChillerDragon commented
Blocked by https://github.com/ddnet/ddnet/issues/8282

2024-04-29 17:43 UTC, Robyt3 requested changes
Seems acceptable, though I would prefer if the textrender was changed to support `STextColorSplit` also with text containers instead of creating a separate text container for every colored segment.

2024-04-29 17:43 UTC, Robyt3 commented on src/game/client/components/broadcast.cpp
> +inline bool IsCharANum(char c)
Should maybe add `str_isnum(char c)` to `system.h` in a separate commit and use that consistently.

2024-04-30 09:18 UTC, ChillerDragon commented
>  though I would prefer if the textrender was changed to support STextColorSplit also with text containers instead of creating a separate text container for every colored segment.

@Robyt3 do you want to do this? Because I do not. If this is blocking we can close the pr because I don't feel like doing that right now.

2024-04-30 09:34 UTC, ChillerDragon commented on src/game/client/components/broadcast.cpp
>  void CBroadcast::OnReset()
Nice catch forgot to null terminate the broadcast buffer.

2024-04-30 09:36 UTC, heinrich5991 commented
I think that this is a rather random format for colors in text. I'd hope that there's some standard format of applying color to text.

`<span style="color: #c00000">red text</span>`

Not sure what would be a good format.

2024-04-30 09:37 UTC, ChillerDragon commented
> I think that this is a rather random format for colors in text. I'd hope that there's some standard format of applying color to text.
> 
> `<span style="color: #c00000">red text</span>`
> 
> Not sure what would be a good format.

Yes it is but it is what teeworlds uses.

2024-04-30 09:38 UTC, heinrich5991 commented
Perhaps we could "support" that by dropping these formatting characters from 0.7 broadcasts instead.

2024-04-30 09:41 UTC, ChillerDragon commented
> Perhaps we could "support" that by dropping these formatting characters from 0.7 broadcasts instead.

We could also roll our own and then add a translation layer to stay compatible with teeworlds. So ddnet to ddnet uses whatever it wants. And ddnet to vanilla does some translation. But not sure if that is worth the complexity.

I agree the format is weird but it is simple to type. You have to keep in mind that this is user facing not a developer only format. So admins have to compute colors in their head when doing broadcasts.

I would have appreciated such simple format back in the days as a 12yo kid trying to add colored text to my minecraft signs. https://minecraftitemids.com/color-codes

2024-04-30 16:14 UTC, Robyt3 commented
> > though I would prefer if the textrender was changed to support STextColorSplit also with text containers instead of creating a separate text container for every colored segment.
> 
> @Robyt3 do you want to do this? Because I do not. If this is blocking we can close the pr because I don't feel like doing that right now.

It's not a blocker for this PR. I didn't notice any adverse impact on FPS when rendering several text containers instead of one, so this seems fine for now. If we add colored text containers anywhere else in the future, we should probably refactor it though.

2024-05-01 00:53 UTC, ChillerDragon commented
Thanks to https://github.com/ddnet/ddnet/pull/8284 being merged. Colored multi line broadcast are also bug free now.

``broadcast ^090foo bar\n^999multiple lines ^505o.O\n\n^900<3``

![screenshot_2024-05-01_08-49-40](https://github.com/ddnet/ddnet/assets/20344300/cd8b8e03-c255-4e4d-b6d5-91a3d83fc861)

Still in state draft because @heinrich5991 does not like the color codes.
And I am waiting for https://github.com/ddnet/ddnet/pull/8286 to be merged so I can use it.

2024-05-01 09:12 UTC, ChillerDragon commented
So what do we do about the color codes @heinrich5991 ?

2024-05-01 09:24 UTC, Robyt3 commented
To consider: the console command input is 512 characters long, so the longest broadcast that can be sent with the current color codes from the rcon without using config files would contain 100 colored segments of 1 byte letters.

```
broadcast ^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A^111A
```

2024-05-01 09:37 UTC, Robyt3 commented on src/game/client/components/broadcast.cpp
> +			m_aSegments[NumSegments].m_Color = ColorRGBA((c[1] - '0') / 9.0f, (c[2] - '0') / 9.0f, (c[3] - '0') / 9.0f, 1.0f);
Possible optimizations:
- You can detect here if the previous segment has the same color as the new one and then reuse the previous segment instead of creating a new one with identical color.
- If the previous segment has length 0, you can overwrite it, since it has no effect. This currently seems to apply to the default segment, which may have length 0 if the broadcast begins with a color code.

2024-05-01 10:35 UTC, ChillerDragon commented on src/game/client/components/broadcast.cpp
> +			m_aSegments[NumSegments].m_Color = ColorRGBA((c[1] - '0') / 9.0f, (c[2] - '0') / 9.0f, (c[3] - '0') / 9.0f, 1.0f);
Seems like more complicated code to me. That has barely any runtime benefit. And is only applied when a administrator creates bogus broadcasts.

2024-05-01 11:25 UTC, Robyt3 commented on src/game/client/components/broadcast.cpp
> +			m_aSegments[NumSegments].m_Color = ColorRGBA((c[1] - '0') / 9.0f, (c[2] - '0') / 9.0f, (c[3] - '0') / 9.0f, 1.0f);
Yeah, I didn't mean it's necessary for this PR, but something to consider if this feature would be made more generic.

2024-05-01 11:45 UTC, heinrich5991 commented
Let's take a step back. Where are colored broadcasts actually used?

2024-05-02 00:08 UTC, ChillerDragon commented
> Let's take a step back, to understand whether the whole feature is desirable. Where are colored broadcasts actually used?

It extends the broadcast feature. So it can be used where the broadcast is used.

Broadcasts are used by:
- Server side mods. [F-DDrace](https://github.com/fokkonaut/F-DDrace) for example uses it on farm tiles. It is nice to highlight names, chat commands, numbers and warnings.
- Admins using rcon, econ or fifo. During events ^900 can be used for warnings and ^090 to highlight player names.
- Software using rcon, econ, or fifo. [TeeworldsEconMod](https://github.com/chillavanilla/TeeworldsEconMod) does not use it but would be a good candidate to highlight names and numbers in spree messages. Or use the colors to differentiate manual admin broadcasts and broadcasts coming from an automated tool.
- Admins using binds or scripts. Admins have their favorite reusable broadcast as bind (I used to use a countdown bind for some time for example). Those binds can now be spiced up with colors. Or the famous [rotating_cube.py](https://github.com/ddnet/ddnet-scripts/blob/8e0909edbeb5d7a6446349dc66a3beb0f5ddccc7/servers/scripts/rotating_cube.py) could now also pulse in rainbow colors.


One thing to note is that this format has no support for escaping. So there is no way to send raw text like ``123^123``. I don't think it is a problem but wanted to mention it anyways.

2024-07-21 02:15 UTC, l-ouis commented
> Let's take a step back, to understand whether the whole feature is desirable. Where are colored broadcasts actually used?

This is desirable for mod creators, and more colors = more ways to easily express what you want to a player.

2024-07-21 10:57 UTC, heinrich5991 commented
> * It is nice to highlight names, chat commands, numbers and warnings.

I guess it's nice.

> * [TeeworldsEconMod](https://github.com/chillavanilla/TeeworldsEconMod) does not use it but would be a good candidate to highlight names and numbers in spree messages. Or use the colors to differentiate manual admin broadcasts and broadcasts coming from an automated tool.

Sounds good.

> * Those binds can now be spiced up with colors. Or the famous [rotating_cube.py](https://github.com/ddnet/ddnet-scripts/blob/8e0909edbeb5d7a6446349dc66a3beb0f5ddccc7/servers/scripts/rotating_cube.py) could now also pulse in rainbow colors.

Meh.

> This is desirable for mod creators, and more colors = more ways to easily express what you want to a player.

Can you give an example?

---

Given that we haven't found a good alternative option, I'd vote for using a very tiny subset of HTML tags then. It's a well-understood format.

E.g. `<span style="color:#c00000">red text</span>`.

Do we have config options for broadcast colors in the client? If so, they should probably be removed before introducing this feature, because otherwise the features would likely interact in a bad way, giving no reliable way for mods to configure the colors of their broadcasts.

2024-07-21 11:02 UTC, jxsl13 commented
colorizing individual letters would take so many characters.

2024-07-21 11:08 UTC, heinrich5991 commented
> colorizing individual letters would take so many characters.

What's your use case for colorizing individual characters?

2024-07-21 11:10 UTC, jxsl13 commented
Same as colorizing all letters, to look good, rainbows are cool.

2024-07-21 13:45 UTC, ChillerDragon commented
@fokkonaut ran out of space with the shorter 0.7 format in F-DDRace already if I am not mistaken. And I doubt it was something intense as coloring every letter.


@heinrich5991 i like the 0.7 format better than html. It's simpler to type. It's simpler to parse. It is already established. And shorter. But in the end I don't care too much. The 0.7 bridge can just translate 0.7 to the ddnet format and if I want to do something with colored broadcasts I can always do it through a 0.7 connection. So I guess next time I find time to work on this I will be implementing an html parser xd. Can we get something shorter than "span" at least? Maybe "p"? I mean "span" is more correct for a colored text section in html but meh.

Question is what would that introduction of html mean? That all unknown html tags should not be displayed? What about span tags without color attributes? What about missing quotes? Is anything printed as raw text unless it's a fully valid color format? If not how does one print html text in broadcasts?

In any case I can see this making the code way more complex than it is right now. And the benefit is non obvious to me. Using 3 numbers for RGB seems like a solid format to me.

2024-07-21 13:51 UTC, ChillerDragon commented
@heinrich5991 so your main argument is that html is "well understood"? What does that mean? That there is a standard for it already? But what good is that if we don't follow it? Do we support spaces after the :? If yes how many? Do we support case insensitive hex codes? Do we support rgba()? Do we support words for colors like red, green and so on? I would argue that working on a system that is close to something you understand well but not the same is worse than learning a maximally simple system from scratch. For example the cursed html that is possible in email is really hard to work with if you are used to proper web html.

If by "well understood" you mean it can be understand easily and well. I would say that applies to the 0.7 format as well.

2024-07-21 16:33 UTC, CherryEx commented
I don't believe using html tags would be a good option. Because:
1. I'm quite sure not everyone knows html or its tags so this is not as well-understood as it should be.
2. Too many characters. Only 2 colors in your message (with the simplest tag format) would look like this:
<text color="FF2222">Hello </text><text color="00FF00">World</text>
Now compare it to: ^933Hello ^090World

Even if Teeworlds format isn't well enough, we could have something simpler than tags (e.g. <COLOR>Text or {COLOR}Text).
And I personally am okay with Teeworlds format though I believe it should be possible to use ^ inside the broadcast message and not just for colors.

2024-07-21 17:20 UTC, heinrich5991 commented
> If by "well understood" you mean it can be understand easily and well. I would say that applies to the 0.7 format as well.

By well-understood I mean that there's plenty of software that can deal with the format. The 0.7 format is made up and used by basically no one.

2024-07-21 17:34 UTC, jxsl13 commented
Imo that's overkill, especially the implications that has, either introduce a new dependency to the code or add a lot of parsing code instead (which needs to be maintained).
Also, those libraries normally do not focus on this specific use case, they focus on html as a whole, I'd guess(big guess), so you'd have to fiddle around limiting those libraries.

If the whole UI is going to be customizable via html, that's a different story but introducing (some) html just to colorize a few characters, overkill imo.

2024-07-22 00:14 UTC, ChillerDragon commented
> By well-understood I mean that there's plenty of software that can deal with the format. The 0.7 format is made up and used by basically no one.

Ok then you have to further elaborate your argument here. Because I don't see the advantage yet. What good is software that can deal with html for our use case here? Are people supposed to use external software to read and write broadcasts? Or are you just saying it will be easier for the users to learn because so many players are already web developers, [for them it will be annoying because it is not ACTUAL html](https://github.com/ddnet/ddnet/pull/8283#issuecomment-2241618912), while for the non web developer players the html will be harder to learn than `^rgb`.

2024-07-22 00:18 UTC, l-ouis commented
> By well-understood I mean that there's plenty of software that can deal with the format. The 0.7 format is made up and used by basically no one.

i think a simple version of Hex codes are a better choice. Its used in the map editor, so it's a standard in the client, and it can be shorter than a whole html tag: why not smth like <#123456> ?

2024-07-22 00:25 UTC, ChillerDragon commented
> i think a simple version of Hex codes are a better choice. Its used in the map editor, so it's a standard in the client, and it can be shorter than a whole html tag: why not smth like <#123456> ?

Yea that looks much better than html. Imo still not worth it to break compat with the totally fine teeworlds format. But fine by me. Anyone having problems with this format?

2024-07-22 00:30 UTC, CherryEx commented
> i think a simple version of Hex codes are a better choice. Its used in the map editor, so it's a standard in the client, and it can be shorter than a whole html tag: why not smth like <#123456> ? 

I agree with both teeworlds and this format. Teeworlds fornat is easier to write however, hex offers more colors.

2024-07-22 13:12 UTC, Learath2 commented
Definitely not merging a html parser for broadcasts :sweat: 
But what on earth was teeworlds thinking using `^RGB`, who uses that? I had to actually check the code to figure out what it was. It creates a subset of messages that can no longer be sent (no means to escape the `^`). 

If there aren't any issues with our text handling I'd use `\033[38;2;r;g;bm` or `\033_rgb\\`. If it has to be compatible with 0.7's unfortunate decision then this PR looks fine-ish

2024-07-22 13:16 UTC, heinrich5991 commented
> If it has to be compatible with 0.7's unfortunate decision

It doesn't.

2024-07-22 13:25 UTC, jxsl13 commented
`^ffeeddaa` ? (aa for alpha)

Why does the current 0.7 format have fewer color variations?

2024-07-22 13:41 UTC, ChillerDragon commented
> If there aren't any issues with our text handling I'd use \033[38;2;r;g;bm or \033_rgb\\. If it has to be compatible with 0.7's unfortunate decision then this PR looks fine-ish

@Learath2  I am a big shell enjoyer but these color codes are pretty complicated. And harder to remember than ^rgb. This should be hand written by casual ddnet players wanting to have some fun colors in their broadcasts. This is not only meant for kernel hacking neckbeards writing scripts that print broadcasts.

And my same [argument I made about html](https://github.com/ddnet/ddnet/pull/8283#issuecomment-2241618912) applies here too. If its just close to the ansi color codes but not fully compatible thats just annoying for people that expect it to work like ansi colors. And if it implements the full ansi color standard we should also be able to parse `\033[38;2;255;82;197;48;2;155;106;0mHello` and support bold, blink, and backgrounds. Even a subset of ansi colors is more complicated to parse than ^rgb. And if escaping is a problem we can extend the ^rgb syntax to support escaping. With `\^rgb`.

2024-07-22 13:52 UTC, Learath2 commented
Well, technically, we are allowed to support any subset of those control sequences as we are not implementing a terminal emulator. I'd discard any extra command part of a multicommand we don't know, so only 38 for now. 

I also proposed another with an application specific sequence. If you think the original one would suggest too heavily that we support everything.

However, I do agree with you that it is harder/impossible to type by hand. Is that really a big use case for this? I'd imagine mostly mods sending this.

Idk I'm just not a huge fan of a non-standard non-intuitive in-band protocol, but if we have to do it, I'd rather it be 100% compatible with teeworlds, so no escape for us either. The only benefit I see is compatibility (I can count the amount of 0.7 servers that accept 0.6 clients on one hand), if we break that, there is no point in using the ^RGB.

2024-07-22 14:25 UTC, ChillerDragon commented
Yes typing by hand for sure is a use case. This is a user facing feature and the users are not developers but regular players.

And I think ^RGB is the best format compatibility or not. I also think compatibility is nice. And sacrificing escapes for full compatibility sounds fine. But also breaking compatibility by adding an escape feature sounds fine to me.

2024-07-22 14:29 UTC, ChillerDragon commented
I fail to see how any of the proposed formats is more "intuitive" than ^RGB. It's so straightforward. I only see formats such as `(red)text(green)more text` being more intuitive. All formats proposed in this thread so far are RGB based. They just use way more syntax to represent it.

2024-07-22 14:30 UTC, heinrich5991 commented
> And I think ^RGB is the best format compatibility or not.

Hard disagree. I doubt we would have found the `^RGB` format if we started from a blank slate and just tried to design a format.

2024-07-22 15:51 UTC, jxsl13 commented
do a survey.

2024-07-22 15:56 UTC, fokkonaut commented
> do a survey.

You mean a survey that'll be ignored by the maintainers?
Like I did for the freeze bar instead of stars?
So many people wanted the stars back, even after "just give them a month to get used to it".
No, it's not only about that. And sadly, even after I got many people on my side, @Learath2 felt pressured to do something, so he announced there would be a similar thing to stars, which up to this date hasn't reached any daylight yet.
It's sad that maintainers who don't even use much of the things they create try to force their own preferences or "this is better code style" onto everyone. No config var policy, no this, no that. It slowly but surely moves away contributors and players.
Think about it for a second

2024-07-22 16:20 UTC, fokkonaut commented
Since heinrich censor edited my comment, here the original one:

You mean a survey that'll be ignored by the maintainers?
Like I did for the freeze bar instead of stars?
So many people wanted the stars back, even after "just give them a month to get used to it".
No, it's not only about that. And sadly, even after I got many people on my side, @Learath2 felt pressured to do something, so he announced there would be a similar thing to stars, which up to this date hasn't reached any daylight yet.
It's sad that maintainers who don't even use much of the things they create try to force their own preferences or "this is better code style" onto everyone. No config var policy, no this, no that. It slowly but surely moves away contributors and players.
Think about it for a second


Heinrich messages me on Discord that I should not insult people hence he edited my comment.
The part he meant is "It's sad that maintainers who don't even use much of the things they create".
He felt personally attacked by it, stating exactly that. Also completely misunderstood my point and even after trying to explain it, he insisted that his interpretation of my words was correct.
He continues with random arguments like "I personally like the freezebar", again, missing my whole point since it's about the stars in that context, which got removed and are desired by many players.
So to sum it up. I DID NOT INSULT ANYONE with that statement, only expressing my sadness over the fact that maintainers who don't use much of the things they create (in this direction, e.g. colored broadcast, which we're talking about in this PR), will force their way of doing things onto the people who would use it more than themselves.
And @heinrich5991, just for you and to clarity things: I did not meant to attack you or anyone personally. According to your interpretation I was insulting everyone who "doesn't play the game enough".
Please stop this overly consoring of literally "free speech", which has always been a problem.
Btw, I personally get really mad over the fact that you're deleting things or editing messages BEFORE asking about any context. You're punishing who you want instead of trying to "fix" a situation.

2024-07-22 16:33 UTC, Learath2 commented
> do a survey.

Survey whom? The playerbase doesn't even know what a broadcast is nowadays given how little we use them. Nor do they care how color escape codes work, the only thing they could possibly care about is whether colored text is cool or not.

The only people interested in the implementation details are probably already in here

2024-07-22 16:54 UTC, jxsl13 commented
developers (often also hosters) and server hosters.

2024-07-22 17:01 UTC, l-ouis commented
so no hex code? I feel like that's the most common form of color coding

again, it's also used in map editor so maybe a mod creator can sync up map colors and broadcast colors easily (not sure how you would do that with ^RGB, maybe you need some calculators)

it also seems better if we ignore escaping, <#______> seems rarer than ^___.

Abt 0.7- How much of a dealbreaker even is it to ignore compatibility? Won't it just break a few broadcasts? if servers really care they can send separate broadcasts depending on the client. Not sure how many cross-version players there are either.

2024-07-22 17:34 UTC, jxsl13 commented
if nicknames are to be broadcast(ed), for example through mods, escaping support would be preferred.

2024-07-22 23:39 UTC, ChillerDragon commented
> Abt 0.7- How much of a dealbreaker even is it to ignore compatibility? Won't it just break a few broadcasts? if servers really care they can send separate broadcasts depending on the client. Not sure how many cross-version players there are either.

Broadcasts don't have to break if we ignore compatibility but it adds more complexity in the translation layer. For me the biggest pain point here would be that something user facing is different in ddnet than in teeworlds. Stuff like that is always annoying if you switch clients. For example there are some config variables and commands that do the same thing in ddnet and teeworlds but they are named differently. For example `cl_show_user_id` != `cl_show_ids` (thats annoying if you try to onboard a new moderator on a bridge server you have to know which client they use and how the command is called there). `say_self` vs `echo` requires users to maintain two versions of their configs just because the print command is called differently. And so on...

In my opinion whoever implemented a feature first ddnet or teeworlds is setting some kind of standard. Whoever is implementing a feature later should check if the other party already has it and then ideally implement the same API. Unless of course there is some advantage of breaking the API. Sadly I disagree with the maintainers of ddnet that the teeworlds color codes were designed poorly.

2024-07-23 00:46 UTC, CherryEx commented
And btw the Teeworlds color format is the shortest one between other ones mentioned in this pr. That said, according to Robyt3, you can have up to 100 differently-colored characters because of the input limits. Now if we use some "standard" format with hex color codes, this number is gonna greatly decrease.

2024-07-27 10:59 UTC, ChillerDragon commented
Well the upstream also supports escaping now so one more argument for going with plain upstream format since there were concerns about no escape options.

https://github.com/teeworlds/teeworlds/pull/3255

The proposed html format supports no escaping.

2024-07-30 09:03 UTC, Learath2 commented
> In my opinion whoever implemented a feature first ddnet or teeworlds is setting some kind of standard. Whoever is implementing a feature later should check if the other party already has it and then ideally implement the same API.

Usually I'd agree with this line of argumentation, but the other party you mention is a dead fork. I see zero benefit to carrying any compatibility with it around anymore. There is 0 reason for them not to have used standard hex codes following the `^`, hex colorcodes even have a shortform and they would allow 16^3 distinct colors in short as opposed to just 10^3.

Either way, I'm okay with merging this as is. I don't like the idea of carrying around an XML parser, even for just a subset. I'd rather have something that starts with a `\033` but you are opposed to it being hard to type. So this compromise format is acceptable-ish.

We can later on add a truecolor version of this supporting full hex-codes. I am *sure* you'll force that standard we set on teeworlds.

2024-07-30 09:36 UTC, ChillerDragon commented
out of draft because it got lerato approval

2024-07-30 09:42 UTC, heinrich5991 commented
> Either way, I'm okay with merging this as is.

We had a small discussion on Discord, I think this is not fine to merge as-is. The format needs to have advantages independent of "this is the 0.7 format". I'd like to see some standard format.

Even with a standard format, it should probably still be opt-in by the server so we don't need to update old servers to start escaping user strings in broadcasts. E.g. a default-false boolean in the broadcast message that tells us whether the text is supposed to be interpreted or displayed as-is.

2024-07-30 11:04 UTC, jxsl13 commented
I think you seem to use "I want a standard format" as an argument which it is not. 
You do not state any advantages of any of those potential standards that would apply to this specific use case.

As already stated in this whole discussion, introducing html/xml for a user facing api is pretty much bad, long, cryptic, introduces maintenance overhead or a giant dependency.

I think a standard like replacing 0-9 with full fledged rgb(a) hex colors would make it easier to copy and paste colors from online color pickers. So that would be an advantage.
But more than that, one could discuss which other prefix character to use instead of ^.

There is no easier api for an end user than <character><RRGGBB>.
No "standard" will be easier to use than such a format.

2024-07-30 22:57 UTC, fokkonaut commented
> > There is no easier api for an end user than `<character><RRGGBB>`. No "standard" will be easier to use than such a format.
> 
> Easier is unlikely. As easy is simple, I'd say `<c=#rrggbb><c/>` is almost as simple.

What if a user quickly want's to announce a broadcast, featuring some letters, numbers or words in specific colors?
They can easily make up a specific color by roughly mixing in the weights of rgb using `^rgb`.
1. They don't need to check which color format is being used, html, hex, whatever. They can rely on a thing made for the exact purpose.
2. Featuring colors that can be done using `^rgb` are more than enough for a broadcast message.

Of course, if they don't know about `^rgb` they would still have to look it up or ask someone, but it's easy to explain for anyone and can be used even by non-developers or even developers who don't know every color format.

2024-07-31 00:39 UTC, l-ouis commented
well we could also support <c="purple"> type tags which would be even easier for cooking up quick broadcasts

2024-07-31 03:12 UTC, ChillerDragon commented
> well we could also support <c="purple"> type tags which would be even easier for cooking up quick broadcasts

Yea I like named colors too. But I am proposing to just extend the current syntax with `^red` since it can be escaped now too it should be fine.

2024-07-31 11:15 UTC, Learath2 commented
> > > There is no easier api for an end user than `<character><RRGGBB>`. No "standard" will be easier to use than such a format.
> > 
> > 
> > Easier is unlikely. As easy is simple, I'd say `<c=#rrggbb><c/>` is almost as simple.
> 
> What if a user quickly want's to announce a broadcast, featuring some letters, numbers or words in specific colors? They can easily make up a specific color by roughly mixing in the weights of rgb using `^rgb`.
> 
>     1. They don't need to check which color format is being used, html, hex, whatever. They can rely on a thing made for the exact purpose.
> 
>     2. Featuring colors that can be done using `^rgb` are more than enough for a broadcast message.
> 
> 
> Of course, if they don't know about `^rgb` they would still have to look it up or ask someone, but it's easy to explain for anyone and can be used even by non-developers or even developers who don't know every color format.

Not like hex colors work any different, you mix colors the exact same way, and I'd argue if they can find out `^` they can find out the tag version too. The only difference is that there is a closing too. Which I'd argue is even more intuitive than the switch color at the control sequence behaviour. (It's not immediately obvious how one would reset the color).

2024-07-31 11:43 UTC, jxsl13 commented
Tags are longer and need more space.

2024-07-31 22:57 UTC, CherryEx commented
> It's not immediately obvious how one would reset the color.

We can have something like ^DEF to go back to default color. It's an easy to understand format and writing it manually isn't hard at all. hex colors with tags use a lot of space and are harder to write manually.
The 0.7 format is extremely easy to write and the color range is enough for broadcasts. and it uses less space which means more color segments.
I still don't understand the benefit here. WHY do we need a "standard" format?

2024-08-01 07:11 UTC, Learath2 commented
> > It's not immediately obvious how one would reset the color.
> 
> We can have something like ^DEF to go back to default color. It's an easy to understand format and writing it manually isn't hard at all. hex colors with tags use a lot of space and are harder to write manually. The 0.7 format is extremely easy to write and the color range is enough for broadcasts. and it uses less space which means more color segments. I still don't understand the benefit here. WHY do we need a "standard" format?

I don't think "standard" is a good argument, you'll have to refer to @heinrich5991 on that (my own proposal isn't exactly standard either). But I do think an XML derivative purpose built for rich text would be much better than this for several reasons:
- Obvious how to reset the color
- Can be used for future other text options (bold, italic, small, big, strikethrough, understrike)
- Can be used in the planned(-ish) server pushed UI (or any other UI extension that has been talked about like directly within maps)
- Can be composed easily `<b><c="red">Red Bold Text</c></b>`
- Allows for more colors, 16^8 colors in long form, 16^3 in short form, compared to just 10^3 of the original format.

2024-08-01 18:31 UTC, l-ouis commented
> The 0.7 format is extremely easy to write and the color range is enough for broadcasts. and it uses less space which means more color segments.

Hard disagree on the "color range", The difference especially for greyscale colors and colors low in brightness will be pretty apparent vs hex.

Also, I can see a lot of mod creators wanting to use broadcast along with some map element and they might prefer hex for broadcasts so they can match any possible editor color.

2024-08-01 22:19 UTC, CherryEx commented
> 
> Hard disagree on the "color range", The difference especially for greyscale colors and colors low in brightness will be pretty apparent vs hex. It also means rainbow effects or gradient effects are a lot lamer.
> 
> Also, I can see a lot of mod creators wanting to use broadcast along with some map element and they might prefer hex for broadcasts so they can match any possible editor color.

I agree that a wider color range is better; and we can translate it for 0.7 as well. But the syntax should be minimal to support as many colored segments as possible.

2024-08-02 10:25 UTC, heinrich5991 commented
The format proposed by @Learath2 looks sensible (as far as I understood it):

`<c=#rrggbb>text</c>` or `<c=#rgb>text</c>` It uses the same way as HTML to describe colors, which is a plus. The format itself isn't standard, that's a minus to me. It's obvious how to extend it for other formatting, another plus.

With two maintainers agreeing on a format, @ChillerDragon do you want to implement it, or should I move this to a feature request issue?

2024-08-02 13:33 UTC, heinrich5991 commented
> I don't think "standard" is a good argument, you'll have to refer to @heinrich5991 on that (my own proposal isn't exactly standard either).

I think using a subset of a standard format is a good thing because people can then lazily implement it by just pulling in a large dependency. It generally makes it easier for reimplementations because such formats might already be implemented somewhere.

2024-08-03 02:17 UTC, ChillerDragon commented
Are admins supposed to type that by hand to make colored broadcasts?!

How can it be extended?
How can it be escaped?
How is this helpfully close to a standard? I don't see any existing tool or library supporting it.

Once those questions are answered I might give the implementation a go.

2024-08-04 11:40 UTC, Learath2 commented
> Are admins supposed to type that by hand to make colored broadcasts?!

Yes

> How can it be extended?

`<b>` for bold
`<i>` for italic

> How can it be escaped?

`&lt;` `&gt;` `&amp;`

> How is this helpfully close to a standard? I don't see any existing tool or library supporting it.

I don't think it is. We strayed away from xml in order to make it easier to type. Shouldn't be an issue for you as you don't seem to mind non-standard formats.

2024-08-04 12:23 UTC, ChillerDragon commented
How do you escape ``&gt;``?

2024-08-04 12:25 UTC, Learath2 commented
> How do you escape ``&gt;``?

`&amp;gt;`

2024-08-04 12:33 UTC, ChillerDragon commented
If the typing by hand is that much more annoying. And we don't get a benefit of a it being a standard format. And the code will be half a html parser with escape sequence support and tag parsing. Is it really worth it? Is it worth to break compatibility with the existing format that is simple and already included in teeworlds?

If the amount of colors is such a concern I propose `^rrggbb` hex as format. But the xml stuff is just weird.

Should all unknown tags be ignored? Only the tags or also their content? Do we need forward compatibility to skip attributes? What should this display? `<a>hahw</a>’ or `<c foo=bar>aaaa</a>` or `<c=red>sss</c>` or `<c=112233>missing hashtag</c>` what about missing closing tags? Do we support nesting?

2024-08-04 12:47 UTC, Learath2 commented
> If the typing by hand is that much more annoying. And we don't get a benefit of a it being a standard format. And the code will be half a html parser with escape sequence support and tag parsing. Is it really worth it?

IMO yes, but that's subjective obviously.

> Is it worth to break compatibility with the existing format that is simple and already included in teeworlds?

Yes, if we think the format is better and will be more useful in the future, it is definitely worth breaking compatibility with a format used by a tiny minority of servers on a version of the game with a tiny subsection of players.

Only concern I had was that the original is indeed very simple. (So simple that it's guaranteed to never be used for anything else within DDNet code and be that one weird format we added to broadcasts that we have to support forever now)

> If the amount of colors is such a concern I propose `^rrggbb` hex as format. But the xml stuff is just weird.

That's better but it can't be reused for anything else nor extended. 

> Should all unknown tags be ignored? 

Yes

> Only the tags or also their content? 

Only the tags IMO.

> Do we need forward compatibility to skip attributes?

I think we don't want attributes to keep it as simple as possible, but we can talk about it.

> What should this display? `<a>hahw</a>` or `<c foo=bar>aaaa</a>` or `<c=red>sss</c>` or `<c=112233>missing hashtag</c>` 

`hahw` unknown tag a, `<c foo=bar>aaaa</a>` parse failure mismatched closing tag, named colors we can support too, missing hashtag is also a parse failure.

> What about missing closing tags? 

Parse failure.

All parse failures can be displayed as plaintext.

> Do we support nesting?

Yes, otherwise imo not worth bothering with this at all.

2024-08-04 13:21 UTC, Learath2 commented
> So we take all those disadvantages of the xml format just to be extendable? 

Elaborate on "all those". The only one I see is that it's a little more annoying to parse and a little more annoying to type.

> And yet its strictly limited and all parse errors result in plain text? So it can only ever be extended by custom tags not by attributes?

I just didn't see much of a use to attributes, we can allow it if you feel you have a use for it.

> So missing hashtag is a parse failure right? `<c=112233>missing hashtag</c>` so this would display as is. And that is because a `c` tag always expects one hex value? What about unknown tags what characters can they include?

Or we can say no hashtag is a teeworlds packed decimal color.
I would display it as plaintext so the admin immediately knows they made a mistake, the reason browsers are millions of lines now is that they are extremely lax in what they accepted and now they can't break websites.

> `<b>bold</b>` -> `bold` (I assume)

Yes

>  `<foo bar>space</foo bar>` parse error? or `space` ? 

If we want to leave a consideration for attributes in the future, `space`. Else parse error.

> `<size=66>big</size>` parse error? or `big`? 

`big` as it's an unknown tag.

> `<a<>fish</a>` parse error I assume `<&amp;>big</&amp;>` parse error I assume

I'd say parse error on both, just `[a-zA-Z0-9-_]` should be allowed within tags IMHO.

2024-08-04 14:28 UTC, ChillerDragon commented
> Elaborate on "all those". The only one I see is that it's a little more annoying to parse and a little more annoying to type.

Yes the implementation is more complicated and the user facing part is also more complicated. And for both I would not use the word little. And imo the third disadvantage is that its a different way to the already established 0.7 way of doing stuff.

> I'd say parse error on both, just [a-zA-Z0-9-_] should be allowed within tags IMHO.

The `c` already contains a `=` and a `#`. Another tag might want to use a `,` or a `(`.

2024-08-04 14:31 UTC, ChillerDragon commented
Closing this pull request because I don't like the maintainers proposals and don't feel like implementing a html parser.

2024-08-04 14:31 UTC, closed without merging

2024-08-04 16:09 UTC, heinrich5991 commented
> > Should all unknown tags be ignored?
> 
> Yes

I thought we could simply return a parse error on unknown tags. The server knows which tags the client supports by its version number. Makes the parser a lot simpler.

2024-08-04 16:32 UTC, fokkonaut commented
> > > Should all unknown tags be ignored?
> > 
> > 
> > Yes
> 
> I thought we could simply return a parse error on unknown tags. The server knows which tags the client supports by its version number. Makes the parser a lot simpler.

I thought we wanted to move away from version number compatibility code.

2024-08-04 18:12 UTC, Learath2 commented
I don't like this very much either. Less serverside branching code, not more ;(

2024-08-05 07:32 UTC, fokkonaut commented
> I don't like this very much either. Less serverside branching code, not more ;(

Well, it's not really more? It's simply replacing Version >= VERSION_DDNET_X by ClientCaps&X.

One net message required and one function to initialize the default's based on version numbers.