Add str_isnum
ddnet/ddnet pull request #8286
Opened 2024-04-30 09:15 UTC by ChillerDragon

2024-04-30 09:15 UTC, ChillerDragon commented
https://github.com/ddnet/ddnet/pull/8283/files#r1583449953
Needed for #8283

2024-04-30 16:29 UTC, Robyt3 requested changes
Looks good, only a small comment regarding the tests.

2024-04-30 16:29 UTC, Robyt3 commented on src/test/str.cpp
> +	EXPECT_EQ(str_isnum('/'), 0);
I think `EXPECT_TRUE` and `EXPECT_FALSE` are preferred for `bool` (or you should use `true`/`false` instead of `1`/`0`), but I didn't find any particular guidelines on this.

2024-05-01 00:40 UTC, ChillerDragon commented on src/test/str.cpp
> +	EXPECT_EQ(str_isnum('/'), 0);
Ye opsi. I went with int first because it is system.cpp and then I remembered https://github.com/ddnet/ddnet/issues/6436

2024-05-01 08:49 UTC, Robyt3 approved these changes

2024-05-01 09:07 UTC, merged