Add contribution guidelines (closed #8142)
ddnet/ddnet pull request #8288
Opened 2024-05-01 03:13 UTC by ChillerDragon

2024-05-01 03:17 UTC, ChillerDragon commented
I just skribbled down some of the things which I would consider the unwritten rules of the ddnet code base.

It is pretty trol that I am doing this since I am not a maintainer. So contributions are welcome. Feel free to decline my pr and reword it entirely.

This is a direct response to https://github.com/ddnet/ddnet/issues/8142#issuecomment-2082909091. Trying to make the contribution process a bit smoother. Ensuring that all contributors and maintainers have a common truth of what is wanted and what is unwanted. Hopefully if a contributor reads and follows this document and follows it the review process should be smooth and not have any style nitpicks anymore.

Here a fitting [quote](https://github.com/ddnet/ddnet/pull/8154#issuecomment-2017677406) of the OG ddnet admin deen aka def-
> Styling changes should never be a point of discussion. Just make an automated check if you care for it enough, and then it will be red in CI. If reviewers look for wrong variable names, they should rather spend that time looking for interesting issues.

2024-05-01 16:10 UTC, heinrich5991 reviewed
I wonder what the correct place for this is. The wiki (https://wiki.ddnet.org/wiki/Development) already has some of it written down. Perhaps the rest could be moved there, along with a link in CONTRIBUTING.md?

2024-05-01 16:10 UTC, heinrich5991 commented on CONTRIBUTING.md
> +`_p`
```suggestion
`p`
```

2024-05-02 05:41 UTC, furo321 commented on CONTRIBUTING.md
> +It would be unfortune if you spend time working on a contribution that does not align with the ideals of the ddnet project.
```suggestion
It would be unfortunate if you spend time working on a contribution that does not align with the ideals of the ddnet project.
```

2024-05-02 10:16 UTC, ChillerDragon commented
> I wonder what the correct place for this is. The wiki (https://wiki.ddnet.org/wiki/Development) already has some of it written down. Perhaps the rest could be moved there, along with a link in CONTRIBUTING.md?

I prefer github over the wiki for contributing and discussing style guide changes. But no hard feelings anywhere is better than nowhere.

2024-05-04 01:33 UTC, ChillerDragon commented
@Robyt3 is minimum variable length an official requirement? Then we should add it as well. And imo also check it in the CI.

https://github.com/ddnet/ddnet/pull/5949#discussion_r1532397607
https://github.com/ddnet/ddnet/pull/5949#discussion_r1532403094
https://github.com/ddnet/ddnet/pull/5949#discussion_r1532404132

2024-05-04 06:59 UTC, heinrich5991 commented
The linked comments do not look like a "minimum variable name length", but rather a "descriptive variable name" requirement. I don't see how the latter could be checked in CI.

2024-05-04 07:09 UTC, ChillerDragon commented
> The linked comments do not look like a "minimum variable name length", but rather a "descriptive variable name" requirement. I don't see how the latter could be checked in CI.

One could argue that single letter is not descriptive. I have the feeling robsti thinks that way and some linters also have that as default requirement. But the key here is that I do not want to guess. I want to know while writing the code if I am allowed to use single letter variables in for loops or not. I do not wanna find out 2 weeks after the pr was published. And then have to edit my code again because of a review comment.

2024-05-04 07:35 UTC, heinrich5991 commented
> I want to know while writing the code if I am allowed to use single letter variables in for loops or not.

You are.

> But the key here is that I do not want to guess.

If you don't want to guess, you can always try to code on the safe side, and make things more explicit, use more descriptive variable names.

2024-05-04 07:41 UTC, ChillerDragon commented
> If you don't want to guess, you can always try to code on the safe side, and make things more explicit, use more descriptive variable names.

How do I know what the safe side is? Is one word always better than one letter?

```C++
for(int Part = 0; Part < protocol7::NUM_SKINPARTS; Part++)
{
	IntsToStr(pObj->m_aaSkinPartNames[Part], 6, aSkinPartNames[Part], std::size(aSkinPartNames[Part]));
	Msg.m_apSkinPartNames[Part] = aSkinPartNames[Part];
	Msg.m_aUseCustomColors[Part] = pObj->m_aUseCustomColors[Part];
	Msg.m_aSkinPartColors[Part] = pObj->m_aSkinPartColors[Part];
}
```

```C++
for(int p = 0; p < protocol7::NUM_SKINPARTS; p++)
{
	IntsToStr(pObj->m_aaSkinPartNames[p], 6, aSkinPartNames[p], std::size(aSkinPartNames[p]));
	Msg.m_apSkinPartNames[p] = aSkinPartNames[p];
	Msg.m_aUseCustomColors[p] = pObj->m_aUseCustomColors[p];
	Msg.m_aSkinPartColors[p] = pObj->m_aSkinPartColors[p];
}
```

If `Part` is safer than `p` then that should also be mentioned in the contribution guidelines.

2024-05-04 07:44 UTC, heinrich5991 commented
> Is one word always better than one letter?

No. But usually?

> If `Part` is safer than `p` then that should also be mentioned in the contribution guidelines.

I think this is getting too detailed.

2024-05-04 07:48 UTC, ChillerDragon commented
I am not getting any smarter here. You can not tell me what the safe way is which forces me to guess every time. Let's wait for rosbti who is the one actually requesting those reviews. He must have some concept.

2024-05-04 09:37 UTC, Robyt3 commented
Variable names should be descriptive and readable. I wouldn't say there's a fixed length that they need to have and I don't know if I can describe it as any general rule. I'll try to explain some examples of my thought process, but I don't think it makes sense to describe all of this in the style guidelines:

- `cs` -> `ColorScale`. It's more descriptive by spelling out the abbreviation. Abbreviations should be avoided or obvious. In this case it only was readable because there was a comment already spelling out the good variable name on the same line. Comments that simply give variables better names should be avoided in favor of giving the variable the name directly.
- `Ctx` -> `Context`, `Idx` -> `Index`, `GetFTile` -> `GetFrontTile`. I would avoid abbreviations that are not the prefix of the whole word or only one letter. Abbreviating `Position` as `Pos` is okay, but abbreviating it as `Psn` is confusing.
- `p` -> `Part`, `p` -> `Pass`. The longer name makes it more descriptive so now you can see easier that one of the loops was over skin parts and the other over passes.
- `i` -> `ClientId`, `i` -> `FrameImageIndex`. Same, the code becomes more readable, especially if multiple loops are involved and you don't need to keep track what variables `i`, `j` etc. do.
- `i` -> `Index`. Not really helpful, you are only making it longer but not more descriptive. I would only do this to avoid naming a function parameter `i`, but I'd also consider finding a better name altogether.
- Using overly long names (e.g. 10 words stringed together in CamelCase) usually makes code less readable, but there's no exact length limit. 10 words are probably too many, the longest we currently use in the code are 8 words for some function and variable names AFAICT with RegEx `\b(m_)?([A-Z][a-z0-9]+){8}\b`.
- Related to variable naming, consider avoiding [Primitive Obsession](https://refactoring.guru/smells/primitive-obsession). Bundle related variables in classes or use existing composite classes when possible. For example, consider replacing separate `float StartX` and `float StartY` with `vec2 Start` or `vec2 StartPos`. If you have several member variables that belong together, for example with a common prefix `m_MyFeature...`, consider adding these fields all to a separate class `CMyFeature` and remove the common prefix from the variable names.

2024-09-01 02:57 UTC, ChillerDragon commented
@heinrich5991 are if statements without curly braces allowed?

2024-09-02 04:23 UTC, ChillerDragon commented
Do we recommend a `Is` prefix for booleans?

```C++
bool IsFoo = true;
```

Do we ban the ``b`` prefix for booleans?

```C++
bool bFoo = true;
```

2024-10-05 04:47 UTC, ChillerDragon commented
> Do we recommend a `Is` prefix for booleans?
> 
> ```c++
> bool IsFoo = true;
> ```
> 
> Do we ban the `b` prefix for booleans?
> 
> ```c++
> bool bFoo = true;
> ```

Since nobody has an opinion on it. I decided it is highly illegal to use ``b`` prefix for booleans.

2024-10-05 04:55 UTC, ChillerDragon commented
This has matured long enough. Ready for review.

2024-10-05 11:07 UTC, def- requested changes

2024-10-05 11:07 UTC, def- commented on CONTRIBUTING.md
> +- Breaking backwards compatibility in gameplay.
```suggestion
- Breaking backwards compatibility in gameplay:
```

2024-10-05 11:07 UTC, def- commented on CONTRIBUTING.md
> +There are a few style rules. Some of them are enforced by the github actions CI and some of them are manually checked by reviewers.
```suggestion
There are a few style rules. Some of them are enforced by CI and some of them are manually checked by reviewers.
```

2024-10-05 11:07 UTC, def- commented on CONTRIBUTING.md
> +If your github pipeline shows some errors please have a look at the logs and try to fix them.
```suggestion
If your GitHub pipeline shows some errors please have a look at the logs and try to fix them.
```

2024-10-05 11:07 UTC, def- commented on CONTRIBUTING.md
> +A lot of the style offenses can be fixed automatically by running the fix script `./scripts/fix_style.py`
```suggestion
A lot of the style offenses can be fixed automatically by running the fix script `scripts/fix_style.py`
```

2024-10-05 11:07 UTC, def- commented on CONTRIBUTING.md
> +DDNet inherited the hungarian notation like prefixes from [teeworlds](https://www.teeworlds.com/?page=docs&wiki=nomenclature)
```suggestion
DDNet inherited the hungarian notation like prefixes from [Teeworlds](https://www.teeworlds.com/?page=docs&wiki=nomenclature)
```

2024-10-05 11:07 UTC, def- commented on CONTRIBUTING.md
> +Do not use the `goto` keyword.
```suggestion
### The usage of `goto` is not encouraged

Do not use the `goto` keyword in new code, there are better control flow constructs in C++.
```

2024-10-05 11:07 UTC, def- commented on CONTRIBUTING.md
> +Default arguments tend to break soon, if you have multiple you have to specify each even if you only want to change the last one.
```suggestion
Default arguments tend to break quickly, if you have multiple you have to specify each even if you only want to change the last one.
```

2024-10-05 11:07 UTC, def- commented on CONTRIBUTING.md
> +So you are encouraged to use all modern C++ features as long as their age is older than the newest supported C++ version of ddnet.
```suggestion
So you are encouraged to use all modern C++ features as long as they are supported by the C++ version we use.
Still be aware that in game loop code you should avoid allocations, so static buffers on the stack can be preferable.
```

2024-10-05 11:07 UTC, def- commented on CONTRIBUTING.md
> +There are no strict rules for commit messages. But it would be nicer to say "Add new feature xyz" instead of "added new feature xyz".
```suggestion
Describe the change your contribution is making for the player/user instead of talking about what you did in a technical sense. Your PR messages will ideally be in a format that can directly be used in the [change log](https://ddnet.org/downloads/).
```

2024-10-05 11:56 UTC, Pioooooo commented on CONTRIBUTING.md
> +So you are encouraged to use all modern C++ features as long as their age is older than the newest supported C++ version of ddnet.
Is the current C++ version be C++17? If so I think we should add this.

2024-10-06 21:36 UTC, def- approved these changes

2024-10-06 21:57 UTC, merged