Add support for clang tidy 19
ddnet/ddnet pull request #8318
Opened 2024-05-06 04:40 UTC by ChillerDragon

2024-05-06 09:17 UTC, Robyt3 commented on .clang-tidy
> +  -bugprone-unchecked-optional-access,
Does this happen frequently in our code? I don't think it should be excluded either or it should have a comment explaining that it's a temporary exclusion.

2024-05-06 09:20 UTC, Robyt3 commented on .clang-tidy
> +  -readability-redundant-casting,
What's the reason for excluding this check? Seems like a safe check to improve readability.

2024-05-06 09:30 UTC, ChillerDragon commented on .clang-tidy
> +  -bugprone-unchecked-optional-access,
I think thats only m_Score but it happend like a few times so I did not feel like spamming in a bunch of if statements. Seems like an unwanted change.

2024-05-06 09:36 UTC, ChillerDragon commented on .clang-tidy
> +  -readability-redundant-casting,
https://github.com/ddnet/ddnet/blob/d4e3f6fc01b594e18c30b85f256deac4760be45b/src/game/collision.cpp#L1158

I did not feel comfortable removing that one.

2024-05-06 09:37 UTC, ChillerDragon commented on .clang-tidy
> +  -readability-redundant-casting,
But yea that is probably okay to be removed. If you say its good ill drop the cast.

2024-05-06 09:41 UTC, ChillerDragon commented on .clang-tidy
> +  -readability-static-accessed-through-instance,
Not needed anymore since https://github.com/ddnet/ddnet/pull/8317 is merged. I will drop it.

2024-05-06 09:47 UTC, ChillerDragon commented
Okay more redundant casts came up. I will have to fix that at some point.

2024-05-06 10:14 UTC, Robyt3 commented on .clang-tidy
> +  -readability-redundant-casting,
Seems fine, `i` is already an `int` and `d` is a `float`.

2024-05-06 10:21 UTC, heinrich5991 commented on .clang-tidy
> +  -bugprone-unchecked-optional-access,
Can you give an example of that warning?

2024-05-06 10:46 UTC, ChillerDragon commented on .clang-tidy
> +  -bugprone-unchecked-optional-access,
```
/home/chiller/Desktop/git/ddnet/src/game/server/player.cpp:940:19: error: unchecked access to optional value [bugprone-unchecked-optional-access,-warnings-as-errors]
  940 |                         str_time_float(Result.m_Data.m_Info.m_Time.value(), TIME_HOURS_CENTISECS, aTime, sizeof(aTime));
      |                                        ^
```

```
/home/chiller/Desktop/git/ddnet/src/engine/server/server.cpp:2092:13: error: unchecked access to optional value [bugprone-unchecked-optional-access,-warnings-as-errors]
 2092 |                                 Score = m_aClients[i].m_Score.value();
      |                                         ^
```

2024-05-06 11:42 UTC, heinrich5991 commented on .clang-tidy
> +  -bugprone-unchecked-optional-access,
Yea, especially the latter one looks like a false positive. Sucks. Thanks for the examples.

2024-05-10 11:26 UTC, Robyt3 requested changes
Looks good, but some changes got mixed up in the commits.

The `if(sock->ipv4sock < 0)` and `if(sock->ipv6sock < 0)` checks should be added in a separate commit, I don't see how they are related to `modernize-use-emplace`.

The removal of explicit `std::make_pair` probably belongs in the commit that fixes `modernize-use-emplace`, instead of being included in 8025cc01f7b1b9828a0d054864844ab7610d27ba.

2024-06-02 08:52 UTC, Robyt3 approved these changes

2024-06-02 09:10 UTC, merged