Add chat commands for toggling weapons in practice mode
ddnet/ddnet pull request #8324
Opened 2024-05-06 20:10 UTC by ewancg

Some people wanted the ability to give themselves weapons within practice mode without having to teleport to the location of the weapon on the map. This allows them to do so by typing something like `/grenade` in the game chat (as long as they're in a team with practice mode enabled).

Note that with the way things are currently being done, there's no clean way for me to "wrap" the callbacks used in the rcon commands cleanly. Currently there has to be a duplicate function for every command that we want to wrap. If you have any ideas on how to reduce the amount of boilerplate please let me know.

Closes #8092

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-05-06 20:11 UTC, ewancg commented
There were a few more rcon commands for player state/movement related toggles that I did not wrap in this pull request. It would be very easy to do so if anyone thinks that's worthwhile (toggling endless, live freeze, and movement commands)

2024-05-06 20:20 UTC, archimede67 requested changes
Regarding the need to have a duplicate method for every practice command, I don't see an easy way to fix this. It seems fine to me as you have factored most of the common code out.

2024-05-06 20:20 UTC, archimede67 commented on src/game/server/ddracechat.cpp
> +std::optional<CCharacter *> CGameContext::GetPracticeCharacter(IConsole::IResult *pResult, void *pUserData)
I don't see the need to use `std::optional` here. You can simply return `CCharacter *`, and instead of returning `std::nullopt` you can return `nullptr`. This will then simplify the usages below.

2024-05-06 20:41 UTC, furo321 commented on src/game/server/gamecontext.h
> +	static std::optional<CCharacter *> GetPracticeCharacter(IConsole::IResult *pResult, void *pUserData);
This doesn't need to be static. To fix the call to non-static member function compiler error, you can call the function via `(CGameContext *)pUserData`

```cpp
CGameContext *pSelf = (CGameContext *)pUserData;
if(pSelf->GetPracticeCharacter(pResult, pUserData))
	ConWeapons(pResult, pUserData);
```

2024-05-06 20:41 UTC, furo321 commented on src/game/server/ddracechat.cpp
>  	if(g_Config.m_SvTeam == SV_TEAM_FORBIDDEN || g_Config.m_SvTeam == SV_TEAM_FORCED_SOLO)
This if should only run if the command is not allowed on solo servers. This check should only be applied to the `unsolo` command, not every command.

2024-05-06 21:06 UTC, ewancg commented on src/game/server/ddracechat.cpp
> +std::optional<CCharacter *> CGameContext::GetPracticeCharacter(IConsole::IResult *pResult, void *pUserData)
Fixed

2024-05-06 21:07 UTC, ewancg commented on src/game/server/gamecontext.h
> +	static std::optional<CCharacter *> GetPracticeCharacter(IConsole::IResult *pResult, void *pUserData);
Fixed. Though I'm not sure if the added fluff of having that CGameContext cast & definition outweighs the convenience of keeping it static.

2024-05-06 21:07 UTC, ewancg commented on src/game/server/ddracechat.cpp
>  	if(g_Config.m_SvTeam == SV_TEAM_FORBIDDEN || g_Config.m_SvTeam == SV_TEAM_FORCED_SOLO)
Fixed

2024-05-07 01:27 UTC, def- reviewed
We already have these commands for server rcon. Maybe we should only have them in one place? I'm not sure if there is a good way to unify them though.

2024-05-07 01:27 UTC, ewancg commented
Yes, that's exactly the issue

2024-05-07 04:45 UTC, def- approved these changes

2024-05-07 05:57 UTC, furo321 commented on src/game/server/ddracechat.cpp
> +
Unused include
```suggestion
```

2024-05-07 06:00 UTC, merged