Fix `goto_tele` not finding all teleporters
ddnet/ddnet pull request #8338
Opened 2024-05-09 04:19 UTC by ChillerDragon

I noticed that on the current master the `goto_tele` feature was skipping one tele.

https://github.com/ddnet/ddnet/assets/20344300/afface81-7199-4419-be2a-9e80d8ada79b

I did not want to debug the code because it looked so complex. So I refactored it and it also fixed the bug. As you can see it now finds one more tele in the same map:

https://github.com/ddnet/ddnet/assets/20344300/49dc9ed3-d1f6-43db-a80a-9ca71d86b6b2

Also the performance should be much better. Since now the worst case is only iterating as many times as there are teleporters of that type in the map. Before in the worst case it would iterate over every single tile in the tele layer (including empty tiles).

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-05-09 07:59 UTC, heinrich5991 commented
I find it hard to see which tele got added in the "new" video.

The old code tried to ensure that teles that are jumped to are a bit apart, is that why it missed one?

2024-05-09 08:32 UTC, Robyt3 requested changes

2024-05-09 08:32 UTC, Robyt3 commented on src/game/collision.h
> +	//         or (-1, -1) if not found
For consistency please format the Javadoc-style doxygen comments like in `system.h`.

2024-05-09 08:32 UTC, Robyt3 commented on src/game/collision.h
> +	vec2 TeleAllGet(int Number, size_t Offset)
Add the function definition in the source file instead of in the header. The only functions defined inline in this header are single-line functions.

2024-05-09 08:32 UTC, Robyt3 commented on src/game/collision.h
> +	size_t TeleAllSize(int Number)
Same

2024-05-09 08:32 UTC, Robyt3 commented on src/game/client/components/camera.cpp
> +		MatchPos = ivec2(Collision()->TeleAllGet(Number, Offset).x / 32, Collision()->TeleAllGet(Number, Offset).y / 32);
Avoid calling the `TeleAllGet` function twice for x and y.

2024-05-09 08:32 UTC, Robyt3 commented on src/game/client/components/camera.cpp
> +			MatchPos = ivec2(Collision()->TeleAllGet(Number, m_GotoTeleOffset).x / 32, Collision()->TeleAllGet(Number, m_GotoTeleOffset).y / 32);
Same

2024-06-02 08:47 UTC, Robyt3 approved these changes

2024-06-02 09:05 UTC, merged