Show percentage of loaded rcon commands (closed #7769)
ddnet/ddnet pull request #8351
Opened 2024-05-11 04:08 UTC by ChillerDragon

![loading_rcon_commands](https://github.com/ddnet/ddnet/assets/20344300/fb826424-89c0-4fed-baf6-c76634ebaee4)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-05-11 08:44 UTC, Robyt3 requested changes

2024-05-11 08:44 UTC, Robyt3 commented on src/engine/client/client.cpp
> +				m_ExpectedRconCommands = -1;
Use `GetIntOrDefault` instead of checking for error after `GetInt`

2024-05-11 08:44 UTC, Robyt3 commented on src/engine/client/client.cpp
> +int CClient::GotRconCommandsPercentage() const
Return and use `float`

2024-05-11 08:44 UTC, Robyt3 commented on src/engine/server/server.cpp
> +		Num++;
Prefer using `{ }` also for single line loop/if-bodies, if the loop/if header is spread over multiple lines. It's more readable that way.

2024-05-11 08:44 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +				str_format(aBuf, sizeof(aBuf), " %d%%", Percentage);
Add a new buffer `aPercentage[8]` instead of reusing `aBuf`.

2024-05-11 08:44 UTC, Robyt3 commented on src/game/client/components/console.cpp
>  			Ui()->RenderProgressSpinner(vec2(Screen.w / 4.0f + FONT_SIZE / 2.f, FONT_SIZE), FONT_SIZE / 2.f);
The progress spinner supports showing both indeterminate and determinate process.

Move up the variable `Percentage` and also make it a `float`, then do:

```cpp
SProgressSpinnerProperties ProgressProps;
ProgressProps.m_Progress = Percentage;
Ui()->RenderProgressSpinner(vec2(Screen.w / 4.0f + FONT_SIZE / 2.f, FONT_SIZE), FONT_SIZE / 2.f, ProgressProps);
```

Note that since `GotRconCommandsPercentage` returns `-1` if the percentage is unknown, this already fits with the progress spinner assuming indeterminate progress if the percentage is -1, so you don't need to handle that case separately for the spinner.

2024-05-11 08:44 UTC, Robyt3 commented on src/engine/client/client.h
> +	int m_GotRconCommands = 0;
Variables should also be reset in `CClient::DisconnectWithReason`, below `m_ReceivingRconCommands = false`.

2024-05-11 08:44 UTC, Robyt3 commented on src/engine/client/client.cpp
> +	return m_GotRconCommands * 100 / m_ExpectedRconCommands;
The server could send too few expected rcon commands, if the access level is changed while the commands are sent.

This should check if `m_GotRconCommands > m_ExpectedRconCommands` and then `return -1.0f` instead, so no percentage is shown after 100% has already been reached.

2024-05-11 08:47 UTC, Robyt3 commented
By the way, closing statements in the commit/PR title still don't work. I always put the `Closes XYZ` in the body of the commit, so I never run into this issue.

2024-05-12 01:11 UTC, heinrich5991 commented on src/engine/client/client.cpp
> +				m_ExpectedRconCommands = -1;
I'd even go so far and say we drop support for messages without the count.

```c++
m_NumExpectedRconCommands = Unpacker.GetInt();
if(Unpacker.Error())
{
	return;
}
m_ReceivingRconCommands = true;
```

One could probably also drop the `m_ReceivingRconCommands` variable.

2024-05-12 05:18 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +				m_ExpectedRconCommands = -1;
idk what you guys want from me now and why yours is better than mine.

2024-05-12 05:24 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +				m_ExpectedRconCommands = -1;
I did some random guessing of how you want the code to look like.

2024-05-12 09:11 UTC, Robyt3 approved these changes

2024-05-12 09:45 UTC, heinrich5991 commented on src/engine/client/client.cpp
> +				m_ExpectedRconCommands = -1;
I like mine better because it doesn't need to care about the old protocol.

If we want to care about the old message (which I don't think is necessary), then I like @Robyt3's version better because it's more extensible to more fields in the message.

2024-05-12 10:41 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +				m_ExpectedRconCommands = -1;
Marking it as resolved then.

2024-05-12 23:41 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +				m_ExpectedRconCommands = -1;
I told you idk what you want from me. So I guessed. You said remove the bool so I removed the bool. Your code snippet included the bool so I could not use it.

2024-05-13 14:20 UTC, heinrich5991 commented on src/engine/client/client.cpp
> +				m_ExpectedRconCommands = -1;
> You said remove the bool so I removed the bool. Your code snippet included the bool so I could not use it.

I see. My code was also wrong, I want to ignore the message if it does not contain a number:

```
int NumExpectedRconCommands = Unpacker.GetInt();
if(Unpacker.Error())
{
	return;
}
m_NumExpectedRconCommands = NumExpectedRconCommands;
```

2024-05-14 00:00 UTC, heinrich5991 commented
This line will need to be turned into an error again:

https://github.com/ddnet/ddnet/blob/03b13cb9f51a343f61aac89c18bc5f7814a5e253/src/engine/shared/network_conn.cpp#L147

2024-05-14 00:48 UTC, ChillerDragon commented
> This line will need to be turned into an error again:
> 
> https://github.com/ddnet/ddnet/blob/03b13cb9f51a343f61aac89c18bc5f7814a5e253/src/engine/shared/network_conn.cpp#L147

Why? How?

2024-05-14 08:20 UTC, heinrich5991 commented
That was @Kaffeine's comment, not related to this PR. This is the thing that goes wrong when the network buffer becomes full.

2024-05-22 08:39 UTC, heinrich5991 approved these changes
Thanks.

2024-05-22 08:58 UTC, merged