Show help text when chaining multiple commands
ddnet/ddnet pull request #8352
Opened 2024-05-11 04:54 UTC by ChillerDragon

Shows help text of last command not of the entire input.

# before

![image](https://github.com/ddnet/ddnet/assets/20344300/b5d87a27-28d2-4e68-8e6e-91f3cea3c77f)

# after

![image](https://github.com/ddnet/ddnet/assets/20344300/45521b5a-8ff2-4013-8155-7ddcac8fecef)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-05-11 06:02 UTC, ChillerDragon commented
It assumes that the last command is the current command. Not the one where the cursor is. Editing/completing the last command should be the most common use case. Not sure if previous commands are worth the effort/complexity.

2024-05-12 01:44 UTC, heinrich5991 reviewed
I like the feature. :)

2024-05-12 01:44 UTC, heinrich5991 commented on src/game/client/components/console.cpp
> +void CGameConsole::CInstance::StrCopyUntilSpace(char *pDest, size_t DestSize, const char *pSrc) const
I don't think these two functions don't need to be member functions.

Is there a reason you changed `StrCopyUntilSpace` to be a member function?

2024-05-12 01:44 UTC, heinrich5991 commented on src/game/client/components/console.cpp
> +		pInput = str_find(pInput, ";") + 1;
This doesn't take quoting into account, but I think it should.

(It also computes `str_find` twice, but since the fix of the above is probably going to fix it anyway, it doesn't matter here.)

2024-05-12 01:44 UTC, heinrich5991 commented on src/game/client/components/console.cpp
> +		pInstance->m_Input.Set(aBuf);
`CLineInput` should probably get a `Truncate` method, then you could call `Append` afterwards.

2024-05-12 02:01 UTC, ChillerDragon commented
I am currently in the process of giving inline editing a try. Instead of only supporting the last command. So far the code is a bit messy but if I can get it to work I think it is worth it.

2024-05-12 02:30 UTC, ChillerDragon commented
https://github.com/ddnet/ddnet/assets/20344300/fbf23aa5-e599-425f-825f-e5a14c45b846

It can now also auto complete in the middle of the line.

2024-05-12 02:32 UTC, ChillerDragon commented on src/game/client/components/console.cpp
> +void CGameConsole::CInstance::StrCopyUntilSpace(char *pDest, size_t DestSize, const char *pSrc) const
Happend during refactors. I thought someone was just too lazy to open the header file. Whats the point of a non member function?

2024-05-12 03:38 UTC, ChillerDragon commented on src/game/client/components/console.cpp
> +		pInstance->m_Input.Set(aBuf);
Idk how to implement a Truncate method. And I do not feel motivated enough to figure it out. I gave it 20 minutes everything got bugged.

2024-05-12 03:42 UTC, ChillerDragon commented on src/game/client/components/console.cpp
> +		pInstance->m_Input.Set(aBuf);
Force pushed that change away now.

2024-05-12 03:42 UTC, ChillerDragon commented on src/game/client/components/console.cpp
> +void CGameConsole::CInstance::StrCopyUntilSpace(char *pDest, size_t DestSize, const char *pSrc) const
Force pushed that change away now.

2024-05-12 03:50 UTC, ChillerDragon commented
There is one last minor bug. That is when auto completing a command on the left side of a semicolon it then shows the wrong suggestion.

Here I just auto completed +emote but it shows +hook

![image](https://github.com/ddnet/ddnet/assets/20344300/6d1b5993-9bb9-4a10-9885-e61c2cf82bf3)

The cursor position is correct. It just needs a refresh to get corrected. For example tabbing in and out of the game. Or moving the cursor one forward and one backward. Or pressing any key that does not print like option. Then it shows this.

![image](https://github.com/ddnet/ddnet/assets/20344300/d99483d2-9210-42c0-b7ac-53ba0f58911e)

Also iterating with tab only works for the last command. There seems to be some kind of off by one error somewhere.

2024-05-12 03:52 UTC, ChillerDragon commented
# state at commit "[Also split commands on spaces](https://github.com/ddnet/ddnet/pull/8352/commits/5628199a5f73687ad5e5fd18c8973eea00e005f4)"


https://github.com/ddnet/ddnet/assets/20344300/305c1497-7091-4a89-8871-eeab0dacdddd

2024-05-12 05:02 UTC, ChillerDragon commented
With the spaces thing the help text bugged away and StrCopyUntilSpace became useless.

2024-05-13 09:00 UTC, heinrich5991 commented on src/game/client/components/console.cpp
> +void CGameConsole::CInstance::StrCopyUntilSpace(char *pDest, size_t DestSize, const char *pSrc) const
> Happend during refactors. I thought someone was just too lazy to open the header file. Whats the point of a non member function?

A non-member function doesn't take an implicit `this` parameter. This function doesn't need a `this` parameter.

2024-05-13 09:10 UTC, ChillerDragon commented on src/game/client/components/console.cpp
> +void CGameConsole::CInstance::StrCopyUntilSpace(char *pDest, size_t DestSize, const char *pSrc) const
Whats bad about the implicit this parameter?

2024-05-13 09:17 UTC, heinrich5991 commented on src/game/client/components/console.cpp
> +void CGameConsole::CInstance::StrCopyUntilSpace(char *pDest, size_t DestSize, const char *pSrc) const
As a general design rule, functions should not take unnecessary parameters.

An implicit `this` parameter stops you from calling this function unless you have an instance of the class.

2024-07-06 00:53 UTC, ChillerDragon commented
# state at commit "[Remove support for space separation](https://github.com/ddnet/ddnet/pull/8352/commits/51394cf5f233b652d061ad55f9593572044f7377)"

https://github.com/ddnet/ddnet/assets/20344300/fcf632b4-a0ad-499a-bfef-5e24f60de7f3

I was planning to support `bind x <tab>` since that is a common thing people type. But it became so annoying to debug. So I dropped that feature. Only `bind x "<tab>` and `bind x "+fire;<tab>` work.

Ready for review :rocket:

2024-07-07 14:06 UTC, Robyt3 requested changes

2024-07-07 14:06 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +				GetCommand(m_aCompletionBuffer, aSearch, sizeof(aSearch));
Sizes `128` and `IConsole::CMDLINE_LENGTH` are used inconsistently. You could change `GetCommand` so it accepts an array of fixed size `IConsole::CMDLINE_LENGTH` as argument and remove the separate size argument:

`void GetCommand(const char *pInput, char (&aCmd)[IConsole::CMDLINE_LENGTH]);`

2024-07-07 14:06 UTC, Robyt3 commented on src/test/str.cpp
> +	bool Found = str_delimiters_around_offset("foo;;;;bar;;;;;;", ";", 4, &Start, &End);
Remove the variable `Found` and check the return value directly, so the output is more readable for failing test cases.

`EXPECT_EQ(str_delimiters_around_offset("foo;;;;bar;;;;;;", ";", 4, &Start, &End), true);`

Also check the return value for all other test cases above.

2024-07-07 14:06 UTC, Robyt3 commented on src/game/client/components/console.cpp
> +	char aaSeperators[][2] = {";", "\""};
Sep***a***rator(s) (also below)

2024-07-10 16:46 UTC, Robyt3 approved these changes

2024-07-10 17:04 UTC, merged

2024-07-19 01:08 UTC, l-ouis commented
This doesn't work when there are leading spaces on the chained commands:
`player_name test; dummy_name test2` will not show help for dummy_name, even though the command itself works
`player_name test;dummy_name test2` will show help for dummy_name (expected)

2024-07-19 02:09 UTC, ChillerDragon commented
> This doesn't work when there are leading spaces on the chained commands: `player_name test; dummy_name test2` will not show help for dummy_name, even though the command itself works `player_name test;dummy_name test2` will show help for dummy_name (expected)

Yea the same way as in the old version ` player_name test` did not work. Multiple commands or not leading spaces were never supported. It would be nice for sure. I am probably not going to send another pr since I have ptsd from this. If you want it in you can open an issue.