Partial antiping
ddnet/ddnet pull request #8375
Opened 2024-05-18 18:21 UTC by JSaurusRex

Partial antping, adds cl_antiping_percent.
If you ever played on higher ping servers and you use antiping you can see how much players jump, but without antiping your actions have a lot of delay. With this PR you can go somewhere inbetween the 2 extremes.
cl_antiping_percent 50, only predicts 50% ahead, etc.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-05-19 08:49 UTC, Robyt3 commented on src/game/client/components/items.cpp
> +	predictTick = Client()->PredGameTick(g_Config.m_ClDummy) - floor(predictTick * predictPercentage);
Use `std::floor` instead of `floor` (same for all math functions) to avoid the cast to `double`

2024-05-29 08:42 UTC, Kaffeine commented
What do you think about a max antiping prediction time instead of a ratio? I mean that different players are OK with different ms of prediction, (usually) independent of the server and connection.
E.g. someone can be OK with 80ms antiping, no matter what is the current ping (100/200/300). For a 100ms the user 'd prefer 80% but the same value would lead to "jumpy" prediction on 300ms.
IIRC we already had such setting in the past (probably it was a static value for antiping instead of the max prediction).

2024-05-29 11:49 UTC, JSaurusRex commented
> What do you think about a max antiping prediction time instead of a ratio? I mean that different players are OK with different ms of prediction, (usually) independent of the server and connection. E.g. someone can be OK with 80ms antiping, no matter what is the current ping (100/200/300). For a 100ms the user 'd prefer 80% but the same value would lead to "jumpy" prediction on 300ms. IIRC we already had such setting in the past (probably it was a static value for antiping instead of the max prediction).

That setting is still there and to my knowledge just straight up disables antiping above set amount. Though having a max antiping number does make sense my one problem with that is that 50% also makes sense. So maybe both possbilities depending on if you write cl_antiping_max 50% or cl_antiping_max 100
The latter going to max out at 100ms

2024-05-31 23:07 UTC, trml commented
Controlling the amount of antiping sounds nice, but I also wonder if setting it in milliseconds could make more sense. If the goal is to limit how jumpy other players are, that will be more related to how many ms of prediction you have.

Another use case for this could be if you want to target a specific ping (like, you are used to playing at 50 ping with antiping off, but the server has 130 ping). In that case a different setting for the target ping would be better.

2024-06-01 02:42 UTC, sjrc6 commented
the current anti ping limit is basically useless, I think it should simply be replaced with this functionality so a limit of 50 would give you 50ms of total prediction as other have suggested.

2024-06-01 16:59 UTC, JSaurusRex commented
I agree with that the current limit is kinda useless, but I can see all three possibilities being useful. Imagine you only want so much delay for your actions, in that case limiting lack of prediction would make sense. As you guys pointed out some people would wanna limit how much antiping is done to limit players jumping. But having a percentage amount also makes sense. Neither solutions (antiping, no antiping) are perfect so balancing that automatically would be nice. But so would the other ones
What about cl_antiping_limit in ms and cl_antiping_percentage to have a percentage, whichever which ever one is lesser gets chosen

2024-09-19 10:32 UTC, JSaurusRex commented
Currently both cl_antiping_limit and cl_antiping_percent have their usage, cl_antiping_percent gives you a % of the full antiping, default is 100. 50% means the antiping will predict 50%, etc
If antiping_limit is set then it will use that instead, antiping_limit limits the amount of delay (time antiping doesn't predict), some players would rather have this to have a more consistent experience rather than the varying of antiping_percent
Does this solution and variable names seem appropriate?

2024-09-19 14:21 UTC, Robyt3 requested changes
See also the failed CI checks.

2024-09-19 14:21 UTC, Robyt3 commented on src/engine/client/client.cpp
> +	// }
This is dead code and should be removed.

2024-09-19 14:21 UTC, Robyt3 commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(ClAntiPingpercent, cl_antiping_percent, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "how far ahead Antiping predicts, ignored when antiping limit is used")
`how` -> `How`, `Antiping` -> `antiping`

2024-09-19 14:21 UTC, Robyt3 commented on src/game/client/components/items.cpp
> +	int predictTick = GameClient()->GetPredictionTick();
`PredictionTick`

2024-09-19 14:21 UTC, Robyt3 commented on src/game/client/components/items.cpp
> +		int predictTick = GameClient()->GetPredictionTick();
`PredictionTick`

2024-09-19 14:21 UTC, Robyt3 commented on src/game/client/components/items.cpp
> +	int predictTick = GameClient()->GetPredictionTick();
`PredictionTick`

2024-09-19 14:21 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +	int predictTick = Client()->GetPredictionTime() * Client()->GameTickSpeed() / 1000.0f;
`PredictionTick`.

Local variables below should all be capitalized as well.

2024-09-19 14:21 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +		predictMin = predictMin2;
This discards the results for `predictMin` and `predictPercentage` when `g_Config.m_ClAntiPingLimit != 0`. Restructure this so the values are only calculated when they are used.

2024-09-19 14:21 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +	int predictTick = GetPredictionTick();
`PredictionTick`

2024-09-19 14:21 UTC, Robyt3 commented on src/game/client/gameclient.h
> +	int GetPredictionTick();
This function would fit better in `CClient` (close to `CClient::GetPredictionTime`) since it doesn't seem to use any gameclient specific functions or members.

2024-09-21 09:02 UTC, Robyt3 approved these changes
Looks good to me, please squash the commits (and rebase on master to fix the conflict).

2024-09-21 10:27 UTC, Robyt3 approved these changes

2024-09-21 19:51 UTC, sjrc6 commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(ClAntiPingLimit, cl_antiping_limit, 0, 0, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Adds delay to antiping (0 to disable)")
200 seems like a low limit for this? Perhaps use 500?

2024-09-24 16:12 UTC, JSaurusRex commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(ClAntiPingLimit, cl_antiping_limit, 0, 0, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Adds delay to antiping (0 to disable)")
changed it

2024-09-26 17:46 UTC, sjrc6 approved these changes

2025-01-27 08:28 UTC, edg-l approved these changes

2025-01-27 09:05 UTC, merged