Add confetti particles on finish
ddnet/ddnet pull request #8406
Opened 2024-05-28 14:20 UTC by l-ouis

Some fun confetti particles whenever a tee finishes.

Not entirely sure on best practice for creating new particle effects / net events so please let me know.

Also I'm not the best at visuals so perhaps someone can find a better 'confetti-like' particle generator.

https://github.com/ddnet/ddnet/assets/69405348/cb5accc3-1cd0-4925-9435-1ef26eef3679

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-05-28 15:00 UTC, Lazuden commented on src/game/client/components/effects.cpp
> +		ColorRGBA c = ConfettiColors[(rand() % 6)].v4() * random_float(0.75f, 1.0f);
may be use variable for array length? (and for second `for` too)

2024-05-28 15:05 UTC, Lazuden commented on src/game/server/teams.cpp
>  	float Time = TimeTicks / (float)Server()->TickSpeed();
i think line with finish time must be before visual effects

2024-05-28 15:11 UTC, heinrich5991 commented on src/game/server/gamecontext.h
> +	void CreateConfetti(vec2 Pos, CClientMask Mask = CClientMask().set());
```suggestion
	void CreateFinishConfetti(vec2 Pos, CClientMask Mask = CClientMask().set());
```

2024-05-28 15:16 UTC, Robyt3 requested changes

2024-05-28 15:16 UTC, Robyt3 commented on src/game/client/components/effects.cpp
> +		p.m_Color = ColorRGBA(c.r, c.g, c.b, 0.75f * Alpha);
Use `std::size(aConfettiColors)` instead of `6`.

Use the `Multiply` and `WithMultipliedAlpha` functions of `ColorRGBA` instead of converting to `vec4` with `v4`.

2024-05-28 15:16 UTC, Robyt3 commented on src/game/client/components/effects.cpp
> +		p.m_Color = ColorRGBA(c.r, c.g, c.b, 0.75f * Alpha);
Same

2024-05-28 15:20 UTC, Lazuden commented on src/game/client/components/effects.cpp
> +		ColorRGBA c = ConfettiColors[(rand() % 6)].v4() * random_float(0.75f, 1.0f);
i think https://github.com/ddnet/ddnet/pull/8406#discussion_r1617466196 more relevant

2024-05-28 16:03 UTC, Avolicious commented
I would suggest renaming it from "finish@netevent.ddnet.tw" to "confetti@effects.ddnet.tw" or "confetti@particles.ddnet.tw", so we can re-use it other mods aswell without misleading in the code because its called "finish".

Just my 2 cents

But it looks awesome 👍

2024-05-28 16:07 UTC, Robyt3 commented
> Also: maybe use i % std::size(aConfettiColors) instead of rand() % std::size(aConfettiColors) for a bit more speed?

Probably not relevant to optimize for speed here, we are already getting lots of random numbers with `random_float` in those loops so that one `rand` won't have a relevant impact. It would make the confetti colors pretty consistent instead of random though, not sure if that would desirable.

2024-05-28 16:42 UTC, heinrich5991 commented
> I would suggest renaming it from "finish@netevent.ddnet.tw" to "confetti@effects.ddnet.tw" or "confetti@particles.ddnet.tw", so we can re-use it other mods aswell without misleading in the code because its called "finish".

The other events are also named after the things that happen (spawn, death), not after the things they display.

You can of course rename it in your code.

2024-05-28 16:57 UTC, heinrich5991 commented on datasrc/network.py
> +	NetEventEx("Finish", "finish@netevent.ddnet.tw", [
```suggestion
	NetEventEx("Finish:Common", "finish@netevent.ddnet.tw", [
```
Did that not work (while removing the `NetIntAny("m_X")` and `NetIntAny("m_Y")` below)?

If it doesn't work, tell me, then I'll try to get it fixed.

2024-05-29 07:40 UTC, Kaffeine commented on datasrc/network.py
> +	NetEvent("Confetti:Common", []),
From a modding point of view, `Confetti` is a better "building block" than `Finish`. There can be many use cases for `Confetti` in non-racing mods (I could use it to congrats with an achievement) and it would be weird to use `Finish` for that.

`Confetti` and `Finish` are different API contracts — it would be fine to use Confetti for non finish events, and it would be fine to replace Confetti with arbitrary visual effect in case of `Finish`.

2024-05-29 07:49 UTC, Kaffeine commented
> The other events are also named after the things that happen (spawn, death), not after the things they display.
> 
> You can of course rename it in your code.

Correct, the other events have the same issue.

In mods we reuse spawn and death events for very different things in different context. It would be much better for mods if Death event would have custom color instead of the ClientID.

A super handy alternative is some abstract `CreateParticles` event with `count`, `position`, `size/scale`, `textureId`, `color` members.

2024-05-29 08:00 UTC, heinrich5991 commented
> > You can of course rename it in your code.
> 
> As I said, the different name means different warranties. We can't replace `Confetti` event visualization with stars or sparkles, and we can't rely on Finish event kept suitable for anything else except Finish.

I'd call that an advantage from DDNet's point of view. We're not guaranteeing we're keeping a confetti animation in the client for all eternity, or some other animation, but can change it when desired.

2024-05-29 08:05 UTC, Kaffeine commented
> I'd call that an advantage from DDNet's point of view. 

Correct. Modding support virtually always limits the freedom of the project.

2024-05-29 08:08 UTC, l-ouis commented
> A super handy alternative is some abstract `CreateParticles` event with `count`, `position`, `size/scale`, `textureId`, `color` members.

I do think this is a better solution rather than trying to generalize other particle events. There could even be a single quite complex CreateParticles event that would be able to handle any particle effect or alternatively a few 'common' particle effect generators like `RadialBurst, ReverseRadialBurst, Fountain, etc.`

2024-05-31 17:00 UTC, Robyt3 commented on datasrc/network.py
> +	NetEventEx("Finish:Common", "finish@netevent.ddnet.tw", []),
I think new events/objects/messages should use `ddnet.org` instead.

2024-05-31 21:03 UTC, gerdoe-jr commented on src/game/server/teams.cpp
> +	m_pGameContext->CreateFinishConfetti(pChar->m_Pos, pChar->TeamMask());
As I mentioned in Discord, would be lovely to simulate confetti effect for old clients with death particles. I don't know if it's even needed, maybe @heinrich5991 has another opinion

2024-05-31 21:08 UTC, heinrich5991 commented on src/game/server/teams.cpp
> +	m_pGameContext->CreateFinishConfetti(pChar->m_Pos, pChar->TeamMask());
I'd say we don't need to focus on old clients in this PR. This is a visual effect, so there aren't really any pressing backward compatibility concerns.

2024-06-02 08:34 UTC, Robyt3 approved these changes

2024-06-02 11:16 UTC, Kaffeine commented on datasrc/network.py
> +
Weird extra newline

2024-06-02 11:32 UTC, merged

2024-06-02 12:28 UTC, ChillerDragon commented
> I'd call that an advantage from DDNet's point of view. We're not guaranteeing we're keeping a confetti animation in the client for all eternity, or some other animation, but can change it when desired.


I think it is better to be descriptive with the naming and call it confetti. It could still be removed and replaced by a new message. Seems cleaner to me than different client versions displaying different things when they receive the same message.

2024-06-02 15:56 UTC, 1kaipark commented
cool, louis! i like it! :)