Server browser friend list: sort not case sensitive
ddnet/ddnet pull request #8468
Opened 2024-06-08 15:08 UTC by Emilcha

Pull request for #8417.
First time contributing, tell me what I could of done better !

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-06-08 15:56 UTC, Robyt3 requested changes

2024-06-08 15:56 UTC, Robyt3 commented on src/game/client/components/menus.h
>  			return Result < 0 || (Result == 0 && str_comp(m_aClan, Other.m_aClan) < 0);
The case insensitive sorting should also be applied to the clan so it's consistent.

2024-06-08 16:12 UTC, Emilcha commented
Sorry didn't mean to mark as resolved !
You are right what I have done is inconsistant, I will change that out.

2024-06-09 01:30 UTC, def- approved these changes

2024-06-09 01:50 UTC, merged