Don't check `sv_max_team_size` for teams in practice
ddnet/ddnet pull request #8493
Opened 2024-06-15 14:08 UTC by furo321

Closes #8487

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-06-15 14:19 UTC, Robyt3 requested changes
This seems to lack checks for any corners cases. For example, what if practice is disabled on a team that is already above the maximum size?

2024-06-15 14:38 UTC, furo321 commented
Good catch, I forgot that practice gets disabled if you kill. I made it so that it won't disable practice if the team has more players than allowed.

2024-06-15 14:47 UTC, Robyt3 commented
> I made it so that it won't disable practice if the team has more players than allowed.

I think that potentially adds more edge cases. It seems safer to me to kill the entire team instead, if practice gets disabled while the number of players in the team is above the maximum number.

2024-06-15 14:53 UTC, Robyt3 commented on src/game/server/teams.cpp
>  			if(Count(Team) > 1)
Seems like the team is already killed in this case but killing doesn't remove the members from the team. What I meant is that it seems safer to disband the team entirely if it's too large and not in practice anymore.

2024-06-15 16:13 UTC, furo321 commented on src/game/server/teams.cpp
>  			if(Count(Team) > 1)
Fixed, hopefully. The team is now disbanded when there is more players than allowed.

2024-06-16 17:28 UTC, Robyt3 requested changes

2024-06-16 17:28 UTC, Robyt3 commented on src/game/server/teams.cpp
> +				if(Count(Team) >= g_Config.m_SvMaxTeamSize)
Is the `>=` correct or shouldn't it be `>` since a team of exactly the maximum size is still allowed?

2024-06-16 17:28 UTC, Robyt3 commented on src/game/server/teams.cpp
> +					GameServer()->SendChatTeam(Team, "This team was disbanded because there is more players than allowed in the team.");
`there is more players` -> `there are more players`

2024-06-24 15:35 UTC, Robyt3 commented on src/game/server/teams.cpp
> +					GameServer()->SendChatTeam(Team, "This team was disbanded because there is more players than allowed in the team.");
`players` got duplicated in the last change

2024-06-24 17:04 UTC, Robyt3 approved these changes

2024-06-24 18:05 UTC, def- approved these changes

2024-06-24 18:24 UTC, merged