Add team size indicator in scoreboard
ddnet/ddnet pull request #8497
Opened 2024-06-16 14:39 UTC by archimede67

Closes #8496.

Scoreboard having a lot of players:
![DDNet_Ore0TqS1Sn](https://github.com/ddnet/ddnet/assets/13364635/251780b2-7f59-4a1f-8394-eb0117df7897)

Scoreboard having a few players:
![DDNet_DL52PkCsxc](https://github.com/ddnet/ddnet/assets/13364635/2dda7c59-e1c5-41f4-bf64-01e1249d2f25)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-06-16 14:52 UTC, def- reviewed
What is the use? Seems a bit cluttered to me. Why not just count the number of people?

2024-06-16 14:53 UTC, Robyt3 reviewed
Looks confusing. How does the user know which number is the team size and which the team number?

2024-06-16 14:56 UTC, archimede67 commented
> What is the use? Seems a bit cluttered to me. Why not just count the number of people?

In big teams people usually wonder how many players there are. It can be hard for some people to count players, this provides an easy and quick way to know the number of players, for example to tell if a team is even or odd.

> Looks confusing. How does the user know which number is the team size and which the team number?

Interested players will know the difference. We could make it an option, or if you have a better position for it then please suggest it.

2024-06-16 15:34 UTC, BlaiZephyr commented
for small team's i would just render it right next to it:
`Team 30 | size 4`

i also dont really like the placement on big teams, i had to look twice to actually see the indicator. This would also be confusing for team's with the same size as the team number (e.g team 8 with teamsize 8)

im not sure about handling bigger teams and a better position for it, but i'd like some way to distinguish both - something like
```
T: 2
S: 5 
```
maybe?

2024-06-16 15:43 UTC, archimede67 commented
@BlaiZephyr The issue is that the scoreboard does not have a lot of space to render more text when there are a lot of players. I'm not a big fan of using a letter in front either. But I still believe we can render it somehow better, we just have to find how.

2024-06-16 17:41 UTC, Robyt3 commented
> Interested players will know the difference.

But new players have a hard time understanding it like this.

> We could make it an option

I'd rather not add more options to the scoreboard.

> or if you have a better position for it then please suggest it.

I'm not sure we should add more info to the scoreboard, since we already have no space left.

For teams with less than 5 members, showing the team size seems unnecessary, since you can see that number of players immediately without counting. A possibility to make it easier to differentiate between the numbers would be to render the team number as `Localize("T%d", "Team number")` or `"#%d"` and the team size as `"%d/%d"` (i.e. with current and maximum team size). For the long version I agree with @BlaiZephyr, it could be shown as `Localize("Team %d (%d/%d)")` instead, but if the variant of the scoreboard with that few players is shown, the number of players per team is likely also low enough that this would be unnecessary in my opinion.

2024-06-21 18:27 UTC, archimede67 commented
For consistency I think we should keep the team size displayed even on the long version.
Also, it would be weird to have an arbitrary number like 5 to display the team size, so I would prefer if we stick with the original issue which wants to show whenever a team has more than one player.

I have made some changes and here is how it looks now:
![DDNet_hPF04RStUL](https://github.com/ddnet/ddnet/assets/13364635/7134fa08-bcbd-4d6c-9754-57e73bc70b67)
![DDNet_NoRyZK8ujQ](https://github.com/ddnet/ddnet/assets/13364635/63a56648-ac0d-45a1-8db1-775f2701028e)
![DDNet_c9CKfBBSRt](https://github.com/ddnet/ddnet/assets/13364635/c3cdbb92-a22e-4d10-b6de-9dd31918ca09)

I'm not sure about changing the team number to display a `#` in front. I think the addition of the max team size should help in knowing which number corresponds to what information.

2024-06-22 01:44 UTC, def- commented
What is the `/64` part? Is it how many players are on the server in total?

2024-06-22 08:06 UTC, archimede67 commented
@def- It is the maximum team size. On a normal map it is 64 players, but for example on dummy maps it's 2 players.

2024-07-06 11:41 UTC, Robyt3 requested changes
Screenshots for reference:
- 8 or less players:
   - Before:
![screenshot_2024-07-06_13-18-32](https://github.com/ddnet/ddnet/assets/23437060/805db14b-b671-4dde-afc2-5f91b14f0b50)
   - After:
![screenshot_2024-07-06_13-14-01](https://github.com/ddnet/ddnet/assets/23437060/7ae5a0a2-1f2c-4a20-b3c9-460f711cef6e)
- 9 or more players:
   - Before: ![screenshot_2024-07-06_13-18-26](https://github.com/ddnet/ddnet/assets/23437060/2c13f587-9bbc-4a99-a43f-8b50a2c4968b)
   - After: 
![screenshot_2024-07-06_13-13-47](https://github.com/ddnet/ddnet/assets/23437060/bdc98e84-7d44-4948-96ae-a319867aff24)

For few players, the team string should be formatted as `Localize("Team %d (%d/%d)")`. I think it looks better with the team size in parenthesis. Also, the size should be part of the localized string, since other languages may reorders this (e.g. they would name the maximum number first and then the current number).

For many players, I still think the position of the team and team size labels is confusing. With the team number in the bottom left and the team size in the top right this makes it seem like the team size is more important than the number. I think it also doesn't look good that these two labels are split like that depending on the size of the team. How about we show the team number and team size together in one label with the team size also in parenthesis but on a second line, e.g. `Localize("%d\n(%d/%d)", "Team and size")`. I think that would make it clearer what the numbers means. I wouldn't show the team size if there is only one member though.

The margin of the active player background rect is now rather inconsistent. I don't think it makes sense to make this margin dynamic based on the size of the label. Maybe we should just remove the margin entirely so the background always covers the entire player, I wasn't really sure what to do about it in #8545. Or the margin should just be kept at a fixed `10.0f`, since it already was overlapping with the team name label previously.

2024-07-06 17:28 UTC, archimede67 commented
> The margin of the active player background rect is now rather inconsistent.

Is it? I just offset it by the maximum team size possible so it does not overlap with the text.

I've made the suggested changes, here's how it looks:

![image](https://github.com/ddnet/ddnet/assets/13364635/bd13881e-1098-45bd-b5a0-13aeef307f73)

2024-07-06 23:23 UTC, BlaiZephyr commented
> I've made the suggested changes, here's how it looks:
i like that one much more than your first implementation! - is wrapping it withing `( )` helping with readability? i cant really understand the need for that, otherwise i'd be totally happy with the implementation of it :3

2024-07-07 08:49 UTC, Robyt3 requested changes
I think it looks good now. Some small code comments below.

> > The margin of the active player background rect is now rather inconsistent.

> Is it? I just offset it by the maximum team size possible so it does not overlap with the text.

I meant the left and right sides of the margin were previously unbalanced.

2024-07-07 08:49 UTC, Robyt3 commented on src/game/client/components/scoreboard.cpp
> +
This variable can also be kept in the inner scope. It doesn't seem necessary to increase its scope anymore.

2024-07-07 08:49 UTC, Robyt3 commented on src/game/client/components/scoreboard.cpp
> +	int MaxTeamSize = m_pClient->ConfigManager()->Values()->m_SvMaxTeamSize;
Use `m_pClient->Config()->m_SvMaxTeamSize` or `g_Config.m_SvMaxTeamSize`.

2024-07-07 10:30 UTC, Robyt3 approved these changes

2024-07-07 10:47 UTC, merged

2024-07-08 09:04 UTC, heinrich5991 commented
The /64 seems unnecessary for unlimited team size.