Fix ShowDistance being double in size
ddnet/ddnet pull request #8500
Opened 2024-06-18 19:59 UTC by fokkonaut

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-06-18 20:05 UTC, heinrich5991 commented
This is something that should be fixed on the client side.

The client requests a view distance, the server gives that view distance. If it wants a different view distance, it should say so.

2024-06-18 20:16 UTC, fokkonaut commented
> This is something that should be fixed on the client side.
> 
> The client requests a view distance, the server gives that view distance. If it wants a different view distance, it should say so.

The client sends it's full distance, would be cool if this would not get removed, since it's already widely used on my server and would break if this get's changed on the clientside.

2024-06-18 20:18 UTC, fokkonaut commented
Well, if we just send half of what we're sending now, I could catch that and multiply it again. But it's really important to get the full screen params for the features in F-DDrace

2024-06-19 00:14 UTC, fokkonaut commented
https://github.com/ddnet/ddnet/pull/5063#issuecomment-1115352645

Seems like it's not entirely wrong, since you already used tit correctly here

2025-04-27 22:12 UTC, fokkonaut commented
Could we maybe get this in for now, to at least reduce network traffic and Snap() calls, when they are really not required? We've been using ShowDistance for years in this style...

2025-06-01 10:07 UTC, Robyt3 requested changes
> Right now we have an issue, where on a big map a player can zoom out only a little bit, and get's twice as much the length in each direction and therefore calls unnecessary amount of Snap()

> This is something that should be fixed on the client side.

2025-08-06 17:56 UTC, edg-l commented
closing as its stale / has known bugs, feel free to open another pr

2025-08-06 17:56 UTC, closed without merging

2025-10-21 07:48 UTC, heinrich5991 commented
Should be fixed on the client side instead.

2026-04-16 15:21 UTC, heinrich5991 commented
By adding a compatibility switch for older clients.

2026-04-16 15:30 UTC, fokkonaut commented
> By adding a compatibility switch for older clients.

The feature works correctly. The client sends it's screen width and height, and the server sends the corresponding objects within those dimensions. Am I missing something?

Since 2 years the DDNet servers are sending too many objects that are out of the client's FOV because you don't like the current implementation. That is just pathetic. You don't want a fix, you want a behaviour change that requires implementation of backwards compatibility, while this is fully functional and requires a serverside fix.

In 2022 you already used the correct calculation: 

> [#5063 (comment)](https://github.com/ddnet/ddnet/pull/5063#issuecomment-1115352645)
> 
> Seems like it's not entirely wrong, since you already used tit correctly here

> Maybe a simpler solution for NetworkClippedLine would also work like @heinrich5991 suggested:
> 
> > I think this would be the proper fix, it should also not be that hard: Perhaps just check whether the closest point on the hook/dragger line is within max(width/2, height/2) of the player's camera center.

Please separate personal issues from technical discussions.