Trim strings in search & exclude inputs in server browser
ddnet/ddnet pull request #8504
Opened 2024-06-19 20:57 UTC by MilkeeyCat

I tried to do part of this issue #8411. I'm not sure the solution is the best one, if you want it to be implemented in a different way, lemme know.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-06-20 01:25 UTC, def- reviewed
I'm wondering how much slower this makes the serverbrowser. Did you check fps with gfx_refresh_rate 0 and cl_refresh_rate 0?

2024-06-20 05:41 UTC, MilkeeyCat commented
![image](https://github.com/ddnet/ddnet/assets/40633857/417fbf99-3f7f-4639-aa11-c3259b984a97)
In my shitty setup it jumps from 500 to 700 fps in both cases. Maybe someone with a better setup could check :/

2024-06-20 06:01 UTC, def- approved these changes

2024-06-20 10:42 UTC, MilkeeyCat commented
![image](https://github.com/ddnet/ddnet/assets/40633857/0640d6c6-f29b-42e7-9c5c-751cecdd439c)
![image](https://github.com/ddnet/ddnet/assets/40633857/ae895b2e-5629-430d-ae5c-3f36021f9417)

2024-06-20 12:01 UTC, def- approved these changes
One problem with the filtering for me is that I often use spaces intentionally to find only the servers of a location, like `" RUS1 "`. I guess this will break now.

2024-06-22 20:16 UTC, Robyt3 requested changes

2024-06-22 20:16 UTC, Robyt3 commented on src/engine/client/serverbrowser.cpp
> +				while((pStr = str_next_token(pStr, IServerBrowser::SEARCH_EXCLUDE_TOKEN, aFilterStr, sizeof(aFilterStrTrimmed))))
Use `sizeof(aFilterStr)` for consistency

2024-06-22 20:16 UTC, Robyt3 commented on src/engine/client/serverbrowser.cpp
> +				while((pStr = str_next_token(pStr, IServerBrowser::SEARCH_EXCLUDE_TOKEN, aExcludeStr, sizeof(aExcludeStrTrimmed))))
Use `sizeof(aExcludeStr)` for consistency

2024-06-22 20:16 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +		GameClient()->m_Tooltips.DoToolTip(&s_FilterInput, &QuickSearch, "Example of usage: \"solo; nameless tee; kobra 2\"");
The tooltip should be `Localize`d

2024-06-22 20:16 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +		GameClient()->m_Tooltips.DoToolTip(&s_ExcludeInput, &QuickSearch, "Example of usage: \"CHN; [A]\"");
The tooltip should be `Localize`d

2024-06-22 20:20 UTC, MilkeeyCat commented on src/game/client/components/menus_browser.cpp
> +		GameClient()->m_Tooltips.DoToolTip(&s_ExcludeInput, &QuickSearch, "Example of usage: \"CHN; [A]\"");
Only `Example of usage` part or the whole string?

2024-06-22 20:27 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +		GameClient()->m_Tooltips.DoToolTip(&s_ExcludeInput, &QuickSearch, "Example of usage: \"CHN; [A]\"");
Only the `Example of usage` I'd say. You'll have to use `static` buffers for the tooltips then though (see usage of `static char s_aHoveredTime[32];` in `menus_demo.cpp`).

2024-06-23 11:07 UTC, Robyt3 requested changes
One more nitpick, looks good otherwise. Please also squash the commits into one.

2024-06-23 11:07 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +		static char aTooltipText[64];
`s_aTooltipText` because it's a static variable

2024-06-23 11:07 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +		static char aTooltipText[64];
`s_aTooltipText`

2024-06-23 13:13 UTC, Robyt3 approved these changes
Thanks.

2024-06-23 13:30 UTC, merged