server: Reserved slot should depend on number of connected clients
ddnet/ddnet pull request #8539
Opened 2024-07-01 11:04 UTC by def-

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-07-01 12:15 UTC, heinrich5991 approved these changes
Previously, the reserved slots were the higher client IDs, e.g. 63 if there was one reserved slot. This meant that if you had joined this reserved slot (client ID 63), and then stay on the server, no one will be able to use the reserved slot even after a player leaves.

The new behavior no longer ties the reserved slots to client IDs, thus reclaiming the reserved slot when *any* player leaves, not just the player who used the reserved slot.

I believe the latter is how the player counting worked for the server info.

I think this change makes sense.

Any other opinions?

2024-07-07 10:58 UTC, Robyt3 requested changes
I think the new behavior makes sense.

There's an off-by-one error though.

2024-07-07 10:58 UTC, Robyt3 commented on src/engine/server/server.cpp
> +				if(NumConnectedClients >= Config()->m_SvMaxClients - Config()->m_SvReservedSlots && !CheckReservedSlotAuth(ClientId, pPassword))
```suggestion
				if(NumConnectedClients > Config()->m_SvMaxClients - Config()->m_SvReservedSlots && !CheckReservedSlotAuth(ClientId, pPassword))
```

For example, with `sv_max_clients 2; sv_reserved_slots 0` and one client already connected, you could not connect to the last free slot unless you used the reserved slot authentication.

2025-06-24 07:03 UTC, edg-l approved these changes

2025-06-24 16:07 UTC, Robyt3 approved these changes

2025-06-24 17:14 UTC, merged