Add 128 player support from F-DDrace
ddnet/ddnet pull request #8542
Opened 2024-07-01 16:20 UTC by fokkonaut

Hey,

this Pull Request will add support for 128 (n) clients at the same time. Good for t0 maps, Multeasy, modders, etc.
It's based on my implementation in [F-DDrace](https://github.com/fokkonaut/F-DDrace), where it works pretty flawlessly without major bugs.
If more than 64p (62, -1 for chat msg, -1 for spectator selector, later more...) are in your FOV, my algorithm doesn't check who of those is actually closer yet, cuz I thought that's not as important. Can't think of many situations where that actually happens.
For the case it does, the players who are in your FOV first will stay in your Idmap until they are NetworkClipped and another tee which is not in the map yet can get added, when not networkclipped.

Players who are not in your Id map are displayed as their weapon + hook as laser:
![image](https://github.com/ddnet/ddnet/assets/35420825/d4fad706-0c3d-4abe-b967-3be3ea9279df)

In case more than 64players are actually online and you want to spectate them, you can use the `+spectate` menu to cycle through a list of players:
![image](https://github.com/ddnet/ddnet/assets/35420825/63c135e2-eb8f-4b1b-8496-698ae529bcdb)
![image](https://github.com/ddnet/ddnet/assets/35420825/2e2c748c-3018-4c16-8f69-d33dfa959e4a)
![image](https://github.com/ddnet/ddnet/assets/35420825/a49de2fb-cb32-4035-979d-5e1010f283da)

Note that it says 66 others, because of the explanation above, 64-2=62, 128-62=66, quick maths.

It's assured that dummy hammer will always work. Players with the same IPs are all stored in the beginning of the map, so they are the same for each:
![image](https://github.com/ddnet/ddnet/assets/35420825/bffc7c45-96e4-4cfd-8f1a-3df8c2cc0106)

Teams are the same, they are sorted after same-ip players, and keep their order, because the client only knows about one set of Teams for teamsstates. That means, dummy's and main's list have to stay in sync in order to not get fucked up.
![image](https://github.com/ddnet/ddnet/assets/35420825/0b9c7d28-9992-4b04-bc47-76e00ee4fc42)

Since team players are always stored, having more than 64 tees in teams will break, same as more than 64 players with the same ip.

Strong/weak hook is translated aswell.

I haven't tested everything on DDNet source yet, but the first tests seemed to be working flawlessly.

I have NOT checked in how far this influences performance, but I believe by a fair bit since it's not 100% optimized.

I had to change the SendMsg functions, because I took the part of my 0.7 server for chat messages. They are very annoying, so I did not want to investigate too much time fixing it for DDNet's 0.6 base and instead simply used it the way I knew it, with protocol7::Sv_Chat, also for 0.6 clients.

If there are any questions, feel free to ask.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-07-01 16:32 UTC, def- commented
Once this builds I'd like to try it out on one of our more powerful servers, so for example UKR and RUS. If things go well, we'll need proper client support instead of player mapping.

2024-07-01 16:33 UTC, fokkonaut commented on src/game/server/playermapping.cpp
> +				GameServer()->m_apPlayers[i]->m_aStrongWeakID[ID] = StrongWeakID;
For some reason ID can be garbage here currently. Dunno yet

2024-07-01 16:52 UTC, fokkonaut commented
> Once this builds I'd like to try it out on one of our more powerful servers, so for example UKR and RUS. If things go well, we'll need proper client support instead of player mapping.

We still need player mapping for older clients though!

2024-07-01 17:14 UTC, def- commented
> We still need player mapping for older clients though!

Nearly everyone is on new client, so we could even limit the client number on those servers. I feel like the playermapping has a lot of complexity.

2024-07-01 17:19 UTC, fokkonaut commented
> > We still need player mapping for older clients though!
> 
> Nearly everyone is on new client, so we could even limit the client number on those servers. I feel like the playermapping has a lot of complexity.

Yes, that's true. DDNet client has many features, that's why. Also, making servers only for DDNet client if max_clients is > 64 sounds good, but that will lead to ddnet cutting off vanilla support in the future for sure

2024-07-01 17:34 UTC, fokkonaut commented
@def- it's building now, pipeline is just failing

2024-07-01 17:49 UTC, def- commented
Fixed tests and style

2024-07-01 18:03 UTC, def- commented
@headshot2017 Do we have to rebuild antibot dlls because we bumped the number of max clients?

2024-07-01 18:11 UTC, def- commented
Indeed. @nobody-mb

2024-07-01 18:14 UTC, def- commented
What happens if you save on a server with 128 players in a huge team and then load on a normal server? :D

2024-07-01 18:16 UTC, fokkonaut commented
> What happens if you save on a server with 128 players in a huge team and then load on a normal server? :D

No idea. Lol. Should disable saving on the BETA server.

2024-07-01 18:24 UTC, def- commented
Please fix the valgrind errors, they look serious.

2024-07-01 18:44 UTC, heinrich5991 commented on src/game/server/gamecontext.cpp
> +			pPickup->m_Type = SubType == WEAPON_SHOTGUN ? protocol7::PICKUP_SHOTGUN : SubType == WEAPON_GRENADE ? protocol7::PICKUP_GRENADE : SubType == WEAPON_LASER ? protocol7::PICKUP_LASER : SubType == WEA
This looks unrelated.

2024-07-01 18:45 UTC, heinrich5991 commented
This should get some teehistorian mark so @Zwelf doesn't despair.

Likely breaks the scoreboard code.

2024-07-01 18:50 UTC, def- commented
Some problems:
- Client needs to support it, current playermapping is messy
- Weapon-rendered players stay closeby to you
- Antibot needs updating
- The message when player 64 joins needs be updated
- Sometimes all players flicker

2024-07-01 19:14 UTC, heinrich5991 commented
I think we should disable ranks on the 128 player server for now.

I think we should add client support before we let this get out of beta.

> * scoreboard in client might fit 128 players Robyt3 reports

The screenshot looked like this was a joke from @Robyt3.

2024-07-01 19:14 UTC, fokkonaut commented on src/game/server/gamecontext.cpp
> +			pPickup->m_Type = SubType == WEAPON_SHOTGUN ? protocol7::PICKUP_SHOTGUN : SubType == WEAPON_GRENADE ? protocol7::PICKUP_GRENADE : SubType == WEAPON_LASER ? protocol7::PICKUP_LASER : SubType == WEA
It is not, since the server renders the weapon as tee if it's not in the idmap.

2024-07-01 19:16 UTC, sjrc6 commented
Is it worth having backwards compatibility for this? If we're going to update the client anyway it seems much less complex to just restrict access to 128 player servers to those who have a supported client.

2024-07-01 19:25 UTC, fokkonaut commented
> Is it worth having backwards compatibility for this? If we're going to update the client anyway it seems much less complex to just restrict access to 128 player servers to those who have a supported client.

Thats the plan

2024-07-01 19:28 UTC, Robyt3 commented
> > * scoreboard in client might fit 128 players Robyt3 reports
> 
> The screenshot looked like this was a joke from @Robyt3.

Yeah, it's not very readable with the small font. It barely works on 1920x1080 but on lower resolutions or with smaller screens it would be even harder. But it would be a relatively simple change (as I had already been refactoring the scoreboard) so it would be good enough for the first client support of this feature in my opinion. There's probably no way around making the scoreboard scrollable though, unless we try to increase its width and show 3 or 4 columns.

![screenshot_2024-07-01_20-49-00](https://github.com/ddnet/ddnet/assets/23437060/6e9fd0a3-b7a0-486c-814e-5c503642c8d5)

2024-07-01 19:28 UTC, sjrc6 commented
> > Is it worth having backwards compatibility for this? If we're going to update the client anyway it seems much less complex to just restrict access to 128 player servers to those who have a supported client.
> 
> Thats the plan

Does that make most of the code in this PR just for testing then? I would think you shouldn't need all the workarounds for getting 64p clients to join with a proper 128p client.

2024-07-01 22:16 UTC, def- commented
> I think we should disable ranks on the 128 player server for now.

People will be extremely disappointed by that, so I'm against that.

2024-07-02 09:13 UTC, heinrich5991 commented
@def- @Zwelf Make sure we skip teehistorian minor version 9 in case we don't merge this PR.

2024-07-02 10:08 UTC, def- commented
I plan to merge it at some point

2024-07-02 11:09 UTC, def- commented
Crashed:
```
Core was generated by `./DDNet-Server-128 -f servers/8312.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  CPacker::AddString (this=this@entry=0x7ffc586f7340,
    pStr=0x3 <error: Cannot access memory at address 0x3>, Limit=2048, Limit@entry=-1)
    at /home/teeworlds/src/128/src/engine/shared/packer.cpp:38
38	/home/teeworlds/src/128/src/engine/shared/packer.cpp: No such file or directory.
[Current thread is 1 (Thread 0x7f6d40eaea40 (LWP 1174604))]
(gdb) bt
#0  CPacker::AddString (this=this@entry=0x7ffc586f7340,
    pStr=0x3 <error: Cannot access memory at address 0x3>, Limit=2048, Limit@entry=-1)
    at /home/teeworlds/src/128/src/engine/shared/packer.cpp:38
#1  0x000055d4f6c60474 in protocol7::CNetMsg_Sv_VoteSet::Pack (pPacker=0x7ffc586f7340,
    this=0x7ffc586f7bf0) at /home/teeworlds/src/128-build/src/game/generated/protocol7.h:700
#2  IServer::SendPackMsgOne<protocol7::CNetMsg_Sv_VoteSet> (this=this@entry=0x7f6d3a5ac010,
    pMsg=pMsg@entry=0x7ffc586f7bf0, Flags=Flags@entry=1, ClientId=ClientId@entry=0)
    at /home/teeworlds/src/128/src/engine/server.h:272
#3  0x000055d4f6c5af34 in IServer::SendPackMsgTranslate (ClientID=0, Flags=1, pMsg=0x7ffc586f7bb0,
    this=0x7f6d3a5ac010) at /home/teeworlds/src/128/src/engine/server.h:285
#4  IServer::SendPackMsg<CNetMsg_Sv_VoteSet, 0> (ClientId=0, Flags=1, pMsg=0x7ffc586f7bb0,
    this=0x7f6d3a5ac010) at /home/teeworlds/src/128/src/engine/server.h:90
#5  CGameContext::SendVoteSet (this=this@entry=0x7f6d40649010, ClientId=ClientId@entry=-1)
    at /home/teeworlds/src/128/src/game/server/gamecontext.cpp:834
#6  0x000055d4f6c5d7d2 in CGameContext::EndVote (this=0x7f6d40649010)
    at /home/teeworlds/src/128/src/game/server/gamecontext.cpp:784
#7  CGameContext::OnTick (this=0x7f6d40649010)
    at /home/teeworlds/src/128/src/game/server/gamecontext.cpp:1214
#8  0x000055d4f6c2eb24 in CServer::Run (this=this@entry=0x7f6d3a5ac010)
    at /home/teeworlds/src/128/src/engine/server/server.cpp:2950
#9  0x000055d4f6c183bb in main (argc=<optimized out>, argv=<optimized out>)
    at /home/teeworlds/src/128/src/engine/server/main.cpp:197
```

2024-07-02 12:00 UTC, def- commented
The RUS2 Novice 128 player server now disappeared from server browser:
```
2024-07-02 14:00:02 E register/6/ipv4: error response from master: 400: Request body deserialize error: EOF while parsing a value at line 1 column 16383
```

2024-07-02 13:27 UTC, def- commented
I'd prefer both together, but not sure how long client support would take and who'd be willing to work on it.

2024-07-02 13:52 UTC, heinrich5991 commented
> I'd prefer both together, but not sure how long client support would take and who'd be willing to work on it.

I'd prefer both together, to the point where I'd not want to merge this beforehand. If that means that no one is working on it, then I'd like to not merge this.

2024-07-02 13:58 UTC, fokkonaut commented
> > I'd prefer both together, but not sure how long client support would take and who'd be willing to work on it.
> 
> I'd prefer both together, to the point where I'd not want to merge this beforehand. If that means that no one is working on it, then I'd like to not merge this.

Maybe there could be a "lightweight" client implementation for now, which does not cover everything yet, just receiving all players and maybe a scoreboard, so the server doesnt have to translate/loop for those. What else would be required?

2024-07-02 14:23 UTC, heinrich5991 commented
Some bugs from Discord:

[Tsumugi](https://discord.com/channels/252358080522747904/757720336274948198/1257692146064949320):
> ![image](https://github.com/ddnet/ddnet/assets/366230/a29cd3de-09ac-4ffb-9f21-3454f6575bee)

[wwwhhh](https://discord.com/channels/252358080522747904/757720336274948198/1257701642623782913):
> on 128 player servers teams above 64 are glitched, 64 shows as "super" in tab and teams above dont show on tab at all and dont have a color

[xKox](https://discord.com/channels/252358080522747904/757720336274948198/1257696098240168058):
> When I was running the map just now, I crossed the finish line and then got a record. But when I tried to re-enter this server, my record was gone. And the records of the people who passed the race in front of and behind me are still there.
> ![image](https://github.com/ddnet/ddnet/assets/366230/91d18384-f107-4d5c-a2b7-e41cd6ce2742)
> ![image](https://github.com/ddnet/ddnet/assets/366230/22319b90-e218-4b91-be96-36fe0cf9643b)
> ![image](https://github.com/ddnet/ddnet/assets/366230/6fdb7c9e-4fbb-4375-ab9b-c0058d064b04)
> ![image](https://github.com/ddnet/ddnet/assets/366230/dcacb166-f52b-4862-8126-b59eacff1d84)

2024-07-03 11:18 UTC, def- commented
Is the voting crash fixed or will this also crash now that we allow map votes?

2024-07-03 12:46 UTC, heinrich5991 commented
Moderators say that they cannot moderate these servers without client support.

2024-07-03 13:35 UTC, fokkonaut commented
> Moderators say that they cannot moderate these servers without client support.

Moderators just have to adapt. Use `status fok` to see only entries containing the string `fok`.
They just don't want to. It works perfectly on my server, just one more command to get the client id instead of checking the scoreboard, which would be too big to find a specific tee with 128 players anyways.

2024-07-03 20:31 UTC, jxsl13 commented
I wonder how to match weird utf8 characters as nicknames

2024-07-03 21:07 UTC, fokkonaut commented
> I wonder how to match weird utf8 characters as nicknames

I always auto complete them with chat, preferrably using shift+tab to reverse iterate, then ctrl+a ctrl+c :)

2024-07-04 04:53 UTC, fokkonaut commented
> Is the voting crash fixed or will this also crash now that we allow map votes? Edit: looks fixed, running map votes now.

Sorry, I didn't see that message at first. Yes, I immeditately fixed it

2024-07-04 05:14 UTC, fokkonaut commented on src/game/server/gamecontext.cpp
>  	}
This probably breaks voting on clients that support 16 tees only

2024-07-04 05:14 UTC, fokkonaut commented on src/game/server/gamecontext.cpp
> +	m_PlayerMapping.InitPlayerMap(ClientID, true);
Haven't tested rejoining the same slot yet, on my server I also call this when rejoin happened.

2024-07-04 05:14 UTC, fokkonaut commented on src/game/server/player.cpp
> -	int FakeId = VANILLA_MAX_CLIENTS - 1;
This will break 16p too

2024-07-14 16:06 UTC, def- commented
@Robyt3 I think a rudimentary client support would still be useful. The cat seems to be out of the bag now anyway, multiple hosters are using this 128 player server. Do you have a branch for your 128 player client support?

2024-07-14 19:10 UTC, Robyt3 commented
> @Robyt3 I think a rudimentary client support would still be useful. The cat seems to be out of the bag now anyway, multiple hosters are using this 128 player server. Do you have a branch for your 128 player client support?

I pushed my changes to add basic support for 128 players in the scoreboard and the spectator UI in #8591, so 128 players should be supported in the UI everywhere (except in the statboard which only support 16 players anyway).

Other than that, I only really changed `MAX_CLIENTS`, `NET_MAX_CLIENTS` and `ANTIBOT_MAX_CLIENTS` from `64` to `128`. I didn't think about any compatiblity for old server and old clients yet. There will probably have to be some translation for `TEAM_SUPER`, since old servers use team 64 but new servers would use team 128, same as `VANILLA_TEAM_SUPER` for old 16 players servers.

2024-07-15 13:31 UTC, heinrich5991 commented
For simplicity, maybe we could keep the old number of 64 teams?

2024-07-16 08:55 UTC, Robyt3 commented
> For simplicity, maybe we could keep the old number of 64 teams?

Would definitely be simpler, but then `sv_team 3` (`SV_TEAM_FORCED_SOLO`) does not work on servers with more than 64 max clients as every client needs its own team.

2024-07-16 18:05 UTC, fokkonaut commented
> > For simplicity, maybe we could keep the old number of 64 teams?
> 
> Would definitely be simpler, but then `sv_team 3` (`SV_TEAM_FORCED_SOLO`) does not work on servers with more than 64 max clients as every client needs its own team.

Just add 128 teams, so solo is fixed, then disallow /team > 63

2024-07-21 09:48 UTC, 0xfaulty commented
@def- Do we need to change
#define CURL_MAX_WRITE_SIZE 16384
in ddnet-libs/curl/include/curl/curl.h
to 32768 also?

Bcs I also face with

E register/6/ipv4: error response from master: 400: Request body deserialize error: EOF while parsing an object at line 1 column 16383

And changed it in that constant as well, but haven't tested it yet, so not sure if it's necessary or not

2024-07-21 09:54 UTC, def- commented
Ready for review from my side. Major changes:
1. 16 player Teeworlds 0.6 is no longer supported at all, are we ok with that? Otherwise have to implement translation for them too. I think no one uses Teeworlds 0.6 anymore
2. Translation to 64 player compat. only happens if sv_max_clients > 64
3. No translation for DDNet 19.0 client, which supports 128 players natively
4. Teams still use team 64 for super, max 64 teams, but 128 for solo mode (not sent to client anyway)

The plan is to release this in DDNet 19.0 while keeping servers at 64 players max, give people a few weeks to update, then switch the servers to 128 players.

2024-07-21 11:03 UTC, heinrich5991 commented on src/engine/server.h
> +	inline int SendPackMsgForce(const T *pMsg, int Flags, int ClientId)
I find the current code quality of this PR to be low. As the first example, I have no clue what this function is supposed to do, and the name doesn't tell m that. I can go over the rest of the PR if you want to merge this and annotate all the places where it's not clear to me.

I'm currently working on moving the whole translation code out of the main code base so that we don't have to translation for older clients all over the place. I'd like to be given a couple of weeks (maybe 4?) to get this to a usable state.

2024-07-21 11:26 UTC, def- commented on src/engine/server.h
> +	inline int SendPackMsgForce(const T *pMsg, int Flags, int ClientId)
Does it make sense to put this much effort into the translation layer? It will be used by way less than 1% of players. Even dropping it might be preferable.

2024-07-21 11:39 UTC, def- commented
@fokkonaut Why are we comparing IPs in playermapping?

2024-07-21 11:39 UTC, fokkonaut commented
> @fokkonaut Why are we comparing IPs in playermapping?

For getting them sorted correctly to make hammerfly work.

2024-07-21 11:39 UTC, def- commented on src/engine/server.h
> +	inline int SendPackMsgForce(const T *pMsg, int Flags, int ClientId)
I think we should focus on features for players on the current DDNet client version, and not keep working so that old versions of Teeworlds, which no one is using, are supported.

2024-07-21 11:40 UTC, def- commented
That is crazy, what does hammerfly have to do with sorting?!

2024-07-21 11:50 UTC, fokkonaut commented
> That is crazy, what does hammerfly have to do with sorting?!

> It's assured that dummy hammer will always work. Players with the same IPs are all stored in the beginning of the map, so they are the same for each

As explained in the initial comment.
They need the correct IDs, if the IDs differ it'll be difficult because the dummy will hammer towards some other person.

2024-07-21 13:00 UTC, def- commented
Thanks @0xfaulty , fixed in latest commit

2024-07-21 13:02 UTC, def- commented
@fokkonaut Hammerfly can still be wrong then if someone else with the same IP plays on the server.

2024-07-21 13:02 UTC, fokkonaut commented
> @fokkonaut Hammerfly can still be wrong then if someone else with the same IP plays on the server.

No?

2024-07-21 13:10 UTC, def- commented
Ah, all the players with same IP will be included, ok.

2024-07-21 17:17 UTC, heinrich5991 commented on src/engine/server.h
> +	inline int SendPackMsgForce(const T *pMsg, int Flags, int ClientId)
Then drop the support instead of adding code.

2024-07-21 17:23 UTC, heinrich5991 commented on src/mastersrv/src/main.rs
> +        .and(warp::body::content_length_limit(32 * 1024)) // limit body size to 32 KiB
Where do the 32 KiB come from? Did someone try to calculate how much is necessary? Do we need 256 bytes per player?

2024-07-22 10:26 UTC, def- commented on src/mastersrv/src/main.rs
> +        .and(warp::body::content_length_limit(32 * 1024)) // limit body size to 32 KiB
There are also servers with 512 players btw, I guess they will break with current mastersrv when they have too many players too.

2024-07-22 10:28 UTC, def- commented on src/engine/server.h
> +	inline int SendPackMsgForce(const T *pMsg, int Flags, int ClientId)
I think we should keep 64 player support for a few versions at least. I'm just worried that you might be putting in a lot of effort for code that we will remove soon-ish.

2024-07-22 11:38 UTC, fokkonaut commented on src/mastersrv/src/main.rs
> +        .and(warp::body::content_length_limit(32 * 1024)) // limit body size to 32 KiB
I think max clients shouldn't be able to exceed 128. SERVERBROWSER_MAX_CLIENTS has been set to 128, to allow 128 clients, but more can't be sent, so why should maxclients be able to display more?

2024-07-22 11:43 UTC, heinrich5991 commented on src/mastersrv/src/main.rs
> +        .and(warp::body::content_length_limit(32 * 1024)) // limit body size to 32 KiB
> `SERVERBROWSER_MAX_CLIENTS` has been set to 128, to allow 128 clients, but more can't be sent, so why should maxclients be able to display more?

The serverbrowser has explicit support for more players, it just can't display more than 128.

2024-07-22 11:57 UTC, fokkonaut commented on src/mastersrv/src/main.rs
> +        .and(warp::body::content_length_limit(32 * 1024)) // limit body size to 32 KiB
> > `SERVERBROWSER_MAX_CLIENTS` has been set to 128, to allow 128 clients, but more can't be sent, so why should maxclients be able to display more?
> 
> The serverbrowser has explicit support for more players, it just can't display more than 128.

Okay, I see, good job on making it variable, but no user will ever notice/care about that at all when the browser can only show 128 due to client limitations.
What I'm trying to tell you is that the mismatch in the client is more than confusing for some people, and I am unsure if they should be able to broadcast such playercounts if they can't reach it. Yes, you made a technically good master, but since clients determine numClients based on the client's that got sent and processed, I think it can not even show a higher numClients than 128.

2024-07-22 12:07 UTC, heinrich5991 commented on src/mastersrv/src/main.rs
> +        .and(warp::body::content_length_limit(32 * 1024)) // limit body size to 32 KiB
> but since clients determine numClients based on the client's that got sent and processed, I think it can not even show a higher numClients than 128.

I think the client also counts the server clients it cannot display:

https://github.com/ddnet/ddnet/blob/3297aa336ab9c9605d4d2238c0b7968b0e248a32/src/engine/shared/serverinfo.cpp#L133-L134

https://github.com/ddnet/ddnet/blob/3297aa336ab9c9605d4d2238c0b7968b0e248a32/src/engine/shared/serverinfo.cpp#L181-L187

If that's not the case, please report a bug.

2024-08-04 13:33 UTC, def- commented on src/engine/server.h
> +	inline int SendPackMsgForce(const T *pMsg, int Flags, int ClientId)
I'd like to try to get this in. @heinrich5991 What else should I try to figure out/explain?
@fokkonaut Maybe you can explain/clean some spots up too?

2024-08-05 16:48 UTC, heinrich5991 reviewed
Couple of `id` → `Id` and `ID` → `Id`.

The PR includes the "see others" functionality which is probably unnecessary, but it probably also doesn't hurt too bad.

Why is there duplication between engine player maps and playermapping.h?

Need to leave, but leaving these comments for now.

2024-08-05 16:48 UTC, heinrich5991 commented on src/engine/server.h
> +	 * SendPackMsg, but send to both 0.6 and 0.7 players, not just one of them
That seems to be what `SendPackMsg` does already. Why do we need another function?

2024-08-05 16:48 UTC, heinrich5991 commented on src/game/server/ddracechat.cpp
> +		if(Team < 0 || Team >= LEGACY_MAX_CLIENTS)
```suggestion
		if(Team < 0 || Team >= TEAM_SUPER)
```
I guess.

2024-08-05 16:48 UTC, heinrich5991 commented on src/engine/server/server.cpp
> +	str_format(aDemoName, sizeof(aDemoName), "%s [128 player BETA]", Config()->m_SvName);
This should probably go before it's released.

2024-08-05 16:48 UTC, heinrich5991 commented on src/engine/server/server.cpp
> +	str_format(aDemoName, sizeof(aDemoName), "%s [128 player BETA]", Config()->m_SvName);
Same.

2024-08-05 16:48 UTC, heinrich5991 commented on src/engine/server/server.cpp
> +	str_format(aDemoName, sizeof(aDemoName), "%s [128 player BETA]", Config()->m_SvName);
Here, too.

2024-08-05 16:48 UTC, heinrich5991 commented on src/game/server/gamecontext.h
> +	CSnapContext(int Version, bool Sixup = false, int ClientId = -1) :
Could you make the parameters non-optional? It seems like `ClientId` isn't amazing for the snap context here, perhaps pass the player mapping directly?

2024-08-05 16:48 UTC, heinrich5991 commented on src/game/server/gamecontext.h
> +	bool FlagsUsed() const;
That seems like dead code for DDNet.

2024-08-05 16:48 UTC, heinrich5991 commented on src/game/server/playermapping.h
> +		enum SSeeOthers
```suggestion
		enum class ESeeOthers
```

2024-08-05 16:48 UTC, heinrich5991 commented on src/game/server/playermapping.cpp
> +	if(Rejoin)
Why is `Rejoin` relevant here?

2024-08-05 16:48 UTC, heinrich5991 commented on src/game/server/playermapping.cpp
> +// made by fokkonaut
```suggestion
```
We don't really have such author notices in our code.

2024-08-05 16:48 UTC, heinrich5991 commented on src/game/server/playermapping.cpp
> +			mem_zero(&Addr, sizeof(OwnAddr));
```suggestion
			mem_zero(&Addr, sizeof(Addr));
```

2024-08-05 16:48 UTC, heinrich5991 commented on src/game/server/playermapping.cpp
> +	while(true)
```suggestion
	while(!Break)
```
or
```suggestion
	while(!Finished)
```

2024-08-05 16:48 UTC, heinrich5991 commented on src/game/server/playermapping.h
> +class CPlayerMapping
Can there be a comment on how this class generally works? It seems to have a player mapping for each IP address, and updates it based on some stuff.

2024-08-05 16:48 UTC, heinrich5991 commented on src/game/server/playermapping.h
> +	struct PlayerMap
```suggestion
	struct CPlayerMap
```

2024-08-05 16:48 UTC, heinrich5991 commented on src/engine/server/server.h
> +	bool IsDebugDummy(int ClientId) const override { return ClientId != SERVER_DEMO_CLIENT && m_aClients[ClientId].m_DebugDummy; }
Why do we care about this outside the engine? Could we simply remove this function?

2024-08-05 16:48 UTC, heinrich5991 commented on src/engine/shared/protocol.h
> +	MSGFLAG_NONAME = 64,
Seems unused?

2024-08-05 16:48 UTC, heinrich5991 commented on src/engine/shared/protocol.h
> +	VERSION_DDNET_UNIQUE_TEAMS = 17030,
What's this?

2024-08-05 16:48 UTC, heinrich5991 commented on src/game/server/entities/character.cpp
> +	// translate id, if we are not in the map of the other person display us as weapon and our hook as a laser
I think I'd prefer to not show a tee as a weapon if there are more than 64 players in range. That looks weird IMO.

2024-08-05 17:47 UTC, Robyt3 requested changes

2024-08-05 17:47 UTC, Robyt3 commented on src/engine/server.h
> +	int SendPackMsgTranslate(const protocol7::CNetMsg_Sv_Chat *pMsg, int Flags, int ClientID)
`ID` -> `Id`

Also in various other places. Especially the existing code shouldn't be changed back to the wrong naming by this.

2024-08-05 17:47 UTC, Robyt3 commented on src/engine/server/server.cpp
> +		id = -1;
```suggestion
	std::fill(std::begin(m_aIdMap), std::end(m_aIdMap), -1);
	std::fill(std::begin(m_aReverseIdMap), std::end(m_aReverseIdMap), -1);
```

2024-08-05 17:47 UTC, Robyt3 commented on src/game/server/gamecontext.h
> +	int GetCid() const { return m_ClientId; }
`GetClientId` or `ClientId`

2024-08-05 17:47 UTC, Robyt3 commented on src/game/server/gamecontroller.h
> +	int GetGameFlags() { return m_GameFlags; }
Unused for DDNet, same as `FlagsUsed`.

2024-08-06 06:17 UTC, fokkonaut commented on src/engine/server.h
> +	inline int SendPackMsgForce(const T *pMsg, int Flags, int ClientId)
Sure

2024-08-06 06:22 UTC, fokkonaut commented on src/engine/server.h
> +	 * SendPackMsg, but send to both 0.6 and 0.7 players, not just one of them
I don't remember exactly, will look into it later again, but I know there was some kind of is_sixup mapping, which I didn't wanna fiddle with for now. That's why I made this to get it to work quickly

2024-08-06 06:23 UTC, fokkonaut commented on src/game/server/gamecontext.h
> +	CSnapContext(int Version, bool Sixup = false, int ClientId = -1) :
Not entirely sure what you mean, but we can figure it out

2024-08-06 06:25 UTC, fokkonaut commented on src/game/server/playermapping.cpp
> +	if(Rejoin)
Not entirely sure anymore, I think it was to remove old clients laying around. There was probably some case in F-DDrace where I needed that

2024-08-06 06:26 UTC, fokkonaut commented on src/game/server/playermapping.h
> +class CPlayerMapping
Sure

2024-08-06 06:27 UTC, fokkonaut commented on src/engine/shared/protocol.h
> +	VERSION_DDNET_UNIQUE_TEAMS = 17030,
It's the golden angle thing, to get the correct team color for the see others feature

2024-08-06 06:29 UTC, fokkonaut commented on src/game/server/entities/character.cpp
> +	// translate id, if we are not in the map of the other person display us as weapon and our hook as a laser
My playermapping sadly doesn't send the closest players only yet, instead due to 0.7 connections which need a whole big netmsg I wanted to reduce the amounts of changes. Thus I only update when a player is in view which wasn't in view before, basically. With more than 64p in view it doesn't map the closests only. Also, iirc there's one bug left where sometimes a player nearby can be overridden, and for some reason he won't be re-inserted until he's out of your view range once (e.g. when using /pause, moving cursor away, resume)

2024-08-06 12:54 UTC, def- commented on src/engine/shared/protocol.h
> +	MSGFLAG_NONAME = 64,
```
if(*pId >= 0 && ((Flags & MSGFLAG_NONAME) || (MsgCopy.m_Mode == protocol7::CHAT_TEAM && *pId != ClientId) || MsgCopy.m_Mode == WhisperRecv || !Translate(*pId, ClientId)))
```

2024-08-06 13:08 UTC, fokkonaut commented
@def- What is left now after your force-push?

2024-08-06 15:41 UTC, def- commented on src/game/server/entities/character.cpp
> +	// translate id, if we are not in the map of the other person display us as weapon and our hook as a laser
@fokkonaut This is unresolved

2024-08-06 15:41 UTC, def- commented on src/engine/server.h
> +	 * SendPackMsg, but send to both 0.6 and 0.7 players, not just one of them
@fokkonaut This is unresolved

2024-08-06 15:41 UTC, def- commented on src/game/server/playermapping.h
> +class CPlayerMapping
@fokkonaut This is unresolved

2024-08-13 10:03 UTC, heinrich5991 commented on src/engine/shared/protocol.h
> +	VERSION_DDNET_UNIQUE_TEAMS = 17030,
I think we don't need to special-case old versions just to get a specific color.

2024-08-13 21:52 UTC, sjrc6 commented
what will happen if a 128 player demo is opened on a 64 player client?

2024-08-14 07:03 UTC, def- commented
We should bump the demo version so that it can't be opened.

2024-08-23 23:24 UTC, 0xfaulty commented on src/game/server/playermapping.cpp
> +				GameServer()->m_apPlayers[i]->m_aStrongWeakId[Id] = StrongWeakId;
@fokkonaut access violation on version >= 19000 as m_aStrongWeakId size is LEGACY_MAX_CLIENTS (64). So Translate of Id >= 64 return same number and lead to out of bounds.

2024-08-29 16:04 UTC, Robyt3 commented
> what will happen if a 128 player demo is opened on a 64 player client?

The players with ID >= 64 are simply ignored by the client, same as for snap objects with invalid client IDs while connected to a server.

2024-11-22 16:22 UTC, closed without merging