Scoreboard spectator clans
ddnet/ddnet pull request #8577
Opened 2024-07-10 19:18 UTC by gerdoe-jr

- Added `cl_spec_clan_color` and `cl_show_spec_clans` config variables
- Added color picker and checkbox in settings (`Appearance`->`HUD` and `Appearance`->`Name plates`)
- Added functionality for rendering spectator

![screenshot](https://media.discordapp.net/attachments/1177692308355940413/1260676184543334481/screenshot_2024-07-10_21-55-01.png?ex=66902fb0&is=668ede30&hm=b862c9e26dba81b79e612cdd5b852402615194aef8dd33bfb2bf5b823ef3ee1e&=&format=webp&quality=lossless)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-07-10 19:39 UTC, Robyt3 requested changes

2024-07-10 19:39 UTC, Robyt3 commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_COL(ClSpecClanColor, cl_spec_clan_color, 179, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Clan color of spectators in scoreboard.")
This config variable seems unnecessary to me. The default light gray should work for everyone.

2024-07-10 19:39 UTC, Robyt3 commented on src/game/client/components/scoreboard.cpp
> +				TextRender()->TextEx(&Cursor, aClientClan);
The separate buffer and `str_format` are unnecessary. Call `TextEx` twice to concatenate text of the same cursor.

```cpp
TextRender()->TextEx(&Cursor, pClanName);
TextRender()->TextEx(&Cursor, " ");
```

2024-07-10 19:39 UTC, Robyt3 commented on src/game/client/components/scoreboard.cpp
> +			if(g_Config.m_ClShowSpecClans && *pClanName != '\0')
`pClanName[0] != '\0'` instead of `*pClanName != '\0'`

2024-07-10 19:39 UTC, Robyt3 commented on src/game/client/components/scoreboard.cpp
> +		{
The clan should be after the client ID.

2024-07-10 19:39 UTC, Robyt3 commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(ClShowSpecClans, cl_show_spec_clans, 0, 0, 1, CFGFLAG_SAVE | CFGFLAG_CLIENT, "Whether to show spectator clans in scoreboard")
`Whether to show spectators' clans in scoreboard`

2024-07-10 19:39 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +		DoButton_CheckBoxAutoVMarginAndSet(&g_Config.m_ClShowSpecClans, Localize("Show spectator clans in scoreboard"), &g_Config.m_ClShowSpecClans, &RightView, LineSize);
`Show spectators' clans in scoreboard`

2024-07-10 20:54 UTC, heinrich5991 requested changes
Please use the PR summary to describe a motivation for your pull request.

2024-07-10 22:23 UTC, gerdoe-jr commented on src/game/client/components/scoreboard.cpp
> +				TextRender()->TextEx(&Cursor, aClientClan);
Yeah, I just checked code below that actually does the same for client IDs, I thought it's a better approach

2024-07-10 22:25 UTC, gerdoe-jr commented on src/game/client/components/scoreboard.cpp
> +		{
It looks weird since you mess different text colors for a single spectator entry, imo

2024-07-10 22:28 UTC, gerdoe-jr commented
> Please use the PR summary to describe a motivation for your pull request.

Done

2024-07-11 14:23 UTC, Robyt3 commented on src/game/client/components/scoreboard.cpp
> +				TextRender()->TextEx(&Cursor, aClientClan);
To format the `int` the `str_format` is necessary, but in general `str_format` is pretty expensive and should be avoided when simpler string manipulation functions work.

2024-07-11 14:26 UTC, Robyt3 commented on src/game/client/components/scoreboard.cpp
> +		{
Seems confusing to me to format it as `Clan 42: Name` instead of `42: Clan Name`. Can you try both and send screenshots for comparison (with client IDs enabled)?

2024-07-13 10:11 UTC, gerdoe-jr commented on src/game/client/components/scoreboard.cpp
> +		{
![screenshot_2024-07-13_13-07-23](https://github.com/user-attachments/assets/13104530-026b-4142-88c6-c47f22015141)
![screenshot_2024-07-13_13-10-42](https://github.com/user-attachments/assets/54619a5a-2d80-4fc7-9028-d21af475d513)

2024-07-13 19:58 UTC, Robyt3 commented on src/game/client/components/scoreboard.cpp
> +		{
I prefer the variant with the client ID first.

2024-07-14 08:48 UTC, heinrich5991 commented
I don't think we should add a config option for this use case, but rather we should enable it for all players or not at all.

This is yet another option that isn't really meaningful. It occupies space in the options menu, too.

2024-07-15 20:18 UTC, CherryEx commented
I think this pr is for very specific use cases. And it makes the spectator panel too crowded/confusing.

2024-07-17 15:47 UTC, gerdoe-jr commented
> I think this pr is for very specific use cases. And it makes the spectator panel too crowded/confusing.

I can not always know if we have enough players for FW/CW since most of them are spectating current game on CTF/gCTF, instead I'm forced to check `Players` tab in overlay menu. Also I had many situations when player faked my mate and I couldn't know about it without talking directly to person in spectators

2024-07-18 23:55 UTC, CherryEx commented
> > I think this pr is for very specific use cases. And it makes the spectator panel too crowded/confusing.
> 
> I can not always know if we have enough players for FW/CW since most of them are spectating current game on CTF/gCTF, instead I'm forced to check `Players` tab in overlay menu. Also I had many situations when player faked my mate and I couldn't know about it without talking directly to person in spectators

Well generally this IS a specific use case. Most people don't really care about clans at all, and I think that's logical considering anyone can put any text in their clan and there's no verification on most source codes including ddnet. Also (I think) this will make the scoreboard show less amount of spectators.

I (personally) think it would be better if u make a config option that enables the use of "Same clan color" on spectator names.

2024-07-19 05:26 UTC, gerdoe-jr commented
> Well generally this IS a specific use case. Most people don't really care about clans at all, and I think that's logical considering anyone can put any text in their clan and there's no verification on most source codes including ddnet. Also (I think) this will make the scoreboard show less amount of spectators.

Well, DDNet client is full of random features like DDFat that got popular for no reason once and now is just gimmick. I see no point in discussing such an old issue that comes from Teeworlds itself, why was `Clan` field introduced then? Before 0.6 you could easily check if player is in clan (because name size was a bit bigger than today and players used it for both nickname and clan), various clients (Z-Pack, TDTW, Gamer, etc) had enhanced scoreboards with all info available (I guess because it's useless?)

> I (personally) think it would be better if u make a config option that enables the use of "Same clan color" on spectator names.

I have added such options, see https://github.com/ddnet/ddnet/pull/8577#issuecomment-2227269627

2024-07-19 09:31 UTC, CherryEx commented
> Well, DDNet client is full of random features like DDFat that got popular for no reason once and now is just gimmick. I see no point in discussing such an old issue that comes from Teeworlds itself, why was `Clan` field introduced then? Before 0.6 you could easily check if player is in clan (because name size was a bit bigger than today and players used it for both nickname and clan), various clients (Z-Pack, TDTW, Gamer, etc) had enhanced scoreboards with all info available (I guess because it's useless?)
> 

I didn't say it's useless, I just say it's not necessary to be in the spectator panel.
There are 4000~ players playing in DDrace servers right now, and less than 150 players on mods like dm,ctf,zcatch,fng,infclass
Maybe we need more feedback if this is not gonna have a settings option because it's gonna affect a lot of players.

2024-07-21 14:17 UTC, gerdoe-jr commented
> Maybe we need more feedback if this is not gonna have a settings option because it's gonna affect a lot of players.

For example, #5802 had visual changes that were discussed for long time and @VoxelDoesCode did the same at first - added options to turn off visual changes because they might be unusual for old players. @heinrich5991 stated
> I'm against more config options, especially those exposed to the UI.

And then after we got a lot of feedback from old russian community that disliked new animations and wanted old behaviour back - #5920 popped out of nowhere stating the same. But
> I don't think we need an option for this.

Do you really look at your `Spectators` tab so often that you want see plain old one forever? I don't remember checking it playing DDRace, but playing vanilla mods

2024-07-23 12:35 UTC, CherryEx commented
I just (personally) believe the spectator panel is not sorted/tidy enough to contain multiple information.
And with names and clans right next to each other, new players would also be confused.

2024-08-13 10:01 UTC, heinrich5991 commented
I squashed the commits.

2024-08-13 10:02 UTC, heinrich5991 approved these changes
Thanks!

2024-08-13 10:36 UTC, merged