Add ctrl+p editor prompt (quick actions)
ddnet/ddnet pull request #8618
Opened 2024-07-19 07:04 UTC by ChillerDragon

closes https://github.com/ddnet/ddnet/issues/7933
follow up to https://github.com/ddnet/ddnet/pull/8358

I only added a few actions for now because I don't think the prompt and all the actions belong together in one pr. I will contribute more actions as soon as the prompt it self is merged.

https://github.com/user-attachments/assets/dc4e184f-d955-4e8a-9d5e-0d350155644e

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-07-19 07:08 UTC, BlaiZephyr requested changes

2024-07-19 07:08 UTC, BlaiZephyr commented on CMakeLists.txt
> +    quick_actions.h
Multiple include

2024-07-19 07:09 UTC, ChillerDragon commented on CMakeLists.txt
> +    quick_actions.h
s

2024-07-19 07:10 UTC, ChillerDragon commented on CMakeLists.txt
> +    quick_actions.h
One header is the class that describes a quick action. And the other is the list of all registered quick actions.

2024-07-19 08:45 UTC, jxsl13 commented
can you remove the rounded corners at the top ._.

2024-07-20 11:01 UTC, BlaiZephyr commented on CMakeLists.txt
> +    quick_actions.h
why not quick_action_list.h then :P - i was tired and didn't even see the s. gg

2024-07-20 11:57 UTC, ChillerDragon commented on CMakeLists.txt
> +    quick_actions.h
Yea I agree the naming is not perfect. Not sure if adding "list" is any better tho.

2024-07-25 20:11 UTC, Robyt3 requested changes

2024-07-25 20:11 UTC, Robyt3 commented on src/game/editor/prompt.cpp
> +void CPrompt::OnRender(CUIRect View)
Regarding the layout, screenshot for reference:

![screenshot_2024-07-25_21-54-21](https://github.com/user-attachments/assets/70685989-c05c-4f64-b484-af38ecb5d3c1)

[As stated before](https://github.com/ddnet/ddnet/pull/8358#discussion_r1672692865), it shouldn't be rendered over the map view. Sorry, I didn't see your response to my comment before.

> Whats wrong with rendering over the map view? Thats seems to be the intended way to use the component system.

The issue with rendering over the map view is that it looks weird and depending on the configuration makes it very hard to use the prompt feature:

![screenshot_2024-07-25_21-58-00](https://github.com/user-attachments/assets/626543fc-421a-4fb7-a329-8842f58a88f1)

It also looks better like a regular modal dialog with the darker background overlayed over the rest of the UI.

The map settings error dialog is also rendered like a dialog in `CEditor::RenderMapSettingsErrorDialog` not with the component `OnRender` function, so I think this is the intended way to render modal dialogs that don't overlay each other.

The text input should have the same height as the other editor buttons in the menu bars for consistency, it doesn't need to be so large.

The description text is currently hard to read due to the low contrast, both for the selected and unselected entries.

The margins on the left and right sides should also be consistent.

2024-08-05 00:30 UTC, ChillerDragon commented
Fixed the prompt overlay. Now looks like this:

![image](https://github.com/user-attachments/assets/3ddb465d-9237-422d-87d8-a2cb97346d48)

![image](https://github.com/user-attachments/assets/03e0d77b-ea02-4d01-9c2e-dead24425e5a)

2024-08-05 03:56 UTC, ChillerDragon commented
Fuzzy match is not perfect yet. It only filters it does not sort yet. There should be some sense of score.

![image](https://github.com/user-attachments/assets/2bbe3373-d53b-48c3-9eaa-11f9ce636aa3)


Searching "roo" should for sure put "Proof" on the first hit.

2024-08-05 05:47 UTC, ChillerDragon commented
There is still no sense of score but that should be fine I think. I fixed the specific "Proof" case yielding too many results because duplicated letters were not strictly checked. Now `roo` only finds `Proof`

![image](https://github.com/user-attachments/assets/50952ab1-c88c-4138-86f1-92c316def14c)

2024-08-05 07:13 UTC, ChillerDragon commented
I added the first action that can be in state disabled. One can now select a mapres for a tile layer without using the mouse.
But the option will only be listed if a tile layer is selected (no game layer).


https://github.com/user-attachments/assets/c5698231-2117-4e38-8458-dc3675518856

2024-08-31 13:59 UTC, ChillerDragon commented
Solved conflicts with master. Still waiting for a review (since last month) and ready to be merged from my side.

2024-08-31 18:18 UTC, Robyt3 approved these changes

2024-08-31 21:33 UTC, def- approved these changes

2024-08-31 22:03 UTC, merged