Spawn a confetti when connecting on your DDNet birthday
ddnet/ddnet pull request #8715
Opened 2024-08-12 21:15 UTC by furo321

https://github.com/user-attachments/assets/dda6f5b3-a87a-4d1e-8c13-54957441d22c

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-08-12 21:40 UTC, def- requested changes

2024-08-12 21:40 UTC, def- commented on src/game/server/player.cpp
> +				GameServer()->CreateFinishConfetti(GetCharacter()->m_Pos, GetCharacter()->TeamMask());
I guess you should rename it from `FinishConfetti` to `Confetti` at this point ;)

2024-08-13 00:34 UTC, ChillerDragon commented on src/game/server/player.cpp
> +				GameServer()->CreateFinishConfetti(GetCharacter()->m_Pos, GetCharacter()->TeamMask());
Well the net message is called `finish@netevent.ddnet.org` and heinrich said it can be replaced with another effect any time. [Avo, kaffeine and me](https://github.com/ddnet/ddnet/pull/8406#issuecomment-2135614567) disagreed with that. But thats how it got merged and released already.

Meaning if we stick to that logic this pr is wrong. And should create a new net message called `birthday@netevent.ddnet.org` which then could trigger the same animation.

2024-08-13 08:22 UTC, def- commented on src/game/server/player.cpp
> +				GameServer()->CreateFinishConfetti(GetCharacter()->m_Pos, GetCharacter()->TeamMask());
Yeah, I agree with you guys, but now it's already called that. Not worth doing a rename.

2024-08-13 08:22 UTC, def- approved these changes

2024-08-13 08:35 UTC, Kaffeine commented on src/game/server/player.cpp
> +				GameServer()->CreateFinishConfetti(GetCharacter()->m_Pos, GetCharacter()->TeamMask());
<s>Oh wow, DDNet decision against mods</s> hit DDNet.

Compared to `birthday@netevent.ddnet.org`, using `Confetti` and `confetti@particles.ddnet.tw` is still an easier solution, which would allow mods to use it.

DDNet also can use the more abstract [`CreateParticles` net messages](https://github.com/ddnet/ddnet/pull/8406#issuecomment-2136767405) (yet to be developed) but we have what we have in terms of DDNet decisions and external contribution.

2024-08-13 08:40 UTC, merged

2024-08-13 08:45 UTC, Kaffeine commented
You can't replace `finish@netevent.ddnet.org` event Confetti animation with another finish animation (e.g. waving flag :checkered_flag: ) anymore (welp, you haven't release this yet but who cares).

2024-08-13 11:06 UTC, ChillerDragon commented
:confused: well now we have an inconsistent mix. There is heinrich who wants the event naming based on for what the event is used and then there is the other camp who wants the events named after what they display so it is cleaner for custom mods.

And now its mixed so its a bit wrong for both sides.

2024-08-13 11:17 UTC, def- commented
Let's call it `maybefinishmaybeconfetti@netevent.ddnet.org`

2024-08-13 11:17 UTC, heinrich5991 commented
@Kaffeine @ChillerDragon Already fixed in #8717.