Fix cutting 0.6 demos
ddnet/ddnet pull request #8754
Opened 2024-08-17 02:50 UTC by ChillerDragon

Closed #8748

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-08-17 08:52 UTC, Robyt3 requested changes

2024-08-17 08:52 UTC, Robyt3 commented on src/engine/shared/demo.cpp
> +	DemoPlayer.SetSixup(str_startswith(pInfo->m_Header.m_aNetversion, "0.7"));
It seems prone to errors to have to do this manually. `CDemoPlayer::m_Sixup` is generally uninitialized, so forgetting to use `SetSixup` on a demo player causes undefined behavior during playback. The same would be missing in the `demo_extract_chat` tool for example.

This should rather happen automatically in `CDemoPlayer::Load`, when the header has been loaded. The client should update its own `m_Sixup` with `m_Sixup = m_DemoPlayer.IsSixup()` and `CDemoPlayer::GetSixup` should be removed.

2024-08-18 02:10 UTC, ChillerDragon commented
After adding rossbits feedback I tested cutting and playing back two slices of 0.6 and 0.7 demos. Everything was smooth.

2024-08-18 06:29 UTC, def- approved these changes

2024-08-18 06:46 UTC, merged