Implement 0.7 delete skin button
ddnet/ddnet pull request #8755
Opened 2024-08-17 03:13 UTC by ChillerDragon

See #8750

https://github.com/user-attachments/assets/e451ebbe-9e0f-4b23-90d9-a3e68549b5e8

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-08-17 08:41 UTC, Robyt3 requested changes

2024-08-17 08:41 UTC, Robyt3 commented on src/game/client/components/menus_settings7.cpp
> +	if(m_pSelectedSkin)
Assert that this is not `nullptr` instead of ignoring. It's a programming mistake if the skin is not set while the popup is confirmed.

2024-08-17 08:41 UTC, Robyt3 commented on src/game/client/components/menus_settings7.cpp
> +			PopupMessage(Localize("Error"), Localize("Unable to delete the skin"), Localize("Ok"));
I think most of this should be moved inside the `CSkins7::RemoveSkin` function for better separation of concerns. This function is only used once, here, and then you wouldn't need to expose the `SKINS7_DIR` define and how skin filenames are constructed for the `PopupConfirmDeleteSkin7` function. I'd keep only the error handling here, so the code here would look like this:

```cpp
if(m_pClient->m_Skins7.RemoveSkin(m_pSelectedSkin))
{
	m_pSelectedSkin = nullptr;
}
else
{
	PopupMessage(Localize("Error"), Localize("Unable to delete the skin"), Localize("Ok"));
}
```

(i.e., let the `RemoveSkin` function return `true` on success)

2024-08-18 02:21 UTC, ChillerDragon commented
Feddback implemented and retested.

2024-08-18 06:43 UTC, def- approved these changes

2024-08-18 07:08 UTC, merged