Add confirm when Lock Team
ddnet/ddnet pull request #8792
Opened 2024-08-23 12:43 UTC by Manki233

It's will tips `Your team is (un)locked by [Locker Player], If you wan't to (un)lock team, Please wait for a second and repeat the command.` when 2 player in a team and they execute `/lock`  together It can prevent situations where several people want to lock the team, but in the end, they execute 'lock' together.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-08-23 12:51 UTC, Bamcane requested changes
I think maybe `'%s' wants to %s your team, wait for a second and repeat the command /%s to confirm it` (first `%s` is the caller, last are 'unlock/lock') is more better.

And others:

2024-08-23 12:55 UTC, Bamcane commented on src/game/server/ddracechat.cpp
Seemed that there is only `ConLock` has changed, but there is a `ConUnlock` function hasn't changed

2024-08-23 12:56 UTC, Bamcane commented on src/game/server/ddracechat.cpp
> +	if (Teams -> m_aLastLocker[Team] != pResult->m_ClientId)
This is not DDNet code style i think

2024-08-23 13:01 UTC, Manki233 commented on src/game/server/ddracechat.cpp
`Unlock`'s target is clear. When used together by multiple people, there will be no confusion.

2024-08-23 13:48 UTC, furo321 commented on src/game/server/ddracechat.cpp
The intent is also clear if you use `/lock 0` and  `/lock 1`,  and should therefore also bypass the confirmation.

2024-08-23 13:52 UTC, Manki233 commented on src/game/server/ddracechat.cpp
> The intent is also clear if you use and , and should therefore also bypass the confirmation`/lock 0``/lock 1`.

ok, done.

2024-08-23 16:41 UTC, BlaiZephyr commented on src/game/server/ddracechat.cpp
> +				"Your team is %s by %s, Please wait for a second and repeat /%s if you want to %s your team.",
you could theoretically move the ternary operator into the str_format instead of declaring it as a variable but that might make it to long i assume - could we still atleast agree on a better name than pLoUL please :P 

I personally also dislike how the string is formatted in general:

"your team is %s by %s" <- why do i need to know who locked/unlocked it
"Please wait for a second and repeat /%s" <- why do i need to know the command i just tried to execute
"if you want to %s your team." <-the intend is clear when i try to execute this command so i'm not sure why we'd specify that

it also feels weird to me having all that logic just in ConLock given it handles the case of wanting to unlock aswell

2024-08-23 17:39 UTC, Chairn commented
This is useless.

Use `/lock 1` to lock and `/lock 0` or `/unlock` to unlock.

2024-08-23 17:39 UTC, closed without merging

2024-08-24 11:21 UTC, Jupeyy commented
@Manki233 it's really nice that you put so much effort to try improving the game with your last two pull requests.
If you have other ideas, maybe you could open an issue and discuss them first. All changes directly have an impact on all players, so usually having pros and cons to evaluate if the feature is _really_ worth it can't hurt.

If a feature clearly shows that it is a good addition for the game it has a high chance to be merged and your effort does not feel so wasted.
I hope you understand that, and you can share more of your ideas.