Add a popup for picking a map for background entities setting
ddnet/ddnet pull request #8803
Opened 2024-08-24 17:10 UTC by furo321

https://github.com/user-attachments/assets/29937a4a-980f-4eea-b81d-51a72b942196

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-08-24 19:30 UTC, Robyt3 requested changes

2024-08-24 19:30 UTC, Robyt3 commented on src/game/client/components/menus.h
> +	struct SPopupMapPickerContext
`struct`s should not be used anymore in new code, see #5338

2024-08-24 19:30 UTC, Robyt3 commented on src/game/client/components/menus.h
> +	static bool CompareFilenameAscending(const SMapListItem pLhs, const SMapListItem pRhs)
The arguments should be const references without prefix `p`.

2024-08-24 19:30 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +				str_format(pMenus->m_aCurrentMapFolder, sizeof(pMenus->m_aCurrentMapFolder), "%s/%s", aTemp, SelectedItem->m_aFilename);
The variable `aTemp` and the `str_copy` seem unnecessary, you can `str_append` instead to avoid the `str_format`.

2024-08-24 19:30 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +		SMapListItem *SelectedItem = &pMenus->m_vMaps.at(pPopupContext->m_Selection);
Use a (const) reference instead of a pointer. Use `[]` instead of `at`. (The name would be wrong for a pointer also.)

2024-08-24 19:30 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +	for(size_t i = 0; i < pMenus->m_vMaps.size(); ++i)
I think a for-each loop looks cleaner. You can use a separate variable to keep track of the map index.

Alternatively, add a variable for the current element instead of using `[]` (or calling `at`) multiple times.

2024-08-24 19:30 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +		pMenus->Ui()->DoLabel(&Label, aLabelText, 10.0f, TEXTALIGN_LEFT);
Use `TEXTALIGN_ML` to ensure it's centered vertically. The text align constants that only specify one dimension should only be used internally.

2024-08-24 19:30 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +		static SPopupMenuId s_PopupMapPickerId;
Let `SPopupMapPickerContext` override `SPopupMenuId` so the separate ID is unnecessary (see for example `SColorPickerPopupContext`).

2024-08-24 19:30 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +		CUIRect Label;
You could also add icons like in the editor file browser for the parent folder, regular folders and maps.

2024-08-24 19:30 UTC, Robyt3 commented on src/game/client/components/menus.h
> +	void MapListPopulate();
I'd also make these members of popup context, since they should only be used together with the popup and it would otherwise break if there were multiple of this popup open at the same time.

2024-08-24 20:24 UTC, furo321 commented
Thanks for review, fixed! Here is how it now looks with icons.

![image](https://github.com/user-attachments/assets/de744091-a0e4-49fa-aa4b-e1f5e8bd48d6)

2024-08-25 10:00 UTC, Robyt3 approved these changes
Looks good, thanks!

2024-08-25 10:19 UTC, merged