Allow reloading current background entities map
ddnet/ddnet pull request #8806
Opened 2024-08-25 11:04 UTC by bencie

This check never really made sense to me, as if you're editing your background entities map, you'd have to pick a different map and re-pick your previous one to see the changes you made in game. Now that it's a reload button, and not an input box, it should especially reload the map when clicked.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-08-25 11:09 UTC, Jupeyy commented
maybe some ppl use a bind that changes the background map. so there it could make sense.

for the reload button it sounds useless indeed

2024-08-25 11:14 UTC, Robyt3 requested changes
Remove the `UpdateBackgroundEntities` function entirely. For the buttons, use `m_pClient->m_Background.LoadBackground();` directly since those should always update the map. For the conchain, keep the check so the map is not reloaded unless the value of the config variable changed, or this causes massive lags with binds that set the background map.

2024-08-25 12:56 UTC, Robyt3 commented
Looks good, can you squash the commits?

2024-08-26 15:04 UTC, Robyt3 approved these changes

2024-08-26 15:23 UTC, merged