Add `hot_reload` to reload map while preserving state
ddnet/ddnet pull request #8813
Opened 2024-08-26 14:51 UTC by furo321

Add `hot_reload` to reload map while preserving the state of tees, teams and switches. The editor will now also run this command on save instead of `reload`. Closes #585

https://github.com/user-attachments/assets/199963f8-c57e-41ca-8073-568ead3139f5

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-08-26 15:17 UTC, def- approved these changes
Very cool!

2024-08-26 16:03 UTC, edg-l approved these changes

2024-08-26 21:02 UTC, Robyt3 requested changes

2024-08-26 21:39 UTC, furo321 commented
Thanks, fixed!

2024-08-26 22:17 UTC, def- approved these changes

2024-08-27 00:47 UTC, ChillerDragon commented
Could we get some game controller hook for other gamemodes than ddrace that also want to save some state?

2024-08-27 01:04 UTC, furo321 commented
> Could we get some game controller hook for other gamemodes than ddrace that also want to save some state?

Not exactly sure how I would implement that. So, you would have to make that yourself.

2024-08-27 03:45 UTC, ChillerDragon commented
I can do it my self for sure don't worry about it @furo321.

Since that would be blocked on #7777 I would like to get a maintainers opinion on it. Imo a mod with for example flags should also be able to restore the flag positions in the mod controller.

2024-08-27 07:21 UTC, merged