Update translations for 18.5, remove 0.7-only translations
ddnet/ddnet pull request #8821
Opened 2024-08-27 09:46 UTC by def-

Fix some minor stuff

0.7 translations are a lot of effort for something most players will never see. They also have weird constracts like `"'%s' %sjoined the game"`

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-08-27 17:03 UTC, Robyt3 requested changes

2024-08-27 17:03 UTC, Robyt3 commented on data/languages/belarusian.txt
> -An error during command recording occurred. Try to update your GPU drivers.
Could you try fixing this manually by adding the missing context `[Graphics error]` before this translation? This otherwise removes the correct translations for the other graphics errors and adds them below without translation.

2024-08-29 07:38 UTC, def- commented on data/languages/belarusian.txt
> -An error during command recording occurred. Try to update your GPU drivers.
I think the contexts are totally broken and every rerun of the update script will lose some translations. I couldn't understand the reason last time I looked (probably a year ago)

2024-08-29 07:53 UTC, Robyt3 approved these changes

2024-08-29 08:29 UTC, merged