Update ukrainian.txt
ddnet/ddnet pull request #8854
Opened 2024-08-31 10:52 UTC by Veydzher

Updated some punctuation mistakes and improved some. Tested in the game.

2024-08-31 20:32 UTC, Jupeyy commented on data/languages/ukrainian.txt
> +# veydzh3r      (31/08/2024 - present)
why present? do you update it in every Planck time unit ever xd

2024-08-31 21:36 UTC, def- approved these changes

2024-08-31 21:41 UTC, Veydzher commented on data/languages/ukrainian.txt
> +# veydzh3r      (31/08/2024 - present)
idk, i would make some changes in soon, so I put "present" xD

2024-08-31 21:42 UTC, def- commented
@EGYT5453 Is this actually better?

2024-08-31 21:54 UTC, EGYT5453 requested changes
Досить непогано, але потрібні невеличкі корекції, що зазначені у коментарях

2024-08-31 21:54 UTC, EGYT5453 commented on data/languages/ukrainian.txt
> +== за стандартом
"За стандартом", на мою скромну думку, не дуже гарний переклад "[by] default", хоча "за замовчуванням" теж такий собі. Натомість, краще перекласти як "типово", "початкові значення" (https://onlinecorrector.com.ua/uk/типовий-стандартний-основний)

2024-08-31 21:54 UTC, EGYT5453 commented on data/languages/ukrainian.txt
> +== EUR
Тут краще залишити як було

2024-08-31 21:54 UTC, EGYT5453 commented on data/languages/ukrainian.txt
> +== Інформаційні повідомлення
Див. `Sat.`

2024-08-31 21:54 UTC, EGYT5453 commented on data/languages/ukrainian.txt
> +== Чутливість в інтерфейсі
Див. `Sat.`

2024-08-31 21:54 UTC, EGYT5453 commented on data/languages/ukrainian.txt
> +== Рядки %d — %d (%s)
https://uk.wikipedia.org/wiki/Тире
> В українській типографіці, якщо тире вживають для позначення діапазону, його не виокремлюють пробілами, а практично в усіх інших випадках — відокремлюють

2024-08-31 21:54 UTC, EGYT5453 commented on data/languages/ukrainian.txt
> +== Завантаження демо-файла зі сховища
демо-файлу*

2024-08-31 21:54 UTC, EGYT5453 commented on data/languages/ukrainian.txt
>  == нічим, за що можна зачепитися
Так як ` Tee` було відредаговано так, що рядок тепер починається з великої літери, тут треба зробити так само. Те ж саме і з `Something hookable`

2024-08-31 21:54 UTC, EGYT5453 commented on data/languages/ukrainian.txt
> +== Непрозорість
Див. `Sat.`

2024-08-31 21:54 UTC, EGYT5453 commented on data/languages/ukrainian.txt
> +== Павза
Серйозно? :roll_eyes:

2024-08-31 21:54 UTC, EGYT5453 commented on data/languages/ukrainian.txt
> +== Повторне під’єднання за %d сек.
Після одиниць вимірювання крапка не ставиться, і вони не відокремлюються пробілом, а "секунда" скорочується до "с"

2024-08-31 21:54 UTC, EGYT5453 commented on data/languages/ukrainian.txt
> +== Частота оновлення
Див. `Sat.`

2024-08-31 21:54 UTC, EGYT5453 commented on data/languages/ukrainian.txt
> +== Економія енергії шляхом зниження частоти оновлення (вища затримка введення)
Див. `Sat.`

2024-08-31 21:54 UTC, EGYT5453 commented on data/languages/ukrainian.txt
> +== Показувати сутності
Див. `Sat.`

2024-08-31 21:57 UTC, EGYT5453 commented
@def- in some places it is better (like sentences with "ing"), some are just okay (changing every `'` to `’` and `"` to `«»`), and some, in my opinion, can have some improvements (like places where the string does not fit)

2024-09-01 07:14 UTC, Veydzher commented
alright, I would go trough the strings commented by @EGYT5453 and change them. Thx for explaining, @EGYT5453.

2024-09-01 07:29 UTC, Veydzher commented on data/languages/ukrainian.txt
> +== Повторне під’єднання за %d сек.
Бачив правило щодо крапок після символів CI, але про непотрібність пробілу між ними ні. Можете скинути джерело про це?

2024-09-01 07:34 UTC, def- commented
@Veydzher Can you incorporate EGYT5453's suggestions into this PR?

2024-09-01 08:01 UTC, Veydzher commented
@def- Sure, I'm working on it now.

2024-09-01 08:14 UTC, Veydzher commented on data/languages/ukrainian.txt
> +== за стандартом
замінив на «типово»

2024-09-01 08:15 UTC, Veydzher commented on data/languages/ukrainian.txt
> +== Насиченість
позменшував до ваших попередніх форм.

2024-09-01 08:15 UTC, Veydzher commented on data/languages/ukrainian.txt
> +== Таблиця
замінив

2024-09-01 08:15 UTC, Veydzher commented on data/languages/ukrainian.txt
> +== Тека ресурсів
повернув назад «текстур»

2024-09-01 08:44 UTC, EGYT5453 requested changes
Добре, але є ще одна річ, яку я не помітив минулого разу: у рядку `Show client IDs (scoreboard, chat, spectator)` "спостерігачі" було пропущено (і, можливо, у інших рядках теж), тоді як рядки `Spectators` та `Spectator mode` було перекладено як "Глядачі" та "Режим глядача" відповідно.

2024-09-01 08:44 UTC, EGYT5453 commented on data/languages/ukrainian.txt
> +== Показувати ID клієнта (таблиця, чат, спостерігачі)
Тут вже я пропустив "спостерігачів", коли перевіряв. Як я розумію, їх заміняємо на "глядачів"?

2024-09-01 08:49 UTC, EGYT5453 commented
Noticed one little thing I didn't notice yesterday (because I started reviewing it somewhere at 23:30 (11:30PM) and finished at 01:00 (AM))

2024-09-01 08:55 UTC, EGYT5453 commented
О, і ще дещо: "стандартного рушія" у рядку `Не вдалося ініціалізувати заданий графічний рушій, повертаємося до стандартного рушія.` можна замінити на "типового рушія", як і "Стандартні очі" у `Стандартні очі під час приєднання до сервера` — на "Типові очі". У рядку `Ви дійсно хочете скинути налаштування керувань до стандартних значень?` "стандартних значень", натомість, можна замінити на "початковий значень".

2024-09-01 09:02 UTC, Veydzher commented on data/languages/ukrainian.txt
> +== Показувати ID клієнта (таблиця, чат, спостерігачі)
так, вже змінюю.

2024-09-01 09:24 UTC, EGYT5453 requested changes
Ох цей "Show client IDs (scoreboard, chat, spectator)", завжди з ним проблеми)

2024-09-01 09:24 UTC, EGYT5453 commented on data/languages/ukrainian.txt
> +== Показувати ID клієнта (таблиці, чату, глядачів)
Тут треба було залишити називний відмінок, так як перераховуються місця, де якраз відображається ID клієнта (таблиця, чат, глядачі)

2024-09-01 09:29 UTC, Veydzher commented on data/languages/ukrainian.txt
> +== Показувати ID клієнта (таблиці, чату, глядачів)
зрозумів)

2024-09-01 09:29 UTC, EGYT5453 approved these changes
Наче файно

2024-09-01 16:56 UTC, merged