Add `verify_url` field to master for automatic verification
ddnet/ddnet pull request #8900
Opened 2024-09-06 13:42 UTC by furo321

Not sure if it should be a config option, so that GER10 for example doesn't have to maintain it's own fork.

Closes #6808 Supersedes #8698

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-09-06 13:55 UTC, Jupeyy commented
Sadly #8210 was closed, which contained the actual discussion about a feature like that.

For example it's not clear to me whether this could violate GDPR. Additionally the URL in your patch can be random and thus can be used to create traffic on unrelated servers.

2024-09-06 14:05 UTC, def- approved these changes
There should be a config we can use for GER10

2024-09-06 14:07 UTC, Jupeyy commented
Would GER10 auth also work with a unsecure http request directly to the IP?
http://ip

2024-09-06 14:33 UTC, furo321 commented
> Additionally the URL in your patch can be random and thus can be used to create traffic on unrelated servers.

Seems quite hard to solve, this is also the case for custom map urls.

> Would GER10 auth also work with a unsecure http request directly to the IP?

No, `http://` is disabled by default. It can only be enabled with `http_allow_insecure 1`.

> There should be a config we can use for GER10

Added `sv_verify_url`.

2024-09-06 14:38 UTC, Jupeyy commented
> Seems quite hard to solve, this is also the case for custom map urls.

Since when do we have that? Yes that is also a problem.

2024-09-06 14:52 UTC, furo321 commented
> Since when do we have that? Yes that is also a problem.

#5829, it also acknowledges the various security problems with doing this.

2024-09-20 12:53 UTC, heinrich5991 requested changes
Thanks for the PR, I think something like this would be valuable.

I found a couple of things that need to be addressed, and some of them require thinking about a solution since I haven't provided one.

2024-09-20 12:53 UTC, heinrich5991 commented on src/engine/server/server.cpp
> +	JsonWriter.WriteStrValue(g_Config.m_SvVerifyUrl);
This should only be added if there's an actual verify URL. Not sure if the name `verify_url` is good though. Any ideas? It doesn't really verify anything.

2024-09-20 12:53 UTC, heinrich5991 commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_STR(SvVerifyUrl, sv_verify_url, 128, "", CFGFLAG_SERVER, "A URL which the client will send a HTTP GET request to upon connecting")
```suggestion
MACRO_CONFIG_STR(SvVerifyUrl, sv_verify_url, 128, "", CFGFLAG_SERVER, "A HTTPS URL which the client will send a HTTPS GET request to upon connecting")
```

2024-09-20 12:53 UTC, heinrich5991 commented on src/engine/shared/serverinfo.h
> +	char m_aVerifyUrl[128];
```suggestion
	bool m_VerifyUrlPresent;
	char m_aVerifyUrl[128];
```

2025-01-27 08:19 UTC, edg-l commented
iirc this is already in (or atleast ger doesnt require it) closing for now

2025-01-27 08:19 UTC, closed without merging