Change editor teleport number behavior
ddnet/ddnet pull request #8961
Opened 2024-09-16 01:32 UTC by KebsCS

Closes #7896
Now, each teleport number is separate. I also fixed inconsistencies with the number when switching it in the Tele popup. The number next to the brush now always matches the one being placed

![image](https://github.com/user-attachments/assets/169e9f03-96f7-4ca2-a8ba-9a77053a21ea)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-09-16 07:36 UTC, def- requested changes
Can you fix the style? https://github.com/ddnet/ddnet/actions/runs/10876292823/job/30176001184?pr=8961
The different text sizes don't look great to me, can we make the popup much wider?

2024-09-16 08:59 UTC, Robyt3 requested changes
I don't think most of the vectors are necessary as the number of tele numbers is fixed.

2024-09-16 08:59 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +	static std::vector<int> s_PreviousTeleNumbers;
The number of tele numbers is fixed (7) so fixed size arrays should be enough instead of vectors.

Naming: `s_aPreviousTeleNumbers` (array) or `s_vPreviousTeleNumbers` (vector)

2024-09-16 08:59 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +	std::vector<CUIRect> FindFreeTeleSlots;
Array instead of vector. Naming.

2024-09-16 08:59 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +		static std::vector<int> s_NextFreeTelePids;
Array instead of vector. Naming. Also change `Pids` to `ButtonIds`.

2024-09-16 08:59 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +			auto Tele = (*std::next(pEditor->m_TeleNumbers.begin(), i));
`TeleText` can be an array of some new wrapper class instead of a map, then this becomes a normal array access.

2024-09-16 08:59 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +		static std::vector<int> s_aIds;
Array instead of vector.

2024-09-25 23:15 UTC, KebsCS commented
@Robyt3 Done,

@def- new popup width
![image](https://github.com/user-attachments/assets/e25f4650-6bc0-4b47-aa5b-ffe0805cea34)

2024-10-09 17:48 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +		static const char *s_aTeleLabelText[] = {
`s_apTeleLabelText`

2024-10-09 22:04 UTC, KebsCS commented on src/game/editor/editor.h
> +	CProperty(std::nullptr_t) :
We need this for backward compatibility with CProperty in other files: `map_grid.cpp(127): error C2440: 'initializing': cannot convert from 'initializer list' to 'CProperty'`

2024-10-10 17:26 UTC, Robyt3 approved these changes

2024-10-10 17:48 UTC, merged