Save the config file when the app is minimized on Android
ddnet/ddnet pull request #8975
Opened 2024-09-17 20:21 UTC by furo321

Closes #8366

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-09-17 22:39 UTC, def- approved these changes

2024-09-18 09:33 UTC, Robyt3 requested changes
Tested, works on my phone. Config is always saved when pressing home key or opening the task view, so it should make it unlikely that the config is lost unless the process is killed while staying in the foreground. Minor nitpick below.

2024-09-18 09:33 UTC, Robyt3 commented on src/engine/client/input.h
> +#include <engine/config.h>
This include is unnecessarily heavy, you can add a forward declaration `class IConfigManager;` instead (next to `class IEngineGraphics;`).

2024-09-18 10:13 UTC, heinrich5991 approved these changes
Thanks for tackling this! :)

2024-09-18 10:27 UTC, Robyt3 approved these changes

2024-09-18 10:48 UTC, merged