Add quick action "Delete layer"
ddnet/ddnet pull request #8985
Opened 2024-09-18 12:44 UTC by ChillerDragon

I am not too sure about this one. This would be the first destructive quick action. Meaning one little typo or miss scroll could delete an entire layer by accident. The way the prompt is designed to be used this can happen way more likely than clicking the delete button. I am not sure how mature the undo feature is. Is it stable? Is it on by default? If we can rely on the undo feature to avoid data loss then this should be fine.

The other option would be introducing a "are you sure?" popup but that would then be in the way of "batch deletion"

https://github.com/user-attachments/assets/054766d5-7166-4d6c-87a1-0ff7e836dc74

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-09-18 23:56 UTC, ChillerDragon commented
https://github.com/user-attachments/assets/20dc63d0-f8a5-4220-a75a-d0bb32a93833

I added a confirm popup. Only to the quick action not to the button that was already there. This should make it safe enough. And it is still faster to delete multiple layers with that additional confirmation than with the mouse.

2024-09-19 06:14 UTC, def- commented
Why do we need it to be safe? Doesn't undo work?

2024-09-19 06:44 UTC, ChillerDragon commented
> Why do we need it to be safe? Doesn't undo work?

Maybe it does I never tested it. It's off on my system. I just really want to make sure to not destroy hours of work some mapper put into a layer that was deleted by accident.

2024-09-21 09:18 UTC, Robyt3 requested changes
I don't really think we need a popup. Undo/redo works, so the popup description is also wrong.

For comparison, I tried the prompt feature in Sublime Text and it did not ask me either before removing a package (although it's a two step process since you select the package also in the promp).

2024-09-21 09:18 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +	if(Input()->ShiftIsPressed())
Seems a bit weird how this function checks if shift is pressed but otherwise only does map related stuff. I'd maybe split it into two separate functions, one for expanding and one for setting the selection. These changes don't seem required for the delete quick action though.

2024-09-21 09:18 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +	if(Input()->ShiftIsPressed())
Same

2024-09-21 09:32 UTC, Robyt3 commented
> > Why do we need it to be safe? Doesn't undo work?
> 
> Maybe it does I never tested it. It's off on my system.

It's always enabled now, there is no option to disable undo/redo anymore. Although you could set `cl_editor_max_history` so only one history action would be saved instead of 50 by default, so you would lose changes after one further edit. There used to be an option to disable it when it was implemented rather crudely, as that was unstable and eventually removed entirely. The undo/redo feature now works for most actions except for those involving images and sounds AFAICT.

Note that if you are using a non-QWERTY keyboard, the Ctrl+Z and Ctrl+Y hotkeys will be moved/swapped.

2024-09-22 05:15 UTC, ChillerDragon commented on src/game/editor/editor.cpp
> +	if(Input()->ShiftIsPressed())
Done

2024-09-22 05:20 UTC, ChillerDragon commented
Reverted the confirmation popup. I really hope nobody loses some data because of it.

> Note that if you are using a non-QWERTY keyboard, the Ctrl+Z and Ctrl+Y hotkeys will be moved/swapped.

Ah yes thanks I am on QWERTZ. If I accidentally would have deleted a layer I put 20 minutes work into and then Ctrl+Z would not have worked I would have flamed in #developer channel and started all over again. Let's hope users know that they can revert the action.

> For comparison, I tried the prompt feature in Sublime Text and it did not ask me either before removing a package (although it's a two step process since you select the package also in the promp).

A package being something like an extension? I think deleting an unsaved file is more comparable than a package that can just be downloaded again.

2024-09-22 13:44 UTC, Robyt3 approved these changes

2024-09-22 14:49 UTC, merged