Show 0.7 servers in LAN serverbrowser
ddnet/ddnet pull request #8992
Opened 2024-09-19 11:06 UTC by MilkeeyCat

It already works. But I would like to know your opinion on code. One thing which is not implemented yet is removing connless packets from `m_ConnlessPackets` after some time. Maybe you have better ideas how to do it =]

If you think there's no way to make this code mergeable, lemme know I'll close the pr xd

closes #8920

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-09-19 11:21 UTC, MilkeeyCat commented
Yikes

2024-09-19 11:37 UTC, MilkeeyCat commented
Easy first try

2024-09-19 11:56 UTC, ChillerDragon reviewed
Amazing thanks @MilkeeyCat for working on this! I would have never had the energy to look into it.

2024-09-19 11:56 UTC, ChillerDragon commented on src/engine/shared/network.h
> +	void CheckConnlessPackets(NETADDR *pAddr, SECURITY_TOKEN Token);
Heinrich probably wants this to be called ``CheckConnlessPackets7`` he once mentioned everything 0.7 related should have a 7 suffix.

2024-09-19 11:56 UTC, ChillerDragon commented on src/engine/client/client.cpp
> +void CClient::PreprocessConnlessPacket(CNetChunk *pPacket)
I am not a maintainer so my opinions don't really matter lol.

But I think it would be nice to move this entire method in some translation file so it does not pollute the 0.6 code. Search for sixup and translation in files there might be some candidates to move it to.

2024-09-24 13:37 UTC, jxsl13 commented
nooo, @MilkeeyCat

2024-09-25 10:40 UTC, MilkeeyCat commented
I'm sorry for being little bitch

2024-11-15 08:30 UTC, MilkeeyCat commented
@Robyt3 Could you take a look at this pr when you are free, please?

2024-11-15 13:31 UTC, ChillerDragon requested changes
Works on my machine. Tested it with two 0.7 servers and one ddnet server. It correctly managed to display the mix of 0.6 and 0.7 servers. Also the 0.7 player score was reported correctly.

The code looks fine to me. But tbh I did not bother to fully understand everything. I pointed out a few nit picks but the only thing that is blocking the merge IMO is the ``NullAddr.type = 7;``.

2024-11-15 13:31 UTC, ChillerDragon commented on src/engine/shared/network_client.cpp
> +	NullAddr.type = 7;
What kind of black magic is that ``7``. The NETADDR.type is usually used for ``NETTYPE_*`` flags.
I am not sure if by ``7`` you meant ``NETTYPE_TW7`` (actual value 16) or it is some magic combination of flags that you need. But either way please use some of the ``NETTYPE_*`` enums like everywhere else.

https://github.com/ddnet/ddnet/blob/4f53dd8048edd72967ddcde90c5e002995f918e4/src/base/types.h#L47-L61

2024-11-15 13:31 UTC, ChillerDragon commented on src/engine/shared/network.cpp
> +	net_udp_send(Socket, pAddr, aBuffer, DataSize + 9);
Could use ``const int DATA_OFFSET = 9;`` instead of the magic number. To be consistent with the 0.6 version.
This method also already exists server side only so it could probably be merged and ``int CNetServer::SendConnlessSixup(CNetChunk *pChunk, SECURITY_TOKEN ResponseToken)`` can be removed. But that could also be done in a follow up pr. Or I would at least wait with those refactors until a maintainer accepts the feature.

2024-11-15 13:31 UTC, ChillerDragon commented on src/engine/shared/network.h
> +	struct SSixupBrowserServer
Sorry for giving you only the annoying style comments -.- but thats all I could find for now in my shallow review.
This should be ``class CSixupBrowserServer`` according to the [new style guide](https://github.com/ddnet/ddnet/blob/4f53dd8048edd72967ddcde90c5e002995f918e4/CONTRIBUTING.md#the-usage-of-class-should-be-favored-over-struct).

2024-11-15 13:31 UTC, ChillerDragon commented on src/game/client/sixup_translate_game.cpp
> +void CClient::PreprocessConnlessPacket7(CNetChunk *pPacket)
The file seems a bit off for a `CClient` method. All translation here is about game messages and methods from the ``CGameClient``. The files sixup_translate_system.cpp and sixup_translate_snapshot.cpp technically are also wrong because it is not a system message or snapshot. But at least these implement ``CClient`` methods. The cleanest solution would be to create ``sixup_translate_connless.cpp``.

2024-11-15 15:03 UTC, ChillerDragon approved these changes

2024-11-15 18:39 UTC, Robyt3 commented on src/game/client/sixup_translate_connless.cpp
> +		GET_STRING(Hostname);
The hostname is unused, call `Up.GetString(CUnpacker::SANITIZE_CC | CUnpacker::SKIP_START_WHITESPACES)` without storing the result.

2024-11-15 18:55 UTC, MilkeeyCat commented on src/engine/shared/network_client.cpp
Ok, but how would I call `CheckSixupAddrs` then?

2024-11-15 19:57 UTC, Robyt3 commented on src/engine/shared/network_client.cpp
Not sure, maybe you can add it after the call to `m_aNetClient[Conn].Recv` in `client.cpp`, though you'd also need to propagate the result of the check `if(m_RecvUnpacker.m_Data.m_Flags & NET_PACKETFLAG_CONTROL && m_RecvUnpacker.m_Data.m_aChunkData[0] == NET_CTRLMSG_TOKEN` to the caller of `Recv`, e.g. by adding a Boolean output (pointer) parameter to this function.

2024-11-16 18:31 UTC, MilkeeyCat commented on src/game/client/sixup_translate_connless.cpp
> +		mem_copy((unsigned char *)pPacket->m_pData + sizeof(SERVERBROWSE_INFO), Packer.Data(), Packer.Size());
I don't know how to do that nicely :\

2024-11-17 10:52 UTC, Robyt3 approved these changes

2024-11-17 14:57 UTC, heinrich5991 commented
First on a high level. Why does this need a new parameter on the `CNetClient::Recv` function? By that point, the client should already know whether the server is a 0.7 or a 0.6 server.

2024-11-17 15:53 UTC, heinrich5991 commented
I think the `NET_CTRLMSG_TOKEN` stuff should be handled by the `CNetClient`, not outside of it. Basically, you should send a serverbrowser info request message and the `CNetClient` will handle the requesting of tokens and sending of the message.

2024-11-20 21:20 UTC, MilkeeyCat commented
@Robyt3, @heinrich5991 sooo, do I have to move it in `CNetClient` or wat?

2024-11-21 20:03 UTC, Robyt3 commented
I guess the token stuff specifically should be handled inside `CNetClient`, but the serverinfo specifics should not be added there.

2024-11-30 21:12 UTC, MilkeeyCat commented
Where should `BrowserInfo7`(https://github.com/ddnet/ddnet/pull/8992/files#diff-64f65b9589678af8ccfe6558a3ea6712dff9e74becd3d0e22fcac74758546776R2352-R2366) function be, in CNetClient or CServerBrowser?

2024-12-01 12:21 UTC, Robyt3 commented
> Where should `BrowserInfo7`(https://github.com/ddnet/ddnet/pull/8992/files#diff-64f65b9589678af8ccfe6558a3ea6712dff9e74becd3d0e22fcac74758546776R2352-R2366) function be, in CNetClient or CServerBrowser?

I'd say only `SERVERBROWSE_GETINFO` and `sizeof(SERVERBROWSE_GETINFO)` belong in `CServerBrowser`. Everything else belongs in `CNetClient`, i.e. generating the token based on the address and adding the token to the end of the message (use a `unsigned char aBuffer[NET_MAX_PACKETSIZE];` instead of `CPacker` for this).

2024-12-01 21:13 UTC, MilkeeyCat commented
> i.e. generating the token based on the address and adding the token to the end of the message (use a `unsigned char aBuffer[NET_MAX_PACKETSIZE];` instead of `CPacker` for this).

I don't understand how to use bytes array instead of `CPacker`, `CVariableInt::Pack` has to be used for browser token. @ChillerDragon can you do this pr, I'm too stupid for this xd

2024-12-01 21:18 UTC, Robyt3 commented
> I don't understand how to use bytes array instead of `CPacker`, `CVariableInt::Pack` has to be used for browser token.

Ah, I didn't notice that. I guess it's fine to use `CPacker` then.

2024-12-03 14:26 UTC, MilkeeyCat commented
I'm planning to add a method to `CNetClient` which will queue 0.7 packets and will send them as soon as the token is fetched. But how to represent the packet's data itself? Should it be something like  `unsigned char [N][NET_MAX_PACKETSIZE]`(that's a lot of bytes) or do you have a better idea?

2024-12-03 17:41 UTC, heinrich5991 commented
> I'm planning to add a method to `CNetClient` which will queue 0.7 packets and will send them as soon as the token is fetched. But how to represent the packet's data itself?

Yes. You can even add that functionality to the existing send function, it'll be used whenever you set the `NETTYPE_TW7` constant.

> But how to represent the packet's data itself? Should it be something like `unsigned char [N][NET_MAX_PACKETSIZE]`(that's a lot of bytes) or do you have a better idea?

You can probably take a look at how the 0.7 code does it. https://github.com/teeworlds/teeworlds/blob/c56fa9e6a20cfc9d7d16502e18c7d7633acdf492/src/engine/shared/network_server.cpp#L267

2024-12-03 20:45 UTC, MilkeeyCat commented
https://github.com/teeworlds/teeworlds/blob/c56fa9e6a20cfc9d7d16502e18c7d7633acdf492/src/engine/shared/network.h#L308-L309 What's better than linked lists?

2024-12-03 20:51 UTC, heinrich5991 commented
You can probably store it in a vector and hope that there aren't going to be many connless messages sent at once.

2024-12-05 18:13 UTC, MilkeeyCat commented
@heinrich5991 @Robyt3 Could you take a look at the new code?

2024-12-12 19:19 UTC, MilkeeyCat commented
@ChillerDragon what does 0.7 pro think about the code?

2024-12-13 01:53 UTC, ChillerDragon commented on src/game/client/sixup_translate_connless.cpp
> +		PutInt(Token & 0xff);
Is this converting a 4 byte 0.7 security token into a one byte (plus null terminator lol) 0.6 token?
That could probably use a comment.

2024-12-13 01:54 UTC, ChillerDragon commented
@MilkeeyCat LGTM if it still works ship it.

2024-12-13 01:58 UTC, ChillerDragon commented on src/game/client/sixup_translate_connless.cpp
> +		PutInt(Token & 0xff);
Oh you can use ``GetBasicToken(Token)`` here maybe then we can even skip the comment.

2024-12-13 20:22 UTC, MilkeeyCat commented on src/game/client/sixup_translate_connless.cpp
> +		PutInt(Token & 0xff);
The only `GetBasicToken` function is see is a private method of `CServerBrowser`, I dunno how to use it :p

2024-12-14 03:48 UTC, ChillerDragon commented on src/game/client/sixup_translate_connless.cpp
> +		PutInt(Token & 0xff);
Ah fair. Never mind then.

2024-12-25 08:28 UTC, MilkeeyCat commented
![image](https://github.com/user-attachments/assets/cf9741af-f490-4ad7-ae1b-32f81be5e1a3)

2024-12-31 22:02 UTC, MilkeeyCat commented
Happy new year ddnet maintainers!

2025-01-16 20:20 UTC, Robyt3 commented
I tested this together with some other fixes for #9176, but it looks like the translated server info produced by this PR isn't valid in some cases yet. For example on @ChillerDragon's server the translated server info has type `SERVERINFO_VANILLA` but this causes the server info to be discarded by the client because of the `Info.m_MaxPlayers > VANILLA_MAX_CLIENTS` check.

2025-01-17 12:17 UTC, MilkeeyCat commented
> I tested this together with some other fixes for #9176, but it looks like the translated server info produced by this PR isn't valid in some cases yet. For example on @ChillerDragon's server the translated server info has type `SERVERINFO_VANILLA` but this causes the server info to be discarded by the client because of the `Info.m_MaxPlayers > VANILLA_MAX_CLIENTS` check.

What server info type should it have? `SERVERINFO_64_LEGACY`?

2025-01-17 14:18 UTC, heinrich5991 commented
> What server info type should it have? `SERVERINFO_64_LEGACY`?

Probably a new `SERVERINFO_7` or so.

2025-01-17 15:46 UTC, heinrich5991 commented
Ah, I misunderstood the question. Yes, `SERVERINFO_EXTENDED` or `SERVERINFO_64_LEGACY`, preferably the first one unless it doesn't work. We'd probably drop `SERVERINFO_64_LEGACY` at some point.

2025-01-17 17:07 UTC, MilkeeyCat commented
![image](https://github.com/user-attachments/assets/8f0295b0-a6a6-4af9-9f19-d26b6e7da48b)
With these changes I can see both, ctf servers with 64 players and vanilla tw servers

2025-01-17 20:05 UTC, Robyt3 commented
The client doesn't accept the server info pong yet when joining a server. The client should print `got pong from current server, latency=%dms` shortly after the `pinging current server, using fallback via server info` debug message, but this currently fails because `ValidPong = Token == m_CurrentServerPingToken` evaluates to false.

Sometimes the `CClient::ProcessServerInfo` function is also never called after joining a 0.7 server, not sure why.

2025-01-17 21:34 UTC, MilkeeyCat commented
Ping pong works now

2025-01-19 11:56 UTC, Robyt3 approved these changes

2025-01-19 22:08 UTC, def- approved these changes

2025-01-19 22:29 UTC, merged