Add "center pivot" for quads
ddnet/ddnet pull request #9019
Opened 2024-09-22 23:54 UTC by furo321

Add quad popup button for centering the pivot of a quad. Ported from vanilla, https://github.com/teeworlds/teeworlds/pull/970/commits/082f8767862e0811bd953c3c6ad8dc07cab05eff.

https://github.com/user-attachments/assets/dc46b2ff-91e7-4f99-897f-f8e3ae74b664

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-09-23 04:35 UTC, ChillerDragon commented
Brand new teeworlds technology from 12 years ago.

![image](https://github.com/user-attachments/assets/58d54838-ddd5-4ed5-8c6f-b47a580157f1)

2024-09-23 11:39 UTC, Robyt3 requested changes

2024-09-23 11:39 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +		pCurrentQuad->m_aPoints[4].y = Top + int((Bottom - Top) / 2);
Those casts to `int` are unnecessary since the operands are already `int`s. We also don't use the operator-like casting style `int(x)` but `(int)x` (or `static_cast` etc.) instead.

2024-09-23 18:14 UTC, Robyt3 approved these changes

2024-09-23 18:17 UTC, Robyt3 requested changes
I just noticed it's missing handling to undo/redo this change, I think you need to add

```cpp
pEditor->m_QuadTracker.BeginQuadTrack(pLayer, pEditor->m_vSelectedQuads);
...
pEditor->m_QuadTracker.EndQuadTrack();
```
Around the code that changes the quad.

2024-09-24 08:50 UTC, Robyt3 approved these changes

2024-09-24 09:08 UTC, merged