Fix ``hot_reload`` losing spectator state
ddnet/ddnet pull request #9021
Opened 2024-09-23 05:01 UTC by ChillerDragon

This fixes the bug that moved spectators in game on ``hot_reload``

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-09-23 11:47 UTC, heinrich5991 requested changes
With the current proposed fix, I'd prefer to keep the bug. I'm not sure if there's a better solution.

2024-09-23 11:47 UTC, heinrich5991 commented on src/game/server/player.h
> +	void SetTeamRaw(int Team) { m_Team = Team; }
This function looks suspicious to me. Why is there a `Raw` function.

2024-09-23 11:47 UTC, heinrich5991 commented on src/game/server/save.h
> +	int m_Team;
I don't think the `m_Team` variable belongs into a save.

(It probably also introduces bugs with actual loads/saves.)

2024-09-23 11:53 UTC, ChillerDragon commented on src/game/server/player.h
> +	void SetTeamRaw(int Team) { m_Team = Team; }
Thats how I call this setter in my forks usually. ``CPlayer::m_Team`` is private and ``SetTeam()`` comes with a lot of side effects. Should I use a friend class instead? Or make it public? Or rename the raw setter?

2024-09-23 11:58 UTC, heinrich5991 commented on src/game/server/save.h
> +	int m_Team;
> But I think a `m_Team` belongs into a save. Otherwise it can cause unexpected behavior also for loading and saving.

It can't cause unexpected behavior since you can't save while you're not playing. This is also why I think it's the wrong place to store such a "spectator" variable. Maybe you could instead change the code where the tees are saved/loaded to not use save/load on spectators?

2024-09-23 12:01 UTC, ChillerDragon commented on src/game/server/save.h
> +	int m_Team;
I also need TEAM_RED and TEAM_BLUE to close https://github.com/ddnet-insta/ddnet-insta/issues/145

2024-09-23 12:10 UTC, heinrich5991 commented on src/game/server/save.h
> +	int m_Team;
You can probably also do that in the place I suggested (in ddnet-insta).

2024-09-23 12:22 UTC, ChillerDragon commented on src/game/server/save.h
> +	int m_Team;
What about instead of skipping spectators the team could be stored in a separate struct that is only used for hot reloading? I am sure it will grow over time. This is probably not the last tee state that should be hot reloaded but not included in savetee.

2024-09-27 20:37 UTC, KebsCS commented on src/game/server/save.h
> +	int m_Team;
@ChillerDragon 
Since this feature uses variables from m_pPlayer and is only for hot_reload, maybe it can be done the same way as in https://github.com/ddnet/ddnet/pull/8902/files But instead of adding a bunch of new arrays, it makes sense to create a class that holds the necessary m_pPlayer variables and make an array of that

2024-09-28 01:53 UTC, ChillerDragon commented on src/game/server/save.h
> +	int m_Team;
This is exactly what I meant when I said.

> I think the additional save state struct would be good.

Since heinrich did not reject the idea yet I will probably implement it  soon.

2024-09-29 06:24 UTC, ChillerDragon commented
I fully refactored the code. It is now using ``CPersistentClientData`` instead of ``CSaveTee`` and there is no more ``SetTeamRaw``.

Also I found out that this fixes two bugs:
- spectators being moved in game
- in games being moved to spectators if ``sv_tournament_mode`` is set

2024-10-07 15:38 UTC, heinrich5991 commented on src/game/server/gamecontext.cpp
> +	pPersistent->m_IsSpectator = pPlayer->GetTeam() == TEAM_SPECTATORS;
It seems that we already have code for retaining spectators as spectators. Why did that not work?

The rest looks like support code for game modes with more teams, I don't want to merge this.

2024-10-08 05:04 UTC, ChillerDragon commented on src/game/server/gamecontext.cpp
> +	pPersistent->m_IsSpectator = pPlayer->GetTeam() == TEAM_SPECTATORS;
> It seems that we already have code for retaining spectators as spectators. Why did that not work?

Good catch. No idea how I did not see that. Probably i assumed its /pause or something like that. As far as I remember I did run into that bug in ddnet-insta and then also tested it in ddnet. Anyways I tested again and there is no bug that moves spectators to the game on ``hot_reload`` or ``reload`` for that matter. So the only bug left is that if ``sv_tournament_mode`` is on all players will be moved to spectators on ``hot_reload``.

> The rest looks like support code for game modes with more teams, I don't want to merge this.

This is sad. I know you have #7777 to lean on now. But limiting down existing teams to a spectator boolean does not seem to me like it improves ddnet maintenance. It is hostile towards forks that use teams and I would like to understand the reasoning here.

2024-10-09 00:14 UTC, ChillerDragon commented
>  I don't want to merge this.

2024-10-09 00:14 UTC, closed without merging