Whitelist logger valgrind errors
ddnet/ddnet pull request #9022
Opened 2024-09-23 11:33 UTC by ChillerDragon

This now shows 0 errors or warnings:
```
valgrind --tool=memcheck --gen-suppressions=all --suppressions=../memcheck.supp --leak-check=full --show-leak-kinds=all ./DDNet-Server
```

Closed #8943

## Checklist

- [x] Tested the change ~~ingame~~
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-09-23 11:45 UTC, heinrich5991 requested changes
Thanks for the change. This makes `valgrind` a lot more usable. Looking into the suppressions, I think it'd be good if they included less detail in the stack traces so the file doesn't have to be updated each time we change the source a little.

2024-09-23 11:45 UTC, heinrich5991 commented on memcheck.supp
> +   fun:main
I think these two lines should be enough.

2024-09-23 11:45 UTC, heinrich5991 commented on memcheck.supp
> +   fun:main
These two lines should be enough.

2024-09-23 11:45 UTC, heinrich5991 commented on memcheck.supp
> +   fun:main
These two.

2024-09-23 11:45 UTC, heinrich5991 commented on memcheck.supp
> +   fun:main
These two.

2024-09-23 11:45 UTC, heinrich5991 commented on memcheck.supp
> +   fun:_ZN5CHttp7RunLoopEv
Not sure if this leak is okay.

2024-09-23 11:45 UTC, heinrich5991 commented on memcheck.supp
> +   fun:main
These two should be enough.

2024-09-23 11:45 UTC, heinrich5991 commented on memcheck.supp
> +   fun:main
These two.

2024-09-23 11:45 UTC, heinrich5991 commented on memcheck.supp
> +   fun:main
These two.

2024-09-23 11:45 UTC, heinrich5991 commented on memcheck.supp
> +   fun:_ZN8CStorage4InitEiiPPKc
Not sure if this leak is okay.

2024-09-23 11:45 UTC, heinrich5991 commented on memcheck.supp
> +   fun:_ZN12CGameContext7AddVoteEPKcS1_
Not sure if this leak is okay.

2024-09-25 05:44 UTC, ChillerDragon commented on memcheck.supp
> +   fun:_ZN5CHttp7RunLoopEv
Don't ask me. Does this help you to figure it out @heinrich5991?

<pre>
 <code>
==2263902== 4,232 bytes in 1 blocks are still reachable in loss record 13 of 17
==2263902==    at 0x4840F2F: operator new(unsigned long) (vg_replace_malloc.c:422)
==2263902==    by 0x24BE48: std::__new_allocator<CLogMessage>::allocate(unsigned long, void const*) (new_allocator.h:137)
==2263902==    by 0x24BD0F: std::allocator_traits<std::allocator<CLogMessage> >::allocate(std::allocator<CLogMessage>&, unsigned long) (alloc_traits.h:464)
==2263902==    by 0x24BC1B: std::_Vector_base<CLogMessage, std::allocator<CLogMessage> >::_M_allocate(unsigned long) (stl_vector.h:378)
==2263902==    by 0x24B86A: void std::vector<CLogMessage, std::allocator<CLogMessage> >::_M_realloc_insert<CLogMessage const&>(__gnu_cxx::__normal_iterator<CLogMessage*, std::vector<CLogMessage, std::allocator<CLogMessage> > >, CLogMessage const&) (vector.tcc:453)
==2263902==    by 0x24B5B6: std::vector<CLogMessage, std::allocator<CLogMessage> >::push_back(CLogMessage const&) (stl_vector.h:1287)
==2263902==    by 0x24B16F: CServerLogger::Log(CLogMessage const*) (server_logger.cpp:38)
==2263902==    by 0x35657D: CFutureLogger::Log(CLogMessage const*) (log.cpp:522)
==2263902==    by 0x356A5B: CLoggerCollection::Log(CLogMessage const*) (log.cpp:201)
==2263902==    by 0x355D4C: log_log_impl(LEVEL, bool, LOG_COLOR, char const*, char const*, __va_list_tag*) (log.cpp:114)
==2263902==    by 0x355ED7: log_log(LEVEL, char const*, char const*, ...) (<a href="https://github.com/ddnet/ddnet/blob/9298ee485e6e1180085455e43023060aacfe04f6/src/base/log.cpp#L127">log.cpp:127</a>)
==2263902==    by 0x31EEB5: CHttp::RunLoop() (<a href="https://github.com/ddnet/ddnet/blob/9298ee485e6e1180085455e43023060aacfe04f6/src/engine/shared/http.cpp#L513">http.cpp:513</a>)
==2263902== 
 </code>
</pre>

2024-09-25 05:49 UTC, ChillerDragon commented on memcheck.supp
> +   fun:_ZN8CStorage4InitEiiPPKc
<pre>
<code>
==2266079== 
==2266079== HEAP SUMMARY:
==2266079==     in use at exit: 384,352 bytes in 18 blocks
==2266079==   total heap usage: 5,721 allocs, 5,703 frees, 17,800,885 bytes allocated
==2266079== 
==2266079== 33,856 bytes in 1 blocks are still reachable in loss record 15 of 17
==2266079==    at 0x4840F2F: operator new(unsigned long) (vg_replace_malloc.c:422)
==2266079==    by 0x24BE48: std::__new_allocator<CLogMessage>::allocate(unsigned long, void const*) (new_allocator.h:137)
==2266079==    by 0x24BD0F: std::allocator_traits<std::allocator<CLogMessage> >::allocate(std::allocator<CLogMessage>&, unsigned long) (alloc_traits.h:464)
==2266079==    by 0x24BC1B: std::_Vector_base<CLogMessage, std::allocator<CLogMessage> >::_M_allocate(unsigned long) (stl_vector.h:378)
==2266079==    by 0x24B86A: void std::vector<CLogMessage, std::allocator<CLogMessage> >::_M_realloc_insert<CLogMessage const&>(__gnu_cxx::__normal_iterator<CLogMessage*, std::vector<CLogMessage, std::allocator<CLogMessage> > >, CLogMessage const&) (vector.tcc:453)
==2266079==    by 0x24B5B6: std::vector<CLogMessage, std::allocator<CLogMessage> >::push_back(CLogMessage const&) (stl_vector.h:1287)
==2266079==    by 0x356629: CFutureLogger::Log(CLogMessage const*) (<a href="https://github.com/ddnet/ddnet/blob/9298ee485e6e1180085455e43023060aacfe04f6/src/base/log.cpp#L532">log.cpp:532</a>)
==2266079==    by 0x356A5B: CLoggerCollection::Log(CLogMessage const*) (<a href="https://github.com/ddnet/ddnet/blob/9298ee485e6e1180085455e43023060aacfe04f6/src/base/log.cpp#L201">log.cpp:201</a>)
==2266079==    by 0x355D4C: log_log_impl(LEVEL, bool, LOG_COLOR, char const*, char const*, __va_list_tag*) (<a href="https://github.com/ddnet/ddnet/blob/9298ee485e6e1180085455e43023060aacfe04f6/src/base/log.cpp#L114">log.cpp:114</a>)
==2266079==    by 0x355DD2: log_log_v(LEVEL, char const*, char const*, __va_list_tag*) (<a href="https://github.com/ddnet/ddnet/blob/9298ee485e6e1180085455e43023060aacfe04f6/src/base/log.cpp#L120">log.cpp:120</a>)
==2266079==    by 0x3589A4: dbg_msg(char const*, char const*, ...) (<a href="https://github.com/ddnet/ddnet/blob/9298ee485e6e1180085455e43023060aacfe04f6/src/base/system.cpp#L220">system.cpp:220</a>)
==2266079==    by 0x3447B0: CStorage::Init(int, int, char const**) (<a href="https://github.com/ddnet/ddnet/blob/9298ee485e6e1180085455e43023060aacfe04f6/src/engine/shared/storage.cpp#L82">storage.cpp:82</a>)
==2266079== 
</code>
</pre>

2024-09-25 05:52 UTC, ChillerDragon commented on memcheck.supp
> +   fun:_ZN12CGameContext7AddVoteEPKcS1_
<pre>
<code>
==2266536== 270,848 bytes in 2 blocks are still reachable in loss record 17 of 17
==2266536==    at 0x4840F2F: operator new(unsigned long) (vg_replace_malloc.c:422)
==2266536==    by 0x24BE48: std::__new_allocator<CLogMessage>::allocate(unsigned long, void const*) (new_allocator.h:137)
==2266536==    by 0x24BD0F: std::allocator_traits<std::allocator<CLogMessage> >::allocate(std::allocator<CLogMessage>&, unsigned long) (alloc_traits.h:464)
==2266536==    by 0x24BC1B: std::_Vector_base<CLogMessage, std::allocator<CLogMessage> >::_M_allocate(unsigned long) (stl_vector.h:378)
==2266536==    by 0x24B86A: void std::vector<CLogMessage, std::allocator<CLogMessage> >::_M_realloc_insert<CLogMessage const&>(__gnu_cxx::__normal_iterator<CLogMessage*, std::vector<CLogMessage, std::allocator<CLogMessage> > >, CLogMessage const&) (vector.tcc:453)
==2266536==    by 0x24B5B6: std::vector<CLogMessage, std::allocator<CLogMessage> >::push_back(CLogMessage const&) (stl_vector.h:1287)
==2266536==    by 0x356629: CFutureLogger::Log(CLogMessage const*) (log.cpp:532)
==2266536==    by 0x356A5B: CLoggerCollection::Log(CLogMessage const*) (log.cpp:201)
==2266536==    by 0x355D4C: log_log_impl(LEVEL, bool, LOG_COLOR, char const*, char const*, __va_list_tag*) (log.cpp:114)
==2266536==    by 0x355ED7: log_log(LEVEL, char const*, char const*, ...) (<a href="https://github.com/ddnet/ddnet/blob/9298ee485e6e1180085455e43023060aacfe04f6/src/base/log.cpp#L127">log.cpp:127</a>)
==2266536==    by 0x309167: CConsole::Print(int, char const*, char const*, ColorRGBA) const (<a href="https://github.com/ddnet/ddnet/blob/9298ee485e6e1180085455e43023060aacfe04f6/src/engine/shared/console.cpp#L347">console.cpp:347</a>)
==2266536==    by 0x285868: CGameContext::AddVote(char const*, char const*) (<a href="https://github.com/ddnet/ddnet/blob/master/src/game/server/gamecontext.cpp#L3264">gamecontext.cpp:3264</a>)
==2266536== 
</code>
</pre>

2024-09-25 05:58 UTC, ChillerDragon commented
I connected to the server did run around a bit. Authed in rcon. Reloaded the server multiple times. Called some map votes. With the whitelists removed from the 3 where we are not sure. The final report looked good.

```
==2266867== LEAK SUMMARY:
==2266867==    definitely lost: 0 bytes in 0 blocks
==2266867==    indirectly lost: 0 bytes in 0 blocks
==2266867==      possibly lost: 0 bytes in 0 blocks
==2266867==    still reachable: 308,936 bytes in 4 blocks
==2266867==         suppressed: 75,416 bytes in 14 blocks
==2266867== 
==2266867== For lists of detected and suppressed errors, rerun with: -s
==2266867== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

2024-10-05 04:36 UTC, ChillerDragon commented
Because there has been no progress since one week I removed the 3 controversial whitelists. I prefer having it improved now over having it fully fixed never.

2024-10-05 10:57 UTC, def- approved these changes

2024-10-05 11:19 UTC, merged