Add ``ed_layer_selector`` config to to toggle layer selector feature
ddnet/ddnet pull request #9031
Opened 2024-09-24 13:35 UTC by ChillerDragon

Closed #9029

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-09-24 13:37 UTC, ChillerDragon commented
No hard feelings on the default. We can also deactivate it by default instead of expecting the users to turn it off. I would assume the majority of the users does not know and understand the feature and thus sees it more as annoying than useful.

2024-09-24 13:48 UTC, furo321 commented
Can you add it to editor settings as well? Kinda impossible to know about the config otherwise.

2024-09-24 13:51 UTC, Robyt3 requested changes

2024-09-24 13:51 UTC, Robyt3 commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(EdLayerSelector, ed_layer_selector, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "ctrl+rightclick tiles to select their layers in the editor")
`Ctrl+right click ...`

2024-09-24 13:51 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +	const bool ScrollToSelection = (g_Config.m_EdLayerSelector && LayerSelector()->SelectByTile()) || s_ScrollToSelectionNext;
Would be cleaner to move this check inside `SelectByTile` since the mouse button handling is also there.

2024-09-24 13:51 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +			else if(m_pBrush->IsEmpty() && g_Config.m_EdLayerSelector)
A case for the feature being disabled that only shows `Use left mouse button to drag and create a brush.` is missing.

2024-09-24 13:51 UTC, Robyt3 commented on src/game/editor/editor.cpp
>  				str_copy(m_aTooltip, "Use left mouse button to drag and create a brush. Use ctrl+right mouse to select layer.");
`Use ctrl+right click to select layer for hovered tile.`

2024-09-24 17:34 UTC, Robyt3 requested changes

2024-09-24 17:34 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +		Ui()->DoPopupMenu(&s_PopupMenuEntitiesId, SettingsButton.x, SettingsButton.y + SettingsButton.h - 1.0f, 200.0f, 120.0f, this, PopupMenuSettings, PopupProperties);
Also increase the width a bit so the text is not scaled down.

2024-09-24 17:34 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +		if(pEditor->DoButton_Ex(&s_ButtonYes, "Yes", g_Config.m_EdLayerSelector, &Yes, 0, "Do not select layers when Ctrl+right clicking on a tile", IGraphics::CORNER_R))
Wrong tooltip text.

2024-09-25 01:23 UTC, ChillerDragon commented
![image](https://github.com/user-attachments/assets/7121c9d2-6a82-46e0-97cb-201ec5899cd4)

2024-09-25 09:02 UTC, Robyt3 approved these changes

2024-09-25 09:20 UTC, merged