Show skin name as tooltip in friendlist and serverinfo
ddnet/ddnet pull request #9041
Opened 2024-09-25 12:44 UTC by bencie

Similarly to the Player tab ingame, you can hover your mouse over tees in the severinfo and friendslist to see the skin they're using.

## Checklists

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-09-25 14:11 UTC, Robyt3 requested changes

2024-09-25 14:11 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +			static char s_aFriends[MAX_CLIENTS] = {0};
This separate array is unnecessary and this will break if you have more than 64 online friends. Add `const void *SkinTooltipId() const { return &m_aSkin; }` after the definition of the `CommunityTooltipId` function in `menus.h` instead and use this as the ID instead, consistently with the usage of `CommunityTooltipId` etc.

2024-09-25 14:11 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> -				int ButtonResult = Ui()->DoButtonLogic(Friend.ListItemId(), 0, &Rect);
Keep this line here, otherwise the behavior is inconsistent and you can hover a point between the skin and background rect where neither is the hot item.

2024-09-25 14:11 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
>  				const bool Inside = Ui()->HotItem() == Friend.ListItemId() || Ui()->HotItem() == Friend.RemoveButtonId() || Ui()->HotItem() == Friend.CommunityTooltipId();
Add `|| Ui()->HotItem() == Friend.SkinTooltipId()` at the end of the condition so the item is highlighted when the skin is hovered.

2024-09-25 14:11 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +				int ButtonResult = Ui()->DoButtonLogic(Friend.ListItemId(), 0, &Rect) || Ui()->DoButtonLogic(&s_aFriends[FriendIndex], 0, &Skin);
Move the `Ui()->DoButtonLogic(Friend.SkinTooltipId(), 0, &Skin);` above the `DoTooltip` call below, this button logic should not be activated when there is no tooltip. As stated above, the `Ui()->DoButtonLogic(Friend.ListItemId(), 0, &Rect)` should be kept at its original location.

2024-09-25 17:48 UTC, Robyt3 approved these changes

2024-09-26 01:41 UTC, def- approved these changes

2024-09-26 02:00 UTC, merged