Add smooth spectating
ddnet/ddnet pull request #9045
Opened 2024-09-26 15:59 UTC by KebsCS

Closes #2513 
Closes #8928 (Spectating flags is not possible due to how spectating is tied to the server and player limit)

The camera is only smooth in spectator mode. It snaps back to the player when exiting spectator mode to avoid affecting gameplay.

https://github.com/user-attachments/assets/feb1e45c-5e0e-4af4-a4ad-f7cf113e0fee

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-09-26 16:25 UTC, Jupeyy commented
It's not clear from your video, what happens if you already spectate someone (from a previous spec) and enter spectate again?

Would that also cause a delay?
It's quite common during gameplay to spectate ppl and quickly see where they are. E.g. in gores some players do this while in the air

2024-09-26 16:25 UTC, Jupeyy commented
Also #8928 sounds like it wants smth different than this, does this patch also do smooth transitions if a Tee dies?

2024-09-26 16:37 UTC, KebsCS commented
> It's not clear from your video, what happens if you already spectate someone (from a previous spec) and enter spectate again?
> 
> Would that also cause a delay? It's quite common during gameplay to spectate ppl and quickly see where they are. E.g. in gores some players do this while in the air

In this case, the camera transitions to the spectating player smoothly. Is this the behavior we want? It's an easy fix with the m_WasSpectating variable


> Also #8928 sounds like it wants smth different than this, does this patch also do smooth transitions if a Tee dies?

No, it doesn't affect the player's camera at all, since you can still move and shoot while the camera is transitioning. I could add another config value, which would be off by default, to also include the player, but I'm not sure if we want that. Or I could just remove this issue from this pr

2024-09-26 16:40 UTC, Jupeyy commented
> Is this the behavior we want?

If you ask me personally, no.
I think waiting for animations is always bad, regardless of smooth zoom, smooth scrollbars etc.
(When ppl use my android phone they always ask why my phone is so fast compared to theirs... bcs i disabled all animations)

Generally:
For going into spec I'd say that has a rather huge impact to gameplay, so we should be extra careful with wasting players time by default (default config behavior)

2024-09-26 18:42 UTC, KebsCS commented
Changed according to @Jupeyy's feedback. Also removed #8928 from this pr, as this feature request doesn't seem good

2024-09-27 09:04 UTC, Robyt3 requested changes

2024-09-27 09:04 UTC, Robyt3 commented on src/game/client/components/camera.cpp
> +		float Derivative[2] = {0.0f};
Use a `vec2` instead of an array of `float`s.

2024-09-27 12:19 UTC, KebsCS commented
@Robyt3 Done

2024-09-28 11:54 UTC, def- approved these changes

2024-09-28 12:15 UTC, merged