Add in-game entities to editor
ddnet/ddnet pull request #9057
Opened 2024-09-28 17:18 UTC by KebsCS

https://github.com/user-attachments/assets/851028c8-97a0-4e94-971f-fca39f0a7ef0

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-09-29 07:01 UTC, ChillerDragon commented
What is the purpose of this? Can they move when put on a speeder?

2024-09-29 18:55 UTC, KebsCS commented
> What is the purpose of this? Can they move when put on a speeder?

The purpose is to allow players to design a map without having to go in-game to check how it looks. When placed on a speeder, they won't move. I couldn’t manage to get it to work accurately because it uses game ticks to move, and it’s not completely accurate within tiles in the game either

2024-10-03 14:17 UTC, KebsCS commented
Another use case is that many custom entities (#9053) lack graphics for weapons, shields etc. So, this PR is the only way to see them

2024-10-03 15:00 UTC, ChillerDragon commented
Which custom entities are missing those textures?

2024-10-03 15:47 UTC, KebsCS commented
> Which custom entities are missing those textures?

The default "comfort" for example. I'm guessing it's like that, because you see the weapons anyway, so they don't bother adding a tile icon for them. That's why if you're going to use an entity skin, that is not specifically made for mapping, it'll be missing

2025-01-23 20:09 UTC, edg-l approved these changes
looks ok to me

2025-01-23 20:17 UTC, Robyt3 requested changes

2025-01-23 20:17 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +			const CGameClient *pGameClient = (CGameClient *)Kernel()->RequestInterface<IGameClient>();
Move this outside the loop

2025-01-23 20:17 UTC, Robyt3 commented on src/game/editor/editor.cpp
> +				Pos += direction(Client()->LocalTime() * 2.0f + x + y) * 2.5f;
Use `GlobalTime` instead of `LocalTime`, the latter depends on the current server and doesn't advance when offline.

2025-01-23 20:17 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +		pEditor->Ui()->DoLabel(&Label, "Show in-game entities", 10.0f, TEXTALIGN_ML);
`ingame` (#9513)

2025-01-23 20:17 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +		if(pEditor->DoButton_Ex(&s_ButtonNo, "No", !g_Config.m_EdShowInGameEntities, &No, 0, "Do not show how weapons, shields, hearts and flags appear in-game", IGraphics::CORNER_L))
`ingame` and all tooltips should end with a period (#9513).

2025-01-23 20:17 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +		if(pEditor->DoButton_Ex(&s_ButtonYes, "Yes", g_Config.m_EdShowInGameEntities, &Yes, 0, "Show how weapons, shields, hearts and flags appear in-game", IGraphics::CORNER_R))
same

2025-01-23 20:17 UTC, Robyt3 commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(EdShowInGameEntities, ed_show_ingame_entities, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show how weapons, shields, hearts and flags appear in-game")
`InGame` --> `Ingame`, `in-game` --> `ingame`

2025-01-23 20:17 UTC, Robyt3 commented on src/game/editor/mapitems/layer_group.cpp
> +					m_pMap->m_pEditor->RenderGameEntities(pTiles);
Add `{ }` around the statement for better readability.

2025-01-23 20:44 UTC, KebsCS commented
@Robyt3 Done!

2025-01-23 21:11 UTC, Robyt3 approved these changes

2025-01-23 21:32 UTC, merged