Add rcon auto-auth for lan addresses
ddnet/ddnet pull request #9060
Opened 2024-09-29 02:47 UTC by KebsCS

With `sv_rcon_auto_auth` enabled, the server will automatically rcon auth all connections from the local network. This is useful for `hot_reload` map testing. 
This setting can be added to autoexec for it to work every time, but should it be enabled by default without the need for autoexec?

https://github.com/user-attachments/assets/0b8618e5-73bd-43eb-af50-b78880916391

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-09-29 06:27 UTC, ChillerDragon commented on src/engine/server/server.cpp
> +				if(pAddr->ip[0] == 127 || pAddr->ip[0] == 10 || (pAddr->ip[0] == 192 && pAddr->ip[1] == 168) || (pAddr->ip[0] == 172 && (pAddr->ip[1] >= 16 && pAddr->ip[1] <= 31)))
does this give my room mate rcon on my lan server?

2024-09-29 06:47 UTC, ChillerDragon commented on src/engine/server/server.cpp
> +				if(pAddr->ip[0] == 127 || pAddr->ip[0] == 10 || (pAddr->ip[0] == 192 && pAddr->ip[1] == 168) || (pAddr->ip[0] == 172 && (pAddr->ip[1] >= 16 && pAddr->ip[1] <= 31)))
![open_ddnet_rcon](https://github.com/user-attachments/assets/1167f236-4864-4320-a208-a6bcedd11645)

2024-09-29 06:53 UTC, ChillerDragon commented
We could also bind a local ip like 127.0.0.1 by default instead of 0.0.0.0 and not expose the server to any other device. And if that is the case have no password. Similar to how database services allow local connections without credentials.

2024-09-29 09:36 UTC, heinrich5991 requested changes
Thanks for your pull request.

I don't think it's a good idea to give authentication based on IP addresses, so I don't think we should merge this.

Authenticating (with a password) on the server started in the client would be a lot safer.

2024-09-29 16:06 UTC, KebsCS commented
> Thanks for your pull request.
> 
> I don't think it's a good idea to give authentication based on IP addresses, so I don't think we should merge this.
> 
> Authenticating (with a password) on the server started in the client would be a lot safer.

That’s true, which is why it shouldn’t be on by default. But since it only works with local IP addresses, which are impossible to fake, it could still be useful for mappers. If someone’s on the same network as the connecting player, they could do much worse things than just griefing a Teeworlds server

2024-09-29 16:28 UTC, KebsCS commented on src/engine/server/server.cpp
> +				if(pAddr->ip[0] == 127 || pAddr->ip[0] == 10 || (pAddr->ip[0] == 192 && pAddr->ip[1] == 168) || (pAddr->ip[0] == 172 && (pAddr->ip[1] >= 16 && pAddr->ip[1] <= 31)))
> does this give my room mate rcon on my lan server?

I guess, if you don't want that, you don't have to use that setting. But if you still do, and he starts griefing your teeworlds server I guess you can fight over it irl 😂

2024-10-03 09:39 UTC, heinrich5991 commented
I like #9092 a lot better.

2024-10-03 09:39 UTC, closed without merging