Show UI debug info inside editor
ddnet/ddnet pull request #9091
Opened 2024-10-01 21:37 UTC by dobrykafe

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-10-01 21:47 UTC, Robyt3 requested changes

2024-10-01 21:47 UTC, Robyt3 commented on src/game/client/ui.cpp
> +	if(g_Config.m_ClEditor)
There probably shouldn't be a dependency on this config variable in the UI. You could pass the position of this text as an argument to the function instead.

2024-10-02 19:29 UTC, dobrykafe commented on src/game/client/ui.cpp
> +	if(g_Config.m_ClEditor)
Done!

2024-10-02 20:30 UTC, Robyt3 approved these changes

2024-10-02 20:50 UTC, merged