Add test map locally
ddnet/ddnet pull request #9092
Opened 2024-10-01 23:26 UTC by KebsCS

Closes #6733
Closes #9009
Alternative to #9060

Runs a local server with the currently opened map (if it's saved to `maps/`) and automatically authenticates with a new custom rcon password

https://github.com/user-attachments/assets/6fda8098-9a85-48a9-a2d9-fd84e770f361

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-10-01 23:39 UTC, SoulyVEVO commented
:O

2024-10-01 23:45 UTC, BlaiZephyr commented
i like this! - but how is it an alternative to #9060, because launching the server normally won't auth you automatically its more of an addition right? also will this relaunch the server each time?

2024-10-02 00:02 UTC, KebsCS commented
> i like this! - but how is it an alternative to #9060, because launching the server normally won't auth you automatically its more of an addition right? also will this relaunch the server each time?

Alternative, becuase it is safer and works like in this comment: https://github.com/ddnet/ddnet/pull/9060#pullrequestreview-2335808680 . The user authenticates themselves rather than the server. Yes, it relaunches every time, but I can add a check like hot reload does. If you're authenticated on a local server, it won't restart, as I can't authenticate the player without relaunching the server

2024-10-02 01:35 UTC, KebsCS commented
Fixed, If you're rcon on a local server, it will simply change the map. If the local server is running or you aren't authenticated, it will prompt you to confirm whether you want to restart. If no server is running, it will start the server and connect you to it, as in the video

2024-10-02 11:00 UTC, heinrich5991 commented
I like the high-level feature, I think it's a very good addition. :)

We'll need to be careful around process spawning and correct escaping of arguments.

2024-10-02 18:23 UTC, Robyt3 requested changes

2024-10-02 18:23 UTC, Robyt3 commented on src/base/system.cpp
> +PROCESS shell_execute(const char *file, EShellExecuteWindowState window_state, const char *arguments)
I think we should probably pass `const char **arguments` and `size_t num_arguments`, i.e. an array of arguments and the size of the array. Then on unix we can construct `argv` of correct length `num_arguments + 2` which should take care of escaping. And on Windows the argument escaping probably has to be different. See the [SHELLEXECUTEINFOW documentation](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-shellexecuteinfow) on the parameter `lpParameters`. Although it currently seems to work, the documentation states "to include double quotation marks in lpParameters, enclose each mark in a pair of quotation marks".

2024-10-03 13:38 UTC, KebsCS commented
@Robyt3 Done!

2024-10-03 15:04 UTC, Robyt3 requested changes

2024-10-03 15:04 UTC, Robyt3 commented on src/game/editor/quick_actions.cpp
> +		pGameClient->m_Menus.RunServer(pArguments, 1);
This should now pass 3 arguments instead of 1 without the escaping and semicolons.

2024-10-03 15:04 UTC, Robyt3 commented on src/base/system.cpp
> +	std::wstring wide_arguments = L"";
Escaping should be added here instead, see https://learn.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-shellexecuteinfow

2024-10-03 18:53 UTC, KebsCS commented
@Robyt3 Done. Semicolons are fine, as they are parsed by the server's `ParseArguments`. I can't add automatic escaping of quotes in `shell_execute` because the user needs to be able to handle both cases: `sv_name \"test\"` and programs that take arguments like `--file="text"` without extra slashes.

2024-10-04 15:37 UTC, Robyt3 requested changes

2024-10-04 15:37 UTC, Robyt3 commented on src/base/system.cpp
> +		if(wide_arg.front() == L'-' && wide_arg.find(L'=') != std::wstring::npos)
Do we need to support arguments starting with `-` and why are those handled differently?

2024-10-04 15:37 UTC, Robyt3 commented on src/base/system.cpp
> +	std::wstring wide_arguments = L"";
It's not strictly following the documentation yet:

> To include double quotation marks in lpParameters, enclose each mark in a pair of quotation marks, as in the following example. [see link]

Though it also works for me like this we should generally follow the documentation.

Will require some more testing though, also with escaped quotes.

2024-10-04 15:37 UTC, Robyt3 commented on src/base/system.cpp
> +			if(wide_arg.find_first_of(L" &|^") != std::wstring::npos)
I'd just always add quotes, no need for this check.

2024-10-04 15:37 UTC, Robyt3 commented on src/base/system.h
> + * @param num_arguments The number of arguments
Dots at the end.

2024-10-04 15:37 UTC, Robyt3 commented on src/game/editor/quick_actions.cpp
> +		str_format(aBuf, sizeof(aBuf), "sv_rcon_password %s;change_map %s", aPass, aFileNameNoExt);
We should pass those as two separate arguments (so three in total), as that was the point of making these functions accept multiple arguments. Will need another `char` buffer but that's fine.

2024-10-04 15:37 UTC, Robyt3 commented on src/game/editor/quick_actions.cpp
> +		const char *pArguments[] = {"sv_register 0", aBuf};
`apArguments`

2024-10-04 15:37 UTC, Robyt3 commented on src/game/editor/quick_actions.cpp
> +		pGameClient->m_Menus.RunServer(pArguments, 2);
`std::size(apArguments)` instead of `2`

2024-10-05 12:17 UTC, KebsCS commented on src/base/system.cpp
> +	std::wstring wide_arguments = L"";
The double quotes are then passed to the program, and the server's `ParseArguments` function can't decode a string that is wrapped in a pair of quotation marks, that's why I kept it as a single `\"`

2024-10-05 12:22 UTC, KebsCS commented on src/base/system.cpp
> +		if(wide_arg.front() == L'-' && wide_arg.find(L'=') != std::wstring::npos)
If we want the `shell_execute` function to be universal, then yes. Some programs use arguments in the format `--key=value`, where only the value is parsed, and the key is treated as a plain string. That's why I didn't include automatic quote escaping at first, to let the developers handle it if necessary. In the case of this PR, it doesn't even use any arguments with quotes

2024-10-06 09:02 UTC, Robyt3 commented on src/base/system.cpp
> +		if(wide_arg.front() == L'-' && wide_arg.find(L'=') != std::wstring::npos)
I think trying to make `shell_execute` universal is not trivial and also not necessary. I think supporting the specific use-case of launching the server/client with some supported arguments should be enough.

I don't see how arguments in the key-value format would work any differently on Windows though. They work exactly like any other string according to my testing:

- `foo.exe --foo=bar` --> Program gets `--foo=bar`
- `foo.exe --foo="bar"` --> Program gets `--foo=bar`
- `foo.exe "--foo=bar"` --> Program gets `--foo=bar`
- `foo.exe """--foo=bar"""` --> Program gets `"--foo=bar"`
- `foo.exe --foo="""bar"""` --> Program gets `--foo="bar"`

2024-10-06 09:06 UTC, Robyt3 commented on src/base/system.cpp
> +	std::wstring wide_arguments = L"";
Seems like we need to leave the outer quotes as single quotes, so each argument will be considered as one unit. But to escape quotes inside arguments it seems that using `"""` (`\"\"\"`) would be more correct according to the documentation. Using `\"` (`\\\"`) also seems to work but it's not documented.

2024-10-07 21:42 UTC, KebsCS commented
@Robyt3 Done! I've tested the escaped quotes `\"\"\"` with `sv_name` and whitespaces, and everything worked fine

2024-10-14 15:52 UTC, heinrich5991 commented on src/base/system.cpp
> +	}
Currently, this looks a bit simpler than the corresponding function in Rust: https://github.com/rust-lang/rust/blob/17a19e684cdf3ca088af8b4da6a6209d128913f4/library/std/src/sys/pal/windows/args.rs#L216-L260.

Looking at difference, I notice that backslashes aren't handled. Is that a problem? What happens to the string `\`? It also escapes `"` as `\"` and not `"""`. I didn't know that was possible, how did you find this?

2024-10-14 18:02 UTC, KebsCS commented on src/base/system.cpp
> +	}
Almost all previous reviews by Roby were about double quote escaping. This code is what we have agreed on so far: `"""` is from the ShellExecuteW documentation https://learn.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-shellexecuteinfow#remarks

2025-01-03 21:23 UTC, Robyt3 requested changes
The server now also works on Android. With #9474 it will also support arguments on launch. I added the same functions as in this PR in `CMenus` already, so it should hopefully be easy to resolve the conflicts (keep the original version, then add the arguments again).

2025-01-27 02:53 UTC, KebsCS commented on src/base/system.cpp
> +	}
Added tests to verify, that it behaves correctly

2025-01-27 03:27 UTC, KebsCS commented
@Robyt3 Resolved conflicts and added tests to verify, that shell_execute which starts the server behaves correctly

2025-01-27 10:37 UTC, heinrich5991 commented on src/base/system.cpp
> +	}
What happens with backslashes?

2025-01-27 15:59 UTC, KebsCS commented on src/base/system.cpp
> +	}
The function wraps every argument in quotes, so it doesn't need to escape backslashes. For example, with `sv_name "te\st"`, it correctly sets the server name to `te\st`. This also works when file paths are passed as arguments, as they don't require escaping either

2025-01-27 18:35 UTC, heinrich5991 commented on src/base/system.cpp
> +	}
Does this also work correctly when the backslash is at the end of the string?

E.g. `./DDNet-Server "sv_name test\" "sv_map foobar\"`?

2025-01-29 21:50 UTC, Robyt3 commented on src/base/system.cpp
> +	}
Looks like that breaks, e.g. `"sv_name test\\"` sets the server name to `test"` instead where `"sv_name test\\\\"` sets it to `test\`.

2025-01-29 22:03 UTC, heinrich5991 commented on src/base/system.cpp
> +	}
I'd suggest following the escaping done by a major programming language, since all of them have to deal with this, e.g. Rust's: https://github.com/rust-lang/rust/blob/17a19e684cdf3ca088af8b4da6a6209d128913f4/library/std/src/sys/pal/windows/args.rs#L216-L260. I guess Python also needs to have one somewhere.

2025-01-29 22:05 UTC, Robyt3 requested changes

2025-01-29 22:05 UTC, Robyt3 commented on src/game/editor/popups.cpp
> +			pEditor->TestMapLocally(true);
On Android this is slightly inconvenient because the server doesn't stop immediately (exacerbated by #9498). This might also be changed on other platforms eventually so the server shuts down more cleanly (but a bit slower). This currently just causes the popup to be shown again so you have to keep clicking the button until the server is stopped and can be restarted. Maybe we could add another `POPEVENT_RESTARTING_SERVER` which shows a message like `Local server is restarting. Please wait…` and a `Cancel` button until the `IsServerRunning` function returns `false` and we can start the server again.

2025-02-09 16:41 UTC, KebsCS commented
@Robyt3 Done. This is the new popup. Could you check if it works on Android?
![image](https://github.com/user-attachments/assets/de2b4cd2-f3bc-4325-b1e8-360284c76fdc)

2025-02-09 20:02 UTC, Robyt3 approved these changes

2025-02-13 14:59 UTC, ChillerDragon commented
Cool feature!

Could disable the quick action if there is no map opened yet.

And also throw a warning if not saved yet or auto save to avoid confusion when the map is outdated.

2025-02-13 15:00 UTC, ChillerDragon commented on src/game/editor/quick_actions.cpp
> +	if(!str_startswith(m_aFileName, "maps/"))
Are downloadedmaps/ not working intentionally?

2025-02-13 15:06 UTC, KebsCS commented on src/game/editor/quick_actions.cpp
> +	if(!str_startswith(m_aFileName, "maps/"))
The server can't run maps from `downloadedmaps/`, only maps from `maps/` show up for me in the `Call vote` menu

2025-02-13 15:48 UTC, KebsCS commented
> Could disable the quick action if there is no map opened yet.

I think that would be unintuitive since there's already a warning prompting the user to save the map to `maps/`
 
> And also throw a warning if not saved yet or auto save to avoid confusion when the map is outdated.

If necessary, I can look into that later. The map doesn’t finish saving when the editor is closed to connect to the server

2025-02-13 17:25 UTC, Robyt3 commented on src/base/system.cpp
>  	const std::wstring wide_file = windows_utf8_to_wide(file);
For additional security I'd add these assertions:

```cpp
dbg_assert(str_endswith(file, ".bat") == nullptr && str_endswith(file, ".cmd") == nullptr, "Running batch files not allowed");
dbg_assert(str_endswith(file, ".exe") != nullptr || num_arguments == 0, "Arguments only allowed with .exe files");
```

To ensure that we don't try to run batch files, which is unsafe and we don't need to support. See https://flatt.tech/research/posts/batbadbut-you-cant-securely-execute-commands-on-windows/

Also, no arguments should be specified unless an executable file is to be opened (i.e. not when opening folders or the config file).

The documentation for `lpParameters` also states

> Optional. The address of a null-terminated string that contains the application parameters. The parameters must be separated by spaces. If the lpFile member specifies a document file, lpParameters should be NULL.

So you should not set `lpParameters` below (keeping the default `nullptr`) value unless `num_arguments` is non-zero.

2025-02-14 11:15 UTC, heinrich5991 commented on src/base/system.cpp
>  	const std::wstring wide_file = windows_utf8_to_wide(file);
> To ensure that we don't try to run batch files, which is unsafe and we don't need to support. See https://flatt.tech/research/posts/batbadbut-you-cant-securely-execute-commands-on-windows/

Doesn't help, you can run bat files without specifying the extension.

2025-02-14 11:19 UTC, heinrich5991 commented on src/base/system.cpp
>  	const std::wstring wide_file = windows_utf8_to_wide(file);
Uh nvm, you also abort unless the extension is `.exe`. Fair enough.

2025-02-14 11:33 UTC, heinrich5991 approved these changes
Thanks a lot for working on this and bringing this to an end. :)

LGTM with @Robyt3's concerns fixed.

2025-02-14 11:40 UTC, Robyt3 commented on src/base/system.cpp
>  	const std::wstring wide_file = windows_utf8_to_wide(file);
AFAICT (accoring to the documentation) `ShellExecute` should also not try to add executable extensions automatically, compared to `CreateProcess` which would expand names without extension to various different candidates and therefore seems very unsafe.

2025-02-14 15:34 UTC, KebsCS commented
@Robyt3 Done, also added `dbg_assert((arguments == nullptr) == (num_arguments == 0), "Invalid number of arguments");` in response to this comment:

> The documentation for lpParameters also states
> 
> Optional. The address of a null-terminated string that contains the application parameters. The parameters must be separated by spaces. If the lpFile member specifies a document file, lpParameters should be NULL.
> 
> So you should not set lpParameters below (keeping the default nullptr) value unless num_arguments is non-zero.

2025-02-14 15:57 UTC, Robyt3 commented
> @Robyt3 Done, also added `dbg_assert((arguments == nullptr) == (num_arguments == 0), "Invalid number of arguments");` in response to this comment:
> 
> > The documentation for lpParameters also states
> > Optional. The address of a null-terminated string that contains the application parameters. The parameters must be separated by spaces. If the lpFile member specifies a document file, lpParameters should be NULL.
> > So you should not set lpParameters below (keeping the default nullptr) value unless num_arguments is non-zero.

The additional assertion seems good, but I meant that `info.lpParameters = wide_arguments.c_str();` should be enclosed in another `if` because it currently sets the parameters to an empty string when there are none but the Windows API documentation calls for it being set to `nullptr` (which is the default because of the `mem_zero`).

2025-02-14 17:37 UTC, Robyt3 approved these changes
Thanks!

2025-02-14 17:58 UTC, merged