Highlight all search items
ddnet/ddnet pull request #9109
Opened 2024-10-04 13:52 UTC by Anime-pdf

# **THIS IS VERY UNOPTIMIZED BUT IM LACKING SKILLS TO DO SO, PLS HELP**

Currently if you have multiple search items (separated by ';'), and server has multiple of them, only first will be highlighted, this PR fixes it.

Before:
![image](https://github.com/user-attachments/assets/c393afbd-d129-45a8-aa06-6bfbdd9ddbd5)

After:
![image](https://github.com/user-attachments/assets/b9b79abf-b870-4168-b50d-78f25c8949a3)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-10-07 19:49 UTC, Robyt3 requested changes
Not sure if the performance can be improved without reworking the text render to render text containers with multiple color splits. Have you tried profiling yet?

The search currently doesn't seem to include multiple matches of the same filter term either. For example I'd expected the filter `a;b;c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z` to match all letters but it only matches the first of each.

![screenshot_2024-10-07_21-39-23](https://github.com/user-attachments/assets/676449b1-7836-4f1f-8ed4-6b6e02672988)

2024-10-07 19:49 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +					Printed = PrintHighlightedMultiple(pItem->m_aName, [&](std::vector<const char *> &vpFilteredStrs, std::vector<int> &vFilterLens) {
One reason why this is slow is that we are not taking advantage of the text containers anymore. Since this is rendering different text/color with the same container it will be recreated every time. Previously, there were exactly 3 containers for the part before the match, the match itself and the part after the match, to avoid the color changes of one container.

2024-10-07 19:49 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +			status box            +-----------------+
This should not be included

2024-10-07 20:00 UTC, Anime-pdf commented on src/game/client/components/menus_browser.cpp
> +					Printed = PrintHighlightedMultiple(pItem->m_aName, [&](std::vector<const char *> &vpFilteredStrs, std::vector<int> &vFilterLens) {
Oh, now it kinda makes sense. When I was making these changes I didn't understand what those `UI_ELEM_NAME_X` were, will try to do it right way

2024-11-24 06:28 UTC, closed without merging

2024-11-24 06:28 UTC, Anime-pdf commented
Won't finish it anytime soon