Add rcon commands (un)infinite_jump, practice commands /(un)infjump
ddnet/ddnet pull request #9114
Opened 2024-10-05 12:18 UTC by Pioooooo

Also missing from practice mode.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-10-05 12:37 UTC, def- requested changes
Did you test this?

2024-10-05 12:37 UTC, def- commented on src/game/server/ddracechat.cpp
> +		ConEndlessJump(pResult, pUserData);
ConUnEndlessJump

2024-10-09 17:40 UTC, Robyt3 approved these changes

2024-10-09 20:26 UTC, def- approved these changes

2024-10-09 20:48 UTC, merged