Preserve super on hot reload, fix hot reload crashes
ddnet/ddnet pull request #9160
Opened 2024-10-21 13:40 UTC by KebsCS

Fixes #9156 for both super and /invincible

Fixed a crash when in super with an empty previous team and when players were on a different teams during hot reload

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-10-21 13:42 UTC, heinrich5991 commented
I don't think it's a good idea to include invincibility and super in `CSaveTee`. Perhaps we can add an abstraction around that `CSaveTee` that encompasses the things we need for hot reload beyond what is actually saved in `/save`?

2024-10-21 14:52 UTC, KebsCS commented
> I don't think it's a good idea to include invincibility and super in `CSaveTee`. Perhaps we can add an abstraction around that `CSaveTee` that encompasses the things we need for hot reload beyond what is actually saved in `/save`?

Done, also moved `m_apSavedTeleTees` that was used to save `/lasttp` to the new `CSaveHotReloadTee` class

2025-01-21 20:08 UTC, Robyt3 requested changes

2025-01-21 20:08 UTC, Robyt3 commented on src/game/server/save.cpp
> +	if(pChr->m_pPlayer)
This check looks unnecessary to me. A character's player should never be `nullptr`. Also, if it was `nullptr` here then `m_SavedTeleTee` wouldn't be initialized.

2025-01-21 20:08 UTC, Robyt3 commented on src/game/server/save.h
> +	bool Load(CCharacter *pchr, int Team, bool IsSwap = false);
`pChr` or `pCharacter`

2025-01-21 20:08 UTC, Robyt3 commented on src/game/server/save.h
> +	int m_Invincible;
Use `bool`s instead of `int`s

2025-01-21 21:20 UTC, KebsCS commented
@Robyt3 Done!

2025-01-21 22:21 UTC, Robyt3 commented
You accidentally changed the ddnet-libs submodule.

2025-01-21 22:48 UTC, Robyt3 approved these changes

2025-01-21 23:23 UTC, merged