Add a "connection problems" icon to nameplate
ddnet/ddnet pull request #9172
Opened 2024-10-26 15:24 UTC by furo321

This adds a new character flag `CONNECTION_PROBLEMS`, this is set for clients who has not sent a packet in the last 5 seconds. Players with the flag will have an icon in their nameplates and can be disabled with `cl_nameplates_network`. The icon is taken from 0.7.

![image](https://github.com/user-attachments/assets/96212e14-8a84-43df-9ef9-a032ca2b8a64)

Closes #9169

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-10-26 15:42 UTC, heinrich5991 reviewed
I like the idea of a "bad network" indicator, would probably help.

2024-10-26 15:42 UTC, heinrich5991 commented on CMakeLists.txt
> +  network.png
Where are these graphics from? What license do they have?

2024-10-26 15:42 UTC, heinrich5991 commented on datasrc/content.py
> +container.sprites.Add(Sprite("network_good", set_networkicons, 0,0,1,1))
Seems unused.

2024-10-26 15:42 UTC, heinrich5991 commented on datasrc/network.py
> +				  "MOVEMENTS_DISABLED", "IN_FREEZE", "PRACTICE_MODE", "LOCK_MODE", "TEAM0_MODE", "INVINCIBLE", "CONNECTION_PROBLEMS"]
This should be a player flag, it's not related to the character.

2024-10-26 15:42 UTC, heinrich5991 commented on src/engine/server/server.cpp
> +	m_LastPacketTick = -1;
Hmmm. I wonder if the last input tick or last acked snapshot, or perhaps even a combination of both would be a better indicator. Just because a chat message made it through does not mean that the player can control the tee. With weird firewalls or DoS "protections" that we have, sometimes only some packets make it through.

2024-10-26 15:42 UTC, heinrich5991 commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(ClNameplatesNetwork, cl_nameplates_network, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show network icon if the player has connection problems")
A new config option shouldn't be added without justification.

2024-10-26 15:42 UTC, heinrich5991 commented on src/game/server/entities/character.cpp
> +		if(Server()->Tick() - Info.m_LastPacketTick >= 5 * 60)
Where does the 60 come from? Is `Server()->TickSpeed()` meant?

2024-10-26 15:50 UTC, Robyt3 requested changes

2024-10-26 15:50 UTC, Robyt3 commented on src/game/server/entities/character.cpp
> +		if(Server()->Tick() - Info.m_LastPacketTick >= 5 * 60)
Use `Server()->TickSpeed()`

2024-10-26 15:50 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +	// Connection problems icon
The nameplate is also previewed in the Appearance settings. Should also show the icon there.

2024-10-26 16:56 UTC, furo321 commented on CMakeLists.txt
> +  network.png
They're from this 0.7 PR, https://github.com/teeworlds/teeworlds/pull/2607. They seem to be licensed under `CC BY-SA 3.0`, I added a `license.txt` file for it.

2024-10-26 16:58 UTC, furo321 commented on datasrc/content.py
> +container.sprites.Add(Sprite("network_good", set_networkicons, 0,0,1,1))
I included because it's available in the `network.png` and if anyone wants to do something with that icon. Should I remove it?

2024-10-26 17:00 UTC, furo321 commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(ClNameplatesNetwork, cl_nameplates_network, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show network icon if the player has connection problems")
I added it because all other nameplate elements have a config option.

2024-10-26 17:05 UTC, furo321 commented on src/engine/server/server.cpp
> +	m_LastPacketTick = -1;
It would be possible to make it work more similar to how `Connection problems...` works in game. If that's wanted. Currently it only shows up on a "complete" loss of connection.

2024-10-26 22:39 UTC, sjrc6 commented
can we call the config cl_nameplates_connection_problems for consistency?

2024-10-27 16:29 UTC, BannZay commented on src/game/client/components/nameplates.cpp
> +			ColorRGBA Color = ColorRGBA(1.0f, 1.0f, 1.0f, 1.0f);
Probably a good idea to extract a method like _DisplayConnectionProblemsIcon_() ?

And ideally reuse it in menus_settings.cpp, if possible.

What do you think ?

2024-11-01 10:04 UTC, furo321 commented on src/game/client/components/nameplates.cpp
> +			ColorRGBA Color = ColorRGBA(1.0f, 1.0f, 1.0f, 1.0f);
I won't do it in this PR, but could be done in a different one. One that refactors and makes the appearance tabs and real code share the same code.

2025-05-22 10:31 UTC, closed without merging

2025-05-22 14:04 UTC, BlaiZephyr commented
furo sadly deleted his entire github existence it seems?

@SollyBunny you've been working a LOT with nameplates in the last few weeks, maybe you could pick this up?
https://github.com/ddnet/ddnet/issues/9169

2025-05-22 22:35 UTC, SollyBunny commented on datasrc/content.py
> +container.sprites.Add(Sprite("network_good", set_networkicons, 0,0,1,1))
@heinrich5991 I agree with the ghost

2025-05-22 22:37 UTC, SollyBunny commented on src/engine/server/server.cpp
> +	m_LastPacketTick = -1;
It would be nice to have a scale from "im good!" (no icon) through "some packet loss, bit laggy" to "there's no point in playing, yall hacking teleport gods or smthin"

2025-05-22 22:38 UTC, SollyBunny commented on src/engine/server/server.cpp
> +	m_LastPacketTick = -1;
I usually use the ping circle from tclient to do this as if you are jumping from green to yellow I know you are lagging, but if you are going red I know you are dying
It's pretty accurate, why haven't we added ping circle to DDNet?

2025-05-22 22:42 UTC, SollyBunny commented on src/engine/server/server.cpp
> +	m_LastPacketTick = -1;
There could be an indicator which is a combination of ping and packet loss
Have 1 to 4 bars for packet loss, then color for ping