Visual changes to friends and server tab
ddnet/ddnet pull request #9248
Opened 2024-11-14 23:38 UTC by SollyBunny

## Checklist

- [*] Tested the change ingame
- [*] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### Friends Tab
* Added padding between items in playerlist (consistency)
* Removed random background
* Added tooltips for sections

### Server Info
* Added alpha variation to playerlist (consistency)
* Added border to background
* Colored ping

![image](https://github.com/user-attachments/assets/ec00e0ed-fbb3-4ce3-9f20-f67fa694f710)

![image](https://github.com/user-attachments/assets/d8379612-79ff-4290-8a76-3fbb9d8b3492)

2024-11-15 19:40 UTC, Robyt3 requested changes

2024-11-15 19:40 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +			ColorOld = TextRender()->GetTextColor();
There is generally no need to retrieve the current color. Simply always reset the text color to `DefaultTextColor` after changing it without the additional checks.

2024-11-15 19:40 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +	View.HSplitBottom(5.0f, &View, nullptr);
I don't like this additional spacing, it misaligned both at the top and bottom now.

![image](https://github.com/user-attachments/assets/af3208c3-a9e9-4607-9d68-f53a140e9c6b)

It was already aligned appropriately previously.

2024-11-15 19:40 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +	s_ListBox.DoStart(25.0f, pSelectedServer->m_NumReceivedClients, 1, 3, -1, &View, false);
I don't think this background should be removed. It looks weird now with only the top half of the info having the full background. The dark color is supposed to indicate the selected tab. Instead, change the `BackgroundCorners` parameter to fix the top corners not being correct before. Then move the left margin from the outside of the listbox to the inside, so the background is rendered correctly also on the left side. Maybe it would also make sense to always show the scrollbars (`ForceShowScrollbar` parameter) for consistent width.

2024-11-15 19:40 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +		CUIRect Header, DeleteIcon, QuestionIcon, Label;
The name `DeleteIcon` is wrong. The variable `GroupLabel` name should be kept instead of reverting to less descriptive `Label` and reusing this variable. Rename `Label` to be more descriptive. Generally, reusing `CUIRects` variables makes the code less readable and is premature optimization.

2024-11-15 19:40 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +			str_format(aBuf, sizeof(aBuf), Localize("Online friends (%d)"), (int)m_avFriends[FriendType].size());
I prefer the previous label.

2024-11-15 19:40 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +				const float Alpha = (FriendIndex % 2 + 1) * 0.05f;
I don't really like how the alternating background colors look with the colored background.

![image](https://github.com/user-attachments/assets/78b089d1-04c3-453f-8adf-83a62f2378c8)

I'd rather remove the alternating background also from the player list if you want total consistency.

2024-11-15 19:40 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> -				CUIRect Label;
Keep the variable here. Or rename to `NoneLabel` to avoid shadowing another variable. Variables should generally be declared as close to their usages with the smallest scope possible, as this increases the maintainability.

2024-11-15 19:40 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +			break;
Add an assertion in the `default` case, same as the `switch(FriendType)` above.

2024-11-15 19:40 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +			GameClient()->m_Tooltips.DoToolTip(&s_aListExtended[FriendType], &Header, pText, Header.w);
Since you added the ?-icon, I think the tooltip should only be shown while you hover that. So you should use `&QuestionIcon` instead of `&Header`. Otherwise I don't really see the need for the ?-icon, as we generally don't indicate that UI elements have tooltips.

I would also remove the last parameter (`Header.w`, the width hint) so the tooltip is rendered with full width. I think it looks too small with just the width of the header.

2024-11-15 19:40 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +		Header.VSplitRight(Header.h, &Label, &QuestionIcon);
This should not change the size of the `Header` rect. You are now cutting off the left part (the group icon) from the header rect, so it's not possible anymore to click the header on the group icon, as the subsequent `DoButtonLogic` call uses the cut `Header` rect.

2024-11-15 19:40 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +			pText = Localize("Offline friends and clanmates will appear here");
My suggestions for the tooltip texts:

- `Add friends by entering their name below or by clicking their name in the player list.`
- `Add clanmates by entering their clan below and leaving the name blank.`
- `Offline friends and clanmates will appear here.` (full stop at the end) (though I'm not sure this explanation is really necessary).

2024-11-16 01:15 UTC, SollyBunny commented on src/game/client/components/menus_browser.cpp
> +		CUIRect Header, DeleteIcon, QuestionIcon, Label;
I think it's better as a message replacing "None"

2024-11-16 01:17 UTC, SollyBunny commented on src/game/client/components/menus_browser.cpp
> +			str_format(aBuf, sizeof(aBuf), Localize("Online friends (%d)"), (int)m_avFriends[FriendType].size());
It is specifically friends in that section rather than any player.

2024-11-17 11:33 UTC, Robyt3 requested changes

2024-11-17 11:33 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +	s_ListBox.DoStart(25.0f, pSelectedServer->m_NumReceivedClients, 1, 3, -1, &View, false, 0, true);
`IGraphics::CORNER_NONE` instead of `0`

2024-11-17 11:33 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +
This looks more complicated than it needs to be. You are effectively encoding `m_FriendState` as two `bool`s and then going back to an integer value anyway. Pass `m_FriendState` to this function directly instead of `Friend` and `Clan`.

Also remove the default values for `Afk` and `Inside`. Default values generally make the code less readable and should only be used with good reason, e.g. for frequently used utility functions like `TextWidth`.

2024-11-17 11:33 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +		// Don't show afk state for FRIEND_NO players
Not sure about this. Now you can't see if non-friends are AFK anymore, which was previously supported.

2024-11-17 11:33 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +		const ColorRGBA Color = PlayerBackgroundColor(CurrentClient.m_FriendState == IFriends::FRIEND_PLAYER, CurrentClient.m_FriendState == IFriends::FRIEND_CLAN, CurrentClient.m_Afk && CurrentClient.m_Fr
The player items now look a bit too bright to me:

![image](https://github.com/user-attachments/assets/bb76cfbc-692f-4fac-b232-0913043e4bfa)

Can you change the background color to be consistent with offline friends?

![image](https://github.com/user-attachments/assets/756a1405-d1af-4b70-b95b-125c7eea4afc)

2024-11-17 11:33 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +				// Render empty description
Move this comment up above `if(m_avFriends[FriendType].empty())`, it also describes the code above.

2024-11-17 11:33 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +				s_ScrollRegion.AddRect(EmptyDescription);
```suggestion
				const float DescriptionMargin = 2.0f;
				const STextBoundingBox BoundingBox = TextRender()->TextBoundingBox(FontSize, pText, -1, List.w - 2 * DescriptionMargin);
				CUIRect EmptyDescription;
				List.HSplitTop(BoundingBox.m_H + 2 * DescriptionMargin, &EmptyDescription, &List);
				s_ScrollRegion.AddRect(EmptyDescription);
				EmptyDescription.Margin(DescriptionMargin, &EmptyDescription);
				SLabelProperties DescriptionProps;
				DescriptionProps.m_MaxWidth = EmptyDescription.w;
				Ui()->DoLabel(&EmptyDescription, pText, FontSize, TEXTALIGN_ML, DescriptionProps);
```

- Consistent margin on all sides.
- Prefer using `DoLabel` for UI instead of the textrender directly.
- Reserve the space in the scroll region before drawing the text for consistent usage of `CScrollRegion`.

2024-11-17 11:33 UTC, Robyt3 commented on src/game/client/components/menus_browser.cpp
> +	static const ColorRGBA ColorsAfk[] = {ColorRGBA(1.0f, 1.0f, 0.5f), ColorRGBA(0.4f, 0.75f, 1.0f), ColorRGBA(0.75f, 0.75f, 0.75f)};
`COLORS` and `COLORS_AFK` names for static constants.

2024-11-17 16:17 UTC, SollyBunny commented on src/game/client/components/menus_browser.cpp
> +		// Don't show afk state for FRIEND_NO players
You can still see afk state through the eyes, having the background dim looks really weird

2024-11-17 16:22 UTC, SollyBunny commented on src/game/client/components/menus_browser.cpp
> +
In the two places PlayerBackgroundColor is used, 2 different enums are available for friend state which aren't compatible

2024-11-18 18:19 UTC, Robyt3 approved these changes
LGTM. Please also update the PR description and screenshots to the current state.

2024-11-20 23:20 UTC, merged

2024-11-24 13:57 UTC, ChillerDragon commented
The variable name ``COLORS`` is a bit annoying for me downstream. Because it also is defined in curses.h.

I know #7777 was declined but could we somehow not conflict with a library as big as ncurses?

```
 /home/runner/work/chillerbot-ux/chillerbot-ux/src/game/client/components/menus_browser.cpp: In function ‘ColorRGBA PlayerBackgroundColor(bool, bool, bool, bool)’:
/home/runner/work/chillerbot-ux/chillerbot-ux/src/game/client/components/menus_browser.cpp:31:32: error: declaration of ‘COLORS’ shadows a global declaration [-Werror=shadow]
   31 |         static const ColorRGBA COLORS[] = {ColorRGBA(0.5f, 1.0f, 0.5f), ColorRGBA(0.4f, 0.4f, 1.0f), ColorRGBA(0.75f, 0.75f, 0.75f)};
      |                                ^~~~~~
In file included from /home/runner/work/chillerbot-ux/chillerbot-ux/src/base/curses.h:5,
                 from /home/runner/work/chillerbot-ux/chillerbot-ux/src/game/client/components/chillerbot/terminalui/terminalui.h:10,
                 from /home/runner/work/chillerbot-ux/chillerbot-ux/src/game/client/gameclient.h:73,
                 from /home/runner/work/chillerbot-ux/chillerbot-ux/src/game/client/components/menus_browser.cpp:17:
/usr/include/curses.h:1481:32: note: shadowed declaration is here
 1481 | extern NCURSES_EXPORT_VAR(int) COLORS;
      |                                ^~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-nullability-completeness’ may have been intended to silence earlier diagnostics
cc1plus: all warnings being treated as errors
[238/357] Building CXX object CMakeFiles/game-client.dir/src/game/client/components/menus_demo.cpp.o
```

https://github.com/chillerbot/chillerbot-ux/actions/runs/11996342749/job/33440664226#step:4:350

2024-11-24 14:37 UTC, Robyt3 commented
Ideally, libraries wouldn't define macros with such common names like `COLORS`, `COLS`, `KEY_*`, `ERR`, `OK` but instead prefix them with the library name.

I suggest not including `curses.h` in another header file that will be included by `menus_browser.cpp`. Or `#undef COLORS` after including `curses.h`.

2024-11-24 14:49 UTC, ChillerDragon commented
Yea I agree it is weird that curses defines ``COLORS`` and the ``KEY_*`` stuff is also conflicting.

Hm sadly I could not get your suggestion to work.
https://github.com/chillerbot/chillerbot-ux/commit/8505bc30ba8c8cab848db77794ee9396aac10f89

2024-11-24 14:53 UTC, ChillerDragon commented
Seems like [undefining variables in C does not work](https://stackoverflow.com/questions/45387465/how-to-undeclare-delete-a-variable-in-c). And I have no idea how to contain the scope of the include to not leak into menus_browser.cpp.

2024-11-24 15:29 UTC, ChillerDragon commented
I see. That seems reasonable but also way more work than just renaming a variable in ddnet.