Add 128 player support
ddnet/ddnet pull request #9274
Opened 2024-11-22 16:33 UTC by def-

Revived from https://github.com/ddnet/ddnet/pull/8542
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-11-24 09:19 UTC, ChillerDragon commented
IMO we should do one separate pr with client support first then release a version and then look at the server side. As far as I know the client does not need much more than bumping max clients and testing it a bit. But then the server support can be implemented much cleaner for newer ddnet clients at least (working kick votes without fake id translation for example).

2024-11-24 09:23 UTC, ChillerDragon commented on src/mastersrv/src/main.rs
> +        .and(warp::body::content_length_limit(32 * 1024)) // limit body size to 32 KiB
This could already be merged in a separate pr. Because @0xfaulty is already hosting 128 player servers that run into this limit.

2024-11-25 18:08 UTC, Robyt3 requested changes

2024-11-25 18:08 UTC, Robyt3 commented on src/engine/shared/protocol.h
> +	MSGFLAG_NONAME = 64,
This is unused except for one condition using it, so it should be removed since the condition can never be true. See also https://github.com/ddnet/ddnet/pull/8542#discussion_r1704386352

2024-11-25 18:08 UTC, Robyt3 commented on src/engine/server.h
> +	virtual bool IsDebugDummy(int ClientId) const = 0;
See https://github.com/ddnet/ddnet/pull/8542#discussion_r1704385008. Debug dummies should be handled like real clients if possible.

2024-11-25 18:08 UTC, Robyt3 commented on src/game/server/playermapping.h
> +class CPlayerMapping
Unresolved comment: https://github.com/ddnet/ddnet/pull/8542#discussion_r1704380429

2024-11-25 18:08 UTC, Robyt3 commented on src/game/server/entities/character.cpp
> +	// translate id, if we are not in the map of the other person display us as weapon and our hook as a laser
Unresolved comment: https://github.com/ddnet/ddnet/pull/8542#discussion_r1704387808

2024-11-25 18:08 UTC, Robyt3 commented on src/game/server/playermapping.cpp
> +	if(Rejoin)
Unresolved comment: https://github.com/ddnet/ddnet/pull/8542#discussion_r1704373649

2024-11-25 18:08 UTC, Robyt3 commented on src/engine/server.h
> +	 * SendPackMsg, but send to both 0.6 and 0.7 players, not just one of them
Unresolved comment: https://github.com/ddnet/ddnet/pull/8542#discussion_r1704342539

2024-11-26 06:38 UTC, ChillerDragon commented on src/game/server/gamecontext.cpp
> +}
Also OrigID seems unused.

2024-11-28 11:17 UTC, 0xfaulty commented on src/mastersrv/src/main.rs
> +        .and(warp::body::content_length_limit(32 * 1024)) // limit body size to 32 KiB
Created #9291

2024-11-30 07:16 UTC, def- commented
@fokkonaut Can you help with the remaining comments?

2024-11-30 08:32 UTC, fokkonaut commented
> @fokkonaut Can you help with the remaining comments?

I'll try to find some time!

2024-12-01 06:25 UTC, def- commented
My plan is to get this merged next week and then immediately cut a new release with it so we have some time for 128 player clients before we switch on 128 player servers a while later.

2025-01-11 12:21 UTC, def- commented
@fokkonaut Are you still planning to fix this or should someone else take a look? (Any volunteers? I wish I could, but I'm finding it difficult to find time) I want this to be part of 19.0

2025-01-27 19:08 UTC, Robyt3 commented on src/engine/server.h
> +	virtual bool IsDebugDummy(int ClientId) const = 0;
Changes related to debug dummies should be unnecessary now with #9591. Remove the `IsDebugDummy` function and consider them like normal clients, as they have unique addresses now. Read the description of #9591 on how to replace existing uses of the `GetClientAddr` and related functions in new code.

2025-02-19 09:23 UTC, def- commented
Can we get this merged for 19.0?

2025-02-19 09:32 UTC, Robyt3 commented
Can you address the comment about debug dummies, i.e. remove special handling for them from this PR, rebase on master and squash?

2025-02-19 09:40 UTC, heinrich5991 commented
From a release stability point of view, it doesn't make sense to start merging huge pull requests right before the release. I suggest postponing the 19.0 release by more than the usual week after this is merged to figure out bugs that this will cause. (It should already be deployed on the servers so that the code paths are actually tested.)

2025-02-19 09:42 UTC, heinrich5991 commented
I see a couple of review comments that were unresolved with the old #8542. Have they been solved?

2025-02-19 09:59 UTC, def- commented
> Can you address the comment about debug dummies, i.e. remove special handling for them from this PR, rebase on master and squash?

Done

2025-02-19 10:07 UTC, def- commented
> From a release stability point of view, it doesn't make sense to start merging huge pull requests right before the release. I suggest postponing the 19.0 release by more than the usual week after this is merged to figure out bugs that this will cause. (It should already be deployed on the servers so that the code paths are actually tested.)

I can try merging again in ~1 years for 20.0 I guess.

> I see a couple of review comments that were unresolved with the old #8542. Have they been solved?

Nope. I just reread them all, but no idea what to do about them.

2025-02-19 12:23 UTC, KebsCS commented
Could the clientside part of this PR be merged now? That way, once it's fully ready, it won't require a major version update e.g. 20.0. It's only bumping `MAX_CLIENTS` in `src/engine/shared` and `src/game`. Since most of this PR focuses on fixing backward compatibility, merging this part would at least make it easier to roll out the update

2025-02-19 12:32 UTC, heinrich5991 commented
> Could the clientside part of this PR be merged now? That way, once it's fully ready, it won't require a major version update e.g. 20.0. It's only bumping `MAX_CLIENTS` in `src/engine/shared` and `src/game`. Since most of this PR focuses on fixing backward compatibility, merging this part would at least make it easier to roll out the update

That sounds like a great idea.

2025-02-19 13:49 UTC, heinrich5991 commented on src/game/server/entity.cpp
> +	return absolute(dy) > pGameServer->m_apPlayers[SnappingClient]->m_ShowDistance.y / 2.f + Border;
There seem to be unrelated changes in here.

2025-02-19 14:03 UTC, heinrich5991 commented on src/game/server/entity.cpp
> +	return absolute(dy) > pGameServer->m_apPlayers[SnappingClient]->m_ShowDistance.y / 2.f + Border;
The client requests a certain width and height, and now you're applying some transformation to it before using it. This should at the very least be commented — but preferably we'd not be ignoring the width the client sends, but fix the client instead.

2025-02-19 14:11 UTC, def- commented
> Could the clientside part of this PR be merged now? That way, once it's fully ready, it won't require a major version update e.g. 20.0. It's only bumping `MAX_CLIENTS` in `src/engine/shared` and `src/game`. Since most of this PR focuses on fixing backward compatibility, merging this part would at least make it easier to roll out the update

That is probably more risky than merging this and not enabling server-side translations for a while.

2025-02-19 14:13 UTC, heinrich5991 commented
> That is probably more risky than merging this and not enabling server-side translations for a while.

Why? It seems like it'd be a lot smaller diff.

2025-02-19 14:54 UTC, fokkonaut commented on src/game/server/entity.cpp
> +	return absolute(dy) > pGameServer->m_apPlayers[SnappingClient]->m_ShowDistance.y / 2.f + Border;
We are not ignoring the width. The client sends it's dimensions of the screen.
So we have to divide it by 2, in order to get the "radius".
It's been this way since it got implemented. Should maybe be commented on the client side. Right now the server is wasting bandwidth and cpu power for snapping non visible entities, exponentionally worse the more you zoom out.

I really do not understand how you hate on this specific thing for so long.

Get over it, or fix it maybe. But definitely not useless or wrong in this PR at this place.

2025-02-19 15:04 UTC, heinrich5991 commented on src/game/server/entity.cpp
> +	return absolute(dy) > pGameServer->m_apPlayers[SnappingClient]->m_ShowDistance.y / 2.f + Border;
From your explanation it seems that it's unrelated to this PR. It should go into another PR and probably be fixed properly instead.

2025-02-19 16:30 UTC, ChillerDragon commented on src/game/teamscore.h
> +	NUM_DDRACE_TEAMS = MAX_CLIENTS + 1,
Do I read this correctly? TEAM_SUPER is 64? And NUM_DDRACE_TEAMS is 129? So TEAM_SUPER and a regular ddrace team can share the same number?

2025-02-26 12:54 UTC, ChillerDragon commented
> That sounds like a great idea.

@heinrich5991  why wasn't it a good idea in november already? https://github.com/ddnet/ddnet/pull/9274#issuecomment-2495886216

2025-02-26 16:43 UTC, fokkonaut commented on src/game/server/entity.cpp
> +	return absolute(dy) > pGameServer->m_apPlayers[SnappingClient]->m_ShowDistance.y / 2.f + Border;
Btw: The showdistance is being used by @TsFreddie the same way I use it.
Feel like when others do stuff it's not as bad as when I do!(?)

2025-02-26 19:04 UTC, TsFreddie commented on src/game/server/entity.cpp
> +	return absolute(dy) > pGameServer->m_apPlayers[SnappingClient]->m_ShowDistance.y / 2.f + Border;
Just to understand both sides here, I believe fokk thinks adding 128 players and reducing bandwidth requirement are linked since 128 adds so much. And heinrich thinks fixing bandwidth is unrelated to the idea of enabling 128 players on the server.

> The showdistance is being used by @TsFreddie the same way I use it.

also btw I think you mean kebs for the spectator count? I wouldn't tag him tho. Without debating whether kebs magical numbers are good here, it is more related to the range for spectator being counted.

I do think these lines here could do with a separate PR tho. It's not about how you used it, it seems fine to me. But a separate PR would allow people to test/discuss specifically whether the numbers are ok for all screen configurations and all dyncam settings. Without blocking this merge by spending time discussing them here.

Given that deen has been wanting this to be merged, taking this to a separate PR seems pretty easy and would unblock this just a tiny bit more quickly. And of course, bandwidth issue should be address quickly before the client gets released.

2025-02-27 14:29 UTC, KebsCS commented on src/game/server/entity.cpp
> +	return absolute(dy) > pGameServer->m_apPlayers[SnappingClient]->m_ShowDistance.y / 2.f + Border;
My numbers are set so that it's roughly in the middle of the screen when spectating someone. Dividing the NetworkClipped by 2 aligns it exactly with the screen's borders, but breaks weapon rendering when it's next to the border, and probably dyncam too

2025-06-09 01:26 UTC, KebsCS commented
Bump 😃

2025-06-09 08:46 UTC, Robyt3 requested changes
> Bump 😃

I don't know how to deal with the open comments. Feel free to revive it, though you should open a comment in the new PR for every unresolved comment here.

2025-06-09 08:46 UTC, Robyt3 commented on src/engine/server/server.cpp
> +			str_format(m_aClients[ClientId].m_aName, sizeof(m_aClients[ClientId].m_aName), "Debug dummy %d", DummyIndex + 1);
Duplicate line, remove.

2025-07-05 17:47 UTC, SollyBunny commented on src/engine/server.h
> +	virtual bool IsDebugDummy(int ClientId) const = 0;
Resolved

2025-07-05 17:51 UTC, SollyBunny commented on src/game/server/playermapping.h
> +class CPlayerMapping
> Can there be a comment on how this class generally works? It seems to have a player mapping for each IP address, and updates it based on some stuff.
> Hein

the class is a bit messy, I can't figure out a good way to comment it

2025-07-05 17:53 UTC, KebsCS commented on src/game/server/playermapping.h
> +class CPlayerMapping
Same. The way it's implemented is kind of blocking me from working on this, even though I very much like this pr

2025-07-05 17:53 UTC, SollyBunny commented on src/game/server/entities/character.cpp
> +	// translate id, if we are not in the map of the other person display us as weapon and our hook as a laser
> I think I'd prefer to not show a tee as a weapon if there are more than 64 players in range. That looks weird IMO.
> Hein

> My playermapping sadly doesn't send the closest players only yet, instead due to 0.7 connections which need a whole big netmsg I wanted to reduce the amounts of changes. Thus I only update when a player is in view which wasn't in view before, basically. With more than 64p in view it doesn't map the closests only. Also, iirc there's one bug left where sometimes a player nearby can be overridden, and for some reason he won't be re-inserted until he's out of your view range once (e.g. when using /pause, moving cursor away, resume)
Fokko

This is not an easy thing to fix

2025-07-05 18:21 UTC, SollyBunny commented on src/engine/server.h
> +	 * SendPackMsg, but send to both 0.6 and 0.7 players, not just one of them
> That seems to be what SendPackMsg does already. Why do we need another function?
> Hein

SendPackMsg has different implemtations depending on if T (the msg type) is sixup or not, SendPackMsgForce is a copy of the non sixup version where both sixup and non sixup clients get sent the message regardless of IsSixup(ClientId)

This is used for sending whispers to supported clients (0.7 and DDNet > 217)

The comment `// The translation layer will send the correct 0.6 packet after translating` suggests there is some funky stuff sending 0.7 packets which get untranslated back to 0.6

(TIL whispers can be disabled)

[has given up, it's so messy]

2025-07-05 18:23 UTC, SollyBunny commented
https://github.com/SollyBunny/ddnet/tree/pr-9274

I didn't get very far

2025-07-16 17:34 UTC, ChillerDragon commented on src/engine/shared/protocolglue.cpp
> +	}
It looks like this refactor changes no actual behavior? This is not related to 128 players and does not belong into this pr.

2025-07-16 17:49 UTC, ChillerDragon commented on src/game/server/player.cpp
> +	GameServer()->m_PlayerMapping.ResetSeeOthers(m_ClientId);
``ResetSeeOthers`` is quite heavy including loops and message sending. Would wrap that in a ``if(OldSpectatorId != Id)`` to avoid doing all of that if the id did not even change.

2025-07-17 07:13 UTC, ChillerDragon commented on src/game/server/gamecontext.cpp
> +		Total = LEGACY_MAX_CLIENTS;
Why does the voting code change from VANILLA_MAX_CLIENTS (16) to LEGACY_MAX_CLIENTS (64) when introducing 128 slots? Could someone explain the use case of this code to me :) 

UPDATE: I get it. Scrolling down a bit further there is ``Server()->Kick(ClientId, "Old Teeworlds 0.6 versions are unsupported. Use DDNet client or Teeworlds 0.7");`` So we only accept connections from clients that support at least 64 players which means we can lift the vote max from 16 to 64.

2025-07-17 07:22 UTC, ChillerDragon commented on src/game/server/playermapping.h
> +	struct CPlayerMap
should be class instead of struct

2025-07-17 07:25 UTC, ChillerDragon commented on src/game/server/playermapping.cpp
> +		((CGameControllerDDRace *)m_pPlayerMapping->GameServer()->m_pController)->Teams().SendTeamsState(m_ClientId);
Remove the cast to CGameControllerDDRace.

2025-07-17 07:55 UTC, ChillerDragon commented on src/game/server/gamecontext.h
> +	int GetClientId() const { return m_ClientId; }
Should be just ``ClientId()`` https://github.com/ddnet/ddnet/blob/f8934fc219abb4a2497d8f0085f1da020efc5313/CONTRIBUTING.md#getters-should-not-have-a-get-prefix

2025-07-17 07:58 UTC, ChillerDragon commented on src/game/server/entities/pickup.cpp
> +	GameServer()->SnapPickup(CSnapContext(SnappingClientVersion, Sixup, -1), GetId(), m_Pos, m_Type, m_Subtype, m_Number);
Why is ``-1`` passed as ``ClientId`` and not ``SnappingClient``?

2025-09-02 14:19 UTC, closed without merging

2025-12-30 12:39 UTC, fokkonaut commented on src/game/server/player.cpp
> +	GameServer()->m_PlayerMapping.ResetSeeOthers(m_ClientId);
i think it's important to trigger the reset, and just a call with some loops shouldn't matter on the cpu that much in comparison