Clean up nameplates
ddnet/ddnet pull request #9284
Opened 2024-11-26 16:50 UTC by SollyBunny

## Checklist

- [X] Tested the change ingame
- [X] Provided screenshots if it is a visual change
- [X] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [X] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

## Stuff changed
* Combine friend icon, id and name onto single line
* Combine hook strength icon and id onto single line, now uses clan size
* Directions now use name size
* Allow nameplate size to go to -50 (0 is too big)

## Screenshots

![image](https://github.com/user-attachments/assets/4414143c-53b9-4eca-b216-306a08225a4c)

![image](https://github.com/user-attachments/assets/b5ab2c23-b9b8-41ce-86de-d2d72bec98b5)

![image](https://github.com/user-attachments/assets/f7479257-6fcf-4c99-bd11-77dc435ffd01)

![image](https://github.com/user-attachments/assets/1872505e-42d4-4381-b581-6575305de9d9)

2024-11-26 17:03 UTC, SollyBunny commented on src/base/system.cpp
> +	*UseAfterFree = 1;
Wow really

2024-11-27 05:24 UTC, SollyBunny commented on src/base/system.cpp
> +	*UseAfterFree = 0;
no way

2024-11-27 10:20 UTC, Jupeyy commented on src/base/system.cpp
> +	*UseAfterFree = 0;
Is there any reason you want to add a vulnerable to ddnet?

2024-11-27 11:33 UTC, furo321 reviewed
> Combine hook strength icon and id onto single line, now uses clan size

This should not be scaled by the clan size, that's just confusing.

> Allow nameplate size to go to -50 (0 is too big)

This feels really niche, I don't think that 0 is too small. I tried `-50` and the nameplates are microscopic.

2024-11-27 12:42 UTC, SollyBunny commented on datasrc/content.py
> +container.sprites.Add(Sprite("hook_icon", set_strongweak, 2,0,1,1))
When you have hook strength Id enabled it's to be put next to it. It shouldn't show if hook Ids arent showed

2024-11-27 12:46 UTC, SollyBunny commented
@furo321 

> [Hook strength] should not be scaled by the clan size, that's just confusing.

Other than making a new variable to control it, I didn't know what else to use. Since it appears above the clan using the name size looked off, and I wanted it to scale rather than it being as big as it was

> [0 to -50 nameplate sizes] feels really niche, I don't think that 0 is too small. I tried `-50` and the nameplates are microscopic.

Me and someone in the TClient server wanted to have smaller nameplates, I thought why not let it be microscopic since 1. it's still visible 2. why not let the user do it, its kinda funny 3. the change is visible in the preview

2024-11-27 12:47 UTC, SollyBunny commented on src/game/client/components/nameplates.h
> +	float m_Zoom, m_ZoomClan;
It was laggy when I made it scale by the zoom level, but when I changed it to the target zoom it stopped being laggy. I think this should be a thing, but the current implementation must, from your experience, be wrong

2024-11-27 12:48 UTC, SollyBunny commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(ClNameplatesSize, cl_nameplates_size, 50, -50, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Size of the name plates from 0 to 100%")
since the only thing its a percentage of is some arbritrary point, it would be a bit weird to change it to -50% to 100% (ghasp false origin). removing the `from 0 to 100%` feels better, also since the completion shows the bounds

2024-11-27 13:43 UTC, Jupeyy commented on src/base/system.cpp
> +	*UseAfterFree = 0;
> It's not really a vunrebility as it will never cause a crash

Imagine it like this:
After you called free, a second thread allocates memory and that memory includes your address.
It fills the memory with some bytes.
Then you suddenly write a zero to one of these bytes ^^

So yeah it is a vulnerable, no matter how hard to trigger it, or how safe it is with sanitizers on.

It would be nice if you are more careful for such stuff, on a bad day a maintainer might merge this accidently. Also it's not nice if you just put the `CodeQL` warnings to resolved.

2024-11-27 21:35 UTC, Robyt3 requested changes

2024-11-27 21:35 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +		const vec2 Position = vec2(RightView.x + RightView.w / 2.0f, RightView.y + RightView.h / 2.0f);
Use `RightView.Center()`

2024-11-27 21:35 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +		TextRender()->DeleteTextContainer(ClanTextContainerIndex);
This function call is quite unreadable due to the [Long Parameter List](https://refactoring.guru/smells/long-parameter-list). I would solve this with [Introduce Parameter Object](https://refactoring.guru/introduce-parameter-object).

Also, you don't need to expose this complex function publicly. I'd add a separate public function `CNamePlates::RenderNameplatePreview` specifically for rendering the preview, which would contain all of the code that I selected for this comment.

2024-11-27 21:35 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +		char s_IdBuf[16];
`aIdBuf`

2024-11-27 21:35 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +		float X;
Move the variable declarations closer to their usages. For example `IdWidth` is initialized here but later overridden, so it should be declared further below directly.

2024-11-27 21:35 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +			str_copy(s_IdBuf, " ");
Instead of setting this to one space it should be empty and we shouldn't render any text if IDs are disabled.

2024-11-27 21:35 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +	// ScreenY0 -= 0;
Unrelated change from clang-format. Just remove this line, it's dead code.

2024-11-27 21:35 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +	m_FriendMarkTextContainerIndex.m_Index = -1;
This should be unnecessary, the constructor already initializes the index.

2024-11-27 21:35 UTC, Robyt3 commented on src/game/client/components/nameplates.h
> +	float m_FriendMarkTextContainerWidth;
`m_FriendMark` and `m_FriendMarkColor` don't need to be member variables, they can be local instead.

`m_FriendMarkTextContainerWidth` is unnecessary, call `GetBoundingBoxTextContainer(m_FriendMarkTextContainerIndex)` directly, which is a simple getter and not expensive.

2024-11-27 21:35 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +	STextContainerIndex *Clan, float FontSizeClan,
Use prefix `p` for pointers

2024-11-27 21:35 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +		LeftView.HSplitTop(MarginSmall, nullptr, &LeftView);
This addition section seems unnecessary to me, those are still part of the name plate settings.

2024-11-27 21:35 UTC, Robyt3 commented on src/game/client/components/menus_settings.cpp
> +		GameClient()->m_NamePlates.RenderNameplate(
The settings preview crashes if your clan is empty because then `ClanTextContainerIndex` will be invalid.

2024-11-27 21:54 UTC, SollyBunny commented on src/game/client/components/menus_settings.cpp
> +		TextRender()->DeleteTextContainer(ClanTextContainerIndex);
I wanted to make the code which rendered it in game and in preview the same.

I agree with `RenderNameplatePreview`, but I then would also do `RenderNameplateGame` which takes the args the game provides

2024-11-27 21:54 UTC, SollyBunny commented on src/game/client/components/nameplates.cpp
> +	m_FriendMarkTextContainerIndex.m_Index = -1;
It's gone now anyway

2024-11-27 21:55 UTC, SollyBunny commented on src/game/client/components/nameplates.h
> +	float m_FriendMarkTextContainerWidth;
Sure, this is gone now anyway

2024-11-27 21:57 UTC, SollyBunny commented on src/game/client/components/menus_settings.cpp
> +		LeftView.HSplitTop(MarginSmall, nullptr, &LeftView);
I wanted to seperate them from the settings which are effected by enabling/disabling nameplates (clan, id, and friendmark only show, or rather previously did, when nameplates were enabled).

Ive now sectioned the extras as "Hook strength" and "Directions", it fills the entire space perfectly which is nice

2024-11-28 06:09 UTC, SollyBunny commented on src/game/client/components/nameplates.h
> +	float m_Zoom, m_ZoomClan;
I've removed this and now everything is rendered at the same zoom level. I don't like it but atleast its consistent.

2024-11-28 08:03 UTC, SollyBunny commented on src/base/system.cpp
> +	*UseAfterFree = 0;
@Jupeyy Every time I mark it as resolved it's because I have then removed it again. I don't just press okay :P
Also the program exits directly after. I guess it would be more safe if you did anarray[999999999999999999] x-x

2024-11-28 08:08 UTC, SollyBunny commented on src/base/system.cpp
> +	*UseAfterFree = 0;
```cpp
void dbg_break()
{
#ifdef __SANITIZE_ADDRESS__
	MAYBE_UNUSED volatile char DerefNullptr = *(char *)nullptr;
#endif
#ifdef __GNUC__
	__builtin_trap();
#else
	abort();
#endif
}
```

2024-11-28 11:12 UTC, furo321 reviewed
Currently name plates are always rendered for yourself, which should only be the case if `cl_nameplates_own` is enabled.

2024-11-28 11:13 UTC, furo321 commented on src/game/client/components/nameplates.h
> +	float m_Zoom, m_ZoomClan;
Thanks, that looks a lot better.

2024-11-28 20:02 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +		TextRender()->DeleteTextContainer(NamePlate.m_WeakStrongId.m_TextContainerIndex);
You can also encapsulate this is a function of the nameplate class

2024-11-28 20:06 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +	else // if(ShowDirectionConfig == 0)
Specify this as code instead of as a comment. Then add an `else`-branch with `dbg_assert(false, "ShowDirectionConfig invalid")` to ensure that bugs are caught if this variable has an unexpected value.

Also, you could use a `switch`-statement here.

2024-11-28 20:07 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +	// if (Data.Alpha <= 0.05f) return;
Remove dead code

2024-11-28 20:08 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +		else // if(Data.HookWeakStrong == TRISTATE::NONE)
Same, explicitly check and `dbg_assert` in the `else` branch.

2024-11-28 20:09 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +	if(Data.pClan && (Data.pClan && Data.pClan[0] != '\0'))
Duplicate `Data.pClan` check

2024-11-28 20:09 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +	// if (Data.Alpha <= 0.05f) return;
Remove dead code

2024-11-28 20:16 UTC, Robyt3 commented on src/engine/shared/config_variables.h
>  MACRO_CONFIG_INT(ClNameplatesOwn, cl_nameplates_own, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show own name plate (useful for demo recording)")
This config variable is now unused. The name plate was previously not shown for the local player by default.

2024-11-29 03:52 UTC, SollyBunny commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(ClNameplatesStrongSize, cl_nameplates_strong_size, 30, -50, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Size of strong/weak state icons and numbers")
I think the default size is too large since normally you are only looking at if it's green or red

2024-11-29 04:16 UTC, SollyBunny commented on src/game/client/components/nameplates.cpp
> -void CNamePlates::ResetNamePlates()
My intention was to rename it Nameplates everywhere as that's how config does it

2024-11-29 04:20 UTC, SollyBunny commented on src/game/client/components/nameplates.cpp
> +		TextRender()->DeleteTextContainer(NamePlate.m_WeakStrongId.m_TextContainerIndex);
Would have to take a reference to TextRender

2024-11-29 04:26 UTC, SollyBunny commented on src/game/client/components/nameplates.cpp
> +	// if (Data.Alpha <= 0.05f) return;
Oops I meant to uncomment that and then also ask you about this.
It will attempt to render nameplates which are fully transparent which is a waste of time. I didn't know if I should just do `== 0.0f` or have a threshold

2024-11-30 09:28 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +	// if (Data.Alpha <= 0.05f) return;
The textrender already skips rendering transparent quads so I think this is unnecessary optimization.

2024-11-30 11:50 UTC, SollyBunny commented on src/game/client/components/nameplates.cpp
> +	// if (Data.Alpha <= 0.05f) return;
But it does alot of work other than rendering

2024-11-30 12:07 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +	// if (Data.Alpha <= 0.05f) return;
Compile in release mode and do some benchmarks if you think it matters.

2024-11-30 19:16 UTC, Robyt3 reviewed
Can we render the preview nameplates at the same size as the ingame nameplates? Looks like the preview nameplates are larger than the ingame nameplates, probably because the ingame screen size is different than the UI screen size.

![screenshot_2024-11-30_20-10-57](https://github.com/user-attachments/assets/e54d5819-927d-404b-aee8-638c3a4acfa0)

2024-12-09 19:01 UTC, Robyt3 commented on src/game/client/components/nameplates.cpp
> +	Data.m_InGame = true;
This was probably supposed to be set to `false` here, but that also has no effect on the preview being slightly larger than the ingame rendering. This variable should be removed for now since it's redundant. Maybe we can figure out how to scale the preview correctly in a later PR.

2024-12-10 01:59 UTC, SollyBunny commented on src/game/client/components/nameplates.cpp
> +	Data.m_InGame = true;
Yeah I have... tried for ages, I have gotten no clsoer

2024-12-10 17:09 UTC, Robyt3 approved these changes
Thanks!

2024-12-10 17:31 UTC, merged