Add spectator cursor: third time's the charm
ddnet/ddnet pull request #9292
Opened 2024-11-28 14:40 UTC by TsFreddie

Another branch for #8836

Depends on #9301. I'll rebase accordingly.

## Spectator Cursor
This is a interpolation only method using existing info from `DDNetCharacter NetObj`.

Added settings: `cl_spec_cursor`, ~~`cl_spec_cursor_interpolate`, `cl_spec_cursor_demo`~~.

* The interpolation is using a cubic interpolation using 3 crafted samples. 
* The cursor guarantees to pass through the sample point but everything in between is fake.
* Note that a polynomial_mix function accepting variable sample sizes is used to test different sampling windows, I settled on the 3 sample one.
* Interpolation settings are hardcoded instead configurable to avoid player thinking interp can affect network latency.
* Downside, if you look close enough or use a 0.1x playback speed in demo, hook collision line will mismatch the cursor due to different interpolation method even if you set `cl_spec_cursor_interp 0` due to hook collision line using a linear angle interpolation.

The interpolated visual is targeted to general player base who wants to see mouse movements in demo / specview and not necessarily want to check the exact position, if you want to see the exact data point, set `cl_spec_cursor_interp 0`.

The interpolation assumes the non-changing data points as non-existent instead of a new sample point, this finally gives us the smoothness similar to local mouse cursor.

Demos:
* interp on

https://github.com/user-attachments/assets/3f81e552-27e4-419d-82c1-720f52de3a4e

* interp off (debug mode)

https://github.com/user-attachments/assets/3bc76927-02a9-4874-9864-c84a3d22e02e

* ground truth comparison

https://github.com/user-attachments/assets/3274e89f-78f8-4d2f-b520-cb5e40ad0a5f

In case of dyncam or zooming. A transparent cursor will show at the lineseg-rect intersection point, this does not apply to local player's cursor.
![image](https://github.com/user-attachments/assets/76bfd444-2274-4953-a3cc-b158955bf9fd)

Thanks to everyone involved in the discussion for this feature:
@sjrc6 @gerdoe-jr @heinrich5991 

## Auto Spec Camera
After #9301, now it is possible to grab player's camera settings with a new `DDNetSpectatorInfo` NetObjectEx.

~~Added settings: `cl_spec_use_player_camera`. `cl_spec_use_player_camera 1` essentially turn off the feature and revert back to the behavior with this.~~

The new feature, dubbed Auto Spec Camera, will sync player's camera settings to make spectating (and demo recording) resembles more closely to what the observed player is seeing.

> If you can think of a better name for this feature, please reply your suggestion.

With Auto Spec Camera on, the camera will automatically match observed player's zoom and dyncam settings, this essentially guarantees the cursor is displayed correctly and not off-screen most of the time if observed player is zoomed.

If player zooms manually, the feature will automatically turn off, until player press `zoom` key-bind or right click.

When in spectator view, an indicator will show whether the feature is on or off (only if it is available).
![image](https://github.com/user-attachments/assets/6a03219b-ceec-4cb3-92af-8737969e1457)

When in demo player, an extra button is added to toggle the feature as well.
![image](https://github.com/user-attachments/assets/04dd6cea-12ef-4ecf-a562-a612cdbedff4)

When the feature is on, zoom smoothing and smooth dyncam is ***hardcoded*** to be ON. This is to avoid dyncam spinning player making the screen unwatchable for a player using non-smooth dyncam, since one player's camera setting does not necessarily look good on another player.

No config about auto spec camera will be provided, this feature is essentially a crafted watching experience. Personally i think it is pretty good for recording video too.

Auto Spec Camera will only available if observed player is using a client that supports `Cl_CameraInfo`, and will only available in newly recorded demo with **Follow mode only**.

Here is a demo of me playing Tutorial (badly), while constantly changing zoom and dyncam toggles.
[BadlyPlayingTutorial.zip](https://github.com/user-attachments/files/17966196/BadlyPlayingTutorial.zip)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-11-28 14:54 UTC, def- approved these changes

2024-11-28 18:35 UTC, TsFreddie commented
Reported by @KebsCS on discord.
> with dyncam and non default zoom, the cursor is slightly off
![image](https://github.com/user-attachments/assets/02a3664d-1973-4cda-ad2c-324749dd7750)
![image](https://github.com/user-attachments/assets/e8063793-5793-4f1a-adb4-1cb670333bcc)

2024-11-28 19:09 UTC, KebsCS commented on src/game/client/gameclient.cpp
> +		m_CursorInfo.m_TargetSamplesData[m_CursorInfo.m_NumSamples] = Target;
Visual Studio warns C6386, it's best to add a bounds check (e.g. `m_NumSamples >= 0 && < CURSOR_SAMPLES`) before the array access to ensure safety

2024-11-28 20:38 UTC, Robyt3 requested changes

2024-11-28 20:38 UTC, Robyt3 commented on src/engine/shared/config_variables.h
> +MACRO_CONFIG_INT(ClSpecCursorInterp, cl_spec_cursor_interp, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Interpolate the cursor of spectating player")
I'd spell it out for better usability: `Interp` -> `Interpolate`, `interp` -> `interpolate`

2024-11-28 20:38 UTC, Robyt3 commented on src/game/client/components/hud.cpp
> +	vec2 TargetPos;
Declare the variables directly where they are defined below (twice)

2024-11-28 20:38 UTC, Robyt3 commented on src/game/client/components/hud.cpp
> +		float v = INFINITY;
Can you give the variables more descriptive names? Seems like they are upper/lower bounds.

2024-11-28 20:38 UTC, Robyt3 commented on src/game/client/components/hud.cpp
> +		v = abs(v);
We mostly use the `absolute` function instead of `abs`.

2024-11-28 20:38 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +	const double Tick = Client()->GameTick(g_Config.m_ClDummy);
Do we need to use `double`s for this? The `IntraGameTickSincePrev` function returns a `float` anyway.

2024-11-28 20:38 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +	m_CursorInfo.m_Target = vec2(Result.x, Result.y);
The `Result` variable and `vec2` construction is unnecessary

2024-11-28 20:38 UTC, Robyt3 commented on src/game/client/gameclient.h
> +	struct CCursorInfo
`struct`s should not be used in new code

2024-11-28 20:38 UTC, Robyt3 commented on src/game/client/gameclient.h
> +		vec2 m_TargetSamplesData[CURSOR_SAMPLES];
`a` prefix for arrays

2024-11-28 20:38 UTC, Robyt3 commented on src/game/client/components/hud.cpp
> +		for(int i = 0; i < 4; i++)
Use `std::size` instead of `4`

2024-11-28 20:40 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +		m_CursorInfo.m_TargetSamplesData[m_CursorInfo.m_NumSamples] = Target;
Seems like a false positive, the `m_NumSamples` value should always be `CURSOR_SAMPLES - 1` here

2024-11-29 01:58 UTC, TsFreddie commented on src/game/client/gameclient.cpp
> +	const double Tick = Client()->GameTick(g_Config.m_ClDummy);
DisplayTime need double.

The displaytime after runs low on precision on long running servers causing two sample point have different tick but the same time during int to float conversion.

Have two sample points with the same time causes polynomial mix to return infinite value making the cursor disappear.

I can move the value closer to the usage so it is more clear or is implicit conversion preferred?

2024-11-29 02:02 UTC, TsFreddie commented on src/game/client/gameclient.h
> +	struct CCursorInfo
Do I just change it to class? or should it just be stray variables

2024-11-29 04:40 UTC, TsFreddie commented
> Reported by @KebsCS on discord.
> 
> > with dyncam and non default zoom, the cursor is slightly off
> > ![image](https://private-user-images.githubusercontent.com/3797859/390882681-02a3664d-1973-4cda-ad2c-324749dd7750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NTM0OTIsIm5iZiI6MTczMjg1MzE5MiwicGF0aCI6Ii8zNzk3ODU5LzM5MDg4MjY4MS0wMmEzNjY0ZC0xOTczLTRjZGEtYWQyYy0zMjQ3NDlkZDc3NTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjlUMDQwNjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWVlODk2MTBkNGFmNWQwMzMxZWI4MzgyYTczNzExMmQ0MDdkZGUxNjBkOWVkZDM3NjQ2MTk1NGEzMGY1MGZjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3Zvh_EfsMTTnzTmw2gKtoMrLVbw7ly5Ril-ktI2x_dg)
> > ![image](https://private-user-images.githubusercontent.com/3797859/390882813-e8063793-5793-4f1a-adb4-1cb670333bcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NTM0OTIsIm5iZiI6MTczMjg1MzE5MiwicGF0aCI6Ii8zNzk3ODU5LzM5MDg4MjgxMy1lODA2Mzc5My01NzkzLTRmMWEtYWRiNC0xY2I2NzAzMzNiY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjlUMDQwNjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWJiNmE2YjAwNTA1MjUyNTNlMGZiOTI5NzMzM2Q2YzlkN2M2Njc0MjQ5YWJjZWFjZTM1MjFlYjU5OWQ3ZWZhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qgmn4mV1Tx4lA31iM2jJupUiY_b9MhOwoJzch_DPFbs)

checked the behavior in server and got some bad news #9294

I'd suggest holding out on merging this one until we have a plan for #9294, since that will affect how this PR should be implemented.

We can also merge and change it later when required if that is acceptable too, in this case the dyncam cursor drift is out of scope for this PR.

2024-11-29 04:56 UTC, TsFreddie commented on src/game/client/components/hud.cpp
> +		float v = INFINITY;
did some implementation around this algorithm. u / v is now gone and replaced with a single scalar called `ClampFactor`

2024-11-29 09:45 UTC, Robyt3 commented on src/game/client/gameclient.h
> +	struct CCursorInfo
The container is good for grouping the variables, but we don't want to use `struct`s in new code, only `classes`. See #5338.

2024-11-29 09:49 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +	const double Tick = Client()->GameTick(g_Config.m_ClDummy);
Seems fine to use double then. You could add this explanation as a code comment since we don't use double often unless it's necessary.

2024-11-30 17:12 UTC, TsFreddie commented
Updated description for a new Auto Spec Camera feature following #9301. I will rebase any changes occurred before that PR get merged.

2024-12-04 13:12 UTC, TsFreddie commented
a few changes:

## configs

cutting down on configs: `cl_spec_cursor_interpolate`, `cl_spec_cursor_demo` and `cl_spec_use_player_camera` has been removed.

demo uses the same setting as `cl_spec_cursor`. for people prefer different settings between demo and in game they can manage that themselves. we can add menu options in the future if necessary. 

interpolation is now tied to debug mode, for inspecting raw cursor position, you need to enable debug mode to do so. people wanting to turn off cursor interpolate forever in normal game is now deemed rare and unsupported.

removing `cl_spec_use_player_camera` essentially removes the ability to be able to use dyncam to move camera around when spectating a player, the dyncam control during spectating is clumsy anyway. and people should use freeview to look around for that purpose.

`cl_spec_cursor` is a feature toggle and I believe has it's place. although I can make this feature non-configurable too if @heinrich5991 asks for it.

## behavior

also hides cursor when spectated player is paused, and stopped client from sending camera info when spectating so people zooming in and out to look around does not translate to spectating player. (also global cursor position doesn't need to update when cursor is shown on screen)

2024-12-17 20:55 UTC, Robyt3 requested changes

2024-12-17 20:55 UTC, Robyt3 commented on src/base/math.h
> +	memset(&result, 0, sizeof(T));
`memset` is not defined in the headers included in this file. It would also be better to avoid this function, as it leads to undefined behavior for non-trivial types. See #6256.

2024-12-17 20:55 UTC, Robyt3 commented on src/game/client/components/hud.cpp
> +		str_copy(aBuf, "AUTO");
Copying to the buffer `aBuf` is unnecessary, you can use a `const char *pAutoLabel` instead. Also, this string should be `Localized`.

2024-12-17 20:55 UTC, Robyt3 commented on src/game/client/components/camera.cpp
> +	m_UserZoomTarget = std::pow(CCamera::ZOOM_STEP, g_Config.m_ClDefaultZoom - 10);
Should probably put `std::pow(CCamera::ZOOM_STEP, ZoomAmount - 10.0f)` in a function.

2024-12-17 20:55 UTC, Robyt3 commented on src/game/client/gameclient.cpp
> +		// interpolate cursor positions when not in debug mode
Should always be enabled and not behind a debug check. `debug` is for testing, including testing of this feature, it shouldn't toggle non-debug features.

2024-12-17 20:55 UTC, Robyt3 commented on datasrc/network.py
> +		NetIntAny("m_FollowFactor"),
Should these be lower/upper bounded? At least minimum 0 seems sane so the zoom values are not negative.

2024-12-18 05:27 UTC, TsFreddie commented on src/game/client/components/hud.cpp
> +		str_copy(aBuf, "AUTO");
I forgot to mention it, this works more like a icon instead of text (like most auto mode on actual cameras often get released untranslated on the dial, admittedly they are usually translated digitally in the digital screens now)

but now that i think about it, maybe it is a good idea to let translators decide what to do with it with the mindset of quite a extreme space constraint.

and now again as i'm writing this, it might be a better idea just to auto adapt the icon width. it already needed the width calc for centering anyway. i'll do that instead.

2024-12-18 08:35 UTC, TsFreddie commented on datasrc/network.py
> +		NetIntAny("m_FollowFactor"),
I added add 0 lower bounds for all, and upper bound for deadzone and followfactor. zoom upper bound value after `std:pow` is a bit nonsensical to bound to imo.

I have a bad feeling about the upper bound tho - the deadzone upper bound for `cl_mouse` and `cl_dyncam` variants are different which seems like a huge oversight when, i assume, `cl_mouse` was added? i chose the highest bound which is the `cl_mouse` one but it still feels unsettling.

would love to know how you feel about the upper bounds.

2024-12-18 16:48 UTC, Robyt3 commented on datasrc/network.py
> +		NetIntAny("m_FollowFactor"),
I think it would be fine to remove the upper bounds to allow for larger values in mods and in future versions.

2024-12-18 16:51 UTC, Robyt3 commented on src/base/math.h
> +	memset(&result, 0, sizeof(T));
Using `mem_zero` is also not ideal, it would require including `system.h` whenever including `math.h` in a compilation unit or it doesn't compile. I think a cleaner way would be to pass the initial value for the result, i.e. `0` or `vec2(0, 0)`, as a separate parameter to this function.

2024-12-19 09:03 UTC, merged