Make Aiming Consistent across Zoom Levels
ddnet/ddnet pull request #9301
Opened 2024-11-30 07:54 UTC by TsFreddie

Closes #9294 #8452 #8666

## Problem:
As previously stated in #9298 and #9296. Dyncam (off-character camera) and Zoom combination introduces some extra math that needs to be done to correctly calculate player's actual cursor position.

We also do not want to touch any dyncam implementation (e.g. adjust the camera position after zoom) since that could kill some player habit.

## Implementation:
Since the actual cursor position is rarely used (currently only `tele` and `telecursor`), after some discussion on discord we think it would be better to unscale input target to restore aiming consistency that matches teeworlds. Then we can calculate cursor position for affected commands specifically via other measures. 

This adds a `Cl_CameraInfo` NetMessageEx to send camera info to server. which allows us to calculate the cursor position in server. 
Assuming a player does not adjust dyncam settings continuously, this should roughly send as frequent as `Cl_ShowDistance`, should have pretty minor impact.

For future reference, world cursor position can be calculated with:
```
vec2 CameraOffset = normalize(Target) * maximum(l - CameraDeadzone, 0.0f) * (CameraFollowFactor / 100.0f);
CursorPos = CharacterPos + (Target - CameraOffset) * Zoom + CameraOffset;
```
This adjust the camera offset which is scaled wrong after zoom when using dyncam. (However, if dyncam scaled the value correctly, dyncam can look very weird during zoom and would shift camera's view point around)

## Drawback:
* Will calculate the wrong value during a smooth zoom animation (insignificant)
* Will calculate the wrong value when player is using a very small mouse distance with a zoom (who does that)
* Have some compatibility issue between versions (see below)

## Version compatibility:
* NEW client in OLD server: `telecursor` will send them to the wrong position if zoomed
* OLD client in NEW server: `telecursor` will behave the same as previous versions (only wrong with dyncam + zoom)

## Next step:
This also changes how #9292 should be implemented. But with the new camera info available to server, spectating experience can closely match what spectated player is currently using / seeing. Spectator cursor will be developed in that PR instead.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-11-30 08:06 UTC, def- approved these changes

2024-12-01 20:22 UTC, Robyt3 requested changes

2024-12-02 02:37 UTC, TsFreddie commented on src/game/client/components/camera.cpp
> +
oops, probably a rebase error.

2024-12-02 04:53 UTC, TsFreddie commented on src/game/client/gameclient.cpp
> +		if(Client()->DummyConnected() && !InitializeDummyVital)
I just feel it is more intentional this way to make sure it is easier to understand that it is trying not to send the vital for dummy twice on first connect. but it does seems to made it a more like a mindtwister if you read the method top to bottom.

I followed the review change but also move the dummy vital above, so it is clear why this line has to be `Client()->DummyConnected() && m_LastDummyConnected`.

2024-12-02 04:54 UTC, TsFreddie commented
I also made CameraInfo send a little bit sooner than ShowDistance when zooming in

2024-12-02 15:27 UTC, Robyt3 approved these changes

2024-12-02 15:28 UTC, Robyt3 commented
LGTM, now has conflicts though.

2024-12-02 16:16 UTC, merged