Add dangerous command protection
ddnet/ddnet pull request #9351
Opened 2024-12-06 05:26 UTC by SollyBunny

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

Closes: #9056

![image](https://github.com/user-attachments/assets/626101ab-805b-47e1-952e-f101c7ffb7d2)

2024-12-06 07:46 UTC, def- commented
I think this makes life too hard, but ok if others think it's useful

2024-12-06 08:00 UTC, fokkonaut commented
> I think this makes life too hard, but ok if others think it's useful

I think this should rather be a flag, like sensitive.

2024-12-06 19:27 UTC, Robyt3 requested changes
I agree, dangerous commands should be registered with a new `CFGFLAG_DANGEROUS`.

2024-12-06 21:18 UTC, SollyBunny commented
Need to make `echo;quit` be blocked as well

2024-12-06 22:55 UTC, sjrc6 commented
I don't think minimize or kill should be dangerous. 

Honestly even the ones that quit the client don't seem that necessary. The difference in danger between losing all your binds and the client closing is pretty big.

2024-12-07 04:33 UTC, TsFreddie commented
dangerous commands should automatically be allowed when loading the initial config file (not `exec`). e.g. `unbindall` is there to unbind default binds so player's unbind in menu can be saved.

also are `quit / disconnect` commands there to prevent trolling or protect accidental usage without knowing what it was for?

2024-12-07 06:44 UTC, sjrc6 commented
> dangerous commands should automatically be allowed when loading the initial config file (not `exec`). e.g. `unbindall` is there to unbind default binds so player's unbind in menu can be saved.

this only applies to typing it manually

2024-12-09 19:09 UTC, fokkonaut commented
> I agree, dangerous commands should be registered with a new `CFGFLAG_DANGEROUS`.

CMDFLAG_DANGEROUS

2024-12-09 19:21 UTC, Robyt3 commented
> > I agree, dangerous commands should be registered with a new `CFGFLAG_DANGEROUS`.
> 
> CMDFLAG_DANGEROUS

We had a short discussion about that on Discord previously, I don't really see the need to differenciate. Otherwise, flags like `CFGFLAG_CLIENT` and `CFGFLAG_SERVER` should also be `CMDFLAG_*` since they are used for commands and config variables (and config variables are commands).

2024-12-09 19:33 UTC, heinrich5991 commented
Do we really want to protect users from using the console? Perhaps the console itself should be unbound by default instead? You can do all sorts of annoying stuff in there if a gullible user types whatever you want in there…

2024-12-09 19:39 UTC, fokkonaut commented
> > > I agree, dangerous commands should be registered with a new `CFGFLAG_DANGEROUS`.
> > 
> > 
> > CMDFLAG_DANGEROUS
> 
> We had a short discussion about that on Discord previously, I don't really see the need to differenciate. Otherwise, flags like `CFGFLAG_CLIENT` and `CFGFLAG_SERVER` should also be `CMDFLAG_*` since they are used for commands and config variables (and config variables are commands).

Ah, okay didn't follow that. We should rename other flags aswell then and keep CFG prefix

2025-05-05 13:58 UTC, closed without merging