Add more general `IntersectEntity()`
ddnet/ddnet pull request #9386
Opened 2024-12-14 09:49 UTC by ChillerDragon

Solves 16 year old todo comment

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

2024-12-14 17:16 UTC, Kaffeine commented
In a case if you're interested, I had to implement a similar generic IntersectEntity() for Infclass but I had to use a filter function because CanCollide() is not flexible enough (e.g. I need the same (piercing, long lasting) laser to hit each target max once; it could be handled on the laser side but filter function is *much* cleaner).
Reference: [infclass/gameworld.cpp#L227-L259](https://github.com/infclass/teeworlds-infclassR/blob/570c4f4fffb964914bc3b4ded8ec43f400212c55/src/game/server/gameworld.cpp#L227-L259)
Note: FilterFunctions don't use dynamic memory, there are ways to use them without std::function or capturing lambdas.

I also implemented types registration and don't have to modify GameWorld code to add new CEntity subclass. Commit for reference&inspiration: [https://github.com/infclass/teeworlds-infclassR/commit/90ee01b7a1d58d18b49ab0f296166254b8c9aa53](https://github.com/infclass/teeworlds-infclassR/commit/90ee01b7a1d58d18b49ab0f296166254b8c9aa53#diff-fd2ded44540051566ed085a5fe6794087ec79190e6858327cda15619367e52c0)

2024-12-30 11:21 UTC, Robyt3 requested changes

2024-12-30 11:21 UTC, Robyt3 commented on src/game/client/prediction/gameworld.cpp
> +	CEntity *pClosest = 0;
`nullptr`

2024-12-30 11:21 UTC, Robyt3 commented on src/game/server/gameworld.h
> +	 * @return Pointer to the closest hit or NULL of there is no intersection.
`nullptr` (you can also use backticks in doxygen comments)

2024-12-30 11:21 UTC, Robyt3 commented on src/game/server/gameworld.h
> +	 * @param Radius How for from the line the CCharacter is allowed to be.
`@link CEntity @endlink`

2024-12-30 11:21 UTC, Robyt3 commented on src/game/server/gameworld.h
> +	 *
Parameters `CollideWith` and `pThisOnly` are missing.

2024-12-30 11:21 UTC, Robyt3 commented on src/game/server/gameworld.h
> +		Function: IntersectCharacter
Please update the entire comment based on the comment of the `IntersectEntity` function. It also says `made for types lasers=1 and doors=0` here which is probably outdated.

2024-12-30 11:21 UTC, Robyt3 commented on src/game/server/gameworld.cpp
> +	CEntity *pClosest = 0;
`nullptr`

2024-12-30 12:40 UTC, Robyt3 approved these changes

2024-12-30 13:05 UTC, def- approved these changes

2024-12-30 13:17 UTC, heinrich5991 commented
Why do we want this? It's unused code in DDNet.

If we want this, please add a test so that we can at least be sure that it's not entirely broken right now and doesn't get broken by future changes.

2024-12-30 13:18 UTC, heinrich5991 commented
I guess it was already approved.

2024-12-30 13:20 UTC, heinrich5991 commented on src/game/client/prediction/entity.h
> +	virtual bool CanCollide(int ClientId) { return true; }
Wait, this doesn't make sense. Why can each projectile collide with every client ID?

2024-12-30 13:20 UTC, heinrich5991 commented
If we want this, please add a test to check that it's not buggy (as it apparently is right now, at least as far as I understand it, see my review comment).

2024-12-30 15:36 UTC, ChillerDragon commented on src/game/client/prediction/entity.h
> +	virtual bool CanCollide(int ClientId) { return true; }
Indeed. Good catch fixed.

2024-12-30 15:48 UTC, ChillerDragon commented
Not sure how to add a test for gameworld. It has so many dependencies.

2025-01-05 07:36 UTC, ChillerDragon commented
@heinrich5991 do you have an idea on how to write tests for gameworld? Do I start linking the entire code base into the tests to get gameworld and its dependencies compiled? Or is there some more light weight way?

2025-01-06 14:35 UTC, heinrich5991 commented
You'll need to link more stuff to get access to the game world, yes.

2025-02-15 13:28 UTC, ChillerDragon commented
Added a bunch of tests for ``IntersectEntity()`` none involving CanCollide because setting ddrace teams requires a controller which does not exist in the test code.

2025-03-02 16:53 UTC, ChillerDragon commented
Any updates here?

2025-03-04 13:50 UTC, edg-l approved these changes
looks good but i would wait on other opinions, maybe @Robyt3

2025-03-04 21:18 UTC, Robyt3 approved these changes

2025-03-05 07:06 UTC, merged

2025-03-05 12:26 UTC, ChillerDragon commented
Nice thanks! Sorry for being pushy here but I am really happy this got finally in :partying_face: