Add chunk header packer test
ddnet/ddnet pull request #9417
Opened 2024-12-21 15:41 UTC by ChillerDragon

2024-12-22 10:24 UTC, ChillerDragon commented
Ok so to clarify what this is about. Well first of all its a test making code refactors saver and yes that chunk packing code already has been refactored a few times.

But this pr is basically just a side quest of me trying to better understand the 0.6 protocol. When testing my own packer implementation I thought that it was bugged. So I compared the values with ddnet and to my surprise they seem to match. Thats why I added the ``// this is weird`` comment.

According to my understanding and the [libtw2 docs](https://github.com/heinrich5991/libtw2/blob/5da5e3ec46cdc121f41e1cf07348c49055fbd45c/doc/packet.md) a vital chunk header has 3 bytes.
The the sequence number takes the entire third byte and shares the second byte with the size.

In the second test you can clearly see size 0 and sequence 5 even are readable when just looking at the hexdump.

```
0x40, 0x00, 0x05
```

First byte 0x40 is the flags and then 0x00 is size 0 and no sequence number leaking into it.
Then the third byte is only the sequence number.

So when I increased the sequence number to 255 (0xff) and it set the second byte I got really confused.

```
0x40, 0x30, 0xff
```

0x40 is still the flags and 0x30 has to be the sequence number because size is still 0 and 0xff has to be the sequence number too because thats the only value put into the third byte.
Now the question is if 0xff is already representing 255 what is the 0x30 for? You might be thinking that there is one more bit for the sign and the maximum value is not actually 255 but 127. But 127 also leaks into the second byte.
In fact 63 is the last sequence number that only sets bits in the third byte. From 64 on wards it seems to use more bits than it needs.

2024-12-22 10:29 UTC, ChillerDragon commented
Also I don't understand this shift.
https://github.com/ddnet/ddnet/blob/004729532f89465851058a3df8210878dc080932/src/engine/shared/network.cpp#L361

If the second byte is 4 bits sequence followed by 4 bits size. Why does the sequence have to be shifted by 2?

2025-02-24 22:04 UTC, Robyt3 commented on src/test/chunk_header.cpp
> +	Header.Pack(pData);
Also check the return values of the `Pack` calls.

2025-02-25 13:42 UTC, ChillerDragon commented on src/test/chunk_header.cpp
> +	Header.Pack(pData);
Thought it was boring but sure can do. I now ensure all of the tests increment the pointer by 3.

2025-02-26 09:12 UTC, ChillerDragon commented
Interesting thanks @Robyt3 

I would love to get rid of the split code. It confuses me. Could you open a pr with that @Robyt3?

2025-03-09 13:59 UTC, ChillerDragon commented
!ddnetbot ready

2025-03-09 22:19 UTC, Robyt3 requested changes

2025-03-09 22:19 UTC, Robyt3 commented on src/test/chunk_header.cpp
> +	EXPECT_EQ(pData[2], 0xff);
This is currently mostly duplicate code. Could you extract a template function with arguments `const CNetChunkHeader &Header, unsigned char aPacked[N]` and `size_t N` being a template parameter? That would also make it easier to add more tests without the vital flag and with different sizes.

2025-03-09 23:50 UTC, ChillerDragon commented on src/test/chunk_header.cpp
> +	EXPECT_EQ(pData[2], 0xff);
Do we need more test cases? I thought tests should be duplicated simple and with little abstraction.

But yea if you insist will do it tomorrow.

2025-03-10 13:09 UTC, ChillerDragon commented on src/test/chunk_header.cpp
> +	EXPECT_EQ(pData[2], 0xff);
I did a thing. Not sure if that is what you envisioned. It now for sure if more fun to add more tests. And I personally also tend to have the urge to always refactor tests into being super dry. But I have the feeling its a bad style. Anyways your call. I have no hard feelings here for me either way works :shrug:

2025-03-10 17:33 UTC, Robyt3 commented on src/test/chunk_header.cpp
> +	EXPECT_EQ(pData[2], 0xff);
Thanks, that's what I had in mind. Test code is still code and the same general design principles should apply.

I also want to use this as a basis to add more tests for https://github.com/ddnet/ddnet/pull/9417#issuecomment-2683300949.

2025-03-10 17:34 UTC, Robyt3 approved these changes

2025-03-10 17:56 UTC, merged